# DERS-X — paper-aligned, resumable end-to-end notebook

This notebook replaces the uploaded IEMOCAP-only scaffold. It implements the manuscript pipeline from data parsing through final tables and figures:

- strict speaker-independent IEMOCAP LOSO with dialog isolation and train/validation/calibration partitions;
- fold-only target standardization and quartile thresholds;
- wav2vec 2.0 Base, learned 12-layer scalar mixture, 256-dimensional projection, and attentive statistics pooling;
- DistilBERT-base-uncased with 128 wordpieces and a learned `[EMPTY]` token;
- four-head bidirectional cross-modal attention, residual normalization, joint continuous regression and masked nine-class emotion supervision;
- post-hoc temperature scaling, utterance/dialog metrics, fold-average and pooled reporting;
- bidirectional IEMOCAP ↔ MSP-Podcast transfer using the paper's exact score `z_arousal - 0.5*z_valence`;
- fusion, regression-head, encoder, and dialog-context studies;
- SNR, AMR/VoIP, transcript-WER, combined degradation, modality comparisons, and an attention-derived reliability diagnostic;
- atomic checkpoints, mid-epoch resume, JSONL/console logs, GPU telemetry, task status, and a hard wall-clock guard.

## Audit verdict on the uploaded notebook

| Paper requirement | Uploaded notebook | This replacement |
|---|---|---|
| MSP-Podcast bidirectional transfer | Replaced with within-IEMOCAP transfer | Implemented with a flexible official-metadata/manifest loader |
| Analytic IEMOCAP sample | Parsed 10,039 rows and mapped `xxx`/no-agreement to `oth` | Drops no-consensus rows and supports an exact utterance-ID manifest; never invents the paper's unexplained 5,479-row subset |
| Resume after interruption | Final model weights only | Model, optimizer, scheduler, AMP scaler, epoch/batch, early-stopping state, RNG, target statistics, and task status |
| 24-hour control | None | Persistent campaign deadline and graceful pause/checkpoint |
| Attention shift | Representation-norm proxy | Entropy/confidence derived from the actual two cross-attention maps, then normalized across modalities |
| Dialog context ablation | Not implemented | Explicit lightweight contextual refiner, clearly marked as an operationalization because the paper does not define this architecture |
| Regression/encoder ablations | Missing | Implemented, with optional GloVe path and log-Mel CNN/TF-IDF baselines |
| Result generation | Included manuscript numbers as plotting defaults | No manuscript score is used as computed output; figures read generated CSV files only |
| Literature comparison (Table 16) | Static manuscript reference values | Preserved only as explicitly external, non-recomputed context; the DERS-X row is filled from real predictions |

## Important reproducibility boundary

The manuscript reports **5,479 IEMOCAP utterances**, but it does not provide an utterance-ID list or a filtering rule that deterministically produces that subset. In `paper_exact` mode this notebook requires an exact subset manifest before it will label a run as manuscript-reproducible. Without that manifest it can still run a transparent, reproducible benchmark on the filtered official corpus, but the sample is not identical to the manuscript.

The manuscript also does not define (a) the architecture behind its “dialog context” ablation or (b) how two separate cross-attention paths become one 55/45 modality share. This notebook provides explicit, logged operational definitions instead of silently fabricating them.

## Runtime profiles

- `paper_exact`: exact paper hyperparameters, all 10 LOSO speakers and seeds 13/29/47, full encoder fine-tuning, and the complete experiment registry. It is implemented, resumable, and method-faithful, but **cannot honestly be guaranteed to finish within 24 hours on one RTX 3060**.
- `rtx3060_24h` (default): hard 24-hour campaign, effective batch 8 through gradient accumulation, AMP/TF32, length bucketing, waveform caching, selective top-layer fine-tuning, and breadth-first task ordering. Every table records its actual scope; this mode never labels reduced-scope results as the exact paper protocol.
- `smoke`: fast parser/model/split validation.

Edit paths and choose the profile in the configuration cell. Run the notebook top-to-bottom. A restart before the campaign deadline resumes automatically. After a 24-hour campaign expires, set `reset_campaign_clock=True` for one launch to begin another 24-hour window; the existing fold checkpoints and task registry are reused, then set it back to `False`.


## Build validation performed before delivery

The notebook was validated without the private corpora or an RTX GPU: every code cell passed AST/nbformat validation; synthetic forward passes passed for audio-only, text-only, early fusion, late-average, and cross-attention modes; actual cross-attention shares summed to one; zero-layer freezing and complete checkpoint round-trip passed; IEMOCAP/MSP parsers, dialog/pooled metrics, degradation table schemas, and automatic Tables 1–22/Figures 1–5 generation passed on synthetic artifacts. These tests establish implementation integrity, not the paper's empirical scores.

## 0. Optional dependency installation

The cell below installs only missing Python packages. It deliberately does **not** replace an existing CUDA-enabled PyTorch build. Install the correct CUDA PyTorch build from the official selector before running training.

In [1]:
INSTALL_MISSING = False

if INSTALL_MISSING:
    import importlib.util, subprocess, sys
    package_map = {
        "transformers": "transformers>=4.42,<5",
        "soundfile": "soundfile>=0.12",
        "sklearn": "scikit-learn>=1.3",
        "scipy": "scipy>=1.10",
        "pandas": "pandas>=2.0",
        "matplotlib": "matplotlib>=3.7",
        "tqdm": "tqdm>=4.66",
        "psutil": "psutil>=5.9",
        "pyarrow": "pyarrow>=14",
    }
    missing = [spec for module, spec in package_map.items() if importlib.util.find_spec(module) is None]
    if missing:
        subprocess.check_call([sys.executable, "-m", "pip", "install", *missing])
    if importlib.util.find_spec("torch") is None:
        raise RuntimeError("PyTorch is missing. Install a CUDA-enabled build from the official PyTorch selector first.")

In [2]:
from __future__ import annotations

import os, re, math, json, time, copy, random, hashlib, logging, platform, subprocess
import tempfile, shutil, contextlib, warnings, csv, traceback
from dataclasses import dataclass, asdict, replace, field
from pathlib import Path
from typing import Any, Dict, Iterable, Iterator, List, Mapping, Optional, Sequence, Tuple
from collections import defaultdict

import numpy as np
import pandas as pd
import soundfile as sf
import psutil

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader, Sampler

from tqdm.auto import tqdm
from scipy.signal import resample_poly
from scipy.stats import pearsonr, spearmanr
from sklearn.metrics import (
    accuracy_score, cohen_kappa_score, classification_report, f1_score,
    mean_absolute_error, mean_squared_error, recall_score,
)
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import Ridge

from transformers import (
    AutoFeatureExtractor, AutoTokenizer, DistilBertModel, Wav2Vec2Model,
    get_linear_schedule_with_warmup,
)

import matplotlib.pyplot as plt

warnings.filterwarnings("once")
print("Python:", platform.python_version())
print("PyTorch:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())

Python: 3.11.14
PyTorch: 2.9.1+cu128
CUDA available: True

## 1. Configuration

The defaults target the stated Xeon E5-2683 v5, 64 GB RAM, and RTX 3060 12 GB system. `effective_batch_size=8` preserves the paper's optimization batch through gradient accumulation even when the GPU micro-batch is 1 or 2.

In [3]:
EMOTION_LABELS = ("ang", "hap", "neu", "sad", "exc", "fea", "fru", "oth", "sur")
EMOTION_TO_ID = {label: i for i, label in enumerate(EMOTION_LABELS)}
ID_TO_EMOTION = {i: label for label, i in EMOTION_TO_ID.items()}
DISTRESS_LABELS = (0, 1, 2, 3)
DISTRESS_NAMES = ("low", "mild", "high", "severe")

PAPER_IEMOCAP_COUNTS = {
    "ang": 1103, "hap": 648, "neu": 1708, "sad": 1084,
    "exc": 429, "fea": 168, "fru": 276, "oth": 42, "sur": 21,
}

@dataclass
class DERSXConfig:
    # Profile and paths
    profile: str = "rtx3060_24h"  # paper_exact | rtx3060_24h | smoke
    iemocap_root: str = str(Path.home() / "Downloads" / "IEMOCAP")
    iemocap_subset_manifest: str = ""  # CSV/TXT containing exact utterance_id values for the paper's 5,479 rows
    msp_root: str = str(Path.home() / "Downloads" / "MSP-Podcast")
    msp_metadata_csv: str = ""          # optional; auto-discovered when blank
    msp_subset_manifest: str = ""       # optional exact 24,500-row ID manifest
    glove_path: str = ""                # optional GloVe text file for that ablation
    noise_root: str = ""                # optional background-noise WAV directory; Gaussian fallback is logged
    output_root: str = str(Path.cwd() / "runs" / "dersx_paper_aligned")
    campaign_name: str = "campaign_01"
    reset_campaign_clock: bool = False

    # Hard wall-clock/resume
    deadline_hours: float = 24.0
    deadline_guard_minutes: float = 10.0
    checkpoint_every_optimizer_steps: int = 100
    log_every_optimizer_steps: int = 25

    # Corpus rules
    expected_iemocap_rows: int = 5479
    expected_msp_rows: int = 24500
    drop_iemocap_no_consensus: bool = True
    map_iemocap_disgust_to_other: bool = True
    msp_agreement_sd_threshold: float = 0.30
    msp_test_partition: str = "Test1"
    fallback_text: str = "[EMPTY]"

    # Paper architecture
    audio_model_name: str = "facebook/wav2vec2-base"
    text_model_name: str = "distilbert-base-uncased"
    sample_rate: int = 16000
    max_text_len: int = 128
    latent_dim: int = 256
    fusion_heads: int = 4
    dropout: float = 0.2
    head_hidden: int = 128
    wav2vec_layers_to_mix: int = 12
    fusion_mode: str = "cross_attention"  # cross_attention | audio_only | text_only | early_concat | late_average
    regression_head: str = "two_gelu"     # linear | one_relu | two_gelu | three_gelu
    audio_backbone: str = "wav2vec2"      # wav2vec2 | logmel_cnn

    # Paper optimization
    effective_batch_size: int = 8
    micro_batch_size: int = 2
    max_epochs: int = 20
    patience: int = 3
    lr_encoders: float = 1e-5
    lr_new: float = 1e-4
    weight_decay: float = 0.01
    warmup_ratio: float = 0.10
    grad_clip: float = 1.0
    lambda_emo: float = 1.0
    lambda_reg: float = 0.5
    seeds: Tuple[int, ...] = (13, 29, 47)

    # RTX 3060 throughput controls
    amp: bool = True
    tf32: bool = True
    cudnn_benchmark: bool = True
    gradient_checkpointing: bool = False
    freeze_wav2vec_feature_encoder: bool = True
    audio_unfreeze_last_n: int = 4
    text_unfreeze_last_n: int = 2
    num_workers: int = 4
    prefetch_factor: int = 2
    pin_memory: bool = True
    persistent_workers: bool = True
    cache_waveforms: bool = True
    precache_iemocap_waveforms: bool = True
    precache_threads: int = 8
    bucket_size_multiplier: int = 40
    fused_adamw: bool = True
    compile_model: bool = False

    # Evaluation
    ece_bins: int = 15
    strict_dialog_loso: bool = True
    save_fused_embeddings: bool = False
    attention_diagnostics: bool = True

    # Scope used by the 24-hour profile. All reduced scope is written into result files.
    budget_primary_seed: int = 13
    budget_representative_fold: str = "Ses01F"
    budget_seed_check_folds: Tuple[str, ...] = ("Ses01F", "Ses03M", "Ses05M")
    budget_degradation_folds: Tuple[str, ...] = ("Ses01F",)
    budget_ablation_folds: Tuple[str, ...] = ("Ses01F",)

    # Execution controls
    run_experiment: bool = True
    run_cross_corpus: bool = True
    run_degradation: bool = True
    run_ablations: bool = True
    run_context_ablation: bool = True
    force_recompute: bool = False


def apply_profile(base: DERSXConfig) -> DERSXConfig:
    p = base.profile.lower().strip()
    if p == "paper_exact":
        return replace(
            base,
            micro_batch_size=1,  # effective batch remains 8 via accumulation; safest for 12 GB
            max_epochs=20, patience=3,
            gradient_checkpointing=True,
            audio_unfreeze_last_n=12,
            text_unfreeze_last_n=6,
            num_workers=0 if os.name == "nt" else min(8, max(2, (os.cpu_count() or 8)//4)),
            save_fused_embeddings=True,
        )
    if p == "rtx3060_24h":
        windows_notebook = os.name == "nt"
        return replace(
            base,
            micro_batch_size=max(1, min(base.micro_batch_size, 2)),
            max_epochs=min(base.max_epochs, 12),
            patience=min(base.patience, 2),
            gradient_checkpointing=False,
            audio_unfreeze_last_n=min(base.audio_unfreeze_last_n, 4),
            text_unfreeze_last_n=min(base.text_unfreeze_last_n, 2),
            # Windows/Jupyter multiprocessing workers frequently fail to pickle notebook state.
            # Caching, bucketing, pinned transfer, AMP and accumulation still drive the GPU.
            num_workers=0 if windows_notebook else min(6, max(2, (os.cpu_count() or 8)//4)),
            persistent_workers=False if windows_notebook else base.persistent_workers,
            save_fused_embeddings=False,
        )
    if p == "smoke":
        return replace(
            base, deadline_hours=1.0, micro_batch_size=1, effective_batch_size=2,
            max_epochs=1, patience=1, audio_unfreeze_last_n=1, text_unfreeze_last_n=1,
            num_workers=0, precache_iemocap_waveforms=False, run_cross_corpus=False, run_degradation=False,
            run_ablations=False, run_context_ablation=False,
        )
    raise ValueError(f"Unknown profile: {base.profile}")

cfg = apply_profile(DERSXConfig())
assert cfg.effective_batch_size % cfg.micro_batch_size == 0, "effective_batch_size must be divisible by micro_batch_size"
print(json.dumps(asdict(cfg), indent=2, default=str))

{
  "profile": "rtx3060_24h",
  "iemocap_root": "C:\\Users\\HaseebWajid\\Downloads\\IEMOCAP",
  "iemocap_subset_manifest": "",
  "msp_root": "C:\\Users\\HaseebWajid\\Downloads\\MSP-Podcast",
  "msp_metadata_csv": "",
  "msp_subset_manifest": "",
  "glove_path": "",
  "noise_root": "",
  "output_root": "C:\\Users\\HaseebWajid\\Downloads\\runs\\dersx_paper_aligned",
  "campaign_name": "campaign_01",
  "reset_campaign_clock": false,
  "deadline_hours": 24.0,
  "deadline_guard_minutes": 10.0,
  "checkpoint_every_optimizer_steps": 100,
  "log_every_optimizer_steps": 25,
  "expected_iemocap_rows": 5479,
  "expected_msp_rows": 24500,
  "drop_iemocap_no_consensus": true,
  "map_iemocap_disgust_to_other": true,
  "msp_agreement_sd_threshold": 0.3,
  "msp_test_partition": "Test1",
  "fallback_text": "[EMPTY]",
  "audio_model_name": "facebook/wav2vec2-base",
  "text_model_name": "distilbert-base-uncased",
  "sample_rate": 16000,
  "max_text_len": 128,
  "latent_dim": 256,
  "fusion_heads": 4,
  "dropout": 0.2,
  "head_hidden": 128,
  "wav2vec_layers_to_mix": 12,
  "fusion_mode": "cross_attention",
  "regression_head": "two_gelu",
  "audio_backbone": "wav2vec2",
  "effective_batch_size": 8,
  "micro_batch_size": 2,
  "max_epochs": 12,
  "patience": 2,
  "lr_encoders": 1e-05,
  "lr_new": 0.0001,
  "weight_decay": 0.01,
  "warmup_ratio": 0.1,
  "grad_clip": 1.0,
  "lambda_emo": 1.0,
  "lambda_reg": 0.5,
  "seeds": [
    13,
    29,
    47
  ],
  "amp": true,
  "tf32": true,
  "cudnn_benchmark": true,
  "gradient_checkpointing": false,
  "freeze_wav2vec_feature_encoder": true,
  "audio_unfreeze_last_n": 4,
  "text_unfreeze_last_n": 2,
  "num_workers": 0,
  "prefetch_factor": 2,
  "pin_memory": true,
  "persistent_workers": false,
  "cache_waveforms": true,
  "precache_iemocap_waveforms": true,
  "precache_threads": 8,
  "bucket_size_multiplier": 40,
  "fused_adamw": true,
  "compile_model": false,
  "ece_bins": 15,
  "strict_dialog_loso": true,
  "save_fused_embeddings": false,
  "attention_diagnostics": true,
  "budget_primary_seed": 13,
  "budget_representative_fold": "Ses01F",
  "budget_seed_check_folds": [
    "Ses01F",
    "Ses03M",
    "Ses05M"
  ],
  "budget_degradation_folds": [
    "Ses01F"
  ],
  "budget_ablation_folds": [
    "Ses01F"
  ],
  "run_experiment": true,
  "run_cross_corpus": true,
  "run_degradation": true,
  "run_ablations": true,
  "run_context_ablation": true,
  "force_recompute": false
}

## 2. Runtime, logging, hardware utilization, and persistent deadline

`run.log`, `metrics.jsonl`, `task_status.json`, and GPU snapshots are written continuously. The campaign start time persists across kernel restarts. Set `reset_campaign_clock=True` only when intentionally starting a new 24-hour campaign; existing model checkpoints remain reusable.

In [4]:
def atomic_json_dump(payload: Mapping[str, Any], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(json.dumps(payload, indent=2, default=str), encoding="utf-8")
    os.replace(tmp, path)


def atomic_torch_save(payload: Mapping[str, Any], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    torch.save(dict(payload), tmp)
    os.replace(tmp, path)


def stable_hash(payload: Any) -> str:
    blob = json.dumps(payload, sort_keys=True, default=str).encode("utf-8")
    return hashlib.sha256(blob).hexdigest()[:16]


RUN_DIR = Path(cfg.output_root).expanduser().resolve() / cfg.campaign_name
RUN_DIR.mkdir(parents=True, exist_ok=True)
LOG_PATH = RUN_DIR / "run.log"
METRICS_JSONL = RUN_DIR / "metrics.jsonl"
TASK_STATUS_PATH = RUN_DIR / "task_status.json"
CAMPAIGN_STATE_PATH = RUN_DIR / "campaign_state.json"

logger = logging.getLogger("DERSX")
logger.setLevel(logging.INFO)
logger.handlers.clear()
fmt = logging.Formatter("%(asctime)s | %(levelname)s | %(message)s", datefmt="%Y-%m-%d %H:%M:%S")
stream_handler = logging.StreamHandler()
stream_handler.setFormatter(fmt)
file_handler = logging.FileHandler(LOG_PATH, encoding="utf-8")
file_handler.setFormatter(fmt)
logger.addHandler(stream_handler)
logger.addHandler(file_handler)


def log_metric(event: str, **payload: Any) -> None:
    record = {"time": time.time(), "event": event, **payload}
    with METRICS_JSONL.open("a", encoding="utf-8") as f:
        f.write(json.dumps(record, default=str) + "\n")


@dataclass
class CampaignBudget:
    state_path: Path
    hours: float
    guard_minutes: float
    reset: bool = False

    def __post_init__(self) -> None:
        now = time.time()
        if self.state_path.exists() and not self.reset:
            state = json.loads(self.state_path.read_text(encoding="utf-8"))
            self.started_at = float(state["started_at"])
        else:
            self.started_at = now
        self.deadline = self.started_at + self.hours * 3600.0
        atomic_json_dump({
            "started_at": self.started_at,
            "deadline": self.deadline,
            "hours": self.hours,
            "profile": cfg.profile,
        }, self.state_path)

    @property
    def remaining_seconds(self) -> float:
        return max(0.0, self.deadline - time.time())

    def should_stop(self, extra_guard_seconds: float = 0.0) -> bool:
        guard = self.guard_minutes * 60.0 + extra_guard_seconds
        return self.remaining_seconds <= guard

    def summary(self) -> Dict[str, Any]:
        return {
            "started_at": time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(self.started_at)),
            "deadline": time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(self.deadline)),
            "remaining_hours": self.remaining_seconds / 3600.0,
        }


budget = CampaignBudget(CAMPAIGN_STATE_PATH, cfg.deadline_hours, cfg.deadline_guard_minutes, cfg.reset_campaign_clock)


def seed_everything(seed: int) -> None:
    os.environ["PYTHONHASHSEED"] = str(seed)
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def seed_worker(worker_id: int) -> None:
    seed = torch.initial_seed() % (2**32)
    random.seed(seed)
    np.random.seed(seed)


def configure_runtime() -> None:
    cpu_count = os.cpu_count() or 8
    torch.set_num_threads(min(16, cpu_count))
    try:
        torch.set_num_interop_threads(min(4, cpu_count))
    except RuntimeError:
        pass
    if torch.cuda.is_available():
        if cfg.tf32:
            torch.set_float32_matmul_precision("high")
            torch.backends.cuda.matmul.allow_tf32 = True
            torch.backends.cudnn.allow_tf32 = True
        torch.backends.cudnn.benchmark = bool(cfg.cudnn_benchmark)
        torch.backends.cudnn.deterministic = False


def gpu_snapshot() -> Dict[str, Any]:
    snap: Dict[str, Any] = {}
    if torch.cuda.is_available():
        snap.update({
            "device": torch.cuda.get_device_name(0),
            "allocated_gb": torch.cuda.memory_allocated(0) / 2**30,
            "reserved_gb": torch.cuda.memory_reserved(0) / 2**30,
            "max_allocated_gb": torch.cuda.max_memory_allocated(0) / 2**30,
        })
        try:
            out = subprocess.check_output(
                ["nvidia-smi", "--query-gpu=utilization.gpu,memory.used,memory.total,temperature.gpu,power.draw", "--format=csv,noheader,nounits"],
                text=True, stderr=subprocess.DEVNULL,
            ).strip()
            if out:
                values = [x.strip() for x in out.split(",")]
                snap.update({"gpu_util_pct": values[0], "gpu_mem_used_mb": values[1], "gpu_mem_total_mb": values[2], "gpu_temp_c": values[3], "gpu_power_w": values[4]})
        except Exception:
            pass
    return snap


def environment_report() -> Dict[str, Any]:
    report = {
        "platform": platform.platform(),
        "python": platform.python_version(),
        "torch": torch.__version__,
        "cuda_available": torch.cuda.is_available(),
        "cuda_runtime": torch.version.cuda,
        "cpu_logical": os.cpu_count(),
        "ram_gb": psutil.virtual_memory().total / 2**30,
        "profile": cfg.profile,
        "budget": budget.summary(),
        "gpu": gpu_snapshot(),
    }
    atomic_json_dump(report, RUN_DIR / "environment.json")
    logger.info("Environment: %s", json.dumps(report, default=str))
    return report

configure_runtime()
seed_everything(cfg.seeds[0])
environment = environment_report()
print("Run directory:", RUN_DIR)
print("Budget:", budget.summary())

2026-08-08 22:32:42 | INFO | Environment: {"platform": "Windows-10-10.0.19045-SP0", "python": "3.11.14", "torch": "2.9.1+cu128", "cuda_available": true, "cuda_runtime": "12.8", "cpu_logical": 64, "ram_gb": 63.91537857055664, "profile": "rtx3060_24h", "budget": {"started_at": "2026-08-08 15:46:03", "deadline": "2026-08-09 15:46:03", "remaining_hours": 17.222302281128037}, "gpu": {"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 0.0, "reserved_gb": 0.0, "max_allocated_gb": 0.0, "gpu_util_pct": "0", "gpu_mem_used_mb": "543", "gpu_mem_total_mb": "12288", "gpu_temp_c": "38", "gpu_power_w": "11.50"}}

Run directory: C:\Users\HaseebWajid\Downloads\runs\dersx_paper_aligned\campaign_01
Budget: {'started_at': '2026-08-08 15:46:03', 'deadline': '2026-08-09 15:46:03', 'remaining_hours': 17.22226714769999}

## 3. Corpus parsing, text normalization, and exact-sample auditing

The parser preserves raw IEMOCAP labels. `xxx`/no-consensus rows are dropped rather than relabeled. An optional manifest is the only defensible way to reproduce the manuscript's unexplained 5,479-row subset exactly.

In [5]:
TAG_KEEP = {"laugh", "laughter", "cry", "crying", "sob", "sobbing"}
IEMOCAP_MAP = {
    "ang": "ang", "hap": "hap", "neu": "neu", "sad": "sad", "exc": "exc",
    "fea": "fea", "fru": "fru", "oth": "oth", "sur": "sur", "dis": "oth",
}
MSP_EMOTION_MAP = {
    "anger": "ang", "angry": "ang", "happiness": "hap", "happy": "hap", "joy": "hap",
    "neutral": "neu", "sadness": "sad", "sad": "sad", "fear": "fea", "fearful": "fea",
    "surprise": "sur", "surprised": "sur", "disgust": "oth", "contempt": "oth", "other": "oth",
    "excited": "exc", "excitement": "exc", "frustrated": "fru", "frustration": "fru",
}


def normalize_transcript(text: Any, fallback: str = "[EMPTY]") -> str:
    s = "" if text is None else str(text)
    s = s.lower().strip()
    s = re.sub(r"([!?.,])\1+", r"\1", s)
    s = re.sub(r"\b(uh+|um+|erm+|hmm+)\b", " ", s)

    def tag_repl(match: re.Match) -> str:
        tag = re.sub(r"[^a-z]+", "", match.group(1).lower())
        return f" [{tag}] " if tag in TAG_KEEP else " "

    s = re.sub(r"[\[<\(]([^\]>)]+)[\]>\)]", tag_repl, s)
    s = re.sub(r"[^a-z0-9'!?.,\[\]\s-]+", " ", s)
    s = re.sub(r"\s+", " ", s).strip()
    return s if s and len(s.replace(" ", "")) >= 1 else fallback


def derive_iemocap_ids(utterance_id: str) -> Tuple[str, str, str, str, str]:
    utt = Path(str(utterance_id)).stem
    parts = utt.split("_")
    dialog = "_".join(parts[:-1]) if len(parts) > 1 else utt
    match = re.search(r"(Ses\d{2})", utt, flags=re.I)
    session = f"Ses{match.group(1)[3:]}" if match else "Ses00"
    suffix = parts[-1] if parts else ""
    gender = suffix[:1].upper() if suffix[:1].upper() in {"F", "M"} else "U"
    speaker = f"{session}{gender}"
    scenario = "improvised" if "impro" in dialog.lower() else ("scripted" if "script" in dialog.lower() else "unknown")
    return utt, dialog, speaker, session, scenario


def read_subset_ids(path: str) -> Optional[set[str]]:
    if not path:
        return None
    p = Path(path).expanduser()
    if not p.exists():
        raise FileNotFoundError(f"Subset manifest not found: {p}")
    if p.suffix.lower() == ".csv":
        frame = pd.read_csv(p)
        col = "utterance_id" if "utterance_id" in frame.columns else frame.columns[0]
        return set(frame[col].astype(str).map(lambda x: Path(x).stem))
    return {Path(line.strip()).stem for line in p.read_text(encoding="utf-8").splitlines() if line.strip()}


def audio_duration(path: Path) -> float:
    try:
        info = sf.info(str(path))
        return float(info.frames / max(info.samplerate, 1))
    except Exception:
        return float("nan")


def find_iemocap_sessions(root: Path) -> List[Path]:
    return sorted({p.resolve() for p in root.rglob("Session*") if (p / "sentences" / "wav").exists()})


def parse_iemocap(root: str, subset_manifest: str = "") -> pd.DataFrame:
    root_path = Path(root).expanduser().resolve()
    sessions = find_iemocap_sessions(root_path)
    if not sessions:
        raise FileNotFoundError(f"No Session*/sentences/wav folders found under {root_path}")

    rows: List[Dict[str, Any]] = []
    subset_ids = read_subset_ids(subset_manifest)
    for session_dir in sessions:
        wav_map = {p.stem: p.resolve() for p in (session_dir / "sentences" / "wav").rglob("*.wav")}
        transcripts: Dict[str, str] = {}
        for txt in (session_dir / "dialog" / "transcriptions").glob("*.txt"):
            for line in txt.read_text(encoding="utf-8", errors="ignore").splitlines():
                m = re.match(r"^(\S+)\s+\[([^\]]+)\]:\s*(.*)$", line.strip())
                if m:
                    transcripts[m.group(1)] = m.group(3)
        for label_file in (session_dir / "dialog" / "EmoEvaluation").glob("*.txt"):
            for line in label_file.read_text(encoding="utf-8", errors="ignore").splitlines():
                if not line.startswith("["):
                    continue
                parts = line.split("\t")
                if len(parts) < 4:
                    continue
                time_match = re.match(r"\[\s*([\d.]+)\s*-\s*([\d.]+)\s*\]", parts[0])
                utt = parts[1].strip()
                raw = parts[2].strip().lower()
                if subset_ids is not None and utt not in subset_ids:
                    continue
                if raw in {"xxx", "no agreement", ""} and cfg.drop_iemocap_no_consensus:
                    continue
                if raw == "dis" and not cfg.map_iemocap_disgust_to_other:
                    continue
                emotion = IEMOCAP_MAP.get(raw)
                if emotion is None:
                    continue
                dims = [float(x) for x in re.findall(r"-?\d+(?:\.\d+)?", parts[3])]
                if len(dims) < 2 or utt not in wav_map:
                    continue
                uid, dialog, speaker, session, scenario = derive_iemocap_ids(utt)
                rows.append({
                    "corpus": "IEMOCAP", "utterance_id": uid, "dialog_id": dialog,
                    "speaker_id": speaker, "session_id": session, "scenario_type": scenario,
                    "audio_path": str(wav_map[utt]), "transcript": normalize_transcript(transcripts.get(utt, ""), cfg.fallback_text),
                    "emotion_label": emotion, "emotion_id": EMOTION_TO_ID[emotion], "raw_emotion_label": raw,
                    "activation": float(dims[1]), "valence": float(dims[0]),
                    "dominance": float(dims[2]) if len(dims) > 2 else np.nan,
                    "start_time": float(time_match.group(1)) if time_match else np.nan,
                    "end_time": float(time_match.group(2)) if time_match else np.nan,
                })
    df = pd.DataFrame(rows).drop_duplicates("utterance_id").reset_index(drop=True)
    if df.empty:
        raise RuntimeError("IEMOCAP parser produced zero rows")
    missing = ~df["audio_path"].map(lambda p: Path(p).exists())
    if missing.any():
        raise FileNotFoundError(f"Missing {int(missing.sum())} IEMOCAP audio files")
    if subset_ids is not None:
        missing_ids = subset_ids - set(df["utterance_id"])
        if missing_ids:
            raise ValueError(f"Subset manifest contains {len(missing_ids)} IDs that were not parsed; examples: {sorted(missing_ids)[:10]}")
    duration_cache = RUN_DIR / "metadata" / "iemocap_durations.csv"
    duration_cache.parent.mkdir(parents=True, exist_ok=True)
    if duration_cache.exists():
        dur = pd.read_csv(duration_cache)
        df = df.merge(dur[["utterance_id", "duration_s"]], on="utterance_id", how="left")
    else:
        df["duration_s"] = [audio_duration(Path(p)) for p in tqdm(df["audio_path"], desc="IEMOCAP durations")]
        df[["utterance_id", "duration_s"]].to_csv(duration_cache, index=False)
    return df


def fingerprint_frame(df: pd.DataFrame, columns: Sequence[str]) -> str:
    view = df.loc[:, [c for c in columns if c in df.columns]].copy().sort_values(columns[0])
    return hashlib.sha256(view.to_csv(index=False).encode("utf-8")).hexdigest()


def audit_iemocap_sample(df: pd.DataFrame) -> pd.DataFrame:
    actual = df["emotion_label"].value_counts().reindex(EMOTION_LABELS, fill_value=0)
    audit = pd.DataFrame({
        "emotion": EMOTION_LABELS,
        "paper_count": [PAPER_IEMOCAP_COUNTS[k] for k in EMOTION_LABELS],
        "parsed_count": [int(actual[k]) for k in EMOTION_LABELS],
    })
    audit["delta"] = audit["parsed_count"] - audit["paper_count"]
    audit.loc[len(audit)] = ["TOTAL", sum(PAPER_IEMOCAP_COUNTS.values()), len(df), len(df)-sum(PAPER_IEMOCAP_COUNTS.values())]
    exact = len(df) == cfg.expected_iemocap_rows and all(int(actual[k]) == PAPER_IEMOCAP_COUNTS[k] for k in EMOTION_LABELS)
    logger.info("IEMOCAP audit: rows=%d speakers=%d dialogs=%d exact_paper_sample=%s", len(df), df.speaker_id.nunique(), df.dialog_id.nunique(), exact)
    audit.to_csv(RUN_DIR / "metadata" / "iemocap_count_audit.csv", index=False)
    if cfg.profile == "paper_exact" and not exact:
        raise ValueError(
            "paper_exact requires the exact 5,479-row utterance subset, but the paper supplies no reproducible filter. "
            "Set cfg.iemocap_subset_manifest to the exact utterance IDs. See iemocap_count_audit.csv."
        )
    return audit

## 4. MSP-Podcast loader

The loader accepts the official metadata layout or a user-built CSV. It auto-detects common column names, retains strong-agreement samples (`SD < 0.3`), maps compatible categorical labels into the nine-class auxiliary space, and masks unavailable emotion labels rather than inventing them.

In [6]:
def _norm_col(name: str) -> str:
    return re.sub(r"[^a-z0-9]", "", str(name).lower())


def find_column(df: pd.DataFrame, aliases: Sequence[str], required: bool = False) -> Optional[str]:
    lookup = {_norm_col(c): c for c in df.columns}
    for alias in aliases:
        if _norm_col(alias) in lookup:
            return lookup[_norm_col(alias)]
    if required:
        raise ValueError(f"Could not find any of {aliases}; available columns: {list(df.columns)}")
    return None


def discover_msp_metadata(root: Path, explicit: str = "") -> Path:
    if explicit:
        p = Path(explicit).expanduser()
        if not p.exists():
            raise FileNotFoundError(p)
        return p
    candidates = list(root.rglob("*.csv")) + list(root.rglob("*.tsv"))
    if not candidates:
        raise FileNotFoundError(f"No MSP metadata CSV/TSV found under {root}")
    scored = []
    for p in candidates:
        try:
            frame = pd.read_csv(p, sep="\t" if p.suffix.lower()==".tsv" else ",", nrows=5)
            names = {_norm_col(c) for c in frame.columns}
            score = sum(any(_norm_col(a) in names for a in group) for group in [
                ["file", "filename", "audio_path"], ["arousal", "activation"], ["valence"], ["speaker", "speaker_id"],
            ])
            scored.append((score, p.stat().st_size, p))
        except Exception:
            continue
    if not scored:
        raise RuntimeError("MSP metadata files were found but none could be parsed")
    return sorted(scored, reverse=True)[0][2]


def build_audio_index(root: Path) -> Dict[str, Path]:
    """Build one deterministic filename/stem index instead of rglob per MSP row."""
    supported = {".wav", ".flac", ".mp3", ".m4a", ".ogg", ".opus"}
    index: Dict[str, Path] = {}
    for candidate in sorted(root.rglob("*")):
        if not candidate.is_file() or candidate.suffix.lower() not in supported:
            continue
        resolved = candidate.resolve()
        index.setdefault(candidate.name.lower(), resolved)
        index.setdefault(candidate.stem.lower(), resolved)
    return index


def resolve_audio_path(
    value: Any,
    root: Path,
    audio_index: Optional[Mapping[str, Path]] = None,
) -> Optional[Path]:
    if value is None or (isinstance(value, float) and np.isnan(value)):
        return None
    path = Path(str(value).strip().replace("\\", os.sep))
    candidates = [path] if path.is_absolute() else [root / path, root / path.name]
    for candidate in candidates:
        if candidate.exists():
            return candidate.resolve()
    if audio_index is None:
        return None
    return audio_index.get(path.name.lower()) or audio_index.get(path.stem.lower())


def parse_msp_podcast(root: str, metadata_csv: str = "", subset_manifest: str = "") -> pd.DataFrame:
    root_path = Path(root).expanduser().resolve()
    if not root_path.exists():
        raise FileNotFoundError(root_path)
    meta_path = discover_msp_metadata(root_path, metadata_csv)
    sep = "\t" if meta_path.suffix.lower() == ".tsv" else ","
    raw = pd.read_csv(meta_path, sep=sep)

    file_col = find_column(raw, ["audio_path", "file", "filename", "wav_path", "segment"], required=True)
    uid_col = find_column(raw, ["utterance_id", "segment_id", "id", "file", "filename"], required=True)
    text_col = find_column(raw, ["transcript", "transcription", "text", "sentence"])
    speaker_col = find_column(raw, ["speaker_id", "speaker", "spkr", "speakerid"])
    dialog_col = find_column(raw, ["dialog_id", "podcast_id", "conversation_id", "show_id"])
    partition_col = find_column(raw, ["partition", "split", "set", "subset"])
    arousal_col = find_column(raw, ["arousal", "activation", "emoact", "aro"], required=True)
    valence_col = find_column(raw, ["valence", "emoval", "val"], required=True)
    aro_sd_col = find_column(raw, ["arousal_sd", "activation_sd", "arousalstd", "arostd", "sd_arousal"])
    val_sd_col = find_column(raw, ["valence_sd", "valencestd", "valstd", "sd_valence"])
    agree_col = find_column(raw, ["agreement_sd", "sd", "label_sd"])
    emotion_col = find_column(raw, ["primary_emotion", "emotion", "categorical_emotion", "label"])

    subset_ids = read_subset_ids(subset_manifest)
    rows = []
    missing_audio = 0
    invalid_affect_rows = 0
    audio_index: Optional[Dict[str, Path]] = None
    for _, r in tqdm(raw.iterrows(), total=len(raw), desc="MSP metadata"):
        uid = Path(str(r[uid_col])).stem
        if subset_ids is not None and uid not in subset_ids:
            continue
        path = resolve_audio_path(r[file_col], root_path, audio_index)
        if path is None:
            if audio_index is None:
                logger.info("Building MSP audio filename index under %s", root_path)
                audio_index = build_audio_index(root_path)
            path = resolve_audio_path(r[file_col], root_path, audio_index)
        if path is None:
            missing_audio += 1
            continue
        sd_values = []
        for col in [aro_sd_col, val_sd_col, agree_col]:
            if col is not None and pd.notna(r[col]):
                try: sd_values.append(float(r[col]))
                except Exception: pass
        agreement_sd = max(sd_values) if sd_values else np.nan
        if np.isfinite(agreement_sd) and agreement_sd >= cfg.msp_agreement_sd_threshold:
            continue
        raw_emotion = str(r[emotion_col]).strip().lower() if emotion_col is not None and pd.notna(r[emotion_col]) else ""
        mapped = MSP_EMOTION_MAP.get(raw_emotion)
        partition = str(r[partition_col]).strip() if partition_col is not None and pd.notna(r[partition_col]) else "unknown"
        speaker = str(r[speaker_col]).strip() if speaker_col is not None and pd.notna(r[speaker_col]) else f"unknown_{uid}"
        dialog = str(r[dialog_col]).strip() if dialog_col is not None and pd.notna(r[dialog_col]) else uid
        try:
            arousal = float(r[arousal_col])
            valence = float(r[valence_col])
        except (TypeError, ValueError):
            invalid_affect_rows += 1
            continue
        if not np.isfinite(arousal) or not np.isfinite(valence):
            invalid_affect_rows += 1
            continue
        rows.append({
            "corpus": "MSP-Podcast", "utterance_id": uid, "dialog_id": dialog, "speaker_id": speaker,
            "audio_path": str(path), "transcript": normalize_transcript(r[text_col] if text_col is not None else "", cfg.fallback_text),
            "emotion_label": mapped if mapped is not None else "", "emotion_id": EMOTION_TO_ID[mapped] if mapped is not None else -1,
            "raw_emotion_label": raw_emotion, "arousal": arousal, "valence": valence,
            "agreement_sd": agreement_sd, "partition": partition, "duration_s": audio_duration(path),
        })
    df = pd.DataFrame(rows).drop_duplicates("utterance_id").reset_index(drop=True)
    if df.empty:
        raise RuntimeError("MSP-Podcast parser produced zero rows")
    if subset_ids is not None:
        missing_ids = subset_ids - set(df.utterance_id)
        if missing_ids:
            raise ValueError(f"MSP subset manifest has {len(missing_ids)} IDs that were not retained")
    logger.info(
        "MSP-Podcast: rows=%d speakers=%d partitions=%s missing_audio=%d invalid_affect=%d emotion_coverage=%.3f",
        len(df),
        df.speaker_id.nunique(),
        sorted(df.partition.astype(str).unique())[:20],
        missing_audio,
        invalid_affect_rows,
        float((df.emotion_id >= 0).mean()),
    )
    if cfg.profile == "paper_exact" and len(df) != cfg.expected_msp_rows:
        raise ValueError(
            f"paper_exact expects {cfg.expected_msp_rows} MSP rows after SD<0.3, got {len(df)}. "
            "Provide cfg.msp_subset_manifest for the paper's exact release/subset IDs."
        )
    return df

## 5. Leakage-controlled targets and splits

IEMOCAP uses training-fold activation statistics. MSP-Podcast implements Equation (3) exactly as `z_arousal - 0.5*z_valence`. Quartiles are always fitted on the source training partition. Cross-corpus label normalization uses a declared target reference partition and is saved in every result bundle.

In [7]:
@dataclass
class TargetStats:
    corpus: str
    activation_mean: float = 0.0
    activation_std: float = 1.0
    arousal_mean: float = 0.0
    arousal_std: float = 1.0
    valence_mean: float = 0.0
    valence_std: float = 1.0
    q25: float = 0.0
    q50: float = 0.0
    q75: float = 0.0


def safe_std(values: Sequence[float]) -> float:
    value = float(np.std(np.asarray(values, dtype=float), ddof=0))
    return value if np.isfinite(value) and value > 1e-8 else 1.0


def _continuous_with_stats(df: pd.DataFrame, stats: TargetStats) -> np.ndarray:
    if stats.corpus == "IEMOCAP":
        return (df["activation"].astype(float).to_numpy() - stats.activation_mean) / stats.activation_std
    if stats.corpus == "MSP-Podcast":
        z_aro = (df["arousal"].astype(float).to_numpy() - stats.arousal_mean) / stats.arousal_std
        z_val = (df["valence"].astype(float).to_numpy() - stats.valence_mean) / stats.valence_std
        return z_aro - 0.5 * z_val
    raise ValueError(stats.corpus)


def fit_target_stats(train_df: pd.DataFrame, corpus: str) -> TargetStats:
    if corpus == "IEMOCAP":
        values = train_df["activation"].astype(float).to_numpy()
        stats = TargetStats(corpus=corpus, activation_mean=float(values.mean()), activation_std=safe_std(values))
    elif corpus == "MSP-Podcast":
        aro = train_df["arousal"].astype(float).to_numpy()
        val = train_df["valence"].astype(float).to_numpy()
        stats = TargetStats(corpus=corpus, arousal_mean=float(aro.mean()), arousal_std=safe_std(aro), valence_mean=float(val.mean()), valence_std=safe_std(val))
    else:
        raise ValueError(corpus)
    cont = _continuous_with_stats(train_df, stats)
    stats.q25, stats.q50, stats.q75 = [float(x) for x in np.quantile(cont, [0.25, 0.50, 0.75])]
    return stats


def continuous_to_bins(values: Sequence[float], stats: TargetStats) -> np.ndarray:
    v = np.asarray(values, dtype=float)
    return np.digitize(v, bins=[stats.q25, stats.q50, stats.q75], right=True).astype(np.int64)


def apply_target_stats(df: pd.DataFrame, stats: TargetStats) -> pd.DataFrame:
    out = df.copy()
    out["distress_cont"] = _continuous_with_stats(out, stats).astype(np.float32)
    out["distress_bin"] = continuous_to_bins(out["distress_cont"].to_numpy(), stats)
    return out


def split_dialogs_three_way(df: pd.DataFrame, seed: int, train_frac: float = 0.80, val_frac: float = 0.10) -> Tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    dialogs = np.array(sorted(df.dialog_id.astype(str).unique()))
    if len(dialogs) < 3:
        raise ValueError("Need at least three dialogs for train/validation/calibration")
    rng = np.random.default_rng(seed)
    rng.shuffle(dialogs)
    n = len(dialogs)
    n_train = max(1, int(round(train_frac*n)))
    n_val = max(1, int(round(val_frac*n)))
    if n_train + n_val >= n:
        n_train = max(1, n-2); n_val = 1
    train_d = set(dialogs[:n_train]); val_d = set(dialogs[n_train:n_train+n_val]); cal_d = set(dialogs[n_train+n_val:])
    return (
        df[df.dialog_id.astype(str).isin(train_d)].copy(),
        df[df.dialog_id.astype(str).isin(val_d)].copy(),
        df[df.dialog_id.astype(str).isin(cal_d)].copy(),
    )


def prepare_iemocap_loso(df: pd.DataFrame, heldout_speaker: str, seed: int) -> Dict[str, Any]:
    test = df[df.speaker_id.astype(str) == heldout_speaker].copy()
    if test.empty:
        raise ValueError(f"No rows for held-out speaker {heldout_speaker}")
    heldout_dialogs = set(test.dialog_id.astype(str))
    pool = df[(df.speaker_id.astype(str) != heldout_speaker) & (~df.dialog_id.astype(str).isin(heldout_dialogs))].copy()
    train, val, cal = split_dialogs_three_way(pool, seed)
    split_sets = {k: set(v.dialog_id.astype(str)) for k, v in {"train":train,"val":val,"cal":cal,"test":test}.items()}
    for a in split_sets:
        for b in split_sets:
            if a < b and split_sets[a] & split_sets[b]:
                raise AssertionError(f"Dialog leakage between {a} and {b}")
    if heldout_speaker in set(train.speaker_id.astype(str)) | set(val.speaker_id.astype(str)) | set(cal.speaker_id.astype(str)):
        raise AssertionError("Held-out speaker leaked into development data")
    stats = fit_target_stats(train, "IEMOCAP")
    return {
        "train": apply_target_stats(train, stats), "val": apply_target_stats(val, stats),
        "cal": apply_target_stats(cal, stats), "test": apply_target_stats(test, stats),
        "target_stats": stats,
    }


def prepare_all_dialog_split(df: pd.DataFrame, corpus: str, seed: int) -> Dict[str, Any]:
    train, val, cal = split_dialogs_three_way(df, seed)
    stats = fit_target_stats(train, corpus)
    return {"train": apply_target_stats(train, stats), "val": apply_target_stats(val, stats), "cal": apply_target_stats(cal, stats), "target_stats": stats}


def select_msp_partition(df: pd.DataFrame, name: str) -> pd.DataFrame:
    norm = df.partition.astype(str).str.lower().str.replace(r"[^a-z0-9]", "", regex=True)
    key = re.sub(r"[^a-z0-9]", "", name.lower())
    exact = df[norm == key]
    if not exact.empty:
        return exact.copy()
    contains = df[norm.str.contains(key, regex=False)]
    return contains.copy()

## 6. Controlled acoustic/channel/text degradation

AMR uses an actual FFmpeg AMR-NB round-trip when an encoder is available. `paper_exact` fails loudly if codec-accurate AMR is unavailable; the 24-hour profile may use a logged narrow-band proxy. Word corruption applies an exact number of edit operations and records realized WER.

In [8]:
@dataclass(frozen=True)
class DegradationSpec:
    name: str
    snr_db: Optional[float] = None
    amr: bool = False
    packet_loss: float = 0.0
    wer: float = 0.0

DEGRADATION_GRID = (
    DegradationSpec("clean"),
    DegradationSpec("noise_20db", snr_db=20), DegradationSpec("noise_15db", snr_db=15),
    DegradationSpec("noise_10db", snr_db=10), DegradationSpec("noise_5db", snr_db=5),
    DegradationSpec("mobile_15db_amr", snr_db=15, amr=True),
    DegradationSpec("voip_15db_packet10", snr_db=15, packet_loss=0.10),
    DegradationSpec("wer_10", wer=0.10), DegradationSpec("wer_20", wer=0.20), DegradationSpec("wer_30", wer=0.30),
    DegradationSpec("typical_15db_wer15", snr_db=15, wer=0.15),
    DegradationSpec("challenging_10db_wer25", snr_db=10, wer=0.25),
    DegradationSpec("extreme_5db_wer35", snr_db=5, wer=0.35),
)


def resample_waveform(wav: torch.Tensor, orig_sr: int, target_sr: int) -> torch.Tensor:
    wav = wav.detach().cpu().float().contiguous()
    if orig_sr == target_sr:
        return wav
    g = math.gcd(int(orig_sr), int(target_sr))
    arr = resample_poly(wav.numpy(), target_sr//g, orig_sr//g).astype(np.float32)
    return torch.from_numpy(np.ascontiguousarray(arr))


def waveform_cache_path(audio_path: str) -> Path:
    p = Path(audio_path)
    token = stable_hash({"path": str(p.resolve()), "mtime": p.stat().st_mtime_ns, "sr": cfg.sample_rate})
    return RUN_DIR / "cache" / "waveforms" / f"{token}.npy"


def load_waveform(audio_path: str) -> torch.Tensor:
    cache = waveform_cache_path(audio_path)
    if cfg.cache_waveforms and cache.exists():
        return torch.from_numpy(np.load(cache).astype(np.float32, copy=False))
    audio, sr = sf.read(audio_path, dtype="float32", always_2d=True)
    wav = torch.from_numpy(np.ascontiguousarray(audio.mean(axis=1), dtype=np.float32))
    wav = resample_waveform(wav, int(sr), cfg.sample_rate)
    if cfg.cache_waveforms:
        cache.parent.mkdir(parents=True, exist_ok=True)
        tmp = cache.with_name(cache.name + f".{os.getpid()}.tmp.npy")
        np.save(tmp, wav.numpy().astype(np.float16))
        try:
            os.replace(tmp, cache)
        except OSError:
            # Another worker/process may have completed the same deterministic cache entry.
            tmp.unlink(missing_ok=True)
    return wav


def noise_files() -> List[Path]:
    if not cfg.noise_root:
        return []
    root = Path(cfg.noise_root).expanduser()
    return sorted([p for p in root.rglob("*.wav") if p.is_file()]) if root.exists() else []

NOISE_FILES = noise_files()


def add_noise_snr(wav: torch.Tensor, snr_db: float, rng: np.random.Generator) -> Tuple[torch.Tensor, str]:
    if NOISE_FILES:
        p = NOISE_FILES[int(rng.integers(0, len(NOISE_FILES)))]
        noise = load_waveform(str(p))
        if len(noise) < len(wav):
            noise = noise.repeat(int(math.ceil(len(wav)/max(len(noise),1))))
        start = int(rng.integers(0, max(1, len(noise)-len(wav)+1)))
        noise = noise[start:start+len(wav)]
        source = str(p)
    else:
        noise = torch.from_numpy(rng.standard_normal(len(wav)).astype(np.float32))
        source = "deterministic_gaussian_fallback"
    sig_pow = wav.pow(2).mean().clamp_min(1e-12)
    noise = noise - noise.mean()
    noise_pow = noise.pow(2).mean().clamp_min(1e-12)
    scale = torch.sqrt(sig_pow / (noise_pow * (10.0 ** (snr_db/10.0))))
    return wav + noise*scale, source


def simulate_packet_loss(wav: torch.Tensor, rate: float, rng: np.random.Generator, packet_ms: int = 20) -> torch.Tensor:
    out = wav.clone()
    packet_len = max(1, int(cfg.sample_rate*packet_ms/1000))
    n_packets = math.ceil(len(out)/packet_len)
    drop = rng.random(n_packets) < rate
    for i in np.flatnonzero(drop):
        out[i*packet_len:min(len(out),(i+1)*packet_len)] = 0
    return out


def ffmpeg_amr_codec() -> Optional[str]:
    exe = shutil.which("ffmpeg")
    if not exe:
        return None
    try:
        enc = subprocess.check_output([exe, "-hide_banner", "-encoders"], text=True, stderr=subprocess.STDOUT)
        for codec in ("libopencore_amrnb", "amr_nb"):
            if codec in enc:
                return codec
    except Exception:
        pass
    return None

AMR_CODEC = ffmpeg_amr_codec()


def amr_roundtrip(wav: torch.Tensor) -> Tuple[torch.Tensor, str]:
    if AMR_CODEC is None:
        if cfg.profile == "paper_exact":
            raise RuntimeError("Codec-accurate AMR-NB requested but FFmpeg has no AMR encoder")
        x = resample_waveform(wav, cfg.sample_rate, 8000)
        x = torch.tanh(1.2*x)
        return resample_waveform(x, 8000, cfg.sample_rate), "narrowband_proxy_no_amr_encoder"
    exe = shutil.which("ffmpeg")
    with tempfile.TemporaryDirectory() as td:
        inp, amr, out = Path(td)/"in.wav", Path(td)/"mid.amr", Path(td)/"out.wav"
        sf.write(inp, wav.numpy(), cfg.sample_rate)
        subprocess.run([exe,"-y","-loglevel","error","-i",str(inp),"-ar","8000","-ac","1","-c:a",AMR_CODEC,"-b:a","12.2k",str(amr)], check=True)
        subprocess.run([exe,"-y","-loglevel","error","-i",str(amr),"-ar",str(cfg.sample_rate),"-ac","1",str(out)], check=True)
        arr, sr = sf.read(out, dtype="float32")
        return resample_waveform(torch.as_tensor(arr), int(sr), cfg.sample_rate), f"ffmpeg:{AMR_CODEC}"


def levenshtein_words(a: Sequence[str], b: Sequence[str]) -> int:
    prev = list(range(len(b)+1))
    for i, x in enumerate(a, 1):
        cur = [i]
        for j, y in enumerate(b, 1):
            cur.append(min(cur[-1]+1, prev[j]+1, prev[j-1]+(x!=y)))
        prev = cur
    return prev[-1]


def corrupt_text_exact_wer(text: str, target_wer: float, vocab: Sequence[str], rng: random.Random) -> Tuple[str, float]:
    original = text.split()
    if target_wer <= 0 or not original:
        return text, 0.0
    output = original.copy()
    n_ops = max(1, int(round(target_wer*len(original))))
    vocabulary = list(vocab) or original or ["word"]
    for _ in range(n_ops):
        op = rng.choice(("sub", "del", "ins"))
        if op == "ins" or not output:
            pos = rng.randrange(len(output)+1)
            output.insert(pos, rng.choice(vocabulary))
        elif op == "del":
            output.pop(rng.randrange(len(output)))
        else:
            output[rng.randrange(len(output))] = rng.choice(vocabulary)
    realized = levenshtein_words(original, output) / max(len(original), 1)
    return " ".join(output) if output else cfg.fallback_text, float(realized)


def apply_degradation(wav: torch.Tensor, text: str, spec: Optional[DegradationSpec], vocab: Sequence[str], seed: int) -> Tuple[torch.Tensor, str, Dict[str, Any]]:
    if spec is None or spec.name == "clean":
        return wav, text, {"noise_source":"none", "channel":"clean", "realized_wer":0.0}
    rng = np.random.default_rng(seed)
    py_rng = random.Random(seed)
    x, t = wav, text
    meta = {"noise_source":"none", "channel":"clean", "realized_wer":0.0}
    if spec.snr_db is not None:
        x, meta["noise_source"] = add_noise_snr(x, spec.snr_db, rng)
    if spec.amr:
        x, meta["channel"] = amr_roundtrip(x)
    if spec.packet_loss > 0:
        x = simulate_packet_loss(x, spec.packet_loss, rng)
        meta["channel"] = f"packet_loss_{spec.packet_loss:.2f}"
    if spec.wer > 0:
        t, meta["realized_wer"] = corrupt_text_exact_wer(t, spec.wer, vocab, py_rng)
    return x, t, meta

## 7. Dataset, dynamic length bucketing, and collator

Length bucketing reduces wasted audio padding. The micro-batch is accumulated to an effective batch of 8. CPU-to-GPU transfer uses pinned memory and non-blocking copies when available.

In [9]:
class SpeechTextDataset(Dataset):
    def __init__(self, frame: pd.DataFrame, degradation: Optional[DegradationSpec] = None, vocab: Sequence[str] = ()):
        self.frame = frame.reset_index(drop=True).copy()
        self.degradation = degradation
        self.vocab = tuple(vocab)

    def __len__(self) -> int:
        return len(self.frame)

    def __getitem__(self, index: int) -> Dict[str, Any]:
        row = self.frame.iloc[index]
        wav = load_waveform(str(row.audio_path))
        text = normalize_transcript(row.transcript, cfg.fallback_text)
        sample_seed = int(hashlib.sha256(f"{row.utterance_id}|{self.degradation}|{index}".encode()).hexdigest()[:8], 16)
        wav, text, deg_meta = apply_degradation(wav, text, self.degradation, self.vocab, sample_seed)
        return {
            "waveform": wav, "text": text,
            "distress_cont": float(row.distress_cont), "distress_bin": int(row.distress_bin),
            "emotion_id": int(row.emotion_id), "utterance_id": str(row.utterance_id),
            "dialog_id": str(row.dialog_id), "speaker_id": str(row.speaker_id),
            "start_time": float(row.get("start_time", np.nan)), "degradation_meta": deg_meta,
        }


class LengthBucketBatchSampler(Sampler[List[int]]):
    def __init__(self, lengths: Sequence[float], batch_size: int, shuffle: bool, seed: int, bucket_multiplier: int = 40):
        arr = np.asarray(lengths, dtype=float)
        finite = arr[np.isfinite(arr)]
        fill = float(np.median(finite)) if len(finite) else 1.0
        self.lengths = np.nan_to_num(arr, nan=fill, posinf=fill, neginf=fill)
        self.batch_size = int(batch_size); self.shuffle = bool(shuffle); self.seed = int(seed)
        self.bucket_size = max(self.batch_size, self.batch_size*int(bucket_multiplier))
        self.epoch = 0; self.start_batch = 0

    def set_epoch(self, epoch: int, start_batch: int = 0) -> None:
        self.epoch = int(epoch); self.start_batch = int(start_batch)

    def _batches(self) -> List[List[int]]:
        order = np.argsort(self.lengths).tolist()
        rng = random.Random(self.seed + self.epoch)
        buckets = [order[i:i+self.bucket_size] for i in range(0, len(order), self.bucket_size)]
        batches: List[List[int]] = []
        for bucket in buckets:
            if self.shuffle: rng.shuffle(bucket)
            batches.extend([bucket[i:i+self.batch_size] for i in range(0, len(bucket), self.batch_size)])
        if self.shuffle: rng.shuffle(batches)
        return batches

    def __iter__(self) -> Iterator[List[int]]:
        yield from self._batches()[self.start_batch:]

    def __len__(self) -> int:
        return math.ceil(len(self.lengths)/self.batch_size)


class DERSXCollator:
    def __init__(self, tokenizer: Any, feature_extractor: Any):
        self.tokenizer = tokenizer; self.feature_extractor = feature_extractor

    def __call__(self, batch: List[Dict[str, Any]]) -> Dict[str, Any]:
        audio = self.feature_extractor(
            [x["waveform"].numpy() for x in batch], sampling_rate=cfg.sample_rate,
            padding=True, return_attention_mask=True, return_tensors="pt",
        )
        text = self.tokenizer(
            [x["text"] for x in batch], padding=True, truncation=True,
            max_length=cfg.max_text_len, return_tensors="pt",
        )
        return {
            "input_values": audio["input_values"], "audio_attention_mask": audio.get("attention_mask"),
            "input_ids": text["input_ids"], "text_attention_mask": text["attention_mask"],
            "distress_cont": torch.tensor([x["distress_cont"] for x in batch], dtype=torch.float32),
            "distress_bin": torch.tensor([x["distress_bin"] for x in batch], dtype=torch.long),
            "emotion_id": torch.tensor([x["emotion_id"] for x in batch], dtype=torch.long),
            "utterance_id": [x["utterance_id"] for x in batch], "dialog_id": [x["dialog_id"] for x in batch],
            "speaker_id": [x["speaker_id"] for x in batch], "start_time": [x["start_time"] for x in batch],
            "degradation_meta": [x["degradation_meta"] for x in batch],
        }


def prepare_processors() -> Tuple[Any, Any]:
    tokenizer = AutoTokenizer.from_pretrained(cfg.text_model_name, use_fast=True)
    if cfg.fallback_text not in tokenizer.get_vocab():
        tokenizer.add_special_tokens({"additional_special_tokens": [cfg.fallback_text]})
    feature_extractor = AutoFeatureExtractor.from_pretrained(cfg.audio_model_name)
    return tokenizer, feature_extractor


def build_loader(frame: pd.DataFrame, tokenizer: Any, feature_extractor: Any, seed: int, shuffle: bool,
                 degradation: Optional[DegradationSpec] = None, vocab: Sequence[str] = (), start_batch: int = 0) -> Tuple[DataLoader, LengthBucketBatchSampler]:
    dataset = SpeechTextDataset(frame, degradation=degradation, vocab=vocab)
    sampler = LengthBucketBatchSampler(frame.duration_s.to_numpy(), cfg.micro_batch_size, shuffle, seed, cfg.bucket_size_multiplier)
    sampler.set_epoch(0, start_batch)
    workers = max(0, int(cfg.num_workers))
    kwargs = dict(
        dataset=dataset, batch_sampler=sampler, collate_fn=DERSXCollator(tokenizer, feature_extractor),
        num_workers=workers, pin_memory=cfg.pin_memory and torch.cuda.is_available(), worker_init_fn=seed_worker,
    )
    if workers > 0:
        kwargs.update(prefetch_factor=cfg.prefetch_factor, persistent_workers=cfg.persistent_workers)
    return DataLoader(**kwargs), sampler


def move_to_device(batch: Dict[str, Any], device: torch.device) -> Dict[str, Any]:
    return {k: (v.to(device, non_blocking=cfg.pin_memory) if torch.is_tensor(v) else v) for k, v in batch.items()}

## 8. DERS-X architecture

The fusion FFN is `512 → 256 → 512` so the residual connection is dimensionally valid. The attention diagnostic measures confidence (one minus normalized entropy) for each source modality's actual cross-attention map and normalizes the two values to sum to one.

In [10]:
class ScalarMix(nn.Module):
    def __init__(self, n_layers: int):
        super().__init__(); self.logits = nn.Parameter(torch.zeros(n_layers))
    def forward(self, hidden_states: Sequence[torch.Tensor]) -> torch.Tensor:
        states = hidden_states[-len(self.logits):]
        weights = torch.softmax(self.logits, dim=0)
        return sum(w*state for w, state in zip(weights, states))


class ProjectionBlock(nn.Module):
    def __init__(self, in_dim: int, out_dim: int, dropout: float):
        super().__init__(); self.net = nn.Sequential(nn.Linear(in_dim,out_dim), nn.GELU(), nn.Dropout(dropout))
    def forward(self, x: torch.Tensor) -> torch.Tensor: return self.net(x)


class AttentiveStatsPooling(nn.Module):
    def __init__(self, dim: int):
        super().__init__(); self.score = nn.Sequential(nn.Linear(dim,dim//2),nn.Tanh(),nn.Linear(dim//2,1))
    def forward(self, x: torch.Tensor, mask: Optional[torch.Tensor]) -> torch.Tensor:
        scores = self.score(x).squeeze(-1)
        if mask is not None: scores = scores.masked_fill(~mask, -1e4)
        alpha = torch.softmax(scores, dim=-1).unsqueeze(-1)
        mean = (alpha*x).sum(dim=1)
        var = (alpha*(x-mean.unsqueeze(1)).pow(2)).sum(dim=1).clamp_min(1e-6)
        return torch.cat([mean, torch.sqrt(var)], dim=-1)


def masked_mean(x: torch.Tensor, mask: Optional[torch.Tensor]) -> torch.Tensor:
    if mask is None: return x.mean(dim=1)
    w = mask.unsqueeze(-1).to(x.dtype)
    return (x*w).sum(dim=1) / w.sum(dim=1).clamp_min(1.0)


def attention_confidence(attn: torch.Tensor, query_mask: Optional[torch.Tensor], key_mask: Optional[torch.Tensor]) -> torch.Tensor:
    # attn: B,H,Q,K. Confidence = 1 - entropy/log(valid K), averaged over heads and valid queries.
    p = attn.float().clamp_min(1e-12)
    if key_mask is not None:
        p = p * key_mask[:,None,None,:].float()
        p = p / p.sum(dim=-1, keepdim=True).clamp_min(1e-12)
        valid_k = key_mask.sum(dim=-1).clamp_min(2).float()
    else:
        valid_k = torch.full((p.shape[0],), max(p.shape[-1],2), device=p.device, dtype=torch.float32)
    log_p = torch.where(p > 0, p.log(), torch.zeros_like(p))
    entropy = -(p * log_p).sum(dim=-1) / valid_k.log()[:,None,None]
    confidence = 1.0 - entropy.clamp(0,1)
    if query_mask is not None:
        w = query_mask[:,None,:].float()
        return (confidence*w).sum(dim=(1,2)) / (w.sum(dim=(1,2))*confidence.shape[1]).clamp_min(1.0)
    return confidence.mean(dim=(1,2))


class CrossModalFusion(nn.Module):
    def __init__(self, dim: int, heads: int, dropout: float):
        super().__init__()
        self.audio_from_text = nn.MultiheadAttention(dim, heads, dropout=dropout, batch_first=True)
        self.text_from_audio = nn.MultiheadAttention(dim, heads, dropout=dropout, batch_first=True)
        self.norm_a = nn.LayerNorm(dim); self.norm_t = nn.LayerNorm(dim)
        self.ff = nn.Sequential(nn.Linear(2*dim, dim), nn.GELU(), nn.Dropout(dropout), nn.Linear(dim,2*dim), nn.Dropout(dropout))
        self.norm_f = nn.LayerNorm(2*dim)

    def forward(self, a: torch.Tensor, t: torch.Tensor, a_mask: Optional[torch.Tensor], t_mask: Optional[torch.Tensor], diagnostics: bool=False):
        a_up, attn_text = self.audio_from_text(a, t, t, key_padding_mask=(~t_mask if t_mask is not None else None), need_weights=diagnostics, average_attn_weights=False)
        t_up, attn_audio = self.text_from_audio(t, a, a, key_padding_mask=(~a_mask if a_mask is not None else None), need_weights=diagnostics, average_attn_weights=False)
        za = self.norm_a(a+a_up); zt = self.norm_t(t+t_up)
        if a_mask is not None: za = za*a_mask.unsqueeze(-1)
        if t_mask is not None: zt = zt*t_mask.unsqueeze(-1)
        base = torch.cat([masked_mean(za,a_mask), masked_mean(zt,t_mask)], dim=-1)
        fused = self.norm_f(base+self.ff(base))
        diag: Dict[str, torch.Tensor] = {}
        if diagnostics and attn_audio is not None and attn_text is not None:
            audio_conf = attention_confidence(attn_audio, t_mask, a_mask)  # text queries, audio keys
            text_conf = attention_confidence(attn_text, a_mask, t_mask)    # audio queries, text keys
            raw_denom = audio_conf + text_conf
            both_uninformative = raw_denom <= 1e-8
            safe_denom = raw_denom.clamp_min(1e-8)
            audio_share = torch.where(
                both_uninformative, torch.full_like(audio_conf, 0.5), audio_conf / safe_denom
            )
            text_share = torch.where(
                both_uninformative, torch.full_like(text_conf, 0.5), text_conf / safe_denom
            )
            diag = {
                "audio_attention_share": audio_share,
                "text_attention_share": text_share,
                "audio_attention_confidence": audio_conf,
                "text_attention_confidence": text_conf,
            }
        return fused, diag


class ConfigurableHead(nn.Module):
    def __init__(self, in_dim: int, hidden: int, out_dim: int, variant: str, dropout: float):
        super().__init__()
        if variant == "linear": layers = [nn.Linear(in_dim,out_dim)]
        elif variant == "one_relu": layers = [nn.Linear(in_dim,hidden),nn.ReLU(),nn.Dropout(dropout),nn.Linear(hidden,out_dim)]
        elif variant == "two_gelu": layers = [nn.Linear(in_dim,hidden),nn.GELU(),nn.Dropout(dropout),nn.Linear(hidden,out_dim)]
        elif variant == "three_gelu": layers = [nn.Linear(in_dim,hidden),nn.GELU(),nn.Dropout(dropout),nn.Linear(hidden,hidden),nn.GELU(),nn.Dropout(dropout),nn.Linear(hidden,out_dim)]
        else: raise ValueError(variant)
        self.net = nn.Sequential(*layers)
    def forward(self, x: torch.Tensor) -> torch.Tensor: return self.net(x)


class LogMelCNNEncoder(nn.Module):
    def __init__(self, out_dim: int = 256):
        super().__init__()
        try:
            import torchaudio
        except ImportError as exc:
            raise ImportError("torchaudio is required only for the log-Mel CNN ablation") from exc
        self.mel = torchaudio.transforms.MelSpectrogram(sample_rate=cfg.sample_rate,n_fft=400,hop_length=160,n_mels=80)
        self.cnn = nn.Sequential(nn.Conv2d(1,32,3,padding=1),nn.GELU(),nn.MaxPool2d((2,2)),nn.Conv2d(32,64,3,padding=1),nn.GELU(),nn.MaxPool2d((2,2)))
        self.proj = nn.Linear(64*20, out_dim)
    def forward(self, input_values: torch.Tensor, attention_mask: Optional[torch.Tensor]):
        spec = torch.log(self.mel(input_values).clamp_min(1e-6)).unsqueeze(1)
        x = self.cnn(spec).permute(0,3,1,2).flatten(2)
        tokens = self.proj(x)
        mask = torch.ones(tokens.shape[:2], dtype=torch.bool, device=tokens.device)
        return tokens, mask

In [11]:
class DERSXModel(nn.Module):
    def __init__(self, tokenizer_size: int, local_cfg: DERSXConfig):
        super().__init__()
        self.cfg = local_cfg
        self.audio_required = local_cfg.fusion_mode != "text_only"
        self.text_required = local_cfg.fusion_mode != "audio_only"

        self.audio_encoder = None
        self.scalar_mix = None
        self.audio_proj = None
        self.logmel = None
        if self.audio_required:
            if local_cfg.audio_backbone == "wav2vec2":
                self.audio_encoder = Wav2Vec2Model.from_pretrained(local_cfg.audio_model_name)
                self.scalar_mix = ScalarMix(local_cfg.wav2vec_layers_to_mix)
                self.audio_proj = ProjectionBlock(
                    self.audio_encoder.config.hidden_size,
                    local_cfg.latent_dim,
                    local_cfg.dropout,
                )
            elif local_cfg.audio_backbone == "logmel_cnn":
                self.audio_proj = nn.Identity()
                self.logmel = LogMelCNNEncoder(local_cfg.latent_dim)
            else:
                raise ValueError(local_cfg.audio_backbone)

        self.text_encoder = None
        self.text_proj = None
        if self.text_required:
            self.text_encoder = DistilBertModel.from_pretrained(local_cfg.text_model_name)
            self.text_encoder.resize_token_embeddings(tokenizer_size)
            self.text_proj = ProjectionBlock(
                self.text_encoder.config.dim,
                local_cfg.latent_dim,
                local_cfg.dropout,
            )

        self.audio_stats = AttentiveStatsPooling(local_cfg.latent_dim)
        self.cross_fusion = CrossModalFusion(
            local_cfg.latent_dim, local_cfg.fusion_heads, local_cfg.dropout
        )
        fused_dim = 2 * local_cfg.latent_dim
        self.audio_to_fused = nn.Sequential(
            nn.Linear(2 * local_cfg.latent_dim, fused_dim),
            nn.GELU(),
            nn.Dropout(local_cfg.dropout),
        )
        self.text_to_fused = nn.Sequential(
            nn.Linear(local_cfg.latent_dim, fused_dim),
            nn.GELU(),
            nn.Dropout(local_cfg.dropout),
        )
        self.early_fusion = nn.Sequential(
            nn.Linear(fused_dim, local_cfg.latent_dim),
            nn.GELU(),
            nn.Dropout(local_cfg.dropout),
            nn.Linear(local_cfg.latent_dim, fused_dim),
            nn.LayerNorm(fused_dim),
        )
        self.regression_head = ConfigurableHead(
            fused_dim,
            local_cfg.head_hidden,
            1,
            local_cfg.regression_head,
            local_cfg.dropout,
        )
        self.emotion_head = ConfigurableHead(
            fused_dim,
            local_cfg.head_hidden,
            len(EMOTION_LABELS),
            "two_gelu",
            local_cfg.dropout,
        )
        self.audio_reg = ConfigurableHead(
            fused_dim,
            local_cfg.head_hidden,
            1,
            local_cfg.regression_head,
            local_cfg.dropout,
        )
        self.text_reg = ConfigurableHead(
            fused_dim,
            local_cfg.head_hidden,
            1,
            local_cfg.regression_head,
            local_cfg.dropout,
        )
        self.audio_emo = ConfigurableHead(
            fused_dim,
            local_cfg.head_hidden,
            len(EMOTION_LABELS),
            "two_gelu",
            local_cfg.dropout,
        )
        self.text_emo = ConfigurableHead(
            fused_dim,
            local_cfg.head_hidden,
            len(EMOTION_LABELS),
            "two_gelu",
            local_cfg.dropout,
        )
        self.configure_trainability()

    def configure_trainability(self) -> None:
        if self.audio_encoder is not None:
            if self.cfg.freeze_wav2vec_feature_encoder:
                try:
                    self.audio_encoder.freeze_feature_encoder()
                except AttributeError:
                    for parameter in self.audio_encoder.feature_extractor.parameters():
                        parameter.requires_grad = False
            layers = self.audio_encoder.encoder.layers
            n_audio = max(0, int(self.cfg.audio_unfreeze_last_n))
            if n_audio <= 0:
                for parameter in self.audio_encoder.parameters():
                    parameter.requires_grad = False
            elif n_audio < len(layers):
                for parameter in self.audio_encoder.parameters():
                    parameter.requires_grad = False
                for layer in layers[-n_audio:]:
                    for parameter in layer.parameters():
                        parameter.requires_grad = True
                for module in (
                    self.audio_encoder.feature_projection,
                    self.audio_encoder.encoder.layer_norm,
                ):
                    for parameter in module.parameters():
                        parameter.requires_grad = True
            if self.cfg.gradient_checkpointing:
                self.audio_encoder.gradient_checkpointing_enable()

        if self.text_encoder is not None:
            layers = self.text_encoder.transformer.layer
            n_text = max(0, int(self.cfg.text_unfreeze_last_n))
            if n_text <= 0:
                for parameter in self.text_encoder.parameters():
                    parameter.requires_grad = False
            elif n_text < len(layers):
                for parameter in self.text_encoder.parameters():
                    parameter.requires_grad = False
                for layer in layers[-n_text:]:
                    for parameter in layer.parameters():
                        parameter.requires_grad = True
                for parameter in self.text_encoder.embeddings.parameters():
                    parameter.requires_grad = True
            if self.cfg.gradient_checkpointing:
                self.text_encoder.gradient_checkpointing_enable()

    def encode_audio(
        self,
        input_values: torch.Tensor,
        audio_attention_mask: Optional[torch.Tensor],
    ) -> Tuple[torch.Tensor, Optional[torch.Tensor]]:
        if not self.audio_required:
            raise RuntimeError("Audio encoder was not built for text_only mode")
        if self.logmel is not None:
            return self.logmel(input_values, audio_attention_mask)
        output = self.audio_encoder(
            input_values=input_values,
            attention_mask=audio_attention_mask,
            output_hidden_states=True,
            return_dict=True,
        )
        tokens = self.audio_proj(self.scalar_mix(output.hidden_states))
        mask = None
        if audio_attention_mask is not None:
            try:
                mask = self.audio_encoder._get_feature_vector_attention_mask(
                    tokens.shape[1], audio_attention_mask
                ).bool()
            except Exception:
                mask = torch.ones(
                    tokens.shape[:2], dtype=torch.bool, device=tokens.device
                )
        return tokens, mask

    def encode_text(
        self,
        input_ids: torch.Tensor,
        text_attention_mask: torch.Tensor,
    ) -> Tuple[torch.Tensor, torch.Tensor]:
        if not self.text_required:
            raise RuntimeError("Text encoder was not built for audio_only mode")
        output = self.text_encoder(
            input_ids=input_ids,
            attention_mask=text_attention_mask,
            return_dict=True,
        )
        return self.text_proj(output.last_hidden_state), text_attention_mask.bool()

    def forward(
        self,
        input_values: torch.Tensor,
        audio_attention_mask: Optional[torch.Tensor],
        input_ids: torch.Tensor,
        text_attention_mask: torch.Tensor,
        diagnostics: bool = False,
    ) -> Dict[str, Any]:
        mode = self.cfg.fusion_mode
        diagnostics_out: Dict[str, torch.Tensor] = {}

        if mode == "audio_only":
            audio_tokens, audio_mask = self.encode_audio(
                input_values, audio_attention_mask
            )
            fused = self.audio_to_fused(
                self.audio_stats(audio_tokens, audio_mask)
            )
            distress = self.regression_head(fused).squeeze(-1)
            logits = self.emotion_head(fused)
        elif mode == "text_only":
            text_tokens, _ = self.encode_text(input_ids, text_attention_mask)
            fused = self.text_to_fused(text_tokens[:, 0])
            distress = self.regression_head(fused).squeeze(-1)
            logits = self.emotion_head(fused)
        else:
            audio_tokens, audio_mask = self.encode_audio(
                input_values, audio_attention_mask
            )
            text_tokens, text_mask = self.encode_text(
                input_ids, text_attention_mask
            )
            if mode == "early_concat":
                fused = self.early_fusion(
                    torch.cat(
                        [masked_mean(audio_tokens, audio_mask), text_tokens[:, 0]],
                        dim=-1,
                    )
                )
                distress = self.regression_head(fused).squeeze(-1)
                logits = self.emotion_head(fused)
            elif mode == "late_average":
                audio_fused = self.audio_to_fused(
                    self.audio_stats(audio_tokens, audio_mask)
                )
                text_fused = self.text_to_fused(text_tokens[:, 0])
                fused = 0.5 * (audio_fused + text_fused)
                distress = 0.5 * (
                    self.audio_reg(audio_fused).squeeze(-1)
                    + self.text_reg(text_fused).squeeze(-1)
                )
                logits = 0.5 * (
                    self.audio_emo(audio_fused) + self.text_emo(text_fused)
                )
            elif mode == "cross_attention":
                fused, diagnostics_out = self.cross_fusion(
                    audio_tokens,
                    text_tokens,
                    audio_mask,
                    text_mask,
                    diagnostics=diagnostics,
                )
                distress = self.regression_head(fused).squeeze(-1)
                logits = self.emotion_head(fused)
            else:
                raise ValueError(mode)

        return {
            "distress_pred": distress,
            "emotion_logits": logits,
            "fused": fused,
            "diagnostics": diagnostics_out,
        }


def trainable_parameter_report(model: nn.Module) -> Dict[str, int]:
    total = sum(parameter.numel() for parameter in model.parameters())
    trainable = sum(
        parameter.numel()
        for parameter in model.parameters()
        if parameter.requires_grad
    )
    return {
        "total": total,
        "trainable": trainable,
        "frozen": total - trainable,
    }

## 9. Loss, metrics, calibration, and dialog aggregation

MSP samples without a compatible categorical emotion use `emotion_id=-1`; they contribute to regression but are masked from cross-entropy. IEMOCAP uses all nine classes and inverse-frequency weights.

In [12]:
def class_weights(frame: pd.DataFrame) -> torch.Tensor:
    ids = frame.loc[frame.emotion_id >= 0, "emotion_id"].astype(int).to_numpy()
    counts = np.bincount(ids, minlength=len(EMOTION_LABELS)).astype(np.float32)
    counts = np.maximum(counts, 1.0)
    return torch.tensor(
        counts.sum() / (len(counts) * counts), dtype=torch.float32
    )


class JointLoss(nn.Module):
    def __init__(self, weights: torch.Tensor, local_cfg: DERSXConfig):
        super().__init__()
        self.register_buffer("weights", weights)
        self.lambda_emo = local_cfg.lambda_emo
        self.lambda_reg = local_cfg.lambda_reg

    def forward(
        self,
        output: Dict[str, Any],
        batch: Dict[str, Any],
    ) -> Tuple[torch.Tensor, Dict[str, Any]]:
        mse = F.mse_loss(output["distress_pred"], batch["distress_cont"])
        emotion_mask = batch["emotion_id"] >= 0
        if emotion_mask.any():
            ce = F.cross_entropy(
                output["emotion_logits"][emotion_mask],
                batch["emotion_id"][emotion_mask],
                weight=self.weights,
            )
        else:
            ce = mse.new_zeros(())
        loss = self.lambda_emo * ce + self.lambda_reg * mse
        return loss, {
            "loss": float(loss.detach()),
            "ce": float(ce.detach()),
            "mse": float(mse.detach()),
            "emotion_labeled": int(emotion_mask.sum()),
        }


def regression_metrics(
    y_true: Sequence[float], predictions: Sequence[float]
) -> Dict[str, float]:
    y_true = np.asarray(y_true, dtype=float)
    predictions = np.asarray(predictions, dtype=float)
    output = {
        "mae": float(mean_absolute_error(y_true, predictions)),
        "rmse": float(mean_squared_error(y_true, predictions) ** 0.5),
    }
    output["pearson_r"] = (
        float(pearsonr(y_true, predictions).statistic)
        if len(y_true) > 1 and np.std(y_true) > 0 and np.std(predictions) > 0
        else np.nan
    )
    output["spearman_rho"] = (
        float(spearmanr(y_true, predictions).statistic)
        if len(y_true) > 1 and np.std(y_true) > 0 and np.std(predictions) > 0
        else np.nan
    )
    return output


def ordinal_metrics(
    y_true: Sequence[int], predictions: Sequence[int]
) -> Dict[str, float]:
    y_true = np.asarray(y_true, dtype=int)
    predictions = np.asarray(predictions, dtype=int)
    return {
        "macro_f1": float(
            f1_score(
                y_true,
                predictions,
                labels=DISTRESS_LABELS,
                average="macro",
                zero_division=0,
            )
        ),
        "accuracy": float(accuracy_score(y_true, predictions)),
        "uar": float(
            recall_score(
                y_true,
                predictions,
                labels=DISTRESS_LABELS,
                average="macro",
                zero_division=0,
            )
        ),
        "qwk": float(
            cohen_kappa_score(
                y_true,
                predictions,
                labels=DISTRESS_LABELS,
                weights="quadratic",
            )
        ),
    }


def ece_score(probs: np.ndarray, labels: np.ndarray, n_bins: int) -> float:
    probs = np.asarray(probs, dtype=float)
    labels = np.asarray(labels, dtype=int)
    confidence = probs.max(axis=1)
    predictions = probs.argmax(axis=1)
    correctness = (predictions == labels).astype(float)
    ece = 0.0
    edges = np.linspace(0.0, 1.0, n_bins + 1)
    for lower, upper in zip(edges[:-1], edges[1:]):
        selected = (
            (confidence > lower) & (confidence <= upper)
            if lower > 0
            else (confidence >= lower) & (confidence <= upper)
        )
        if selected.any():
            ece += selected.mean() * abs(
                correctness[selected].mean() - confidence[selected].mean()
            )
    return float(ece)


class TemperatureScaler(nn.Module):
    def __init__(self):
        super().__init__()
        self.log_t = nn.Parameter(torch.zeros(()))

    @property
    def temperature(self) -> torch.Tensor:
        return self.log_t.exp().clamp(1e-3, 100)

    def forward(self, logits: torch.Tensor) -> torch.Tensor:
        return logits / self.temperature

    def fit(self, logits: np.ndarray, labels: np.ndarray) -> "TemperatureScaler":
        x = torch.tensor(logits, dtype=torch.float32)
        y = torch.tensor(labels, dtype=torch.long)
        optimizer = torch.optim.LBFGS([self.log_t], lr=0.05, max_iter=100)

        def closure() -> torch.Tensor:
            optimizer.zero_grad()
            loss = F.cross_entropy(self(x), y)
            loss.backward()
            return loss

        optimizer.step(closure)
        return self


def softmax_np(logits: np.ndarray) -> np.ndarray:
    shifted = logits - np.max(logits, axis=1, keepdims=True)
    exp_logits = np.exp(shifted)
    return exp_logits / exp_logits.sum(axis=1, keepdims=True)


def score_prediction_frame(
    prediction_frame: pd.DataFrame,
    stats: TargetStats,
    temperature: Optional[float] = None,
) -> Dict[str, Any]:
    y_continuous = prediction_frame.y_distress_cont.to_numpy()
    pred_continuous = prediction_frame.pred_distress_cont.to_numpy()
    y_bins = prediction_frame.y_distress_bin.to_numpy()
    pred_bins = continuous_to_bins(pred_continuous, stats)
    result: Dict[str, Any] = {
        "regression": regression_metrics(y_continuous, pred_continuous),
        "distress": ordinal_metrics(y_bins, pred_bins),
    }
    valid = prediction_frame.y_emotion.to_numpy() >= 0
    logit_columns = [f"logit_{index}" for index in range(len(EMOTION_LABELS))]
    if valid.any():
        logits = prediction_frame.loc[valid, logit_columns].to_numpy()
        scaled = logits / (float(temperature) if temperature is not None else 1.0)
        probabilities = softmax_np(scaled)
        labels = prediction_frame.loc[valid, "y_emotion"].to_numpy()
        predictions = probabilities.argmax(axis=1)
        result["emotion"] = {
            "macro_f1": float(
                f1_score(
                    labels,
                    predictions,
                    labels=range(len(EMOTION_LABELS)),
                    average="macro",
                    zero_division=0,
                )
            ),
            "accuracy": float(accuracy_score(labels, predictions)),
            "ece": ece_score(probabilities, labels, cfg.ece_bins),
            "class_report": classification_report(
                labels,
                predictions,
                labels=range(len(EMOTION_LABELS)),
                target_names=EMOTION_LABELS,
                zero_division=0,
                output_dict=True,
            ),
        }
    return result


def _mode_nonnegative(values: pd.Series) -> int:
    series = pd.Series(values)
    valid = series[series >= 0]
    return int(valid.mode().iloc[0]) if len(valid) else -1


def aggregate_dialog(
    prediction_frame: pd.DataFrame,
    stats: TargetStats,
    temperature: Optional[float],
) -> Tuple[pd.DataFrame, Dict[str, Any]]:
    logit_columns = [f"logit_{index}" for index in range(len(EMOTION_LABELS))]
    work = prediction_frame.copy()
    work["utterance_emotion_pred"] = work[logit_columns].to_numpy().argmax(axis=1)
    aggregation: Dict[str, Any] = {
        "y_distress_cont": "mean",
        "pred_distress_cont": "mean",
        "speaker_id": "first",
        "y_emotion": _mode_nonnegative,
        "utterance_emotion_pred": lambda values: int(
            pd.Series(values).mode().iloc[0]
        ),
    }
    for column in logit_columns:
        aggregation[column] = "mean"
    dialog_frame = work.groupby("dialog_id", as_index=False).agg(aggregation)
    dialog_frame["y_distress_bin"] = continuous_to_bins(
        dialog_frame.y_distress_cont, stats
    )
    dialog_frame["pred_distress_bin"] = continuous_to_bins(
        dialog_frame.pred_distress_cont, stats
    )
    metrics: Dict[str, Any] = {
        "regression": regression_metrics(
            dialog_frame.y_distress_cont,
            dialog_frame.pred_distress_cont,
        ),
        "distress": ordinal_metrics(
            dialog_frame.y_distress_bin,
            dialog_frame.pred_distress_bin,
        ),
    }
    valid = dialog_frame.y_emotion.to_numpy() >= 0
    if valid.any():
        labels = dialog_frame.loc[valid, "y_emotion"].to_numpy(dtype=int)
        scaled = dialog_frame.loc[valid, logit_columns].to_numpy() / (
            float(temperature) if temperature is not None else 1.0
        )
        probabilities = softmax_np(scaled)
        mean_logit_predictions = probabilities.argmax(axis=1)
        majority_predictions = dialog_frame.loc[
            valid, "utterance_emotion_pred"
        ].to_numpy(dtype=int)
        dialog_frame.loc[valid, "pred_emotion_mean_logit"] = (
            mean_logit_predictions
        )
        metrics["emotion_mean_logit"] = {
            "macro_f1": float(
                f1_score(
                    labels,
                    mean_logit_predictions,
                    labels=range(len(EMOTION_LABELS)),
                    average="macro",
                    zero_division=0,
                )
            ),
            "accuracy": float(accuracy_score(labels, mean_logit_predictions)),
            "ece": ece_score(probabilities, labels, cfg.ece_bins),
        }
        metrics["emotion_majority_vote"] = {
            "macro_f1": float(
                f1_score(
                    labels,
                    majority_predictions,
                    labels=range(len(EMOTION_LABELS)),
                    average="macro",
                    zero_division=0,
                )
            ),
            "accuracy": float(accuracy_score(labels, majority_predictions)),
        }
    return dialog_frame, metrics

## 10. Optimizer, AMP, atomic checkpoints, and mid-epoch resume

A complete training checkpoint contains model, optimizer, scheduler, AMP scaler, epoch, next batch, optimizer step, early-stopping state, RNG states, configuration signature, and data fingerprint. Checkpoints are written only after an optimizer step, so no partial accumulation is resumed incorrectly.

In [13]:
def method_signature(local_cfg: DERSXConfig) -> str:
    keys = (
        "audio_model_name",
        "text_model_name",
        "sample_rate",
        "max_text_len",
        "latent_dim",
        "fusion_heads",
        "dropout",
        "head_hidden",
        "fusion_mode",
        "regression_head",
        "audio_backbone",
        "effective_batch_size",
        "micro_batch_size",
        "lr_encoders",
        "lr_new",
        "weight_decay",
        "warmup_ratio",
        "lambda_emo",
        "lambda_reg",
        "audio_unfreeze_last_n",
        "text_unfreeze_last_n",
    )
    return stable_hash({key: getattr(local_cfg, key) for key in keys})


def capture_rng() -> Dict[str, Any]:
    state: Dict[str, Any] = {
        "python": random.getstate(),
        "numpy": np.random.get_state(),
        "torch": torch.get_rng_state(),
    }
    if torch.cuda.is_available():
        state["cuda"] = torch.cuda.get_rng_state_all()
    return state


def restore_rng(state: Mapping[str, Any]) -> None:
    random.setstate(state["python"])
    np.random.set_state(state["numpy"])
    torch.set_rng_state(state["torch"])
    if torch.cuda.is_available() and "cuda" in state:
        torch.cuda.set_rng_state_all(state["cuda"])


def make_scaler(enabled: bool):
    try:
        return torch.amp.GradScaler("cuda", enabled=enabled)
    except (AttributeError, TypeError):
        return torch.cuda.amp.GradScaler(enabled=enabled)


def autocast_context(enabled: bool):
    if not enabled:
        return contextlib.nullcontext()
    try:
        return torch.autocast(device_type="cuda", dtype=torch.float16)
    except Exception:
        return torch.cuda.amp.autocast(dtype=torch.float16)


def optimizer_and_scheduler(
    model: nn.Module,
    total_steps: int,
    local_cfg: DERSXConfig,
) -> Tuple[torch.optim.Optimizer, Any]:
    groups: Dict[Tuple[str, str], List[nn.Parameter]] = defaultdict(list)
    for name, parameter in model.named_parameters():
        if not parameter.requires_grad:
            continue
        scope = (
            "encoder"
            if name.startswith(("audio_encoder", "text_encoder"))
            else "new"
        )
        decay = (
            "no_decay"
            if name.endswith("bias")
            or "layernorm" in name.lower()
            or ".norm" in name.lower()
            else "decay"
        )
        groups[(scope, decay)].append(parameter)
    parameter_groups = []
    for (scope, decay), parameters in groups.items():
        parameter_groups.append(
            {
                "params": parameters,
                "lr": (
                    local_cfg.lr_encoders
                    if scope == "encoder"
                    else local_cfg.lr_new
                ),
                "weight_decay": (
                    0.0 if decay == "no_decay" else local_cfg.weight_decay
                ),
            }
        )
    optimizer_kwargs: Dict[str, Any] = {}
    if local_cfg.fused_adamw and torch.cuda.is_available():
        optimizer_kwargs["fused"] = True
    try:
        optimizer = torch.optim.AdamW(parameter_groups, **optimizer_kwargs)
    except (TypeError, RuntimeError):
        optimizer = torch.optim.AdamW(parameter_groups)
    scheduler = get_linear_schedule_with_warmup(
        optimizer,
        num_warmup_steps=int(local_cfg.warmup_ratio * total_steps),
        num_training_steps=max(1, total_steps),
    )
    return optimizer, scheduler


def save_training_checkpoint(
    path: Path,
    model: DERSXModel,
    optimizer: Any,
    scheduler: Any,
    scaler: Any,
    epoch: int,
    next_batch: int,
    global_step: int,
    best_f1: float,
    best_mae: float,
    bad_epochs: int,
    data_fingerprint: str,
    history: List[Dict[str, Any]],
) -> None:
    atomic_torch_save(
        {
            "model": model.state_dict(),
            "optimizer": optimizer.state_dict(),
            "scheduler": scheduler.state_dict(),
            "scaler": scaler.state_dict(),
            "epoch": epoch,
            "next_batch": next_batch,
            "global_step": global_step,
            "best_f1": best_f1,
            "best_mae": best_mae,
            "bad_epochs": bad_epochs,
            "rng": capture_rng(),
            "method_signature": method_signature(model.cfg),
            "config": asdict(model.cfg),
            "data_fingerprint": data_fingerprint,
            "history": history,
        },
        path,
    )


def load_training_checkpoint(
    path: Path,
    model: DERSXModel,
    optimizer: Any,
    scheduler: Any,
    scaler: Any,
    data_fingerprint: str,
) -> Dict[str, Any]:
    state = torch.load(path, map_location="cpu", weights_only=False)
    if state["method_signature"] != method_signature(model.cfg):
        raise ValueError(
            "Checkpoint method signature differs from the current task configuration"
        )
    if state["data_fingerprint"] != data_fingerprint:
        raise ValueError(
            "Checkpoint data fingerprint differs from the current split"
        )
    model.load_state_dict(state["model"])
    optimizer.load_state_dict(state["optimizer"])
    scheduler.load_state_dict(state["scheduler"])
    scaler.load_state_dict(state["scaler"])
    restore_rng(state["rng"])
    return state


def collect_predictions(
    model: DERSXModel,
    loader: DataLoader,
    device: torch.device,
    diagnostics: bool = False,
) -> pd.DataFrame:
    model.eval()
    rows: List[Dict[str, Any]] = []
    with torch.inference_mode():
        for batch in tqdm(loader, desc="predict", leave=False):
            device_batch = move_to_device(batch, device)
            with autocast_context(model.cfg.amp and device.type == "cuda"):
                output = model(
                    device_batch["input_values"],
                    device_batch["audio_attention_mask"],
                    device_batch["input_ids"],
                    device_batch["text_attention_mask"],
                    diagnostics=diagnostics,
                )
            distress = output["distress_pred"].float().cpu().numpy()
            logits = output["emotion_logits"].float().cpu().numpy()
            diagnostics_output = output.get("diagnostics", {})
            fused = (
                output["fused"].float().cpu().numpy()
                if model.cfg.save_fused_embeddings
                else None
            )
            for index in range(len(batch["utterance_id"])):
                row: Dict[str, Any] = {
                    "utterance_id": batch["utterance_id"][index],
                    "dialog_id": batch["dialog_id"][index],
                    "speaker_id": batch["speaker_id"][index],
                    "start_time": batch["start_time"][index],
                    "y_distress_cont": float(batch["distress_cont"][index]),
                    "y_distress_bin": int(batch["distress_bin"][index]),
                    "y_emotion": int(batch["emotion_id"][index]),
                    "pred_distress_cont": float(distress[index]),
                }
                for class_index in range(len(EMOTION_LABELS)):
                    row[f"logit_{class_index}"] = float(
                        logits[index, class_index]
                    )
                for key, value in diagnostics_output.items():
                    row[key] = float(value[index].detach().cpu())
                if fused is not None:
                    row["fused_embedding"] = fused[index].astype(np.float16)
                metadata = batch["degradation_meta"][index]
                row.update(
                    {
                        f"degradation_{key}": value
                        for key, value in metadata.items()
                    }
                )
                rows.append(row)
    return pd.DataFrame(rows)


def validation_metrics(
    model: DERSXModel,
    loader: DataLoader,
    device: torch.device,
    stats: TargetStats,
) -> Tuple[Dict[str, float], pd.DataFrame]:
    predictions = collect_predictions(model, loader, device, diagnostics=False)
    scores = score_prediction_frame(predictions, stats)
    return {
        "macro_f1": scores["distress"]["macro_f1"],
        "mae": scores["regression"]["mae"],
    }, predictions

In [14]:
def train_resumable(
    model: DERSXModel,
    train_df: pd.DataFrame,
    val_df: pd.DataFrame,
    stats: TargetStats,
    tokenizer: Any,
    feature_extractor: Any,
    task_dir: Path,
    seed: int,
) -> Dict[str, Any]:
    seed_everything(seed)
    local_cfg = model.cfg
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model.to(device)
    train_loader, train_sampler = build_loader(
        train_df, tokenizer, feature_extractor, seed, True
    )
    val_loader, _ = build_loader(
        val_df, tokenizer, feature_extractor, seed + 1, False
    )
    accumulation_steps = (
        local_cfg.effective_batch_size // local_cfg.micro_batch_size
    )
    steps_per_epoch = math.ceil(len(train_sampler) / accumulation_steps)
    total_steps = steps_per_epoch * local_cfg.max_epochs
    optimizer, scheduler = optimizer_and_scheduler(
        model, total_steps, local_cfg
    )
    scaler = make_scaler(local_cfg.amp and device.type == "cuda")
    criterion = JointLoss(class_weights(train_df), local_cfg).to(device)
    fingerprint = fingerprint_frame(
        pd.concat(
            [
                train_df.assign(split="train"),
                val_df.assign(split="val"),
            ]
        ),
        ["utterance_id", "split", "distress_cont", "emotion_id"],
    )
    latest_path = task_dir / "latest.pt"
    best_path = task_dir / "best.pt"
    history: List[Dict[str, Any]] = []
    start_epoch = 0
    start_batch = 0
    global_step = 0
    best_f1 = -np.inf
    best_mae = np.inf
    bad_epochs = 0
    if latest_path.exists() and not cfg.force_recompute:
        state = load_training_checkpoint(
            latest_path,
            model,
            optimizer,
            scheduler,
            scaler,
            fingerprint,
        )
        start_epoch = int(state["epoch"])
        start_batch = int(state["next_batch"])
        global_step = int(state["global_step"])
        best_f1 = float(state["best_f1"])
        best_mae = float(state["best_mae"])
        bad_epochs = int(state["bad_epochs"])
        history = list(state.get("history", []))
        logger.info(
            "Resumed %s at epoch=%d batch=%d step=%d",
            task_dir,
            start_epoch,
            start_batch,
            global_step,
        )

    status = "running"
    for epoch in range(start_epoch, local_cfg.max_epochs):
        epoch_started = time.perf_counter()
        epoch_start_batch = start_batch if epoch == start_epoch else 0
        train_sampler.set_epoch(epoch, epoch_start_batch)
        model.train()
        optimizer.zero_grad(set_to_none=True)
        loss_sums: Dict[str, float] = defaultdict(float)
        seen_batches = 0
        remaining_batches = len(train_sampler) - epoch_start_batch
        progress = tqdm(
            enumerate(train_loader, start=epoch_start_batch),
            total=remaining_batches,
            desc=f"epoch {epoch + 1}",
        )
        for batch_index, batch in progress:
            device_batch = move_to_device(batch, device)
            cycle_start = (batch_index // accumulation_steps) * accumulation_steps
            cycle_end = min(
                cycle_start + accumulation_steps, len(train_sampler)
            )
            cycle_length = max(1, cycle_end - cycle_start)
            with autocast_context(local_cfg.amp and device.type == "cuda"):
                output = model(
                    device_batch["input_values"],
                    device_batch["audio_attention_mask"],
                    device_batch["input_ids"],
                    device_batch["text_attention_mask"],
                    diagnostics=False,
                )
                loss, components = criterion(output, device_batch)
                scaled_loss = loss / cycle_length
            scaler.scale(scaled_loss).backward()
            for key, value in components.items():
                loss_sums[key] += float(value)
            seen_batches += 1
            at_optimizer_boundary = (batch_index + 1) >= cycle_end
            if not at_optimizer_boundary:
                continue

            scaler.unscale_(optimizer)
            torch.nn.utils.clip_grad_norm_(
                model.parameters(), local_cfg.grad_clip
            )
            scaler.step(optimizer)
            scaler.update()
            optimizer.zero_grad(set_to_none=True)
            scheduler.step()
            global_step += 1

            if global_step % local_cfg.log_every_optimizer_steps == 0:
                snapshot = gpu_snapshot()
                logger.info(
                    "train task=%s epoch=%d batch=%d/%d step=%d "
                    "loss=%.4f ce=%.4f mse=%.4f gpu=%s",
                    task_dir.name,
                    epoch + 1,
                    batch_index + 1,
                    len(train_sampler),
                    global_step,
                    components["loss"],
                    components["ce"],
                    components["mse"],
                    json.dumps(snapshot),
                )
                log_metric(
                    "train_step",
                    task=str(task_dir),
                    epoch=epoch,
                    batch=batch_index,
                    step=global_step,
                    **components,
                    **snapshot,
                )

            if (
                global_step % local_cfg.checkpoint_every_optimizer_steps == 0
                or budget.should_stop()
            ):
                save_training_checkpoint(
                    latest_path,
                    model,
                    optimizer,
                    scheduler,
                    scaler,
                    epoch,
                    batch_index + 1,
                    global_step,
                    best_f1,
                    best_mae,
                    bad_epochs,
                    fingerprint,
                    history,
                )
            if budget.should_stop():
                logger.warning(
                    "Deadline guard reached; saved %s", latest_path
                )
                status = "paused_deadline"
                break

        if status == "paused_deadline":
            break
        start_batch = 0
        validation_scores, _ = validation_metrics(
            model, val_loader, device, stats
        )
        history_row = {
            "epoch": epoch + 1,
            "train_loss": loss_sums["loss"] / max(seen_batches, 1),
            "train_ce": loss_sums["ce"] / max(seen_batches, 1),
            "train_mse": loss_sums["mse"] / max(seen_batches, 1),
            "val_macro_f1": validation_scores["macro_f1"],
            "val_mae": validation_scores["mae"],
            "global_step": global_step,
            "epoch_seconds": time.perf_counter() - epoch_started,
        }
        history.append(history_row)
        pd.DataFrame(history).to_csv(
            task_dir / "training_history.csv", index=False
        )
        logger.info(
            "Epoch %02d task=%s train_loss=%.4f "
            "val_macro_f1=%.4f val_mae=%.4f epoch_seconds=%.1f",
            epoch + 1,
            task_dir.name,
            history_row["train_loss"],
            history_row["val_macro_f1"],
            history_row["val_mae"],
            history_row["epoch_seconds"],
        )
        log_metric("epoch_end", task=str(task_dir), **history_row)
        improved = (
            history_row["val_macro_f1"] > best_f1 + 1e-8
            or (
                abs(history_row["val_macro_f1"] - best_f1) <= 1e-8
                and history_row["val_mae"] < best_mae
            )
        )
        if improved:
            best_f1 = history_row["val_macro_f1"]
            best_mae = history_row["val_mae"]
            bad_epochs = 0
            atomic_torch_save(
                {
                    "model": model.state_dict(),
                    "epoch": epoch,
                    "best_f1": best_f1,
                    "best_mae": best_mae,
                    "method_signature": method_signature(local_cfg),
                    "config": asdict(local_cfg),
                },
                best_path,
            )
        else:
            bad_epochs += 1
        save_training_checkpoint(
            latest_path,
            model,
            optimizer,
            scheduler,
            scaler,
            epoch + 1,
            0,
            global_step,
            best_f1,
            best_mae,
            bad_epochs,
            fingerprint,
            history,
        )
        if bad_epochs >= local_cfg.patience:
            status = "early_stopped"
            break
    else:
        status = "completed_max_epochs"

    if status != "paused_deadline" and best_path.exists():
        model.load_state_dict(
            torch.load(
                best_path, map_location=device, weights_only=False
            )["model"]
        )
    return {
        "status": status,
        "history": history,
        "global_step": global_step,
        "best_f1": best_f1,
        "best_mae": best_mae,
        "model": model,
        "device": device,
    }

## 11. Generic train/calibrate/test bundle and IEMOCAP LOSO

Each completed task stores its exact split, target statistics, temperature, predictions, metrics, parameter counts, configuration signature, and scope. Existing `done.json` files are reused on rerun.

In [15]:
def vocabulary_from(
    frame: pd.DataFrame, limit: int = 50000
) -> List[str]:
    counts: Dict[str, int] = defaultdict(int)
    for text in frame.transcript.astype(str):
        for word in normalize_transcript(text, cfg.fallback_text).split():
            counts[word] += 1
    return [
        word
        for word, _ in sorted(
            counts.items(), key=lambda item: (-item[1], item[0])
        )[:limit]
    ]


def evaluate_trained_bundle(
    model: DERSXModel,
    splits: Dict[str, pd.DataFrame],
    stats: TargetStats,
    tokenizer: Any,
    feature_extractor: Any,
    task_dir: Path,
    scope: Dict[str, Any],
) -> Dict[str, Any]:
    device = next(model.parameters()).device
    vocabulary = vocabulary_from(splits["train"])
    calibration_loader, _ = build_loader(
        splits["cal"],
        tokenizer,
        feature_extractor,
        13,
        False,
        vocab=vocabulary,
    )
    test_loader, _ = build_loader(
        splits["test"],
        tokenizer,
        feature_extractor,
        17,
        False,
        vocab=vocabulary,
    )
    calibration_predictions = collect_predictions(
        model, calibration_loader, device, diagnostics=False
    )
    valid = calibration_predictions.y_emotion.to_numpy() >= 0
    temperature = 1.0
    if valid.any():
        logit_columns = [
            f"logit_{index}" for index in range(len(EMOTION_LABELS))
        ]
        logits = calibration_predictions.loc[valid, logit_columns].to_numpy()
        labels = calibration_predictions.loc[valid, "y_emotion"].to_numpy()
        temperature = float(
            TemperatureScaler().fit(logits, labels).temperature.detach()
        )
    test_predictions = collect_predictions(
        model,
        test_loader,
        device,
        diagnostics=model.cfg.attention_diagnostics,
    )
    uncalibrated_metrics = score_prediction_frame(
        test_predictions, stats, None
    )
    calibrated_metrics = score_prediction_frame(
        test_predictions, stats, temperature
    )
    dialog_predictions, dialog_metrics = aggregate_dialog(
        test_predictions, stats, temperature
    )
    for index in range(len(EMOTION_LABELS)):
        test_predictions[f"cal_logit_{index}"] = (
            test_predictions[f"logit_{index}"] / temperature
        )
    test_predictions.to_pickle(task_dir / "test_predictions.pkl")
    test_predictions.drop(
        columns=["fused_embedding"], errors="ignore"
    ).to_csv(task_dir / "test_predictions.csv", index=False)
    dialog_predictions.to_csv(
        task_dir / "dialog_predictions.csv", index=False
    )
    payload = {
        "status": "complete",
        "scope": scope,
        "temperature": temperature,
        "target_stats": asdict(stats),
        "metrics_uncalibrated": uncalibrated_metrics,
        "metrics_calibrated": calibrated_metrics,
        "dialog_metrics": dialog_metrics,
        "rows": {name: len(part) for name, part in splits.items()},
        "method_signature": method_signature(model.cfg),
        "task_config": asdict(model.cfg),
    }
    atomic_json_dump(payload, task_dir / "metrics.json")
    atomic_json_dump(payload, task_dir / "done.json")
    return payload


def run_train_bundle(
    splits: Dict[str, pd.DataFrame],
    stats: TargetStats,
    task_dir: Path,
    seed: int,
    tokenizer: Any,
    feature_extractor: Any,
    scope: Dict[str, Any],
    local_cfg: Optional[DERSXConfig] = None,
) -> Dict[str, Any]:
    task_dir.mkdir(parents=True, exist_ok=True)
    done_path = task_dir / "done.json"
    if done_path.exists() and not cfg.force_recompute:
        return json.loads(done_path.read_text(encoding="utf-8"))
    task_cfg = local_cfg or cfg
    model = DERSXModel(len(tokenizer), task_cfg)
    logger.info(
        "Task %s parameters=%s scope=%s",
        task_dir,
        trainable_parameter_report(model),
        scope,
    )
    result = train_resumable(
        model,
        splits["train"],
        splits["val"],
        stats,
        tokenizer,
        feature_extractor,
        task_dir,
        seed,
    )
    if result["status"] == "paused_deadline":
        return {"status": "paused_deadline", "scope": scope}
    return evaluate_trained_bundle(
        result["model"],
        splits,
        stats,
        tokenizer,
        feature_extractor,
        task_dir,
        scope,
    )


def run_iemocap_fold(
    df: pd.DataFrame,
    heldout_speaker: str,
    seed: int,
    tokenizer: Any,
    feature_extractor: Any,
    stage: str = "main",
    local_cfg: Optional[DERSXConfig] = None,
) -> Dict[str, Any]:
    splits = prepare_iemocap_loso(df, heldout_speaker, seed)
    stats = splits.pop("target_stats")
    task_dir = RUN_DIR / stage / f"seed_{seed}" / heldout_speaker
    task_dir.mkdir(parents=True, exist_ok=True)
    for name, part in splits.items():
        part[["utterance_id", "dialog_id", "speaker_id"]].to_csv(
            task_dir / f"{name}_ids.csv", index=False
        )
    scope = {
        "corpus": "IEMOCAP",
        "protocol": "strict_LOSO",
        "heldout_speaker": heldout_speaker,
        "seed": seed,
        "stage": stage,
        "profile": cfg.profile,
    }
    return run_train_bundle(
        splits,
        stats,
        task_dir,
        seed,
        tokenizer,
        feature_extractor,
        scope,
        local_cfg,
    )


def run_main_loso(
    df: pd.DataFrame,
    tokenizer: Any,
    feature_extractor: Any,
    seeds: Sequence[int],
    folds: Sequence[str],
) -> pd.DataFrame:
    rows: List[Dict[str, Any]] = []
    for seed in seeds:
        for speaker in folds:
            if budget.should_stop():
                return pd.DataFrame(rows)
            result = run_iemocap_fold(
                df,
                speaker,
                seed,
                tokenizer,
                feature_extractor,
            )
            rows.append(
                {
                    "seed": seed,
                    "speaker": speaker,
                    "status": result.get("status"),
                    "metrics_path": str(
                        RUN_DIR
                        / "main"
                        / f"seed_{seed}"
                        / speaker
                        / "metrics.json"
                    ),
                }
            )
            if result.get("status") == "paused_deadline":
                return pd.DataFrame(rows)
    summary = pd.DataFrame(rows)
    summary.to_csv(RUN_DIR / "main" / "task_summary.csv", index=False)
    return summary

## 12. Fold-average, pooled, class-wise, and report tables

Only generated prediction files are consumed. There is no dictionary of manuscript scores and no fallback to reported values.

In [16]:
def flatten_numeric(
    prefix: str, value: Any, output: Dict[str, float]
) -> None:
    if isinstance(value, Mapping):
        for key, child in value.items():
            flatten_numeric(
                f"{prefix}_{key}" if prefix else str(key), child, output
            )
    elif (
        isinstance(value, (int, float, np.number))
        and not isinstance(value, bool)
    ):
        output[prefix] = float(value)


def collect_completed_metrics(stage: str = "main") -> pd.DataFrame:
    rows: List[Dict[str, Any]] = []
    for path in (RUN_DIR / stage).glob("seed_*/*/metrics.json"):
        payload = json.loads(path.read_text(encoding="utf-8"))
        row: Dict[str, Any] = {
            "seed": int(path.parent.parent.name.split("_")[-1]),
            "fold": path.parent.name,
            "path": str(path),
        }
        flatten_numeric("", payload, row)
        rows.append(row)
    return pd.DataFrame(rows)


def pooled_loso(
    stage: str = "main", seed: Optional[int] = None
) -> Dict[str, Any]:
    paths = list((RUN_DIR / stage).glob("seed_*/*/test_predictions.pkl"))
    if seed is not None:
        paths = [
            path
            for path in paths
            if path.parent.parent.name == f"seed_{seed}"
        ]
    if not paths:
        return {"status": "no_predictions"}
    frames: List[pd.DataFrame] = []
    for path in paths:
        metrics_path = path.parent / "metrics.json"
        if not metrics_path.exists():
            continue
        metrics = json.loads(metrics_path.read_text(encoding="utf-8"))
        stats = TargetStats(**metrics["target_stats"])
        frame = pd.read_pickle(path)
        frame["fold"] = path.parent.name
        frame["seed"] = int(path.parent.parent.name.split("_")[-1])
        frame["pred_distress_bin"] = continuous_to_bins(
            frame.pred_distress_cont.to_numpy(), stats
        )
        frames.append(frame)
    if not frames:
        return {"status": "no_complete_predictions"}
    predictions = pd.concat(frames, ignore_index=True)
    result: Dict[str, Any] = {
        "status": "complete",
        "scope_note": (
            "Pooled once across all held-out predictions for the selected seed; "
            "seed=None concatenates repeats and is diagnostic only."
        ),
        "rows": len(predictions),
        "distress": ordinal_metrics(
            predictions.y_distress_bin,
            predictions.pred_distress_bin,
        ),
        "regression": regression_metrics(
            predictions.y_distress_cont,
            predictions.pred_distress_cont,
        ),
    }
    valid = predictions.y_emotion.to_numpy() >= 0
    calibrated_columns = [
        f"cal_logit_{index}" for index in range(len(EMOTION_LABELS))
    ]
    if valid.any() and set(calibrated_columns).issubset(predictions.columns):
        logits = predictions.loc[valid, calibrated_columns].to_numpy()
        labels = predictions.loc[valid, "y_emotion"].to_numpy()
        probabilities = softmax_np(logits)
        emotion_predictions = probabilities.argmax(axis=1)
        result["emotion"] = {
            "macro_f1": float(
                f1_score(
                    labels,
                    emotion_predictions,
                    labels=range(len(EMOTION_LABELS)),
                    average="macro",
                    zero_division=0,
                )
            ),
            "ece": ece_score(probabilities, labels, cfg.ece_bins),
            "class_report": classification_report(
                labels,
                emotion_predictions,
                labels=range(len(EMOTION_LABELS)),
                target_names=EMOTION_LABELS,
                zero_division=0,
                output_dict=True,
            ),
        }
    atomic_json_dump(
        result,
        RUN_DIR
        / stage
        / f"pooled_seed_{seed if seed is not None else 'all'}.json",
    )
    return result


def frame_as_markdown(frame: pd.DataFrame) -> str:
    try:
        return frame.to_markdown(index=False)
    except ImportError:
        return "```text\n" + frame.to_string(index=False) + "\n```"


def generate_progress_report() -> Path:
    metric_frame = collect_completed_metrics("main")
    task_state = (
        json.loads(TASK_STATUS_PATH.read_text(encoding="utf-8"))
        if TASK_STATUS_PATH.exists()
        else {}
    )
    lines = [
        "# DERS-X generated experiment report",
        "",
        f"Profile: `{cfg.profile}`",
        f"Campaign directory: `{RUN_DIR}`",
        f"Remaining campaign hours: {budget.remaining_seconds / 3600:.2f}",
        "",
    ]
    if not metric_frame.empty:
        selected = metric_frame[
            [
                column
                for column in [
                    "seed",
                    "fold",
                    "metrics_calibrated_distress_macro_f1",
                    "metrics_calibrated_regression_pearson_r",
                    "dialog_metrics_distress_qwk",
                    "metrics_calibrated_emotion_ece",
                ]
                if column in metric_frame
            ]
        ]
        lines += [
            "## Completed main LOSO folds",
            "",
            frame_as_markdown(selected),
            "",
        ]
        fold_columns = [
            column
            for column in metric_frame.columns
            if column.startswith("metrics_calibrated_")
            or column.startswith("dialog_metrics_")
        ]
        numeric = metric_frame[fold_columns].select_dtypes(
            include=[np.number]
        )
        if not numeric.empty:
            summary = pd.DataFrame(
                {"mean": numeric.mean(), "std": numeric.std(ddof=0)}
            ).reset_index(names="metric")
            lines += [
                "## Fold-average metrics",
                "",
                frame_as_markdown(summary),
                "",
            ]
    pooled = pooled_loso("main", cfg.budget_primary_seed)
    lines += [
        "## Pooled available held-out predictions",
        "",
        "```json",
        json.dumps(pooled, indent=2, default=str),
        "```",
        "",
        "## Task registry",
        "",
        "```json",
        json.dumps(task_state, indent=2, default=str),
        "```",
        "",
        "## Interpretation boundary",
        "",
        "Rows marked reduced-scope or budget-profile are not the exact full "
        "manuscript protocol. Missing or blocked tasks are not replaced by "
        "manuscript values.",
    ]
    report_path = RUN_DIR / "REPORT.md"
    report_path.write_text("\n".join(lines), encoding="utf-8")
    return report_path

## 13. Bidirectional cross-corpus transfer

The source corpus is split into train/validation/calibration. The target corpus is never used to update model weights. A target reference partition is used only to define its corpus-specific standardized proxy labels; this operational choice is recorded because the manuscript does not fully specify target-side normalization.

In [17]:
def make_msp_source_split(msp:pd.DataFrame,seed:int) -> Dict[str,Any]:
    train_part=select_msp_partition(msp,"Train")
    dev_part=select_msp_partition(msp,"Development")
    if train_part.empty:
        return prepare_all_dialog_split(msp,"MSP-Podcast",seed)
    if dev_part.empty:
        train,val,cal=split_dialogs_three_way(train_part,seed)
    else:
        train=train_part.copy();val,cal,_=split_dialogs_three_way(dev_part,seed,train_frac=0.5,val_frac=0.49)
    stats=fit_target_stats(train,"MSP-Podcast")
    return {"train":apply_target_stats(train,stats),"val":apply_target_stats(val,stats),"cal":apply_target_stats(cal,stats),"target_stats":stats}


def target_reference_and_test(df:pd.DataFrame,corpus:str,seed:int,test_partition:Optional[str]=None) -> Tuple[pd.DataFrame,pd.DataFrame,TargetStats]:
    if corpus=="MSP-Podcast" and test_partition:
        test=select_msp_partition(df,test_partition);reference=select_msp_partition(df,"Train")
        if test.empty: raise ValueError(f"MSP target partition {test_partition} not found")
        if reference.empty: reference,test,_=split_dialogs_three_way(df,seed)
    else:
        reference,test,_=split_dialogs_three_way(df,seed,train_frac=0.20,val_frac=0.79)
    stats=fit_target_stats(reference,corpus);return apply_target_stats(reference,stats),apply_target_stats(test,stats),stats


def run_cross_corpus(direction:str,iemocap:pd.DataFrame,msp:pd.DataFrame,tokenizer:Any,feature_extractor:Any,seed:int=13) -> Dict[str,Any]:
    direction=direction.lower();task_dir=RUN_DIR/"cross_corpus"/direction/f"seed_{seed}";done=task_dir/"done.json"
    if done.exists() and not cfg.force_recompute:return json.loads(done.read_text(encoding="utf-8"))
    if direction=="iemocap_to_msp":
        src=prepare_all_dialog_split(iemocap,"IEMOCAP",seed);src_stats=src.pop("target_stats");_,target_test,target_stats=target_reference_and_test(msp,"MSP-Podcast",seed,cfg.msp_test_partition)
    elif direction=="msp_to_iemocap":
        src=make_msp_source_split(msp,seed);src_stats=src.pop("target_stats");_,target_test,target_stats=target_reference_and_test(iemocap,"IEMOCAP",seed)
    else:raise ValueError(direction)
    # Train and calibrate on source, then evaluate target with source prediction thresholds and target ground-truth bins.
    src_with_placeholder={**src,"test":src["val"].copy()}
    scope={"protocol":"cross_corpus","direction":direction,"seed":seed,"target_normalization":"target_reference_partition","profile":cfg.profile}
    train_result=run_train_bundle(src_with_placeholder,src_stats,task_dir/"source_training",seed,tokenizer,feature_extractor,scope)
    if train_result.get("status")=="paused_deadline":return train_result
    best=torch.load(task_dir/"source_training"/"best.pt",map_location="cpu",weights_only=False)
    saved_cfg=DERSXConfig(**best.get("config",asdict(cfg)))
    model=DERSXModel(len(tokenizer),saved_cfg)
    model.load_state_dict(best["model"])
    device=torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model.to(device)
    temp=float(json.loads((task_dir/"source_training"/"metrics.json").read_text())["temperature"])
    vocab=vocabulary_from(src["train"]);loader,_=build_loader(target_test,tokenizer,feature_extractor,seed+9,False,vocab=vocab);pred=collect_predictions(model,loader,device,diagnostics=model.cfg.attention_diagnostics)
    pred["pred_distress_bin"]=continuous_to_bins(pred.pred_distress_cont,src_stats);pred["y_distress_bin"]=target_test.set_index("utterance_id").loc[pred.utterance_id,"distress_bin"].to_numpy()
    metrics={"regression":regression_metrics(pred.y_distress_cont,pred.pred_distress_cont),"distress":ordinal_metrics(pred.y_distress_bin,pred.pred_distress_bin)}
    payload={"status":"complete","scope":scope,"source_target_stats":asdict(src_stats),"target_reference_stats":asdict(target_stats),"temperature":temp,"metrics":metrics,"target_rows":len(pred)}
    task_dir.mkdir(parents=True,exist_ok=True);pred.to_csv(task_dir/"target_predictions.csv",index=False);atomic_json_dump(payload,task_dir/"metrics.json");atomic_json_dump(payload,done);return payload

## 14. Ablations

Neural fusion and regression-head variants retrain the same leakage-controlled fold. The log-Mel CNN variant uses the same multimodal framework. TF-IDF and optional GloVe baselines fit continuous distress regression and derive four bins from the training-fold thresholds.

In [18]:
FUSION_VARIANTS=("audio_only","text_only","early_concat","late_average","cross_attention")
REGRESSION_VARIANTS=("linear","one_relu","two_gelu","three_gelu")


def run_neural_ablation(df:pd.DataFrame,fold:str,seed:int,tokenizer:Any,feature_extractor:Any,family:str) -> pd.DataFrame:
    rows=[]
    variants=FUSION_VARIANTS if family=="fusion" else REGRESSION_VARIANTS
    for variant in variants:
        if budget.should_stop():break
        local=replace(cfg,fusion_mode=(variant if family=="fusion" else cfg.fusion_mode),regression_head=(variant if family=="regression" else cfg.regression_head))
        result=run_iemocap_fold(df,fold,seed,tokenizer,feature_extractor,stage=f"ablations/{family}/{variant}",local_cfg=local)
        rows.append({"family":family,"variant":variant,"fold":fold,"seed":seed,"status":result.get("status")})
        if result.get("status")=="paused_deadline":break
    out=pd.DataFrame(rows);path=RUN_DIR/"ablations"/family/f"{fold}_seed_{seed}_tasks.csv";path.parent.mkdir(parents=True,exist_ok=True);out.to_csv(path,index=False);return out


def run_logmel_ablation(df:pd.DataFrame,fold:str,seed:int,tokenizer:Any,feature_extractor:Any) -> Dict[str,Any]:
    local=replace(cfg,audio_backbone="logmel_cnn",fusion_mode="audio_only",audio_unfreeze_last_n=0)
    return run_iemocap_fold(df,fold,seed,tokenizer,feature_extractor,stage="ablations/encoder/logmel_cnn",local_cfg=local)


def run_tfidf_baseline(df:pd.DataFrame,fold:str,seed:int) -> Dict[str,Any]:
    task_dir=RUN_DIR/"ablations"/"encoder"/"tfidf"/f"seed_{seed}"/fold;done=task_dir/"done.json"
    if done.exists() and not cfg.force_recompute:return json.loads(done.read_text())
    splits=prepare_iemocap_loso(df,fold,seed);stats=splits.pop("target_stats")
    vec=TfidfVectorizer(max_features=30000,ngram_range=(1,2),min_df=2,sublinear_tf=True)
    x_train=vec.fit_transform(splits["train"].transcript);x_test=vec.transform(splits["test"].transcript);reg=Ridge(alpha=1.0).fit(x_train,splits["train"].distress_cont);pred=reg.predict(x_test)
    metrics={"regression":regression_metrics(splits["test"].distress_cont,pred),"distress":ordinal_metrics(splits["test"].distress_bin,continuous_to_bins(pred,stats))}
    payload={"status":"complete","scope":{"fold":fold,"seed":seed,"encoder":"TF-IDF"},"metrics":metrics};task_dir.mkdir(parents=True,exist_ok=True);atomic_json_dump(payload,done);return payload


def load_glove_subset(path:str,vocab:set[str]) -> Tuple[Dict[str,np.ndarray],int]:
    vectors={};dim=0
    with Path(path).expanduser().open("r",encoding="utf-8",errors="ignore") as f:
        for line in f:
            parts=line.rstrip().split(" ");word=parts[0]
            if word in vocab:
                vec=np.asarray(parts[1:],dtype=np.float32);dim=len(vec);vectors[word]=vec
    return vectors,dim


def run_glove_baseline(df:pd.DataFrame,fold:str,seed:int) -> Dict[str,Any]:
    if not cfg.glove_path or not Path(cfg.glove_path).expanduser().exists():return {"status":"blocked_missing_glove","path":cfg.glove_path}
    task_dir=RUN_DIR/"ablations"/"encoder"/"glove"/f"seed_{seed}"/fold;done=task_dir/"done.json"
    if done.exists() and not cfg.force_recompute:return json.loads(done.read_text())
    splits=prepare_iemocap_loso(df,fold,seed);stats=splits.pop("target_stats");vocab=set(" ".join(splits["train"].transcript.astype(str)).split());vectors,dim=load_glove_subset(cfg.glove_path,vocab)
    def encode(texts):
        out=[]
        for text in texts:
            vs=[vectors[w] for w in str(text).split() if w in vectors];out.append(np.mean(vs,axis=0) if vs else np.zeros(dim,dtype=np.float32))
        return np.stack(out)
    reg=Ridge(alpha=1.0).fit(encode(splits["train"].transcript),splits["train"].distress_cont);pred=reg.predict(encode(splits["test"].transcript));metrics={"regression":regression_metrics(splits["test"].distress_cont,pred),"distress":ordinal_metrics(splits["test"].distress_bin,continuous_to_bins(pred,stats))}
    payload={"status":"complete","scope":{"fold":fold,"seed":seed,"encoder":"GloVe","dimension":dim},"metrics":metrics};task_dir.mkdir(parents=True,exist_ok=True);atomic_json_dump(payload,done);return payload

## 15. Dialog-context operationalization

The manuscript's main architecture is utterance-level and does not specify a contextual module despite reporting a context ablation. This notebook therefore treats context as a separate diagnostic: a one-layer bidirectional GRU refines **frozen, leakage-controlled DERS-X fused embeddings** within each dialog. The report names this implementation explicitly.

In [19]:
class DialogEmbeddingDataset(Dataset):
    def __init__(self, frame:pd.DataFrame, embeddings:Mapping[str,np.ndarray]):
        self.items=[]
        for dialog,g in frame.sort_values(["dialog_id","start_time","utterance_id"]).groupby("dialog_id"):
            ids=[u for u in g.utterance_id if u in embeddings]
            if not ids:continue
            rows=g.set_index("utterance_id").loc[ids]
            self.items.append((dialog,ids,np.stack([embeddings[u] for u in ids]),rows.distress_cont.to_numpy(np.float32),rows.distress_bin.to_numpy(np.int64)))
    def __len__(self):return len(self.items)
    def __getitem__(self,i):return self.items[i]


def dialog_collate(batch):
    max_len=max(len(x[1]) for x in batch);dim=batch[0][2].shape[1];x=torch.zeros(len(batch),max_len,dim);y=torch.zeros(len(batch),max_len);bins=torch.zeros(len(batch),max_len,dtype=torch.long);mask=torch.zeros(len(batch),max_len,dtype=torch.bool);ids=[];dialogs=[]
    for i,(d,u,e,t,b) in enumerate(batch):
        n=len(u);x[i,:n]=torch.tensor(e);y[i,:n]=torch.tensor(t);bins[i,:n]=torch.tensor(b);mask[i,:n]=True;ids.append(u);dialogs.append(d)
    return {"x":x,"y":y,"bins":bins,"mask":mask,"ids":ids,"dialogs":dialogs}


class DialogContextGRU(nn.Module):
    def __init__(self,dim:int):super().__init__();self.gru=nn.GRU(dim,128,batch_first=True,bidirectional=True);self.head=nn.Sequential(nn.Linear(256,128),nn.GELU(),nn.Dropout(0.2),nn.Linear(128,1))
    def forward(self,x):return self.head(self.gru(x)[0]).squeeze(-1)


def extract_fused_embeddings(model:DERSXModel,frame:pd.DataFrame,tokenizer:Any,feature_extractor:Any,device:torch.device) -> Dict[str,np.ndarray]:
    loader,_=build_loader(frame,tokenizer,feature_extractor,31,False);model.eval();out={}
    with torch.inference_mode():
        for batch in loader:
            dev=move_to_device(batch,device);result=model(dev["input_values"],dev["audio_attention_mask"],dev["input_ids"],dev["text_attention_mask"])
            for uid,emb in zip(batch["utterance_id"],result["fused"].float().cpu().numpy()):out[uid]=emb.astype(np.float32)
    return out


def run_context_ablation(df:pd.DataFrame,fold:str,seed:int,tokenizer:Any,feature_extractor:Any) -> Dict[str,Any]:
    base_dir=RUN_DIR/"main"/f"seed_{seed}"/fold
    if not (base_dir/"best.pt").exists():return {"status":"blocked_missing_main_checkpoint"}
    task_dir=RUN_DIR/"ablations"/"context"/f"seed_{seed}"/fold;done=task_dir/"done.json"
    if done.exists() and not cfg.force_recompute:return json.loads(done.read_text())
    splits=prepare_iemocap_loso(df,fold,seed)
    stats=splits.pop("target_stats")
    saved=torch.load(base_dir/"best.pt",map_location="cpu",weights_only=False)
    saved_cfg=DERSXConfig(**saved.get("config",asdict(cfg)))
    model=DERSXModel(len(tokenizer),saved_cfg)
    model.load_state_dict(saved["model"])
    device=torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model.to(device)
    embeddings={}
    for part in splits.values():embeddings.update(extract_fused_embeddings(model,part,tokenizer,feature_extractor,device))
    train_ds=DialogEmbeddingDataset(splits["train"],embeddings);val_ds=DialogEmbeddingDataset(splits["val"],embeddings);test_ds=DialogEmbeddingDataset(splits["test"],embeddings)
    train_loader=DataLoader(train_ds,batch_size=8,shuffle=True,collate_fn=dialog_collate);val_loader=DataLoader(val_ds,batch_size=8,shuffle=False,collate_fn=dialog_collate);test_loader=DataLoader(test_ds,batch_size=8,shuffle=False,collate_fn=dialog_collate)
    ctx=DialogContextGRU(2*model.cfg.latent_dim).to(device);opt=torch.optim.AdamW(ctx.parameters(),lr=1e-3,weight_decay=0.01);best=None;best_f1=-1;bad=0
    for epoch in range(20):
        ctx.train()
        for b in train_loader:
            x,y,m=b["x"].to(device),b["y"].to(device),b["mask"].to(device);pred=ctx(x);loss=F.mse_loss(pred[m],y[m]);opt.zero_grad();loss.backward();opt.step()
        ctx.eval();ys=[];ps=[];bins=[]
        with torch.inference_mode():
            for b in val_loader:
                pred=ctx(b["x"].to(device)).cpu();m=b["mask"];ys.extend(b["y"][m].numpy());ps.extend(pred[m].numpy());bins.extend(b["bins"][m].numpy())
        f1=ordinal_metrics(bins,continuous_to_bins(ps,stats))["macro_f1"]
        if f1>best_f1:best_f1=f1;best=copy.deepcopy(ctx.state_dict());bad=0
        else:bad+=1
        if bad>=3:break
    ctx.load_state_dict(best);ys=[];ps=[];bins=[]
    with torch.inference_mode():
        for b in test_loader:
            pred=ctx(b["x"].to(device)).cpu();m=b["mask"];ys.extend(b["y"][m].numpy());ps.extend(pred[m].numpy());bins.extend(b["bins"][m].numpy())
    payload={"status":"complete","operationalization":"one-layer bidirectional GRU over frozen fused utterance embeddings","metrics":{"regression":regression_metrics(ys,ps),"distress":ordinal_metrics(bins,continuous_to_bins(ps,stats))}}
    task_dir.mkdir(parents=True,exist_ok=True);atomic_json_dump(payload,done);return payload

## 16. Degradation evaluation and attention-shift tables

The same trained checkpoint and fold-specific temperature are reused across conditions. No degradation condition retrains the model. Attention shares are diagnostic, not causal explanations.

In [20]:
def load_saved_dersx_model(
    checkpoint_dir: Path,
    tokenizer: Any,
) -> Tuple[DERSXModel, torch.device, Dict[str, Any]]:
    best_path = checkpoint_dir / "best.pt"
    metrics_path = checkpoint_dir / "metrics.json"
    if not best_path.exists() or not metrics_path.exists():
        raise FileNotFoundError(
            f"Missing best.pt or metrics.json under {checkpoint_dir}"
        )
    saved = torch.load(best_path, map_location="cpu", weights_only=False)
    saved_cfg = DERSXConfig(**saved.get("config", asdict(cfg)))
    model = DERSXModel(len(tokenizer), saved_cfg)
    model.load_state_dict(saved["model"])
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model.to(device)
    metrics = json.loads(metrics_path.read_text(encoding="utf-8"))
    return model, device, metrics


def run_degradation_fold(
    df: pd.DataFrame,
    fold: str,
    seed: int,
    tokenizer: Any,
    feature_extractor: Any,
) -> pd.DataFrame:
    base = RUN_DIR / "main" / f"seed_{seed}" / fold
    if not (base / "best.pt").exists():
        return pd.DataFrame(
            [{"fold": fold, "status": "blocked_missing_main_checkpoint"}]
        )
    splits = prepare_iemocap_loso(df, fold, seed)
    stats = splits.pop("target_stats")
    model, device, base_metrics = load_saved_dersx_model(base, tokenizer)
    temperature = float(base_metrics["temperature"])
    vocabulary = vocabulary_from(splits["train"])
    rows: List[Dict[str, Any]] = []
    for degradation in DEGRADATION_GRID:
        condition_dir = (
            RUN_DIR
            / "degradation"
            / f"seed_{seed}"
            / fold
            / degradation.name
        )
        done_path = condition_dir / "done.json"
        if done_path.exists() and not cfg.force_recompute:
            payload = json.loads(done_path.read_text(encoding="utf-8"))
        else:
            if budget.should_stop():
                break
            loader, _ = build_loader(
                splits["test"],
                tokenizer,
                feature_extractor,
                seed + 100,
                False,
                degradation=degradation,
                vocab=vocabulary,
            )
            predictions = collect_predictions(
                model,
                loader,
                device,
                diagnostics=(model.cfg.fusion_mode == "cross_attention"),
            )
            score = score_prediction_frame(
                predictions, stats, temperature
            )
            payload = {
                "status": "complete",
                "fold": fold,
                "seed": seed,
                "condition": asdict(degradation),
                "metrics": score,
                "attention": {
                    "audio_share": float(
                        predictions.audio_attention_share.mean()
                    )
                    if "audio_attention_share" in predictions
                    else np.nan,
                    "text_share": float(
                        predictions.text_attention_share.mean()
                    )
                    if "text_attention_share" in predictions
                    else np.nan,
                },
                "realized_wer": float(
                    pd.to_numeric(
                        predictions.get("degradation_realized_wer", 0),
                        errors="coerce",
                    ).mean()
                ),
            }
            condition_dir.mkdir(parents=True, exist_ok=True)
            predictions.to_csv(
                condition_dir / "predictions.csv", index=False
            )
            atomic_json_dump(payload, done_path)
        flattened: Dict[str, Any] = {
            "fold": fold,
            "seed": seed,
            "condition": degradation.name,
            "status": payload.get("status"),
        }
        flatten_numeric("", payload, flattened)
        rows.append(flattened)
    output = pd.DataFrame(rows)
    output_dir = RUN_DIR / "degradation" / f"seed_{seed}" / fold
    output_dir.mkdir(parents=True, exist_ok=True)
    output.to_csv(output_dir / "summary.csv", index=False)
    return output


COMBINED_MODALITY_DEGRADATIONS = tuple(
    degradation
    for degradation in DEGRADATION_GRID
    if degradation.name
    in {
        "clean",
        "typical_15db_wer15",
        "challenging_10db_wer25",
        "extreme_5db_wer35",
    }
)


def run_modality_degradation_comparison(
    df: pd.DataFrame,
    fold: str,
    seed: int,
    tokenizer: Any,
    feature_extractor: Any,
) -> pd.DataFrame:
    """Generate the paper's multimodal/audio/text comparison under combined degradation."""
    checkpoint_dirs = {
        "multimodal": RUN_DIR / "main" / f"seed_{seed}" / fold,
        "audio_only": (
            RUN_DIR
            / "ablations"
            / "fusion"
            / "audio_only"
            / f"seed_{seed}"
            / fold
        ),
        "text_only": (
            RUN_DIR
            / "ablations"
            / "fusion"
            / "text_only"
            / f"seed_{seed}"
            / fold
        ),
    }
    missing = [
        name
        for name, directory in checkpoint_dirs.items()
        if not (directory / "best.pt").exists()
        or not (directory / "metrics.json").exists()
    ]
    if missing:
        return pd.DataFrame(
            [
                {
                    "fold": fold,
                    "seed": seed,
                    "status": "blocked_missing_modality_checkpoints",
                    "missing": ",".join(missing),
                }
            ]
        )

    splits = prepare_iemocap_loso(df, fold, seed)
    stats = splits.pop("target_stats")
    vocabulary = vocabulary_from(splits["train"])
    rows: List[Dict[str, Any]] = []
    for variant, checkpoint_dir in checkpoint_dirs.items():
        model, device, metrics = load_saved_dersx_model(
            checkpoint_dir, tokenizer
        )
        temperature = float(metrics["temperature"])
        for degradation in COMBINED_MODALITY_DEGRADATIONS:
            if budget.should_stop():
                break
            condition_dir = (
                RUN_DIR
                / "degradation_modality"
                / f"seed_{seed}"
                / fold
                / variant
                / degradation.name
            )
            done_path = condition_dir / "done.json"
            if done_path.exists() and not cfg.force_recompute:
                payload = json.loads(done_path.read_text(encoding="utf-8"))
            else:
                loader, _ = build_loader(
                    splits["test"],
                    tokenizer,
                    feature_extractor,
                    seed + 200,
                    False,
                    degradation=degradation,
                    vocab=vocabulary,
                )
                predictions = collect_predictions(
                    model,
                    loader,
                    device,
                    diagnostics=(variant == "multimodal"),
                )
                score = score_prediction_frame(
                    predictions, stats, temperature
                )
                payload = {
                    "status": "complete",
                    "fold": fold,
                    "seed": seed,
                    "variant": variant,
                    "condition": asdict(degradation),
                    "metrics": score,
                }
                condition_dir.mkdir(parents=True, exist_ok=True)
                predictions.to_csv(
                    condition_dir / "predictions.csv", index=False
                )
                atomic_json_dump(payload, done_path)
            flattened: Dict[str, Any] = {
                "fold": fold,
                "seed": seed,
                "variant": variant,
                "condition": degradation.name,
                "status": payload.get("status"),
            }
            flatten_numeric("", payload, flattened)
            rows.append(flattened)
        del model
        if torch.cuda.is_available():
            torch.cuda.empty_cache()
        if budget.should_stop():
            break
    output = pd.DataFrame(rows)
    output_dir = RUN_DIR / "degradation_modality" / f"seed_{seed}" / fold
    output_dir.mkdir(parents=True, exist_ok=True)
    output.to_csv(output_dir / "summary.csv", index=False)
    return output


def plot_generated_degradation(summary_csv: Path) -> None:
    frame = pd.read_csv(summary_csv)
    x = np.arange(len(frame))
    plt.figure(figsize=(11, 4))
    plt.plot(
        x,
        frame["metrics_distress_macro_f1"],
        marker="o",
        label="Macro-F1",
    )
    plt.plot(
        x,
        frame["metrics_regression_pearson_r"],
        marker="o",
        label="Pearson r",
    )
    if "metrics_emotion_ece" in frame:
        plt.plot(
            x,
            frame["metrics_emotion_ece"],
            marker="o",
            label="ECE",
        )
    plt.xticks(x, frame.condition, rotation=45, ha="right")
    plt.ylim(0, 1)
    plt.legend()
    plt.tight_layout()
    plt.show()

## 17. Automatic manuscript tables and figures

This generator consumes only completed prediction/checkpoint outputs. It writes publication-ready CSV tables and PNG figures as results become available. Missing experiments remain absent or explicitly blocked; manuscript-reported numbers are never substituted.

In [21]:
TABLE_DIR = RUN_DIR / "paper_tables"
FIGURE_DIR = RUN_DIR / "paper_figures"
TABLE_DIR.mkdir(parents=True, exist_ok=True)
FIGURE_DIR.mkdir(parents=True, exist_ok=True)


def read_json_if_exists(path: Path) -> Optional[Dict[str, Any]]:
    if not path.exists():
        return None
    return json.loads(path.read_text(encoding="utf-8"))


def save_table(name: str, frame: pd.DataFrame) -> Optional[Path]:
    if frame is None or frame.empty:
        return None
    path = TABLE_DIR / f"{name}.csv"
    frame.to_csv(path, index=False)
    return path


def metric_get(payload: Mapping[str, Any], *keys: str, default: Any = np.nan) -> Any:
    current: Any = payload
    for key in keys:
        if not isinstance(current, Mapping) or key not in current:
            return default
        current = current[key]
    return current


def collect_variant_metrics(family: str) -> pd.DataFrame:
    rows: List[Dict[str, Any]] = []
    root = RUN_DIR / "ablations" / family
    if not root.exists():
        return pd.DataFrame()
    for metrics_path in root.glob("*/seed_*/*/metrics.json"):
        payload = read_json_if_exists(metrics_path)
        if payload is None:
            continue
        rows.append(
            {
                "family": family,
                "variant": metrics_path.parents[2].name,
                "seed": int(metrics_path.parent.parent.name.split("_")[-1]),
                "fold": metrics_path.parent.name,
                "utterance_macro_f1": metric_get(payload, "metrics_calibrated", "distress", "macro_f1"),
                "utterance_accuracy": metric_get(payload, "metrics_calibrated", "distress", "accuracy"),
                "utterance_uar": metric_get(payload, "metrics_calibrated", "distress", "uar"),
                "pearson_r": metric_get(payload, "metrics_calibrated", "regression", "pearson_r"),
                "mae": metric_get(payload, "metrics_calibrated", "regression", "mae"),
                "dialog_qwk": metric_get(payload, "dialog_metrics", "distress", "qwk"),
                "ece_before": metric_get(payload, "metrics_uncalibrated", "emotion", "ece"),
                "ece_after": metric_get(payload, "metrics_calibrated", "emotion", "ece"),
                "metrics_path": str(metrics_path),
            }
        )
    return pd.DataFrame(rows)


def average_variant_metrics(frame: pd.DataFrame) -> pd.DataFrame:
    if frame.empty:
        return frame
    numeric = [
        column
        for column in frame.columns
        if column
        in {
            "utterance_macro_f1",
            "utterance_accuracy",
            "utterance_uar",
            "pearson_r",
            "mae",
            "dialog_qwk",
            "ece_before",
            "ece_after",
        }
    ]
    return (
        frame.groupby(["family", "variant"], as_index=False)[numeric]
        .agg(["mean", "std", "count"])
        .reset_index()
    )


def completed_main_prediction_paths(seed: Optional[int] = None) -> List[Path]:
    paths = list((RUN_DIR / "main").glob("seed_*/*/test_predictions.pkl"))
    if seed is not None:
        paths = [
            path
            for path in paths
            if path.parent.parent.name == f"seed_{seed}"
        ]
    return sorted(paths)


def dialog_pooled_available(seed: int) -> Dict[str, Any]:
    frames: List[pd.DataFrame] = []
    for prediction_path in completed_main_prediction_paths(seed):
        dialog_path = prediction_path.parent / "dialog_predictions.csv"
        metrics_path = prediction_path.parent / "metrics.json"
        if not dialog_path.exists() or not metrics_path.exists():
            continue
        frame = pd.read_csv(dialog_path)
        payload = read_json_if_exists(metrics_path)
        stats = TargetStats(**payload["target_stats"])
        frame["pred_distress_bin"] = continuous_to_bins(
            frame.pred_distress_cont.to_numpy(), stats
        )
        frame["fold"] = prediction_path.parent.name
        frames.append(frame)
    if not frames:
        return {"status": "no_dialog_predictions"}
    dialog = pd.concat(frames, ignore_index=True)
    return {
        "status": "complete",
        "rows": len(dialog),
        "regression": regression_metrics(
            dialog.y_distress_cont, dialog.pred_distress_cont
        ),
        "distress": ordinal_metrics(
            dialog.y_distress_bin, dialog.pred_distress_bin
        ),
    }


def training_seconds_for(directory: Path) -> float:
    history_path = directory / "training_history.csv"
    if not history_path.exists():
        return np.nan
    history = pd.read_csv(history_path)
    if "epoch_seconds" not in history or history.empty:
        return np.nan
    return float(history.epoch_seconds.mean())


def generate_manuscript_outputs(
    iemocap: Optional[pd.DataFrame] = None,
    msp: Optional[pd.DataFrame] = None,
) -> Dict[str, Any]:
    generated: Dict[str, Any] = {"tables": [], "figures": []}

    # Tables 2-3: analytic data actually parsed in this run.
    dataset_rows: List[Dict[str, Any]] = []
    class_rows: List[Dict[str, Any]] = []
    if iemocap is not None:
        dataset_rows.append(
            {
                "corpus": "IEMOCAP",
                "analytic_rows": len(iemocap),
                "speakers": iemocap.speaker_id.nunique(),
                "dialogs": iemocap.dialog_id.nunique(),
                "paper_expected_rows": cfg.expected_iemocap_rows,
                "exact_paper_subset": len(iemocap) == cfg.expected_iemocap_rows,
            }
        )
        counts = iemocap.emotion_label.value_counts().reindex(
            EMOTION_LABELS, fill_value=0
        )
        for label in EMOTION_LABELS:
            class_rows.append(
                {
                    "corpus": "IEMOCAP",
                    "label": label,
                    "samples": int(counts[label]),
                    "percentage": float(counts[label] / max(len(iemocap), 1) * 100),
                    "paper_count": PAPER_IEMOCAP_COUNTS[label],
                }
            )
    if msp is not None:
        dataset_rows.append(
            {
                "corpus": "MSP-Podcast",
                "analytic_rows": len(msp),
                "speakers": msp.speaker_id.nunique(),
                "dialogs": msp.dialog_id.nunique(),
                "paper_expected_rows": cfg.expected_msp_rows,
                "exact_paper_subset": len(msp) == cfg.expected_msp_rows,
            }
        )
    corpus_roles = pd.DataFrame(
        [
            {
                "corpus": "IEMOCAP",
                "nature": "acted and semi-scripted dyadic interactions",
                "labels_used": "nine categorical emotions plus dimensional activation",
                "role": "primary speaker-independent LOSO benchmark",
                "status": "computed when local corpus is available",
            },
            {
                "corpus": "MSP-Podcast",
                "nature": "naturalistic podcast speech",
                "labels_used": "arousal and valence mapped to shared proxy distress",
                "role": "bidirectional cross-corpus robustness",
                "status": "computed when local corpus is available",
            },
        ]
    )
    for name, frame in (
        ("table_01_corpus_roles", corpus_roles),
        ("table_02_dataset_statistics", pd.DataFrame(dataset_rows)),
        ("table_03_class_distribution", pd.DataFrame(class_rows)),
    ):
        path = save_table(name, frame)
        if path:
            generated["tables"].append(str(path))

    # Tables 4-6: fold-wise, fold-average, pooled and seed-wise LOSO.
    main = collect_completed_metrics("main")
    if not main.empty:
        wanted = [
            "seed",
            "fold",
            "rows_test",
            "metrics_calibrated_distress_macro_f1",
            "metrics_calibrated_distress_accuracy",
            "metrics_calibrated_distress_uar",
            "metrics_calibrated_regression_mae",
            "metrics_calibrated_regression_rmse",
            "metrics_calibrated_regression_pearson_r",
            "metrics_calibrated_regression_spearman_rho",
            "dialog_metrics_distress_qwk",
            "dialog_metrics_regression_pearson_r",
            "metrics_calibrated_emotion_macro_f1",
            "metrics_uncalibrated_emotion_ece",
            "metrics_calibrated_emotion_ece",
            "temperature",
            "path",
        ]
        fold_table = main[[column for column in wanted if column in main]].copy()
        path = save_table("table_05_foldwise_loso", fold_table)
        if path:
            generated["tables"].append(str(path))
        numeric_columns = [
            column
            for column in fold_table.columns
            if column not in {"seed", "fold", "path"}
            and pd.api.types.is_numeric_dtype(fold_table[column])
        ]
        if numeric_columns:
            fold_average = pd.DataFrame(
                {
                    "metric": numeric_columns,
                    "mean": [fold_table[column].mean() for column in numeric_columns],
                    "std": [fold_table[column].std(ddof=0) for column in numeric_columns],
                    "completed_folds": [fold_table[column].notna().sum() for column in numeric_columns],
                }
            )
            path = save_table("table_04_fold_average_summary", fold_average)
            if path:
                generated["tables"].append(str(path))
            seed_table = (
                fold_table.groupby("seed", as_index=False)[numeric_columns]
                .mean(numeric_only=True)
            )
            path = save_table("table_06_seedwise_summary", seed_table)
            if path:
                generated["tables"].append(str(path))

    pooled = pooled_loso("main", cfg.budget_primary_seed)
    dialog_pooled = dialog_pooled_available(cfg.budget_primary_seed)
    if pooled.get("status") == "complete":
        main_summary = pd.DataFrame(
            [
                {
                    "level": "utterance",
                    "macro_f1": metric_get(pooled, "distress", "macro_f1"),
                    "accuracy": metric_get(pooled, "distress", "accuracy"),
                    "uar": metric_get(pooled, "distress", "uar"),
                    "qwk": metric_get(pooled, "distress", "qwk"),
                    "mae": metric_get(pooled, "regression", "mae"),
                    "rmse": metric_get(pooled, "regression", "rmse"),
                    "pearson_r": metric_get(pooled, "regression", "pearson_r"),
                    "spearman_rho": metric_get(pooled, "regression", "spearman_rho"),
                    "rows": pooled.get("rows"),
                },
                {
                    "level": "dialog",
                    "macro_f1": metric_get(dialog_pooled, "distress", "macro_f1"),
                    "accuracy": metric_get(dialog_pooled, "distress", "accuracy"),
                    "uar": metric_get(dialog_pooled, "distress", "uar"),
                    "qwk": metric_get(dialog_pooled, "distress", "qwk"),
                    "mae": metric_get(dialog_pooled, "regression", "mae"),
                    "rmse": metric_get(dialog_pooled, "regression", "rmse"),
                    "pearson_r": metric_get(dialog_pooled, "regression", "pearson_r"),
                    "spearman_rho": metric_get(dialog_pooled, "regression", "spearman_rho"),
                    "rows": dialog_pooled.get("rows"),
                },
            ]
        )
        for name in (
            "table_04_pooled_main_summary",
            "table_07_regression_utterance_dialog",
            "table_08_binned_distress",
        ):
            path = save_table(name, main_summary)
            if path:
                generated["tables"].append(str(path))
        emotion_report = metric_get(pooled, "emotion", "class_report", default={})
        emotion_rows = []
        for label in EMOTION_LABELS:
            if label in emotion_report:
                emotion_rows.append(
                    {
                        "emotion": label,
                        "precision": emotion_report[label].get("precision"),
                        "recall": emotion_report[label].get("recall"),
                        "f1_score": emotion_report[label].get("f1-score"),
                        "support": emotion_report[label].get("support"),
                    }
                )
        path = save_table("table_11_pooled_emotion_classwise", pd.DataFrame(emotion_rows))
        if path:
            generated["tables"].append(str(path))

    # Table 10: calibration before/after per fold.
    if not main.empty:
        calibration_columns = [
            column
            for column in [
                "seed",
                "fold",
                "metrics_uncalibrated_emotion_ece",
                "metrics_calibrated_emotion_ece",
                "temperature",
            ]
            if column in main
        ]
        path = save_table("table_10_temperature_calibration", main[calibration_columns])
        if path:
            generated["tables"].append(str(path))

    # Tables 9, 12 and 13: modality/fusion and regression-head ablations.
    fusion = collect_variant_metrics("fusion")
    regression = collect_variant_metrics("regression")
    for name, frame in (
        ("table_09_modality_comparison", fusion[fusion.variant.isin(["audio_only", "text_only", "cross_attention"])] if not fusion.empty else fusion),
        ("table_12_fusion_ablation", fusion),
        ("table_13_regression_head_ablation", regression),
    ):
        path = save_table(name, frame)
        if path:
            generated["tables"].append(str(path))

    # Table 14: encoder baselines plus mean epoch time where available.
    encoder_rows: List[Dict[str, Any]] = []
    for variant, directory in {
        "logmel_cnn": RUN_DIR / "ablations" / "encoder" / "logmel_cnn",
        "tfidf": RUN_DIR / "ablations" / "encoder" / "tfidf",
        "glove": RUN_DIR / "ablations" / "encoder" / "glove",
    }.items():
        for done_path in directory.glob("seed_*/*/done.json") if directory.exists() else []:
            payload = read_json_if_exists(done_path)
            if payload is None or payload.get("status") != "complete":
                continue
            calibrated = payload.get("metrics_calibrated", payload.get("metrics", {}))
            encoder_rows.append(
                {
                    "encoder": variant,
                    "seed": int(done_path.parent.parent.name.split("_")[-1]),
                    "fold": done_path.parent.name,
                    "macro_f1": metric_get(calibrated, "distress", "macro_f1"),
                    "pearson_r": metric_get(calibrated, "regression", "pearson_r"),
                    "mae": metric_get(calibrated, "regression", "mae"),
                    "mean_epoch_seconds": training_seconds_for(done_path.parent),
                }
            )
    if not fusion.empty:
        for _, row in fusion[fusion.variant.isin(["audio_only", "text_only"])].iterrows():
            encoder_rows.append(
                {
                    "encoder": "wav2vec2" if row.variant == "audio_only" else "distilbert",
                    "seed": row.seed,
                    "fold": row.fold,
                    "macro_f1": row.utterance_macro_f1,
                    "pearson_r": row.pearson_r,
                    "mae": row.mae,
                    "mean_epoch_seconds": training_seconds_for(Path(row.metrics_path).parent),
                }
            )
    path = save_table("table_14_encoder_ablation", pd.DataFrame(encoder_rows))
    if path:
        generated["tables"].append(str(path))

    # Table 15: explicit context operationalization.
    context_rows: List[Dict[str, Any]] = []
    context_root = RUN_DIR / "ablations" / "context"
    for done_path in context_root.glob("seed_*/*/done.json") if context_root.exists() else []:
        payload = read_json_if_exists(done_path)
        if payload is None:
            continue
        context_rows.append(
            {
                "seed": int(done_path.parent.parent.name.split("_")[-1]),
                "fold": done_path.parent.name,
                "operationalization": payload.get("operationalization"),
                "macro_f1": metric_get(payload, "metrics", "distress", "macro_f1"),
                "dialog_qwk": metric_get(payload, "metrics", "distress", "qwk"),
                "pearson_r": metric_get(payload, "metrics", "regression", "pearson_r"),
                "mae": metric_get(payload, "metrics", "regression", "mae"),
            }
        )
    path = save_table("table_15_context_ablation", pd.DataFrame(context_rows))
    if path:
        generated["tables"].append(str(path))

    # Tables 17-18: bidirectional cross-corpus results.
    cross_rows: List[Dict[str, Any]] = []
    cross_root = RUN_DIR / "cross_corpus"
    for metrics_path in cross_root.glob("*/seed_*/metrics.json") if cross_root.exists() else []:
        payload = read_json_if_exists(metrics_path)
        if payload is None:
            continue
        cross_rows.append(
            {
                "direction": metrics_path.parent.parent.name,
                "seed": int(metrics_path.parent.name.split("_")[-1]),
                "target_rows": payload.get("target_rows"),
                "macro_f1": metric_get(payload, "metrics", "distress", "macro_f1"),
                "accuracy": metric_get(payload, "metrics", "distress", "accuracy"),
                "uar": metric_get(payload, "metrics", "distress", "uar"),
                "qwk": metric_get(payload, "metrics", "distress", "qwk"),
                "pearson_r": metric_get(payload, "metrics", "regression", "pearson_r"),
                "mae": metric_get(payload, "metrics", "regression", "mae"),
                "scope": json.dumps(payload.get("scope", {}), sort_keys=True),
            }
        )
    cross_frame = pd.DataFrame(cross_rows)
    # Table 16 is contextual literature reporting, not a rerun of external baselines.
    dersx_metric = "pending computed outputs"
    if pooled.get("status") == "complete":
        dersx_metric = (
            f"computed pooled proxy-distress Macro-F1="
            f"{metric_get(pooled, 'distress', 'macro_f1'):.4f}"
        )
    literature_context = pd.DataFrame(
        [
            {
                "model": "MulT",
                "task_modalities": "four one-vs-rest emotions; text/audio/visual",
                "reported_metric": "mean accuracy 74.7%; mean F1 71.5%",
                "provenance": "external literature value quoted by the manuscript; not recomputed",
                "comparability": "different categorical target and modalities",
            },
            {
                "model": "TACFN",
                "task_modalities": "multimodal categorical emotion recognition",
                "reported_metric": "mean accuracy 76.2%; mean F1 72.6%",
                "provenance": "external literature value quoted by the manuscript; not recomputed",
                "comparability": "different categorical target",
            },
            {
                "model": "SCMM",
                "task_modalities": "multimodal emotion recognition in conversation",
                "reported_metric": "weighted F1 82.06% on IEMOCAP-4",
                "provenance": "external literature value quoted by the manuscript; not recomputed",
                "comparability": "different categorical target and protocol",
            },
            {
                "model": "DERS-X",
                "task_modalities": "audio-text proxy-distress plus auxiliary emotion",
                "reported_metric": dersx_metric,
                "provenance": "generated from this notebook's held-out predictions",
                "comparability": "not a strict leaderboard comparison",
            },
        ]
    )
    path = save_table("table_16_literature_context", literature_context)
    if path:
        generated["tables"].append(str(path))

    for name in ("table_17_cross_corpus", "table_18_bidirectional_transfer"):
        path = save_table(name, cross_frame)
        if path:
            generated["tables"].append(str(path))

    # Tables 19-21: all acoustic/text/combined conditions and attention shares.
    degradation_frames = []
    for summary_path in (RUN_DIR / "degradation").glob("seed_*/*/summary.csv") if (RUN_DIR / "degradation").exists() else []:
        frame = pd.read_csv(summary_path)
        frame["summary_path"] = str(summary_path)
        degradation_frames.append(frame)
    degradation = pd.concat(degradation_frames, ignore_index=True) if degradation_frames else pd.DataFrame()
    if not degradation.empty:
        acoustic_names = {
            "clean", "noise_20db", "noise_15db", "noise_10db", "noise_5db",
            "mobile_15db_amr", "voip_15db_packet10",
        }
        wer_names = {"clean", "wer_10", "wer_20", "wer_30"}
        combined_names = {
            "clean", "typical_15db_wer15", "challenging_10db_wer25", "extreme_5db_wer35",
        }
        for name, subset in (
            ("table_19_acoustic_channel_degradation", degradation[degradation.condition.isin(acoustic_names)]),
            ("table_20_transcript_wer_degradation", degradation[degradation.condition.isin(wer_names)]),
            ("table_21_combined_degradation", degradation[degradation.condition.isin(combined_names)]),
        ):
            path = save_table(name, subset)
            if path:
                generated["tables"].append(str(path))

    # Table 22: multimodal/audio/text under combined degradation.
    modality_frames = []
    modality_root = RUN_DIR / "degradation_modality"
    for summary_path in modality_root.glob("seed_*/*/summary.csv") if modality_root.exists() else []:
        frame = pd.read_csv(summary_path)
        frame["summary_path"] = str(summary_path)
        modality_frames.append(frame)
    modality_degradation = pd.concat(modality_frames, ignore_index=True) if modality_frames else pd.DataFrame()
    path = save_table("table_22_modality_under_degradation", modality_degradation)
    if path:
        generated["tables"].append(str(path))

    # Figures generated from computed tables only.
    if not fusion.empty and "utterance_macro_f1" in fusion:
        plot_frame = fusion.groupby("variant", as_index=False).utterance_macro_f1.mean()
        plt.figure(figsize=(8, 4))
        plt.bar(plot_frame.variant, plot_frame.utterance_macro_f1)
        plt.ylabel("Utterance Macro-F1")
        plt.xticks(rotation=25, ha="right")
        plt.tight_layout()
        figure_path = FIGURE_DIR / "figure_01_modality_fusion.png"
        plt.savefig(figure_path, dpi=180)
        plt.close()
        generated["figures"].append(str(figure_path))

    if not cross_frame.empty:
        plt.figure(figsize=(7, 4))
        plt.bar(cross_frame.direction, cross_frame.macro_f1)
        plt.ylabel("Macro-F1")
        plt.xticks(rotation=20, ha="right")
        plt.tight_layout()
        figure_path = FIGURE_DIR / "figure_02_cross_corpus.png"
        plt.savefig(figure_path, dpi=180)
        plt.close()
        generated["figures"].append(str(figure_path))

    if not degradation.empty:
        representative = degradation[
            (degradation.fold == cfg.budget_representative_fold)
            & (degradation.seed == cfg.budget_primary_seed)
        ]
        if representative.empty:
            representative = degradation
        representative = representative.drop_duplicates("condition")
        x = np.arange(len(representative))
        plt.figure(figsize=(11, 4))
        if "metrics_distress_macro_f1" in representative:
            plt.plot(x, representative.metrics_distress_macro_f1, marker="o", label="Macro-F1")
        if "metrics_regression_pearson_r" in representative:
            plt.plot(x, representative.metrics_regression_pearson_r, marker="o", label="Pearson r")
        if "metrics_emotion_ece" in representative:
            plt.plot(x, representative.metrics_emotion_ece, marker="o", label="ECE")
        plt.xticks(x, representative.condition, rotation=45, ha="right")
        plt.legend()
        plt.tight_layout()
        figure_path = FIGURE_DIR / "figure_03_degradation_curve.png"
        plt.savefig(figure_path, dpi=180)
        plt.close()
        generated["figures"].append(str(figure_path))
        if {"attention_audio_share", "attention_text_share"}.issubset(representative.columns):
            plt.figure(figsize=(9, 4))
            plt.plot(x, representative.attention_audio_share, marker="o", label="Audio share")
            plt.plot(x, representative.attention_text_share, marker="o", label="Text share")
            plt.xticks(x, representative.condition, rotation=45, ha="right")
            plt.ylim(0, 1)
            plt.legend()
            plt.tight_layout()
            figure_path = FIGURE_DIR / "figure_04_attention_shift.png"
            plt.savefig(figure_path, dpi=180)
            plt.close()
            generated["figures"].append(str(figure_path))

    if not modality_degradation.empty and "metrics_distress_macro_f1" in modality_degradation:
        plt.figure(figsize=(9, 4))
        conditions = list(dict.fromkeys(modality_degradation.condition.astype(str)))
        x = np.arange(len(conditions))
        for variant, group in modality_degradation.groupby("variant"):
            values = group.set_index("condition").reindex(conditions).metrics_distress_macro_f1
            plt.plot(x, values, marker="o", label=variant)
        plt.xticks(x, conditions, rotation=35, ha="right")
        plt.ylabel("Macro-F1")
        plt.legend()
        plt.tight_layout()
        figure_path = FIGURE_DIR / "figure_05_modality_degradation.png"
        plt.savefig(figure_path, dpi=180)
        plt.close()
        generated["figures"].append(str(figure_path))

    atomic_json_dump(generated, RUN_DIR / "generated_outputs.json")
    return generated



def safe_generate_manuscript_outputs(
    iemocap: Optional[pd.DataFrame] = None,
    msp: Optional[pd.DataFrame] = None,
) -> Dict[str, Any]:
    """Generate all currently available tables/figures without interrupting training."""
    try:
        result = generate_manuscript_outputs(iemocap=iemocap, msp=msp)
        logger.info(
            "Manuscript outputs refreshed: %d tables, %d figures",
            len(result.get("tables", [])),
            len(result.get("figures", [])),
        )
        return result
    except Exception as exc:
        logger.exception("Manuscript output generation failed: %s", exc)
        return {"status": "failed", "error": repr(exc), "tables": [], "figures": []}

## 18. Persistent task registry and breadth-first 24-hour plan

The default budget plan first produces one complete end-to-end fold, its degradation suite and ablations, both transfer directions, then finishes the remaining LOSO folds and seed checks. This maximizes scientific coverage before the deadline. Every task has a durable status and can resume.

In [22]:
def load_task_status() -> Dict[str,Any]:
    return json.loads(TASK_STATUS_PATH.read_text(encoding="utf-8")) if TASK_STATUS_PATH.exists() else {}


def update_task(task_id:str,status:str,**extra:Any) -> None:
    state=load_task_status();state[task_id]={"status":status,"updated":time.time(),**extra};atomic_json_dump(state,TASK_STATUS_PATH);logger.info("Task %s -> %s",task_id,status)


def build_plan(speakers:Sequence[str]) -> List[Dict[str,Any]]:
    rep=cfg.budget_representative_fold if cfg.budget_representative_fold in speakers else speakers[0]
    if cfg.profile=="smoke":return [{"kind":"main_fold","fold":rep,"seed":cfg.budget_primary_seed}]
    if cfg.profile=="paper_exact":
        plan=[{"kind":"main_fold","fold":f,"seed":s} for s in cfg.seeds for f in speakers]
        if cfg.run_cross_corpus:plan += [{"kind":"cross","direction":d,"seed":13} for d in ("iemocap_to_msp","msp_to_iemocap")]
        if cfg.run_ablations:
            plan += [{"kind":"fusion_ablation","fold":f,"seed":13} for f in speakers]+[{"kind":"regression_ablation","fold":f,"seed":13} for f in speakers]+[{"kind":"encoder_ablation","fold":f,"seed":13} for f in speakers]
        if cfg.run_context_ablation:plan += [{"kind":"context","fold":f,"seed":13} for f in speakers]
        if cfg.run_degradation:
            plan += [{"kind":"degradation","fold":f,"seed":13} for f in speakers]
            if cfg.run_ablations:
                plan += [{"kind":"modality_degradation","fold":f,"seed":13} for f in speakers]
        return plan
    # 24-hour breadth-first plan
    plan=[{"kind":"main_fold","fold":rep,"seed":cfg.budget_primary_seed}]
    if cfg.run_degradation:plan.append({"kind":"degradation","fold":rep,"seed":cfg.budget_primary_seed})
    if cfg.run_ablations:
        plan += [{"kind":"fusion_ablation","fold":rep,"seed":13}]
        if cfg.run_degradation:
            plan += [{"kind":"modality_degradation","fold":rep,"seed":13}]
        plan += [{"kind":"regression_ablation","fold":rep,"seed":13},{"kind":"encoder_ablation","fold":rep,"seed":13}]
    if cfg.run_context_ablation:plan.append({"kind":"context","fold":rep,"seed":13})
    if cfg.run_cross_corpus:plan += [{"kind":"cross","direction":"iemocap_to_msp","seed":13},{"kind":"cross","direction":"msp_to_iemocap","seed":13}]
    plan += [{"kind":"main_fold","fold":f,"seed":cfg.budget_primary_seed} for f in speakers if f!=rep]
    for seed in (29,47):plan += [{"kind":"main_fold","fold":f,"seed":seed} for f in cfg.budget_seed_check_folds if f in speakers]
    return plan


def execute_plan(
    iemocap: pd.DataFrame,
    msp: Optional[pd.DataFrame],
    tokenizer: Any,
    feature_extractor: Any,
) -> pd.DataFrame:
    speakers = sorted(iemocap.speaker_id.unique())
    plan = build_plan(speakers)
    atomic_json_dump(
        {"profile": cfg.profile, "tasks": plan},
        RUN_DIR / "experiment_plan.json",
    )
    rows: List[Dict[str, Any]] = []

    for task in plan:
        task_id = stable_hash(task) + "_" + task["kind"]
        existing = load_task_status().get(task_id, {})
        if existing.get("status") == "complete" and not cfg.force_recompute:
            rows.append({**task, "status": "complete_cached"})
            continue

        if budget.should_stop():
            update_task(task_id, "paused_deadline_before_start", task=task)
            break

        update_task(task_id, "running", task=task)
        try:
            kind = task["kind"]
            if kind == "main_fold":
                result = run_iemocap_fold(
                    iemocap, task["fold"], task["seed"], tokenizer, feature_extractor
                )
            elif kind == "degradation":
                result = run_degradation_fold(
                    iemocap, task["fold"], task["seed"], tokenizer, feature_extractor
                )
            elif kind == "fusion_ablation":
                result = run_neural_ablation(
                    iemocap, task["fold"], task["seed"], tokenizer,
                    feature_extractor, "fusion"
                )
            elif kind == "modality_degradation":
                result = run_modality_degradation_comparison(
                    iemocap, task["fold"], task["seed"], tokenizer,
                    feature_extractor
                )
            elif kind == "regression_ablation":
                result = run_neural_ablation(
                    iemocap, task["fold"], task["seed"], tokenizer,
                    feature_extractor, "regression"
                )
            elif kind == "encoder_ablation":
                result = {
                    "logmel": run_logmel_ablation(
                        iemocap, task["fold"], task["seed"], tokenizer,
                        feature_extractor
                    ),
                    "tfidf": run_tfidf_baseline(
                        iemocap, task["fold"], task["seed"]
                    ),
                    "glove": run_glove_baseline(
                        iemocap, task["fold"], task["seed"]
                    ),
                }
            elif kind == "context":
                result = run_context_ablation(
                    iemocap, task["fold"], task["seed"], tokenizer,
                    feature_extractor
                )
            elif kind == "cross":
                if msp is None:
                    result = {"status": "blocked_missing_msp"}
                else:
                    result = run_cross_corpus(
                        task["direction"], iemocap, msp, tokenizer,
                        feature_extractor, task["seed"]
                    )
            else:
                raise ValueError(kind)

            if isinstance(result, dict):
                status = result.get("status", "complete")
            elif (
                isinstance(result, pd.DataFrame)
                and "status" in result.columns
                and not result.empty
            ):
                statuses = set(result.status.astype(str))
                if "paused_deadline" in statuses:
                    status = "paused_deadline"
                elif all(value.startswith("blocked") for value in statuses):
                    status = sorted(statuses)[0]
                elif "failed" in statuses:
                    status = "failed"
                else:
                    status = "complete"
            else:
                status = "paused_deadline" if budget.should_stop() else "complete"

            update_task(task_id, status, task=task)
            rows.append({**task, "status": status})
            generate_progress_report()
            safe_generate_manuscript_outputs(iemocap, msp)
            if status == "paused_deadline":
                break
        except Exception as exc:
            update_task(
                task_id,
                "failed",
                task=task,
                error=repr(exc),
                traceback=traceback.format_exc(),
            )
            logger.exception("Task failed: %s", task)
            rows.append({**task, "status": "failed", "error": repr(exc)})
            if cfg.profile == "paper_exact":
                raise
        finally:
            if torch.cuda.is_available():
                torch.cuda.empty_cache()

    out = pd.DataFrame(rows)
    out.to_csv(RUN_DIR / "last_execution_tasks.csv", index=False)
    generate_progress_report()
    safe_generate_manuscript_outputs(iemocap, msp)
    return out

## 19. Data setup and preflight

The cell below loads local corpora, writes metadata fingerprints, checks the paper's expected class counts, and initializes the processors. MSP absence blocks only cross-corpus tasks in the 24-hour profile; `paper_exact` requires it.

In [23]:
IEMOCAP_DF: Optional[pd.DataFrame] = None
MSP_DF: Optional[pd.DataFrame] = None
TOKENIZER = None
FEATURE_EXTRACTOR = None


def warm_iemocap_waveform_cache(frame: pd.DataFrame) -> Dict[str, Any]:
    """Decode/resample IEMOCAP once using threads; later notebook DataLoaders stay Windows-safe."""
    if not cfg.cache_waveforms or not cfg.precache_iemocap_waveforms:
        return {"status": "disabled", "cached": 0}
    unique_paths = sorted(set(frame.audio_path.astype(str)))
    missing = [
        audio_path
        for audio_path in unique_paths
        if not waveform_cache_path(audio_path).exists()
    ]
    if not missing:
        result = {"status": "already_complete", "cached": len(unique_paths)}
        logger.info("IEMOCAP waveform cache already complete: %d files", len(unique_paths))
        return result

    from concurrent.futures import ThreadPoolExecutor, as_completed

    workers = max(1, min(int(cfg.precache_threads), os.cpu_count() or 1))
    errors: List[Tuple[str, str]] = []

    def cache_one(audio_path: str) -> str:
        _ = load_waveform(audio_path)
        return audio_path

    logger.info(
        "Pre-caching %d IEMOCAP waveforms with %d threads",
        len(missing),
        workers,
    )
    with ThreadPoolExecutor(max_workers=workers) as executor:
        future_to_path = {
            executor.submit(cache_one, audio_path): audio_path
            for audio_path in missing
        }
        for future in tqdm(
            as_completed(future_to_path),
            total=len(future_to_path),
            desc="IEMOCAP waveform cache",
        ):
            audio_path = future_to_path[future]
            try:
                future.result()
            except Exception as exc:
                errors.append((audio_path, repr(exc)))
    result = {
        "status": "complete" if not errors else "failed",
        "requested": len(missing),
        "cached": len(missing) - len(errors),
        "errors": errors[:20],
    }
    atomic_json_dump(result, RUN_DIR / "metadata" / "waveform_cache_report.json")
    if errors:
        raise RuntimeError(
            f"Waveform pre-cache failed for {len(errors)} files; see waveform_cache_report.json"
        )
    return result


def preflight() -> Tuple[pd.DataFrame, Optional[pd.DataFrame], Any, Any]:
    iem = parse_iemocap(cfg.iemocap_root, cfg.iemocap_subset_manifest)
    audit = audit_iemocap_sample(iem)
    metadata_dir = RUN_DIR / "metadata"
    metadata_dir.mkdir(parents=True, exist_ok=True)
    iem.to_csv(metadata_dir / "iemocap_metadata.csv", index=False)
    atomic_json_dump(
        {
            "fingerprint": fingerprint_frame(
                iem, ["utterance_id", "emotion_label", "activation"]
            ),
            "rows": len(iem),
            "speakers": iem.speaker_id.nunique(),
            "dialogs": iem.dialog_id.nunique(),
        },
        metadata_dir / "iemocap_fingerprint.json",
    )
    warm_iemocap_waveform_cache(iem)

    msp = None
    try:
        msp = parse_msp_podcast(
            cfg.msp_root,
            cfg.msp_metadata_csv,
            cfg.msp_subset_manifest,
        )
        msp.to_csv(metadata_dir / "msp_metadata.csv", index=False)
        atomic_json_dump(
            {
                "fingerprint": fingerprint_frame(
                    msp, ["utterance_id", "arousal", "valence"]
                ),
                "rows": len(msp),
            },
            metadata_dir / "msp_fingerprint.json",
        )
    except Exception as exc:
        logger.warning("MSP-Podcast unavailable: %s", exc)
        if cfg.profile == "paper_exact" and cfg.run_cross_corpus:
            raise
    tokenizer, feature_extractor = prepare_processors()
    logger.info(
        "Preflight complete. IEMOCAP=%d MSP=%s",
        len(iem),
        None if msp is None else len(msp),
    )
    audit.to_csv(metadata_dir / "iemocap_count_audit.csv", index=False)
    return iem, msp, tokenizer, feature_extractor


IEMOCAP_DF, MSP_DF, TOKENIZER, FEATURE_EXTRACTOR = preflight()
display(audit_iemocap_sample(IEMOCAP_DF))

2026-08-08 22:33:04 | INFO | IEMOCAP audit: rows=7532 speakers=10 dialogs=151 exact_paper_sample=False
2026-08-08 22:33:10 | INFO | IEMOCAP waveform cache already complete: 7532 files
2026-08-08 22:33:10 | WARNING | MSP-Podcast unavailable: C:\Users\HaseebWajid\Downloads\MSP-Podcast
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\transformers\configuration_utils.py:335: UserWarning: Passing `gradient_checkpointing` to a config initialization is deprecated and will be removed in v5 Transformers. Using `model.gradient_checkpointing_enable()` instead, or if you are using the `Trainer` API, pass `gradient_checkpointing=True` in your `TrainingArguments`.
  warnings.warn(
2026-08-08 22:33:13 | INFO | Preflight complete. IEMOCAP=7532 MSP=None
2026-08-08 22:33:13 | INFO | IEMOCAP audit: rows=7532 speakers=10 dialogs=151 exact_paper_sample=False

  emotion  paper_count  parsed_count  delta
0     ang         1103          1103      0
1     hap          648           595    -53
2     neu         1708          1708      0
3     sad         1084          1084      0
4     exc          429          1041    612
5     fea          168            40   -128
6     fru          276          1849   1573
7     oth           42             5    -37
8     sur           21           107     86
9   TOTAL         5479          7532   2053

## 20. Lightweight implementation self-tests

These tests do not train the full encoders. They verify target formulas, binning, leakage checks, WER corruption, attention-share normalization, and checkpoint payload structure before the expensive run.

In [24]:
def run_self_tests() -> Dict[str,str]:
    results={}
    # Equation (3)
    tiny=pd.DataFrame({"arousal":[1.,2.,3.,4.],"valence":[4.,3.,2.,1.]})
    st=fit_target_stats(tiny,"MSP-Podcast");computed=_continuous_with_stats(tiny,st);manual=(tiny.arousal-tiny.arousal.mean())/tiny.arousal.std(ddof=0)-0.5*(tiny.valence-tiny.valence.mean())/tiny.valence.std(ddof=0)
    assert np.allclose(computed,manual);results["msp_equation_3"]="pass"
    assert set(continuous_to_bins(computed,st))<=set(DISTRESS_LABELS);results["quartile_bins"]="pass"
    corrupted,realized=corrupt_text_exact_wer("one two three four five",0.4,["alpha","beta"],random.Random(13));assert corrupted and realized>=0;results["wer_corruption"]="pass"
    attn=torch.full((2,4,3,5),0.2);q=torch.ones(2,3,dtype=torch.bool);k=torch.ones(2,5,dtype=torch.bool);conf=attention_confidence(attn,q,k);assert torch.all((conf>=0)&(conf<=1));results["attention_confidence"]="pass"
    # Checkpoint schema is tested without serializing a full model.
    required={"model","optimizer","scheduler","scaler","epoch","next_batch","global_step","best_f1","best_mae","bad_epochs","rng","method_signature","config","data_fingerprint","history"};results["checkpoint_schema"]="pass" if len(required)==15 else "fail"
    logger.info("Self-tests: %s",results);atomic_json_dump(results,RUN_DIR/"self_tests.json");return results

SELF_TESTS=run_self_tests()
SELF_TESTS

2026-08-08 22:33:13 | INFO | Self-tests: {'msp_equation_3': 'pass', 'quartile_bins': 'pass', 'wer_corruption': 'pass', 'attention_confidence': 'pass', 'checkpoint_schema': 'pass'}

{'msp_equation_3': 'pass',
 'quartile_bins': 'pass',
 'wer_corruption': 'pass',
 'attention_confidence': 'pass',
 'checkpoint_schema': 'pass'}

## 21. Launch or resume the full campaign

This cell performs the work now. It does not run in the background. When the deadline guard is reached, the active task checkpoints and the cell returns. Before the stored deadline, rerunning resumes automatically. After that deadline, set `reset_campaign_clock=True` for one launch to open a new 24-hour campaign while reusing all checkpoints, then return it to `False`.

In [25]:
EXECUTION_SUMMARY = pd.DataFrame()
if cfg.run_experiment:
    EXECUTION_SUMMARY = execute_plan(IEMOCAP_DF, MSP_DF, TOKENIZER, FEATURE_EXTRACTOR)
    display(EXECUTION_SUMMARY)
else:
    logger.info("cfg.run_experiment=False; preflight and self-tests completed without training")


FINAL_GENERATED_OUTPUTS = safe_generate_manuscript_outputs(IEMOCAP_DF, MSP_DF)
FINAL_GENERATED_OUTPUTS

2026-08-08 22:33:13 | INFO | Task e79a9da83e9280e0_regression_ablation -> running
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\transformers\configuration_utils.py:335: UserWarning: Passing `gradient_checkpointing` to a config initialization is deprecated and will be removed in v5 Transformers. Using `model.gradient_checkpointing_enable()` instead, or if you are using the `Trainer` API, pass `gradient_checkpointing=True` in your `TrainingArguments`.
  warnings.warn(
The new embeddings will be initialized from a multivariate normal distribution that has old embeddings' mean and covariance. As described in this article: https://nlp.stanford.edu/~johnhew/vocab-expansion.html. To disable this, use `mean_resizing=False`
2026-08-08 22:33:18 | INFO | Task C:\Users\HaseebWajid\Downloads\runs\dersx_paper_aligned\campaign_01\ablations\regression\two_gelu\seed_13\Ses01F parameters={'total': 163009451, 'trainable': 69034283, 'frozen': 93975168} scope={'corpus': 'IEMOCAP', 'protocol': 'strict_LOSO', 'heldout_speaker': 'Ses01F', 'seed': 13, 'stage': 'ablations/regression/two_gelu', 'profile': 'rtx3060_24h'}
2026-08-08 22:33:25 | INFO | Resumed C:\Users\HaseebWajid\Downloads\runs\dersx_paper_aligned\campaign_01\ablations\regression\two_gelu\seed_13\Ses01F at epoch=2 batch=2136 step=1800

epoch 3:   0%|          | 0/393 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-08 22:34:36 | INFO | train task=Ses01F epoch=3 batch=2236/2529 step=1825 loss=1.0020 ce=0.8461 mse=0.3119 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1380796432495117, "reserved_gb": 1.70703125, "max_allocated_gb": 2.8183722496032715, "gpu_util_pct": "98", "gpu_mem_used_mb": "2372", "gpu_mem_total_mb": "12288", "gpu_temp_c": "56", "gpu_power_w": "82.48"}
2026-08-08 22:35:35 | INFO | train task=Ses01F epoch=3 batch=2336/2529 step=1850 loss=1.4607 ce=1.4491 mse=0.0232 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1381797790527344, "reserved_gb": 1.724609375, "max_allocated_gb": 2.8183722496032715, "gpu_util_pct": "20", "gpu_mem_used_mb": "2390", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "87.06"}
2026-08-08 22:36:29 | INFO | train task=Ses01F epoch=3 batch=2436/2529 step=1875 loss=1.4975 ce=1.1139 mse=0.7672 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1382250785827637, "reserved_gb": 1.744140625, "max_allocated_gb": 2.8183722496032715, "gpu_util_pct": "43", "gpu_mem_used_mb": "2410", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "88.87"}

predict:   0%|          | 0/281 [00:00<?, ?it/s]

2026-08-08 22:38:35 | INFO | Epoch 03 task=Ses01F train_loss=1.2468 val_macro_f1=0.5507 val_mae=0.5231 epoch_seconds=309.8

epoch 4:   0%|          | 0/2529 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-08 22:38:41 | INFO | train task=Ses01F epoch=4 batch=4/2529 step=1900 loss=0.2784 ce=0.1642 mse=0.2286 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1378765106201172, "reserved_gb": 1.521484375, "max_allocated_gb": 2.8183722496032715, "gpu_util_pct": "12", "gpu_mem_used_mb": "2186", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "68.22"}
2026-08-08 22:39:39 | INFO | train task=Ses01F epoch=4 batch=104/2529 step=1925 loss=0.1933 ce=0.1721 mse=0.0425 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1383066177368164, "reserved_gb": 1.716796875, "max_allocated_gb": 2.8183722496032715, "gpu_util_pct": "20", "gpu_mem_used_mb": "2386", "gpu_mem_total_mb": "12288", "gpu_temp_c": "44", "gpu_power_w": "58.97"}
2026-08-08 22:40:27 | INFO | train task=Ses01F epoch=4 batch=204/2529 step=1950 loss=0.8358 ce=0.7476 mse=0.1764 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1396598815917969, "reserved_gb": 1.896484375, "max_allocated_gb": 2.8183722496032715, "gpu_util_pct": "23", "gpu_mem_used_mb": "2573", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "65.89"}
2026-08-08 22:41:10 | INFO | train task=Ses01F epoch=4 batch=304/2529 step=1975 loss=1.4018 ce=1.0795 mse=0.6446 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1381034851074219, "reserved_gb": 1.720703125, "max_allocated_gb": 2.8183722496032715, "gpu_util_pct": "97", "gpu_mem_used_mb": "2393", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "83.36"}
2026-08-08 22:41:45 | INFO | train task=Ses01F epoch=4 batch=404/2529 step=2000 loss=1.2137 ce=0.9526 mse=0.5221 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.140472412109375, "reserved_gb": 1.947265625, "max_allocated_gb": 2.8183722496032715, "gpu_util_pct": "45", "gpu_mem_used_mb": "2625", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "80.14"}
2026-08-08 22:42:40 | INFO | train task=Ses01F epoch=4 batch=504/2529 step=2025 loss=0.6221 ce=0.5214 mse=0.2014 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.138049602508545, "reserved_gb": 1.712890625, "max_allocated_gb": 2.8183722496032715, "gpu_util_pct": "23", "gpu_mem_used_mb": "2385", "gpu_mem_total_mb": "12288", "gpu_temp_c": "44", "gpu_power_w": "82.51"}
2026-08-08 22:43:19 | INFO | train task=Ses01F epoch=4 batch=604/2529 step=2050 loss=0.2772 ce=0.2596 mse=0.0353 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1389927864074707, "reserved_gb": 1.8671875, "max_allocated_gb": 2.8183722496032715, "gpu_util_pct": "34", "gpu_mem_used_mb": "2543", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "73.97"}
2026-08-08 22:43:55 | INFO | train task=Ses01F epoch=4 batch=704/2529 step=2075 loss=1.0901 ce=1.0597 mse=0.0606 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1385459899902344, "reserved_gb": 1.61328125, "max_allocated_gb": 2.8183722496032715, "gpu_util_pct": "36", "gpu_mem_used_mb": "2283", "gpu_mem_total_mb": "12288", "gpu_temp_c": "44", "gpu_power_w": "54.71"}
2026-08-08 22:44:28 | INFO | train task=Ses01F epoch=4 batch=804/2529 step=2100 loss=0.6718 ce=0.1804 mse=0.9828 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1380681991577148, "reserved_gb": 1.732421875, "max_allocated_gb": 2.8894639015197754, "gpu_util_pct": "16", "gpu_mem_used_mb": "2405", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "64.97"}
2026-08-08 22:45:18 | INFO | train task=Ses01F epoch=4 batch=904/2529 step=2125 loss=1.0109 ce=0.8170 mse=0.3877 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1386661529541016, "reserved_gb": 1.708984375, "max_allocated_gb": 2.8894639015197754, "gpu_util_pct": "42", "gpu_mem_used_mb": "2381", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "77.80"}
2026-08-08 22:45:55 | INFO | train task=Ses01F epoch=4 batch=1004/2529 step=2150 loss=1.4783 ce=1.3983 mse=0.1600 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1382455825805664, "reserved_gb": 1.76953125, "max_allocated_gb": 2.8894639015197754, "gpu_util_pct": "100", "gpu_mem_used_mb": "2443", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "106.58"}
2026-08-08 22:46:33 | INFO | train task=Ses01F epoch=4 batch=1104/2529 step=2175 loss=0.2210 ce=0.0309 mse=0.3803 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1388912200927734, "reserved_gb": 1.787109375, "max_allocated_gb": 2.8894639015197754, "gpu_util_pct": "33", "gpu_mem_used_mb": "2461", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "73.97"}
2026-08-08 22:47:03 | INFO | train task=Ses01F epoch=4 batch=1204/2529 step=2200 loss=0.6435 ce=0.5757 mse=0.1355 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1385059356689453, "reserved_gb": 1.748046875, "max_allocated_gb": 2.8894639015197754, "gpu_util_pct": "17", "gpu_mem_used_mb": "2421", "gpu_mem_total_mb": "12288", "gpu_temp_c": "43", "gpu_power_w": "54.88"}
2026-08-08 22:47:51 | INFO | train task=Ses01F epoch=4 batch=1304/2529 step=2225 loss=1.6228 ce=1.0828 mse=1.0801 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.139266014099121, "reserved_gb": 1.833984375, "max_allocated_gb": 2.8894639015197754, "gpu_util_pct": "53", "gpu_mem_used_mb": "2513", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "86.95"}
2026-08-08 22:48:28 | INFO | train task=Ses01F epoch=4 batch=1404/2529 step=2250 loss=1.0178 ce=0.7867 mse=0.4622 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.139711856842041, "reserved_gb": 1.578125, "max_allocated_gb": 2.8894639015197754, "gpu_util_pct": "99", "gpu_mem_used_mb": "2251", "gpu_mem_total_mb": "12288", "gpu_temp_c": "53", "gpu_power_w": "67.71"}
2026-08-08 22:49:06 | INFO | train task=Ses01F epoch=4 batch=1504/2529 step=2275 loss=0.8027 ce=0.7939 mse=0.0175 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1383013725280762, "reserved_gb": 1.72265625, "max_allocated_gb": 3.0375351905822754, "gpu_util_pct": "22", "gpu_mem_used_mb": "2399", "gpu_mem_total_mb": "12288", "gpu_temp_c": "55", "gpu_power_w": "67.96"}
2026-08-08 22:49:38 | INFO | train task=Ses01F epoch=4 batch=1604/2529 step=2300 loss=3.2216 ce=2.9569 mse=0.5295 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1379117965698242, "reserved_gb": 1.720703125, "max_allocated_gb": 3.0375351905822754, "gpu_util_pct": "27", "gpu_mem_used_mb": "2397", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "72.57"}
2026-08-08 22:50:29 | INFO | train task=Ses01F epoch=4 batch=1704/2529 step=2325 loss=0.2605 ce=0.0720 mse=0.3770 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1395158767700195, "reserved_gb": 1.513671875, "max_allocated_gb": 3.0375351905822754, "gpu_util_pct": "36", "gpu_mem_used_mb": "2185", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "77.86"}
2026-08-08 22:51:04 | INFO | train task=Ses01F epoch=4 batch=1804/2529 step=2350 loss=1.1842 ce=1.1030 mse=0.1624 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1382026672363281, "reserved_gb": 1.716796875, "max_allocated_gb": 3.0375351905822754, "gpu_util_pct": "19", "gpu_mem_used_mb": "2393", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "65.67"}
2026-08-08 22:51:40 | INFO | train task=Ses01F epoch=4 batch=1904/2529 step=2375 loss=0.5539 ce=0.2696 mse=0.5686 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1384382247924805, "reserved_gb": 1.7265625, "max_allocated_gb": 3.0375351905822754, "gpu_util_pct": "20", "gpu_mem_used_mb": "2403", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "75.49"}
2026-08-08 22:52:13 | INFO | train task=Ses01F epoch=4 batch=2004/2529 step=2400 loss=0.7702 ce=0.6416 mse=0.2572 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1382827758789062, "reserved_gb": 1.91796875, "max_allocated_gb": 3.0375351905822754, "gpu_util_pct": "35", "gpu_mem_used_mb": "2599", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "71.57"}
2026-08-08 22:52:57 | INFO | train task=Ses01F epoch=4 batch=2104/2529 step=2425 loss=0.9491 ce=0.5999 mse=0.6984 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1378564834594727, "reserved_gb": 1.70703125, "max_allocated_gb": 3.0375351905822754, "gpu_util_pct": "37", "gpu_mem_used_mb": "2383", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "80.34"}
2026-08-08 22:53:31 | INFO | train task=Ses01F epoch=4 batch=2204/2529 step=2450 loss=1.1530 ce=0.1093 mse=2.0875 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1387615203857422, "reserved_gb": 1.91796875, "max_allocated_gb": 3.2347326278686523, "gpu_util_pct": "22", "gpu_mem_used_mb": "2599", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "61.26"}
2026-08-08 22:54:05 | INFO | train task=Ses01F epoch=4 batch=2304/2529 step=2475 loss=1.3373 ce=1.1527 mse=0.3692 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.137988567352295, "reserved_gb": 1.740234375, "max_allocated_gb": 3.2347326278686523, "gpu_util_pct": "34", "gpu_mem_used_mb": "2417", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "94.58"}
2026-08-08 22:54:38 | INFO | train task=Ses01F epoch=4 batch=2404/2529 step=2500 loss=2.6237 ce=2.3214 mse=0.6045 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1381335258483887, "reserved_gb": 1.703125, "max_allocated_gb": 3.2347326278686523, "gpu_util_pct": "20", "gpu_mem_used_mb": "2379", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "73.62"}
2026-08-08 22:55:25 | INFO | train task=Ses01F epoch=4 batch=2504/2529 step=2525 loss=0.5445 ce=0.3757 mse=0.3376 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1383056640625, "reserved_gb": 1.892578125, "max_allocated_gb": 3.2347326278686523, "gpu_util_pct": "41", "gpu_mem_used_mb": "2573", "gpu_mem_total_mb": "12288", "gpu_temp_c": "41", "gpu_power_w": "43.51"}

predict:   0%|          | 0/281 [00:00<?, ?it/s]

2026-08-08 22:55:53 | INFO | Epoch 04 task=Ses01F train_loss=1.0468 val_macro_f1=0.4863 val_mae=0.5583 epoch_seconds=1034.7

epoch 5:   0%|          | 0/2529 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-08 22:56:11 | INFO | train task=Ses01F epoch=5 batch=72/2529 step=2550 loss=0.9672 ce=0.6569 mse=0.6208 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1382789611816406, "reserved_gb": 2.599609375, "max_allocated_gb": 3.2347326278686523, "gpu_util_pct": "17", "gpu_mem_used_mb": "3297", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "59.58"}
2026-08-08 22:56:30 | INFO | train task=Ses01F epoch=5 batch=172/2529 step=2575 loss=0.3641 ce=0.1339 mse=0.4604 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1380887031555176, "reserved_gb": 1.921875, "max_allocated_gb": 3.2347326278686523, "gpu_util_pct": "20", "gpu_mem_used_mb": "2603", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "46.56"}
2026-08-08 22:56:49 | INFO | train task=Ses01F epoch=5 batch=272/2529 step=2600 loss=0.4423 ce=0.2699 mse=0.3449 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1400408744812012, "reserved_gb": 1.998046875, "max_allocated_gb": 3.2347326278686523, "gpu_util_pct": "31", "gpu_mem_used_mb": "2680", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "71.64"}
2026-08-08 22:57:14 | INFO | train task=Ses01F epoch=5 batch=372/2529 step=2625 loss=3.1221 ce=2.5055 mse=1.2332 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1385679244995117, "reserved_gb": 1.90625, "max_allocated_gb": 3.2347326278686523, "gpu_util_pct": "47", "gpu_mem_used_mb": "2586", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "42.31"}
2026-08-08 22:57:33 | INFO | train task=Ses01F epoch=5 batch=472/2529 step=2650 loss=2.4007 ce=1.7787 mse=1.2440 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.143376350402832, "reserved_gb": 2.091796875, "max_allocated_gb": 3.2347326278686523, "gpu_util_pct": "42", "gpu_mem_used_mb": "2776", "gpu_mem_total_mb": "12288", "gpu_temp_c": "55", "gpu_power_w": "64.17"}
2026-08-08 22:57:57 | INFO | train task=Ses01F epoch=5 batch=572/2529 step=2675 loss=0.1749 ce=0.1695 mse=0.0109 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1394281387329102, "reserved_gb": 1.716796875, "max_allocated_gb": 3.2347326278686523, "gpu_util_pct": "37", "gpu_mem_used_mb": "2392", "gpu_mem_total_mb": "12288", "gpu_temp_c": "57", "gpu_power_w": "85.22"}
2026-08-08 22:58:18 | INFO | train task=Ses01F epoch=5 batch=672/2529 step=2700 loss=0.6190 ce=0.3813 mse=0.4753 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1380681991577148, "reserved_gb": 2.451171875, "max_allocated_gb": 3.2347326278686523, "gpu_util_pct": "31", "gpu_mem_used_mb": "3144", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "63.19"}
2026-08-08 22:58:42 | INFO | train task=Ses01F epoch=5 batch=772/2529 step=2725 loss=0.4461 ce=0.2043 mse=0.4836 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1399002075195312, "reserved_gb": 1.970703125, "max_allocated_gb": 3.2347326278686523, "gpu_util_pct": "42", "gpu_mem_used_mb": "2651", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "67.59"}
2026-08-08 22:59:02 | INFO | train task=Ses01F epoch=5 batch=872/2529 step=2750 loss=0.6070 ce=0.5224 mse=0.1691 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1380882263183594, "reserved_gb": 2.44921875, "max_allocated_gb": 3.2347326278686523, "gpu_util_pct": "17", "gpu_mem_used_mb": "3141", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "69.82"}
2026-08-08 22:59:26 | INFO | train task=Ses01F epoch=5 batch=972/2529 step=2775 loss=0.6645 ce=0.1902 mse=0.9487 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1389508247375488, "reserved_gb": 1.794921875, "max_allocated_gb": 3.2347326278686523, "gpu_util_pct": "35", "gpu_mem_used_mb": "2471", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "63.92"}
2026-08-08 22:59:46 | INFO | train task=Ses01F epoch=5 batch=1072/2529 step=2800 loss=0.6338 ce=0.4910 mse=0.2856 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.13800048828125, "reserved_gb": 1.7109375, "max_allocated_gb": 3.2347326278686523, "gpu_util_pct": "12", "gpu_mem_used_mb": "2393", "gpu_mem_total_mb": "12288", "gpu_temp_c": "44", "gpu_power_w": "52.21"}
2026-08-08 23:00:09 | INFO | train task=Ses01F epoch=5 batch=1172/2529 step=2825 loss=0.4848 ce=0.2438 mse=0.4819 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1393241882324219, "reserved_gb": 1.73828125, "max_allocated_gb": 3.2347326278686523, "gpu_util_pct": "23", "gpu_mem_used_mb": "2421", "gpu_mem_total_mb": "12288", "gpu_temp_c": "44", "gpu_power_w": "54.10"}
2026-08-08 23:00:28 | INFO | train task=Ses01F epoch=5 batch=1272/2529 step=2850 loss=1.5899 ce=1.1789 mse=0.8220 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1385092735290527, "reserved_gb": 1.798828125, "max_allocated_gb": 3.2347326278686523, "gpu_util_pct": "14", "gpu_mem_used_mb": "2483", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "70.64"}
2026-08-08 23:00:50 | INFO | train task=Ses01F epoch=5 batch=1372/2529 step=2875 loss=0.9480 ce=0.3793 mse=1.1373 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.137965202331543, "reserved_gb": 1.828125, "max_allocated_gb": 3.2347326278686523, "gpu_util_pct": "23", "gpu_mem_used_mb": "2513", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "75.38"}
2026-08-08 23:01:09 | INFO | train task=Ses01F epoch=5 batch=1472/2529 step=2900 loss=0.7337 ce=0.1456 mse=1.1762 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1385226249694824, "reserved_gb": 1.79296875, "max_allocated_gb": 3.2347326278686523, "gpu_util_pct": "27", "gpu_mem_used_mb": "2477", "gpu_mem_total_mb": "12288", "gpu_temp_c": "43", "gpu_power_w": "46.08"}
2026-08-08 23:01:31 | INFO | train task=Ses01F epoch=5 batch=1572/2529 step=2925 loss=0.1761 ce=0.0933 mse=0.1656 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.138570785522461, "reserved_gb": 2.041015625, "max_allocated_gb": 3.2347326278686523, "gpu_util_pct": "16", "gpu_mem_used_mb": "2731", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "78.07"}
2026-08-08 23:01:53 | INFO | train task=Ses01F epoch=5 batch=1672/2529 step=2950 loss=0.8802 ce=0.7896 mse=0.1812 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.137892246246338, "reserved_gb": 2.009765625, "max_allocated_gb": 3.2347326278686523, "gpu_util_pct": "35", "gpu_mem_used_mb": "2698", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "62.06"}
2026-08-08 23:02:15 | INFO | train task=Ses01F epoch=5 batch=1772/2529 step=2975 loss=0.5738 ce=0.4774 mse=0.1929 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.137967586517334, "reserved_gb": 1.962890625, "max_allocated_gb": 3.2347326278686523, "gpu_util_pct": "16", "gpu_mem_used_mb": "2650", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "67.07"}
2026-08-08 23:02:37 | INFO | train task=Ses01F epoch=5 batch=1872/2529 step=3000 loss=0.5585 ce=0.5514 mse=0.0142 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1389665603637695, "reserved_gb": 1.712890625, "max_allocated_gb": 3.2347326278686523, "gpu_util_pct": "29", "gpu_mem_used_mb": "2394", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "66.54"}
2026-08-08 23:03:01 | INFO | train task=Ses01F epoch=5 batch=1972/2529 step=3025 loss=0.3181 ce=0.2919 mse=0.0524 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.138535976409912, "reserved_gb": 1.794921875, "max_allocated_gb": 3.2347326278686523, "gpu_util_pct": "20", "gpu_mem_used_mb": "2478", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "75.46"}
2026-08-08 23:03:25 | INFO | train task=Ses01F epoch=5 batch=2072/2529 step=3050 loss=0.5170 ce=0.2424 mse=0.5492 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1408090591430664, "reserved_gb": 1.517578125, "max_allocated_gb": 3.2347326278686523, "gpu_util_pct": "97", "gpu_mem_used_mb": "2194", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "82.53"}
2026-08-08 23:03:49 | INFO | train task=Ses01F epoch=5 batch=2172/2529 step=3075 loss=1.1017 ce=0.8650 mse=0.4734 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1378974914550781, "reserved_gb": 1.765625, "max_allocated_gb": 3.2347326278686523, "gpu_util_pct": "20", "gpu_mem_used_mb": "2448", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "71.40"}
2026-08-08 23:04:10 | INFO | train task=Ses01F epoch=5 batch=2272/2529 step=3100 loss=0.2847 ce=0.2752 mse=0.0190 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.138040542602539, "reserved_gb": 1.7265625, "max_allocated_gb": 3.2347326278686523, "gpu_util_pct": "24", "gpu_mem_used_mb": "2410", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "66.52"}
2026-08-08 23:04:37 | INFO | train task=Ses01F epoch=5 batch=2372/2529 step=3125 loss=0.1237 ce=0.1065 mse=0.0344 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1410417556762695, "reserved_gb": 2.041015625, "max_allocated_gb": 3.2347326278686523, "gpu_util_pct": "64", "gpu_mem_used_mb": "2732", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "74.13"}
2026-08-08 23:04:58 | INFO | train task=Ses01F epoch=5 batch=2472/2529 step=3150 loss=0.3824 ce=0.1017 mse=0.5615 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1380643844604492, "reserved_gb": 1.720703125, "max_allocated_gb": 3.2347326278686523, "gpu_util_pct": "31", "gpu_mem_used_mb": "2404", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "63.35"}

predict:   0%|          | 0/281 [00:00<?, ?it/s]

2026-08-08 23:05:30 | INFO | Epoch 05 task=Ses01F train_loss=0.9292 val_macro_f1=0.5368 val_mae=0.5528 epoch_seconds=573.4

predict:   0%|          | 0/255 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)

predict:   0%|          | 0/328 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\transformers\configuration_utils.py:335: UserWarning: Passing `gradient_checkpointing` to a config initialization is deprecated and will be removed in v5 Transformers. Using `model.gradient_checkpointing_enable()` instead, or if you are using the `Trainer` API, pass `gradient_checkpointing=True` in your `TrainingArguments`.
  warnings.warn(
2026-08-08 23:07:44 | INFO | Task C:\Users\HaseebWajid\Downloads\runs\dersx_paper_aligned\campaign_01\ablations\regression\three_gelu\seed_13\Ses01F parameters={'total': 163058987, 'trainable': 69083819, 'frozen': 93975168} scope={'corpus': 'IEMOCAP', 'protocol': 'strict_LOSO', 'heldout_speaker': 'Ses01F', 'seed': 13, 'stage': 'ablations/regression/three_gelu', 'profile': 'rtx3060_24h'}

epoch 1:   0%|          | 0/2529 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-08 23:08:07 | INFO | train task=Ses01F epoch=1 batch=100/2529 step=25 loss=3.1339 ce=2.0381 mse=2.1916 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2637009620666504, "reserved_gb": 2.6953125, "max_allocated_gb": 3.529967784881592, "gpu_util_pct": "99", "gpu_mem_used_mb": "3430", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "100.50"}
2026-08-08 23:08:28 | INFO | train task=Ses01F epoch=1 batch=200/2529 step=50 loss=2.4112 ce=2.1404 mse=0.5416 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.258171558380127, "reserved_gb": 3.31640625, "max_allocated_gb": 3.529967784881592, "gpu_util_pct": "29", "gpu_mem_used_mb": "4066", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "58.47"}
2026-08-08 23:08:48 | INFO | train task=Ses01F epoch=1 batch=300/2529 step=75 loss=2.6152 ce=1.8937 mse=1.4430 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.258148670196533, "reserved_gb": 2.9921875, "max_allocated_gb": 3.529967784881592, "gpu_util_pct": "13", "gpu_mem_used_mb": "3734", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "69.26"}
2026-08-08 23:09:09 | INFO | train task=Ses01F epoch=1 batch=400/2529 step=100 loss=2.0239 ce=1.7881 mse=0.4715 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2585391998291016, "reserved_gb": 2.896484375, "max_allocated_gb": 3.529967784881592, "gpu_util_pct": "39", "gpu_mem_used_mb": "3636", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "69.05"}
2026-08-08 23:09:35 | INFO | train task=Ses01F epoch=1 batch=500/2529 step=125 loss=2.5305 ce=1.6969 mse=1.6671 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.258598804473877, "reserved_gb": 2.955078125, "max_allocated_gb": 3.529967784881592, "gpu_util_pct": "30", "gpu_mem_used_mb": "3696", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "68.70"}
2026-08-08 23:09:56 | INFO | train task=Ses01F epoch=1 batch=600/2529 step=150 loss=2.0672 ce=1.7537 mse=0.6271 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2585978507995605, "reserved_gb": 3.125, "max_allocated_gb": 3.529967784881592, "gpu_util_pct": "34", "gpu_mem_used_mb": "3870", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "71.75"}
2026-08-08 23:10:17 | INFO | train task=Ses01F epoch=1 batch=700/2529 step=175 loss=2.5618 ce=2.3864 mse=0.3508 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.258859634399414, "reserved_gb": 3.150390625, "max_allocated_gb": 3.557720184326172, "gpu_util_pct": "30", "gpu_mem_used_mb": "3896", "gpu_mem_total_mb": "12288", "gpu_temp_c": "43", "gpu_power_w": "47.37"}
2026-08-08 23:10:40 | INFO | train task=Ses01F epoch=1 batch=800/2529 step=200 loss=2.0750 ce=2.0283 mse=0.0933 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.258589267730713, "reserved_gb": 2.8984375, "max_allocated_gb": 3.557720184326172, "gpu_util_pct": "32", "gpu_mem_used_mb": "3638", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "73.86"}
2026-08-08 23:11:07 | INFO | train task=Ses01F epoch=1 batch=900/2529 step=225 loss=2.8692 ce=1.7458 mse=2.2467 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.258359909057617, "reserved_gb": 4.267578125, "max_allocated_gb": 3.9036221504211426, "gpu_util_pct": "58", "gpu_mem_used_mb": "5040", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "89.84"}
2026-08-08 23:11:29 | INFO | train task=Ses01F epoch=1 batch=1000/2529 step=250 loss=2.5242 ce=2.1313 mse=0.7857 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.258598804473877, "reserved_gb": 2.88671875, "max_allocated_gb": 3.9036221504211426, "gpu_util_pct": "12", "gpu_mem_used_mb": "3626", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "80.46"}
2026-08-08 23:11:52 | INFO | train task=Ses01F epoch=1 batch=1100/2529 step=275 loss=1.7694 ce=1.5951 mse=0.3485 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2585439682006836, "reserved_gb": 3.208984375, "max_allocated_gb": 3.9036221504211426, "gpu_util_pct": "19", "gpu_mem_used_mb": "3956", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "64.07"}
2026-08-08 23:12:14 | INFO | train task=Ses01F epoch=1 batch=1200/2529 step=300 loss=2.5816 ce=1.7759 mse=1.6113 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.258847236633301, "reserved_gb": 3.017578125, "max_allocated_gb": 3.9036221504211426, "gpu_util_pct": "39", "gpu_mem_used_mb": "3760", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "59.14"}
2026-08-08 23:12:40 | INFO | train task=Ses01F epoch=1 batch=1300/2529 step=325 loss=1.4003 ce=1.2690 mse=0.2625 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2585668563842773, "reserved_gb": 2.951171875, "max_allocated_gb": 3.9036221504211426, "gpu_util_pct": "69", "gpu_mem_used_mb": "3692", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "86.44"}
2026-08-08 23:13:03 | INFO | train task=Ses01F epoch=1 batch=1400/2529 step=350 loss=2.3525 ce=1.6076 mse=1.4900 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.259648323059082, "reserved_gb": 2.884765625, "max_allocated_gb": 3.9036221504211426, "gpu_util_pct": "39", "gpu_mem_used_mb": "3624", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "69.17"}
2026-08-08 23:13:25 | INFO | train task=Ses01F epoch=1 batch=1500/2529 step=375 loss=1.3830 ce=0.9561 mse=0.8537 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.258708953857422, "reserved_gb": 2.892578125, "max_allocated_gb": 3.9036221504211426, "gpu_util_pct": "22", "gpu_mem_used_mb": "3632", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "85.07"}
2026-08-08 23:13:48 | INFO | train task=Ses01F epoch=1 batch=1600/2529 step=400 loss=1.1866 ce=0.9284 mse=0.5166 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2582240104675293, "reserved_gb": 2.880859375, "max_allocated_gb": 3.9036221504211426, "gpu_util_pct": "28", "gpu_mem_used_mb": "3620", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "66.74"}
2026-08-08 23:14:15 | INFO | train task=Ses01F epoch=1 batch=1700/2529 step=425 loss=1.8905 ce=1.7568 mse=0.2673 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.258625030517578, "reserved_gb": 2.9140625, "max_allocated_gb": 3.9036221504211426, "gpu_util_pct": "36", "gpu_mem_used_mb": "3654", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "76.68"}
2026-08-08 23:14:40 | INFO | train task=Ses01F epoch=1 batch=1800/2529 step=450 loss=1.2444 ce=0.9346 mse=0.6197 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.259143829345703, "reserved_gb": 3.25, "max_allocated_gb": 3.9036221504211426, "gpu_util_pct": "24", "gpu_mem_used_mb": "3997", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "69.93"}
2026-08-08 23:15:05 | INFO | train task=Ses01F epoch=1 batch=1900/2529 step=475 loss=1.0550 ce=0.7702 mse=0.5696 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.263457775115967, "reserved_gb": 2.94921875, "max_allocated_gb": 3.9036221504211426, "gpu_util_pct": "86", "gpu_mem_used_mb": "3689", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "75.57"}
2026-08-08 23:15:29 | INFO | train task=Ses01F epoch=1 batch=2000/2529 step=500 loss=2.9382 ce=2.5361 mse=0.8042 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2637009620666504, "reserved_gb": 2.947265625, "max_allocated_gb": 3.9036221504211426, "gpu_util_pct": "32", "gpu_mem_used_mb": "3687", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "62.06"}
2026-08-08 23:15:56 | INFO | train task=Ses01F epoch=1 batch=2100/2529 step=525 loss=1.1886 ce=1.1731 mse=0.0310 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2589216232299805, "reserved_gb": 2.9296875, "max_allocated_gb": 3.9036221504211426, "gpu_util_pct": "30", "gpu_mem_used_mb": "3669", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "66.12"}
2026-08-08 23:16:20 | INFO | train task=Ses01F epoch=1 batch=2200/2529 step=550 loss=0.6421 ce=0.6379 mse=0.0085 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.259561538696289, "reserved_gb": 2.892578125, "max_allocated_gb": 3.9036221504211426, "gpu_util_pct": "48", "gpu_mem_used_mb": "3631", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "68.56"}
2026-08-08 23:16:45 | INFO | train task=Ses01F epoch=1 batch=2300/2529 step=575 loss=2.3685 ce=2.1299 mse=0.4772 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.258370876312256, "reserved_gb": 3.140625, "max_allocated_gb": 3.9036221504211426, "gpu_util_pct": "9", "gpu_mem_used_mb": "3885", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "86.53"}
2026-08-08 23:17:11 | INFO | train task=Ses01F epoch=1 batch=2400/2529 step=600 loss=1.4709 ce=1.3468 mse=0.2483 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2589526176452637, "reserved_gb": 2.884765625, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "18", "gpu_mem_used_mb": "3623", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "60.90"}
2026-08-08 23:17:40 | INFO | train task=Ses01F epoch=1 batch=2500/2529 step=625 loss=2.0040 ce=1.9780 mse=0.0520 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2582345008850098, "reserved_gb": 2.88671875, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "17", "gpu_mem_used_mb": "3625", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "65.82"}

predict:   0%|          | 0/281 [00:00<?, ?it/s]

2026-08-08 23:18:32 | INFO | Epoch 01 task=Ses01F train_loss=2.0464 val_macro_f1=0.5247 val_mae=0.5510 epoch_seconds=647.5

epoch 2:   0%|          | 0/2529 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-08 23:18:51 | INFO | train task=Ses01F epoch=2 batch=68/2529 step=650 loss=1.6068 ce=1.4182 mse=0.3774 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.263075351715088, "reserved_gb": 3.486328125, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "20", "gpu_mem_used_mb": "4238", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "66.40"}
2026-08-08 23:19:11 | INFO | train task=Ses01F epoch=2 batch=168/2529 step=675 loss=1.3467 ce=1.1833 mse=0.3268 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.258601665496826, "reserved_gb": 2.892578125, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "31", "gpu_mem_used_mb": "3630", "gpu_mem_total_mb": "12288", "gpu_temp_c": "44", "gpu_power_w": "59.77"}
2026-08-08 23:19:33 | INFO | train task=Ses01F epoch=2 batch=268/2529 step=700 loss=1.4661 ce=1.1656 mse=0.6011 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1392550468444824, "reserved_gb": 1.80859375, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "18", "gpu_mem_used_mb": "2520", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "59.28"}
2026-08-08 23:19:58 | INFO | train task=Ses01F epoch=2 batch=368/2529 step=725 loss=2.2809 ce=1.7988 mse=0.9642 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.140861988067627, "reserved_gb": 2.662109375, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "55", "gpu_mem_used_mb": "3393", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "81.46"}
2026-08-08 23:20:17 | INFO | train task=Ses01F epoch=2 batch=468/2529 step=750 loss=1.7881 ce=1.5876 mse=0.4009 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1406512260437012, "reserved_gb": 1.837890625, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "19", "gpu_mem_used_mb": "2549", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "65.35"}
2026-08-08 23:20:38 | INFO | train task=Ses01F epoch=2 batch=568/2529 step=775 loss=0.6731 ce=0.5047 mse=0.3367 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1400232315063477, "reserved_gb": 1.828125, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "23", "gpu_mem_used_mb": "2539", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "75.41"}
2026-08-08 23:20:59 | INFO | train task=Ses01F epoch=2 batch=668/2529 step=800 loss=0.9449 ce=0.8150 mse=0.2598 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.139747142791748, "reserved_gb": 1.7265625, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "17", "gpu_mem_used_mb": "2435", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "58.64"}
2026-08-08 23:21:23 | INFO | train task=Ses01F epoch=2 batch=768/2529 step=825 loss=2.0577 ce=1.6840 mse=0.7473 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1393113136291504, "reserved_gb": 1.798828125, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "35", "gpu_mem_used_mb": "2509", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "65.27"}
2026-08-08 23:21:43 | INFO | train task=Ses01F epoch=2 batch=868/2529 step=850 loss=2.3551 ce=2.3003 mse=0.1097 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1394009590148926, "reserved_gb": 1.68359375, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "26", "gpu_mem_used_mb": "2391", "gpu_mem_total_mb": "12288", "gpu_temp_c": "43", "gpu_power_w": "50.70"}
2026-08-08 23:22:05 | INFO | train task=Ses01F epoch=2 batch=968/2529 step=875 loss=2.8400 ce=2.8022 mse=0.0756 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1393108367919922, "reserved_gb": 1.693359375, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "61", "gpu_mem_used_mb": "2400", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "74.61"}
2026-08-08 23:22:26 | INFO | train task=Ses01F epoch=2 batch=1068/2529 step=900 loss=2.1978 ce=1.9150 mse=0.5654 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1393475532531738, "reserved_gb": 1.869140625, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "18", "gpu_mem_used_mb": "2580", "gpu_mem_total_mb": "12288", "gpu_temp_c": "43", "gpu_power_w": "58.07"}
2026-08-08 23:22:50 | INFO | train task=Ses01F epoch=2 batch=1168/2529 step=925 loss=0.8979 ce=0.6926 mse=0.4107 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1398420333862305, "reserved_gb": 1.6875, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "17", "gpu_mem_used_mb": "2394", "gpu_mem_total_mb": "12288", "gpu_temp_c": "44", "gpu_power_w": "68.10"}
2026-08-08 23:23:12 | INFO | train task=Ses01F epoch=2 batch=1268/2529 step=950 loss=2.6965 ce=1.8497 mse=1.6935 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1414170265197754, "reserved_gb": 1.74609375, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "53", "gpu_mem_used_mb": "2454", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "82.29"}
2026-08-08 23:23:32 | INFO | train task=Ses01F epoch=2 batch=1368/2529 step=975 loss=2.6416 ce=2.5480 mse=0.1873 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1395783424377441, "reserved_gb": 1.728515625, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "19", "gpu_mem_used_mb": "2436", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "76.89"}
2026-08-08 23:23:53 | INFO | train task=Ses01F epoch=2 batch=1468/2529 step=1000 loss=0.4738 ce=0.4730 mse=0.0017 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1399965286254883, "reserved_gb": 1.865234375, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "16", "gpu_mem_used_mb": "2576", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "63.37"}
2026-08-08 23:24:18 | INFO | train task=Ses01F epoch=2 batch=1568/2529 step=1025 loss=1.3305 ce=1.1074 mse=0.4461 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1393237113952637, "reserved_gb": 1.701171875, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "22", "gpu_mem_used_mb": "2407", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "65.79"}
2026-08-08 23:24:38 | INFO | train task=Ses01F epoch=2 batch=1668/2529 step=1050 loss=2.9274 ce=2.9211 mse=0.0126 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1445317268371582, "reserved_gb": 2.384765625, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "46", "gpu_mem_used_mb": "3107", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "68.18"}
2026-08-08 23:25:00 | INFO | train task=Ses01F epoch=2 batch=1768/2529 step=1075 loss=0.6883 ce=0.6348 mse=0.1070 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1395788192749023, "reserved_gb": 1.76171875, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "29", "gpu_mem_used_mb": "2469", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "65.80"}
2026-08-08 23:25:23 | INFO | train task=Ses01F epoch=2 batch=1868/2529 step=1100 loss=1.2167 ce=0.9759 mse=0.4817 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.139388084411621, "reserved_gb": 1.6875, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "25", "gpu_mem_used_mb": "2393", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "70.39"}
2026-08-08 23:25:48 | INFO | train task=Ses01F epoch=2 batch=1968/2529 step=1125 loss=1.3904 ce=1.0824 mse=0.6160 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.140622615814209, "reserved_gb": 2.0625, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "49", "gpu_mem_used_mb": "2788", "gpu_mem_total_mb": "12288", "gpu_temp_c": "43", "gpu_power_w": "46.14"}
2026-08-08 23:26:10 | INFO | train task=Ses01F epoch=2 batch=2068/2529 step=1150 loss=0.9268 ce=0.8086 mse=0.2364 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1406445503234863, "reserved_gb": 1.890625, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "32", "gpu_mem_used_mb": "2612", "gpu_mem_total_mb": "12288", "gpu_temp_c": "44", "gpu_power_w": "64.59"}
2026-08-08 23:26:31 | INFO | train task=Ses01F epoch=2 batch=2168/2529 step=1175 loss=1.2276 ce=1.0981 mse=0.2589 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1396775245666504, "reserved_gb": 1.712890625, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "19", "gpu_mem_used_mb": "2430", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "61.29"}
2026-08-08 23:26:52 | INFO | train task=Ses01F epoch=2 batch=2268/2529 step=1200 loss=2.1325 ce=1.9839 mse=0.2972 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1395354270935059, "reserved_gb": 1.8203125, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "20", "gpu_mem_used_mb": "2540", "gpu_mem_total_mb": "12288", "gpu_temp_c": "44", "gpu_power_w": "59.02"}
2026-08-08 23:27:19 | INFO | train task=Ses01F epoch=2 batch=2368/2529 step=1225 loss=0.2229 ce=0.2132 mse=0.0193 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1408710479736328, "reserved_gb": 1.8515625, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "21", "gpu_mem_used_mb": "2572", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "79.35"}
2026-08-08 23:27:41 | INFO | train task=Ses01F epoch=2 batch=2468/2529 step=1250 loss=0.6320 ce=0.5382 mse=0.1875 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.139434814453125, "reserved_gb": 1.685546875, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "26", "gpu_mem_used_mb": "2402", "gpu_mem_total_mb": "12288", "gpu_temp_c": "43", "gpu_power_w": "54.10"}

predict:   0%|          | 0/281 [00:00<?, ?it/s]

2026-08-08 23:28:18 | INFO | Epoch 02 task=Ses01F train_loss=1.4606 val_macro_f1=0.5628 val_mae=0.5450 epoch_seconds=581.6

epoch 3:   0%|          | 0/2529 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-08 23:28:31 | INFO | train task=Ses01F epoch=3 batch=36/2529 step=1275 loss=0.8803 ce=0.8147 mse=0.1313 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1395049095153809, "reserved_gb": 1.912109375, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "46", "gpu_mem_used_mb": "2606", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "51.46"}
2026-08-08 23:28:52 | INFO | train task=Ses01F epoch=3 batch=136/2529 step=1300 loss=1.4163 ce=1.2229 mse=0.3868 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.139345645904541, "reserved_gb": 1.849609375, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "16", "gpu_mem_used_mb": "2656", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "105.85"}
2026-08-08 23:29:16 | INFO | train task=Ses01F epoch=3 batch=236/2529 step=1325 loss=2.0707 ce=1.6045 mse=0.9324 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1398329734802246, "reserved_gb": 2.04296875, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "16", "gpu_mem_used_mb": "2790", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "64.29"}
2026-08-08 23:29:38 | INFO | train task=Ses01F epoch=3 batch=336/2529 step=1350 loss=1.9220 ce=1.7988 mse=0.2464 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1394000053405762, "reserved_gb": 1.873046875, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "29", "gpu_mem_used_mb": "2598", "gpu_mem_total_mb": "12288", "gpu_temp_c": "53", "gpu_power_w": "82.66"}
2026-08-08 23:30:01 | INFO | train task=Ses01F epoch=3 batch=436/2529 step=1375 loss=0.8907 ce=0.7550 mse=0.2715 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.139244556427002, "reserved_gb": 1.748046875, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "69", "gpu_mem_used_mb": "2472", "gpu_mem_total_mb": "12288", "gpu_temp_c": "57", "gpu_power_w": "85.95"}
2026-08-08 23:30:21 | INFO | train task=Ses01F epoch=3 batch=536/2529 step=1400 loss=0.8656 ce=0.4092 mse=0.9128 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1409478187561035, "reserved_gb": 1.91796875, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "31", "gpu_mem_used_mb": "2646", "gpu_mem_total_mb": "12288", "gpu_temp_c": "56", "gpu_power_w": "64.54"}
2026-08-08 23:30:46 | INFO | train task=Ses01F epoch=3 batch=636/2529 step=1425 loss=2.2160 ce=2.0470 mse=0.3380 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1397061347961426, "reserved_gb": 2.767578125, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "32", "gpu_mem_used_mb": "3516", "gpu_mem_total_mb": "12288", "gpu_temp_c": "57", "gpu_power_w": "74.68"}
2026-08-08 23:31:06 | INFO | train task=Ses01F epoch=3 batch=736/2529 step=1450 loss=1.4046 ce=1.2874 mse=0.2345 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1397604942321777, "reserved_gb": 1.6953125, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "46", "gpu_mem_used_mb": "2418", "gpu_mem_total_mb": "12288", "gpu_temp_c": "53", "gpu_power_w": "67.48"}
2026-08-08 23:31:29 | INFO | train task=Ses01F epoch=3 batch=836/2529 step=1475 loss=1.2231 ce=1.0682 mse=0.3099 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1395559310913086, "reserved_gb": 2.181640625, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "40", "gpu_mem_used_mb": "2916", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "74.72"}
2026-08-08 23:31:50 | INFO | train task=Ses01F epoch=3 batch=936/2529 step=1500 loss=0.6065 ce=0.5263 mse=0.1603 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1394495964050293, "reserved_gb": 2.30078125, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "22", "gpu_mem_used_mb": "3040", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "71.01"}
2026-08-08 23:32:14 | INFO | train task=Ses01F epoch=3 batch=1036/2529 step=1525 loss=1.9193 ce=1.6045 mse=0.6296 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1394877433776855, "reserved_gb": 1.7109375, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "23", "gpu_mem_used_mb": "2436", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "53.16"}
2026-08-08 23:32:35 | INFO | train task=Ses01F epoch=3 batch=1136/2529 step=1550 loss=0.0987 ce=0.0791 mse=0.0392 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1443753242492676, "reserved_gb": 2.25, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "17", "gpu_mem_used_mb": "3009", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "48.13"}
2026-08-08 23:32:54 | INFO | train task=Ses01F epoch=3 batch=1236/2529 step=1575 loss=0.4696 ce=0.2264 mse=0.4865 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.139376163482666, "reserved_gb": 1.697265625, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "10", "gpu_mem_used_mb": "2442", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "65.14"}
2026-08-08 23:33:14 | INFO | train task=Ses01F epoch=3 batch=1336/2529 step=1600 loss=0.6481 ce=0.2728 mse=0.7508 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1399240493774414, "reserved_gb": 1.79296875, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "38", "gpu_mem_used_mb": "2525", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "74.95"}
2026-08-08 23:33:36 | INFO | train task=Ses01F epoch=3 batch=1436/2529 step=1625 loss=0.6979 ce=0.6940 mse=0.0078 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1408710479736328, "reserved_gb": 1.703125, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "44", "gpu_mem_used_mb": "2447", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "69.49"}
2026-08-08 23:33:58 | INFO | train task=Ses01F epoch=3 batch=1536/2529 step=1650 loss=0.2237 ce=0.0799 mse=0.2878 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.141787052154541, "reserved_gb": 1.8984375, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "11", "gpu_mem_used_mb": "2647", "gpu_mem_total_mb": "12288", "gpu_temp_c": "42", "gpu_power_w": "38.72"}
2026-08-08 23:34:19 | INFO | train task=Ses01F epoch=3 batch=1636/2529 step=1675 loss=0.5268 ce=0.4703 mse=0.1129 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1404609680175781, "reserved_gb": 1.951171875, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "27", "gpu_mem_used_mb": "2701", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "79.07"}
2026-08-08 23:34:39 | INFO | train task=Ses01F epoch=3 batch=1736/2529 step=1700 loss=0.7041 ce=0.3071 mse=0.7941 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1411628723144531, "reserved_gb": 1.98828125, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "39", "gpu_mem_used_mb": "2743", "gpu_mem_total_mb": "12288", "gpu_temp_c": "43", "gpu_power_w": "44.35"}
2026-08-08 23:35:02 | INFO | train task=Ses01F epoch=3 batch=1836/2529 step=1725 loss=0.5913 ce=0.3597 mse=0.4631 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1393256187438965, "reserved_gb": 1.904296875, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "17", "gpu_mem_used_mb": "2657", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "67.02"}
2026-08-08 23:35:25 | INFO | train task=Ses01F epoch=3 batch=1936/2529 step=1750 loss=0.8056 ce=0.7802 mse=0.0509 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1400485038757324, "reserved_gb": 1.859375, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "19", "gpu_mem_used_mb": "2611", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "74.25"}
2026-08-08 23:35:48 | INFO | train task=Ses01F epoch=3 batch=2036/2529 step=1775 loss=2.0489 ce=1.4453 mse=1.2071 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.140058994293213, "reserved_gb": 1.751953125, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "29", "gpu_mem_used_mb": "2501", "gpu_mem_total_mb": "12288", "gpu_temp_c": "43", "gpu_power_w": "47.09"}
2026-08-08 23:36:10 | INFO | train task=Ses01F epoch=3 batch=2136/2529 step=1800 loss=0.8781 ce=0.7427 mse=0.2708 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1405057907104492, "reserved_gb": 1.6953125, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "37", "gpu_mem_used_mb": "2443", "gpu_mem_total_mb": "12288", "gpu_temp_c": "44", "gpu_power_w": "58.23"}
2026-08-08 23:36:34 | INFO | train task=Ses01F epoch=3 batch=2236/2529 step=1825 loss=0.8661 ce=0.6216 mse=0.4889 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.139479160308838, "reserved_gb": 1.896484375, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "28", "gpu_mem_used_mb": "2649", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "64.44"}
2026-08-08 23:36:56 | INFO | train task=Ses01F epoch=3 batch=2336/2529 step=1850 loss=1.5289 ce=1.5269 mse=0.0040 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1395792961120605, "reserved_gb": 1.705078125, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "47", "gpu_mem_used_mb": "2453", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "70.14"}
2026-08-08 23:37:21 | INFO | train task=Ses01F epoch=3 batch=2436/2529 step=1875 loss=0.8157 ce=0.4917 mse=0.6481 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1396245956420898, "reserved_gb": 1.734375, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "42", "gpu_mem_used_mb": "2483", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "85.76"}

predict:   0%|          | 0/281 [00:00<?, ?it/s]

2026-08-08 23:38:00 | INFO | Epoch 03 task=Ses01F train_loss=1.2417 val_macro_f1=0.5744 val_mae=0.5138 epoch_seconds=576.4

epoch 4:   0%|          | 0/2529 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-08 23:38:06 | INFO | train task=Ses01F epoch=4 batch=4/2529 step=1900 loss=0.5131 ce=0.3604 mse=0.3053 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1392760276794434, "reserved_gb": 11.91796875, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "46", "gpu_mem_used_mb": "12072", "gpu_mem_total_mb": "12288", "gpu_temp_c": "43", "gpu_power_w": "29.38"}
2026-08-08 23:38:29 | INFO | train task=Ses01F epoch=4 batch=104/2529 step=1925 loss=0.3384 ce=0.3024 mse=0.0721 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1397061347961426, "reserved_gb": 1.69140625, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "20", "gpu_mem_used_mb": "2320", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "61.80"}
2026-08-08 23:38:49 | INFO | train task=Ses01F epoch=4 batch=204/2529 step=1950 loss=0.8822 ce=0.8140 mse=0.1364 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.141059398651123, "reserved_gb": 1.876953125, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "35", "gpu_mem_used_mb": "2510", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "52.47"}
2026-08-08 23:39:10 | INFO | train task=Ses01F epoch=4 batch=304/2529 step=1975 loss=1.1877 ce=0.8068 mse=0.7618 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.139503002166748, "reserved_gb": 2.169921875, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "24", "gpu_mem_used_mb": "2809", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "71.28"}
2026-08-08 23:39:30 | INFO | train task=Ses01F epoch=4 batch=404/2529 step=2000 loss=1.4749 ce=1.2117 mse=0.5264 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1422228813171387, "reserved_gb": 2.02734375, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "25", "gpu_mem_used_mb": "2663", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "63.96"}
2026-08-08 23:39:53 | INFO | train task=Ses01F epoch=4 batch=504/2529 step=2025 loss=0.9657 ce=0.8043 mse=0.3228 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.139449119567871, "reserved_gb": 2.818359375, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "17", "gpu_mem_used_mb": "3488", "gpu_mem_total_mb": "12288", "gpu_temp_c": "53", "gpu_power_w": "70.02"}
2026-08-08 23:40:13 | INFO | train task=Ses01F epoch=4 batch=604/2529 step=2050 loss=0.2562 ce=0.2354 mse=0.0417 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1403923034667969, "reserved_gb": 1.841796875, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "42", "gpu_mem_used_mb": "2488", "gpu_mem_total_mb": "12288", "gpu_temp_c": "55", "gpu_power_w": "65.98"}
2026-08-08 23:40:34 | INFO | train task=Ses01F epoch=4 batch=704/2529 step=2075 loss=0.5724 ce=0.5565 mse=0.0320 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1399455070495605, "reserved_gb": 1.939453125, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "27", "gpu_mem_used_mb": "2592", "gpu_mem_total_mb": "12288", "gpu_temp_c": "56", "gpu_power_w": "66.92"}
2026-08-08 23:40:53 | INFO | train task=Ses01F epoch=4 batch=804/2529 step=2100 loss=0.5221 ce=0.1477 mse=0.7487 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.139467716217041, "reserved_gb": 1.70703125, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "37", "gpu_mem_used_mb": "2354", "gpu_mem_total_mb": "12288", "gpu_temp_c": "53", "gpu_power_w": "63.81"}
2026-08-08 23:41:17 | INFO | train task=Ses01F epoch=4 batch=904/2529 step=2125 loss=1.0576 ce=0.7307 mse=0.6540 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1400656700134277, "reserved_gb": 1.896484375, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "29", "gpu_mem_used_mb": "2548", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "67.83"}
2026-08-08 23:41:39 | INFO | train task=Ses01F epoch=4 batch=1004/2529 step=2150 loss=1.4325 ce=1.3228 mse=0.2195 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1396450996398926, "reserved_gb": 2.294921875, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "60", "gpu_mem_used_mb": "2956", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "70.89"}
2026-08-08 23:41:59 | INFO | train task=Ses01F epoch=4 batch=1104/2529 step=2175 loss=0.1489 ce=0.0548 mse=0.1882 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1402907371520996, "reserved_gb": 1.84375, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "24", "gpu_mem_used_mb": "2494", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "77.65"}
2026-08-08 23:42:19 | INFO | train task=Ses01F epoch=4 batch=1204/2529 step=2200 loss=1.2713 ce=1.1584 mse=0.2259 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1399054527282715, "reserved_gb": 1.7421875, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "16", "gpu_mem_used_mb": "2390", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "59.16"}
2026-08-08 23:42:45 | INFO | train task=Ses01F epoch=4 batch=1304/2529 step=2225 loss=1.4821 ce=1.1028 mse=0.7586 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1406655311584473, "reserved_gb": 1.953125, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "29", "gpu_mem_used_mb": "2606", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "79.01"}
2026-08-08 23:43:06 | INFO | train task=Ses01F epoch=4 batch=1404/2529 step=2250 loss=1.1682 ce=0.9261 mse=0.4844 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1411113739013672, "reserved_gb": 2.044921875, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "41", "gpu_mem_used_mb": "2700", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "75.56"}
2026-08-08 23:43:28 | INFO | train task=Ses01F epoch=4 batch=1504/2529 step=2275 loss=0.5179 ce=0.5059 mse=0.0239 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1397008895874023, "reserved_gb": 1.76953125, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "33", "gpu_mem_used_mb": "2418", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "65.47"}
2026-08-08 23:43:48 | INFO | train task=Ses01F epoch=4 batch=1604/2529 step=2300 loss=2.6704 ce=2.3831 mse=0.5746 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1393113136291504, "reserved_gb": 1.71875, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "34", "gpu_mem_used_mb": "2366", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "79.97"}
2026-08-08 23:44:13 | INFO | train task=Ses01F epoch=4 batch=1704/2529 step=2325 loss=0.3510 ce=0.1168 mse=0.4684 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1409153938293457, "reserved_gb": 1.8203125, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "26", "gpu_mem_used_mb": "2470", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "71.69"}
2026-08-08 23:44:33 | INFO | train task=Ses01F epoch=4 batch=1804/2529 step=2350 loss=0.9240 ce=0.9157 mse=0.0167 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1396021842956543, "reserved_gb": 1.6953125, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "44", "gpu_mem_used_mb": "2342", "gpu_mem_total_mb": "12288", "gpu_temp_c": "44", "gpu_power_w": "41.23"}
2026-08-08 23:44:55 | INFO | train task=Ses01F epoch=4 batch=1904/2529 step=2375 loss=0.8713 ce=0.6405 mse=0.4615 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1398377418518066, "reserved_gb": 1.701171875, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "18", "gpu_mem_used_mb": "2348", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "75.62"}
2026-08-08 23:45:17 | INFO | train task=Ses01F epoch=4 batch=2004/2529 step=2400 loss=0.5984 ce=0.3079 mse=0.5809 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1396822929382324, "reserved_gb": 1.97265625, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "36", "gpu_mem_used_mb": "2626", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "77.83"}
2026-08-08 23:45:41 | INFO | train task=Ses01F epoch=4 batch=2104/2529 step=2425 loss=1.4046 ce=1.0969 mse=0.6155 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1392560005187988, "reserved_gb": 2.125, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "24", "gpu_mem_used_mb": "2782", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "63.76"}
2026-08-08 23:46:01 | INFO | train task=Ses01F epoch=4 batch=2204/2529 step=2450 loss=0.6056 ce=0.0879 mse=1.0353 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1401610374450684, "reserved_gb": 1.91015625, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "36", "gpu_mem_used_mb": "2562", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "67.11"}
2026-08-08 23:46:24 | INFO | train task=Ses01F epoch=4 batch=2304/2529 step=2475 loss=0.7395 ce=0.5241 mse=0.4308 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.139388084411621, "reserved_gb": 1.79296875, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "37", "gpu_mem_used_mb": "2442", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "112.36"}
2026-08-08 23:46:47 | INFO | train task=Ses01F epoch=4 batch=2404/2529 step=2500 loss=3.4718 ce=3.1572 mse=0.6293 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1395330429077148, "reserved_gb": 1.697265625, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "19", "gpu_mem_used_mb": "2344", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "75.48"}
2026-08-08 23:47:12 | INFO | train task=Ses01F epoch=4 batch=2504/2529 step=2525 loss=0.3826 ce=0.2766 mse=0.2121 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1397051811218262, "reserved_gb": 1.8671875, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "16", "gpu_mem_used_mb": "2518", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "63.76"}

predict:   0%|          | 0/281 [00:00<?, ?it/s]

2026-08-08 23:47:36 | INFO | Epoch 04 task=Ses01F train_loss=1.0564 val_macro_f1=0.5203 val_mae=0.5376 epoch_seconds=571.0

epoch 5:   0%|          | 0/2529 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-08 23:47:53 | INFO | train task=Ses01F epoch=5 batch=72/2529 step=2550 loss=0.5971 ce=0.3528 mse=0.4884 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1396784782409668, "reserved_gb": 2.939453125, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "20", "gpu_mem_used_mb": "3616", "gpu_mem_total_mb": "12288", "gpu_temp_c": "44", "gpu_power_w": "59.81"}
2026-08-08 23:48:12 | INFO | train task=Ses01F epoch=5 batch=172/2529 step=2575 loss=0.5654 ce=0.2508 mse=0.6293 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1394882202148438, "reserved_gb": 1.8984375, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "17", "gpu_mem_used_mb": "2549", "gpu_mem_total_mb": "12288", "gpu_temp_c": "43", "gpu_power_w": "47.39"}
2026-08-08 23:48:31 | INFO | train task=Ses01F epoch=5 batch=272/2529 step=2600 loss=0.2880 ce=0.0770 mse=0.4220 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1414403915405273, "reserved_gb": 1.951171875, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "13", "gpu_mem_used_mb": "2603", "gpu_mem_total_mb": "12288", "gpu_temp_c": "44", "gpu_power_w": "65.59"}
2026-08-08 23:48:55 | INFO | train task=Ses01F epoch=5 batch=372/2529 step=2625 loss=3.3515 ce=2.9967 mse=0.7095 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.139967441558838, "reserved_gb": 1.90625, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "50", "gpu_mem_used_mb": "2557", "gpu_mem_total_mb": "12288", "gpu_temp_c": "44", "gpu_power_w": "41.00"}
2026-08-08 23:49:15 | INFO | train task=Ses01F epoch=5 batch=472/2529 step=2650 loss=2.4160 ce=1.8670 mse=1.0980 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.144432544708252, "reserved_gb": 2.06640625, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "13", "gpu_mem_used_mb": "2721", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "54.83"}
2026-08-08 23:49:37 | INFO | train task=Ses01F epoch=5 batch=572/2529 step=2675 loss=0.2466 ce=0.1397 mse=0.2138 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1408276557922363, "reserved_gb": 1.705078125, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "46", "gpu_mem_used_mb": "2351", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "87.97"}
2026-08-08 23:49:57 | INFO | train task=Ses01F epoch=5 batch=672/2529 step=2700 loss=0.5355 ce=0.0655 mse=0.9400 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.139467716217041, "reserved_gb": 2.525390625, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "12", "gpu_mem_used_mb": "3191", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "51.02"}
2026-08-08 23:50:20 | INFO | train task=Ses01F epoch=5 batch=772/2529 step=2725 loss=0.9664 ce=0.6134 mse=0.7061 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1412997245788574, "reserved_gb": 2.03125, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "30", "gpu_mem_used_mb": "2685", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "54.21"}
2026-08-08 23:50:40 | INFO | train task=Ses01F epoch=5 batch=872/2529 step=2750 loss=0.7344 ce=0.5613 mse=0.3462 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1394877433776855, "reserved_gb": 2.509765625, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "59", "gpu_mem_used_mb": "3175", "gpu_mem_total_mb": "12288", "gpu_temp_c": "54", "gpu_power_w": "73.01"}
2026-08-08 23:51:02 | INFO | train task=Ses01F epoch=5 batch=972/2529 step=2775 loss=0.9131 ce=0.2745 mse=1.2772 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.140350341796875, "reserved_gb": 1.826171875, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "25", "gpu_mem_used_mb": "2475", "gpu_mem_total_mb": "12288", "gpu_temp_c": "56", "gpu_power_w": "62.37"}
2026-08-08 23:51:21 | INFO | train task=Ses01F epoch=5 batch=1072/2529 step=2800 loss=0.5134 ce=0.3018 mse=0.4231 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1394000053405762, "reserved_gb": 1.68359375, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "32", "gpu_mem_used_mb": "2328", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "60.30"}
2026-08-08 23:51:44 | INFO | train task=Ses01F epoch=5 batch=1172/2529 step=2825 loss=0.5223 ce=0.2382 mse=0.5681 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.140723705291748, "reserved_gb": 1.724609375, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "23", "gpu_mem_used_mb": "2370", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "49.37"}
2026-08-08 23:52:04 | INFO | train task=Ses01F epoch=5 batch=1272/2529 step=2850 loss=2.7479 ce=2.3447 mse=0.8064 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.139908790588379, "reserved_gb": 1.75390625, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "30", "gpu_mem_used_mb": "2400", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "63.19"}
2026-08-08 23:52:26 | INFO | train task=Ses01F epoch=5 batch=1372/2529 step=2875 loss=0.9911 ce=0.3957 mse=1.1907 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1393647193908691, "reserved_gb": 1.873046875, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "26", "gpu_mem_used_mb": "2522", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "67.83"}
2026-08-08 23:52:45 | INFO | train task=Ses01F epoch=5 batch=1472/2529 step=2900 loss=0.8959 ce=0.2069 mse=1.3779 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1399221420288086, "reserved_gb": 1.767578125, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "21", "gpu_mem_used_mb": "2414", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "64.32"}
2026-08-08 23:53:08 | INFO | train task=Ses01F epoch=5 batch=1572/2529 step=2925 loss=0.7117 ce=0.5902 mse=0.2430 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.139970302581787, "reserved_gb": 2.017578125, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "38", "gpu_mem_used_mb": "2670", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "80.03"}
2026-08-08 23:53:29 | INFO | train task=Ses01F epoch=5 batch=1672/2529 step=2950 loss=0.7393 ce=0.5693 mse=0.3401 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.139291763305664, "reserved_gb": 1.978515625, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "34", "gpu_mem_used_mb": "2629", "gpu_mem_total_mb": "12288", "gpu_temp_c": "44", "gpu_power_w": "60.37"}
2026-08-08 23:53:50 | INFO | train task=Ses01F epoch=5 batch=1772/2529 step=2975 loss=1.1813 ce=1.1041 mse=0.1544 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1393671035766602, "reserved_gb": 1.955078125, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "12", "gpu_mem_used_mb": "2605", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "65.76"}
2026-08-08 23:54:13 | INFO | train task=Ses01F epoch=5 batch=1872/2529 step=3000 loss=0.7766 ce=0.7737 mse=0.0058 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1403660774230957, "reserved_gb": 1.703125, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "44", "gpu_mem_used_mb": "2347", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "69.43"}
2026-08-08 23:54:37 | INFO | train task=Ses01F epoch=5 batch=1972/2529 step=3025 loss=0.5116 ce=0.4364 mse=0.1505 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1399354934692383, "reserved_gb": 1.85546875, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "25", "gpu_mem_used_mb": "2503", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "74.16"}
2026-08-08 23:55:00 | INFO | train task=Ses01F epoch=5 batch=2072/2529 step=3050 loss=0.4407 ce=0.0818 mse=0.7178 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1417431831359863, "reserved_gb": 1.724609375, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "59", "gpu_mem_used_mb": "2369", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "80.05"}
2026-08-08 23:55:22 | INFO | train task=Ses01F epoch=5 batch=2172/2529 step=3075 loss=1.6860 ce=1.5687 mse=0.2345 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1392970085144043, "reserved_gb": 1.759765625, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "16", "gpu_mem_used_mb": "2404", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "69.43"}
2026-08-08 23:55:43 | INFO | train task=Ses01F epoch=5 batch=2272/2529 step=3100 loss=0.1197 ce=0.1162 mse=0.0070 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1394400596618652, "reserved_gb": 1.720703125, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "20", "gpu_mem_used_mb": "2364", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "67.53"}
2026-08-08 23:56:10 | INFO | train task=Ses01F epoch=5 batch=2372/2529 step=3125 loss=0.1023 ce=0.0750 mse=0.0545 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.143059253692627, "reserved_gb": 2.015625, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "53", "gpu_mem_used_mb": "2666", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "65.39"}
2026-08-08 23:56:32 | INFO | train task=Ses01F epoch=5 batch=2472/2529 step=3150 loss=0.5186 ce=0.2254 mse=0.5863 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1394639015197754, "reserved_gb": 1.72265625, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "18", "gpu_mem_used_mb": "2366", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "67.81"}

predict:   0%|          | 0/281 [00:00<?, ?it/s]

2026-08-08 23:57:04 | INFO | Epoch 05 task=Ses01F train_loss=0.9415 val_macro_f1=0.5372 val_mae=0.5516 epoch_seconds=565.4

predict:   0%|          | 0/255 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)

predict:   0%|          | 0/328 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
2026-08-08 23:58:29 | INFO | Task e79a9da83e9280e0_regression_ablation -> complete
2026-08-08 23:58:31 | INFO | Manuscript outputs refreshed: 20 tables, 4 figures
2026-08-08 23:58:31 | INFO | Task fde94e460302e7c0_encoder_ablation -> running
2026-08-08 23:58:31 | INFO | Task C:\Users\HaseebWajid\Downloads\runs\dersx_paper_aligned\campaign_01\ablations\encoder\logmel_cnn\seed_13\Ses01F parameters={'total': 2227103, 'trainable': 2227103, 'frozen': 0} scope={'corpus': 'IEMOCAP', 'protocol': 'strict_LOSO', 'heldout_speaker': 'Ses01F', 'seed': 13, 'stage': 'ablations/encoder/logmel_cnn', 'profile': 'rtx3060_24h'}

epoch 1:   0%|          | 0/2529 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
2026-08-09 00:05:55 | INFO | train task=Ses01F epoch=1 batch=100/2529 step=25 loss=nan ce=nan mse=nan gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 0.05433988571166992, "reserved_gb": 0.130859375, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "9", "gpu_mem_used_mb": "884", "gpu_mem_total_mb": "12288", "gpu_temp_c": "42", "gpu_power_w": "14.57"}
2026-08-09 00:10:54 | INFO | train task=Ses01F epoch=1 batch=200/2529 step=50 loss=nan ce=nan mse=nan gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 0.05136537551879883, "reserved_gb": 0.1328125, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "0", "gpu_mem_used_mb": "911", "gpu_mem_total_mb": "12288", "gpu_temp_c": "40", "gpu_power_w": "11.34"}
2026-08-09 00:15:29 | INFO | train task=Ses01F epoch=1 batch=300/2529 step=75 loss=nan ce=nan mse=nan gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 0.05134439468383789, "reserved_gb": 0.1328125, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "0", "gpu_mem_used_mb": "867", "gpu_mem_total_mb": "12288", "gpu_temp_c": "41", "gpu_power_w": "30.96"}
2026-08-09 00:19:01 | INFO | train task=Ses01F epoch=1 batch=400/2529 step=100 loss=nan ce=nan mse=nan gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 0.051683902740478516, "reserved_gb": 0.1328125, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "0", "gpu_mem_used_mb": "849", "gpu_mem_total_mb": "12288", "gpu_temp_c": "39", "gpu_power_w": "11.94"}
2026-08-09 00:23:43 | INFO | train task=Ses01F epoch=1 batch=500/2529 step=125 loss=nan ce=nan mse=nan gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 0.051808834075927734, "reserved_gb": 0.1328125, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "78", "gpu_mem_used_mb": "847", "gpu_mem_total_mb": "12288", "gpu_temp_c": "41", "gpu_power_w": "12.84"}
2026-08-09 00:27:00 | INFO | train task=Ses01F epoch=1 batch=600/2529 step=150 loss=nan ce=nan mse=nan gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 0.051732540130615234, "reserved_gb": 0.1328125, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "93", "gpu_mem_used_mb": "850", "gpu_mem_total_mb": "12288", "gpu_temp_c": "41", "gpu_power_w": "12.74"}
2026-08-09 00:29:07 | INFO | train task=Ses01F epoch=1 batch=700/2529 step=175 loss=nan ce=nan mse=nan gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 0.0519404411315918, "reserved_gb": 0.134765625, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "0", "gpu_mem_used_mb": "851", "gpu_mem_total_mb": "12288", "gpu_temp_c": "41", "gpu_power_w": "11.60"}
2026-08-09 00:32:04 | INFO | train task=Ses01F epoch=1 batch=800/2529 step=200 loss=nan ce=nan mse=nan gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 0.05179929733276367, "reserved_gb": 0.1328125, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "43", "gpu_mem_used_mb": "847", "gpu_mem_total_mb": "12288", "gpu_temp_c": "42", "gpu_power_w": "12.04"}
2026-08-09 00:34:30 | INFO | train task=Ses01F epoch=1 batch=900/2529 step=225 loss=nan ce=nan mse=nan gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 0.05153226852416992, "reserved_gb": 0.185546875, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "100", "gpu_mem_used_mb": "900", "gpu_mem_total_mb": "12288", "gpu_temp_c": "43", "gpu_power_w": "13.09"}
2026-08-09 00:36:09 | INFO | train task=Ses01F epoch=1 batch=1000/2529 step=250 loss=nan ce=nan mse=nan gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 0.051808834075927734, "reserved_gb": 0.158203125, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "91", "gpu_mem_used_mb": "871", "gpu_mem_total_mb": "12288", "gpu_temp_c": "43", "gpu_power_w": "12.50"}
2026-08-09 00:38:26 | INFO | train task=Ses01F epoch=1 batch=1100/2529 step=275 loss=nan ce=nan mse=nan gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 0.05168771743774414, "reserved_gb": 0.1328125, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "0", "gpu_mem_used_mb": "846", "gpu_mem_total_mb": "12288", "gpu_temp_c": "42", "gpu_power_w": "11.76"}
2026-08-09 00:40:52 | INFO | train task=Ses01F epoch=1 batch=1200/2529 step=300 loss=nan ce=nan mse=nan gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 0.051930904388427734, "reserved_gb": 0.134765625, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "0", "gpu_mem_used_mb": "847", "gpu_mem_total_mb": "12288", "gpu_temp_c": "43", "gpu_power_w": "11.83"}
2026-08-09 00:42:46 | INFO | train task=Ses01F epoch=1 batch=1300/2529 step=325 loss=nan ce=nan mse=nan gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 0.051706790924072266, "reserved_gb": 0.1328125, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "0", "gpu_mem_used_mb": "844", "gpu_mem_total_mb": "12288", "gpu_temp_c": "43", "gpu_power_w": "11.87"}
2026-08-09 00:44:41 | INFO | train task=Ses01F epoch=1 batch=1400/2529 step=350 loss=nan ce=nan mse=nan gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 0.05251169204711914, "reserved_gb": 0.154296875, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "1", "gpu_mem_used_mb": "865", "gpu_mem_total_mb": "12288", "gpu_temp_c": "42", "gpu_power_w": "11.89"}
2026-08-09 00:46:17 | INFO | train task=Ses01F epoch=1 batch=1500/2529 step=375 loss=nan ce=nan mse=nan gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 0.05182218551635742, "reserved_gb": 0.134765625, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "3", "gpu_mem_used_mb": "844", "gpu_mem_total_mb": "12288", "gpu_temp_c": "43", "gpu_power_w": "14.94"}
2026-08-09 00:46:51 | INFO | train task=Ses01F epoch=1 batch=1600/2529 step=400 loss=nan ce=nan mse=nan gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 0.05141305923461914, "reserved_gb": 0.1328125, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "0", "gpu_mem_used_mb": "842", "gpu_mem_total_mb": "12288", "gpu_temp_c": "42", "gpu_power_w": "12.12"}
2026-08-09 00:47:59 | INFO | train task=Ses01F epoch=1 batch=1700/2529 step=425 loss=nan ce=nan mse=nan gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 0.05175447463989258, "reserved_gb": 0.154296875, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "43", "gpu_mem_used_mb": "864", "gpu_mem_total_mb": "12288", "gpu_temp_c": "43", "gpu_power_w": "16.32"}
2026-08-09 00:49:39 | INFO | train task=Ses01F epoch=1 batch=1800/2529 step=450 loss=nan ce=nan mse=nan gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 0.0521550178527832, "reserved_gb": 0.1328125, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "0", "gpu_mem_used_mb": "841", "gpu_mem_total_mb": "12288", "gpu_temp_c": "43", "gpu_power_w": "11.76"}
2026-08-09 00:50:57 | INFO | train task=Ses01F epoch=1 batch=1900/2529 step=475 loss=nan ce=nan mse=nan gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 0.05434083938598633, "reserved_gb": 0.130859375, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "0", "gpu_mem_used_mb": "838", "gpu_mem_total_mb": "12288", "gpu_temp_c": "42", "gpu_power_w": "11.75"}
2026-08-09 00:52:07 | INFO | train task=Ses01F epoch=1 batch=2000/2529 step=500 loss=nan ce=nan mse=nan gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 0.05405378341674805, "reserved_gb": 0.15234375, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "0", "gpu_mem_used_mb": "862", "gpu_mem_total_mb": "12288", "gpu_temp_c": "43", "gpu_power_w": "14.15"}
2026-08-09 00:53:00 | INFO | train task=Ses01F epoch=1 batch=2100/2529 step=525 loss=nan ce=nan mse=nan gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 0.05198812484741211, "reserved_gb": 0.134765625, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "35", "gpu_mem_used_mb": "843", "gpu_mem_total_mb": "12288", "gpu_temp_c": "43", "gpu_power_w": "16.45"}
2026-08-09 00:53:59 | INFO | train task=Ses01F epoch=1 batch=2200/2529 step=550 loss=nan ce=nan mse=nan gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 0.05245161056518555, "reserved_gb": 0.134765625, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "6", "gpu_mem_used_mb": "843", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "24.25"}
2026-08-09 00:54:54 | INFO | train task=Ses01F epoch=1 batch=2300/2529 step=575 loss=nan ce=nan mse=nan gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 0.051541805267333984, "reserved_gb": 0.1328125, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "99", "gpu_mem_used_mb": "840", "gpu_mem_total_mb": "12288", "gpu_temp_c": "44", "gpu_power_w": "12.83"}
2026-08-09 00:56:05 | INFO | train task=Ses01F epoch=1 batch=2400/2529 step=600 loss=nan ce=nan mse=nan gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 0.052011966705322266, "reserved_gb": 0.158203125, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "0", "gpu_mem_used_mb": "866", "gpu_mem_total_mb": "12288", "gpu_temp_c": "43", "gpu_power_w": "11.80"}
2026-08-09 00:57:18 | INFO | train task=Ses01F epoch=1 batch=2500/2529 step=625 loss=nan ce=nan mse=nan gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 0.05144453048706055, "reserved_gb": 0.134765625, "max_allocated_gb": 4.159046649932861, "gpu_util_pct": "96", "gpu_mem_used_mb": "841", "gpu_mem_total_mb": "12288", "gpu_temp_c": "44", "gpu_power_w": "12.78"}

predict:   0%|          | 0/281 [00:00<?, ?it/s]

2026-08-09 00:58:00 | INFO | Task fde94e460302e7c0_encoder_ablation -> failed
2026-08-09 00:58:00 | ERROR | Task failed: {'kind': 'encoder_ablation', 'fold': 'Ses01F', 'seed': 13}
Traceback (most recent call last):
  File "C:\Users\HaseebWajid\AppData\Local\Temp\ipykernel_19704\2991325871.py", line 91, in execute_plan
    "logmel": run_logmel_ablation(
              ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HaseebWajid\AppData\Local\Temp\ipykernel_19704\3548813907.py", line 19, in run_logmel_ablation
    return run_iemocap_fold(df,fold,seed,tokenizer,feature_extractor,stage="ablations/encoder/logmel_cnn",local_cfg=local)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HaseebWajid\AppData\Local\Temp\ipykernel_19704\3633906516.py", line 170, in run_iemocap_fold
    return run_train_bundle(
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\HaseebWajid\AppData\Local\Temp\ipykernel_19704\3633906516.py", line 122, in run_train_bundle
    result = train_resumable(
             ^^^^^^^^^^^^^^^^
  File "C:\Users\HaseebWajid\AppData\Local\Temp\ipykernel_19704\37259444.py", line 177, in train_resumable
    validation_scores, _ = validation_metrics(
                           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HaseebWajid\AppData\Local\Temp\ipykernel_19704\3571513685.py", line 241, in validation_metrics
    scores = score_prediction_frame(predictions, stats)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HaseebWajid\AppData\Local\Temp\ipykernel_19704\4217115591.py", line 163, in score_prediction_frame
    "regression": regression_metrics(y_continuous, pred_continuous),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HaseebWajid\AppData\Local\Temp\ipykernel_19704\4217115591.py", line 47, in regression_metrics
    "mae": float(mean_absolute_error(y_true, predictions)),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\sklearn\utils\_param_validation.py", line 218, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\sklearn\metrics\_regression.py", line 283, in mean_absolute_error
    _check_reg_targets_with_floating_dtype(
  File "C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\sklearn\metrics\_regression.py", line 208, in _check_reg_targets_with_floating_dtype
    y_type, y_true, y_pred, sample_weight, multioutput = _check_reg_targets(
                                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\sklearn\metrics\_regression.py", line 115, in _check_reg_targets
    y_pred = check_array(y_pred, ensure_2d=False, dtype=dtype)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\sklearn\utils\validation.py", line 1074, in check_array
    _assert_all_finite(
  File "C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\sklearn\utils\validation.py", line 133, in _assert_all_finite
    _assert_all_finite_element_wise(
  File "C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\sklearn\utils\validation.py", line 182, in _assert_all_finite_element_wise
    raise ValueError(msg_err)
ValueError: Input contains NaN.
2026-08-09 00:58:00 | INFO | Task bea8c4a552dc2b16_context -> running
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\transformers\configuration_utils.py:335: UserWarning: Passing `gradient_checkpointing` to a config initialization is deprecated and will be removed in v5 Transformers. Using `model.gradient_checkpointing_enable()` instead, or if you are using the `Trainer` API, pass `gradient_checkpointing=True` in your `TrainingArguments`.
  warnings.warn(
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
2026-08-09 01:09:44 | INFO | Task bea8c4a552dc2b16_context -> complete
2026-08-09 01:09:45 | INFO | Manuscript outputs refreshed: 21 tables, 4 figures
2026-08-09 01:09:45 | INFO | Task 158fe0020464366a_cross -> running
2026-08-09 01:09:45 | INFO | Task 158fe0020464366a_cross -> blocked_missing_msp
2026-08-09 01:09:47 | INFO | Manuscript outputs refreshed: 21 tables, 4 figures
2026-08-09 01:09:47 | INFO | Task 7a725110d6dbcdd0_cross -> running
2026-08-09 01:09:47 | INFO | Task 7a725110d6dbcdd0_cross -> blocked_missing_msp
2026-08-09 01:09:48 | INFO | Manuscript outputs refreshed: 21 tables, 4 figures
2026-08-09 01:09:48 | INFO | Task c63203b695c78ae0_main_fold -> running
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\transformers\configuration_utils.py:335: UserWarning: Passing `gradient_checkpointing` to a config initialization is deprecated and will be removed in v5 Transformers. Using `model.gradient_checkpointing_enable()` instead, or if you are using the `Trainer` API, pass `gradient_checkpointing=True` in your `TrainingArguments`.
  warnings.warn(
2026-08-09 01:09:51 | INFO | Task C:\Users\HaseebWajid\Downloads\runs\dersx_paper_aligned\campaign_01\main\seed_13\Ses01M parameters={'total': 163009451, 'trainable': 69034283, 'frozen': 93975168} scope={'corpus': 'IEMOCAP', 'protocol': 'strict_LOSO', 'heldout_speaker': 'Ses01M', 'seed': 13, 'stage': 'main', 'profile': 'rtx3060_24h'}

epoch 1:   0%|          | 0/2529 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 01:10:30 | INFO | train task=Ses01M epoch=1 batch=100/2529 step=25 loss=3.7357 ce=2.2617 mse=2.9480 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1440858840942383, "reserved_gb": 1.765625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "73", "gpu_mem_used_mb": "2519", "gpu_mem_total_mb": "12288", "gpu_temp_c": "58", "gpu_power_w": "99.40"}
2026-08-09 01:11:04 | INFO | train task=Ses01M epoch=1 batch=200/2529 step=50 loss=2.1903 ce=2.1407 mse=0.0991 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1385564804077148, "reserved_gb": 1.697265625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "50", "gpu_mem_used_mb": "2449", "gpu_mem_total_mb": "12288", "gpu_temp_c": "57", "gpu_power_w": "87.82"}
2026-08-09 01:11:36 | INFO | train task=Ses01M epoch=1 batch=300/2529 step=75 loss=2.6308 ce=2.1631 mse=0.9355 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.138533592224121, "reserved_gb": 1.712890625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "14", "gpu_mem_used_mb": "2464", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "71.41"}
2026-08-09 01:12:07 | INFO | train task=Ses01M epoch=1 batch=400/2529 step=100 loss=1.9020 ce=1.7368 mse=0.3303 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1389241218566895, "reserved_gb": 1.705078125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "43", "gpu_mem_used_mb": "2456", "gpu_mem_total_mb": "12288", "gpu_temp_c": "54", "gpu_power_w": "77.19"}
2026-08-09 01:12:44 | INFO | train task=Ses01M epoch=1 batch=500/2529 step=125 loss=2.6441 ce=1.8736 mse=1.5410 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1389837265014648, "reserved_gb": 1.8125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "19", "gpu_mem_used_mb": "2566", "gpu_mem_total_mb": "12288", "gpu_temp_c": "53", "gpu_power_w": "81.66"}
2026-08-09 01:13:14 | INFO | train task=Ses01M epoch=1 batch=600/2529 step=150 loss=2.2099 ce=1.8233 mse=0.7731 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1389827728271484, "reserved_gb": 1.755859375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "2508", "gpu_mem_total_mb": "12288", "gpu_temp_c": "53", "gpu_power_w": "82.59"}
2026-08-09 01:13:43 | INFO | train task=Ses01M epoch=1 batch=700/2529 step=175 loss=2.4039 ce=2.1779 mse=0.4521 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.139244556427002, "reserved_gb": 1.697265625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "53", "gpu_mem_used_mb": "2447", "gpu_mem_total_mb": "12288", "gpu_temp_c": "53", "gpu_power_w": "71.76"}
2026-08-09 01:14:12 | INFO | train task=Ses01M epoch=1 batch=800/2529 step=200 loss=1.7598 ce=1.6421 mse=0.2354 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1389741897583008, "reserved_gb": 1.728515625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "42", "gpu_mem_used_mb": "2479", "gpu_mem_total_mb": "12288", "gpu_temp_c": "53", "gpu_power_w": "81.44"}
2026-08-09 01:14:46 | INFO | train task=Ses01M epoch=1 batch=900/2529 step=225 loss=3.3895 ce=1.8413 mse=3.0964 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.138744831085205, "reserved_gb": 1.734375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "31", "gpu_mem_used_mb": "2485", "gpu_mem_total_mb": "12288", "gpu_temp_c": "54", "gpu_power_w": "117.61"}
2026-08-09 01:15:15 | INFO | train task=Ses01M epoch=1 batch=1000/2529 step=250 loss=2.3500 ce=1.7562 mse=1.1874 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1389837265014648, "reserved_gb": 1.716796875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "23", "gpu_mem_used_mb": "2467", "gpu_mem_total_mb": "12288", "gpu_temp_c": "53", "gpu_power_w": "77.87"}
2026-08-09 01:15:43 | INFO | train task=Ses01M epoch=1 batch=1100/2529 step=275 loss=1.6393 ce=1.5245 mse=0.2295 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1389288902282715, "reserved_gb": 1.73046875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "37", "gpu_mem_used_mb": "2481", "gpu_mem_total_mb": "12288", "gpu_temp_c": "54", "gpu_power_w": "76.63"}
2026-08-09 01:16:12 | INFO | train task=Ses01M epoch=1 batch=1200/2529 step=300 loss=2.7693 ce=1.9976 mse=1.5434 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1392321586608887, "reserved_gb": 1.708984375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "2459", "gpu_mem_total_mb": "12288", "gpu_temp_c": "53", "gpu_power_w": "75.34"}
2026-08-09 01:16:42 | INFO | train task=Ses01M epoch=1 batch=1300/2529 step=325 loss=1.7524 ce=1.5829 mse=0.3390 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1389517784118652, "reserved_gb": 1.771484375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "60", "gpu_mem_used_mb": "2523", "gpu_mem_total_mb": "12288", "gpu_temp_c": "53", "gpu_power_w": "91.78"}
2026-08-09 01:17:09 | INFO | train task=Ses01M epoch=1 batch=1400/2529 step=350 loss=2.2866 ce=1.5568 mse=1.4596 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.14003324508667, "reserved_gb": 1.71875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "37", "gpu_mem_used_mb": "2469", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "74.26"}
2026-08-09 01:17:34 | INFO | train task=Ses01M epoch=1 batch=1500/2529 step=375 loss=1.3118 ce=1.0172 mse=0.5892 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1390938758850098, "reserved_gb": 1.71875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "2469", "gpu_mem_total_mb": "12288", "gpu_temp_c": "53", "gpu_power_w": "89.14"}
2026-08-09 01:17:58 | INFO | train task=Ses01M epoch=1 batch=1600/2529 step=400 loss=1.2611 ce=0.9015 mse=0.7193 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1386089324951172, "reserved_gb": 1.701171875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "2451", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "72.83"}
2026-08-09 01:18:27 | INFO | train task=Ses01M epoch=1 batch=1700/2529 step=425 loss=1.4351 ce=1.3093 mse=0.2514 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.139009952545166, "reserved_gb": 1.705078125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "31", "gpu_mem_used_mb": "2455", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "78.72"}
2026-08-09 01:18:54 | INFO | train task=Ses01M epoch=1 batch=1800/2529 step=450 loss=1.4615 ce=1.0318 mse=0.8595 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.139528751373291, "reserved_gb": 1.708984375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "45", "gpu_mem_used_mb": "2459", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "77.25"}
2026-08-09 01:19:20 | INFO | train task=Ses01M epoch=1 batch=1900/2529 step=475 loss=0.9915 ce=0.5241 mse=0.9347 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1440868377685547, "reserved_gb": 1.767578125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "35", "gpu_mem_used_mb": "2519", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "74.34"}
2026-08-09 01:19:44 | INFO | train task=Ses01M epoch=1 batch=2000/2529 step=500 loss=1.8305 ce=1.5291 mse=0.6028 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1440858840942383, "reserved_gb": 1.765625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "90", "gpu_mem_used_mb": "2517", "gpu_mem_total_mb": "12288", "gpu_temp_c": "56", "gpu_power_w": "88.32"}
2026-08-09 01:20:11 | INFO | train task=Ses01M epoch=1 batch=2100/2529 step=525 loss=1.0543 ce=1.0018 mse=0.1050 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1393065452575684, "reserved_gb": 1.74609375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "19", "gpu_mem_used_mb": "2497", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "72.00"}
2026-08-09 01:20:36 | INFO | train task=Ses01M epoch=1 batch=2200/2529 step=550 loss=0.6474 ce=0.5610 mse=0.1727 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.139946460723877, "reserved_gb": 1.705078125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "54", "gpu_mem_used_mb": "2455", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "71.46"}
2026-08-09 01:21:00 | INFO | train task=Ses01M epoch=1 batch=2300/2529 step=575 loss=1.8297 ce=1.6016 mse=0.4561 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1387557983398438, "reserved_gb": 1.958984375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "39", "gpu_mem_used_mb": "2715", "gpu_mem_total_mb": "12288", "gpu_temp_c": "53", "gpu_power_w": "101.37"}
2026-08-09 01:21:26 | INFO | train task=Ses01M epoch=1 batch=2400/2529 step=600 loss=1.0643 ce=0.7907 mse=0.5471 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1393375396728516, "reserved_gb": 1.69140625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "16", "gpu_mem_used_mb": "2441", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "64.43"}
2026-08-09 01:21:55 | INFO | train task=Ses01M epoch=1 batch=2500/2529 step=625 loss=1.7775 ce=1.7154 mse=0.1243 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1386194229125977, "reserved_gb": 1.705078125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "19", "gpu_mem_used_mb": "2455", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "69.94"}

predict:   0%|          | 0/281 [00:00<?, ?it/s]

2026-08-09 01:22:47 | INFO | Epoch 01 task=Ses01M train_loss=1.9985 val_macro_f1=0.4554 val_mae=0.5602 epoch_seconds=775.8

epoch 2:   0%|          | 0/2529 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 01:23:06 | INFO | train task=Ses01M epoch=2 batch=68/2529 step=650 loss=1.4713 ce=1.3046 mse=0.3334 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1440858840942383, "reserved_gb": 2.30859375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "3073", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "69.90"}
2026-08-09 01:23:24 | INFO | train task=Ses01M epoch=2 batch=168/2529 step=675 loss=1.4054 ce=1.2004 mse=0.4100 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.138986587524414, "reserved_gb": 1.708984375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "2459", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "67.13"}
2026-08-09 01:23:45 | INFO | train task=Ses01M epoch=2 batch=268/2529 step=700 loss=1.3411 ce=0.9993 mse=0.6837 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1385650634765625, "reserved_gb": 1.818359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "23", "gpu_mem_used_mb": "2571", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "62.03"}
2026-08-09 01:24:09 | INFO | train task=Ses01M epoch=2 batch=368/2529 step=725 loss=2.0517 ce=1.5093 mse=1.0849 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.140172004699707, "reserved_gb": 2.65234375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "57", "gpu_mem_used_mb": "3425", "gpu_mem_total_mb": "12288", "gpu_temp_c": "54", "gpu_power_w": "74.55"}
2026-08-09 01:24:27 | INFO | train task=Ses01M epoch=2 batch=468/2529 step=750 loss=2.0113 ce=1.7710 mse=0.4807 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1399612426757812, "reserved_gb": 1.8515625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "25", "gpu_mem_used_mb": "2605", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "66.52"}
2026-08-09 01:24:47 | INFO | train task=Ses01M epoch=2 batch=568/2529 step=775 loss=0.7893 ce=0.5010 mse=0.5765 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1393332481384277, "reserved_gb": 1.8359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "25", "gpu_mem_used_mb": "2589", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "77.46"}
2026-08-09 01:25:08 | INFO | train task=Ses01M epoch=2 batch=668/2529 step=800 loss=0.8235 ce=0.5433 mse=0.5604 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1390571594238281, "reserved_gb": 1.740234375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "30", "gpu_mem_used_mb": "2491", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "63.03"}
2026-08-09 01:25:31 | INFO | train task=Ses01M epoch=2 batch=768/2529 step=825 loss=1.6770 ce=1.4703 mse=0.4134 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1386213302612305, "reserved_gb": 1.7890625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "37", "gpu_mem_used_mb": "2541", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "66.09"}
2026-08-09 01:25:51 | INFO | train task=Ses01M epoch=2 batch=868/2529 step=850 loss=1.9202 ce=1.6752 mse=0.4899 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1387109756469727, "reserved_gb": 1.69921875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "35", "gpu_mem_used_mb": "2449", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "62.81"}
2026-08-09 01:26:10 | INFO | train task=Ses01M epoch=2 batch=968/2529 step=875 loss=1.7172 ce=1.5841 mse=0.2662 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1386208534240723, "reserved_gb": 1.685546875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "26", "gpu_mem_used_mb": "2435", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "73.98"}
2026-08-09 01:26:31 | INFO | train task=Ses01M epoch=2 batch=1068/2529 step=900 loss=2.3289 ce=1.9463 mse=0.7652 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.138657569885254, "reserved_gb": 1.86328125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "18", "gpu_mem_used_mb": "2617", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "58.82"}
2026-08-09 01:26:54 | INFO | train task=Ses01M epoch=2 batch=1168/2529 step=925 loss=0.8560 ce=0.7231 mse=0.2658 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1391520500183105, "reserved_gb": 1.703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "16", "gpu_mem_used_mb": "2453", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "61.28"}
2026-08-09 01:27:15 | INFO | train task=Ses01M epoch=2 batch=1268/2529 step=950 loss=2.2046 ce=1.5189 mse=1.3715 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1407270431518555, "reserved_gb": 1.73828125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "46", "gpu_mem_used_mb": "2489", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "83.39"}
2026-08-09 01:27:35 | INFO | train task=Ses01M epoch=2 batch=1368/2529 step=975 loss=2.9201 ce=2.7452 mse=0.3499 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1388883590698242, "reserved_gb": 1.748046875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "44", "gpu_mem_used_mb": "2499", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "78.26"}
2026-08-09 01:27:56 | INFO | train task=Ses01M epoch=2 batch=1468/2529 step=1000 loss=0.2903 ce=0.2813 mse=0.0178 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1393065452575684, "reserved_gb": 1.859375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "2613", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "69.17"}
2026-08-09 01:28:20 | INFO | train task=Ses01M epoch=2 batch=1568/2529 step=1025 loss=1.6367 ce=1.0979 mse=1.0775 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1386337280273438, "reserved_gb": 1.71484375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "19", "gpu_mem_used_mb": "2465", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "64.68"}
2026-08-09 01:28:39 | INFO | train task=Ses01M epoch=2 batch=1668/2529 step=1050 loss=2.3858 ce=2.3833 mse=0.0051 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1440858840942383, "reserved_gb": 2.380859375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "19", "gpu_mem_used_mb": "3147", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "75.29"}
2026-08-09 01:29:00 | INFO | train task=Ses01M epoch=2 batch=1768/2529 step=1075 loss=0.6541 ce=0.4605 mse=0.3873 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1388888359069824, "reserved_gb": 1.7734375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "25", "gpu_mem_used_mb": "2525", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "67.05"}
2026-08-09 01:29:23 | INFO | train task=Ses01M epoch=2 batch=1868/2529 step=1100 loss=1.4697 ce=1.0709 mse=0.7976 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1386981010437012, "reserved_gb": 1.6875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "24", "gpu_mem_used_mb": "2437", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "72.87"}
2026-08-09 01:29:46 | INFO | train task=Ses01M epoch=2 batch=1968/2529 step=1125 loss=1.4565 ce=1.1063 mse=0.7003 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.139932632446289, "reserved_gb": 2.083984375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "32", "gpu_mem_used_mb": "2843", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "69.23"}
2026-08-09 01:30:07 | INFO | train task=Ses01M epoch=2 batch=2068/2529 step=1150 loss=0.5604 ce=0.4928 mse=0.1352 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1399545669555664, "reserved_gb": 1.884765625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "40", "gpu_mem_used_mb": "2639", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "68.15"}
2026-08-09 01:30:28 | INFO | train task=Ses01M epoch=2 batch=2168/2529 step=1175 loss=1.0371 ce=0.8625 mse=0.3491 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1389875411987305, "reserved_gb": 1.705078125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "19", "gpu_mem_used_mb": "2455", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "71.61"}
2026-08-09 01:30:49 | INFO | train task=Ses01M epoch=2 batch=2268/2529 step=1200 loss=1.4644 ce=1.2759 mse=0.3771 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.138845443725586, "reserved_gb": 1.833984375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "2587", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "63.38"}
2026-08-09 01:31:14 | INFO | train task=Ses01M epoch=2 batch=2368/2529 step=1225 loss=0.3561 ce=0.2953 mse=0.1216 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.140181064605713, "reserved_gb": 1.86328125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "31", "gpu_mem_used_mb": "2617", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "80.88"}
2026-08-09 01:31:35 | INFO | train task=Ses01M epoch=2 batch=2468/2529 step=1250 loss=0.5604 ce=0.4982 mse=0.1244 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.138744831085205, "reserved_gb": 1.701171875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "2451", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "52.82"}

predict:   0%|          | 0/281 [00:00<?, ?it/s]

2026-08-09 01:32:09 | INFO | Epoch 02 task=Ses01M train_loss=1.4480 val_macro_f1=0.5516 val_mae=0.5487 epoch_seconds=557.7

epoch 3:   0%|          | 0/2529 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 01:32:21 | INFO | train task=Ses01M epoch=3 batch=36/2529 step=1275 loss=1.3964 ce=1.2173 mse=0.3582 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.138814926147461, "reserved_gb": 1.91796875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "2623", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "55.14"}
2026-08-09 01:32:41 | INFO | train task=Ses01M epoch=3 batch=136/2529 step=1300 loss=1.5138 ce=1.2713 mse=0.4851 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.138655662536621, "reserved_gb": 1.859375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "76", "gpu_mem_used_mb": "2563", "gpu_mem_total_mb": "12288", "gpu_temp_c": "55", "gpu_power_w": "92.33"}
2026-08-09 01:33:04 | INFO | train task=Ses01M epoch=3 batch=236/2529 step=1325 loss=1.3032 ce=0.9678 mse=0.6709 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1391429901123047, "reserved_gb": 2.037109375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "37", "gpu_mem_used_mb": "2745", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "66.29"}
2026-08-09 01:33:24 | INFO | train task=Ses01M epoch=3 batch=336/2529 step=1350 loss=1.9891 ce=1.7226 mse=0.5330 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1387100219726562, "reserved_gb": 1.88671875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "14", "gpu_mem_used_mb": "2591", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "70.25"}
2026-08-09 01:33:43 | INFO | train task=Ses01M epoch=3 batch=436/2529 step=1375 loss=0.6619 ce=0.4455 mse=0.4329 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.138554573059082, "reserved_gb": 1.736328125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "45", "gpu_mem_used_mb": "2437", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "81.97"}
2026-08-09 01:34:02 | INFO | train task=Ses01M epoch=3 batch=536/2529 step=1400 loss=0.6150 ce=0.2168 mse=0.7963 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1402578353881836, "reserved_gb": 1.943359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "31", "gpu_mem_used_mb": "2649", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "65.29"}
2026-08-09 01:34:24 | INFO | train task=Ses01M epoch=3 batch=636/2529 step=1425 loss=1.9636 ce=1.8049 mse=0.3176 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1390161514282227, "reserved_gb": 2.763671875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "85", "gpu_mem_used_mb": "3489", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "75.68"}
2026-08-09 01:34:43 | INFO | train task=Ses01M epoch=3 batch=736/2529 step=1450 loss=1.1066 ce=0.9658 mse=0.2817 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1390705108642578, "reserved_gb": 1.7109375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "42", "gpu_mem_used_mb": "2411", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "65.76"}
2026-08-09 01:35:02 | INFO | train task=Ses01M epoch=3 batch=836/2529 step=1475 loss=0.9026 ce=0.8475 mse=0.1101 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1388659477233887, "reserved_gb": 2.1875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "2899", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "70.70"}
2026-08-09 01:35:22 | INFO | train task=Ses01M epoch=3 batch=936/2529 step=1500 loss=0.9187 ce=0.7763 mse=0.2848 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1387596130371094, "reserved_gb": 2.306640625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "32", "gpu_mem_used_mb": "3021", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "72.55"}
2026-08-09 01:35:45 | INFO | train task=Ses01M epoch=3 batch=1036/2529 step=1525 loss=1.3264 ce=0.9772 mse=0.6983 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1387977600097656, "reserved_gb": 1.716796875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "18", "gpu_mem_used_mb": "2417", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "61.38"}
2026-08-09 01:36:05 | INFO | train task=Ses01M epoch=3 batch=1136/2529 step=1550 loss=0.0768 ce=0.0418 mse=0.0699 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1440858840942383, "reserved_gb": 2.265625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "34", "gpu_mem_used_mb": "2979", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "43.64"}
2026-08-09 01:36:24 | INFO | train task=Ses01M epoch=3 batch=1236/2529 step=1575 loss=0.3765 ce=0.2294 mse=0.2942 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.138686180114746, "reserved_gb": 1.7109375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "2411", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "71.08"}
2026-08-09 01:36:43 | INFO | train task=Ses01M epoch=3 batch=1336/2529 step=1600 loss=0.7766 ce=0.2212 mse=1.1108 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1392340660095215, "reserved_gb": 1.7890625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "2491", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "77.56"}
2026-08-09 01:37:05 | INFO | train task=Ses01M epoch=3 batch=1436/2529 step=1625 loss=0.5888 ce=0.5866 mse=0.0044 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.140181064605713, "reserved_gb": 1.705078125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "27", "gpu_mem_used_mb": "2405", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "68.65"}
2026-08-09 01:37:25 | INFO | train task=Ses01M epoch=3 batch=1536/2529 step=1650 loss=0.1744 ce=0.0832 mse=0.1824 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.141951560974121, "reserved_gb": 1.91015625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "14", "gpu_mem_used_mb": "2615", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "41.62"}
2026-08-09 01:37:44 | INFO | train task=Ses01M epoch=3 batch=1636/2529 step=1675 loss=0.3669 ce=0.1923 mse=0.3491 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1397709846496582, "reserved_gb": 1.94921875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "2655", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "81.71"}
2026-08-09 01:38:04 | INFO | train task=Ses01M epoch=3 batch=1736/2529 step=1700 loss=1.0974 ce=0.6680 mse=0.8589 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1404728889465332, "reserved_gb": 1.984375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "33", "gpu_mem_used_mb": "2691", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "58.96"}
2026-08-09 01:38:27 | INFO | train task=Ses01M epoch=3 batch=1836/2529 step=1725 loss=0.7751 ce=0.5432 mse=0.4636 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1386356353759766, "reserved_gb": 1.91796875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "2623", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "69.90"}
2026-08-09 01:38:49 | INFO | train task=Ses01M epoch=3 batch=1936/2529 step=1750 loss=0.8103 ce=0.7348 mse=0.1511 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1393585205078125, "reserved_gb": 1.9609375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "2667", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "74.89"}
2026-08-09 01:39:10 | INFO | train task=Ses01M epoch=3 batch=2036/2529 step=1775 loss=1.8261 ce=1.3662 mse=0.9197 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.139369010925293, "reserved_gb": 1.794921875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "39", "gpu_mem_used_mb": "2497", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "52.17"}
2026-08-09 01:39:31 | INFO | train task=Ses01M epoch=3 batch=2136/2529 step=1800 loss=0.6475 ce=0.5810 mse=0.1331 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1398158073425293, "reserved_gb": 1.708984375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "23", "gpu_mem_used_mb": "2409", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "65.69"}
2026-08-09 01:39:55 | INFO | train task=Ses01M epoch=3 batch=2236/2529 step=1825 loss=0.9905 ce=0.8244 mse=0.3322 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.138789176940918, "reserved_gb": 1.90625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "2611", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "64.76"}
2026-08-09 01:40:16 | INFO | train task=Ses01M epoch=3 batch=2336/2529 step=1850 loss=1.9344 ce=1.9218 mse=0.0251 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1388893127441406, "reserved_gb": 1.701171875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "2401", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "66.69"}
2026-08-09 01:40:40 | INFO | train task=Ses01M epoch=3 batch=2436/2529 step=1875 loss=1.3542 ce=1.0303 mse=0.6477 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.13893461227417, "reserved_gb": 1.73046875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "28", "gpu_mem_used_mb": "2431", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "84.39"}

predict:   0%|          | 0/281 [00:00<?, ?it/s]

2026-08-09 01:41:20 | INFO | Epoch 03 task=Ses01M train_loss=1.2378 val_macro_f1=0.5365 val_mae=0.5286 epoch_seconds=546.2

epoch 4:   0%|          | 0/2529 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 01:41:24 | INFO | train task=Ses01M epoch=4 batch=4/2529 step=1900 loss=0.3835 ce=0.3042 mse=0.1587 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1385860443115234, "reserved_gb": 11.935546875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "10", "gpu_mem_used_mb": "12047", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "32.19"}
2026-08-09 01:41:45 | INFO | train task=Ses01M epoch=4 batch=104/2529 step=1925 loss=0.2216 ce=0.2053 mse=0.0325 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1390161514282227, "reserved_gb": 1.705078125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "2305", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "64.33"}
2026-08-09 01:42:04 | INFO | train task=Ses01M epoch=4 batch=204/2529 step=1950 loss=0.7341 ce=0.6918 mse=0.0846 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1403694152832031, "reserved_gb": 1.87890625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "24", "gpu_mem_used_mb": "2483", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "61.63"}
2026-08-09 01:42:24 | INFO | train task=Ses01M epoch=4 batch=304/2529 step=1975 loss=1.6360 ce=1.2725 mse=0.7270 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1388130187988281, "reserved_gb": 2.185546875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "2797", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "69.15"}
2026-08-09 01:42:43 | INFO | train task=Ses01M epoch=4 batch=404/2529 step=2000 loss=0.9337 ce=0.6664 mse=0.5347 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1417903900146484, "reserved_gb": 2.03515625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "25", "gpu_mem_used_mb": "2643", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "62.67"}
2026-08-09 01:43:06 | INFO | train task=Ses01M epoch=4 batch=504/2529 step=2025 loss=0.8842 ce=0.7080 mse=0.3524 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1387591361999512, "reserved_gb": 2.83203125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "44", "gpu_mem_used_mb": "3459", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "70.40"}
2026-08-09 01:43:25 | INFO | train task=Ses01M epoch=4 batch=604/2529 step=2050 loss=0.3982 ce=0.3767 mse=0.0430 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.139702320098877, "reserved_gb": 1.857421875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "37", "gpu_mem_used_mb": "2461", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "76.91"}
2026-08-09 01:43:45 | INFO | train task=Ses01M epoch=4 batch=704/2529 step=2075 loss=0.8173 ce=0.7841 mse=0.0666 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1392555236816406, "reserved_gb": 1.955078125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "2561", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "63.72"}
2026-08-09 01:44:04 | INFO | train task=Ses01M epoch=4 batch=804/2529 step=2100 loss=0.6323 ce=0.1934 mse=0.8778 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.138777732849121, "reserved_gb": 1.720703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "29", "gpu_mem_used_mb": "2321", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "66.21"}
2026-08-09 01:44:27 | INFO | train task=Ses01M epoch=4 batch=904/2529 step=2125 loss=0.9752 ce=0.7720 mse=0.4064 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1393756866455078, "reserved_gb": 1.9140625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "42", "gpu_mem_used_mb": "2519", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "67.76"}
2026-08-09 01:44:47 | INFO | train task=Ses01M epoch=4 batch=1004/2529 step=2150 loss=1.3828 ce=1.2670 mse=0.2316 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1389551162719727, "reserved_gb": 2.291015625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "52", "gpu_mem_used_mb": "2905", "gpu_mem_total_mb": "12288", "gpu_temp_c": "53", "gpu_power_w": "70.08"}
2026-08-09 01:45:07 | INFO | train task=Ses01M epoch=4 batch=1104/2529 step=2175 loss=0.2203 ce=0.0251 mse=0.3904 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1396007537841797, "reserved_gb": 1.86328125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "36", "gpu_mem_used_mb": "2467", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "67.00"}
2026-08-09 01:45:27 | INFO | train task=Ses01M epoch=4 batch=1204/2529 step=2200 loss=0.7597 ce=0.7182 mse=0.0829 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1392154693603516, "reserved_gb": 1.75390625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "2355", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "60.25"}
2026-08-09 01:45:53 | INFO | train task=Ses01M epoch=4 batch=1304/2529 step=2225 loss=1.2766 ce=0.9514 mse=0.6503 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1399755477905273, "reserved_gb": 1.9609375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "28", "gpu_mem_used_mb": "2567", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "83.57"}
2026-08-09 01:46:14 | INFO | train task=Ses01M epoch=4 batch=1404/2529 step=2250 loss=0.8874 ce=0.7771 mse=0.2206 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1404213905334473, "reserved_gb": 2.041015625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "36", "gpu_mem_used_mb": "2649", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "77.83"}
2026-08-09 01:46:35 | INFO | train task=Ses01M epoch=4 batch=1504/2529 step=2275 loss=0.6232 ce=0.5766 mse=0.0932 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1390109062194824, "reserved_gb": 1.78515625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "27", "gpu_mem_used_mb": "2387", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "65.79"}
2026-08-09 01:46:55 | INFO | train task=Ses01M epoch=4 batch=1604/2529 step=2300 loss=3.2838 ce=3.0404 mse=0.4869 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1386213302612305, "reserved_gb": 1.734375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "18", "gpu_mem_used_mb": "2335", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "85.72"}
2026-08-09 01:47:18 | INFO | train task=Ses01M epoch=4 batch=1704/2529 step=2325 loss=0.1525 ce=0.0998 mse=0.1054 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1402254104614258, "reserved_gb": 1.8359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "2439", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "73.20"}
2026-08-09 01:47:37 | INFO | train task=Ses01M epoch=4 batch=1804/2529 step=2350 loss=1.3399 ce=1.2637 mse=0.1525 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1389122009277344, "reserved_gb": 1.712890625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "2313", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "43.42"}
2026-08-09 01:47:58 | INFO | train task=Ses01M epoch=4 batch=1904/2529 step=2375 loss=1.0969 ce=0.7273 mse=0.7393 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1391477584838867, "reserved_gb": 1.712890625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "28", "gpu_mem_used_mb": "2313", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "75.74"}
2026-08-09 01:48:20 | INFO | train task=Ses01M epoch=4 batch=2004/2529 step=2400 loss=0.4610 ce=0.4019 mse=0.1183 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1389923095703125, "reserved_gb": 2.015625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "41", "gpu_mem_used_mb": "2623", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "75.76"}
2026-08-09 01:48:42 | INFO | train task=Ses01M epoch=4 batch=2104/2529 step=2425 loss=0.7554 ce=0.5363 mse=0.4382 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.138566017150879, "reserved_gb": 2.138671875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "37", "gpu_mem_used_mb": "2749", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "57.90"}
2026-08-09 01:49:02 | INFO | train task=Ses01M epoch=4 batch=2204/2529 step=2450 loss=0.7906 ce=0.1175 mse=1.3462 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1394710540771484, "reserved_gb": 1.90625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "2511", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "67.21"}
2026-08-09 01:49:24 | INFO | train task=Ses01M epoch=4 batch=2304/2529 step=2475 loss=1.3767 ce=1.2214 mse=0.3105 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1386981010437012, "reserved_gb": 1.791015625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "35", "gpu_mem_used_mb": "2393", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "116.94"}
2026-08-09 01:49:46 | INFO | train task=Ses01M epoch=4 batch=2404/2529 step=2500 loss=2.9860 ce=2.6082 mse=0.7557 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.138843059539795, "reserved_gb": 1.712890625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "19", "gpu_mem_used_mb": "2313", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "76.56"}
2026-08-09 01:50:11 | INFO | train task=Ses01M epoch=4 batch=2504/2529 step=2525 loss=0.6055 ce=0.2397 mse=0.7315 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1390151977539062, "reserved_gb": 1.8828125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "28", "gpu_mem_used_mb": "2487", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "50.79"}

predict:   0%|          | 0/281 [00:00<?, ?it/s]

2026-08-09 01:50:35 | INFO | Epoch 04 task=Ses01M train_loss=1.0549 val_macro_f1=0.5230 val_mae=0.5462 epoch_seconds=552.1

predict:   0%|          | 0/255 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)

predict:   0%|          | 0/375 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
2026-08-09 01:52:32 | INFO | Task c63203b695c78ae0_main_fold -> complete
2026-08-09 01:52:34 | INFO | Manuscript outputs refreshed: 21 tables, 4 figures
2026-08-09 01:52:34 | INFO | Task b522cf749704d8fc_main_fold -> running
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\transformers\configuration_utils.py:335: UserWarning: Passing `gradient_checkpointing` to a config initialization is deprecated and will be removed in v5 Transformers. Using `model.gradient_checkpointing_enable()` instead, or if you are using the `Trainer` API, pass `gradient_checkpointing=True` in your `TrainingArguments`.
  warnings.warn(
2026-08-09 01:52:36 | INFO | Task C:\Users\HaseebWajid\Downloads\runs\dersx_paper_aligned\campaign_01\main\seed_13\Ses02F parameters={'total': 163009451, 'trainable': 69034283, 'frozen': 93975168} scope={'corpus': 'IEMOCAP', 'protocol': 'strict_LOSO', 'heldout_speaker': 'Ses02F', 'seed': 13, 'stage': 'main', 'profile': 'rtx3060_24h'}

epoch 1:   0%|          | 0/2468 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 01:52:59 | INFO | train task=Ses02F epoch=1 batch=100/2468 step=25 loss=2.7766 ce=2.1989 mse=1.1554 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.13873291015625, "reserved_gb": 2.037109375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "44", "gpu_mem_used_mb": "2645", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "73.64"}
2026-08-09 01:53:24 | INFO | train task=Ses02F epoch=1 batch=200/2468 step=50 loss=2.2851 ce=2.1058 mse=0.3588 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1391100883483887, "reserved_gb": 1.716796875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "37", "gpu_mem_used_mb": "2317", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "78.62"}
2026-08-09 01:53:48 | INFO | train task=Ses02F epoch=1 batch=300/2468 step=75 loss=2.2298 ce=1.9778 mse=0.5041 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.139009952545166, "reserved_gb": 1.73046875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "2331", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "59.00"}
2026-08-09 01:54:11 | INFO | train task=Ses02F epoch=1 batch=400/2468 step=100 loss=1.8995 ce=1.8510 mse=0.0971 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1392250061035156, "reserved_gb": 1.796875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "2399", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "68.53"}
2026-08-09 01:54:39 | INFO | train task=Ses02F epoch=1 batch=500/2468 step=125 loss=2.2350 ce=1.7129 mse=1.0441 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1390633583068848, "reserved_gb": 1.705078125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "41", "gpu_mem_used_mb": "2305", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "75.77"}
2026-08-09 01:55:03 | INFO | train task=Ses02F epoch=1 batch=600/2468 step=150 loss=1.6916 ce=1.6187 mse=0.1460 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1384925842285156, "reserved_gb": 1.673828125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "38", "gpu_mem_used_mb": "2273", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "78.38"}
2026-08-09 01:55:29 | INFO | train task=Ses02F epoch=1 batch=700/2468 step=175 loss=2.6154 ce=2.0635 mse=1.1038 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1388678550720215, "reserved_gb": 1.947265625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "35", "gpu_mem_used_mb": "2553", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "61.95"}
2026-08-09 01:55:53 | INFO | train task=Ses02F epoch=1 batch=800/2468 step=200 loss=1.4578 ce=1.4026 mse=0.1105 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1411619186401367, "reserved_gb": 1.916015625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "35", "gpu_mem_used_mb": "2521", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "96.49"}
2026-08-09 01:56:20 | INFO | train task=Ses02F epoch=1 batch=900/2468 step=225 loss=2.2560 ce=2.0444 mse=0.4232 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1386404037475586, "reserved_gb": 1.74609375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "2347", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "69.65"}
2026-08-09 01:56:44 | INFO | train task=Ses02F epoch=1 batch=1000/2468 step=250 loss=1.9742 ce=1.5285 mse=0.8914 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1385703086853027, "reserved_gb": 1.986328125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "16", "gpu_mem_used_mb": "2593", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "71.43"}
2026-08-09 01:57:05 | INFO | train task=Ses02F epoch=1 batch=1100/2468 step=275 loss=2.1290 ce=1.5020 mse=1.2542 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.139136791229248, "reserved_gb": 1.75, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "2351", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "68.11"}
2026-08-09 01:57:30 | INFO | train task=Ses02F epoch=1 batch=1200/2468 step=300 loss=1.4338 ce=1.2313 mse=0.4049 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1400136947631836, "reserved_gb": 1.8828125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "46", "gpu_mem_used_mb": "2487", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "44.49"}
2026-08-09 01:57:53 | INFO | train task=Ses02F epoch=1 batch=1300/2468 step=325 loss=1.7678 ce=1.4824 mse=0.5707 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1407866477966309, "reserved_gb": 1.728515625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "18", "gpu_mem_used_mb": "2329", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "63.53"}
2026-08-09 01:58:15 | INFO | train task=Ses02F epoch=1 batch=1400/2468 step=350 loss=1.3658 ce=1.1069 mse=0.5179 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.13954496383667, "reserved_gb": 1.74609375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "27", "gpu_mem_used_mb": "2347", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "70.43"}
2026-08-09 01:58:41 | INFO | train task=Ses02F epoch=1 batch=1500/2468 step=375 loss=1.6729 ce=1.5522 mse=0.2413 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.14031982421875, "reserved_gb": 1.8984375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "24", "gpu_mem_used_mb": "2503", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "84.93"}
2026-08-09 01:59:06 | INFO | train task=Ses02F epoch=1 batch=1600/2468 step=400 loss=0.8580 ce=0.8205 mse=0.0749 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1385688781738281, "reserved_gb": 1.955078125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "25", "gpu_mem_used_mb": "2561", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "62.13"}
2026-08-09 01:59:34 | INFO | train task=Ses02F epoch=1 batch=1700/2468 step=425 loss=1.2705 ce=1.2246 mse=0.0919 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1396074295043945, "reserved_gb": 1.849609375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "2453", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "66.22"}
2026-08-09 01:59:54 | INFO | train task=Ses02F epoch=1 batch=1800/2468 step=450 loss=1.8578 ce=1.8211 mse=0.0736 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.139028549194336, "reserved_gb": 1.69921875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "35", "gpu_mem_used_mb": "2299", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "54.30"}
2026-08-09 02:00:17 | INFO | train task=Ses02F epoch=1 batch=1900/2468 step=475 loss=1.7174 ce=1.6892 mse=0.0563 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1398296356201172, "reserved_gb": 1.693359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "25", "gpu_mem_used_mb": "2293", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "77.06"}
2026-08-09 02:00:40 | INFO | train task=Ses02F epoch=1 batch=2000/2468 step=500 loss=1.9258 ce=1.8398 mse=0.1721 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1394133567810059, "reserved_gb": 1.962890625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "24", "gpu_mem_used_mb": "2569", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "69.93"}
2026-08-09 02:01:07 | INFO | train task=Ses02F epoch=1 batch=2100/2468 step=525 loss=1.7094 ce=1.6725 mse=0.0739 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1387310028076172, "reserved_gb": 1.708984375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "41", "gpu_mem_used_mb": "2309", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "82.32"}
2026-08-09 02:01:32 | INFO | train task=Ses02F epoch=1 batch=2200/2468 step=550 loss=1.3050 ce=1.0471 mse=0.5157 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1387882232666016, "reserved_gb": 1.685546875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "38", "gpu_mem_used_mb": "2285", "gpu_mem_total_mb": "12288", "gpu_temp_c": "53", "gpu_power_w": "72.15"}
2026-08-09 02:01:57 | INFO | train task=Ses02F epoch=1 batch=2300/2468 step=575 loss=1.3698 ce=1.2467 mse=0.2463 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1390690803527832, "reserved_gb": 1.716796875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "2317", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "81.37"}
2026-08-09 02:02:23 | INFO | train task=Ses02F epoch=1 batch=2400/2468 step=600 loss=2.5048 ce=1.8199 mse=1.3697 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1386680603027344, "reserved_gb": 1.712890625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "44", "gpu_mem_used_mb": "2313", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "80.02"}

predict:   0%|          | 0/315 [00:00<?, ?it/s]

2026-08-09 02:03:22 | INFO | Epoch 01 task=Ses02F train_loss=2.0308 val_macro_f1=0.4723 val_mae=0.5287 epoch_seconds=644.7

epoch 2:   0%|          | 0/2468 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 02:03:33 | INFO | train task=Ses02F epoch=2 batch=32/2468 step=625 loss=0.6377 ce=0.4291 mse=0.4172 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1390647888183594, "reserved_gb": 1.90625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "35", "gpu_mem_used_mb": "2511", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "67.62"}
2026-08-09 02:03:53 | INFO | train task=Ses02F epoch=2 batch=132/2468 step=650 loss=1.0164 ce=0.9982 mse=0.0364 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1390633583068848, "reserved_gb": 1.818359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "26", "gpu_mem_used_mb": "2421", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "84.89"}
2026-08-09 02:04:12 | INFO | train task=Ses02F epoch=2 batch=232/2468 step=675 loss=3.1564 ce=2.9310 mse=0.4506 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1440324783325195, "reserved_gb": 2.34765625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "30", "gpu_mem_used_mb": "2963", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "73.89"}
2026-08-09 02:04:33 | INFO | train task=Ses02F epoch=2 batch=332/2468 step=700 loss=0.6330 ce=0.5947 mse=0.0767 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.139575481414795, "reserved_gb": 1.783203125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "48", "gpu_mem_used_mb": "2385", "gpu_mem_total_mb": "12288", "gpu_temp_c": "53", "gpu_power_w": "99.21"}
2026-08-09 02:04:55 | INFO | train task=Ses02F epoch=2 batch=432/2468 step=725 loss=1.4589 ce=1.4237 mse=0.0704 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.138814926147461, "reserved_gb": 1.74609375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "28", "gpu_mem_used_mb": "2347", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "41.93"}
2026-08-09 02:05:14 | INFO | train task=Ses02F epoch=2 batch=532/2468 step=750 loss=1.7865 ce=1.7544 mse=0.0642 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1385765075683594, "reserved_gb": 1.751953125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "16", "gpu_mem_used_mb": "2353", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "73.21"}
2026-08-09 02:05:32 | INFO | train task=Ses02F epoch=2 batch=632/2468 step=775 loss=3.0320 ce=2.4663 mse=1.1314 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1387577056884766, "reserved_gb": 2.08203125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "32", "gpu_mem_used_mb": "2691", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "75.41"}
2026-08-09 02:05:52 | INFO | train task=Ses02F epoch=2 batch=732/2468 step=800 loss=2.3942 ce=2.0063 mse=0.7758 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1397604942321777, "reserved_gb": 1.826171875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "14", "gpu_mem_used_mb": "2429", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "69.15"}
2026-08-09 02:06:13 | INFO | train task=Ses02F epoch=2 batch=832/2468 step=825 loss=1.2600 ce=1.2104 mse=0.0991 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1388311386108398, "reserved_gb": 2.26953125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "11", "gpu_mem_used_mb": "2883", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "62.73"}
2026-08-09 02:06:33 | INFO | train task=Ses02F epoch=2 batch=932/2468 step=850 loss=1.1467 ce=1.0267 mse=0.2401 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1385912895202637, "reserved_gb": 1.9375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "14", "gpu_mem_used_mb": "2543", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "63.23"}
2026-08-09 02:06:53 | INFO | train task=Ses02F epoch=2 batch=1032/2468 step=875 loss=0.7867 ce=0.7707 mse=0.0319 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.138777732849121, "reserved_gb": 1.8125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "26", "gpu_mem_used_mb": "2415", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "98.47"}
2026-08-09 02:07:13 | INFO | train task=Ses02F epoch=2 batch=1132/2468 step=900 loss=0.7148 ce=0.3843 mse=0.6611 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1393423080444336, "reserved_gb": 1.830078125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "56", "gpu_mem_used_mb": "2433", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "75.10"}
2026-08-09 02:07:36 | INFO | train task=Ses02F epoch=2 batch=1232/2468 step=925 loss=1.0128 ce=0.9840 mse=0.0576 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1387815475463867, "reserved_gb": 1.90625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "63", "gpu_mem_used_mb": "2511", "gpu_mem_total_mb": "12288", "gpu_temp_c": "53", "gpu_power_w": "88.43"}
2026-08-09 02:07:57 | INFO | train task=Ses02F epoch=2 batch=1332/2468 step=950 loss=1.2237 ce=1.1594 mse=0.1285 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1387453079223633, "reserved_gb": 1.861328125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "30", "gpu_mem_used_mb": "2465", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "58.47"}
2026-08-09 02:08:17 | INFO | train task=Ses02F epoch=2 batch=1432/2468 step=975 loss=3.5872 ce=3.3941 mse=0.3863 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1390790939331055, "reserved_gb": 1.830078125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "25", "gpu_mem_used_mb": "2433", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "69.40"}
2026-08-09 02:08:36 | INFO | train task=Ses02F epoch=2 batch=1532/2468 step=1000 loss=1.3077 ce=0.1996 mse=2.2161 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1402440071105957, "reserved_gb": 2.02734375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "53", "gpu_mem_used_mb": "2635", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "65.31"}
2026-08-09 02:09:00 | INFO | train task=Ses02F epoch=2 batch=1632/2468 step=1025 loss=0.4626 ce=0.4595 mse=0.0063 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.139603614807129, "reserved_gb": 1.6953125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "46", "gpu_mem_used_mb": "2295", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "53.83"}
2026-08-09 02:09:21 | INFO | train task=Ses02F epoch=2 batch=1732/2468 step=1050 loss=0.5294 ce=0.3057 mse=0.4473 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1393442153930664, "reserved_gb": 1.939453125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "28", "gpu_mem_used_mb": "2607", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "48.82"}
2026-08-09 02:09:41 | INFO | train task=Ses02F epoch=2 batch=1832/2468 step=1075 loss=2.0678 ce=1.6462 mse=0.8432 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1392011642456055, "reserved_gb": 1.81640625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "2485", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "79.72"}
2026-08-09 02:10:02 | INFO | train task=Ses02F epoch=2 batch=1932/2468 step=1100 loss=0.8495 ce=0.3010 mse=1.0970 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1391839981079102, "reserved_gb": 1.90234375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "29", "gpu_mem_used_mb": "2580", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "63.79"}
2026-08-09 02:10:30 | INFO | train task=Ses02F epoch=2 batch=2032/2468 step=1125 loss=1.5516 ce=1.4539 mse=0.1954 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1388254165649414, "reserved_gb": 1.693359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "60", "gpu_mem_used_mb": "2378", "gpu_mem_total_mb": "12288", "gpu_temp_c": "55", "gpu_power_w": "82.18"}
2026-08-09 02:10:50 | INFO | train task=Ses02F epoch=2 batch=2132/2468 step=1150 loss=1.5510 ce=1.3579 mse=0.3863 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.138596534729004, "reserved_gb": 1.7265625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "40", "gpu_mem_used_mb": "2412", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "94.33"}
2026-08-09 02:11:12 | INFO | train task=Ses02F epoch=2 batch=2232/2468 step=1175 loss=1.9728 ce=1.9132 mse=0.1192 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1394729614257812, "reserved_gb": 1.814453125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "24", "gpu_mem_used_mb": "2502", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "54.93"}
2026-08-09 02:11:34 | INFO | train task=Ses02F epoch=2 batch=2332/2468 step=1200 loss=3.5531 ce=3.2627 mse=0.5808 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1407804489135742, "reserved_gb": 1.71875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "2408", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "56.31"}
2026-08-09 02:12:00 | INFO | train task=Ses02F epoch=2 batch=2432/2468 step=1225 loss=1.3296 ce=1.1312 mse=0.3969 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1396880149841309, "reserved_gb": 1.837890625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "28", "gpu_mem_used_mb": "2530", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "77.63"}

predict:   0%|          | 0/315 [00:00<?, ?it/s]

2026-08-09 02:12:28 | INFO | Epoch 02 task=Ses02F train_loss=1.4966 val_macro_f1=0.5143 val_mae=0.4880 epoch_seconds=542.4

epoch 3:   0%|          | 0/2468 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 02:12:46 | INFO | train task=Ses02F epoch=3 batch=64/2468 step=1250 loss=1.8920 ce=1.8627 mse=0.0587 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1393022537231445, "reserved_gb": 1.935546875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "43", "gpu_mem_used_mb": "2603", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "75.76"}
2026-08-09 02:13:06 | INFO | train task=Ses02F epoch=3 batch=164/2468 step=1275 loss=1.3069 ce=0.3771 mse=1.8596 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1393752098083496, "reserved_gb": 1.693359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "2355", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "63.91"}
2026-08-09 02:13:28 | INFO | train task=Ses02F epoch=3 batch=264/2468 step=1300 loss=0.7332 ce=0.4788 mse=0.5088 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1384782791137695, "reserved_gb": 1.6875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "29", "gpu_mem_used_mb": "2349", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "62.70"}
2026-08-09 02:13:50 | INFO | train task=Ses02F epoch=3 batch=364/2468 step=1325 loss=0.2288 ce=0.2179 mse=0.0219 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1392526626586914, "reserved_gb": 1.736328125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "38", "gpu_mem_used_mb": "2399", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "59.19"}
2026-08-09 02:14:10 | INFO | train task=Ses02F epoch=3 batch=464/2468 step=1350 loss=0.7347 ce=0.4043 mse=0.6608 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1394634246826172, "reserved_gb": 1.779296875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "30", "gpu_mem_used_mb": "2443", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "70.44"}
2026-08-09 02:14:28 | INFO | train task=Ses02F epoch=3 batch=564/2468 step=1375 loss=0.7079 ce=0.3527 mse=0.7103 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1386451721191406, "reserved_gb": 2.001953125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "13", "gpu_mem_used_mb": "2687", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "52.50"}
2026-08-09 02:14:49 | INFO | train task=Ses02F epoch=3 batch=664/2468 step=1400 loss=0.5445 ce=0.4260 mse=0.2371 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1396336555480957, "reserved_gb": 1.796875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "2477", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "67.64"}
2026-08-09 02:15:12 | INFO | train task=Ses02F epoch=3 batch=764/2468 step=1425 loss=2.1241 ce=1.7522 mse=0.7438 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.139660358428955, "reserved_gb": 1.95703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "34", "gpu_mem_used_mb": "2641", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "77.87"}
2026-08-09 02:15:32 | INFO | train task=Ses02F epoch=3 batch=864/2468 step=1450 loss=1.2605 ce=1.0447 mse=0.4316 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1390633583068848, "reserved_gb": 2.09765625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "27", "gpu_mem_used_mb": "2785", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "57.79"}
2026-08-09 02:15:50 | INFO | train task=Ses02F epoch=3 batch=964/2468 step=1475 loss=2.9835 ce=2.7613 mse=0.4444 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.139716625213623, "reserved_gb": 2.44140625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "31", "gpu_mem_used_mb": "3137", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "43.62"}
2026-08-09 02:16:10 | INFO | train task=Ses02F epoch=3 batch=1064/2468 step=1500 loss=3.0007 ce=2.2193 mse=1.5628 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1395158767700195, "reserved_gb": 1.8828125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "28", "gpu_mem_used_mb": "2565", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "54.07"}
2026-08-09 02:16:32 | INFO | train task=Ses02F epoch=3 batch=1164/2468 step=1525 loss=2.0216 ce=1.4653 mse=1.1125 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.138594150543213, "reserved_gb": 2.45703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "24", "gpu_mem_used_mb": "3153", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "73.06"}
2026-08-09 02:16:51 | INFO | train task=Ses02F epoch=3 batch=1264/2468 step=1550 loss=0.4014 ce=0.3794 mse=0.0439 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1440858840942383, "reserved_gb": 2.07421875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "49", "gpu_mem_used_mb": "2761", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "70.62"}
2026-08-09 02:17:10 | INFO | train task=Ses02F epoch=3 batch=1364/2468 step=1575 loss=1.2898 ce=0.8762 mse=0.8272 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1397414207458496, "reserved_gb": 2.072265625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "15", "gpu_mem_used_mb": "2784", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "71.95"}
2026-08-09 02:17:31 | INFO | train task=Ses02F epoch=3 batch=1464/2468 step=1600 loss=5.5017 ce=5.2632 mse=0.4770 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.140519142150879, "reserved_gb": 2.123046875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "12", "gpu_mem_used_mb": "2837", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "63.99"}
2026-08-09 02:17:54 | INFO | train task=Ses02F epoch=3 batch=1564/2468 step=1625 loss=0.3590 ce=0.1210 mse=0.4760 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1440858840942383, "reserved_gb": 2.380859375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "53", "gpu_mem_used_mb": "3101", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "64.93"}
2026-08-09 02:18:14 | INFO | train task=Ses02F epoch=3 batch=1664/2468 step=1650 loss=1.6743 ce=1.3538 mse=0.6408 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1389470100402832, "reserved_gb": 1.69140625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "2395", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "64.51"}
2026-08-09 02:18:34 | INFO | train task=Ses02F epoch=3 batch=1764/2468 step=1675 loss=3.1545 ce=2.8379 mse=0.6332 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1388888359069824, "reserved_gb": 1.828125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "31", "gpu_mem_used_mb": "2535", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "68.96"}
2026-08-09 02:18:56 | INFO | train task=Ses02F epoch=3 batch=1864/2468 step=1700 loss=0.8571 ce=0.8380 mse=0.0383 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1394367218017578, "reserved_gb": 1.8984375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "2606", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "93.08"}
2026-08-09 02:19:19 | INFO | train task=Ses02F epoch=3 batch=1964/2468 step=1725 loss=0.4963 ce=0.4820 mse=0.0284 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1390752792358398, "reserved_gb": 1.701171875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "19", "gpu_mem_used_mb": "2410", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "66.32"}
2026-08-09 02:19:40 | INFO | train task=Ses02F epoch=3 batch=2064/2468 step=1750 loss=1.2103 ce=1.0668 mse=0.2870 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1388626098632812, "reserved_gb": 1.71875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "64", "gpu_mem_used_mb": "2428", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "65.89"}
2026-08-09 02:20:01 | INFO | train task=Ses02F epoch=3 batch=2164/2468 step=1775 loss=1.1794 ce=1.0417 mse=0.2754 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1390161514282227, "reserved_gb": 2.068359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "19", "gpu_mem_used_mb": "2782", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "68.38"}
2026-08-09 02:20:23 | INFO | train task=Ses02F epoch=3 batch=2264/2468 step=1800 loss=1.2636 ce=1.1388 mse=0.2497 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.138761043548584, "reserved_gb": 2.001953125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "2714", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "74.50"}
2026-08-09 02:20:47 | INFO | train task=Ses02F epoch=3 batch=2364/2468 step=1825 loss=1.1210 ce=0.5071 mse=1.2279 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1392631530761719, "reserved_gb": 1.734375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "2440", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "72.20"}
2026-08-09 02:21:09 | INFO | train task=Ses02F epoch=3 batch=2464/2468 step=1850 loss=0.9484 ce=0.9385 mse=0.0198 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.138859748840332, "reserved_gb": 1.763671875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "23", "gpu_mem_used_mb": "2470", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "77.00"}

predict:   0%|          | 0/315 [00:00<?, ?it/s]

2026-08-09 02:21:29 | INFO | Epoch 03 task=Ses02F train_loss=1.2709 val_macro_f1=0.5361 val_mae=0.4586 epoch_seconds=535.2

epoch 4:   0%|          | 0/2468 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 02:21:52 | INFO | train task=Ses02F epoch=4 batch=96/2468 step=1875 loss=1.9600 ce=1.5670 mse=0.7860 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1391944885253906, "reserved_gb": 1.720703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "39", "gpu_mem_used_mb": "2293", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "45.08"}
2026-08-09 02:22:12 | INFO | train task=Ses02F epoch=4 batch=196/2468 step=1900 loss=0.6533 ce=0.6426 mse=0.0214 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1389360427856445, "reserved_gb": 1.751953125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "63", "gpu_mem_used_mb": "2330", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "71.07"}
2026-08-09 02:22:34 | INFO | train task=Ses02F epoch=4 batch=296/2468 step=1925 loss=0.5829 ce=0.4531 mse=0.2595 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1391139030456543, "reserved_gb": 1.9140625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "2500", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "67.19"}
2026-08-09 02:22:53 | INFO | train task=Ses02F epoch=4 batch=396/2468 step=1950 loss=2.1534 ce=2.0343 mse=0.2382 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.138814926147461, "reserved_gb": 1.83203125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "18", "gpu_mem_used_mb": "2416", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "72.39"}
2026-08-09 02:23:13 | INFO | train task=Ses02F epoch=4 batch=496/2468 step=1975 loss=0.7140 ce=0.6815 mse=0.0649 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.138641357421875, "reserved_gb": 2.3359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "23", "gpu_mem_used_mb": "2932", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "68.37"}
2026-08-09 02:23:32 | INFO | train task=Ses02F epoch=4 batch=596/2468 step=2000 loss=0.4912 ce=0.1843 mse=0.6138 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.139383316040039, "reserved_gb": 1.740234375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "2322", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "71.30"}
2026-08-09 02:23:55 | INFO | train task=Ses02F epoch=4 batch=696/2468 step=2025 loss=0.8901 ce=0.5946 mse=0.5909 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1386337280273438, "reserved_gb": 1.83984375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "26", "gpu_mem_used_mb": "2424", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "68.94"}
2026-08-09 02:24:14 | INFO | train task=Ses02F epoch=4 batch=796/2468 step=2050 loss=1.9062 ce=1.3832 mse=1.0461 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1386499404907227, "reserved_gb": 1.8984375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "2484", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "66.11"}
2026-08-09 02:24:34 | INFO | train task=Ses02F epoch=4 batch=896/2468 step=2075 loss=1.6078 ce=1.5239 mse=0.1678 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1389789581298828, "reserved_gb": 2.083984375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "2798", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "68.00"}
2026-08-09 02:24:53 | INFO | train task=Ses02F epoch=4 batch=996/2468 step=2100 loss=0.3131 ce=0.2955 mse=0.0351 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1388206481933594, "reserved_gb": 1.685546875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "26", "gpu_mem_used_mb": "2328", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "64.88"}
2026-08-09 02:25:18 | INFO | train task=Ses02F epoch=4 batch=1096/2468 step=2125 loss=0.7642 ce=0.7463 mse=0.0358 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1388421058654785, "reserved_gb": 1.73828125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "24", "gpu_mem_used_mb": "2531", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "73.71"}
2026-08-09 02:25:38 | INFO | train task=Ses02F epoch=4 batch=1196/2468 step=2150 loss=0.8641 ce=0.7764 mse=0.1754 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1398100852966309, "reserved_gb": 1.80078125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "30", "gpu_mem_used_mb": "2466", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "68.87"}
2026-08-09 02:25:58 | INFO | train task=Ses02F epoch=4 batch=1296/2468 step=2175 loss=0.9220 ce=0.5419 mse=0.7602 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1393518447875977, "reserved_gb": 2.025390625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "29", "gpu_mem_used_mb": "2679", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "89.86"}
2026-08-09 02:26:19 | INFO | train task=Ses02F epoch=4 batch=1396/2468 step=2200 loss=2.2138 ce=1.7836 mse=0.8604 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1391019821166992, "reserved_gb": 1.6484375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "43", "gpu_mem_used_mb": "2294", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "53.73"}
2026-08-09 02:26:42 | INFO | train task=Ses02F epoch=4 batch=1496/2468 step=2225 loss=1.0984 ce=0.7317 mse=0.7334 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1390414237976074, "reserved_gb": 1.75, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "33", "gpu_mem_used_mb": "2488", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "69.47"}
2026-08-09 02:27:02 | INFO | train task=Ses02F epoch=4 batch=1596/2468 step=2250 loss=1.4991 ce=1.3953 mse=0.2076 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.139129638671875, "reserved_gb": 1.8515625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "31", "gpu_mem_used_mb": "2528", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "93.39"}
2026-08-09 02:27:22 | INFO | train task=Ses02F epoch=4 batch=1696/2468 step=2275 loss=4.4129 ce=4.0036 mse=0.8186 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.140519142150879, "reserved_gb": 1.9765625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "37", "gpu_mem_used_mb": "2656", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "95.72"}
2026-08-09 02:27:41 | INFO | train task=Ses02F epoch=4 batch=1796/2468 step=2300 loss=0.3168 ce=0.3033 mse=0.0271 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1440858840942383, "reserved_gb": 2.0859375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "43", "gpu_mem_used_mb": "2768", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "69.64"}
2026-08-09 02:28:05 | INFO | train task=Ses02F epoch=4 batch=1896/2468 step=2325 loss=1.5924 ce=1.2621 mse=0.6606 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1387338638305664, "reserved_gb": 1.7109375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "19", "gpu_mem_used_mb": "2384", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "97.57"}
2026-08-09 02:28:25 | INFO | train task=Ses02F epoch=4 batch=1996/2468 step=2350 loss=1.4406 ce=1.0730 mse=0.7351 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1401147842407227, "reserved_gb": 1.876953125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "31", "gpu_mem_used_mb": "2554", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "83.83"}
2026-08-09 02:28:45 | INFO | train task=Ses02F epoch=4 batch=2096/2468 step=2375 loss=0.2067 ce=0.1769 mse=0.0596 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.139521598815918, "reserved_gb": 2.017578125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "28", "gpu_mem_used_mb": "2698", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "61.48"}
2026-08-09 02:29:05 | INFO | train task=Ses02F epoch=4 batch=2196/2468 step=2400 loss=0.2317 ce=0.0891 mse=0.2853 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1395773887634277, "reserved_gb": 1.732421875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "25", "gpu_mem_used_mb": "2406", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "73.00"}
2026-08-09 02:29:29 | INFO | train task=Ses02F epoch=4 batch=2296/2468 step=2425 loss=0.3726 ce=0.2988 mse=0.1476 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.139204502105713, "reserved_gb": 1.99609375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "2676", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "65.45"}
2026-08-09 02:29:51 | INFO | train task=Ses02F epoch=4 batch=2396/2468 step=2450 loss=0.8676 ce=0.5815 mse=0.5723 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1388440132141113, "reserved_gb": 1.693359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "2430", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "67.86"}

predict:   0%|          | 0/315 [00:00<?, ?it/s]

2026-08-09 02:30:26 | INFO | Epoch 04 task=Ses02F train_loss=1.1108 val_macro_f1=0.4863 val_mae=0.4795 epoch_seconds=532.0

epoch 5:   0%|          | 0/2468 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 02:30:34 | INFO | train task=Ses02F epoch=5 batch=28/2468 step=2475 loss=0.9175 ce=0.6916 mse=0.4518 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1428842544555664, "reserved_gb": 2.318359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "2758", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "55.93"}
2026-08-09 02:30:52 | INFO | train task=Ses02F epoch=5 batch=128/2468 step=2500 loss=0.8751 ce=0.7890 mse=0.1723 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.139052391052246, "reserved_gb": 1.75390625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "2248", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "58.10"}
2026-08-09 02:31:15 | INFO | train task=Ses02F epoch=5 batch=228/2468 step=2525 loss=0.8296 ce=0.7902 mse=0.0788 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.13887357711792, "reserved_gb": 2.03515625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "30", "gpu_mem_used_mb": "2515", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "51.94"}
2026-08-09 02:31:34 | INFO | train task=Ses02F epoch=5 batch=328/2468 step=2550 loss=0.6482 ce=0.6440 mse=0.0082 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1390810012817383, "reserved_gb": 1.806640625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "25", "gpu_mem_used_mb": "2386", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "54.94"}
2026-08-09 02:31:53 | INFO | train task=Ses02F epoch=5 batch=428/2468 step=2575 loss=0.4394 ce=0.3792 mse=0.1203 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1391410827636719, "reserved_gb": 2.033203125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "2555", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "68.78"}
2026-08-09 02:32:12 | INFO | train task=Ses02F epoch=5 batch=528/2468 step=2600 loss=2.5146 ce=2.4026 mse=0.2240 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1387925148010254, "reserved_gb": 1.921875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "39", "gpu_mem_used_mb": "2441", "gpu_mem_total_mb": "12288", "gpu_temp_c": "54", "gpu_power_w": "70.86"}
2026-08-09 02:32:34 | INFO | train task=Ses02F epoch=5 batch=628/2468 step=2625 loss=1.0644 ce=0.5677 mse=0.9934 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1386709213256836, "reserved_gb": 1.6953125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "23", "gpu_mem_used_mb": "2251", "gpu_mem_total_mb": "12288", "gpu_temp_c": "53", "gpu_power_w": "56.77"}
2026-08-09 02:32:54 | INFO | train task=Ses02F epoch=5 batch=728/2468 step=2650 loss=0.3206 ce=0.3073 mse=0.0265 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1389875411987305, "reserved_gb": 1.97265625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "32", "gpu_mem_used_mb": "2535", "gpu_mem_total_mb": "12288", "gpu_temp_c": "56", "gpu_power_w": "69.39"}
2026-08-09 02:33:13 | INFO | train task=Ses02F epoch=5 batch=828/2468 step=2675 loss=0.7152 ce=0.5835 mse=0.2636 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1406426429748535, "reserved_gb": 1.888671875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "43", "gpu_mem_used_mb": "2449", "gpu_mem_total_mb": "12288", "gpu_temp_c": "56", "gpu_power_w": "53.27"}
2026-08-09 02:33:32 | INFO | train task=Ses02F epoch=5 batch=928/2468 step=2700 loss=0.8138 ce=0.6516 mse=0.3244 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1393203735351562, "reserved_gb": 1.75390625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "28", "gpu_mem_used_mb": "2311", "gpu_mem_total_mb": "12288", "gpu_temp_c": "54", "gpu_power_w": "68.12"}
2026-08-09 02:33:54 | INFO | train task=Ses02F epoch=5 batch=1028/2468 step=2725 loss=0.3986 ce=0.2205 mse=0.3564 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1390247344970703, "reserved_gb": 2.306640625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "18", "gpu_mem_used_mb": "2877", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "63.94"}
2026-08-09 02:34:12 | INFO | train task=Ses02F epoch=5 batch=1128/2468 step=2750 loss=0.5329 ce=0.2875 mse=0.4908 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1392288208007812, "reserved_gb": 2.001953125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "27", "gpu_mem_used_mb": "2565", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "61.90"}
2026-08-09 02:34:30 | INFO | train task=Ses02F epoch=5 batch=1228/2468 step=2775 loss=2.1779 ce=2.0986 mse=0.1586 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1387338638305664, "reserved_gb": 2.0390625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "55", "gpu_mem_used_mb": "2603", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "56.26"}
2026-08-09 02:34:50 | INFO | train task=Ses02F epoch=5 batch=1328/2468 step=2800 loss=4.3258 ce=2.7384 mse=3.1749 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1386771202087402, "reserved_gb": 2.03515625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "2599", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "66.84"}
2026-08-09 02:35:13 | INFO | train task=Ses02F epoch=5 batch=1428/2468 step=2825 loss=0.3175 ce=0.0613 mse=0.5123 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.146158218383789, "reserved_gb": 2.296875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "69", "gpu_mem_used_mb": "2867", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "78.82"}
2026-08-09 02:35:34 | INFO | train task=Ses02F epoch=5 batch=1528/2468 step=2850 loss=0.5320 ce=0.5200 mse=0.0241 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1388459205627441, "reserved_gb": 1.703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "19", "gpu_mem_used_mb": "2259", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "65.58"}
2026-08-09 02:35:54 | INFO | train task=Ses02F epoch=5 batch=1628/2468 step=2875 loss=0.1931 ce=0.1667 mse=0.0528 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1392526626586914, "reserved_gb": 2.306640625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "57", "gpu_mem_used_mb": "2877", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "75.46"}
2026-08-09 02:36:14 | INFO | train task=Ses02F epoch=5 batch=1728/2468 step=2900 loss=0.5948 ce=0.4157 mse=0.3582 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1398844718933105, "reserved_gb": 2.103515625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "16", "gpu_mem_used_mb": "2669", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "60.27"}
2026-08-09 02:36:37 | INFO | train task=Ses02F epoch=5 batch=1828/2468 step=2925 loss=0.2449 ce=0.2336 mse=0.0226 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1390981674194336, "reserved_gb": 1.701171875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "47", "gpu_mem_used_mb": "2257", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "66.08"}
2026-08-09 02:36:58 | INFO | train task=Ses02F epoch=5 batch=1928/2468 step=2950 loss=0.5320 ce=0.5121 mse=0.0399 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1391892433166504, "reserved_gb": 2.595703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "54", "gpu_mem_used_mb": "3173", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "69.78"}
2026-08-09 02:37:17 | INFO | train task=Ses02F epoch=5 batch=2028/2468 step=2975 loss=0.5841 ce=0.2307 mse=0.7069 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1394386291503906, "reserved_gb": 2.0546875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "41", "gpu_mem_used_mb": "2619", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "64.89"}
2026-08-09 02:37:39 | INFO | train task=Ses02F epoch=5 batch=2128/2468 step=3000 loss=1.1375 ce=0.9413 mse=0.3924 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1386466026306152, "reserved_gb": 2.20703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "31", "gpu_mem_used_mb": "2775", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "67.80"}
2026-08-09 02:38:04 | INFO | train task=Ses02F epoch=5 batch=2228/2468 step=3025 loss=1.0530 ce=0.2983 mse=1.5095 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1400604248046875, "reserved_gb": 2.0625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "47", "gpu_mem_used_mb": "2627", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "71.28"}
2026-08-09 02:38:24 | INFO | train task=Ses02F epoch=5 batch=2328/2468 step=3050 loss=0.5294 ce=0.5155 mse=0.0276 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1429662704467773, "reserved_gb": 1.744140625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "41", "gpu_mem_used_mb": "2301", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "71.97"}
2026-08-09 02:38:44 | INFO | train task=Ses02F epoch=5 batch=2428/2468 step=3075 loss=0.6885 ce=0.5554 mse=0.2662 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1395511627197266, "reserved_gb": 1.708984375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "40", "gpu_mem_used_mb": "2265", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "74.22"}

predict:   0%|          | 0/315 [00:00<?, ?it/s]

2026-08-09 02:39:13 | INFO | Epoch 05 task=Ses02F train_loss=0.9771 val_macro_f1=0.5010 val_mae=0.4924 epoch_seconds=524.8

predict:   0%|          | 0/296 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)

predict:   0%|          | 0/330 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
2026-08-09 02:40:46 | INFO | Task b522cf749704d8fc_main_fold -> complete
2026-08-09 02:40:48 | INFO | Manuscript outputs refreshed: 21 tables, 4 figures
2026-08-09 02:40:48 | INFO | Task 523a04de7af1f0cf_main_fold -> running
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\transformers\configuration_utils.py:335: UserWarning: Passing `gradient_checkpointing` to a config initialization is deprecated and will be removed in v5 Transformers. Using `model.gradient_checkpointing_enable()` instead, or if you are using the `Trainer` API, pass `gradient_checkpointing=True` in your `TrainingArguments`.
  warnings.warn(
2026-08-09 02:40:50 | INFO | Task C:\Users\HaseebWajid\Downloads\runs\dersx_paper_aligned\campaign_01\main\seed_13\Ses02M parameters={'total': 163009451, 'trainable': 69034283, 'frozen': 93975168} scope={'corpus': 'IEMOCAP', 'protocol': 'strict_LOSO', 'heldout_speaker': 'Ses02M', 'seed': 13, 'stage': 'main', 'profile': 'rtx3060_24h'}

epoch 1:   0%|          | 0/2468 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 02:41:11 | INFO | train task=Ses02M epoch=1 batch=100/2468 step=25 loss=2.7035 ce=2.1837 mse=1.0397 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1403350830078125, "reserved_gb": 1.68359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "57", "gpu_mem_used_mb": "2239", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "78.68"}
2026-08-09 02:41:34 | INFO | train task=Ses02M epoch=1 batch=200/2468 step=50 loss=2.2320 ce=2.0103 mse=0.4433 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1407122611999512, "reserved_gb": 1.7109375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "41", "gpu_mem_used_mb": "2268", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "72.94"}
2026-08-09 02:41:55 | INFO | train task=Ses02M epoch=1 batch=300/2468 step=75 loss=2.3254 ce=1.9536 mse=0.7437 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1406121253967285, "reserved_gb": 1.7109375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "35", "gpu_mem_used_mb": "2276", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "68.35"}
2026-08-09 02:42:16 | INFO | train task=Ses02M epoch=1 batch=400/2468 step=100 loss=2.0714 ce=1.9886 mse=0.1656 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1408271789550781, "reserved_gb": 1.732421875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "18", "gpu_mem_used_mb": "2298", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "67.19"}
2026-08-09 02:42:41 | INFO | train task=Ses02M epoch=1 batch=500/2468 step=125 loss=2.2534 ce=1.9688 mse=0.5693 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1406655311584473, "reserved_gb": 1.701171875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "2266", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "70.22"}
2026-08-09 02:43:02 | INFO | train task=Ses02M epoch=1 batch=600/2468 step=150 loss=1.9078 ce=1.8612 mse=0.0931 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1400947570800781, "reserved_gb": 1.6875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "41", "gpu_mem_used_mb": "2252", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "72.95"}
2026-08-09 02:43:22 | INFO | train task=Ses02M epoch=1 batch=700/2468 step=175 loss=2.2295 ce=1.7944 mse=0.8701 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.140470027923584, "reserved_gb": 1.888671875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "38", "gpu_mem_used_mb": "2458", "gpu_mem_total_mb": "12288", "gpu_temp_c": "44", "gpu_power_w": "56.68"}
2026-08-09 02:43:44 | INFO | train task=Ses02M epoch=1 batch=800/2468 step=200 loss=1.5488 ce=1.5311 mse=0.0353 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1428613662719727, "reserved_gb": 1.73828125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "26", "gpu_mem_used_mb": "2304", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "75.46"}
2026-08-09 02:44:09 | INFO | train task=Ses02M epoch=1 batch=900/2468 step=225 loss=2.0634 ce=1.7470 mse=0.6328 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.140242576599121, "reserved_gb": 1.705078125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "16", "gpu_mem_used_mb": "2270", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "63.56"}
2026-08-09 02:44:32 | INFO | train task=Ses02M epoch=1 batch=1000/2468 step=250 loss=2.2808 ce=1.6259 mse=1.3098 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1401724815368652, "reserved_gb": 1.939453125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "18", "gpu_mem_used_mb": "2510", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "64.72"}
2026-08-09 02:44:54 | INFO | train task=Ses02M epoch=1 batch=1100/2468 step=275 loss=1.7157 ce=1.3989 mse=0.6334 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1407389640808105, "reserved_gb": 1.69921875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "27", "gpu_mem_used_mb": "2264", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "67.46"}
2026-08-09 02:45:15 | INFO | train task=Ses02M epoch=1 batch=1200/2468 step=300 loss=1.2557 ce=1.1695 mse=0.1724 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.141615867614746, "reserved_gb": 1.89453125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "39", "gpu_mem_used_mb": "2464", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "45.65"}
2026-08-09 02:45:39 | INFO | train task=Ses02M epoch=1 batch=1300/2468 step=325 loss=1.8450 ce=1.4380 mse=0.8140 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1423888206481934, "reserved_gb": 1.736328125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "2302", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "70.69"}
2026-08-09 02:46:01 | INFO | train task=Ses02M epoch=1 batch=1400/2468 step=350 loss=1.3123 ce=1.0575 mse=0.5096 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1411471366882324, "reserved_gb": 1.73046875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "25", "gpu_mem_used_mb": "2296", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "78.14"}
2026-08-09 02:46:23 | INFO | train task=Ses02M epoch=1 batch=1500/2468 step=375 loss=2.1044 ce=1.9736 mse=0.2615 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1419219970703125, "reserved_gb": 1.796875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "59", "gpu_mem_used_mb": "2364", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "76.55"}
2026-08-09 02:46:47 | INFO | train task=Ses02M epoch=1 batch=1600/2468 step=400 loss=0.6365 ce=0.6335 mse=0.0059 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1401710510253906, "reserved_gb": 1.75, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "14", "gpu_mem_used_mb": "2316", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "60.45"}
2026-08-09 02:47:14 | INFO | train task=Ses02M epoch=1 batch=1700/2468 step=425 loss=1.6621 ce=1.5264 mse=0.2716 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.141209602355957, "reserved_gb": 1.8515625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "26", "gpu_mem_used_mb": "2420", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "67.62"}
2026-08-09 02:47:35 | INFO | train task=Ses02M epoch=1 batch=1800/2468 step=450 loss=1.6552 ce=1.6375 mse=0.0354 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1406307220458984, "reserved_gb": 1.693359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "23", "gpu_mem_used_mb": "2258", "gpu_mem_total_mb": "12288", "gpu_temp_c": "44", "gpu_power_w": "48.23"}
2026-08-09 02:47:58 | INFO | train task=Ses02M epoch=1 batch=1900/2468 step=475 loss=1.6773 ce=1.6398 mse=0.0751 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1414318084716797, "reserved_gb": 1.693359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "35", "gpu_mem_used_mb": "2258", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "67.14"}
2026-08-09 02:48:22 | INFO | train task=Ses02M epoch=1 batch=2000/2468 step=500 loss=1.8119 ce=1.7552 mse=0.1134 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1410155296325684, "reserved_gb": 1.787109375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "25", "gpu_mem_used_mb": "2354", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "71.18"}
2026-08-09 02:48:48 | INFO | train task=Ses02M epoch=1 batch=2100/2468 step=525 loss=1.9772 ce=1.9500 mse=0.0544 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1403331756591797, "reserved_gb": 1.703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "26", "gpu_mem_used_mb": "2268", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "83.86"}
2026-08-09 02:49:13 | INFO | train task=Ses02M epoch=1 batch=2200/2468 step=550 loss=1.2791 ce=1.0177 mse=0.5228 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.140390396118164, "reserved_gb": 1.693359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "35", "gpu_mem_used_mb": "2258", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "73.38"}
2026-08-09 02:49:37 | INFO | train task=Ses02M epoch=1 batch=2300/2468 step=575 loss=1.3393 ce=1.2452 mse=0.1882 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1406712532043457, "reserved_gb": 1.716796875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "18", "gpu_mem_used_mb": "2282", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "94.37"}
2026-08-09 02:50:02 | INFO | train task=Ses02M epoch=1 batch=2400/2468 step=600 loss=2.3466 ce=1.6698 mse=1.3536 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1402702331542969, "reserved_gb": 1.705078125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "2269", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "69.34"}

predict:   0%|          | 0/315 [00:00<?, ?it/s]

2026-08-09 02:51:05 | INFO | Epoch 01 task=Ses02M train_loss=2.0378 val_macro_f1=0.4585 val_mae=0.5428 epoch_seconds=614.3

epoch 2:   0%|          | 0/2468 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 02:51:17 | INFO | train task=Ses02M epoch=2 batch=32/2468 step=625 loss=0.6364 ce=0.4063 mse=0.4602 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1406669616699219, "reserved_gb": 1.90625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "13", "gpu_mem_used_mb": "2475", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "66.79"}
2026-08-09 02:51:42 | INFO | train task=Ses02M epoch=2 batch=132/2468 step=650 loss=1.0158 ce=1.0034 mse=0.0249 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1406655311584473, "reserved_gb": 1.828125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "2395", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "69.44"}
2026-08-09 02:52:08 | INFO | train task=Ses02M epoch=2 batch=232/2468 step=675 loss=2.8497 ce=2.6757 mse=0.3479 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1456880569458008, "reserved_gb": 2.330078125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "31", "gpu_mem_used_mb": "2908", "gpu_mem_total_mb": "12288", "gpu_temp_c": "44", "gpu_power_w": "43.92"}
2026-08-09 02:52:32 | INFO | train task=Ses02M epoch=2 batch=332/2468 step=700 loss=0.6616 ce=0.6552 mse=0.0128 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1411776542663574, "reserved_gb": 1.86328125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "2435", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "74.94"}
2026-08-09 02:53:01 | INFO | train task=Ses02M epoch=2 batch=432/2468 step=725 loss=1.5392 ce=1.5049 mse=0.0687 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1404170989990234, "reserved_gb": 1.775390625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "0", "gpu_mem_used_mb": "2345", "gpu_mem_total_mb": "12288", "gpu_temp_c": "41", "gpu_power_w": "37.62"}
2026-08-09 02:53:27 | INFO | train task=Ses02M epoch=2 batch=532/2468 step=750 loss=2.0214 ce=1.9668 mse=0.1091 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1401786804199219, "reserved_gb": 1.74609375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "2315", "gpu_mem_total_mb": "12288", "gpu_temp_c": "43", "gpu_power_w": "67.44"}
2026-08-09 02:53:53 | INFO | train task=Ses02M epoch=2 batch=632/2468 step=775 loss=2.6055 ce=1.9693 mse=1.2725 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.140359878540039, "reserved_gb": 2.0703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "16", "gpu_mem_used_mb": "2647", "gpu_mem_total_mb": "12288", "gpu_temp_c": "43", "gpu_power_w": "58.26"}
2026-08-09 02:54:19 | INFO | train task=Ses02M epoch=2 batch=732/2468 step=800 loss=2.0167 ce=1.8414 mse=0.3506 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1413626670837402, "reserved_gb": 1.8125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "46", "gpu_mem_used_mb": "2383", "gpu_mem_total_mb": "12288", "gpu_temp_c": "41", "gpu_power_w": "44.81"}
2026-08-09 02:54:46 | INFO | train task=Ses02M epoch=2 batch=832/2468 step=825 loss=1.5521 ce=1.5107 mse=0.0827 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1404333114624023, "reserved_gb": 2.26953125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "31", "gpu_mem_used_mb": "2851", "gpu_mem_total_mb": "12288", "gpu_temp_c": "42", "gpu_power_w": "36.99"}
2026-08-09 02:55:12 | INFO | train task=Ses02M epoch=2 batch=932/2468 step=850 loss=0.7700 ce=0.7438 mse=0.0524 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1401934623718262, "reserved_gb": 1.9375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "13", "gpu_mem_used_mb": "2511", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "37.17"}
2026-08-09 02:55:39 | INFO | train task=Ses02M epoch=2 batch=1032/2468 step=875 loss=0.8175 ce=0.7808 mse=0.0735 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1403799057006836, "reserved_gb": 1.80859375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "68", "gpu_mem_used_mb": "2379", "gpu_mem_total_mb": "12288", "gpu_temp_c": "54", "gpu_power_w": "95.86"}
2026-08-09 02:56:04 | INFO | train task=Ses02M epoch=2 batch=1132/2468 step=900 loss=0.8275 ce=0.4361 mse=0.7827 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.140944480895996, "reserved_gb": 1.830078125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "68", "gpu_mem_used_mb": "2401", "gpu_mem_total_mb": "12288", "gpu_temp_c": "54", "gpu_power_w": "72.46"}
2026-08-09 02:56:34 | INFO | train task=Ses02M epoch=2 batch=1232/2468 step=925 loss=0.6353 ce=0.5843 mse=0.1020 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1403837203979492, "reserved_gb": 1.8984375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "26", "gpu_mem_used_mb": "2471", "gpu_mem_total_mb": "12288", "gpu_temp_c": "55", "gpu_power_w": "83.69"}
2026-08-09 02:57:00 | INFO | train task=Ses02M epoch=2 batch=1332/2468 step=950 loss=1.1800 ce=1.0518 mse=0.2564 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1403474807739258, "reserved_gb": 1.85546875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "19", "gpu_mem_used_mb": "2427", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "39.62"}
2026-08-09 02:57:24 | INFO | train task=Ses02M epoch=2 batch=1432/2468 step=975 loss=3.0187 ce=2.8199 mse=0.3976 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.140681266784668, "reserved_gb": 1.830078125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "24", "gpu_mem_used_mb": "2401", "gpu_mem_total_mb": "12288", "gpu_temp_c": "55", "gpu_power_w": "61.53"}
2026-08-09 02:57:48 | INFO | train task=Ses02M epoch=2 batch=1532/2468 step=1000 loss=1.2698 ce=0.1846 mse=2.1704 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1418461799621582, "reserved_gb": 2.107421875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "69", "gpu_mem_used_mb": "2685", "gpu_mem_total_mb": "12288", "gpu_temp_c": "54", "gpu_power_w": "43.34"}
2026-08-09 02:58:17 | INFO | train task=Ses02M epoch=2 batch=1632/2468 step=1025 loss=0.5679 ce=0.5632 mse=0.0094 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1412057876586914, "reserved_gb": 1.7109375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "34", "gpu_mem_used_mb": "2279", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "45.30"}
2026-08-09 02:58:42 | INFO | train task=Ses02M epoch=2 batch=1732/2468 step=1050 loss=0.7098 ce=0.4936 mse=0.4325 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.140946388244629, "reserved_gb": 1.94140625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "27", "gpu_mem_used_mb": "2515", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "40.59"}
2026-08-09 02:59:07 | INFO | train task=Ses02M epoch=2 batch=1832/2468 step=1075 loss=1.4890 ce=1.0514 mse=0.8752 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.140803337097168, "reserved_gb": 1.806640625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "2377", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "77.82"}
2026-08-09 02:59:34 | INFO | train task=Ses02M epoch=2 batch=1932/2468 step=1100 loss=0.8448 ce=0.3881 mse=0.9135 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1407861709594727, "reserved_gb": 1.89453125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "19", "gpu_mem_used_mb": "2467", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "58.06"}
2026-08-09 03:00:06 | INFO | train task=Ses02M epoch=2 batch=2032/2468 step=1125 loss=1.8701 ce=1.8140 mse=0.1123 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.140427589416504, "reserved_gb": 1.6953125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "2262", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "78.33"}
2026-08-09 03:00:32 | INFO | train task=Ses02M epoch=2 batch=2132/2468 step=1150 loss=1.2274 ce=1.0010 mse=0.4528 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1401987075805664, "reserved_gb": 1.73828125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "2308", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "82.10"}
2026-08-09 03:00:57 | INFO | train task=Ses02M epoch=2 batch=2232/2468 step=1175 loss=1.8076 ce=1.7307 mse=0.1537 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1410751342773438, "reserved_gb": 1.78125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "25", "gpu_mem_used_mb": "2352", "gpu_mem_total_mb": "12288", "gpu_temp_c": "43", "gpu_power_w": "48.79"}
2026-08-09 03:01:24 | INFO | train task=Ses02M epoch=2 batch=2332/2468 step=1200 loss=3.9737 ce=3.5117 mse=0.9239 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1423826217651367, "reserved_gb": 1.7265625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "18", "gpu_mem_used_mb": "2296", "gpu_mem_total_mb": "12288", "gpu_temp_c": "44", "gpu_power_w": "49.80"}
2026-08-09 03:01:55 | INFO | train task=Ses02M epoch=2 batch=2432/2468 step=1225 loss=1.0341 ce=0.8110 mse=0.4462 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1412901878356934, "reserved_gb": 1.84375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "39", "gpu_mem_used_mb": "2416", "gpu_mem_total_mb": "12288", "gpu_temp_c": "44", "gpu_power_w": "69.90"}

predict:   0%|          | 0/315 [00:00<?, ?it/s]

2026-08-09 03:02:47 | INFO | Epoch 02 task=Ses02M train_loss=1.5040 val_macro_f1=0.5017 val_mae=0.5074 epoch_seconds=697.1

epoch 3:   0%|          | 0/2468 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 03:03:04 | INFO | train task=Ses02M epoch=3 batch=64/2468 step=1250 loss=1.8011 ce=1.7135 mse=0.1752 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.140904426574707, "reserved_gb": 1.9453125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "23", "gpu_mem_used_mb": "2439", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "73.47"}
2026-08-09 03:03:24 | INFO | train task=Ses02M epoch=3 batch=164/2468 step=1275 loss=1.3650 ce=0.4906 mse=1.7488 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.140977382659912, "reserved_gb": 1.708984375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "40", "gpu_mem_used_mb": "2197", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "67.24"}
2026-08-09 03:03:45 | INFO | train task=Ses02M epoch=3 batch=264/2468 step=1300 loss=0.5839 ce=0.3929 mse=0.3818 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.140080451965332, "reserved_gb": 1.6796875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "2167", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "58.56"}
2026-08-09 03:04:08 | INFO | train task=Ses02M epoch=3 batch=364/2468 step=1325 loss=0.2153 ce=0.2032 mse=0.0243 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.140854835510254, "reserved_gb": 1.751953125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "2258", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "48.89"}
2026-08-09 03:04:28 | INFO | train task=Ses02M epoch=3 batch=464/2468 step=1350 loss=0.6868 ce=0.3082 mse=0.7571 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1410655975341797, "reserved_gb": 1.765625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "24", "gpu_mem_used_mb": "2276", "gpu_mem_total_mb": "12288", "gpu_temp_c": "53", "gpu_power_w": "65.04"}
2026-08-09 03:04:46 | INFO | train task=Ses02M epoch=3 batch=564/2468 step=1375 loss=0.8583 ce=0.4824 mse=0.7517 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1402473449707031, "reserved_gb": 2.078125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "19", "gpu_mem_used_mb": "2596", "gpu_mem_total_mb": "12288", "gpu_temp_c": "54", "gpu_power_w": "51.32"}
2026-08-09 03:05:06 | INFO | train task=Ses02M epoch=3 batch=664/2468 step=1400 loss=0.7214 ce=0.6175 mse=0.2078 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1412358283996582, "reserved_gb": 1.818359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "30", "gpu_mem_used_mb": "2330", "gpu_mem_total_mb": "12288", "gpu_temp_c": "54", "gpu_power_w": "57.95"}
2026-08-09 03:05:31 | INFO | train task=Ses02M epoch=3 batch=764/2468 step=1425 loss=2.3192 ce=1.8921 mse=0.8543 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1412625312805176, "reserved_gb": 1.94921875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "38", "gpu_mem_used_mb": "2464", "gpu_mem_total_mb": "12288", "gpu_temp_c": "53", "gpu_power_w": "81.01"}
2026-08-09 03:05:50 | INFO | train task=Ses02M epoch=3 batch=864/2468 step=1450 loss=0.9894 ce=0.7321 mse=0.5147 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1406655311584473, "reserved_gb": 2.193359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "26", "gpu_mem_used_mb": "2714", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "56.46"}
2026-08-09 03:06:09 | INFO | train task=Ses02M epoch=3 batch=964/2468 step=1475 loss=2.9891 ce=2.7904 mse=0.3974 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1413187980651855, "reserved_gb": 2.427734375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "42", "gpu_mem_used_mb": "2954", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "41.06"}
2026-08-09 03:06:29 | INFO | train task=Ses02M epoch=3 batch=1064/2468 step=1500 loss=2.6117 ce=1.7005 mse=1.8225 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.141118049621582, "reserved_gb": 1.91796875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "28", "gpu_mem_used_mb": "2432", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "51.93"}
2026-08-09 03:06:52 | INFO | train task=Ses02M epoch=3 batch=1164/2468 step=1525 loss=2.1759 ce=1.3584 mse=1.6350 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1401963233947754, "reserved_gb": 2.455078125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "27", "gpu_mem_used_mb": "2982", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "72.31"}
2026-08-09 03:07:12 | INFO | train task=Ses02M epoch=3 batch=1264/2468 step=1550 loss=0.3977 ce=0.3878 mse=0.0197 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1456880569458008, "reserved_gb": 2.0546875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "2572", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "68.66"}
2026-08-09 03:07:31 | INFO | train task=Ses02M epoch=3 batch=1364/2468 step=1575 loss=1.2874 ce=0.9006 mse=0.7734 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.141343593597412, "reserved_gb": 2.068359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "30", "gpu_mem_used_mb": "2586", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "64.71"}
2026-08-09 03:07:51 | INFO | train task=Ses02M epoch=3 batch=1464/2468 step=1600 loss=5.7294 ce=5.3233 mse=0.8124 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1421213150024414, "reserved_gb": 2.12890625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "2648", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "64.00"}
2026-08-09 03:08:14 | INFO | train task=Ses02M epoch=3 batch=1564/2468 step=1625 loss=0.4804 ce=0.1308 mse=0.6993 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1456880569458008, "reserved_gb": 2.38671875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "16", "gpu_mem_used_mb": "2912", "gpu_mem_total_mb": "12288", "gpu_temp_c": "44", "gpu_power_w": "64.64"}
2026-08-09 03:08:34 | INFO | train task=Ses02M epoch=3 batch=1664/2468 step=1650 loss=1.3906 ce=0.9653 mse=0.8506 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1405491828918457, "reserved_gb": 1.703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "30", "gpu_mem_used_mb": "2212", "gpu_mem_total_mb": "12288", "gpu_temp_c": "44", "gpu_power_w": "62.32"}
2026-08-09 03:08:55 | INFO | train task=Ses02M epoch=3 batch=1764/2468 step=1675 loss=3.0136 ce=2.6825 mse=0.6621 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.140491008758545, "reserved_gb": 1.837890625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "41", "gpu_mem_used_mb": "2350", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "67.45"}
2026-08-09 03:09:17 | INFO | train task=Ses02M epoch=3 batch=1864/2468 step=1700 loss=0.4530 ce=0.4425 mse=0.0210 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1410388946533203, "reserved_gb": 1.888671875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "13", "gpu_mem_used_mb": "2402", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "93.02"}
2026-08-09 03:09:41 | INFO | train task=Ses02M epoch=3 batch=1964/2468 step=1725 loss=0.4507 ce=0.3200 mse=0.2615 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1406774520874023, "reserved_gb": 1.708984375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "35", "gpu_mem_used_mb": "2218", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "65.83"}
2026-08-09 03:10:02 | INFO | train task=Ses02M epoch=3 batch=2064/2468 step=1750 loss=1.4387 ce=1.1324 mse=0.6127 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1404647827148438, "reserved_gb": 1.70703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "2216", "gpu_mem_total_mb": "12288", "gpu_temp_c": "44", "gpu_power_w": "59.65"}
2026-08-09 03:10:24 | INFO | train task=Ses02M epoch=3 batch=2164/2468 step=1775 loss=1.3394 ce=1.2581 mse=0.1626 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1406183242797852, "reserved_gb": 2.052734375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "2570", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "65.65"}
2026-08-09 03:10:45 | INFO | train task=Ses02M epoch=3 batch=2264/2468 step=1800 loss=1.4123 ce=1.1617 mse=0.5013 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1403632164001465, "reserved_gb": 1.9921875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "2508", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "75.98"}
2026-08-09 03:11:10 | INFO | train task=Ses02M epoch=3 batch=2364/2468 step=1825 loss=1.3900 ce=0.9106 mse=0.9588 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1408653259277344, "reserved_gb": 1.74609375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "40", "gpu_mem_used_mb": "2256", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "70.59"}
2026-08-09 03:11:32 | INFO | train task=Ses02M epoch=3 batch=2464/2468 step=1850 loss=1.1573 ce=1.1426 mse=0.0294 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1404619216918945, "reserved_gb": 1.7734375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "28", "gpu_mem_used_mb": "2284", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "71.50"}

predict:   0%|          | 0/315 [00:00<?, ?it/s]

2026-08-09 03:11:52 | INFO | Epoch 03 task=Ses02M train_loss=1.2802 val_macro_f1=0.5131 val_mae=0.4644 epoch_seconds=540.5

epoch 4:   0%|          | 0/2468 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 03:12:16 | INFO | train task=Ses02M epoch=4 batch=96/2468 step=1875 loss=2.1579 ce=1.7433 mse=0.8291 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1407966613769531, "reserved_gb": 1.779296875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "31", "gpu_mem_used_mb": "2256", "gpu_mem_total_mb": "12288", "gpu_temp_c": "42", "gpu_power_w": "45.29"}
2026-08-09 03:12:37 | INFO | train task=Ses02M epoch=4 batch=196/2468 step=1900 loss=0.6819 ce=0.6385 mse=0.0867 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.140538215637207, "reserved_gb": 1.75390625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "19", "gpu_mem_used_mb": "2255", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "69.39"}
2026-08-09 03:13:00 | INFO | train task=Ses02M epoch=4 batch=296/2468 step=1925 loss=0.6366 ce=0.6147 mse=0.0438 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1407160758972168, "reserved_gb": 1.93359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "11", "gpu_mem_used_mb": "2439", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "65.80"}
2026-08-09 03:13:20 | INFO | train task=Ses02M epoch=4 batch=396/2468 step=1950 loss=1.3408 ce=1.2075 mse=0.2667 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1404170989990234, "reserved_gb": 1.779296875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "23", "gpu_mem_used_mb": "2281", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "71.29"}
2026-08-09 03:13:40 | INFO | train task=Ses02M epoch=4 batch=496/2468 step=1975 loss=0.6242 ce=0.5776 mse=0.0933 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1402435302734375, "reserved_gb": 2.330078125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "14", "gpu_mem_used_mb": "2845", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "60.70"}
2026-08-09 03:14:01 | INFO | train task=Ses02M epoch=4 batch=596/2468 step=2000 loss=0.5652 ce=0.1769 mse=0.7765 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1409854888916016, "reserved_gb": 1.7421875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "26", "gpu_mem_used_mb": "2243", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "76.09"}
2026-08-09 03:14:24 | INFO | train task=Ses02M epoch=4 batch=696/2468 step=2025 loss=0.8931 ce=0.5511 mse=0.6840 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1402359008789062, "reserved_gb": 1.841796875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "28", "gpu_mem_used_mb": "2345", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "67.46"}
2026-08-09 03:14:43 | INFO | train task=Ses02M epoch=4 batch=796/2468 step=2050 loss=1.8860 ce=1.4443 mse=0.8833 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1402521133422852, "reserved_gb": 1.88671875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "23", "gpu_mem_used_mb": "2391", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "72.88"}
2026-08-09 03:15:03 | INFO | train task=Ses02M epoch=4 batch=896/2468 step=2075 loss=2.0098 ce=1.8999 mse=0.2197 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1405811309814453, "reserved_gb": 2.115234375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "2625", "gpu_mem_total_mb": "12288", "gpu_temp_c": "44", "gpu_power_w": "66.28"}
2026-08-09 03:15:22 | INFO | train task=Ses02M epoch=4 batch=996/2468 step=2100 loss=0.4368 ce=0.4264 mse=0.0207 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1404228210449219, "reserved_gb": 1.703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "44", "gpu_mem_used_mb": "2203", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "65.35"}
2026-08-09 03:15:47 | INFO | train task=Ses02M epoch=4 batch=1096/2468 step=2125 loss=0.7080 ce=0.6595 mse=0.0969 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.140444278717041, "reserved_gb": 1.73046875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "11", "gpu_mem_used_mb": "2231", "gpu_mem_total_mb": "12288", "gpu_temp_c": "44", "gpu_power_w": "71.90"}
2026-08-09 03:16:08 | INFO | train task=Ses02M epoch=4 batch=1196/2468 step=2150 loss=0.6268 ce=0.5112 mse=0.2312 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1414122581481934, "reserved_gb": 1.791015625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "26", "gpu_mem_used_mb": "2293", "gpu_mem_total_mb": "12288", "gpu_temp_c": "44", "gpu_power_w": "69.64"}
2026-08-09 03:16:28 | INFO | train task=Ses02M epoch=4 batch=1296/2468 step=2175 loss=0.7820 ce=0.5791 mse=0.4058 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1409540176391602, "reserved_gb": 2.056640625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "30", "gpu_mem_used_mb": "2565", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "82.60"}
2026-08-09 03:16:48 | INFO | train task=Ses02M epoch=4 batch=1396/2468 step=2200 loss=3.1747 ce=2.8052 mse=0.7390 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1407041549682617, "reserved_gb": 1.708984375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "2209", "gpu_mem_total_mb": "12288", "gpu_temp_c": "43", "gpu_power_w": "48.84"}
2026-08-09 03:17:14 | INFO | train task=Ses02M epoch=4 batch=1496/2468 step=2225 loss=1.2124 ce=0.8463 mse=0.7323 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.14064359664917, "reserved_gb": 1.7890625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "2290", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "68.46"}
2026-08-09 03:17:34 | INFO | train task=Ses02M epoch=4 batch=1596/2468 step=2250 loss=1.3427 ce=1.2623 mse=0.1607 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1407318115234375, "reserved_gb": 1.8984375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "26", "gpu_mem_used_mb": "2402", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "86.32"}
2026-08-09 03:17:59 | INFO | train task=Ses02M epoch=4 batch=1696/2468 step=2275 loss=3.4397 ce=3.1496 mse=0.5802 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1421213150024414, "reserved_gb": 1.951171875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "41", "gpu_mem_used_mb": "2456", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "92.38"}
2026-08-09 03:18:23 | INFO | train task=Ses02M epoch=4 batch=1796/2468 step=2300 loss=0.2684 ce=0.2647 mse=0.0073 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1444997787475586, "reserved_gb": 2.083984375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "26", "gpu_mem_used_mb": "2592", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "68.52"}
2026-08-09 03:18:52 | INFO | train task=Ses02M epoch=4 batch=1896/2468 step=2325 loss=1.8762 ce=1.3630 mse=1.0264 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.140336036682129, "reserved_gb": 1.71875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "45", "gpu_mem_used_mb": "2218", "gpu_mem_total_mb": "12288", "gpu_temp_c": "55", "gpu_power_w": "84.81"}
2026-08-09 03:19:19 | INFO | train task=Ses02M epoch=4 batch=1996/2468 step=2350 loss=1.4765 ce=1.2168 mse=0.5193 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1417169570922852, "reserved_gb": 1.875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "2377", "gpu_mem_total_mb": "12288", "gpu_temp_c": "57", "gpu_power_w": "77.13"}
2026-08-09 03:19:46 | INFO | train task=Ses02M epoch=4 batch=2096/2468 step=2375 loss=0.2136 ce=0.2099 mse=0.0073 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1411237716674805, "reserved_gb": 2.001953125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "25", "gpu_mem_used_mb": "2507", "gpu_mem_total_mb": "12288", "gpu_temp_c": "55", "gpu_power_w": "59.45"}
2026-08-09 03:20:11 | INFO | train task=Ses02M epoch=4 batch=2196/2468 step=2400 loss=0.3708 ce=0.1096 mse=0.5223 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1411795616149902, "reserved_gb": 1.7890625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "69", "gpu_mem_used_mb": "2303", "gpu_mem_total_mb": "12288", "gpu_temp_c": "57", "gpu_power_w": "66.85"}
2026-08-09 03:20:40 | INFO | train task=Ses02M epoch=4 batch=2296/2468 step=2425 loss=0.5428 ce=0.4620 mse=0.1615 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1408066749572754, "reserved_gb": 2.00390625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "23", "gpu_mem_used_mb": "2533", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "53.40"}
2026-08-09 03:21:09 | INFO | train task=Ses02M epoch=4 batch=2396/2468 step=2450 loss=1.5197 ce=1.3509 mse=0.3377 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1404461860656738, "reserved_gb": 1.70703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "43", "gpu_mem_used_mb": "2260", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "48.24"}

predict:   0%|          | 0/315 [00:00<?, ?it/s]

2026-08-09 03:22:10 | INFO | Epoch 04 task=Ses02M train_loss=1.1120 val_macro_f1=0.4841 val_mae=0.4882 epoch_seconds=612.5

epoch 5:   0%|          | 0/2468 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 03:22:20 | INFO | train task=Ses02M epoch=5 batch=28/2468 step=2475 loss=0.6215 ce=0.2118 mse=0.8194 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1438608169555664, "reserved_gb": 2.302734375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "12", "gpu_mem_used_mb": "2731", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "48.17"}
2026-08-09 03:22:43 | INFO | train task=Ses02M epoch=5 batch=128/2468 step=2500 loss=0.9797 ce=0.8454 mse=0.2686 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1406545639038086, "reserved_gb": 1.796875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "31", "gpu_mem_used_mb": "2293", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "56.03"}
2026-08-09 03:23:11 | INFO | train task=Ses02M epoch=5 batch=228/2468 step=2525 loss=0.8851 ce=0.8547 mse=0.0609 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1404757499694824, "reserved_gb": 2.107421875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "24", "gpu_mem_used_mb": "2611", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "50.42"}
2026-08-09 03:23:34 | INFO | train task=Ses02M epoch=5 batch=328/2468 step=2550 loss=0.4468 ce=0.4359 mse=0.0218 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1406831741333008, "reserved_gb": 1.798828125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "2295", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "35.41"}
2026-08-09 03:23:57 | INFO | train task=Ses02M epoch=5 batch=428/2468 step=2575 loss=0.7039 ce=0.6847 mse=0.0383 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1407432556152344, "reserved_gb": 2.048828125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "34", "gpu_mem_used_mb": "2551", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "56.89"}
2026-08-09 03:24:20 | INFO | train task=Ses02M epoch=5 batch=528/2468 step=2600 loss=3.0164 ce=2.9495 mse=0.1337 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.140394687652588, "reserved_gb": 1.935546875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "19", "gpu_mem_used_mb": "2435", "gpu_mem_total_mb": "12288", "gpu_temp_c": "55", "gpu_power_w": "67.33"}
2026-08-09 03:24:47 | INFO | train task=Ses02M epoch=5 batch=628/2468 step=2625 loss=0.6964 ce=0.4995 mse=0.3937 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.140273094177246, "reserved_gb": 1.677734375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "28", "gpu_mem_used_mb": "2171", "gpu_mem_total_mb": "12288", "gpu_temp_c": "54", "gpu_power_w": "43.44"}
2026-08-09 03:25:12 | INFO | train task=Ses02M epoch=5 batch=728/2468 step=2650 loss=0.3525 ce=0.3439 mse=0.0172 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.140589714050293, "reserved_gb": 1.96875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "44", "gpu_mem_used_mb": "2469", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "43.50"}
2026-08-09 03:25:35 | INFO | train task=Ses02M epoch=5 batch=828/2468 step=2675 loss=0.4869 ce=0.3556 mse=0.2626 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.142244815826416, "reserved_gb": 1.884765625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "28", "gpu_mem_used_mb": "2383", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "44.44"}
2026-08-09 03:25:58 | INFO | train task=Ses02M epoch=5 batch=928/2468 step=2700 loss=0.5182 ce=0.3957 mse=0.2449 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1409225463867188, "reserved_gb": 1.751953125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "2247", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "64.30"}
2026-08-09 03:26:23 | INFO | train task=Ses02M epoch=5 batch=1028/2468 step=2725 loss=0.5491 ce=0.3933 mse=0.3115 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1406269073486328, "reserved_gb": 2.32421875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "2833", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "55.72"}
2026-08-09 03:26:45 | INFO | train task=Ses02M epoch=5 batch=1128/2468 step=2750 loss=0.3058 ce=0.0870 mse=0.4375 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1408309936523438, "reserved_gb": 2.009765625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "18", "gpu_mem_used_mb": "2511", "gpu_mem_total_mb": "12288", "gpu_temp_c": "43", "gpu_power_w": "42.21"}
2026-08-09 03:27:07 | INFO | train task=Ses02M epoch=5 batch=1228/2468 step=2775 loss=2.4285 ce=2.3221 mse=0.2127 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.140336036682129, "reserved_gb": 2.033203125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "29", "gpu_mem_used_mb": "2535", "gpu_mem_total_mb": "12288", "gpu_temp_c": "44", "gpu_power_w": "41.76"}
2026-08-09 03:27:30 | INFO | train task=Ses02M epoch=5 batch=1328/2468 step=2800 loss=5.2105 ce=3.2959 mse=3.8292 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1402792930603027, "reserved_gb": 2.029296875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "26", "gpu_mem_used_mb": "2531", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "59.25"}
2026-08-09 03:27:57 | INFO | train task=Ses02M epoch=5 batch=1428/2468 step=2825 loss=0.4707 ce=0.0901 mse=0.7612 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1477603912353516, "reserved_gb": 2.291015625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "48", "gpu_mem_used_mb": "2799", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "70.85"}
2026-08-09 03:28:22 | INFO | train task=Ses02M epoch=5 batch=1528/2468 step=2850 loss=0.6771 ce=0.6085 mse=0.1372 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1404480934143066, "reserved_gb": 1.697265625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "24", "gpu_mem_used_mb": "2191", "gpu_mem_total_mb": "12288", "gpu_temp_c": "43", "gpu_power_w": "43.04"}
2026-08-09 03:28:47 | INFO | train task=Ses02M epoch=5 batch=1628/2468 step=2875 loss=0.6083 ce=0.4803 mse=0.2559 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.140854835510254, "reserved_gb": 2.306640625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "23", "gpu_mem_used_mb": "2814", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "71.49"}
2026-08-09 03:29:11 | INFO | train task=Ses02M epoch=5 batch=1728/2468 step=2900 loss=0.6488 ce=0.4210 mse=0.4556 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.141486644744873, "reserved_gb": 2.095703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "13", "gpu_mem_used_mb": "2598", "gpu_mem_total_mb": "12288", "gpu_temp_c": "44", "gpu_power_w": "48.42"}
2026-08-09 03:29:37 | INFO | train task=Ses02M epoch=5 batch=1828/2468 step=2925 loss=0.1493 ce=0.1075 mse=0.0835 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.140700340270996, "reserved_gb": 1.693359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "19", "gpu_mem_used_mb": "2186", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "52.14"}
2026-08-09 03:30:03 | INFO | train task=Ses02M epoch=5 batch=1928/2468 step=2950 loss=0.2872 ce=0.1908 mse=0.1928 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.140791416168213, "reserved_gb": 2.5859375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "65", "gpu_mem_used_mb": "3100", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "63.86"}
2026-08-09 03:30:26 | INFO | train task=Ses02M epoch=5 batch=2028/2468 step=2975 loss=0.4512 ce=0.1026 mse=0.6973 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1410408020019531, "reserved_gb": 2.0390625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "2540", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "62.31"}
2026-08-09 03:30:52 | INFO | train task=Ses02M epoch=5 batch=2128/2468 step=3000 loss=0.8897 ce=0.6373 mse=0.5048 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1402487754821777, "reserved_gb": 2.19921875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "0", "gpu_mem_used_mb": "2704", "gpu_mem_total_mb": "12288", "gpu_temp_c": "44", "gpu_power_w": "58.06"}
2026-08-09 03:31:21 | INFO | train task=Ses02M epoch=5 batch=2228/2468 step=3025 loss=0.9212 ce=0.3169 mse=1.2085 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.14166259765625, "reserved_gb": 2.060546875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "33", "gpu_mem_used_mb": "2562", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "65.67"}
2026-08-09 03:31:46 | INFO | train task=Ses02M epoch=5 batch=2328/2468 step=3050 loss=0.8448 ce=0.8346 mse=0.0205 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1439428329467773, "reserved_gb": 1.73828125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "59", "gpu_mem_used_mb": "2232", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "67.62"}
2026-08-09 03:32:12 | INFO | train task=Ses02M epoch=5 batch=2428/2468 step=3075 loss=0.9736 ce=0.5622 mse=0.8229 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.141153335571289, "reserved_gb": 1.69140625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "30", "gpu_mem_used_mb": "2184", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "73.78"}

predict:   0%|          | 0/315 [00:00<?, ?it/s]

2026-08-09 03:32:42 | INFO | Epoch 05 task=Ses02M train_loss=0.9723 val_macro_f1=0.4889 val_mae=0.4780 epoch_seconds=629.6

predict:   0%|          | 0/296 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)

predict:   0%|          | 0/358 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
2026-08-09 03:35:05 | INFO | Task 523a04de7af1f0cf_main_fold -> complete
2026-08-09 03:35:07 | INFO | Manuscript outputs refreshed: 21 tables, 4 figures
2026-08-09 03:35:07 | INFO | Task 0695196ad49b8151_main_fold -> running
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\transformers\configuration_utils.py:335: UserWarning: Passing `gradient_checkpointing` to a config initialization is deprecated and will be removed in v5 Transformers. Using `model.gradient_checkpointing_enable()` instead, or if you are using the `Trainer` API, pass `gradient_checkpointing=True` in your `TrainingArguments`.
  warnings.warn(
2026-08-09 03:35:09 | INFO | Task C:\Users\HaseebWajid\Downloads\runs\dersx_paper_aligned\campaign_01\main\seed_13\Ses03F parameters={'total': 163009451, 'trainable': 69034283, 'frozen': 93975168} scope={'corpus': 'IEMOCAP', 'protocol': 'strict_LOSO', 'heldout_speaker': 'Ses03F', 'seed': 13, 'stage': 'main', 'profile': 'rtx3060_24h'}

epoch 1:   0%|          | 0/2350 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 03:35:33 | INFO | train task=Ses03F epoch=1 batch=100/2350 step=25 loss=2.6169 ce=2.0009 mse=1.2318 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1430702209472656, "reserved_gb": 1.908203125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "31", "gpu_mem_used_mb": "2406", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "55.87"}
2026-08-09 03:35:55 | INFO | train task=Ses03F epoch=1 batch=200/2350 step=50 loss=2.2929 ce=2.1895 mse=0.2069 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1419777870178223, "reserved_gb": 1.724609375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "2218", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "66.96"}
2026-08-09 03:36:17 | INFO | train task=Ses03F epoch=1 batch=300/2350 step=75 loss=2.1905 ce=1.8956 mse=0.5899 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1407432556152344, "reserved_gb": 1.701171875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "28", "gpu_mem_used_mb": "2194", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "93.25"}
2026-08-09 03:36:40 | INFO | train task=Ses03F epoch=1 batch=400/2350 step=100 loss=2.4867 ce=1.9337 mse=1.1060 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1403875350952148, "reserved_gb": 1.814453125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "48", "gpu_mem_used_mb": "2310", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "70.62"}
2026-08-09 03:37:04 | INFO | train task=Ses03F epoch=1 batch=500/2350 step=125 loss=2.5742 ce=1.8321 mse=1.4843 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1407475471496582, "reserved_gb": 1.9921875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "37", "gpu_mem_used_mb": "2492", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "71.18"}
2026-08-09 03:37:28 | INFO | train task=Ses03F epoch=1 batch=600/2350 step=150 loss=2.8220 ce=2.4390 mse=0.7660 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.14003324508667, "reserved_gb": 1.7265625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "43", "gpu_mem_used_mb": "2220", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "69.93"}
2026-08-09 03:37:53 | INFO | train task=Ses03F epoch=1 batch=700/2350 step=175 loss=2.7419 ce=1.7397 mse=2.0042 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.140812873840332, "reserved_gb": 1.900390625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "2416", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "93.61"}
2026-08-09 03:38:16 | INFO | train task=Ses03F epoch=1 batch=800/2350 step=200 loss=1.8447 ce=1.8320 mse=0.0254 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1405448913574219, "reserved_gb": 1.76171875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "2274", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "63.87"}
2026-08-09 03:38:42 | INFO | train task=Ses03F epoch=1 batch=900/2350 step=225 loss=2.5359 ce=2.5177 mse=0.0366 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1407785415649414, "reserved_gb": 1.708984375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "23", "gpu_mem_used_mb": "2220", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "79.19"}
2026-08-09 03:39:06 | INFO | train task=Ses03F epoch=1 batch=1000/2350 step=250 loss=2.0197 ce=1.6009 mse=0.8376 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1404905319213867, "reserved_gb": 1.70703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "38", "gpu_mem_used_mb": "2218", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "52.51"}
2026-08-09 03:39:31 | INFO | train task=Ses03F epoch=1 batch=1100/2350 step=275 loss=1.7053 ce=1.4333 mse=0.5439 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1401138305664062, "reserved_gb": 1.857421875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "18", "gpu_mem_used_mb": "2396", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "64.64"}
2026-08-09 03:39:58 | INFO | train task=Ses03F epoch=1 batch=1200/2350 step=300 loss=1.5788 ce=1.0861 mse=0.9853 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1435728073120117, "reserved_gb": 1.7265625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "46", "gpu_mem_used_mb": "2262", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "73.77"}
2026-08-09 03:40:24 | INFO | train task=Ses03F epoch=1 batch=1300/2350 step=325 loss=1.4227 ce=1.1433 mse=0.5590 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1411309242248535, "reserved_gb": 1.818359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "28", "gpu_mem_used_mb": "2356", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "78.91"}
2026-08-09 03:40:48 | INFO | train task=Ses03F epoch=1 batch=1400/2350 step=350 loss=2.0191 ce=1.7266 mse=0.5851 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1405344009399414, "reserved_gb": 1.748046875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "2284", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "55.63"}
2026-08-09 03:41:12 | INFO | train task=Ses03F epoch=1 batch=1500/2350 step=375 loss=1.4404 ce=1.3364 mse=0.2078 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1401963233947754, "reserved_gb": 1.712890625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "32", "gpu_mem_used_mb": "2248", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "64.50"}
2026-08-09 03:41:36 | INFO | train task=Ses03F epoch=1 batch=1600/2350 step=400 loss=2.7228 ce=2.1437 mse=1.1582 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1438612937927246, "reserved_gb": 1.75, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "55", "gpu_mem_used_mb": "2286", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "73.93"}
2026-08-09 03:42:05 | INFO | train task=Ses03F epoch=1 batch=1700/2350 step=425 loss=1.9186 ce=1.8721 mse=0.0930 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1400270462036133, "reserved_gb": 1.740234375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "19", "gpu_mem_used_mb": "2276", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "75.57"}
2026-08-09 03:42:29 | INFO | train task=Ses03F epoch=1 batch=1800/2350 step=450 loss=0.6455 ce=0.5292 mse=0.2325 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1406173706054688, "reserved_gb": 1.7890625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "23", "gpu_mem_used_mb": "2326", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "76.15"}
2026-08-09 03:42:55 | INFO | train task=Ses03F epoch=1 batch=1900/2350 step=475 loss=2.4688 ce=1.3943 mse=2.1489 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1400504112243652, "reserved_gb": 1.759765625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "2296", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "85.42"}
2026-08-09 03:43:18 | INFO | train task=Ses03F epoch=1 batch=2000/2350 step=500 loss=2.3929 ce=2.2136 mse=0.3587 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1414361000061035, "reserved_gb": 2.001953125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "36", "gpu_mem_used_mb": "2544", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "65.25"}
2026-08-09 03:43:45 | INFO | train task=Ses03F epoch=1 batch=2100/2350 step=525 loss=1.3727 ce=0.9744 mse=0.7967 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.140376091003418, "reserved_gb": 1.763671875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "60", "gpu_mem_used_mb": "2300", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "57.56"}
2026-08-09 03:44:09 | INFO | train task=Ses03F epoch=1 batch=2200/2350 step=550 loss=2.4171 ce=1.6735 mse=1.4872 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1400322914123535, "reserved_gb": 1.783203125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "2320", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "71.06"}
2026-08-09 03:44:32 | INFO | train task=Ses03F epoch=1 batch=2300/2350 step=575 loss=1.6380 ce=1.3402 mse=0.5955 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.140556812286377, "reserved_gb": 1.78125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "2318", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "96.54"}

predict:   0%|          | 0/336 [00:00<?, ?it/s]

2026-08-09 03:45:19 | INFO | Epoch 01 task=Ses03F train_loss=1.9975 val_macro_f1=0.3787 val_mae=0.6062 epoch_seconds=609.3

epoch 2:   0%|          | 0/2350 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 03:45:34 | INFO | train task=Ses03F epoch=2 batch=48/2350 step=600 loss=2.5297 ce=2.1577 mse=0.7441 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.141850471496582, "reserved_gb": 2.029296875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "32", "gpu_mem_used_mb": "2571", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "70.01"}
2026-08-09 03:45:57 | INFO | train task=Ses03F epoch=2 batch=148/2350 step=625 loss=0.7346 ce=0.7288 mse=0.0117 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.140326976776123, "reserved_gb": 1.705078125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "2239", "gpu_mem_total_mb": "12288", "gpu_temp_c": "44", "gpu_power_w": "56.02"}
2026-08-09 03:46:20 | INFO | train task=Ses03F epoch=2 batch=248/2350 step=650 loss=0.8187 ce=0.5693 mse=0.4990 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1407060623168945, "reserved_gb": 1.818359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "16", "gpu_mem_used_mb": "2355", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "81.96"}
2026-08-09 03:46:41 | INFO | train task=Ses03F epoch=2 batch=348/2350 step=675 loss=0.4369 ce=0.3726 mse=0.1286 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1402320861816406, "reserved_gb": 2.1953125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "18", "gpu_mem_used_mb": "2741", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "66.51"}
2026-08-09 03:47:00 | INFO | train task=Ses03F epoch=2 batch=448/2350 step=700 loss=0.4968 ce=0.2410 mse=0.5116 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1408252716064453, "reserved_gb": 1.755859375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "13", "gpu_mem_used_mb": "2291", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "73.15"}
2026-08-09 03:47:24 | INFO | train task=Ses03F epoch=2 batch=548/2350 step=725 loss=0.5126 ce=0.4937 mse=0.0379 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1425790786743164, "reserved_gb": 1.966796875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "40", "gpu_mem_used_mb": "2507", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "76.72"}
2026-08-09 03:47:45 | INFO | train task=Ses03F epoch=2 batch=648/2350 step=750 loss=1.5632 ce=1.5562 mse=0.0140 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1401329040527344, "reserved_gb": 1.744140625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "29", "gpu_mem_used_mb": "2279", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "64.80"}
2026-08-09 03:48:04 | INFO | train task=Ses03F epoch=2 batch=748/2350 step=775 loss=1.6499 ce=1.1687 mse=0.9624 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1435365676879883, "reserved_gb": 1.748046875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "69", "gpu_mem_used_mb": "2282", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "62.20"}
2026-08-09 03:48:24 | INFO | train task=Ses03F epoch=2 batch=848/2350 step=800 loss=2.9900 ce=2.8115 mse=0.3570 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1399760246276855, "reserved_gb": 1.685546875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "23", "gpu_mem_used_mb": "2218", "gpu_mem_total_mb": "12288", "gpu_temp_c": "44", "gpu_power_w": "49.61"}
2026-08-09 03:48:48 | INFO | train task=Ses03F epoch=2 batch=948/2350 step=825 loss=0.4284 ce=0.3863 mse=0.0842 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.140413761138916, "reserved_gb": 2.078125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "23", "gpu_mem_used_mb": "2626", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "65.50"}
2026-08-09 03:49:07 | INFO | train task=Ses03F epoch=2 batch=1048/2350 step=850 loss=1.2597 ce=0.7142 mse=1.0910 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1408653259277344, "reserved_gb": 1.84375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "2386", "gpu_mem_total_mb": "12288", "gpu_temp_c": "44", "gpu_power_w": "60.17"}
2026-08-09 03:49:26 | INFO | train task=Ses03F epoch=2 batch=1148/2350 step=875 loss=0.9341 ce=0.7915 mse=0.2853 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1412410736083984, "reserved_gb": 1.779296875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "28", "gpu_mem_used_mb": "2320", "gpu_mem_total_mb": "12288", "gpu_temp_c": "44", "gpu_power_w": "42.28"}
2026-08-09 03:49:46 | INFO | train task=Ses03F epoch=2 batch=1248/2350 step=900 loss=0.4849 ce=0.2839 mse=0.4018 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1438612937927246, "reserved_gb": 2.71484375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "36", "gpu_mem_used_mb": "3278", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "74.44"}
2026-08-09 03:50:09 | INFO | train task=Ses03F epoch=2 batch=1348/2350 step=925 loss=1.1665 ce=1.0100 mse=0.3131 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1408281326293945, "reserved_gb": 1.767578125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "2308", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "65.29"}
2026-08-09 03:50:29 | INFO | train task=Ses03F epoch=2 batch=1448/2350 step=950 loss=1.7093 ce=1.4347 mse=0.5492 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1400656700134277, "reserved_gb": 1.708984375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "25", "gpu_mem_used_mb": "2248", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "65.88"}
2026-08-09 03:50:48 | INFO | train task=Ses03F epoch=2 batch=1548/2350 step=975 loss=1.7069 ce=1.4714 mse=0.4711 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.140174388885498, "reserved_gb": 1.99609375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "36", "gpu_mem_used_mb": "2542", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "58.95"}
2026-08-09 03:51:09 | INFO | train task=Ses03F epoch=2 batch=1648/2350 step=1000 loss=1.9629 ce=1.6147 mse=0.6963 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.141641616821289, "reserved_gb": 2.56640625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "18", "gpu_mem_used_mb": "3126", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "73.61"}
2026-08-09 03:51:31 | INFO | train task=Ses03F epoch=2 batch=1748/2350 step=1025 loss=0.9198 ce=0.9185 mse=0.0025 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1405029296875, "reserved_gb": 2.4296875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "23", "gpu_mem_used_mb": "2986", "gpu_mem_total_mb": "12288", "gpu_temp_c": "43", "gpu_power_w": "47.07"}
2026-08-09 03:51:50 | INFO | train task=Ses03F epoch=2 batch=1848/2350 step=1050 loss=0.6417 ce=0.3612 mse=0.5611 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1411452293395996, "reserved_gb": 2.23046875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "38", "gpu_mem_used_mb": "2782", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "71.30"}
2026-08-09 03:52:08 | INFO | train task=Ses03F epoch=2 batch=1948/2350 step=1075 loss=0.5064 ce=0.4922 mse=0.0284 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1425132751464844, "reserved_gb": 2.103515625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "27", "gpu_mem_used_mb": "2652", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "62.26"}
2026-08-09 03:52:27 | INFO | train task=Ses03F epoch=2 batch=2048/2350 step=1100 loss=1.8557 ce=1.4866 mse=0.7381 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1402263641357422, "reserved_gb": 1.8359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "10", "gpu_mem_used_mb": "2378", "gpu_mem_total_mb": "12288", "gpu_temp_c": "44", "gpu_power_w": "61.10"}
2026-08-09 03:52:49 | INFO | train task=Ses03F epoch=2 batch=2148/2350 step=1125 loss=1.0958 ce=1.0401 mse=0.1115 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1415624618530273, "reserved_gb": 1.791015625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "28", "gpu_mem_used_mb": "2332", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "64.96"}
2026-08-09 03:53:09 | INFO | train task=Ses03F epoch=2 batch=2248/2350 step=1150 loss=1.6084 ce=0.5684 mse=2.0801 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1419281959533691, "reserved_gb": 1.76171875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "8", "gpu_mem_used_mb": "2302", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "54.83"}
2026-08-09 03:53:29 | INFO | train task=Ses03F epoch=2 batch=2348/2350 step=1175 loss=0.7521 ce=0.6711 mse=0.1620 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1399965286254883, "reserved_gb": 2.6484375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "26", "gpu_mem_used_mb": "3210", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "73.24"}

predict:   0%|          | 0/336 [00:00<?, ?it/s]

2026-08-09 03:53:51 | INFO | Epoch 02 task=Ses03F train_loss=1.4522 val_macro_f1=0.3824 val_mae=0.5721 epoch_seconds=506.0

epoch 3:   0%|          | 0/2350 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 03:54:13 | INFO | train task=Ses03F epoch=3 batch=96/2350 step=1200 loss=0.9056 ce=0.8652 mse=0.0809 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1402945518493652, "reserved_gb": 1.919921875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "15", "gpu_mem_used_mb": "2464", "gpu_mem_total_mb": "12288", "gpu_temp_c": "54", "gpu_power_w": "64.61"}
2026-08-09 03:54:35 | INFO | train task=Ses03F epoch=3 batch=196/2350 step=1225 loss=0.9709 ce=0.9405 mse=0.0608 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1401586532592773, "reserved_gb": 2.333984375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "34", "gpu_mem_used_mb": "2888", "gpu_mem_total_mb": "12288", "gpu_temp_c": "56", "gpu_power_w": "62.19"}
2026-08-09 03:54:54 | INFO | train task=Ses03F epoch=3 batch=296/2350 step=1250 loss=2.6621 ce=1.8735 mse=1.5772 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1401190757751465, "reserved_gb": 2.33984375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "14", "gpu_mem_used_mb": "2894", "gpu_mem_total_mb": "12288", "gpu_temp_c": "57", "gpu_power_w": "73.16"}
2026-08-09 03:55:13 | INFO | train task=Ses03F epoch=3 batch=396/2350 step=1275 loss=1.1398 ce=0.8758 mse=0.5280 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1454896926879883, "reserved_gb": 2.306640625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "2860", "gpu_mem_total_mb": "12288", "gpu_temp_c": "56", "gpu_power_w": "76.62"}
2026-08-09 03:55:32 | INFO | train task=Ses03F epoch=3 batch=496/2350 step=1300 loss=0.6156 ce=0.5199 mse=0.1915 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1402745246887207, "reserved_gb": 2.1640625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "11", "gpu_mem_used_mb": "2714", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "46.31"}
2026-08-09 03:55:55 | INFO | train task=Ses03F epoch=3 batch=596/2350 step=1325 loss=0.6993 ce=0.4951 mse=0.4084 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1401634216308594, "reserved_gb": 1.734375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "32", "gpu_mem_used_mb": "2274", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "60.93"}
2026-08-09 03:56:13 | INFO | train task=Ses03F epoch=3 batch=696/2350 step=1350 loss=0.6695 ce=0.6614 mse=0.0163 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1399755477905273, "reserved_gb": 1.822265625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "46", "gpu_mem_used_mb": "2364", "gpu_mem_total_mb": "12288", "gpu_temp_c": "54", "gpu_power_w": "93.39"}
2026-08-09 03:56:32 | INFO | train task=Ses03F epoch=3 batch=796/2350 step=1375 loss=1.8242 ce=1.2305 mse=1.1875 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1402583122253418, "reserved_gb": 1.787109375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "88", "gpu_mem_used_mb": "2328", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "84.43"}
2026-08-09 03:56:52 | INFO | train task=Ses03F epoch=3 batch=896/2350 step=1400 loss=1.2545 ce=1.0552 mse=0.3987 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.140458106994629, "reserved_gb": 1.990234375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "2536", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "64.90"}
2026-08-09 03:57:15 | INFO | train task=Ses03F epoch=3 batch=996/2350 step=1425 loss=0.5970 ce=0.1758 mse=0.8424 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1411528587341309, "reserved_gb": 1.984375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "31", "gpu_mem_used_mb": "2530", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "58.36"}
2026-08-09 03:57:35 | INFO | train task=Ses03F epoch=3 batch=1096/2350 step=1450 loss=1.7176 ce=1.6172 mse=0.2007 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.140988826751709, "reserved_gb": 1.75390625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "29", "gpu_mem_used_mb": "2294", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "72.20"}
2026-08-09 03:57:54 | INFO | train task=Ses03F epoch=3 batch=1196/2350 step=1475 loss=4.2280 ce=4.1112 mse=0.2337 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1452350616455078, "reserved_gb": 2.5234375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "3082", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "75.93"}
2026-08-09 03:58:12 | INFO | train task=Ses03F epoch=3 batch=1296/2350 step=1500 loss=0.4604 ce=0.2485 mse=0.4237 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.140906810760498, "reserved_gb": 2.228515625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "29", "gpu_mem_used_mb": "2780", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "68.34"}
2026-08-09 03:58:35 | INFO | train task=Ses03F epoch=3 batch=1396/2350 step=1525 loss=2.9512 ce=2.9336 mse=0.0353 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1416654586791992, "reserved_gb": 1.84765625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "61", "gpu_mem_used_mb": "2390", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "69.62"}
2026-08-09 03:58:55 | INFO | train task=Ses03F epoch=3 batch=1496/2350 step=1550 loss=1.1930 ce=0.8913 mse=0.6034 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1418476104736328, "reserved_gb": 1.990234375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "19", "gpu_mem_used_mb": "2536", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "59.95"}
2026-08-09 03:59:14 | INFO | train task=Ses03F epoch=3 batch=1596/2350 step=1575 loss=0.8012 ce=0.6792 mse=0.2440 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.140331745147705, "reserved_gb": 1.7578125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "45", "gpu_mem_used_mb": "2298", "gpu_mem_total_mb": "12288", "gpu_temp_c": "44", "gpu_power_w": "42.17"}
2026-08-09 03:59:34 | INFO | train task=Ses03F epoch=3 batch=1696/2350 step=1600 loss=2.8292 ce=2.5397 mse=0.5790 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1402969360351562, "reserved_gb": 2.0625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "30", "gpu_mem_used_mb": "2610", "gpu_mem_total_mb": "12288", "gpu_temp_c": "44", "gpu_power_w": "53.37"}
2026-08-09 03:59:55 | INFO | train task=Ses03F epoch=3 batch=1796/2350 step=1625 loss=0.2966 ce=0.2403 mse=0.1126 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1408748626708984, "reserved_gb": 1.7734375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "16", "gpu_mem_used_mb": "2314", "gpu_mem_total_mb": "12288", "gpu_temp_c": "43", "gpu_power_w": "40.63"}
2026-08-09 04:00:14 | INFO | train task=Ses03F epoch=3 batch=1896/2350 step=1650 loss=0.3946 ce=0.3309 mse=0.1273 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.141566276550293, "reserved_gb": 1.732421875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "16", "gpu_mem_used_mb": "2272", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "57.06"}
2026-08-09 04:00:35 | INFO | train task=Ses03F epoch=3 batch=1996/2350 step=1675 loss=0.2274 ce=0.1712 mse=0.1124 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1399497985839844, "reserved_gb": 2.13671875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "55", "gpu_mem_used_mb": "2686", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "65.34"}
2026-08-09 04:00:57 | INFO | train task=Ses03F epoch=3 batch=2096/2350 step=1700 loss=1.7254 ce=0.6256 mse=2.1996 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1404352188110352, "reserved_gb": 1.724609375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "2263", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "64.58"}
2026-08-09 04:01:20 | INFO | train task=Ses03F epoch=3 batch=2196/2350 step=1725 loss=1.1273 ce=0.8753 mse=0.5041 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1404728889465332, "reserved_gb": 1.70703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "16", "gpu_mem_used_mb": "2246", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "65.52"}
2026-08-09 04:01:39 | INFO | train task=Ses03F epoch=3 batch=2296/2350 step=1750 loss=3.1153 ce=2.9393 mse=0.3520 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1419758796691895, "reserved_gb": 2.154296875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "38", "gpu_mem_used_mb": "2704", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "45.15"}

predict:   0%|          | 0/336 [00:00<?, ?it/s]

2026-08-09 04:02:13 | INFO | Epoch 03 task=Ses03F train_loss=1.2114 val_macro_f1=0.4203 val_mae=0.6000 epoch_seconds=497.6

epoch 4:   0%|          | 0/2350 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 04:02:26 | INFO | train task=Ses03F epoch=4 batch=44/2350 step=1775 loss=1.7540 ce=1.6985 mse=0.1110 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1402263641357422, "reserved_gb": 2.048828125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "2447", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "81.71"}
2026-08-09 04:02:45 | INFO | train task=Ses03F epoch=4 batch=144/2350 step=1800 loss=2.3619 ce=2.2473 mse=0.2293 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1412734985351562, "reserved_gb": 2.2421875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "58", "gpu_mem_used_mb": "2652", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "58.83"}
2026-08-09 04:03:08 | INFO | train task=Ses03F epoch=4 batch=244/2350 step=1825 loss=0.4721 ce=0.2293 mse=0.4857 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.140662670135498, "reserved_gb": 1.783203125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "36", "gpu_mem_used_mb": "2182", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "80.68"}
2026-08-09 04:03:26 | INFO | train task=Ses03F epoch=4 batch=344/2350 step=1850 loss=1.3650 ce=1.0901 mse=0.5497 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1400270462036133, "reserved_gb": 1.83984375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "31", "gpu_mem_used_mb": "2249", "gpu_mem_total_mb": "12288", "gpu_temp_c": "54", "gpu_power_w": "99.68"}
2026-08-09 04:03:46 | INFO | train task=Ses03F epoch=4 batch=444/2350 step=1875 loss=0.7026 ce=0.5974 mse=0.2103 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1407809257507324, "reserved_gb": 1.705078125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "32", "gpu_mem_used_mb": "2111", "gpu_mem_total_mb": "12288", "gpu_temp_c": "55", "gpu_power_w": "67.25"}
2026-08-09 04:04:04 | INFO | train task=Ses03F epoch=4 batch=544/2350 step=1900 loss=1.2412 ce=0.4734 mse=1.5355 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1405048370361328, "reserved_gb": 2.263671875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "31", "gpu_mem_used_mb": "2683", "gpu_mem_total_mb": "12288", "gpu_temp_c": "54", "gpu_power_w": "66.93"}
2026-08-09 04:04:27 | INFO | train task=Ses03F epoch=4 batch=644/2350 step=1925 loss=0.5828 ce=0.4774 mse=0.2108 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1409316062927246, "reserved_gb": 2.451171875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "2875", "gpu_mem_total_mb": "12288", "gpu_temp_c": "53", "gpu_power_w": "70.92"}
2026-08-09 04:04:47 | INFO | train task=Ses03F epoch=4 batch=744/2350 step=1950 loss=0.8244 ce=0.5004 mse=0.6482 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1400108337402344, "reserved_gb": 1.8046875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "43", "gpu_mem_used_mb": "2215", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "78.12"}
2026-08-09 04:05:06 | INFO | train task=Ses03F epoch=4 batch=844/2350 step=1975 loss=0.5521 ce=0.5430 mse=0.0182 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.140629768371582, "reserved_gb": 1.79296875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "26", "gpu_mem_used_mb": "2203", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "76.98"}
2026-08-09 04:05:24 | INFO | train task=Ses03F epoch=4 batch=944/2350 step=2000 loss=0.1541 ce=0.0623 mse=0.1835 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1401963233947754, "reserved_gb": 1.771484375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "49", "gpu_mem_used_mb": "2181", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "42.75"}
2026-08-09 04:05:47 | INFO | train task=Ses03F epoch=4 batch=1044/2350 step=2025 loss=0.7338 ce=0.5532 mse=0.3612 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1410179138183594, "reserved_gb": 2.25, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "35", "gpu_mem_used_mb": "2671", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "71.56"}
2026-08-09 04:06:05 | INFO | train task=Ses03F epoch=4 batch=1144/2350 step=2050 loss=0.5639 ce=0.3432 mse=0.4414 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1414270401000977, "reserved_gb": 2.240234375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "18", "gpu_mem_used_mb": "2661", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "61.48"}
2026-08-09 04:06:24 | INFO | train task=Ses03F epoch=4 batch=1244/2350 step=2075 loss=0.6340 ce=0.5679 mse=0.1321 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.139979362487793, "reserved_gb": 1.78125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "30", "gpu_mem_used_mb": "2235", "gpu_mem_total_mb": "12288", "gpu_temp_c": "44", "gpu_power_w": "43.99"}
2026-08-09 04:06:43 | INFO | train task=Ses03F epoch=4 batch=1344/2350 step=2100 loss=0.5241 ce=0.3193 mse=0.4096 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1399078369140625, "reserved_gb": 2.01171875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "19", "gpu_mem_used_mb": "2471", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "64.75"}
2026-08-09 04:07:06 | INFO | train task=Ses03F epoch=4 batch=1444/2350 step=2125 loss=0.4914 ce=0.3649 mse=0.2530 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1399741172790527, "reserved_gb": 2.015625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "15", "gpu_mem_used_mb": "2475", "gpu_mem_total_mb": "12288", "gpu_temp_c": "44", "gpu_power_w": "48.87"}
2026-08-09 04:07:25 | INFO | train task=Ses03F epoch=4 batch=1544/2350 step=2150 loss=0.7495 ce=0.7226 mse=0.0539 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.140528678894043, "reserved_gb": 1.759765625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "30", "gpu_mem_used_mb": "2213", "gpu_mem_total_mb": "12288", "gpu_temp_c": "43", "gpu_power_w": "39.52"}
2026-08-09 04:07:43 | INFO | train task=Ses03F epoch=4 batch=1644/2350 step=2175 loss=1.6283 ce=1.5410 mse=0.1746 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1402359008789062, "reserved_gb": 1.73828125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "70", "gpu_mem_used_mb": "2191", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "69.60"}
2026-08-09 04:08:05 | INFO | train task=Ses03F epoch=4 batch=1744/2350 step=2200 loss=0.4030 ce=0.3538 mse=0.0984 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1417598724365234, "reserved_gb": 1.83203125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "35", "gpu_mem_used_mb": "2287", "gpu_mem_total_mb": "12288", "gpu_temp_c": "44", "gpu_power_w": "55.37"}
2026-08-09 04:08:26 | INFO | train task=Ses03F epoch=4 batch=1844/2350 step=2225 loss=0.4929 ce=0.3272 mse=0.3314 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1441235542297363, "reserved_gb": 2.31640625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "36", "gpu_mem_used_mb": "2783", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "74.19"}
2026-08-09 04:08:45 | INFO | train task=Ses03F epoch=4 batch=1944/2350 step=2250 loss=0.1463 ce=0.0996 mse=0.0933 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1405448913574219, "reserved_gb": 1.8125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "23", "gpu_mem_used_mb": "2267", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "63.75"}
2026-08-09 04:09:05 | INFO | train task=Ses03F epoch=4 batch=2044/2350 step=2275 loss=1.2159 ce=1.2149 mse=0.0019 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.141861915588379, "reserved_gb": 1.9453125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "19", "gpu_mem_used_mb": "2403", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "67.82"}
2026-08-09 04:09:25 | INFO | train task=Ses03F epoch=4 batch=2144/2350 step=2300 loss=1.5618 ce=1.4063 mse=0.3110 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1400485038757324, "reserved_gb": 1.810546875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "18", "gpu_mem_used_mb": "2265", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "71.39"}
2026-08-09 04:09:48 | INFO | train task=Ses03F epoch=4 batch=2244/2350 step=2325 loss=0.3641 ce=0.2507 mse=0.2269 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1411175727844238, "reserved_gb": 1.705078125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "47", "gpu_mem_used_mb": "2157", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "69.71"}
2026-08-09 04:10:09 | INFO | train task=Ses03F epoch=4 batch=2344/2350 step=2350 loss=1.5676 ce=1.3691 mse=0.3970 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.140427589416504, "reserved_gb": 1.994140625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "48", "gpu_mem_used_mb": "2453", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "55.85"}

predict:   0%|          | 0/336 [00:00<?, ?it/s]

2026-08-09 04:10:31 | INFO | Epoch 04 task=Ses03F train_loss=1.0591 val_macro_f1=0.3912 val_mae=0.5750 epoch_seconds=494.0

epoch 5:   0%|          | 0/2350 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 04:10:52 | INFO | train task=Ses03F epoch=5 batch=92/2350 step=2375 loss=0.2604 ce=0.0660 mse=0.3887 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1406731605529785, "reserved_gb": 1.96875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "16", "gpu_mem_used_mb": "2427", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "61.41"}
2026-08-09 04:11:11 | INFO | train task=Ses03F epoch=5 batch=192/2350 step=2400 loss=1.0835 ce=0.6852 mse=0.7966 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1399555206298828, "reserved_gb": 2.140625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "30", "gpu_mem_used_mb": "2603", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "71.42"}
2026-08-09 04:11:33 | INFO | train task=Ses03F epoch=5 batch=292/2350 step=2425 loss=1.0972 ce=1.0675 mse=0.0593 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.140047550201416, "reserved_gb": 2.43359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "2903", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "66.72"}
2026-08-09 04:11:51 | INFO | train task=Ses03F epoch=5 batch=392/2350 step=2450 loss=0.1201 ce=0.1124 mse=0.0154 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.143545150756836, "reserved_gb": 2.04296875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "40", "gpu_mem_used_mb": "2557", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "61.29"}
2026-08-09 04:12:10 | INFO | train task=Ses03F epoch=5 batch=492/2350 step=2475 loss=1.7670 ce=1.2409 mse=1.0522 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1409344673156738, "reserved_gb": 2.078125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "2593", "gpu_mem_total_mb": "12288", "gpu_temp_c": "55", "gpu_power_w": "69.40"}
2026-08-09 04:12:29 | INFO | train task=Ses03F epoch=5 batch=592/2350 step=2500 loss=1.7558 ce=1.4482 mse=0.6154 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1400861740112305, "reserved_gb": 1.73046875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "40", "gpu_mem_used_mb": "2237", "gpu_mem_total_mb": "12288", "gpu_temp_c": "56", "gpu_power_w": "61.31"}
2026-08-09 04:12:52 | INFO | train task=Ses03F epoch=5 batch=692/2350 step=2525 loss=0.9328 ce=0.8579 mse=0.1498 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1405630111694336, "reserved_gb": 2.2578125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "25", "gpu_mem_used_mb": "2777", "gpu_mem_total_mb": "12288", "gpu_temp_c": "57", "gpu_power_w": "93.74"}
2026-08-09 04:13:11 | INFO | train task=Ses03F epoch=5 batch=792/2350 step=2550 loss=1.7171 ce=1.6711 mse=0.0920 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1400184631347656, "reserved_gb": 2.255859375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "11", "gpu_mem_used_mb": "2775", "gpu_mem_total_mb": "12288", "gpu_temp_c": "55", "gpu_power_w": "70.33"}
2026-08-09 04:13:30 | INFO | train task=Ses03F epoch=5 batch=892/2350 step=2575 loss=0.4030 ce=0.2694 mse=0.2672 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1400666236877441, "reserved_gb": 3.205078125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "23", "gpu_mem_used_mb": "3747", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "62.78"}
2026-08-09 04:13:49 | INFO | train task=Ses03F epoch=5 batch=992/2350 step=2600 loss=0.3981 ce=0.2996 mse=0.1971 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1404809951782227, "reserved_gb": 2.244140625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "2765", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "65.31"}
2026-08-09 04:14:11 | INFO | train task=Ses03F epoch=5 batch=1092/2350 step=2625 loss=0.4574 ce=0.3284 mse=0.2580 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.139937400817871, "reserved_gb": 1.7265625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "49", "gpu_mem_used_mb": "2235", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "72.87"}
2026-08-09 04:14:29 | INFO | train task=Ses03F epoch=5 batch=1192/2350 step=2650 loss=0.9778 ce=0.2791 mse=1.3974 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1400809288024902, "reserved_gb": 1.744140625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "2253", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "68.86"}
2026-08-09 04:14:49 | INFO | train task=Ses03F epoch=5 batch=1292/2350 step=2675 loss=0.4823 ce=0.3251 mse=0.3144 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1406073570251465, "reserved_gb": 2.37109375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "16", "gpu_mem_used_mb": "2895", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "72.59"}
2026-08-09 04:15:09 | INFO | train task=Ses03F epoch=5 batch=1392/2350 step=2700 loss=1.7008 ce=1.5274 mse=0.3468 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1405267715454102, "reserved_gb": 2.251953125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "18", "gpu_mem_used_mb": "2773", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "63.43"}
2026-08-09 04:15:30 | INFO | train task=Ses03F epoch=5 batch=1492/2350 step=2725 loss=0.4241 ce=0.2095 mse=0.4293 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1405515670776367, "reserved_gb": 2.2109375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "2731", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "52.72"}
2026-08-09 04:15:49 | INFO | train task=Ses03F epoch=5 batch=1592/2350 step=2750 loss=4.2120 ce=3.8557 mse=0.7127 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1404495239257812, "reserved_gb": 2.3984375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "30", "gpu_mem_used_mb": "2923", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "66.30"}
2026-08-09 04:16:08 | INFO | train task=Ses03F epoch=5 batch=1692/2350 step=2775 loss=0.1266 ce=0.1150 mse=0.0232 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1401729583740234, "reserved_gb": 2.318359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "30", "gpu_mem_used_mb": "2841", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "66.39"}
2026-08-09 04:16:27 | INFO | train task=Ses03F epoch=5 batch=1792/2350 step=2800 loss=1.0674 ce=1.0644 mse=0.0061 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1404671669006348, "reserved_gb": 2.103515625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "2621", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "67.65"}
2026-08-09 04:16:50 | INFO | train task=Ses03F epoch=5 batch=1892/2350 step=2825 loss=1.3574 ce=1.1636 mse=0.3877 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1406731605529785, "reserved_gb": 2.537109375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "3065", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "59.12"}
2026-08-09 04:17:10 | INFO | train task=Ses03F epoch=5 batch=1992/2350 step=2850 loss=0.5913 ce=0.4681 mse=0.2465 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1404995918273926, "reserved_gb": 1.74609375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "2257", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "57.37"}
2026-08-09 04:17:29 | INFO | train task=Ses03F epoch=5 batch=2092/2350 step=2875 loss=0.8518 ce=0.6221 mse=0.4595 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.140462875366211, "reserved_gb": 2.36328125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "26", "gpu_mem_used_mb": "2889", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "70.46"}
2026-08-09 04:17:49 | INFO | train task=Ses03F epoch=5 batch=2192/2350 step=2900 loss=0.4251 ce=0.2977 mse=0.2547 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1404690742492676, "reserved_gb": 1.78515625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "30", "gpu_mem_used_mb": "2297", "gpu_mem_total_mb": "12288", "gpu_temp_c": "44", "gpu_power_w": "44.33"}
2026-08-09 04:18:12 | INFO | train task=Ses03F epoch=5 batch=2292/2350 step=2925 loss=0.6158 ce=0.5940 mse=0.0437 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.144639015197754, "reserved_gb": 2.296875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "35", "gpu_mem_used_mb": "2821", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "70.21"}

predict:   0%|          | 0/336 [00:00<?, ?it/s]

2026-08-09 04:18:46 | INFO | Epoch 05 task=Ses03F train_loss=0.9261 val_macro_f1=0.3972 val_mae=0.5654 epoch_seconds=492.0

predict:   0%|          | 0/299 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)

predict:   0%|          | 0/369 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
2026-08-09 04:20:26 | INFO | Task 0695196ad49b8151_main_fold -> complete
2026-08-09 04:20:28 | INFO | Manuscript outputs refreshed: 21 tables, 4 figures
2026-08-09 04:20:28 | INFO | Task 96a7c942afc158a8_main_fold -> running
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\transformers\configuration_utils.py:335: UserWarning: Passing `gradient_checkpointing` to a config initialization is deprecated and will be removed in v5 Transformers. Using `model.gradient_checkpointing_enable()` instead, or if you are using the `Trainer` API, pass `gradient_checkpointing=True` in your `TrainingArguments`.
  warnings.warn(
2026-08-09 04:20:30 | INFO | Task C:\Users\HaseebWajid\Downloads\runs\dersx_paper_aligned\campaign_01\main\seed_13\Ses03M parameters={'total': 163009451, 'trainable': 69034283, 'frozen': 93975168} scope={'corpus': 'IEMOCAP', 'protocol': 'strict_LOSO', 'heldout_speaker': 'Ses03M', 'seed': 13, 'stage': 'main', 'profile': 'rtx3060_24h'}

epoch 1:   0%|          | 0/2350 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 04:20:52 | INFO | train task=Ses03M epoch=1 batch=100/2350 step=25 loss=2.7208 ce=2.1519 mse=1.1378 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1608004570007324, "reserved_gb": 1.763671875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "65", "gpu_mem_used_mb": "2274", "gpu_mem_total_mb": "12288", "gpu_temp_c": "53", "gpu_power_w": "73.53"}
2026-08-09 04:21:12 | INFO | train task=Ses03M epoch=1 batch=200/2350 step=50 loss=2.5555 ce=2.3311 mse=0.4488 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1601619720458984, "reserved_gb": 1.95703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "28", "gpu_mem_used_mb": "2472", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "74.14"}
2026-08-09 04:21:32 | INFO | train task=Ses03M epoch=1 batch=300/2350 step=75 loss=2.0964 ce=1.8938 mse=0.4051 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1589274406433105, "reserved_gb": 1.892578125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "14", "gpu_mem_used_mb": "2439", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "85.70"}
2026-08-09 04:21:54 | INFO | train task=Ses03M epoch=1 batch=400/2350 step=100 loss=2.7125 ce=2.1121 mse=1.2009 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.158571720123291, "reserved_gb": 1.8125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "28", "gpu_mem_used_mb": "2357", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "70.17"}
2026-08-09 04:22:18 | INFO | train task=Ses03M epoch=1 batch=500/2350 step=125 loss=2.7766 ce=2.0159 mse=1.5214 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1589317321777344, "reserved_gb": 1.818359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "58", "gpu_mem_used_mb": "2363", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "76.73"}
2026-08-09 04:22:38 | INFO | train task=Ses03M epoch=1 batch=600/2350 step=150 loss=2.4528 ce=2.0769 mse=0.7518 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.158217430114746, "reserved_gb": 1.75390625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "2297", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "66.59"}
2026-08-09 04:22:59 | INFO | train task=Ses03M epoch=1 batch=700/2350 step=175 loss=2.8134 ce=1.7676 mse=2.0917 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1589970588684082, "reserved_gb": 1.935546875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "2483", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "89.88"}
2026-08-09 04:23:20 | INFO | train task=Ses03M epoch=1 batch=800/2350 step=200 loss=1.9662 ce=1.8387 mse=0.2551 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.158729076385498, "reserved_gb": 1.7265625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "46", "gpu_mem_used_mb": "2269", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "71.76"}
2026-08-09 04:23:45 | INFO | train task=Ses03M epoch=1 batch=900/2350 step=225 loss=2.3181 ce=2.2669 mse=0.1024 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1589627265930176, "reserved_gb": 1.833984375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "27", "gpu_mem_used_mb": "2379", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "67.44"}
2026-08-09 04:24:06 | INFO | train task=Ses03M epoch=1 batch=1000/2350 step=250 loss=2.1993 ce=1.8106 mse=0.7773 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.158674716949463, "reserved_gb": 1.720703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "18", "gpu_mem_used_mb": "2263", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "63.61"}
2026-08-09 04:24:27 | INFO | train task=Ses03M epoch=1 batch=1100/2350 step=275 loss=2.0277 ce=1.7259 mse=0.6035 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1582980155944824, "reserved_gb": 1.861328125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "28", "gpu_mem_used_mb": "2407", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "85.80"}
2026-08-09 04:24:50 | INFO | train task=Ses03M epoch=1 batch=1200/2350 step=300 loss=1.5297 ce=1.0851 mse=0.8892 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1607460975646973, "reserved_gb": 1.744140625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "2287", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "68.49"}
2026-08-09 04:25:15 | INFO | train task=Ses03M epoch=1 batch=1300/2350 step=325 loss=1.5798 ce=1.4079 mse=0.3438 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1593151092529297, "reserved_gb": 1.818359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "57", "gpu_mem_used_mb": "2363", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "82.37"}
2026-08-09 04:25:39 | INFO | train task=Ses03M epoch=1 batch=1400/2350 step=350 loss=2.0886 ce=1.7573 mse=0.6625 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1587185859680176, "reserved_gb": 1.78125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "44", "gpu_mem_used_mb": "2325", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "71.70"}
2026-08-09 04:26:01 | INFO | train task=Ses03M epoch=1 batch=1500/2350 step=375 loss=1.5849 ce=1.4963 mse=0.1771 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1583805084228516, "reserved_gb": 1.958984375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "15", "gpu_mem_used_mb": "2507", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "64.51"}
2026-08-09 04:26:23 | INFO | train task=Ses03M epoch=1 batch=1600/2350 step=400 loss=2.4351 ce=1.7290 mse=1.4121 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1620378494262695, "reserved_gb": 1.763671875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "55", "gpu_mem_used_mb": "2307", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "73.43"}
2026-08-09 04:26:49 | INFO | train task=Ses03M epoch=1 batch=1700/2350 step=425 loss=1.8427 ce=1.8179 mse=0.0497 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1582112312316895, "reserved_gb": 1.72265625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "2265", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "82.45"}
2026-08-09 04:27:14 | INFO | train task=Ses03M epoch=1 batch=1800/2350 step=450 loss=0.7575 ce=0.6589 mse=0.1973 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.158801555633545, "reserved_gb": 1.783203125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "15", "gpu_mem_used_mb": "2327", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "84.68"}
2026-08-09 04:27:38 | INFO | train task=Ses03M epoch=1 batch=1900/2350 step=475 loss=2.9957 ce=1.5617 mse=2.8680 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.140653133392334, "reserved_gb": 1.84375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "26", "gpu_mem_used_mb": "2389", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "84.58"}
2026-08-09 04:28:01 | INFO | train task=Ses03M epoch=1 batch=2000/2350 step=500 loss=2.1325 ce=1.8831 mse=0.4988 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1420388221740723, "reserved_gb": 1.939453125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "43", "gpu_mem_used_mb": "2487", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "52.95"}
2026-08-09 04:28:28 | INFO | train task=Ses03M epoch=1 batch=2100/2350 step=525 loss=1.5240 ce=1.1047 mse=0.8386 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1409788131713867, "reserved_gb": 1.763671875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "49", "gpu_mem_used_mb": "2307", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "59.94"}
2026-08-09 04:28:52 | INFO | train task=Ses03M epoch=1 batch=2200/2350 step=550 loss=2.5084 ce=1.8542 mse=1.3084 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1406350135803223, "reserved_gb": 1.734375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "16", "gpu_mem_used_mb": "2277", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "71.56"}
2026-08-09 04:29:14 | INFO | train task=Ses03M epoch=1 batch=2300/2350 step=575 loss=1.2541 ce=1.0113 mse=0.4857 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1411595344543457, "reserved_gb": 1.775390625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "53", "gpu_mem_used_mb": "2319", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "92.31"}

predict:   0%|          | 0/336 [00:00<?, ?it/s]

2026-08-09 04:30:08 | INFO | Epoch 01 task=Ses03M train_loss=2.0425 val_macro_f1=0.3956 val_mae=0.6037 epoch_seconds=576.4

epoch 2:   0%|          | 0/2350 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 04:30:23 | INFO | train task=Ses03M epoch=2 batch=48/2350 step=600 loss=2.0852 ce=1.7973 mse=0.5758 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1424531936645508, "reserved_gb": 2.037109375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "39", "gpu_mem_used_mb": "2586", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "67.64"}
2026-08-09 04:30:46 | INFO | train task=Ses03M epoch=2 batch=148/2350 step=625 loss=0.7159 ce=0.7115 mse=0.0086 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1409296989440918, "reserved_gb": 1.693359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "27", "gpu_mem_used_mb": "2235", "gpu_mem_total_mb": "12288", "gpu_temp_c": "44", "gpu_power_w": "43.43"}
2026-08-09 04:31:08 | INFO | train task=Ses03M epoch=2 batch=248/2350 step=650 loss=1.0941 ce=0.6851 mse=0.8179 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1413087844848633, "reserved_gb": 1.736328125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "24", "gpu_mem_used_mb": "2279", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "75.07"}
2026-08-09 04:31:29 | INFO | train task=Ses03M epoch=2 batch=348/2350 step=675 loss=0.3491 ce=0.2927 mse=0.1128 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1408348083496094, "reserved_gb": 1.763671875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "36", "gpu_mem_used_mb": "2307", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "73.30"}
2026-08-09 04:31:49 | INFO | train task=Ses03M epoch=2 batch=448/2350 step=700 loss=0.7738 ce=0.4526 mse=0.6425 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.141427993774414, "reserved_gb": 1.75390625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "2301", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "71.96"}
2026-08-09 04:32:12 | INFO | train task=Ses03M epoch=2 batch=548/2350 step=725 loss=0.4124 ce=0.4119 mse=0.0011 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1432619094848633, "reserved_gb": 2.033203125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "29", "gpu_mem_used_mb": "2587", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "92.74"}
2026-08-09 04:32:32 | INFO | train task=Ses03M epoch=2 batch=648/2350 step=750 loss=1.3980 ce=1.3906 mse=0.0148 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1407356262207031, "reserved_gb": 1.787109375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "13", "gpu_mem_used_mb": "2335", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "62.40"}
2026-08-09 04:32:52 | INFO | train task=Ses03M epoch=2 batch=748/2350 step=775 loss=1.6830 ce=1.1499 mse=1.0662 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1425104141235352, "reserved_gb": 1.74609375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "46", "gpu_mem_used_mb": "2293", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "57.09"}
2026-08-09 04:33:12 | INFO | train task=Ses03M epoch=2 batch=848/2350 step=800 loss=2.7590 ce=2.6660 mse=0.1860 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1405787467956543, "reserved_gb": 1.68359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "2229", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "60.86"}
2026-08-09 04:33:36 | INFO | train task=Ses03M epoch=2 batch=948/2350 step=825 loss=0.6751 ce=0.6566 mse=0.0372 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1410164833068848, "reserved_gb": 2.07421875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "2629", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "72.49"}
2026-08-09 04:33:55 | INFO | train task=Ses03M epoch=2 batch=1048/2350 step=850 loss=0.8166 ce=0.4665 mse=0.7001 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1414680480957031, "reserved_gb": 1.845703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "2395", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "59.64"}
2026-08-09 04:34:14 | INFO | train task=Ses03M epoch=2 batch=1148/2350 step=875 loss=0.8082 ce=0.6613 mse=0.2939 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1418437957763672, "reserved_gb": 1.771484375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "33", "gpu_mem_used_mb": "2319", "gpu_mem_total_mb": "12288", "gpu_temp_c": "44", "gpu_power_w": "46.31"}
2026-08-09 04:34:34 | INFO | train task=Ses03M epoch=2 batch=1248/2350 step=900 loss=0.4827 ce=0.3041 mse=0.3573 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.144456386566162, "reserved_gb": 2.71484375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "54", "gpu_mem_used_mb": "3285", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "74.83"}
2026-08-09 04:34:57 | INFO | train task=Ses03M epoch=2 batch=1348/2350 step=925 loss=0.8318 ce=0.6364 mse=0.3908 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1414308547973633, "reserved_gb": 1.705078125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "46", "gpu_mem_used_mb": "2251", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "65.58"}
2026-08-09 04:35:17 | INFO | train task=Ses03M epoch=2 batch=1448/2350 step=950 loss=1.3584 ce=0.9562 mse=0.8044 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1406683921813965, "reserved_gb": 1.703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "32", "gpu_mem_used_mb": "2249", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "65.87"}
2026-08-09 04:35:36 | INFO | train task=Ses03M epoch=2 batch=1548/2350 step=975 loss=1.3207 ce=1.0546 mse=0.5320 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1407771110534668, "reserved_gb": 1.958984375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "34", "gpu_mem_used_mb": "2511", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "68.81"}
2026-08-09 04:35:56 | INFO | train task=Ses03M epoch=2 batch=1648/2350 step=1000 loss=1.9208 ce=1.5318 mse=0.7780 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1422443389892578, "reserved_gb": 2.58203125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "49", "gpu_mem_used_mb": "3149", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "68.17"}
2026-08-09 04:36:19 | INFO | train task=Ses03M epoch=2 batch=1748/2350 step=1025 loss=0.8691 ce=0.8628 mse=0.0126 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1411056518554688, "reserved_gb": 2.359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "2921", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "66.35"}
2026-08-09 04:36:39 | INFO | train task=Ses03M epoch=2 batch=1848/2350 step=1050 loss=0.5290 ce=0.3466 mse=0.3648 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1417479515075684, "reserved_gb": 2.251953125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "54", "gpu_mem_used_mb": "2811", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "69.40"}
2026-08-09 04:36:57 | INFO | train task=Ses03M epoch=2 batch=1948/2350 step=1075 loss=0.9910 ce=0.9556 mse=0.0707 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1431961059570312, "reserved_gb": 1.7421875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "35", "gpu_mem_used_mb": "2289", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "71.44"}
2026-08-09 04:37:16 | INFO | train task=Ses03M epoch=2 batch=2048/2350 step=1100 loss=2.1064 ce=1.5849 mse=1.0429 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.140829086303711, "reserved_gb": 1.83203125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "23", "gpu_mem_used_mb": "2381", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "64.45"}
2026-08-09 04:37:39 | INFO | train task=Ses03M epoch=2 batch=2148/2350 step=1125 loss=0.8167 ce=0.8029 mse=0.0275 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.142165184020996, "reserved_gb": 1.787109375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "55", "gpu_mem_used_mb": "2335", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "66.28"}
2026-08-09 04:37:59 | INFO | train task=Ses03M epoch=2 batch=2248/2350 step=1150 loss=1.8069 ce=1.0741 mse=1.4656 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.142530918121338, "reserved_gb": 1.78515625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "63", "gpu_mem_used_mb": "2333", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "63.67"}
2026-08-09 04:38:19 | INFO | train task=Ses03M epoch=2 batch=2348/2350 step=1175 loss=1.1238 ce=1.0412 mse=0.1651 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.140599250793457, "reserved_gb": 2.625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "25", "gpu_mem_used_mb": "3193", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "65.78"}

predict:   0%|          | 0/336 [00:00<?, ?it/s]

2026-08-09 04:38:42 | INFO | Epoch 02 task=Ses03M train_loss=1.4601 val_macro_f1=0.3843 val_mae=0.5729 epoch_seconds=509.2

epoch 3:   0%|          | 0/2350 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 04:39:03 | INFO | train task=Ses03M epoch=3 batch=96/2350 step=1200 loss=0.7441 ce=0.6256 mse=0.2368 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.140897274017334, "reserved_gb": 1.994140625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "16", "gpu_mem_used_mb": "2547", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "62.46"}
2026-08-09 04:39:25 | INFO | train task=Ses03M epoch=3 batch=196/2350 step=1225 loss=1.3462 ce=1.3131 mse=0.0662 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.140761375427246, "reserved_gb": 2.33203125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "35", "gpu_mem_used_mb": "2893", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "56.68"}
2026-08-09 04:39:44 | INFO | train task=Ses03M epoch=3 batch=296/2350 step=1250 loss=2.8536 ce=2.1793 mse=1.3487 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1407217979431152, "reserved_gb": 2.310546875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "27", "gpu_mem_used_mb": "2871", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "75.57"}
2026-08-09 04:40:03 | INFO | train task=Ses03M epoch=3 batch=396/2350 step=1275 loss=1.2634 ce=0.9637 mse=0.5993 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.146092414855957, "reserved_gb": 2.322265625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "16", "gpu_mem_used_mb": "2883", "gpu_mem_total_mb": "12288", "gpu_temp_c": "53", "gpu_power_w": "70.79"}
2026-08-09 04:40:21 | INFO | train task=Ses03M epoch=3 batch=496/2350 step=1300 loss=0.8885 ce=0.8557 mse=0.0656 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1408772468566895, "reserved_gb": 2.203125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "19", "gpu_mem_used_mb": "2761", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "45.24"}
2026-08-09 04:40:44 | INFO | train task=Ses03M epoch=3 batch=596/2350 step=1325 loss=0.6012 ce=0.4290 mse=0.3445 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1407661437988281, "reserved_gb": 1.732421875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "80", "gpu_mem_used_mb": "2365", "gpu_mem_total_mb": "12288", "gpu_temp_c": "59", "gpu_power_w": "74.27"}
2026-08-09 04:41:03 | INFO | train task=Ses03M epoch=3 batch=696/2350 step=1350 loss=0.7459 ce=0.6570 mse=0.1779 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.140578269958496, "reserved_gb": 1.841796875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "78", "gpu_mem_used_mb": "2505", "gpu_mem_total_mb": "12288", "gpu_temp_c": "57", "gpu_power_w": "94.46"}
2026-08-09 04:41:22 | INFO | train task=Ses03M epoch=3 batch=796/2350 step=1375 loss=2.5124 ce=1.6706 mse=1.6836 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1408610343933105, "reserved_gb": 1.751953125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "59", "gpu_mem_used_mb": "2345", "gpu_mem_total_mb": "12288", "gpu_temp_c": "56", "gpu_power_w": "89.95"}
2026-08-09 04:41:41 | INFO | train task=Ses03M epoch=3 batch=896/2350 step=1400 loss=0.9848 ce=0.7874 mse=0.3949 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1410608291625977, "reserved_gb": 2.00390625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "2602", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "67.75"}
2026-08-09 04:42:03 | INFO | train task=Ses03M epoch=3 batch=996/2350 step=1425 loss=0.7963 ce=0.3350 mse=0.9225 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1417555809020996, "reserved_gb": 1.98046875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "8", "gpu_mem_used_mb": "2580", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "64.53"}
2026-08-09 04:42:22 | INFO | train task=Ses03M epoch=3 batch=1096/2350 step=1450 loss=2.1563 ce=2.0384 mse=0.2357 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1415915489196777, "reserved_gb": 1.775390625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "23", "gpu_mem_used_mb": "2370", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "72.13"}
2026-08-09 04:42:41 | INFO | train task=Ses03M epoch=3 batch=1196/2350 step=1475 loss=4.0988 ce=3.9972 mse=0.2032 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1459312438964844, "reserved_gb": 2.591796875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "18", "gpu_mem_used_mb": "3206", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "78.14"}
2026-08-09 04:42:59 | INFO | train task=Ses03M epoch=3 batch=1296/2350 step=1500 loss=0.5107 ce=0.2208 mse=0.5798 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1415095329284668, "reserved_gb": 2.22265625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "31", "gpu_mem_used_mb": "2828", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "66.17"}
2026-08-09 04:43:21 | INFO | train task=Ses03M epoch=3 batch=1396/2350 step=1525 loss=3.1540 ce=3.1513 mse=0.0054 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.142268180847168, "reserved_gb": 1.841796875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "37", "gpu_mem_used_mb": "2433", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "66.63"}
2026-08-09 04:43:41 | INFO | train task=Ses03M epoch=3 batch=1496/2350 step=1550 loss=1.4860 ce=1.2343 mse=0.5033 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1424503326416016, "reserved_gb": 1.97265625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "24", "gpu_mem_used_mb": "2637", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "61.72"}
2026-08-09 04:44:00 | INFO | train task=Ses03M epoch=3 batch=1596/2350 step=1575 loss=1.1952 ce=1.0819 mse=0.2266 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1409344673156738, "reserved_gb": 1.72265625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "26", "gpu_mem_used_mb": "2391", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "45.52"}
2026-08-09 04:44:20 | INFO | train task=Ses03M epoch=3 batch=1696/2350 step=1600 loss=2.9459 ce=2.6388 mse=0.6143 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.140899658203125, "reserved_gb": 2.05859375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "25", "gpu_mem_used_mb": "2671", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "59.32"}
2026-08-09 04:44:42 | INFO | train task=Ses03M epoch=3 batch=1796/2350 step=1625 loss=0.4036 ce=0.3624 mse=0.0824 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1414775848388672, "reserved_gb": 1.796875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "28", "gpu_mem_used_mb": "2443", "gpu_mem_total_mb": "12288", "gpu_temp_c": "43", "gpu_power_w": "42.26"}
2026-08-09 04:45:02 | INFO | train task=Ses03M epoch=3 batch=1896/2350 step=1650 loss=0.3862 ce=0.3441 mse=0.0841 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1421689987182617, "reserved_gb": 1.7265625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "57", "gpu_mem_used_mb": "2377", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "67.46"}
2026-08-09 04:45:23 | INFO | train task=Ses03M epoch=3 batch=1996/2350 step=1675 loss=0.5568 ce=0.4641 mse=0.1854 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1405525207519531, "reserved_gb": 2.14453125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "39", "gpu_mem_used_mb": "2747", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "63.16"}
2026-08-09 04:45:44 | INFO | train task=Ses03M epoch=3 batch=2096/2350 step=1700 loss=1.8155 ce=0.7145 mse=2.2020 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.141037940979004, "reserved_gb": 1.73046875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "32", "gpu_mem_used_mb": "2324", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "67.48"}
2026-08-09 04:46:06 | INFO | train task=Ses03M epoch=3 batch=2196/2350 step=1725 loss=1.2697 ce=0.9927 mse=0.5541 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.141075611114502, "reserved_gb": 1.701171875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "36", "gpu_mem_used_mb": "2297", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "61.96"}
2026-08-09 04:46:25 | INFO | train task=Ses03M epoch=3 batch=2296/2350 step=1750 loss=3.3348 ce=3.0543 mse=0.5609 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1425786018371582, "reserved_gb": 2.15625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "15", "gpu_mem_used_mb": "2763", "gpu_mem_total_mb": "12288", "gpu_temp_c": "44", "gpu_power_w": "45.92"}

predict:   0%|          | 0/336 [00:00<?, ?it/s]

2026-08-09 04:46:57 | INFO | Epoch 03 task=Ses03M train_loss=1.2261 val_macro_f1=0.4165 val_mae=0.5824 epoch_seconds=491.4

epoch 4:   0%|          | 0/2350 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 04:47:12 | INFO | train task=Ses03M epoch=4 batch=44/2350 step=1775 loss=2.1912 ce=2.0401 mse=0.3022 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.140829086303711, "reserved_gb": 2.04296875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "13", "gpu_mem_used_mb": "2646", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "80.28"}
2026-08-09 04:47:30 | INFO | train task=Ses03M epoch=4 batch=144/2350 step=1800 loss=2.0180 ce=1.8458 mse=0.3445 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.141876220703125, "reserved_gb": 2.287109375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "59", "gpu_mem_used_mb": "2896", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "54.74"}
2026-08-09 04:47:52 | INFO | train task=Ses03M epoch=4 batch=244/2350 step=1825 loss=0.3719 ce=0.1817 mse=0.3803 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1412653923034668, "reserved_gb": 1.794921875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "18", "gpu_mem_used_mb": "2454", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "88.58"}
2026-08-09 04:48:11 | INFO | train task=Ses03M epoch=4 batch=344/2350 step=1850 loss=1.6966 ce=1.2121 mse=0.9689 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.140629768371582, "reserved_gb": 1.83203125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "28", "gpu_mem_used_mb": "2631", "gpu_mem_total_mb": "12288", "gpu_temp_c": "54", "gpu_power_w": "94.41"}
2026-08-09 04:48:33 | INFO | train task=Ses03M epoch=4 batch=444/2350 step=1875 loss=0.7353 ce=0.5351 mse=0.4004 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1413836479187012, "reserved_gb": 1.697265625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "44", "gpu_mem_used_mb": "2320", "gpu_mem_total_mb": "12288", "gpu_temp_c": "56", "gpu_power_w": "69.54"}
2026-08-09 04:48:52 | INFO | train task=Ses03M epoch=4 batch=544/2350 step=1900 loss=1.4480 ce=0.4749 mse=1.9461 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1411075592041016, "reserved_gb": 2.220703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "15", "gpu_mem_used_mb": "2874", "gpu_mem_total_mb": "12288", "gpu_temp_c": "55", "gpu_power_w": "65.04"}
2026-08-09 04:49:16 | INFO | train task=Ses03M epoch=4 batch=644/2350 step=1925 loss=0.6169 ce=0.4963 mse=0.2412 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1415343284606934, "reserved_gb": 2.4453125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "73", "gpu_mem_used_mb": "3230", "gpu_mem_total_mb": "12288", "gpu_temp_c": "59", "gpu_power_w": "75.51"}
2026-08-09 04:49:35 | INFO | train task=Ses03M epoch=4 batch=744/2350 step=1950 loss=0.5236 ce=0.3351 mse=0.3771 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1406135559082031, "reserved_gb": 1.78125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "26", "gpu_mem_used_mb": "2389", "gpu_mem_total_mb": "12288", "gpu_temp_c": "55", "gpu_power_w": "80.84"}
2026-08-09 04:49:54 | INFO | train task=Ses03M epoch=4 batch=844/2350 step=1975 loss=0.9892 ce=0.9066 mse=0.1652 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1412324905395508, "reserved_gb": 1.787109375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "16", "gpu_mem_used_mb": "2423", "gpu_mem_total_mb": "12288", "gpu_temp_c": "53", "gpu_power_w": "76.35"}
2026-08-09 04:50:13 | INFO | train task=Ses03M epoch=4 batch=944/2350 step=2000 loss=0.2409 ce=0.1542 mse=0.1733 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1407990455627441, "reserved_gb": 1.763671875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "26", "gpu_mem_used_mb": "2437", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "46.06"}
2026-08-09 04:50:34 | INFO | train task=Ses03M epoch=4 batch=1044/2350 step=2025 loss=0.8410 ce=0.5932 mse=0.4955 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1416206359863281, "reserved_gb": 2.2578125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "2890", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "72.15"}
2026-08-09 04:50:52 | INFO | train task=Ses03M epoch=4 batch=1144/2350 step=2050 loss=0.4454 ce=0.3506 mse=0.1897 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1420297622680664, "reserved_gb": 2.236328125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "2841", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "61.84"}
2026-08-09 04:51:11 | INFO | train task=Ses03M epoch=4 batch=1244/2350 step=2075 loss=0.6728 ce=0.5844 mse=0.1769 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1405820846557617, "reserved_gb": 1.826171875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "28", "gpu_mem_used_mb": "2422", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "45.20"}
2026-08-09 04:51:30 | INFO | train task=Ses03M epoch=4 batch=1344/2350 step=2100 loss=0.4808 ce=0.3291 mse=0.3033 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1405105590820312, "reserved_gb": 2.0078125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "28", "gpu_mem_used_mb": "2616", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "64.74"}
2026-08-09 04:51:52 | INFO | train task=Ses03M epoch=4 batch=1444/2350 step=2125 loss=0.6276 ce=0.5740 mse=0.1071 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1405768394470215, "reserved_gb": 2.009765625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "14", "gpu_mem_used_mb": "2617", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "65.29"}
2026-08-09 04:52:12 | INFO | train task=Ses03M epoch=4 batch=1544/2350 step=2150 loss=1.0475 ce=1.0403 mse=0.0144 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1411314010620117, "reserved_gb": 1.78515625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "34", "gpu_mem_used_mb": "2384", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "57.55"}
2026-08-09 04:52:30 | INFO | train task=Ses03M epoch=4 batch=1644/2350 step=2175 loss=2.2720 ce=2.2109 mse=0.1221 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.140838623046875, "reserved_gb": 1.744140625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "67", "gpu_mem_used_mb": "2342", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "60.48"}
2026-08-09 04:52:51 | INFO | train task=Ses03M epoch=4 batch=1744/2350 step=2200 loss=0.2627 ce=0.2363 mse=0.0528 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1423625946044922, "reserved_gb": 1.833984375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "25", "gpu_mem_used_mb": "2434", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "61.27"}
2026-08-09 04:53:12 | INFO | train task=Ses03M epoch=4 batch=1844/2350 step=2225 loss=0.5999 ce=0.4314 mse=0.3370 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1440110206604004, "reserved_gb": 2.3125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "35", "gpu_mem_used_mb": "2936", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "76.31"}
2026-08-09 04:53:30 | INFO | train task=Ses03M epoch=4 batch=1944/2350 step=2250 loss=0.4087 ce=0.2980 mse=0.2213 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1411476135253906, "reserved_gb": 1.865234375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "44", "gpu_mem_used_mb": "2477", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "64.98"}
2026-08-09 04:53:50 | INFO | train task=Ses03M epoch=4 batch=2044/2350 step=2275 loss=1.4378 ce=1.4332 mse=0.0091 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1424646377563477, "reserved_gb": 1.990234375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "14", "gpu_mem_used_mb": "2615", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "66.08"}
2026-08-09 04:54:10 | INFO | train task=Ses03M epoch=4 batch=2144/2350 step=2300 loss=2.2793 ce=2.0917 mse=0.3753 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1406512260437012, "reserved_gb": 1.771484375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "47", "gpu_mem_used_mb": "2370", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "70.59"}
2026-08-09 04:54:33 | INFO | train task=Ses03M epoch=4 batch=2244/2350 step=2325 loss=0.7821 ce=0.6933 mse=0.1776 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1417202949523926, "reserved_gb": 1.701171875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "64", "gpu_mem_used_mb": "2298", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "65.09"}
2026-08-09 04:54:53 | INFO | train task=Ses03M epoch=4 batch=2344/2350 step=2350 loss=1.2819 ce=1.0949 mse=0.3740 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1410303115844727, "reserved_gb": 2.013671875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "26", "gpu_mem_used_mb": "2639", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "66.81"}

predict:   0%|          | 0/336 [00:00<?, ?it/s]

2026-08-09 04:55:17 | INFO | Epoch 04 task=Ses03M train_loss=1.0721 val_macro_f1=0.4114 val_mae=0.5769 epoch_seconds=495.3

epoch 5:   0%|          | 0/2350 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 04:55:38 | INFO | train task=Ses03M epoch=5 batch=92/2350 step=2375 loss=0.1415 ce=0.0713 mse=0.1404 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1412758827209473, "reserved_gb": 1.95703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "2580", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "67.34"}
2026-08-09 04:55:57 | INFO | train task=Ses03M epoch=5 batch=192/2350 step=2400 loss=1.5983 ce=1.2800 mse=0.6365 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1405582427978516, "reserved_gb": 2.13671875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "31", "gpu_mem_used_mb": "2746", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "71.40"}
2026-08-09 04:56:21 | INFO | train task=Ses03M epoch=5 batch=292/2350 step=2425 loss=1.1199 ce=1.0609 mse=0.1179 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1406502723693848, "reserved_gb": 2.3984375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "3014", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "63.45"}
2026-08-09 04:56:39 | INFO | train task=Ses03M epoch=5 batch=392/2350 step=2450 loss=0.1909 ce=0.0891 mse=0.2035 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.143056869506836, "reserved_gb": 2.00390625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "36", "gpu_mem_used_mb": "2610", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "62.86"}
2026-08-09 04:56:57 | INFO | train task=Ses03M epoch=5 batch=492/2350 step=2475 loss=1.3946 ce=0.9388 mse=0.9117 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1415371894836426, "reserved_gb": 2.07421875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "42", "gpu_mem_used_mb": "2682", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "68.21"}
2026-08-09 04:57:16 | INFO | train task=Ses03M epoch=5 batch=592/2350 step=2500 loss=1.9180 ce=1.5883 mse=0.6593 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1406888961791992, "reserved_gb": 1.728515625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "25", "gpu_mem_used_mb": "2328", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "71.19"}
2026-08-09 04:57:38 | INFO | train task=Ses03M epoch=5 batch=692/2350 step=2525 loss=1.0833 ce=1.0794 mse=0.0079 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1411657333374023, "reserved_gb": 2.310546875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "35", "gpu_mem_used_mb": "2938", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "68.76"}
2026-08-09 04:57:58 | INFO | train task=Ses03M epoch=5 batch=792/2350 step=2550 loss=1.4166 ce=1.3295 mse=0.1742 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1406211853027344, "reserved_gb": 2.2734375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "16", "gpu_mem_used_mb": "2900", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "69.97"}
2026-08-09 04:58:17 | INFO | train task=Ses03M epoch=5 batch=892/2350 step=2575 loss=0.4774 ce=0.3235 mse=0.3078 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.140669345855713, "reserved_gb": 3.201171875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "24", "gpu_mem_used_mb": "3849", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "67.54"}
2026-08-09 04:58:36 | INFO | train task=Ses03M epoch=5 batch=992/2350 step=2600 loss=0.1413 ce=0.1091 mse=0.0644 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1410837173461914, "reserved_gb": 2.2421875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "30", "gpu_mem_used_mb": "2872", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "67.03"}
2026-08-09 04:58:59 | INFO | train task=Ses03M epoch=5 batch=1092/2350 step=2625 loss=0.2827 ce=0.0767 mse=0.4120 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1405401229858398, "reserved_gb": 1.72265625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "74", "gpu_mem_used_mb": "2334", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "76.28"}
2026-08-09 04:59:18 | INFO | train task=Ses03M epoch=5 batch=1192/2350 step=2650 loss=1.0255 ce=0.4013 mse=1.2484 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.140683650970459, "reserved_gb": 1.734375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "18", "gpu_mem_used_mb": "2330", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "67.42"}
2026-08-09 04:59:37 | INFO | train task=Ses03M epoch=5 batch=1292/2350 step=2675 loss=1.1147 ce=1.0509 mse=0.1276 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1412100791931152, "reserved_gb": 2.38671875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "24", "gpu_mem_used_mb": "3077", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "74.49"}
2026-08-09 04:59:57 | INFO | train task=Ses03M epoch=5 batch=1392/2350 step=2700 loss=1.3511 ce=1.1833 mse=0.3354 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.141129493713379, "reserved_gb": 2.232421875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "15", "gpu_mem_used_mb": "2857", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "53.75"}
2026-08-09 05:00:19 | INFO | train task=Ses03M epoch=5 batch=1492/2350 step=2725 loss=0.4847 ce=0.2912 mse=0.3871 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1411542892456055, "reserved_gb": 2.2109375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "2818", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "53.13"}
2026-08-09 05:00:38 | INFO | train task=Ses03M epoch=5 batch=1592/2350 step=2750 loss=3.4874 ce=3.1485 mse=0.6778 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.14105224609375, "reserved_gb": 2.40234375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "41", "gpu_mem_used_mb": "3032", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "68.38"}
2026-08-09 05:00:56 | INFO | train task=Ses03M epoch=5 batch=1692/2350 step=2775 loss=0.1997 ce=0.1876 mse=0.0242 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1407756805419922, "reserved_gb": 2.3125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "24", "gpu_mem_used_mb": "3017", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "66.63"}
2026-08-09 05:01:16 | INFO | train task=Ses03M epoch=5 batch=1792/2350 step=2800 loss=0.8460 ce=0.8366 mse=0.0189 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1410698890686035, "reserved_gb": 2.0625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "2699", "gpu_mem_total_mb": "12288", "gpu_temp_c": "44", "gpu_power_w": "63.05"}
2026-08-09 05:01:39 | INFO | train task=Ses03M epoch=5 batch=1892/2350 step=2825 loss=1.6520 ce=1.1045 mse=1.0951 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1412758827209473, "reserved_gb": 2.53515625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "15", "gpu_mem_used_mb": "3180", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "53.90"}
2026-08-09 05:01:58 | INFO | train task=Ses03M epoch=5 batch=1992/2350 step=2850 loss=1.4192 ce=1.2996 mse=0.2393 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1411023139953613, "reserved_gb": 1.787109375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "30", "gpu_mem_used_mb": "2414", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "58.64"}
2026-08-09 05:02:17 | INFO | train task=Ses03M epoch=5 batch=2092/2350 step=2875 loss=0.6209 ce=0.4530 mse=0.3358 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1410655975341797, "reserved_gb": 2.294921875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "2933", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "76.93"}
2026-08-09 05:02:37 | INFO | train task=Ses03M epoch=5 batch=2192/2350 step=2900 loss=0.2838 ce=0.1681 mse=0.2314 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1410717964172363, "reserved_gb": 1.7890625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "13", "gpu_mem_used_mb": "2415", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "53.99"}
2026-08-09 05:03:00 | INFO | train task=Ses03M epoch=5 batch=2292/2350 step=2925 loss=0.9180 ce=0.8381 mse=0.1598 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.146092414855957, "reserved_gb": 2.353515625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "30", "gpu_mem_used_mb": "2993", "gpu_mem_total_mb": "12288", "gpu_temp_c": "55", "gpu_power_w": "77.19"}

predict:   0%|          | 0/336 [00:00<?, ?it/s]

2026-08-09 05:03:33 | INFO | Epoch 05 task=Ses03M train_loss=0.9357 val_macro_f1=0.4110 val_mae=0.5574 epoch_seconds=493.0

predict:   0%|          | 0/299 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)

predict:   0%|          | 0/413 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
2026-08-09 05:05:19 | INFO | Task 96a7c942afc158a8_main_fold -> complete
2026-08-09 05:05:21 | INFO | Manuscript outputs refreshed: 21 tables, 4 figures
2026-08-09 05:05:21 | INFO | Task fbe86de81535c0cc_main_fold -> running
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\transformers\configuration_utils.py:335: UserWarning: Passing `gradient_checkpointing` to a config initialization is deprecated and will be removed in v5 Transformers. Using `model.gradient_checkpointing_enable()` instead, or if you are using the `Trainer` API, pass `gradient_checkpointing=True` in your `TrainingArguments`.
  warnings.warn(
2026-08-09 05:05:23 | INFO | Task C:\Users\HaseebWajid\Downloads\runs\dersx_paper_aligned\campaign_01\main\seed_13\Ses04F parameters={'total': 163009451, 'trainable': 69034283, 'frozen': 93975168} scope={'corpus': 'IEMOCAP', 'protocol': 'strict_LOSO', 'heldout_speaker': 'Ses04F', 'seed': 13, 'stage': 'main', 'profile': 'rtx3060_24h'}

epoch 1:   0%|          | 0/2405 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 05:05:48 | INFO | train task=Ses04F epoch=1 batch=100/2405 step=25 loss=2.6226 ce=2.0615 mse=1.1221 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2619714736938477, "reserved_gb": 2.869140625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "3467", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "71.84"}
2026-08-09 05:06:11 | INFO | train task=Ses04F epoch=1 batch=200/2405 step=50 loss=2.6394 ce=2.2529 mse=0.7730 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.26239013671875, "reserved_gb": 2.9296875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "3529", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "70.05"}
2026-08-09 05:06:34 | INFO | train task=Ses04F epoch=1 batch=300/2405 step=75 loss=2.4169 ce=2.1492 mse=0.5354 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.264340877532959, "reserved_gb": 2.89453125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "23", "gpu_mem_used_mb": "3492", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "68.11"}
2026-08-09 05:06:56 | INFO | train task=Ses04F epoch=1 batch=400/2405 step=100 loss=3.0493 ce=2.2700 mse=1.5585 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.261507511138916, "reserved_gb": 2.908203125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "27", "gpu_mem_used_mb": "3506", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "72.86"}
2026-08-09 05:07:24 | INFO | train task=Ses04F epoch=1 batch=500/2405 step=125 loss=3.1952 ce=1.9888 mse=2.4129 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2625179290771484, "reserved_gb": 2.837890625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "47", "gpu_mem_used_mb": "3434", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "78.86"}
2026-08-09 05:07:48 | INFO | train task=Ses04F epoch=1 batch=600/2405 step=150 loss=2.0473 ce=2.0280 mse=0.0385 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2618322372436523, "reserved_gb": 2.869140625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "33", "gpu_mem_used_mb": "3466", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "71.43"}
2026-08-09 05:08:11 | INFO | train task=Ses04F epoch=1 batch=700/2405 step=175 loss=2.2945 ce=2.2634 mse=0.0621 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2616639137268066, "reserved_gb": 3.029296875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "16", "gpu_mem_used_mb": "3630", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "68.07"}
2026-08-09 05:08:33 | INFO | train task=Ses04F epoch=1 batch=800/2405 step=200 loss=1.9762 ce=1.8017 mse=0.3490 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2626261711120605, "reserved_gb": 2.89453125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "97", "gpu_mem_used_mb": "3492", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "85.55"}
2026-08-09 05:09:00 | INFO | train task=Ses04F epoch=1 batch=900/2405 step=225 loss=2.0417 ce=1.8566 mse=0.3702 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.261629104614258, "reserved_gb": 2.91015625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "33", "gpu_mem_used_mb": "3507", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "67.45"}
2026-08-09 05:09:23 | INFO | train task=Ses04F epoch=1 batch=1000/2405 step=250 loss=1.7506 ce=1.6812 mse=0.1388 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.268156051635742, "reserved_gb": 3.63671875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "4251", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "69.93"}
2026-08-09 05:09:47 | INFO | train task=Ses04F epoch=1 batch=1100/2405 step=275 loss=1.2381 ce=1.1416 mse=0.1931 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2615432739257812, "reserved_gb": 2.853515625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "27", "gpu_mem_used_mb": "3449", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "70.85"}
2026-08-09 05:10:12 | INFO | train task=Ses04F epoch=1 batch=1200/2405 step=300 loss=1.2880 ce=1.1826 mse=0.2108 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2626423835754395, "reserved_gb": 2.859375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "29", "gpu_mem_used_mb": "3463", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "73.01"}
2026-08-09 05:10:38 | INFO | train task=Ses04F epoch=1 batch=1300/2405 step=325 loss=1.9630 ce=1.4471 mse=1.0318 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.267202854156494, "reserved_gb": 3.376953125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "54", "gpu_mem_used_mb": "3993", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "83.35"}
2026-08-09 05:11:01 | INFO | train task=Ses04F epoch=1 batch=1400/2405 step=350 loss=1.6280 ce=1.6109 mse=0.0341 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.261554718017578, "reserved_gb": 2.875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "3479", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "78.64"}
2026-08-09 05:11:26 | INFO | train task=Ses04F epoch=1 batch=1500/2405 step=375 loss=1.4239 ce=1.1992 mse=0.4493 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.264491558074951, "reserved_gb": 2.89453125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "26", "gpu_mem_used_mb": "3499", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "78.85"}
2026-08-09 05:11:51 | INFO | train task=Ses04F epoch=1 batch=1600/2405 step=400 loss=2.1929 ce=1.7264 mse=0.9330 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2619400024414062, "reserved_gb": 2.869140625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "48", "gpu_mem_used_mb": "3472", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "64.92"}
2026-08-09 05:12:17 | INFO | train task=Ses04F epoch=1 batch=1700/2405 step=425 loss=1.8975 ce=1.6229 mse=0.5490 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2621278762817383, "reserved_gb": 2.814453125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "29", "gpu_mem_used_mb": "3416", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "70.60"}
2026-08-09 05:12:40 | INFO | train task=Ses04F epoch=1 batch=1800/2405 step=450 loss=1.0873 ce=0.9451 mse=0.2844 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2629880905151367, "reserved_gb": 2.859375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "3462", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "65.67"}
2026-08-09 05:13:04 | INFO | train task=Ses04F epoch=1 batch=1900/2405 step=475 loss=1.7712 ce=1.6098 mse=0.3228 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2619333267211914, "reserved_gb": 2.90625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "26", "gpu_mem_used_mb": "3510", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "68.78"}
2026-08-09 05:13:28 | INFO | train task=Ses04F epoch=1 batch=2000/2405 step=500 loss=1.9812 ce=1.6434 mse=0.6756 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2616806030273438, "reserved_gb": 3.01953125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "24", "gpu_mem_used_mb": "3626", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "79.31"}
2026-08-09 05:13:55 | INFO | train task=Ses04F epoch=1 batch=2100/2405 step=525 loss=1.6919 ce=1.0447 mse=1.2945 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.261956214904785, "reserved_gb": 2.875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "36", "gpu_mem_used_mb": "3477", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "73.86"}
2026-08-09 05:14:19 | INFO | train task=Ses04F epoch=1 batch=2200/2405 step=550 loss=1.0425 ce=1.0407 mse=0.0035 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2623648643493652, "reserved_gb": 2.92578125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "30", "gpu_mem_used_mb": "3529", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "61.78"}
2026-08-09 05:14:42 | INFO | train task=Ses04F epoch=1 batch=2300/2405 step=575 loss=1.3012 ce=1.1089 mse=0.3845 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2628965377807617, "reserved_gb": 2.8515625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "66", "gpu_mem_used_mb": "3453", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "77.01"}
2026-08-09 05:15:07 | INFO | train task=Ses04F epoch=1 batch=2400/2405 step=600 loss=2.2755 ce=2.2242 mse=0.1026 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.262247085571289, "reserved_gb": 2.857421875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "3459", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "64.98"}

predict:   0%|          | 0/328 [00:00<?, ?it/s]

2026-08-09 05:15:59 | INFO | Epoch 01 task=Ses04F train_loss=2.0440 val_macro_f1=0.3239 val_mae=0.5641 epoch_seconds=634.7

epoch 2:   0%|          | 0/2405 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 05:16:22 | INFO | train task=Ses04F epoch=2 batch=92/2405 step=625 loss=1.2680 ce=0.4340 mse=1.6678 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2616233825683594, "reserved_gb": 2.828125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "3428", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "59.83"}
2026-08-09 05:16:42 | INFO | train task=Ses04F epoch=2 batch=192/2405 step=650 loss=3.4081 ce=2.5098 mse=1.7965 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2622008323669434, "reserved_gb": 3.05078125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "18", "gpu_mem_used_mb": "3656", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "62.68"}
2026-08-09 05:17:03 | INFO | train task=Ses04F epoch=2 batch=292/2405 step=675 loss=1.6864 ce=0.8848 mse=1.6031 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2616395950317383, "reserved_gb": 3.03125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "36", "gpu_mem_used_mb": "3636", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "74.29"}
2026-08-09 05:17:23 | INFO | train task=Ses04F epoch=2 batch=392/2405 step=700 loss=1.2698 ce=0.4056 mse=1.7283 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2617998123168945, "reserved_gb": 3.0625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "34", "gpu_mem_used_mb": "3668", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "69.87"}
2026-08-09 05:17:47 | INFO | train task=Ses04F epoch=2 batch=492/2405 step=725 loss=2.0694 ce=1.9146 mse=0.3096 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.261455535888672, "reserved_gb": 3.322265625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "3934", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "75.46"}
2026-08-09 05:18:08 | INFO | train task=Ses04F epoch=2 batch=592/2405 step=750 loss=1.9711 ce=1.9429 mse=0.0565 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2614355087280273, "reserved_gb": 2.837890625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "3437", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "70.01"}
2026-08-09 05:18:27 | INFO | train task=Ses04F epoch=2 batch=692/2405 step=775 loss=1.2751 ce=1.1596 mse=0.2312 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2624459266662598, "reserved_gb": 2.927734375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "3529", "gpu_mem_total_mb": "12288", "gpu_temp_c": "44", "gpu_power_w": "62.82"}
2026-08-09 05:18:46 | INFO | train task=Ses04F epoch=2 batch=792/2405 step=800 loss=2.4153 ce=2.0804 mse=0.6699 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.262248992919922, "reserved_gb": 2.982421875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "15", "gpu_mem_used_mb": "3585", "gpu_mem_total_mb": "12288", "gpu_temp_c": "43", "gpu_power_w": "42.22"}
2026-08-09 05:19:11 | INFO | train task=Ses04F epoch=2 batch=892/2405 step=825 loss=2.0466 ce=2.0145 mse=0.0641 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2628049850463867, "reserved_gb": 3.0078125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "26", "gpu_mem_used_mb": "3610", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "60.78"}
2026-08-09 05:19:31 | INFO | train task=Ses04F epoch=2 batch=992/2405 step=850 loss=0.8596 ce=0.7365 mse=0.2460 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2625956535339355, "reserved_gb": 2.853515625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "64", "gpu_mem_used_mb": "3452", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "73.36"}
2026-08-09 05:19:51 | INFO | train task=Ses04F epoch=2 batch=1092/2405 step=875 loss=2.0590 ce=1.9369 mse=0.2442 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.26694393157959, "reserved_gb": 3.302734375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "3912", "gpu_mem_total_mb": "12288", "gpu_temp_c": "43", "gpu_power_w": "53.98"}
2026-08-09 05:20:12 | INFO | train task=Ses04F epoch=2 batch=1192/2405 step=900 loss=1.3558 ce=1.3542 mse=0.0034 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1404037475585938, "reserved_gb": 2.259765625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "31", "gpu_mem_used_mb": "2844", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "68.30"}
2026-08-09 05:20:35 | INFO | train task=Ses04F epoch=2 batch=1292/2405 step=925 loss=0.4938 ce=0.4747 mse=0.0382 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1420159339904785, "reserved_gb": 1.716796875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "42", "gpu_mem_used_mb": "2288", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "70.14"}
2026-08-09 05:20:55 | INFO | train task=Ses04F epoch=2 batch=1392/2405 step=950 loss=1.5088 ce=1.1091 mse=0.7994 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1403255462646484, "reserved_gb": 1.6953125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "19", "gpu_mem_used_mb": "2266", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "65.04"}
2026-08-09 05:21:17 | INFO | train task=Ses04F epoch=2 batch=1492/2405 step=975 loss=1.8317 ce=1.6478 mse=0.3678 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1401982307434082, "reserved_gb": 1.7734375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "2345", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "76.27"}
2026-08-09 05:21:39 | INFO | train task=Ses04F epoch=2 batch=1592/2405 step=1000 loss=1.4012 ce=1.3914 mse=0.0196 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1408891677856445, "reserved_gb": 1.859375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "2433", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "60.74"}
2026-08-09 05:22:03 | INFO | train task=Ses04F epoch=2 batch=1692/2405 step=1025 loss=2.1453 ce=2.1431 mse=0.0045 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1404814720153809, "reserved_gb": 1.759765625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "25", "gpu_mem_used_mb": "2331", "gpu_mem_total_mb": "12288", "gpu_temp_c": "44", "gpu_power_w": "63.57"}
2026-08-09 05:22:25 | INFO | train task=Ses04F epoch=2 batch=1792/2405 step=1050 loss=1.0082 ce=0.8530 mse=0.3104 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1414165496826172, "reserved_gb": 2.380859375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "39", "gpu_mem_used_mb": "2967", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "73.27"}
2026-08-09 05:22:47 | INFO | train task=Ses04F epoch=2 batch=1892/2405 step=1075 loss=0.6473 ce=0.3802 mse=0.5341 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1400861740112305, "reserved_gb": 1.751953125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "19", "gpu_mem_used_mb": "2323", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "63.30"}
2026-08-09 05:23:08 | INFO | train task=Ses04F epoch=2 batch=1992/2405 step=1100 loss=2.7543 ce=2.6431 mse=0.2224 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1413397789001465, "reserved_gb": 1.791015625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "2363", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "77.09"}
2026-08-09 05:23:32 | INFO | train task=Ses04F epoch=2 batch=2092/2405 step=1125 loss=2.8135 ce=2.7691 mse=0.0887 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1411590576171875, "reserved_gb": 1.697265625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "26", "gpu_mem_used_mb": "2266", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "66.20"}
2026-08-09 05:23:52 | INFO | train task=Ses04F epoch=2 batch=2192/2405 step=1150 loss=2.1326 ce=1.9642 mse=0.3368 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1420769691467285, "reserved_gb": 1.91015625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "2484", "gpu_mem_total_mb": "12288", "gpu_temp_c": "44", "gpu_power_w": "50.14"}
2026-08-09 05:24:15 | INFO | train task=Ses04F epoch=2 batch=2292/2405 step=1175 loss=0.3514 ce=0.3254 mse=0.0520 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1411285400390625, "reserved_gb": 1.783203125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "26", "gpu_mem_used_mb": "2354", "gpu_mem_total_mb": "12288", "gpu_temp_c": "44", "gpu_power_w": "59.04"}
2026-08-09 05:24:40 | INFO | train task=Ses04F epoch=2 batch=2392/2405 step=1200 loss=0.2821 ce=0.2581 mse=0.0479 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1405229568481445, "reserved_gb": 1.810546875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "2382", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "81.30"}

predict:   0%|          | 0/328 [00:00<?, ?it/s]

2026-08-09 05:25:13 | INFO | Epoch 02 task=Ses04F train_loss=1.4804 val_macro_f1=0.3930 val_mae=0.5631 epoch_seconds=550.1

epoch 3:   0%|          | 0/2405 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 05:25:36 | INFO | train task=Ses04F epoch=3 batch=84/2405 step=1225 loss=1.8318 ce=1.5883 mse=0.4870 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1415066719055176, "reserved_gb": 1.943359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "40", "gpu_mem_used_mb": "2420", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "69.45"}
2026-08-09 05:25:55 | INFO | train task=Ses04F epoch=3 batch=184/2405 step=1250 loss=1.4635 ce=1.4367 mse=0.0535 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1401557922363281, "reserved_gb": 2.005859375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "2484", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "70.47"}
2026-08-09 05:26:15 | INFO | train task=Ses04F epoch=3 batch=284/2405 step=1275 loss=0.7183 ce=0.2872 mse=0.8622 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1403727531433105, "reserved_gb": 2.037109375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "18", "gpu_mem_used_mb": "2517", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "64.92"}
2026-08-09 05:26:35 | INFO | train task=Ses04F epoch=3 batch=384/2405 step=1300 loss=0.8231 ce=0.6015 mse=0.4434 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1407408714294434, "reserved_gb": 1.974609375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "26", "gpu_mem_used_mb": "2453", "gpu_mem_total_mb": "12288", "gpu_temp_c": "54", "gpu_power_w": "72.71"}
2026-08-09 05:26:58 | INFO | train task=Ses04F epoch=3 batch=484/2405 step=1325 loss=0.5332 ce=0.3498 mse=0.3668 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1405534744262695, "reserved_gb": 1.701171875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "28", "gpu_mem_used_mb": "2173", "gpu_mem_total_mb": "12288", "gpu_temp_c": "56", "gpu_power_w": "68.68"}
2026-08-09 05:27:18 | INFO | train task=Ses04F epoch=3 batch=584/2405 step=1350 loss=1.0252 ce=0.8381 mse=0.3742 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1434602737426758, "reserved_gb": 1.75390625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "60", "gpu_mem_used_mb": "2227", "gpu_mem_total_mb": "12288", "gpu_temp_c": "63", "gpu_power_w": "90.19"}
2026-08-09 05:27:38 | INFO | train task=Ses04F epoch=3 batch=684/2405 step=1375 loss=0.7945 ce=0.6290 mse=0.3309 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1404142379760742, "reserved_gb": 1.6953125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "32", "gpu_mem_used_mb": "2167", "gpu_mem_total_mb": "12288", "gpu_temp_c": "53", "gpu_power_w": "55.97"}
2026-08-09 05:27:58 | INFO | train task=Ses04F epoch=3 batch=784/2405 step=1400 loss=2.3984 ce=2.3847 mse=0.0274 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1400647163391113, "reserved_gb": 1.701171875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "43", "gpu_mem_used_mb": "2173", "gpu_mem_total_mb": "12288", "gpu_temp_c": "54", "gpu_power_w": "79.83"}
2026-08-09 05:28:23 | INFO | train task=Ses04F epoch=3 batch=884/2405 step=1425 loss=0.8170 ce=0.7404 mse=0.1531 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.139993667602539, "reserved_gb": 2.001953125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "36", "gpu_mem_used_mb": "2481", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "61.56"}
2026-08-09 05:28:43 | INFO | train task=Ses04F epoch=3 batch=984/2405 step=1450 loss=0.7893 ce=0.7483 mse=0.0820 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.139899730682373, "reserved_gb": 1.7421875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "49", "gpu_mem_used_mb": "2215", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "67.39"}
2026-08-09 05:29:03 | INFO | train task=Ses04F epoch=3 batch=1084/2405 step=1475 loss=0.9288 ce=0.9245 mse=0.0085 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1413569450378418, "reserved_gb": 1.70703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "34", "gpu_mem_used_mb": "2179", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "70.99"}
2026-08-09 05:29:23 | INFO | train task=Ses04F epoch=3 batch=1184/2405 step=1500 loss=1.3339 ce=1.1940 mse=0.2798 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.139920711517334, "reserved_gb": 2.068359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "26", "gpu_mem_used_mb": "2549", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "64.15"}
2026-08-09 05:29:47 | INFO | train task=Ses04F epoch=3 batch=1284/2405 step=1525 loss=0.3221 ce=0.0776 mse=0.4889 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1413931846618652, "reserved_gb": 1.77734375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "32", "gpu_mem_used_mb": "2251", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "81.12"}
2026-08-09 05:30:08 | INFO | train task=Ses04F epoch=3 batch=1384/2405 step=1550 loss=0.6644 ce=0.5299 mse=0.2691 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1402125358581543, "reserved_gb": 1.708984375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "2181", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "59.31"}
2026-08-09 05:30:29 | INFO | train task=Ses04F epoch=3 batch=1484/2405 step=1575 loss=1.2146 ce=1.1361 mse=0.1569 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.141054630279541, "reserved_gb": 1.740234375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "23", "gpu_mem_used_mb": "2213", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "70.42"}
2026-08-09 05:30:52 | INFO | train task=Ses04F epoch=3 batch=1584/2405 step=1600 loss=1.6433 ce=1.4496 mse=0.3874 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1400156021118164, "reserved_gb": 1.759765625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "92", "gpu_mem_used_mb": "2233", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "85.65"}
2026-08-09 05:31:17 | INFO | train task=Ses04F epoch=3 batch=1684/2405 step=1625 loss=2.1555 ce=1.3672 mse=1.5767 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.140397071838379, "reserved_gb": 1.6953125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "40", "gpu_mem_used_mb": "2167", "gpu_mem_total_mb": "12288", "gpu_temp_c": "44", "gpu_power_w": "43.19"}
2026-08-09 05:31:39 | INFO | train task=Ses04F epoch=3 batch=1784/2405 step=1650 loss=1.2443 ce=1.2178 mse=0.0530 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.140080451965332, "reserved_gb": 1.681640625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "38", "gpu_mem_used_mb": "2153", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "80.31"}
2026-08-09 05:32:02 | INFO | train task=Ses04F epoch=3 batch=1884/2405 step=1675 loss=0.4555 ce=0.0819 mse=0.7472 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1406078338623047, "reserved_gb": 1.775390625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "33", "gpu_mem_used_mb": "2249", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "69.62"}
2026-08-09 05:32:25 | INFO | train task=Ses04F epoch=3 batch=1984/2405 step=1700 loss=0.6862 ce=0.1718 mse=1.0288 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1400566101074219, "reserved_gb": 1.76171875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "53", "gpu_mem_used_mb": "2235", "gpu_mem_total_mb": "12288", "gpu_temp_c": "53", "gpu_power_w": "88.28"}
2026-08-09 05:32:51 | INFO | train task=Ses04F epoch=3 batch=2084/2405 step=1725 loss=0.1764 ce=0.1447 mse=0.0634 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1414146423339844, "reserved_gb": 1.88671875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "29", "gpu_mem_used_mb": "2363", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "58.48"}
2026-08-09 05:33:14 | INFO | train task=Ses04F epoch=3 batch=2184/2405 step=1750 loss=0.5939 ce=0.1015 mse=0.9848 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1419167518615723, "reserved_gb": 1.7421875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "36", "gpu_mem_used_mb": "2215", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "77.19"}
2026-08-09 05:33:37 | INFO | train task=Ses04F epoch=3 batch=2284/2405 step=1775 loss=1.1798 ce=0.9517 mse=0.4561 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1399402618408203, "reserved_gb": 1.890625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "27", "gpu_mem_used_mb": "2367", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "63.91"}
2026-08-09 05:33:59 | INFO | train task=Ses04F epoch=3 batch=2384/2405 step=1800 loss=0.4127 ce=0.2480 mse=0.3295 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1400814056396484, "reserved_gb": 1.701171875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "38", "gpu_mem_used_mb": "2173", "gpu_mem_total_mb": "12288", "gpu_temp_c": "44", "gpu_power_w": "58.57"}

predict:   0%|          | 0/328 [00:00<?, ?it/s]

2026-08-09 05:34:35 | INFO | Epoch 03 task=Ses04F train_loss=1.2449 val_macro_f1=0.3756 val_mae=0.5471 epoch_seconds=556.3

epoch 4:   0%|          | 0/2405 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 05:34:54 | INFO | train task=Ses04F epoch=4 batch=76/2405 step=1825 loss=0.4665 ce=0.3739 mse=0.1852 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.141038417816162, "reserved_gb": 2.0, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "33", "gpu_mem_used_mb": "2370", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "79.58"}
2026-08-09 05:35:15 | INFO | train task=Ses04F epoch=4 batch=176/2405 step=1850 loss=0.6905 ce=0.5395 mse=0.3020 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1404986381530762, "reserved_gb": 1.763671875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "26", "gpu_mem_used_mb": "2168", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "63.81"}
2026-08-09 05:35:36 | INFO | train task=Ses04F epoch=4 batch=276/2405 step=1875 loss=0.5037 ce=0.4432 mse=0.1211 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1398735046386719, "reserved_gb": 1.794921875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "27", "gpu_mem_used_mb": "2200", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "69.00"}
2026-08-09 05:35:55 | INFO | train task=Ses04F epoch=4 batch=376/2405 step=1900 loss=0.3732 ce=0.2371 mse=0.2721 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.140946865081787, "reserved_gb": 1.779296875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "2184", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "68.43"}
2026-08-09 05:36:18 | INFO | train task=Ses04F epoch=4 batch=476/2405 step=1925 loss=0.6506 ce=0.3659 mse=0.5694 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1401219367980957, "reserved_gb": 1.703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "27", "gpu_mem_used_mb": "2106", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "76.07"}
2026-08-09 05:36:37 | INFO | train task=Ses04F epoch=4 batch=576/2405 step=1950 loss=0.6680 ce=0.1833 mse=0.9695 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1454133987426758, "reserved_gb": 2.05859375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "54", "gpu_mem_used_mb": "2470", "gpu_mem_total_mb": "12288", "gpu_temp_c": "44", "gpu_power_w": "56.63"}
2026-08-09 05:36:58 | INFO | train task=Ses04F epoch=4 batch=676/2405 step=1975 loss=1.2536 ce=1.1456 mse=0.2159 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1398663520812988, "reserved_gb": 1.810546875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "23", "gpu_mem_used_mb": "2216", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "69.23"}
2026-08-09 05:37:19 | INFO | train task=Ses04F epoch=4 batch=776/2405 step=2000 loss=0.2279 ce=0.2204 mse=0.0150 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1403436660766602, "reserved_gb": 1.732421875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "2136", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "78.55"}
2026-08-09 05:37:44 | INFO | train task=Ses04F epoch=4 batch=876/2405 step=2025 loss=0.9359 ce=0.2997 mse=1.2725 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1406607627868652, "reserved_gb": 1.775390625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "27", "gpu_mem_used_mb": "2180", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "63.96"}
2026-08-09 05:38:06 | INFO | train task=Ses04F epoch=4 batch=976/2405 step=2050 loss=0.6168 ce=0.5996 mse=0.0344 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1400723457336426, "reserved_gb": 2.169921875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "2584", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "115.46"}
2026-08-09 05:38:28 | INFO | train task=Ses04F epoch=4 batch=1076/2405 step=2075 loss=1.6703 ce=1.4488 mse=0.4430 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.140883445739746, "reserved_gb": 1.755859375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "23", "gpu_mem_used_mb": "2160", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "59.52"}
2026-08-09 05:38:48 | INFO | train task=Ses04F epoch=4 batch=1176/2405 step=2100 loss=1.0282 ce=0.8318 mse=0.3927 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1454143524169922, "reserved_gb": 2.109375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "70", "gpu_mem_used_mb": "2522", "gpu_mem_total_mb": "12288", "gpu_temp_c": "44", "gpu_power_w": "56.83"}
2026-08-09 05:39:13 | INFO | train task=Ses04F epoch=4 batch=1276/2405 step=2125 loss=1.7124 ce=1.5836 mse=0.2577 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1418170928955078, "reserved_gb": 2.0078125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "62", "gpu_mem_used_mb": "2418", "gpu_mem_total_mb": "12288", "gpu_temp_c": "44", "gpu_power_w": "45.91"}
2026-08-09 05:39:34 | INFO | train task=Ses04F epoch=4 batch=1376/2405 step=2150 loss=0.9943 ce=0.7235 mse=0.5417 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.139899730682373, "reserved_gb": 1.6953125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "16", "gpu_mem_used_mb": "2098", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "62.44"}
2026-08-09 05:39:54 | INFO | train task=Ses04F epoch=4 batch=1476/2405 step=2175 loss=1.0727 ce=1.0444 mse=0.0565 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1427726745605469, "reserved_gb": 1.736328125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "74", "gpu_mem_used_mb": "2140", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "86.79"}
2026-08-09 05:40:16 | INFO | train task=Ses04F epoch=4 batch=1576/2405 step=2200 loss=1.4591 ce=1.2649 mse=0.3884 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1400446891784668, "reserved_gb": 1.875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "31", "gpu_mem_used_mb": "2282", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "75.17"}
2026-08-09 05:40:41 | INFO | train task=Ses04F epoch=4 batch=1676/2405 step=2225 loss=1.3257 ce=1.1564 mse=0.3387 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1399822235107422, "reserved_gb": 1.685546875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "12", "gpu_mem_used_mb": "2141", "gpu_mem_total_mb": "12288", "gpu_temp_c": "43", "gpu_power_w": "43.98"}
2026-08-09 05:41:02 | INFO | train task=Ses04F epoch=4 batch=1776/2405 step=2250 loss=1.5861 ce=1.4063 mse=0.3598 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1397905349731445, "reserved_gb": 1.6953125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "2152", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "81.48"}
2026-08-09 05:41:24 | INFO | train task=Ses04F epoch=4 batch=1876/2405 step=2275 loss=2.1478 ce=1.6120 mse=1.0716 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1406545639038086, "reserved_gb": 1.775390625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "2234", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "68.83"}
2026-08-09 05:41:48 | INFO | train task=Ses04F epoch=4 batch=1976/2405 step=2300 loss=0.8677 ce=0.6386 mse=0.4581 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1400089263916016, "reserved_gb": 1.880859375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "33", "gpu_mem_used_mb": "2342", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "73.98"}
2026-08-09 05:42:10 | INFO | train task=Ses04F epoch=4 batch=2076/2405 step=2325 loss=0.3623 ce=0.3383 mse=0.0480 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1402583122253418, "reserved_gb": 1.810546875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "35", "gpu_mem_used_mb": "2270", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "61.30"}
2026-08-09 05:42:32 | INFO | train task=Ses04F epoch=4 batch=2176/2405 step=2350 loss=0.4163 ce=0.2667 mse=0.2990 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1402859687805176, "reserved_gb": 1.693359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "2150", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "71.08"}
2026-08-09 05:42:54 | INFO | train task=Ses04F epoch=4 batch=2276/2405 step=2375 loss=0.1753 ce=0.1529 mse=0.0449 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1427841186523438, "reserved_gb": 1.935546875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "13", "gpu_mem_used_mb": "2398", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "65.28"}
2026-08-09 05:43:19 | INFO | train task=Ses04F epoch=4 batch=2376/2405 step=2400 loss=0.7412 ce=0.7053 mse=0.0718 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1406526565551758, "reserved_gb": 1.75390625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "19", "gpu_mem_used_mb": "2250", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "102.01"}

predict:   0%|          | 0/328 [00:00<?, ?it/s]

2026-08-09 05:43:55 | INFO | Epoch 04 task=Ses04F train_loss=1.0897 val_macro_f1=0.3809 val_mae=0.5347 epoch_seconds=557.7

predict:   0%|          | 0/264 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)

predict:   0%|          | 0/365 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
2026-08-09 05:45:22 | INFO | Task fbe86de81535c0cc_main_fold -> complete
2026-08-09 05:45:23 | INFO | Manuscript outputs refreshed: 21 tables, 4 figures
2026-08-09 05:45:23 | INFO | Task 2dc40c69dc08c922_main_fold -> running
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\transformers\configuration_utils.py:335: UserWarning: Passing `gradient_checkpointing` to a config initialization is deprecated and will be removed in v5 Transformers. Using `model.gradient_checkpointing_enable()` instead, or if you are using the `Trainer` API, pass `gradient_checkpointing=True` in your `TrainingArguments`.
  warnings.warn(
2026-08-09 05:45:26 | INFO | Task C:\Users\HaseebWajid\Downloads\runs\dersx_paper_aligned\campaign_01\main\seed_13\Ses04M parameters={'total': 163009451, 'trainable': 69034283, 'frozen': 93975168} scope={'corpus': 'IEMOCAP', 'protocol': 'strict_LOSO', 'heldout_speaker': 'Ses04M', 'seed': 13, 'stage': 'main', 'profile': 'rtx3060_24h'}

epoch 1:   0%|          | 0/2405 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 05:45:48 | INFO | train task=Ses04M epoch=1 batch=100/2405 step=25 loss=2.9921 ce=2.3252 mse=1.3339 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1417417526245117, "reserved_gb": 1.7265625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "28", "gpu_mem_used_mb": "2193", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "69.94"}
2026-08-09 05:46:08 | INFO | train task=Ses04M epoch=1 batch=200/2405 step=50 loss=2.5140 ce=2.2783 mse=0.4714 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.142160415649414, "reserved_gb": 1.779296875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "26", "gpu_mem_used_mb": "2247", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "70.96"}
2026-08-09 05:46:31 | INFO | train task=Ses04M epoch=1 batch=300/2405 step=75 loss=2.2166 ce=2.0136 mse=0.4061 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1441760063171387, "reserved_gb": 1.724609375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "2191", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "66.06"}
2026-08-09 05:46:52 | INFO | train task=Ses04M epoch=1 batch=400/2405 step=100 loss=2.9101 ce=2.1864 mse=1.4474 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.14127779006958, "reserved_gb": 2.001953125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "15", "gpu_mem_used_mb": "2475", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "65.32"}
2026-08-09 05:47:17 | INFO | train task=Ses04M epoch=1 batch=500/2405 step=125 loss=3.4226 ce=1.9027 mse=3.0399 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1422882080078125, "reserved_gb": 1.70703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "31", "gpu_mem_used_mb": "2173", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "62.70"}
2026-08-09 05:47:40 | INFO | train task=Ses04M epoch=1 batch=600/2405 step=150 loss=1.9704 ce=1.9595 mse=0.0217 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1416025161743164, "reserved_gb": 1.705078125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "26", "gpu_mem_used_mb": "2179", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "71.12"}
2026-08-09 05:48:02 | INFO | train task=Ses04M epoch=1 batch=700/2405 step=175 loss=2.2497 ce=2.2431 mse=0.0131 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1414341926574707, "reserved_gb": 1.6953125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "2169", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "70.87"}
2026-08-09 05:48:22 | INFO | train task=Ses04M epoch=1 batch=800/2405 step=200 loss=2.0903 ce=1.8626 mse=0.4555 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1423964500427246, "reserved_gb": 1.75, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "27", "gpu_mem_used_mb": "2225", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "79.85"}
2026-08-09 05:48:50 | INFO | train task=Ses04M epoch=1 batch=900/2405 step=225 loss=1.9901 ce=1.8076 mse=0.3650 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1413993835449219, "reserved_gb": 1.69140625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "51", "gpu_mem_used_mb": "2165", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "57.60"}
2026-08-09 05:49:12 | INFO | train task=Ses04M epoch=1 batch=1000/2405 step=250 loss=1.6079 ce=1.5537 mse=0.1084 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1479301452636719, "reserved_gb": 2.3515625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "23", "gpu_mem_used_mb": "2841", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "77.60"}
2026-08-09 05:49:36 | INFO | train task=Ses04M epoch=1 batch=1100/2405 step=275 loss=1.3996 ce=1.1792 mse=0.4407 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1413135528564453, "reserved_gb": 1.6875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "19", "gpu_mem_used_mb": "2165", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "69.54"}
2026-08-09 05:49:59 | INFO | train task=Ses04M epoch=1 batch=1200/2405 step=300 loss=1.7144 ce=1.6211 mse=0.1866 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1424126625061035, "reserved_gb": 1.70703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "2185", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "70.96"}
2026-08-09 05:50:26 | INFO | train task=Ses04M epoch=1 batch=1300/2405 step=325 loss=2.2399 ce=1.6855 mse=1.1088 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1469731330871582, "reserved_gb": 1.791015625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "75", "gpu_mem_used_mb": "2271", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "97.63"}
2026-08-09 05:50:49 | INFO | train task=Ses04M epoch=1 batch=1400/2405 step=350 loss=1.8118 ce=1.7928 mse=0.0380 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1413249969482422, "reserved_gb": 1.685546875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "23", "gpu_mem_used_mb": "2163", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "80.97"}
2026-08-09 05:51:13 | INFO | train task=Ses04M epoch=1 batch=1500/2405 step=375 loss=1.8898 ce=1.7404 mse=0.2988 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1443266868591309, "reserved_gb": 1.947265625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "36", "gpu_mem_used_mb": "2431", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "74.07"}
2026-08-09 05:51:36 | INFO | train task=Ses04M epoch=1 batch=1600/2405 step=400 loss=2.0896 ce=1.7573 mse=0.6646 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1417102813720703, "reserved_gb": 1.724609375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "38", "gpu_mem_used_mb": "2203", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "70.40"}
2026-08-09 05:52:01 | INFO | train task=Ses04M epoch=1 batch=1700/2405 step=425 loss=1.7666 ce=1.6447 mse=0.2437 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1418981552124023, "reserved_gb": 1.76171875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "16", "gpu_mem_used_mb": "2241", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "75.22"}
2026-08-09 05:52:25 | INFO | train task=Ses04M epoch=1 batch=1800/2405 step=450 loss=1.2857 ce=1.0314 mse=0.5087 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1427583694458008, "reserved_gb": 1.84765625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "2329", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "82.50"}
2026-08-09 05:52:49 | INFO | train task=Ses04M epoch=1 batch=1900/2405 step=475 loss=1.6450 ce=1.5129 mse=0.2642 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1417036056518555, "reserved_gb": 1.7265625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "30", "gpu_mem_used_mb": "2205", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "71.93"}
2026-08-09 05:53:13 | INFO | train task=Ses04M epoch=1 batch=2000/2405 step=500 loss=1.7771 ce=1.5604 mse=0.4333 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1414508819580078, "reserved_gb": 1.794921875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "48", "gpu_mem_used_mb": "2275", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "80.85"}
2026-08-09 05:53:40 | INFO | train task=Ses04M epoch=1 batch=2100/2405 step=525 loss=1.5009 ce=0.9423 mse=1.1172 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1417264938354492, "reserved_gb": 1.70703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "19", "gpu_mem_used_mb": "2185", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "75.11"}
2026-08-09 05:54:04 | INFO | train task=Ses04M epoch=1 batch=2200/2405 step=550 loss=0.9154 ce=0.9009 mse=0.0290 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1421351432800293, "reserved_gb": 1.818359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "30", "gpu_mem_used_mb": "2299", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "63.24"}
2026-08-09 05:54:28 | INFO | train task=Ses04M epoch=1 batch=2300/2405 step=575 loss=2.0093 ce=1.6741 mse=0.6705 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1426668167114258, "reserved_gb": 1.70703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "43", "gpu_mem_used_mb": "2185", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "74.47"}
2026-08-09 05:54:52 | INFO | train task=Ses04M epoch=1 batch=2400/2405 step=600 loss=2.5367 ce=2.5215 mse=0.0304 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1420173645019531, "reserved_gb": 1.708984375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "24", "gpu_mem_used_mb": "2187", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "66.64"}

predict:   0%|          | 0/328 [00:00<?, ?it/s]

2026-08-09 05:55:42 | INFO | Epoch 01 task=Ses04M train_loss=2.0393 val_macro_f1=0.3312 val_mae=0.5616 epoch_seconds=615.2

epoch 2:   0%|          | 0/2405 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 05:56:05 | INFO | train task=Ses04M epoch=2 batch=92/2405 step=625 loss=1.7672 ce=0.6100 mse=2.3145 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1413936614990234, "reserved_gb": 1.771484375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "53", "gpu_mem_used_mb": "2250", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "58.55"}
2026-08-09 05:56:25 | INFO | train task=Ses04M epoch=2 batch=192/2405 step=650 loss=3.3164 ce=2.3433 mse=1.9461 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1419711112976074, "reserved_gb": 1.833984375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "26", "gpu_mem_used_mb": "2314", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "69.27"}
2026-08-09 05:56:46 | INFO | train task=Ses04M epoch=2 batch=292/2405 step=675 loss=1.6024 ce=0.8703 mse=1.4643 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1414098739624023, "reserved_gb": 1.9375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "18", "gpu_mem_used_mb": "2420", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "69.82"}
2026-08-09 05:57:06 | INFO | train task=Ses04M epoch=2 batch=392/2405 step=700 loss=1.2296 ce=0.4208 mse=1.6177 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1415700912475586, "reserved_gb": 1.888671875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "18", "gpu_mem_used_mb": "2370", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "68.27"}
2026-08-09 05:57:30 | INFO | train task=Ses04M epoch=2 batch=492/2405 step=725 loss=2.0284 ce=1.5242 mse=1.0084 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.141225814819336, "reserved_gb": 2.15234375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "42", "gpu_mem_used_mb": "2640", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "81.10"}
2026-08-09 05:57:50 | INFO | train task=Ses04M epoch=2 batch=592/2405 step=750 loss=1.9498 ce=1.8789 mse=0.1417 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1412057876586914, "reserved_gb": 1.689453125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "18", "gpu_mem_used_mb": "2166", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "66.98"}
2026-08-09 05:58:10 | INFO | train task=Ses04M epoch=2 batch=692/2405 step=775 loss=1.6438 ce=1.3063 mse=0.6752 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1422162055969238, "reserved_gb": 1.76171875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "19", "gpu_mem_used_mb": "2239", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "64.01"}
2026-08-09 05:58:30 | INFO | train task=Ses04M epoch=2 batch=792/2405 step=800 loss=2.2811 ce=1.9494 mse=0.6633 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.142019271850586, "reserved_gb": 1.8125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "35", "gpu_mem_used_mb": "2291", "gpu_mem_total_mb": "12288", "gpu_temp_c": "43", "gpu_power_w": "39.53"}
2026-08-09 05:58:54 | INFO | train task=Ses04M epoch=2 batch=892/2405 step=825 loss=1.9861 ce=1.9073 mse=0.1576 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1425752639770508, "reserved_gb": 1.765625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "25", "gpu_mem_used_mb": "2243", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "61.17"}
2026-08-09 05:59:14 | INFO | train task=Ses04M epoch=2 batch=992/2405 step=850 loss=0.8500 ce=0.7213 mse=0.2574 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1423659324645996, "reserved_gb": 1.70703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "28", "gpu_mem_used_mb": "2183", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "76.49"}
2026-08-09 05:59:34 | INFO | train task=Ses04M epoch=2 batch=1092/2405 step=875 loss=2.2092 ce=2.0298 mse=0.3588 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1466035842895508, "reserved_gb": 2.15625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "64", "gpu_mem_used_mb": "2643", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "60.20"}
2026-08-09 05:59:55 | INFO | train task=Ses04M epoch=2 batch=1192/2405 step=900 loss=1.8582 ce=1.8459 mse=0.0247 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.141815185546875, "reserved_gb": 2.078125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "49", "gpu_mem_used_mb": "2563", "gpu_mem_total_mb": "12288", "gpu_temp_c": "55", "gpu_power_w": "76.86"}
2026-08-09 06:00:18 | INFO | train task=Ses04M epoch=2 batch=1292/2405 step=925 loss=0.4537 ce=0.4259 mse=0.0555 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1434273719787598, "reserved_gb": 1.728515625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "69", "gpu_mem_used_mb": "2205", "gpu_mem_total_mb": "12288", "gpu_temp_c": "59", "gpu_power_w": "76.05"}
2026-08-09 06:00:38 | INFO | train task=Ses04M epoch=2 batch=1392/2405 step=950 loss=1.5628 ce=1.2821 mse=0.5615 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1417369842529297, "reserved_gb": 1.70703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "23", "gpu_mem_used_mb": "2183", "gpu_mem_total_mb": "12288", "gpu_temp_c": "59", "gpu_power_w": "68.65"}
2026-08-09 06:01:00 | INFO | train task=Ses04M epoch=2 batch=1492/2405 step=975 loss=1.9026 ce=1.6066 mse=0.5920 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1416096687316895, "reserved_gb": 1.748046875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "26", "gpu_mem_used_mb": "2225", "gpu_mem_total_mb": "12288", "gpu_temp_c": "54", "gpu_power_w": "74.31"}
2026-08-09 06:01:22 | INFO | train task=Ses04M epoch=2 batch=1592/2405 step=1000 loss=1.6831 ce=1.6411 mse=0.0839 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1423006057739258, "reserved_gb": 1.80078125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "2278", "gpu_mem_total_mb": "12288", "gpu_temp_c": "53", "gpu_power_w": "67.76"}
2026-08-09 06:01:45 | INFO | train task=Ses04M epoch=2 batch=1692/2405 step=1025 loss=1.9738 ce=1.9634 mse=0.0208 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.141892910003662, "reserved_gb": 1.76953125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "2246", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "66.21"}
2026-08-09 06:02:07 | INFO | train task=Ses04M epoch=2 batch=1792/2405 step=1050 loss=0.8451 ce=0.5872 mse=0.5157 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1428279876708984, "reserved_gb": 2.392578125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "30", "gpu_mem_used_mb": "2884", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "70.12"}
2026-08-09 06:02:29 | INFO | train task=Ses04M epoch=2 batch=1892/2405 step=1075 loss=0.6726 ce=0.4381 mse=0.4690 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1414976119995117, "reserved_gb": 1.767578125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "2244", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "58.88"}
2026-08-09 06:02:51 | INFO | train task=Ses04M epoch=2 batch=1992/2405 step=1100 loss=3.3333 ce=3.1302 mse=0.4062 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1427512168884277, "reserved_gb": 1.837890625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "44", "gpu_mem_used_mb": "2316", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "76.59"}
2026-08-09 06:03:15 | INFO | train task=Ses04M epoch=2 batch=2092/2405 step=1125 loss=2.6445 ce=2.5965 mse=0.0960 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1425704956054688, "reserved_gb": 1.70703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "28", "gpu_mem_used_mb": "2181", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "67.41"}
2026-08-09 06:03:35 | INFO | train task=Ses04M epoch=2 batch=2192/2405 step=1150 loss=2.2300 ce=2.0396 mse=0.3807 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1434884071350098, "reserved_gb": 1.916015625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "25", "gpu_mem_used_mb": "2395", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "47.43"}
2026-08-09 06:03:57 | INFO | train task=Ses04M epoch=2 batch=2292/2405 step=1175 loss=0.3918 ce=0.3647 mse=0.0543 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1425399780273438, "reserved_gb": 1.791015625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "18", "gpu_mem_used_mb": "2267", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "65.57"}
2026-08-09 06:04:22 | INFO | train task=Ses04M epoch=2 batch=2392/2405 step=1200 loss=0.4385 ce=0.3465 mse=0.1842 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1419343948364258, "reserved_gb": 1.822265625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "25", "gpu_mem_used_mb": "2299", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "80.14"}

predict:   0%|          | 0/328 [00:00<?, ?it/s]

2026-08-09 06:04:59 | INFO | Epoch 02 task=Ses04M train_loss=1.4904 val_macro_f1=0.3698 val_mae=0.5630 epoch_seconds=552.9

epoch 3:   0%|          | 0/2405 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 06:05:24 | INFO | train task=Ses04M epoch=3 batch=84/2405 step=1225 loss=1.9753 ce=1.7277 mse=0.4952 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1429181098937988, "reserved_gb": 1.90234375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "2268", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "70.42"}
2026-08-09 06:05:43 | INFO | train task=Ses04M epoch=3 batch=184/2405 step=1250 loss=1.5589 ce=1.5537 mse=0.0103 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1415672302246094, "reserved_gb": 2.044921875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "31", "gpu_mem_used_mb": "2423", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "69.97"}
2026-08-09 06:06:03 | INFO | train task=Ses04M epoch=3 batch=284/2405 step=1275 loss=0.8659 ce=0.4040 mse=0.9238 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1417841911315918, "reserved_gb": 2.0078125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "19", "gpu_mem_used_mb": "2385", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "65.03"}
2026-08-09 06:06:24 | INFO | train task=Ses04M epoch=3 batch=384/2405 step=1300 loss=0.9507 ce=0.6501 mse=0.6012 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1421523094177246, "reserved_gb": 1.982421875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "30", "gpu_mem_used_mb": "2375", "gpu_mem_total_mb": "12288", "gpu_temp_c": "53", "gpu_power_w": "71.95"}
2026-08-09 06:06:47 | INFO | train task=Ses04M epoch=3 batch=484/2405 step=1325 loss=0.6104 ce=0.5437 mse=0.1333 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1419649124145508, "reserved_gb": 1.69921875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "28", "gpu_mem_used_mb": "2085", "gpu_mem_total_mb": "12288", "gpu_temp_c": "55", "gpu_power_w": "75.75"}
2026-08-09 06:07:08 | INFO | train task=Ses04M epoch=3 batch=584/2405 step=1350 loss=0.9387 ce=0.8115 mse=0.2545 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.144871711730957, "reserved_gb": 1.74609375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "71", "gpu_mem_used_mb": "2133", "gpu_mem_total_mb": "12288", "gpu_temp_c": "61", "gpu_power_w": "88.08"}
2026-08-09 06:07:28 | INFO | train task=Ses04M epoch=3 batch=684/2405 step=1375 loss=0.6108 ce=0.4834 mse=0.2549 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1418256759643555, "reserved_gb": 1.70703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "29", "gpu_mem_used_mb": "2093", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "47.44"}
2026-08-09 06:07:48 | INFO | train task=Ses04M epoch=3 batch=784/2405 step=1400 loss=3.3279 ce=3.3055 mse=0.0448 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1414761543273926, "reserved_gb": 1.7109375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "19", "gpu_mem_used_mb": "2097", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "73.61"}
2026-08-09 06:08:13 | INFO | train task=Ses04M epoch=3 batch=884/2405 step=1425 loss=0.7676 ce=0.7096 mse=0.1161 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1414051055908203, "reserved_gb": 2.01171875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "2405", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "65.63"}
2026-08-09 06:08:32 | INFO | train task=Ses04M epoch=3 batch=984/2405 step=1450 loss=1.0487 ce=0.9687 mse=0.1599 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1413111686706543, "reserved_gb": 1.716796875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "29", "gpu_mem_used_mb": "2103", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "69.59"}
2026-08-09 06:08:53 | INFO | train task=Ses04M epoch=3 batch=1084/2405 step=1475 loss=0.7898 ce=0.7885 mse=0.0026 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.142768383026123, "reserved_gb": 1.716796875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "2103", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "65.88"}
2026-08-09 06:09:13 | INFO | train task=Ses04M epoch=3 batch=1184/2405 step=1500 loss=1.4933 ce=1.2732 mse=0.4403 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1413321495056152, "reserved_gb": 2.07421875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "50", "gpu_mem_used_mb": "2469", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "60.73"}
2026-08-09 06:09:38 | INFO | train task=Ses04M epoch=3 batch=1284/2405 step=1525 loss=0.4552 ce=0.1490 mse=0.6124 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1428046226501465, "reserved_gb": 1.787109375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "2175", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "80.43"}
2026-08-09 06:09:58 | INFO | train task=Ses04M epoch=3 batch=1384/2405 step=1550 loss=0.7047 ce=0.5735 mse=0.2623 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1416239738464355, "reserved_gb": 1.7109375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "2097", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "49.23"}
2026-08-09 06:10:20 | INFO | train task=Ses04M epoch=3 batch=1484/2405 step=1575 loss=1.2618 ce=1.1754 mse=0.1728 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1424660682678223, "reserved_gb": 1.7890625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "33", "gpu_mem_used_mb": "2177", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "73.59"}
2026-08-09 06:10:43 | INFO | train task=Ses04M epoch=3 batch=1584/2405 step=1600 loss=1.1433 ce=0.9518 mse=0.3830 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1414270401000977, "reserved_gb": 1.765625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "56", "gpu_mem_used_mb": "2153", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "86.79"}
2026-08-09 06:11:07 | INFO | train task=Ses04M epoch=3 batch=1684/2405 step=1625 loss=1.8460 ce=1.1542 mse=1.3837 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1418085098266602, "reserved_gb": 1.70703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "29", "gpu_mem_used_mb": "2093", "gpu_mem_total_mb": "12288", "gpu_temp_c": "44", "gpu_power_w": "46.52"}
2026-08-09 06:11:30 | INFO | train task=Ses04M epoch=3 batch=1784/2405 step=1650 loss=1.0320 ce=1.0279 mse=0.0081 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1414918899536133, "reserved_gb": 1.69140625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "2077", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "79.07"}
2026-08-09 06:11:52 | INFO | train task=Ses04M epoch=3 batch=1884/2405 step=1675 loss=0.3546 ce=0.1212 mse=0.4669 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.142019271850586, "reserved_gb": 1.814453125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "2203", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "66.21"}
2026-08-09 06:12:16 | INFO | train task=Ses04M epoch=3 batch=1984/2405 step=1700 loss=0.5332 ce=0.2248 mse=0.6167 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1414680480957031, "reserved_gb": 1.7734375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "16", "gpu_mem_used_mb": "2161", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "91.74"}
2026-08-09 06:12:41 | INFO | train task=Ses04M epoch=3 batch=2084/2405 step=1725 loss=0.1468 ce=0.0706 mse=0.1523 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1428260803222656, "reserved_gb": 1.8515625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "37", "gpu_mem_used_mb": "2241", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "59.90"}
2026-08-09 06:13:04 | INFO | train task=Ses04M epoch=3 batch=2184/2405 step=1750 loss=0.4667 ce=0.1576 mse=0.6182 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1433281898498535, "reserved_gb": 1.75390625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "50", "gpu_mem_used_mb": "2141", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "79.98"}
2026-08-09 06:13:27 | INFO | train task=Ses04M epoch=3 batch=2284/2405 step=1775 loss=0.8120 ce=0.6586 mse=0.3067 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1413516998291016, "reserved_gb": 1.880859375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "32", "gpu_mem_used_mb": "2271", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "63.89"}
2026-08-09 06:13:49 | INFO | train task=Ses04M epoch=3 batch=2384/2405 step=1800 loss=0.4744 ce=0.2732 mse=0.4025 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1414928436279297, "reserved_gb": 1.7109375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "18", "gpu_mem_used_mb": "2097", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "57.13"}

predict:   0%|          | 0/328 [00:00<?, ?it/s]

2026-08-09 06:14:27 | INFO | Epoch 03 task=Ses04M train_loss=1.2616 val_macro_f1=0.3789 val_mae=0.5623 epoch_seconds=562.9

epoch 4:   0%|          | 0/2405 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 06:14:50 | INFO | train task=Ses04M epoch=4 batch=76/2405 step=1825 loss=0.9784 ce=0.9271 mse=0.1027 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1424498558044434, "reserved_gb": 1.990234375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "40", "gpu_mem_used_mb": "2380", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "80.37"}
2026-08-09 06:15:12 | INFO | train task=Ses04M epoch=4 batch=176/2405 step=1850 loss=0.5970 ce=0.4514 mse=0.2913 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1419100761413574, "reserved_gb": 1.69921875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "2085", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "67.34"}
2026-08-09 06:15:32 | INFO | train task=Ses04M epoch=4 batch=276/2405 step=1875 loss=0.3113 ce=0.2372 mse=0.1482 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1412849426269531, "reserved_gb": 1.80078125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "28", "gpu_mem_used_mb": "2189", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "66.34"}
2026-08-09 06:15:51 | INFO | train task=Ses04M epoch=4 batch=376/2405 step=1900 loss=0.5768 ce=0.3285 mse=0.4966 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1423583030700684, "reserved_gb": 1.7890625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "19", "gpu_mem_used_mb": "2177", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "68.43"}
2026-08-09 06:16:14 | INFO | train task=Ses04M epoch=4 batch=476/2405 step=1925 loss=0.7897 ce=0.4085 mse=0.7623 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.141533374786377, "reserved_gb": 1.712890625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "48", "gpu_mem_used_mb": "2099", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "76.07"}
2026-08-09 06:16:34 | INFO | train task=Ses04M epoch=4 batch=576/2405 step=1950 loss=0.5185 ce=0.1405 mse=0.7559 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.146824836730957, "reserved_gb": 2.048828125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "48", "gpu_mem_used_mb": "2443", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "59.92"}
2026-08-09 06:16:55 | INFO | train task=Ses04M epoch=4 batch=676/2405 step=1975 loss=1.0742 ce=1.0200 mse=0.1085 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.14127779006958, "reserved_gb": 1.78515625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "7", "gpu_mem_used_mb": "2173", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "61.04"}
2026-08-09 06:17:15 | INFO | train task=Ses04M epoch=4 batch=776/2405 step=2000 loss=0.2271 ce=0.1308 mse=0.1927 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1417551040649414, "reserved_gb": 1.72265625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "29", "gpu_mem_used_mb": "2109", "gpu_mem_total_mb": "12288", "gpu_temp_c": "56", "gpu_power_w": "81.11"}
2026-08-09 06:17:40 | INFO | train task=Ses04M epoch=4 batch=876/2405 step=2025 loss=1.2841 ce=0.6475 mse=1.2733 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1420722007751465, "reserved_gb": 1.794921875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "2183", "gpu_mem_total_mb": "12288", "gpu_temp_c": "54", "gpu_power_w": "56.62"}
2026-08-09 06:18:02 | INFO | train task=Ses04M epoch=4 batch=976/2405 step=2050 loss=0.5182 ce=0.4757 mse=0.0850 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1414837837219238, "reserved_gb": 2.1796875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "76", "gpu_mem_used_mb": "2577", "gpu_mem_total_mb": "12288", "gpu_temp_c": "65", "gpu_power_w": "134.18"}
2026-08-09 06:18:24 | INFO | train task=Ses04M epoch=4 batch=1076/2405 step=2075 loss=2.7795 ce=2.5753 mse=0.4085 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1422948837280273, "reserved_gb": 1.8359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "23", "gpu_mem_used_mb": "2225", "gpu_mem_total_mb": "12288", "gpu_temp_c": "54", "gpu_power_w": "64.76"}
2026-08-09 06:18:44 | INFO | train task=Ses04M epoch=4 batch=1176/2405 step=2100 loss=1.1122 ce=0.9493 mse=0.3257 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1468257904052734, "reserved_gb": 2.12109375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "32", "gpu_mem_used_mb": "2540", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "53.99"}
2026-08-09 06:19:09 | INFO | train task=Ses04M epoch=4 batch=1276/2405 step=2125 loss=1.4268 ce=1.3637 mse=0.1262 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.143228530883789, "reserved_gb": 2.037109375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "40", "gpu_mem_used_mb": "2454", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "48.58"}
2026-08-09 06:19:30 | INFO | train task=Ses04M epoch=4 batch=1376/2405 step=2150 loss=0.8840 ce=0.7312 mse=0.3057 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1413111686706543, "reserved_gb": 1.70703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "15", "gpu_mem_used_mb": "2116", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "63.42"}
2026-08-09 06:19:50 | INFO | train task=Ses04M epoch=4 batch=1476/2405 step=2175 loss=1.6794 ce=1.6728 mse=0.0133 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1442489624023438, "reserved_gb": 1.7265625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "44", "gpu_mem_used_mb": "2136", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "95.22"}
2026-08-09 06:20:12 | INFO | train task=Ses04M epoch=4 batch=1576/2405 step=2200 loss=1.2542 ce=1.1044 mse=0.2995 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.141456127166748, "reserved_gb": 1.8828125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "35", "gpu_mem_used_mb": "2296", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "77.94"}
2026-08-09 06:20:37 | INFO | train task=Ses04M epoch=4 batch=1676/2405 step=2225 loss=0.5723 ce=0.4866 mse=0.1714 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1413936614990234, "reserved_gb": 1.693359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "16", "gpu_mem_used_mb": "2102", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "64.62"}
2026-08-09 06:20:58 | INFO | train task=Ses04M epoch=4 batch=1776/2405 step=2250 loss=0.6466 ce=0.3718 mse=0.5497 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1412019729614258, "reserved_gb": 1.70703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "16", "gpu_mem_used_mb": "2116", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "81.31"}
2026-08-09 06:21:19 | INFO | train task=Ses04M epoch=4 batch=1876/2405 step=2275 loss=1.7719 ce=1.0157 mse=1.5123 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1420660018920898, "reserved_gb": 1.767578125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "26", "gpu_mem_used_mb": "2178", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "67.86"}
2026-08-09 06:21:43 | INFO | train task=Ses04M epoch=4 batch=1976/2405 step=2300 loss=0.5911 ce=0.3358 mse=0.5106 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1414203643798828, "reserved_gb": 1.884765625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "33", "gpu_mem_used_mb": "2298", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "67.31"}
2026-08-09 06:22:06 | INFO | train task=Ses04M epoch=4 batch=2076/2405 step=2325 loss=0.4693 ce=0.4486 mse=0.0414 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.141669750213623, "reserved_gb": 1.80078125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "10", "gpu_mem_used_mb": "2212", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "61.67"}
2026-08-09 06:22:28 | INFO | train task=Ses04M epoch=4 batch=2176/2405 step=2350 loss=0.7088 ce=0.3812 mse=0.6551 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1416974067687988, "reserved_gb": 1.705078125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "11", "gpu_mem_used_mb": "2114", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "70.73"}
2026-08-09 06:22:50 | INFO | train task=Ses04M epoch=4 batch=2276/2405 step=2375 loss=0.4296 ce=0.3748 mse=0.1098 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1442604064941406, "reserved_gb": 1.939453125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "12", "gpu_mem_used_mb": "2354", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "66.96"}
2026-08-09 06:23:15 | INFO | train task=Ses04M epoch=4 batch=2376/2405 step=2400 loss=1.5089 ce=1.4769 mse=0.0640 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.142064094543457, "reserved_gb": 1.716796875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "66", "gpu_mem_used_mb": "2126", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "100.45"}

predict:   0%|          | 0/328 [00:00<?, ?it/s]

2026-08-09 06:23:51 | INFO | Epoch 04 task=Ses04M train_loss=1.1085 val_macro_f1=0.3476 val_mae=0.5479 epoch_seconds=559.0

epoch 5:   0%|          | 0/2405 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 06:24:18 | INFO | train task=Ses04M epoch=5 batch=68/2405 step=2425 loss=0.6115 ce=0.5806 mse=0.0618 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.141340732574463, "reserved_gb": 1.958984375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "14", "gpu_mem_used_mb": "2300", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "65.32"}
2026-08-09 06:24:38 | INFO | train task=Ses04M epoch=5 batch=168/2405 step=2450 loss=1.3298 ce=0.8806 mse=0.8984 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1432747840881348, "reserved_gb": 1.8359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "78", "gpu_mem_used_mb": "2190", "gpu_mem_total_mb": "12288", "gpu_temp_c": "54", "gpu_power_w": "68.26"}
2026-08-09 06:24:59 | INFO | train task=Ses04M epoch=5 batch=268/2405 step=2475 loss=0.9586 ce=0.7961 mse=0.3250 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1419496536254883, "reserved_gb": 1.70703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "24", "gpu_mem_used_mb": "2090", "gpu_mem_total_mb": "12288", "gpu_temp_c": "54", "gpu_power_w": "78.16"}
2026-08-09 06:25:17 | INFO | train task=Ses04M epoch=5 batch=368/2405 step=2500 loss=0.5432 ce=0.4368 mse=0.2129 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1425676345825195, "reserved_gb": 1.875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "27", "gpu_mem_used_mb": "2265", "gpu_mem_total_mb": "12288", "gpu_temp_c": "53", "gpu_power_w": "43.97"}
2026-08-09 06:25:41 | INFO | train task=Ses04M epoch=5 batch=468/2405 step=2525 loss=1.0559 ce=1.0527 mse=0.0065 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1413111686706543, "reserved_gb": 1.75390625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "18", "gpu_mem_used_mb": "2141", "gpu_mem_total_mb": "12288", "gpu_temp_c": "54", "gpu_power_w": "58.17"}
2026-08-09 06:26:00 | INFO | train task=Ses04M epoch=5 batch=568/2405 step=2550 loss=0.1208 ce=0.1031 mse=0.0354 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.141894817352295, "reserved_gb": 2.140625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "74", "gpu_mem_used_mb": "2537", "gpu_mem_total_mb": "12288", "gpu_temp_c": "55", "gpu_power_w": "57.31"}
2026-08-09 06:26:20 | INFO | train task=Ses04M epoch=5 batch=668/2405 step=2575 loss=1.0380 ce=0.4098 mse=1.2564 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1421914100646973, "reserved_gb": 1.751953125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "13", "gpu_mem_used_mb": "2139", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "54.63"}
2026-08-09 06:26:40 | INFO | train task=Ses04M epoch=5 batch=768/2405 step=2600 loss=3.1573 ce=3.0684 mse=0.1779 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1415977478027344, "reserved_gb": 1.76171875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "41", "gpu_mem_used_mb": "2149", "gpu_mem_total_mb": "12288", "gpu_temp_c": "56", "gpu_power_w": "83.98"}
2026-08-09 06:27:04 | INFO | train task=Ses04M epoch=5 batch=868/2405 step=2625 loss=0.7990 ce=0.7017 mse=0.1947 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.143343448638916, "reserved_gb": 1.892578125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "35", "gpu_mem_used_mb": "2283", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "75.30"}
2026-08-09 06:27:24 | INFO | train task=Ses04M epoch=5 batch=968/2405 step=2650 loss=1.4890 ce=1.0813 mse=0.8155 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1418571472167969, "reserved_gb": 1.9140625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "24", "gpu_mem_used_mb": "2305", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "64.72"}
2026-08-09 06:27:44 | INFO | train task=Ses04M epoch=5 batch=1068/2405 step=2675 loss=0.9700 ce=0.9195 mse=0.1011 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1414127349853516, "reserved_gb": 2.326171875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "26", "gpu_mem_used_mb": "2727", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "60.00"}
2026-08-09 06:28:04 | INFO | train task=Ses04M epoch=5 batch=1168/2405 step=2700 loss=1.2048 ce=1.1741 mse=0.0613 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1421995162963867, "reserved_gb": 1.708984375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "29", "gpu_mem_used_mb": "2095", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "71.68"}
2026-08-09 06:28:27 | INFO | train task=Ses04M epoch=5 batch=1268/2405 step=2725 loss=1.8751 ce=1.5219 mse=0.7064 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1416950225830078, "reserved_gb": 1.705078125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "50", "gpu_mem_used_mb": "2091", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "74.32"}
2026-08-09 06:28:48 | INFO | train task=Ses04M epoch=5 batch=1368/2405 step=2750 loss=0.7796 ce=0.6181 mse=0.3229 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1415481567382812, "reserved_gb": 1.916015625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "29", "gpu_mem_used_mb": "2307", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "65.25"}
2026-08-09 06:29:09 | INFO | train task=Ses04M epoch=5 batch=1468/2405 step=2775 loss=0.5661 ce=0.3160 mse=0.5001 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1424660682678223, "reserved_gb": 1.826171875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "27", "gpu_mem_used_mb": "2215", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "79.41"}
2026-08-09 06:29:32 | INFO | train task=Ses04M epoch=5 batch=1568/2405 step=2800 loss=0.9713 ce=0.9148 mse=0.1131 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1414341926574707, "reserved_gb": 2.1640625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "34", "gpu_mem_used_mb": "2561", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "68.96"}
2026-08-09 06:29:56 | INFO | train task=Ses04M epoch=5 batch=1668/2405 step=2825 loss=1.0639 ce=0.8235 mse=0.4808 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1417417526245117, "reserved_gb": 1.833984375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "37", "gpu_mem_used_mb": "2223", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "69.68"}
2026-08-09 06:30:18 | INFO | train task=Ses04M epoch=5 batch=1768/2405 step=2850 loss=0.4643 ce=0.4180 mse=0.0926 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1417832374572754, "reserved_gb": 1.837890625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "28", "gpu_mem_used_mb": "2227", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "69.92"}
2026-08-09 06:30:41 | INFO | train task=Ses04M epoch=5 batch=1868/2405 step=2875 loss=1.4657 ce=1.4653 mse=0.0008 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1414318084716797, "reserved_gb": 1.794921875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "25", "gpu_mem_used_mb": "2183", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "82.39"}
2026-08-09 06:31:03 | INFO | train task=Ses04M epoch=5 batch=1968/2405 step=2900 loss=1.0287 ce=0.9605 mse=0.1363 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1418981552124023, "reserved_gb": 2.3359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "26", "gpu_mem_used_mb": "2737", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "60.31"}
2026-08-09 06:31:29 | INFO | train task=Ses04M epoch=5 batch=2068/2405 step=2925 loss=0.3282 ce=0.3007 mse=0.0550 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1431169509887695, "reserved_gb": 1.880859375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "30", "gpu_mem_used_mb": "2271", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "78.51"}
2026-08-09 06:31:53 | INFO | train task=Ses04M epoch=5 batch=2168/2405 step=2950 loss=1.2790 ce=1.2203 mse=0.1175 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.146824836730957, "reserved_gb": 1.765625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "48", "gpu_mem_used_mb": "2153", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "86.91"}
2026-08-09 06:32:15 | INFO | train task=Ses04M epoch=5 batch=2268/2405 step=2975 loss=0.5769 ce=0.4645 mse=0.2248 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1412935256958008, "reserved_gb": 1.77734375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "38", "gpu_mem_used_mb": "2165", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "77.48"}
2026-08-09 06:32:36 | INFO | train task=Ses04M epoch=5 batch=2368/2405 step=3000 loss=0.7321 ce=0.6461 mse=0.1720 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1414289474487305, "reserved_gb": 1.705078125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "18", "gpu_mem_used_mb": "2091", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "68.90"}

predict:   0%|          | 0/328 [00:00<?, ?it/s]

2026-08-09 06:33:10 | INFO | Epoch 05 task=Ses04M train_loss=0.9847 val_macro_f1=0.3837 val_mae=0.5500 epoch_seconds=555.6

epoch 6:   0%|          | 0/2405 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 06:33:30 | INFO | train task=Ses04M epoch=6 batch=60/2405 step=3025 loss=0.8750 ce=0.8369 mse=0.0763 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.146824836730957, "reserved_gb": 2.056640625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "50", "gpu_mem_used_mb": "2451", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "73.00"}
2026-08-09 06:33:49 | INFO | train task=Ses04M epoch=6 batch=160/2405 step=3050 loss=0.4383 ce=0.1884 mse=0.4997 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1413888931274414, "reserved_gb": 2.318359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "25", "gpu_mem_used_mb": "2719", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "70.95"}
2026-08-09 06:34:08 | INFO | train task=Ses04M epoch=6 batch=260/2405 step=3075 loss=0.2970 ce=0.1300 mse=0.3340 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1414542198181152, "reserved_gb": 2.146484375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "2543", "gpu_mem_total_mb": "12288", "gpu_temp_c": "53", "gpu_power_w": "70.71"}
2026-08-09 06:34:29 | INFO | train task=Ses04M epoch=6 batch=360/2405 step=3100 loss=0.4575 ce=0.3084 mse=0.2982 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1416468620300293, "reserved_gb": 1.7109375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "12", "gpu_mem_used_mb": "2097", "gpu_mem_total_mb": "12288", "gpu_temp_c": "53", "gpu_power_w": "62.84"}
2026-08-09 06:34:54 | INFO | train task=Ses04M epoch=6 batch=460/2405 step=3125 loss=0.3563 ce=0.0516 mse=0.6095 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1412358283996582, "reserved_gb": 1.76953125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "34", "gpu_mem_used_mb": "2157", "gpu_mem_total_mb": "12288", "gpu_temp_c": "57", "gpu_power_w": "70.90"}
2026-08-09 06:35:14 | INFO | train task=Ses04M epoch=6 batch=560/2405 step=3150 loss=1.7926 ce=1.6639 mse=0.2574 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1416726112365723, "reserved_gb": 1.953125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "23", "gpu_mem_used_mb": "2345", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "67.83"}
2026-08-09 06:35:34 | INFO | train task=Ses04M epoch=6 batch=660/2405 step=3175 loss=0.2808 ce=0.0742 mse=0.4133 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1423530578613281, "reserved_gb": 1.767578125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "32", "gpu_mem_used_mb": "2155", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "66.76"}
2026-08-09 06:35:54 | INFO | train task=Ses04M epoch=6 batch=760/2405 step=3200 loss=1.1090 ce=0.9406 mse=0.3368 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1413850784301758, "reserved_gb": 2.4140625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "2817", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "61.69"}
2026-08-09 06:36:17 | INFO | train task=Ses04M epoch=6 batch=860/2405 step=3225 loss=0.7930 ce=0.6783 mse=0.2293 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1418023109436035, "reserved_gb": 1.779296875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "24", "gpu_mem_used_mb": "2167", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "63.66"}
2026-08-09 06:36:38 | INFO | train task=Ses04M epoch=6 batch=960/2405 step=3250 loss=0.4753 ce=0.4471 mse=0.0564 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1418070793151855, "reserved_gb": 1.708984375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "2095", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "56.03"}
2026-08-09 06:36:58 | INFO | train task=Ses04M epoch=6 batch=1060/2405 step=3275 loss=0.3298 ce=0.1996 mse=0.2605 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.142354965209961, "reserved_gb": 1.794921875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "43", "gpu_mem_used_mb": "2183", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "79.63"}
2026-08-09 06:37:18 | INFO | train task=Ses04M epoch=6 batch=1160/2405 step=3300 loss=1.4630 ce=0.5882 mse=1.7495 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1414108276367188, "reserved_gb": 1.79296875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "30", "gpu_mem_used_mb": "2181", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "64.28"}
2026-08-09 06:37:41 | INFO | train task=Ses04M epoch=6 batch=1260/2405 step=3325 loss=2.2947 ce=1.9801 mse=0.6292 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1429181098937988, "reserved_gb": 1.703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "48", "gpu_mem_used_mb": "2089", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "66.88"}
2026-08-09 06:38:01 | INFO | train task=Ses04M epoch=6 batch=1360/2405 step=3350 loss=0.8153 ce=0.8071 mse=0.0164 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1415538787841797, "reserved_gb": 1.712890625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "61", "gpu_mem_used_mb": "2099", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "69.63"}
2026-08-09 06:38:22 | INFO | train task=Ses04M epoch=6 batch=1460/2405 step=3375 loss=0.3765 ce=0.1738 mse=0.4054 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1413612365722656, "reserved_gb": 1.73046875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "16", "gpu_mem_used_mb": "2117", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "74.45"}
2026-08-09 06:38:43 | INFO | train task=Ses04M epoch=6 batch=1560/2405 step=3400 loss=0.3647 ce=0.3021 mse=0.1253 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1423792839050293, "reserved_gb": 1.884765625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "16", "gpu_mem_used_mb": "2275", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "62.53"}
2026-08-09 06:39:08 | INFO | train task=Ses04M epoch=6 batch=1660/2405 step=3425 loss=0.3515 ce=0.1937 mse=0.3156 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1442914009094238, "reserved_gb": 1.75, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "66", "gpu_mem_used_mb": "2137", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "61.13"}
2026-08-09 06:39:30 | INFO | train task=Ses04M epoch=6 batch=1760/2405 step=3450 loss=0.3127 ce=0.2528 mse=0.1198 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1423397064208984, "reserved_gb": 1.7734375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "19", "gpu_mem_used_mb": "2161", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "63.51"}
2026-08-09 06:39:51 | INFO | train task=Ses04M epoch=6 batch=1860/2405 step=3475 loss=0.1630 ce=0.0326 mse=0.2608 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1421146392822266, "reserved_gb": 1.767578125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "23", "gpu_mem_used_mb": "2155", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "71.75"}
2026-08-09 06:40:11 | INFO | train task=Ses04M epoch=6 batch=1960/2405 step=3500 loss=0.1583 ce=0.1522 mse=0.0121 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.141617774963379, "reserved_gb": 2.2734375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "47", "gpu_mem_used_mb": "2673", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "69.41"}
2026-08-09 06:40:37 | INFO | train task=Ses04M epoch=6 batch=2060/2405 step=3525 loss=0.6081 ce=0.4147 mse=0.3870 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1414031982421875, "reserved_gb": 1.73046875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "16", "gpu_mem_used_mb": "2117", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "71.48"}
2026-08-09 06:40:59 | INFO | train task=Ses04M epoch=6 batch=2160/2405 step=3550 loss=1.8585 ce=1.6762 mse=0.3645 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1420707702636719, "reserved_gb": 1.70703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "51", "gpu_mem_used_mb": "2093", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "79.84"}
2026-08-09 06:41:22 | INFO | train task=Ses04M epoch=6 batch=2260/2405 step=3575 loss=0.3343 ce=0.3116 mse=0.0454 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1430015563964844, "reserved_gb": 1.7109375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "8", "gpu_mem_used_mb": "2097", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "69.75"}
2026-08-09 06:41:46 | INFO | train task=Ses04M epoch=6 batch=2360/2405 step=3600 loss=0.3342 ce=0.2839 mse=0.1007 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.146824836730957, "reserved_gb": 1.75, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "2137", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "65.79"}

predict:   0%|          | 0/328 [00:00<?, ?it/s]

2026-08-09 06:42:21 | INFO | Epoch 06 task=Ses04M train_loss=0.8829 val_macro_f1=0.3840 val_mae=0.5490 epoch_seconds=545.8

epoch 7:   0%|          | 0/2405 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 06:42:41 | INFO | train task=Ses04M epoch=7 batch=52/2405 step=3625 loss=0.2580 ce=0.2182 mse=0.0795 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.141554832458496, "reserved_gb": 1.9140625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "30", "gpu_mem_used_mb": "2295", "gpu_mem_total_mb": "12288", "gpu_temp_c": "43", "gpu_power_w": "50.44"}
2026-08-09 06:43:01 | INFO | train task=Ses04M epoch=7 batch=152/2405 step=3650 loss=2.0643 ce=1.5753 mse=0.9779 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.142749309539795, "reserved_gb": 1.859375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "2239", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "72.06"}
2026-08-09 06:43:20 | INFO | train task=Ses04M epoch=7 batch=252/2405 step=3675 loss=0.3998 ce=0.2472 mse=0.3052 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1416106224060059, "reserved_gb": 1.70703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "19", "gpu_mem_used_mb": "2091", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "63.38"}
2026-08-09 06:43:40 | INFO | train task=Ses04M epoch=7 batch=352/2405 step=3700 loss=1.1003 ce=0.1913 mse=1.8179 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1440682411193848, "reserved_gb": 2.244140625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "39", "gpu_mem_used_mb": "2643", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "60.34"}
2026-08-09 06:44:03 | INFO | train task=Ses04M epoch=7 batch=452/2405 step=3725 loss=0.8326 ce=0.5126 mse=0.6399 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1413888931274414, "reserved_gb": 1.7890625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "23", "gpu_mem_used_mb": "2177", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "68.31"}
2026-08-09 06:44:22 | INFO | train task=Ses04M epoch=7 batch=552/2405 step=3750 loss=0.3014 ce=0.2853 mse=0.0322 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1417655944824219, "reserved_gb": 1.875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "2265", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "77.65"}
2026-08-09 06:44:42 | INFO | train task=Ses04M epoch=7 batch=652/2405 step=3775 loss=1.3858 ce=1.3550 mse=0.0616 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1415653228759766, "reserved_gb": 1.845703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "25", "gpu_mem_used_mb": "2235", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "63.68"}
2026-08-09 06:45:02 | INFO | train task=Ses04M epoch=7 batch=752/2405 step=3800 loss=0.8624 ce=0.6875 mse=0.3498 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.141718864440918, "reserved_gb": 1.9765625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "19", "gpu_mem_used_mb": "2369", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "65.20"}
2026-08-09 06:45:25 | INFO | train task=Ses04M epoch=7 batch=852/2405 step=3825 loss=0.0630 ce=0.0579 mse=0.0102 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1433281898498535, "reserved_gb": 2.224609375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "15", "gpu_mem_used_mb": "2623", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "68.52"}
2026-08-09 06:45:46 | INFO | train task=Ses04M epoch=7 batch=952/2405 step=3850 loss=1.1579 ce=0.7296 mse=0.8567 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1414761543273926, "reserved_gb": 2.25, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "23", "gpu_mem_used_mb": "2649", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "59.70"}
2026-08-09 06:46:07 | INFO | train task=Ses04M epoch=7 batch=1052/2405 step=3875 loss=0.8445 ce=0.7172 mse=0.2546 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.141432285308838, "reserved_gb": 1.7578125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "2145", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "84.74"}
2026-08-09 06:46:28 | INFO | train task=Ses04M epoch=7 batch=1152/2405 step=3900 loss=2.6542 ce=2.6453 mse=0.0178 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1412057876586914, "reserved_gb": 1.720703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "2107", "gpu_mem_total_mb": "12288", "gpu_temp_c": "54", "gpu_power_w": "80.85"}
2026-08-09 06:46:51 | INFO | train task=Ses04M epoch=7 batch=1252/2405 step=3925 loss=1.0916 ce=1.0657 mse=0.0520 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1413321495056152, "reserved_gb": 2.041015625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "19", "gpu_mem_used_mb": "2435", "gpu_mem_total_mb": "12288", "gpu_temp_c": "55", "gpu_power_w": "63.97"}
2026-08-09 06:47:13 | INFO | train task=Ses04M epoch=7 batch=1352/2405 step=3950 loss=0.0964 ce=0.0422 mse=0.1084 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1421961784362793, "reserved_gb": 1.974609375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "27", "gpu_mem_used_mb": "2367", "gpu_mem_total_mb": "12288", "gpu_temp_c": "56", "gpu_power_w": "55.38"}
2026-08-09 06:47:35 | INFO | train task=Ses04M epoch=7 batch=1452/2405 step=3975 loss=0.2203 ce=0.1850 mse=0.0705 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.142868995666504, "reserved_gb": 1.744140625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "19", "gpu_mem_used_mb": "2131", "gpu_mem_total_mb": "12288", "gpu_temp_c": "54", "gpu_power_w": "72.62"}
2026-08-09 06:47:57 | INFO | train task=Ses04M epoch=7 batch=1552/2405 step=4000 loss=2.2441 ce=1.2541 mse=1.9800 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1423888206481934, "reserved_gb": 1.70703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "24", "gpu_mem_used_mb": "2093", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "80.95"}
2026-08-09 06:48:22 | INFO | train task=Ses04M epoch=7 batch=1652/2405 step=4025 loss=0.2093 ce=0.1552 mse=0.1082 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1416964530944824, "reserved_gb": 1.73046875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "37", "gpu_mem_used_mb": "2117", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "87.75"}
2026-08-09 06:48:44 | INFO | train task=Ses04M epoch=7 batch=1752/2405 step=4050 loss=1.6626 ce=0.5387 mse=2.2477 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1413092613220215, "reserved_gb": 1.775390625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "29", "gpu_mem_used_mb": "2163", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "47.30"}
2026-08-09 06:49:05 | INFO | train task=Ses04M epoch=7 batch=1852/2405 step=4075 loss=0.6191 ce=0.6023 mse=0.0336 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.141578197479248, "reserved_gb": 1.984375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "2377", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "70.26"}
2026-08-09 06:49:27 | INFO | train task=Ses04M epoch=7 batch=1952/2405 step=4100 loss=0.4329 ce=0.3909 mse=0.0841 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1415095329284668, "reserved_gb": 1.708984375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "2095", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "72.18"}
2026-08-09 06:49:52 | INFO | train task=Ses04M epoch=7 batch=2052/2405 step=4125 loss=0.0547 ce=0.0499 mse=0.0096 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.141432285308838, "reserved_gb": 1.83984375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "23", "gpu_mem_used_mb": "2229", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "87.11"}
2026-08-09 06:50:14 | INFO | train task=Ses04M epoch=7 batch=2152/2405 step=4150 loss=0.6284 ce=0.5167 mse=0.2234 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1415104866027832, "reserved_gb": 1.708984375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "2095", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "74.15"}
2026-08-09 06:50:39 | INFO | train task=Ses04M epoch=7 batch=2252/2405 step=4175 loss=0.1033 ce=0.0750 mse=0.0566 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1413226127624512, "reserved_gb": 1.6875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "25", "gpu_mem_used_mb": "2073", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "72.41"}
2026-08-09 06:51:01 | INFO | train task=Ses04M epoch=7 batch=2352/2405 step=4200 loss=0.9532 ce=0.8307 mse=0.2450 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1413216590881348, "reserved_gb": 1.896484375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "19", "gpu_mem_used_mb": "2287", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "76.19"}

predict:   0%|          | 0/328 [00:00<?, ?it/s]

2026-08-09 06:51:44 | INFO | Epoch 07 task=Ses04M train_loss=0.7851 val_macro_f1=0.3759 val_mae=0.5428 epoch_seconds=557.8

epoch 8:   0%|          | 0/2405 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 06:51:58 | INFO | train task=Ses04M epoch=8 batch=44/2405 step=4225 loss=0.5432 ce=0.3076 mse=0.4713 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.142186164855957, "reserved_gb": 2.341796875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "36", "gpu_mem_used_mb": "2665", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "71.23"}
2026-08-09 06:52:17 | INFO | train task=Ses04M epoch=8 batch=144/2405 step=4250 loss=0.5125 ce=0.1624 mse=0.7001 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1430950164794922, "reserved_gb": 1.779296875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "2125", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "59.97"}
2026-08-09 06:52:36 | INFO | train task=Ses04M epoch=8 batch=244/2405 step=4275 loss=1.8802 ce=1.8174 mse=0.1256 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1418609619140625, "reserved_gb": 2.0, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "37", "gpu_mem_used_mb": "2351", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "66.07"}
2026-08-09 06:52:55 | INFO | train task=Ses04M epoch=8 batch=344/2405 step=4300 loss=0.1876 ce=0.0471 mse=0.2810 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1418657302856445, "reserved_gb": 2.048828125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "32", "gpu_mem_used_mb": "2401", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "61.80"}
2026-08-09 06:53:18 | INFO | train task=Ses04M epoch=8 batch=444/2405 step=4325 loss=1.3388 ce=1.1787 mse=0.3203 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.142348289489746, "reserved_gb": 1.97265625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "42", "gpu_mem_used_mb": "2325", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "88.69"}
2026-08-09 06:53:39 | INFO | train task=Ses04M epoch=8 batch=544/2405 step=4350 loss=0.0600 ce=0.0111 mse=0.0977 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.146824836730957, "reserved_gb": 2.130859375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "38", "gpu_mem_used_mb": "2487", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "78.79"}
2026-08-09 06:53:59 | INFO | train task=Ses04M epoch=8 batch=644/2405 step=4375 loss=1.6252 ce=1.3683 mse=0.5139 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.146824836730957, "reserved_gb": 1.771484375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "78", "gpu_mem_used_mb": "2119", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "81.97"}
2026-08-09 06:54:19 | INFO | train task=Ses04M epoch=8 batch=744/2405 step=4400 loss=0.7081 ce=0.6893 mse=0.0375 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1414709091186523, "reserved_gb": 2.265625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "53", "gpu_mem_used_mb": "2625", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "69.16"}
2026-08-09 06:54:41 | INFO | train task=Ses04M epoch=8 batch=844/2405 step=4425 loss=0.1452 ce=0.0062 mse=0.2780 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1432814598083496, "reserved_gb": 1.728515625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "44", "gpu_mem_used_mb": "2075", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "62.20"}
2026-08-09 06:55:01 | INFO | train task=Ses04M epoch=8 batch=944/2405 step=4450 loss=1.2177 ce=0.9798 mse=0.4757 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.141794204711914, "reserved_gb": 1.833984375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "36", "gpu_mem_used_mb": "2183", "gpu_mem_total_mb": "12288", "gpu_temp_c": "43", "gpu_power_w": "41.04"}
2026-08-09 06:55:22 | INFO | train task=Ses04M epoch=8 batch=1044/2405 step=4475 loss=0.9064 ce=0.7887 mse=0.2355 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1412649154663086, "reserved_gb": 1.70703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "24", "gpu_mem_used_mb": "2053", "gpu_mem_total_mb": "12288", "gpu_temp_c": "43", "gpu_power_w": "50.52"}
2026-08-09 06:55:43 | INFO | train task=Ses04M epoch=8 batch=1144/2405 step=4500 loss=0.2687 ce=0.0194 mse=0.4985 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1422743797302246, "reserved_gb": 1.70703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "2053", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "73.65"}
2026-08-09 06:56:08 | INFO | train task=Ses04M epoch=8 batch=1244/2405 step=4525 loss=0.5989 ce=0.5849 mse=0.0280 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1416611671447754, "reserved_gb": 1.705078125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "2051", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "68.86"}
2026-08-09 06:56:28 | INFO | train task=Ses04M epoch=8 batch=1344/2405 step=4550 loss=0.2399 ce=0.2117 mse=0.0565 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.141533374786377, "reserved_gb": 1.74609375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "19", "gpu_mem_used_mb": "2094", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "57.06"}
2026-08-09 06:56:51 | INFO | train task=Ses04M epoch=8 batch=1444/2405 step=4575 loss=0.9478 ce=0.8963 mse=0.1031 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1414098739624023, "reserved_gb": 1.689453125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "31", "gpu_mem_used_mb": "2036", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "62.94"}
2026-08-09 06:57:12 | INFO | train task=Ses04M epoch=8 batch=1544/2405 step=4600 loss=1.2018 ce=1.1465 mse=0.1107 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1414761543273926, "reserved_gb": 1.755859375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "2104", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "81.14"}
2026-08-09 06:57:37 | INFO | train task=Ses04M epoch=8 batch=1644/2405 step=4625 loss=0.2966 ce=0.0223 mse=0.5487 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.141946792602539, "reserved_gb": 1.76953125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "27", "gpu_mem_used_mb": "2118", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "56.36"}
2026-08-09 06:57:59 | INFO | train task=Ses04M epoch=8 batch=1744/2405 step=4650 loss=5.2655 ce=4.8628 mse=0.8054 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1413354873657227, "reserved_gb": 1.779296875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "30", "gpu_mem_used_mb": "2128", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "78.64"}
2026-08-09 06:58:19 | INFO | train task=Ses04M epoch=8 batch=1844/2405 step=4675 loss=2.7880 ce=1.9554 mse=1.6652 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1418499946594238, "reserved_gb": 1.708984375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "23", "gpu_mem_used_mb": "2056", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "65.79"}
2026-08-09 06:58:41 | INFO | train task=Ses04M epoch=8 batch=1944/2405 step=4700 loss=0.2066 ce=0.1059 mse=0.2015 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1434412002563477, "reserved_gb": 1.728515625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "40", "gpu_mem_used_mb": "2076", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "54.13"}
2026-08-09 06:59:08 | INFO | train task=Ses04M epoch=8 batch=2044/2405 step=4725 loss=0.5206 ce=0.3299 mse=0.3815 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.14298677444458, "reserved_gb": 1.708984375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "73", "gpu_mem_used_mb": "2056", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "54.37"}
2026-08-09 06:59:30 | INFO | train task=Ses04M epoch=8 batch=2144/2405 step=4750 loss=0.9063 ce=0.8461 mse=0.1204 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1418023109436035, "reserved_gb": 1.775390625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "10", "gpu_mem_used_mb": "2124", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "70.99"}
2026-08-09 06:59:53 | INFO | train task=Ses04M epoch=8 batch=2244/2405 step=4775 loss=1.2538 ce=0.9148 mse=0.6779 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1420350074768066, "reserved_gb": 1.703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "35", "gpu_mem_used_mb": "2050", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "72.54"}
2026-08-09 07:00:16 | INFO | train task=Ses04M epoch=8 batch=2344/2405 step=4800 loss=0.6456 ce=0.4921 mse=0.3070 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1426033973693848, "reserved_gb": 1.845703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "23", "gpu_mem_used_mb": "2196", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "80.41"}

predict:   0%|          | 0/328 [00:00<?, ?it/s]

2026-08-09 07:00:58 | INFO | Epoch 08 task=Ses04M train_loss=0.7115 val_macro_f1=0.3825 val_mae=0.5454 epoch_seconds=551.4

predict:   0%|          | 0/264 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)

predict:   0%|          | 0/405 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
2026-08-09 07:02:36 | INFO | Task 2dc40c69dc08c922_main_fold -> complete
2026-08-09 07:02:38 | INFO | Manuscript outputs refreshed: 21 tables, 4 figures
2026-08-09 07:02:38 | INFO | Task de641ed1d0ddc4dc_main_fold -> running
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\transformers\configuration_utils.py:335: UserWarning: Passing `gradient_checkpointing` to a config initialization is deprecated and will be removed in v5 Transformers. Using `model.gradient_checkpointing_enable()` instead, or if you are using the `Trainer` API, pass `gradient_checkpointing=True` in your `TrainingArguments`.
  warnings.warn(
2026-08-09 07:02:40 | INFO | Task C:\Users\HaseebWajid\Downloads\runs\dersx_paper_aligned\campaign_01\main\seed_13\Ses05F parameters={'total': 163009451, 'trainable': 69034283, 'frozen': 93975168} scope={'corpus': 'IEMOCAP', 'protocol': 'strict_LOSO', 'heldout_speaker': 'Ses05F', 'seed': 13, 'stage': 'main', 'profile': 'rtx3060_24h'}

epoch 1:   0%|          | 0/2378 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 07:03:04 | INFO | train task=Ses05F epoch=1 batch=100/2378 step=25 loss=2.2023 ce=2.0557 mse=0.2932 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2649455070495605, "reserved_gb": 2.875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "3274", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "62.92"}
2026-08-09 07:03:28 | INFO | train task=Ses05F epoch=1 batch=200/2378 step=50 loss=2.4598 ce=2.2306 mse=0.4584 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2646427154541016, "reserved_gb": 2.841796875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "28", "gpu_mem_used_mb": "3240", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "66.38"}
2026-08-09 07:03:49 | INFO | train task=Ses05F epoch=1 batch=300/2378 step=75 loss=2.9767 ce=2.0568 mse=1.8398 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2650508880615234, "reserved_gb": 2.880859375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "27", "gpu_mem_used_mb": "3280", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "60.81"}
2026-08-09 07:04:12 | INFO | train task=Ses05F epoch=1 batch=400/2378 step=100 loss=2.2799 ce=1.9954 mse=0.5690 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2656068801879883, "reserved_gb": 2.8515625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "50", "gpu_mem_used_mb": "3250", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "68.76"}
2026-08-09 07:04:37 | INFO | train task=Ses05F epoch=1 batch=500/2378 step=125 loss=2.4257 ce=2.0430 mse=0.7655 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2650132179260254, "reserved_gb": 2.853515625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "3252", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "82.56"}
2026-08-09 07:05:00 | INFO | train task=Ses05F epoch=1 batch=600/2378 step=150 loss=1.9949 ce=1.8047 mse=0.3805 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.264815330505371, "reserved_gb": 2.8984375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "67", "gpu_mem_used_mb": "3298", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "74.00"}
2026-08-09 07:05:23 | INFO | train task=Ses05F epoch=1 batch=700/2378 step=175 loss=1.9886 ce=1.8745 mse=0.2282 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.26499605178833, "reserved_gb": 2.85546875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "24", "gpu_mem_used_mb": "3254", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "82.97"}
2026-08-09 07:05:45 | INFO | train task=Ses05F epoch=1 batch=800/2378 step=200 loss=1.7883 ce=1.7862 mse=0.0041 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2647762298583984, "reserved_gb": 2.84375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "37", "gpu_mem_used_mb": "3242", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "76.03"}
2026-08-09 07:06:11 | INFO | train task=Ses05F epoch=1 batch=900/2378 step=225 loss=2.4055 ce=1.4258 mse=1.9595 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2653722763061523, "reserved_gb": 3.09375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "12", "gpu_mem_used_mb": "3498", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "67.42"}
2026-08-09 07:06:33 | INFO | train task=Ses05F epoch=1 batch=1000/2378 step=250 loss=2.2015 ce=1.3872 mse=1.6287 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.265007495880127, "reserved_gb": 3.017578125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "3420", "gpu_mem_total_mb": "12288", "gpu_temp_c": "44", "gpu_power_w": "49.42"}
2026-08-09 07:06:58 | INFO | train task=Ses05F epoch=1 batch=1100/2378 step=275 loss=1.5728 ce=1.2158 mse=0.7140 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2673702239990234, "reserved_gb": 2.98828125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "18", "gpu_mem_used_mb": "3390", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "74.03"}
2026-08-09 07:07:22 | INFO | train task=Ses05F epoch=1 batch=1200/2378 step=300 loss=1.7964 ce=1.7242 mse=0.1445 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.265414237976074, "reserved_gb": 3.154296875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "32", "gpu_mem_used_mb": "3560", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "79.83"}
2026-08-09 07:07:49 | INFO | train task=Ses05F epoch=1 batch=1300/2378 step=325 loss=1.7849 ce=1.7360 mse=0.0978 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.269026756286621, "reserved_gb": 2.9453125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "47", "gpu_mem_used_mb": "3346", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "79.93"}
2026-08-09 07:08:12 | INFO | train task=Ses05F epoch=1 batch=1400/2378 step=350 loss=2.0394 ce=1.9140 mse=0.2508 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.265540599822998, "reserved_gb": 2.892578125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "26", "gpu_mem_used_mb": "3292", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "74.76"}
2026-08-09 07:08:36 | INFO | train task=Ses05F epoch=1 batch=1500/2378 step=375 loss=2.1311 ce=1.8840 mse=0.4942 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2652268409729004, "reserved_gb": 2.8359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "59", "gpu_mem_used_mb": "3234", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "54.83"}
2026-08-09 07:08:59 | INFO | train task=Ses05F epoch=1 batch=1600/2378 step=400 loss=1.3007 ce=1.2223 mse=0.1568 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.264735221862793, "reserved_gb": 2.86328125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "24", "gpu_mem_used_mb": "3262", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "83.05"}
2026-08-09 07:09:26 | INFO | train task=Ses05F epoch=1 batch=1700/2378 step=425 loss=1.8226 ce=1.6031 mse=0.4389 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2651424407958984, "reserved_gb": 2.857421875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "34", "gpu_mem_used_mb": "3256", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "75.92"}
2026-08-09 07:09:50 | INFO | train task=Ses05F epoch=1 batch=1800/2378 step=450 loss=0.7608 ce=0.3754 mse=0.7709 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2714896202087402, "reserved_gb": 2.9609375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "59", "gpu_mem_used_mb": "3362", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "94.20"}
2026-08-09 07:10:13 | INFO | train task=Ses05F epoch=1 batch=1900/2378 step=475 loss=2.0466 ce=1.9961 mse=0.1011 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2650933265686035, "reserved_gb": 2.896484375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "14", "gpu_mem_used_mb": "3296", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "70.71"}
2026-08-09 07:10:39 | INFO | train task=Ses05F epoch=1 batch=2000/2378 step=500 loss=2.3528 ce=2.1231 mse=0.4595 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2646121978759766, "reserved_gb": 2.8359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "3234", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "63.33"}
2026-08-09 07:11:06 | INFO | train task=Ses05F epoch=1 batch=2100/2378 step=525 loss=1.9751 ce=1.7164 mse=0.5173 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2649741172790527, "reserved_gb": 2.85546875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "19", "gpu_mem_used_mb": "3254", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "65.71"}
2026-08-09 07:11:30 | INFO | train task=Ses05F epoch=1 batch=2200/2378 step=550 loss=1.9131 ce=1.9083 mse=0.0097 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2653212547302246, "reserved_gb": 2.8359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "43", "gpu_mem_used_mb": "3234", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "71.37"}
2026-08-09 07:11:55 | INFO | train task=Ses05F epoch=1 batch=2300/2378 step=575 loss=2.9881 ce=2.6650 mse=0.6461 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2681140899658203, "reserved_gb": 2.888671875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "23", "gpu_mem_used_mb": "3288", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "76.00"}

predict:   0%|          | 0/303 [00:00<?, ?it/s]

2026-08-09 07:12:51 | INFO | Epoch 01 task=Ses05F train_loss=2.0695 val_macro_f1=0.4798 val_mae=0.5607 epoch_seconds=609.4

epoch 2:   0%|          | 0/2378 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 07:12:59 | INFO | train task=Ses05F epoch=2 batch=20/2378 step=600 loss=1.8957 ce=1.8321 mse=0.1272 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.266275405883789, "reserved_gb": 3.34375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "29", "gpu_mem_used_mb": "3754", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "67.52"}
2026-08-09 07:13:24 | INFO | train task=Ses05F epoch=2 batch=120/2378 step=625 loss=1.7414 ce=1.7197 mse=0.0435 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.264664649963379, "reserved_gb": 2.806640625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "3204", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "65.57"}
2026-08-09 07:13:43 | INFO | train task=Ses05F epoch=2 batch=220/2378 step=650 loss=0.7564 ce=0.6581 mse=0.1966 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2661752700805664, "reserved_gb": 3.271484375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "29", "gpu_mem_used_mb": "3680", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "62.81"}
2026-08-09 07:14:03 | INFO | train task=Ses05F epoch=2 batch=320/2378 step=675 loss=2.2793 ce=2.1304 mse=0.2977 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1429119110107422, "reserved_gb": 2.01953125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "23", "gpu_mem_used_mb": "2398", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "67.13"}
2026-08-09 07:14:22 | INFO | train task=Ses05F epoch=2 batch=420/2378 step=700 loss=1.2380 ce=0.9554 mse=0.5653 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1425814628601074, "reserved_gb": 2.146484375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "47", "gpu_mem_used_mb": "2528", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "65.55"}
2026-08-09 07:14:46 | INFO | train task=Ses05F epoch=2 batch=520/2378 step=725 loss=1.6009 ce=1.3426 mse=0.5166 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1426191329956055, "reserved_gb": 1.94140625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "39", "gpu_mem_used_mb": "2318", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "66.22"}
2026-08-09 07:15:05 | INFO | train task=Ses05F epoch=2 batch=620/2378 step=750 loss=3.0929 ce=3.0615 mse=0.0629 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1425538063049316, "reserved_gb": 2.4609375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "19", "gpu_mem_used_mb": "2850", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "73.42"}
2026-08-09 07:15:25 | INFO | train task=Ses05F epoch=2 batch=720/2378 step=775 loss=1.5857 ce=1.4005 mse=0.3704 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1452069282531738, "reserved_gb": 1.92578125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "36", "gpu_mem_used_mb": "2302", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "82.59"}
2026-08-09 07:15:46 | INFO | train task=Ses05F epoch=2 batch=820/2378 step=800 loss=0.4040 ce=0.4037 mse=0.0007 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.142554759979248, "reserved_gb": 1.939453125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "41", "gpu_mem_used_mb": "2316", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "73.76"}
2026-08-09 07:16:09 | INFO | train task=Ses05F epoch=2 batch=920/2378 step=825 loss=1.6612 ce=1.5990 mse=0.1245 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1423015594482422, "reserved_gb": 2.25390625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "15", "gpu_mem_used_mb": "2638", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "70.17"}
2026-08-09 07:16:30 | INFO | train task=Ses05F epoch=2 batch=1020/2378 step=850 loss=1.1541 ce=1.1515 mse=0.0052 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.144371509552002, "reserved_gb": 2.44921875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "44", "gpu_mem_used_mb": "2838", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "74.76"}
2026-08-09 07:16:51 | INFO | train task=Ses05F epoch=2 batch=1120/2378 step=875 loss=0.8324 ce=0.6917 mse=0.2814 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1427254676818848, "reserved_gb": 2.181640625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "25", "gpu_mem_used_mb": "2564", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "57.01"}
2026-08-09 07:17:10 | INFO | train task=Ses05F epoch=2 batch=1220/2378 step=900 loss=2.0839 ce=2.0643 mse=0.0392 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1443252563476562, "reserved_gb": 1.92578125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "24", "gpu_mem_used_mb": "2302", "gpu_mem_total_mb": "12288", "gpu_temp_c": "43", "gpu_power_w": "43.63"}
2026-08-09 07:17:34 | INFO | train task=Ses05F epoch=2 batch=1320/2378 step=925 loss=0.3258 ce=0.3087 mse=0.0341 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1433444023132324, "reserved_gb": 1.923828125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "19", "gpu_mem_used_mb": "2300", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "57.39"}
2026-08-09 07:17:55 | INFO | train task=Ses05F epoch=2 batch=1420/2378 step=950 loss=1.2069 ce=1.1694 mse=0.0750 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.142296314239502, "reserved_gb": 1.927734375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "16", "gpu_mem_used_mb": "2304", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "78.84"}
2026-08-09 07:18:16 | INFO | train task=Ses05F epoch=2 batch=1520/2378 step=975 loss=1.9226 ce=1.6078 mse=0.6296 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1423845291137695, "reserved_gb": 2.14453125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "34", "gpu_mem_used_mb": "2526", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "72.03"}
2026-08-09 07:18:37 | INFO | train task=Ses05F epoch=2 batch=1620/2378 step=1000 loss=2.4372 ce=2.3890 mse=0.0965 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.142446517944336, "reserved_gb": 1.9296875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "14", "gpu_mem_used_mb": "2306", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "77.15"}
2026-08-09 07:19:03 | INFO | train task=Ses05F epoch=2 batch=1720/2378 step=1025 loss=0.2338 ce=0.2256 mse=0.0165 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1422672271728516, "reserved_gb": 1.9296875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "32", "gpu_mem_used_mb": "2306", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "91.37"}
2026-08-09 07:19:24 | INFO | train task=Ses05F epoch=2 batch=1820/2378 step=1050 loss=3.0293 ce=2.7595 mse=0.5396 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1426043510437012, "reserved_gb": 1.939453125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "23", "gpu_mem_used_mb": "2316", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "91.14"}
2026-08-09 07:19:46 | INFO | train task=Ses05F epoch=2 batch=1920/2378 step=1075 loss=1.4116 ce=1.2753 mse=0.2726 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1425037384033203, "reserved_gb": 2.287109375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "2672", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "56.16"}
2026-08-09 07:20:08 | INFO | train task=Ses05F epoch=2 batch=2020/2378 step=1100 loss=1.6038 ce=1.2992 mse=0.6091 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.142878532409668, "reserved_gb": 1.923828125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "36", "gpu_mem_used_mb": "2300", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "90.56"}
2026-08-09 07:20:32 | INFO | train task=Ses05F epoch=2 batch=2120/2378 step=1125 loss=1.9263 ce=1.6890 mse=0.4747 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1424474716186523, "reserved_gb": 1.94140625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "14", "gpu_mem_used_mb": "2318", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "66.89"}
2026-08-09 07:20:53 | INFO | train task=Ses05F epoch=2 batch=2220/2378 step=1150 loss=1.4562 ce=0.6600 mse=1.5924 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.142848014831543, "reserved_gb": 1.923828125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "31", "gpu_mem_used_mb": "2300", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "70.48"}
2026-08-09 07:21:17 | INFO | train task=Ses05F epoch=2 batch=2320/2378 step=1175 loss=1.0913 ce=0.8701 mse=0.4424 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1429476737976074, "reserved_gb": 2.001953125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "24", "gpu_mem_used_mb": "2380", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "80.49"}

predict:   0%|          | 0/303 [00:00<?, ?it/s]

2026-08-09 07:21:52 | INFO | Epoch 02 task=Ses05F train_loss=1.4887 val_macro_f1=0.4740 val_mae=0.5684 epoch_seconds=536.5

epoch 3:   0%|          | 0/2378 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 07:22:03 | INFO | train task=Ses05F epoch=3 batch=40/2378 step=1200 loss=1.3276 ce=1.2701 mse=0.1149 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.144279956817627, "reserved_gb": 2.287109375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "41", "gpu_mem_used_mb": "2656", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "55.18"}
2026-08-09 07:22:27 | INFO | train task=Ses05F epoch=3 batch=140/2378 step=1225 loss=1.4228 ce=0.8138 mse=1.2180 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.142714023590088, "reserved_gb": 2.521484375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "25", "gpu_mem_used_mb": "2896", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "69.32"}
2026-08-09 07:22:47 | INFO | train task=Ses05F epoch=3 batch=240/2378 step=1250 loss=0.3858 ce=0.2212 mse=0.3292 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1426730155944824, "reserved_gb": 1.943359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "2304", "gpu_mem_total_mb": "12288", "gpu_temp_c": "53", "gpu_power_w": "70.48"}
2026-08-09 07:23:07 | INFO | train task=Ses05F epoch=3 batch=340/2378 step=1275 loss=1.3671 ce=1.3665 mse=0.0011 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1450676918029785, "reserved_gb": 2.310546875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "61", "gpu_mem_used_mb": "2680", "gpu_mem_total_mb": "12288", "gpu_temp_c": "56", "gpu_power_w": "79.08"}
2026-08-09 07:23:27 | INFO | train task=Ses05F epoch=3 batch=440/2378 step=1300 loss=1.3195 ce=0.7856 mse=1.0676 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1437692642211914, "reserved_gb": 2.01953125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "28", "gpu_mem_used_mb": "2382", "gpu_mem_total_mb": "12288", "gpu_temp_c": "56", "gpu_power_w": "68.93"}
2026-08-09 07:23:50 | INFO | train task=Ses05F epoch=3 batch=540/2378 step=1325 loss=0.9293 ce=0.8186 mse=0.2214 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1424970626831055, "reserved_gb": 1.931640625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "2292", "gpu_mem_total_mb": "12288", "gpu_temp_c": "57", "gpu_power_w": "60.76"}
2026-08-09 07:24:10 | INFO | train task=Ses05F epoch=3 batch=640/2378 step=1350 loss=0.3110 ce=0.1564 mse=0.3092 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.142655849456787, "reserved_gb": 2.515625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "2890", "gpu_mem_total_mb": "12288", "gpu_temp_c": "53", "gpu_power_w": "78.00"}
2026-08-09 07:24:30 | INFO | train task=Ses05F epoch=3 batch=740/2378 step=1375 loss=1.2605 ce=0.9423 mse=0.6365 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1437020301818848, "reserved_gb": 2.021484375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "49", "gpu_mem_used_mb": "2384", "gpu_mem_total_mb": "12288", "gpu_temp_c": "56", "gpu_power_w": "89.63"}
2026-08-09 07:24:50 | INFO | train task=Ses05F epoch=3 batch=840/2378 step=1400 loss=0.3273 ce=0.3004 mse=0.0538 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1432075500488281, "reserved_gb": 1.94140625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "2302", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "71.52"}
2026-08-09 07:25:14 | INFO | train task=Ses05F epoch=3 batch=940/2378 step=1425 loss=1.0670 ce=0.8868 mse=0.3605 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1478939056396484, "reserved_gb": 2.693359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "30", "gpu_mem_used_mb": "3072", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "62.16"}
2026-08-09 07:25:34 | INFO | train task=Ses05F epoch=3 batch=1040/2378 step=1450 loss=1.2968 ce=1.2942 mse=0.0053 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1425514221191406, "reserved_gb": 1.947265625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "18", "gpu_mem_used_mb": "2308", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "74.58"}
2026-08-09 07:25:55 | INFO | train task=Ses05F epoch=3 batch=1140/2378 step=1475 loss=1.5456 ce=1.2372 mse=0.6168 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1426348686218262, "reserved_gb": 2.015625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "18", "gpu_mem_used_mb": "2378", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "73.86"}
2026-08-09 07:26:16 | INFO | train task=Ses05F epoch=3 batch=1240/2378 step=1500 loss=0.6554 ce=0.6223 mse=0.0662 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1424436569213867, "reserved_gb": 2.1171875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "34", "gpu_mem_used_mb": "2482", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "69.07"}
2026-08-09 07:26:40 | INFO | train task=Ses05F epoch=3 batch=1340/2378 step=1525 loss=0.8593 ce=0.7701 mse=0.1783 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1451902389526367, "reserved_gb": 2.169921875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "62", "gpu_mem_used_mb": "2536", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "77.21"}
2026-08-09 07:27:00 | INFO | train task=Ses05F epoch=3 batch=1440/2378 step=1550 loss=2.4030 ce=2.2600 mse=0.2859 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1434712409973145, "reserved_gb": 1.935546875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "25", "gpu_mem_used_mb": "2296", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "57.99"}
2026-08-09 07:27:21 | INFO | train task=Ses05F epoch=3 batch=1540/2378 step=1575 loss=3.7224 ce=3.6739 mse=0.0971 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1432313919067383, "reserved_gb": 1.935546875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "2296", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "67.29"}
2026-08-09 07:27:42 | INFO | train task=Ses05F epoch=3 batch=1640/2378 step=1600 loss=2.3236 ce=1.6041 mse=1.4391 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1426153182983398, "reserved_gb": 1.939453125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "24", "gpu_mem_used_mb": "2300", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "42.78"}
2026-08-09 07:28:07 | INFO | train task=Ses05F epoch=3 batch=1740/2378 step=1625 loss=0.7755 ce=0.2094 mse=1.1324 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1428284645080566, "reserved_gb": 1.9453125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "13", "gpu_mem_used_mb": "2306", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "65.85"}
2026-08-09 07:28:28 | INFO | train task=Ses05F epoch=3 batch=1840/2378 step=1650 loss=0.5657 ce=0.4501 mse=0.2311 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1425833702087402, "reserved_gb": 1.939453125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "2300", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "88.11"}
2026-08-09 07:28:50 | INFO | train task=Ses05F epoch=3 batch=1940/2378 step=1675 loss=0.4483 ce=0.3789 mse=0.1389 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1425671577453613, "reserved_gb": 1.94140625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "28", "gpu_mem_used_mb": "2302", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "79.97"}
2026-08-09 07:29:11 | INFO | train task=Ses05F epoch=3 batch=2040/2378 step=1700 loss=1.0330 ce=0.9962 mse=0.0736 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1424593925476074, "reserved_gb": 1.9296875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "29", "gpu_mem_used_mb": "2290", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "69.68"}
2026-08-09 07:29:37 | INFO | train task=Ses05F epoch=3 batch=2140/2378 step=1725 loss=0.1479 ce=0.1192 mse=0.0575 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1435165405273438, "reserved_gb": 1.9296875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "51", "gpu_mem_used_mb": "2290", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "60.36"}
2026-08-09 07:29:59 | INFO | train task=Ses05F epoch=3 batch=2240/2378 step=1750 loss=1.1300 ce=0.6330 mse=0.9939 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1430907249450684, "reserved_gb": 1.947265625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "27", "gpu_mem_used_mb": "2308", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "90.89"}
2026-08-09 07:30:21 | INFO | train task=Ses05F epoch=3 batch=2340/2378 step=1775 loss=1.1839 ce=0.8787 mse=0.6105 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.148817539215088, "reserved_gb": 1.935546875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "73", "gpu_mem_used_mb": "2296", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "82.11"}

predict:   0%|          | 0/303 [00:00<?, ?it/s]

2026-08-09 07:30:52 | INFO | Epoch 03 task=Ses05F train_loss=1.2638 val_macro_f1=0.4903 val_mae=0.5547 epoch_seconds=537.0

epoch 4:   0%|          | 0/2378 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 07:31:10 | INFO | train task=Ses05F epoch=4 batch=60/2378 step=1800 loss=0.3864 ce=0.2102 mse=0.3523 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.144352912902832, "reserved_gb": 1.92578125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "76", "gpu_mem_used_mb": "2286", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "71.40"}
2026-08-09 07:31:35 | INFO | train task=Ses05F epoch=4 batch=160/2378 step=1825 loss=1.4437 ce=1.0046 mse=0.8781 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.142324447631836, "reserved_gb": 1.94140625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "25", "gpu_mem_used_mb": "2302", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "69.43"}
2026-08-09 07:31:56 | INFO | train task=Ses05F epoch=4 batch=260/2378 step=1850 loss=0.8140 ce=0.6558 mse=0.3165 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1434588432312012, "reserved_gb": 1.943359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "24", "gpu_mem_used_mb": "2304", "gpu_mem_total_mb": "12288", "gpu_temp_c": "53", "gpu_power_w": "69.87"}
2026-08-09 07:32:16 | INFO | train task=Ses05F epoch=4 batch=360/2378 step=1875 loss=0.5427 ce=0.1456 mse=0.7941 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1429343223571777, "reserved_gb": 1.923828125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "2284", "gpu_mem_total_mb": "12288", "gpu_temp_c": "56", "gpu_power_w": "75.17"}
2026-08-09 07:32:35 | INFO | train task=Ses05F epoch=4 batch=460/2378 step=1900 loss=0.3859 ce=0.3139 mse=0.1440 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1427898406982422, "reserved_gb": 2.205078125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "42", "gpu_mem_used_mb": "2572", "gpu_mem_total_mb": "12288", "gpu_temp_c": "57", "gpu_power_w": "65.01"}
2026-08-09 07:32:58 | INFO | train task=Ses05F epoch=4 batch=560/2378 step=1925 loss=0.5858 ce=0.0968 mse=0.9779 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1439261436462402, "reserved_gb": 2.38671875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "68", "gpu_mem_used_mb": "2758", "gpu_mem_total_mb": "12288", "gpu_temp_c": "60", "gpu_power_w": "73.64"}
2026-08-09 07:33:17 | INFO | train task=Ses05F epoch=4 batch=660/2378 step=1950 loss=0.6181 ce=0.5057 mse=0.2248 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1427569389343262, "reserved_gb": 1.94140625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "46", "gpu_mem_used_mb": "2302", "gpu_mem_total_mb": "12288", "gpu_temp_c": "55", "gpu_power_w": "70.26"}
2026-08-09 07:33:36 | INFO | train task=Ses05F epoch=4 batch=760/2378 step=1975 loss=0.8135 ce=0.5848 mse=0.4575 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.144411563873291, "reserved_gb": 1.927734375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "16", "gpu_mem_used_mb": "2288", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "66.40"}
2026-08-09 07:33:57 | INFO | train task=Ses05F epoch=4 batch=860/2378 step=2000 loss=0.7161 ce=0.6199 mse=0.1925 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.147801399230957, "reserved_gb": 1.93359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "61", "gpu_mem_used_mb": "2294", "gpu_mem_total_mb": "12288", "gpu_temp_c": "54", "gpu_power_w": "82.99"}
2026-08-09 07:34:20 | INFO | train task=Ses05F epoch=4 batch=960/2378 step=2025 loss=2.9242 ce=2.6921 mse=0.4641 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1438484191894531, "reserved_gb": 2.20703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "29", "gpu_mem_used_mb": "2574", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "70.73"}
2026-08-09 07:34:41 | INFO | train task=Ses05F epoch=4 batch=1060/2378 step=2050 loss=1.5791 ce=1.4097 mse=0.3388 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1434063911437988, "reserved_gb": 1.943359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "2304", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "71.94"}
2026-08-09 07:35:01 | INFO | train task=Ses05F epoch=4 batch=1160/2378 step=2075 loss=1.4223 ce=0.8862 mse=1.0721 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1426444053649902, "reserved_gb": 2.173828125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "16", "gpu_mem_used_mb": "2540", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "54.39"}
2026-08-09 07:35:22 | INFO | train task=Ses05F epoch=4 batch=1260/2378 step=2100 loss=2.5393 ce=2.5250 mse=0.0286 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1442570686340332, "reserved_gb": 2.21875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "19", "gpu_mem_used_mb": "2586", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "79.08"}
2026-08-09 07:35:44 | INFO | train task=Ses05F epoch=4 batch=1360/2378 step=2125 loss=0.9792 ce=0.6627 mse=0.6330 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1425466537475586, "reserved_gb": 2.25390625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "2622", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "63.40"}
2026-08-09 07:36:04 | INFO | train task=Ses05F epoch=4 batch=1460/2378 step=2150 loss=0.4065 ce=0.3913 mse=0.0304 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1432442665100098, "reserved_gb": 2.201171875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "33", "gpu_mem_used_mb": "2568", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "66.22"}
2026-08-09 07:36:26 | INFO | train task=Ses05F epoch=4 batch=1560/2378 step=2175 loss=2.0457 ce=1.9804 mse=0.1305 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1423940658569336, "reserved_gb": 1.9375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "26", "gpu_mem_used_mb": "2298", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "85.24"}
2026-08-09 07:36:48 | INFO | train task=Ses05F epoch=4 batch=1660/2378 step=2200 loss=2.1874 ce=1.4949 mse=1.3850 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1427021026611328, "reserved_gb": 2.275390625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "53", "gpu_mem_used_mb": "2644", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "50.15"}
2026-08-09 07:37:12 | INFO | train task=Ses05F epoch=4 batch=1760/2378 step=2225 loss=1.5266 ce=0.5822 mse=1.8887 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1427373886108398, "reserved_gb": 1.943359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "2304", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "69.87"}
2026-08-09 07:37:33 | INFO | train task=Ses05F epoch=4 batch=1860/2378 step=2250 loss=1.6888 ce=1.5405 mse=0.2965 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1424217224121094, "reserved_gb": 1.9453125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "15", "gpu_mem_used_mb": "2306", "gpu_mem_total_mb": "12288", "gpu_temp_c": "43", "gpu_power_w": "40.74"}
2026-08-09 07:37:54 | INFO | train task=Ses05F epoch=4 batch=1960/2378 step=2275 loss=2.5134 ce=2.1595 mse=0.7077 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1422739028930664, "reserved_gb": 2.2421875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "16", "gpu_mem_used_mb": "2610", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "69.89"}
2026-08-09 07:38:16 | INFO | train task=Ses05F epoch=4 batch=2060/2378 step=2300 loss=0.3875 ce=0.0651 mse=0.6449 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1427159309387207, "reserved_gb": 1.943359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "24", "gpu_mem_used_mb": "2304", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "86.68"}
2026-08-09 07:38:41 | INFO | train task=Ses05F epoch=4 batch=2160/2378 step=2325 loss=0.5730 ce=0.2000 mse=0.7461 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1424226760864258, "reserved_gb": 1.943359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "2304", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "72.83"}
2026-08-09 07:39:04 | INFO | train task=Ses05F epoch=4 batch=2260/2378 step=2350 loss=0.8529 ce=0.7886 mse=0.1286 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1451416015625, "reserved_gb": 1.931640625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "58", "gpu_mem_used_mb": "2292", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "77.61"}
2026-08-09 07:39:27 | INFO | train task=Ses05F epoch=4 batch=2360/2378 step=2375 loss=0.5067 ce=0.3235 mse=0.3664 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.143012523651123, "reserved_gb": 1.923828125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "51", "gpu_mem_used_mb": "2284", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "83.84"}

predict:   0%|          | 0/303 [00:00<?, ?it/s]

2026-08-09 07:39:52 | INFO | Epoch 04 task=Ses05F train_loss=1.0867 val_macro_f1=0.4714 val_mae=0.6035 epoch_seconds=535.7

epoch 5:   0%|          | 0/2378 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 07:40:13 | INFO | train task=Ses05F epoch=5 batch=80/2378 step=2400 loss=1.2451 ce=0.9635 mse=0.5632 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.142740249633789, "reserved_gb": 2.00390625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "32", "gpu_mem_used_mb": "2358", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "63.50"}
2026-08-09 07:40:35 | INFO | train task=Ses05F epoch=5 batch=180/2378 step=2425 loss=0.6224 ce=0.5295 mse=0.1859 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.147801399230957, "reserved_gb": 2.494140625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "45", "gpu_mem_used_mb": "2860", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "67.82"}
2026-08-09 07:40:55 | INFO | train task=Ses05F epoch=5 batch=280/2378 step=2450 loss=0.0636 ce=0.0565 mse=0.0142 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1431636810302734, "reserved_gb": 1.923828125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "2276", "gpu_mem_total_mb": "12288", "gpu_temp_c": "53", "gpu_power_w": "78.93"}
2026-08-09 07:41:15 | INFO | train task=Ses05F epoch=5 batch=380/2378 step=2475 loss=0.2952 ce=0.2528 mse=0.0847 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.142695426940918, "reserved_gb": 1.943359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "2296", "gpu_mem_total_mb": "12288", "gpu_temp_c": "53", "gpu_power_w": "72.60"}
2026-08-09 07:41:34 | INFO | train task=Ses05F epoch=5 batch=480/2378 step=2500 loss=0.6980 ce=0.2326 mse=0.9308 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1438097953796387, "reserved_gb": 2.0703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "2426", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "39.03"}
2026-08-09 07:41:57 | INFO | train task=Ses05F epoch=5 batch=580/2378 step=2525 loss=0.4032 ce=0.3048 mse=0.1968 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1425752639770508, "reserved_gb": 1.947265625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "19", "gpu_mem_used_mb": "2300", "gpu_mem_total_mb": "12288", "gpu_temp_c": "56", "gpu_power_w": "102.05"}
2026-08-09 07:42:16 | INFO | train task=Ses05F epoch=5 batch=680/2378 step=2550 loss=2.9476 ce=1.4837 mse=2.9278 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.142392635345459, "reserved_gb": 2.01953125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "41", "gpu_mem_used_mb": "2374", "gpu_mem_total_mb": "12288", "gpu_temp_c": "55", "gpu_power_w": "86.67"}
2026-08-09 07:42:37 | INFO | train task=Ses05F epoch=5 batch=780/2378 step=2575 loss=0.5437 ce=0.4278 mse=0.2318 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1430816650390625, "reserved_gb": 2.72265625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "48", "gpu_mem_used_mb": "3094", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "78.46"}
2026-08-09 07:42:57 | INFO | train task=Ses05F epoch=5 batch=880/2378 step=2600 loss=1.2713 ce=1.1844 mse=0.1738 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1433491706848145, "reserved_gb": 1.927734375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "59", "gpu_mem_used_mb": "2280", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "72.49"}
2026-08-09 07:43:19 | INFO | train task=Ses05F epoch=5 batch=980/2378 step=2625 loss=0.3139 ce=0.2878 mse=0.0522 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.14357328414917, "reserved_gb": 1.92578125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "27", "gpu_mem_used_mb": "2278", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "64.23"}
2026-08-09 07:43:40 | INFO | train task=Ses05F epoch=5 batch=1080/2378 step=2650 loss=0.1928 ce=0.1187 mse=0.1481 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1436471939086914, "reserved_gb": 2.025390625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "24", "gpu_mem_used_mb": "2380", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "73.38"}
2026-08-09 07:44:01 | INFO | train task=Ses05F epoch=5 batch=1180/2378 step=2675 loss=0.3568 ce=0.1199 mse=0.4738 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1437187194824219, "reserved_gb": 2.00390625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "24", "gpu_mem_used_mb": "2358", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "70.91"}
2026-08-09 07:44:21 | INFO | train task=Ses05F epoch=5 batch=1280/2378 step=2700 loss=1.3617 ce=0.6351 mse=1.4532 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.142582893371582, "reserved_gb": 2.16015625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "24", "gpu_mem_used_mb": "2518", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "64.68"}
2026-08-09 07:44:45 | INFO | train task=Ses05F epoch=5 batch=1380/2378 step=2725 loss=0.8993 ce=0.6552 mse=0.4882 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1440281867980957, "reserved_gb": 2.029296875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "19", "gpu_mem_used_mb": "2384", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "69.59"}
2026-08-09 07:45:08 | INFO | train task=Ses05F epoch=5 batch=1480/2378 step=2750 loss=2.2036 ce=2.1405 mse=0.1261 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1426372528076172, "reserved_gb": 1.943359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "38", "gpu_mem_used_mb": "2296", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "67.48"}
2026-08-09 07:45:29 | INFO | train task=Ses05F epoch=5 batch=1580/2378 step=2775 loss=2.5865 ce=2.5670 mse=0.0390 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1450581550598145, "reserved_gb": 1.9296875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "54", "gpu_mem_used_mb": "2282", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "73.47"}
2026-08-09 07:45:49 | INFO | train task=Ses05F epoch=5 batch=1680/2378 step=2800 loss=0.7047 ce=0.6158 mse=0.1779 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.14247465133667, "reserved_gb": 1.943359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "2296", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "58.98"}
2026-08-09 07:46:13 | INFO | train task=Ses05F epoch=5 batch=1780/2378 step=2825 loss=2.1071 ce=2.0706 mse=0.0730 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1430845260620117, "reserved_gb": 1.923828125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "51", "gpu_mem_used_mb": "2276", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "69.29"}
2026-08-09 07:46:34 | INFO | train task=Ses05F epoch=5 batch=1880/2378 step=2850 loss=1.1153 ce=0.8614 mse=0.5078 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1429476737976074, "reserved_gb": 2.208984375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "34", "gpu_mem_used_mb": "2568", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "71.09"}
2026-08-09 07:46:54 | INFO | train task=Ses05F epoch=5 batch=1980/2378 step=2875 loss=1.6857 ce=1.5567 mse=0.2579 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1424078941345215, "reserved_gb": 1.931640625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "24", "gpu_mem_used_mb": "2284", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "57.59"}
2026-08-09 07:47:18 | INFO | train task=Ses05F epoch=5 batch=2080/2378 step=2900 loss=0.2232 ce=0.0482 mse=0.3500 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.147801399230957, "reserved_gb": 2.2890625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "42", "gpu_mem_used_mb": "2650", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "82.74"}
2026-08-09 07:47:44 | INFO | train task=Ses05F epoch=5 batch=2180/2378 step=2925 loss=0.3310 ce=0.2237 mse=0.2144 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.145273208618164, "reserved_gb": 2.173828125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "2532", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "72.55"}
2026-08-09 07:48:05 | INFO | train task=Ses05F epoch=5 batch=2280/2378 step=2950 loss=2.1147 ce=1.9159 mse=0.3976 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1428146362304688, "reserved_gb": 1.947265625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "36", "gpu_mem_used_mb": "2300", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "69.79"}
2026-08-09 07:48:26 | INFO | train task=Ses05F epoch=5 batch=2378/2378 step=2975 loss=0.4397 ce=0.2100 mse=0.4594 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1422343254089355, "reserved_gb": 1.923828125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "54", "gpu_mem_used_mb": "2276", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "76.69"}

predict:   0%|          | 0/303 [00:00<?, ?it/s]

2026-08-09 07:48:46 | INFO | Epoch 05 task=Ses05F train_loss=0.9605 val_macro_f1=0.5085 val_mae=0.5428 epoch_seconds=530.2

epoch 6:   0%|          | 0/2378 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 07:49:11 | INFO | train task=Ses05F epoch=6 batch=100/2378 step=3000 loss=0.2397 ce=0.2096 mse=0.0603 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1433987617492676, "reserved_gb": 2.205078125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "23", "gpu_mem_used_mb": "2555", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "76.96"}
2026-08-09 07:49:34 | INFO | train task=Ses05F epoch=6 batch=200/2378 step=3025 loss=0.1965 ce=0.1796 mse=0.0338 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.144205093383789, "reserved_gb": 2.15234375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "28", "gpu_mem_used_mb": "2509", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "73.34"}
2026-08-09 07:49:54 | INFO | train task=Ses05F epoch=6 batch=300/2378 step=3050 loss=0.2574 ce=0.1895 mse=0.1358 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.145273208618164, "reserved_gb": 2.24609375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "23", "gpu_mem_used_mb": "2605", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "67.32"}
2026-08-09 07:50:13 | INFO | train task=Ses05F epoch=6 batch=400/2378 step=3075 loss=4.2928 ce=4.2168 mse=0.1519 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1422386169433594, "reserved_gb": 2.484375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "14", "gpu_mem_used_mb": "2849", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "68.08"}
2026-08-09 07:50:32 | INFO | train task=Ses05F epoch=6 batch=500/2378 step=3100 loss=0.6901 ce=0.6096 mse=0.1610 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1428947448730469, "reserved_gb": 1.923828125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "59", "gpu_mem_used_mb": "2275", "gpu_mem_total_mb": "12288", "gpu_temp_c": "59", "gpu_power_w": "78.13"}
2026-08-09 07:50:56 | INFO | train task=Ses05F epoch=6 batch=600/2378 step=3125 loss=2.7555 ce=2.4845 mse=0.5420 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1424436569213867, "reserved_gb": 2.41796875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "31", "gpu_mem_used_mb": "2781", "gpu_mem_total_mb": "12288", "gpu_temp_c": "57", "gpu_power_w": "72.03"}
2026-08-09 07:51:16 | INFO | train task=Ses05F epoch=6 batch=700/2378 step=3150 loss=0.2373 ce=0.1994 mse=0.0759 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.143415927886963, "reserved_gb": 2.228515625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "25", "gpu_mem_used_mb": "2587", "gpu_mem_total_mb": "12288", "gpu_temp_c": "56", "gpu_power_w": "75.00"}
2026-08-09 07:51:36 | INFO | train task=Ses05F epoch=6 batch=800/2378 step=3175 loss=0.3093 ce=0.2799 mse=0.0587 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1434178352355957, "reserved_gb": 2.15234375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "16", "gpu_mem_used_mb": "2509", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "65.66"}
2026-08-09 07:51:56 | INFO | train task=Ses05F epoch=6 batch=900/2378 step=3200 loss=0.6541 ce=0.2275 mse=0.8533 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1428203582763672, "reserved_gb": 2.16796875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "18", "gpu_mem_used_mb": "2525", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "77.06"}
2026-08-09 07:52:19 | INFO | train task=Ses05F epoch=6 batch=1000/2378 step=3225 loss=2.1067 ce=2.0866 mse=0.0402 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.14225435256958, "reserved_gb": 1.927734375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "37", "gpu_mem_used_mb": "2279", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "68.90"}
2026-08-09 07:52:40 | INFO | train task=Ses05F epoch=6 batch=1100/2378 step=3250 loss=0.3758 ce=0.0714 mse=0.6089 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.143594741821289, "reserved_gb": 2.146484375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "19", "gpu_mem_used_mb": "2503", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "64.19"}
2026-08-09 07:53:01 | INFO | train task=Ses05F epoch=6 batch=1200/2378 step=3275 loss=1.7836 ce=1.3850 mse=0.7971 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.142796516418457, "reserved_gb": 1.9453125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "2297", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "71.04"}
2026-08-09 07:53:20 | INFO | train task=Ses05F epoch=6 batch=1300/2378 step=3300 loss=1.2903 ce=1.2520 mse=0.0766 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1426615715026855, "reserved_gb": 1.943359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "2295", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "71.27"}
2026-08-09 07:53:45 | INFO | train task=Ses05F epoch=6 batch=1400/2378 step=3325 loss=0.1582 ce=0.0931 mse=0.1302 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1422357559204102, "reserved_gb": 1.923828125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "62", "gpu_mem_used_mb": "2275", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "55.13"}
2026-08-09 07:54:05 | INFO | train task=Ses05F epoch=6 batch=1500/2378 step=3350 loss=0.8486 ce=0.6826 mse=0.3320 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1431245803833008, "reserved_gb": 1.923828125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "35", "gpu_mem_used_mb": "2276", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "65.89"}
2026-08-09 07:54:24 | INFO | train task=Ses05F epoch=6 batch=1600/2378 step=3375 loss=1.6586 ce=1.5776 mse=0.1619 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1429071426391602, "reserved_gb": 1.9296875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "35", "gpu_mem_used_mb": "2282", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "70.32"}
2026-08-09 07:54:44 | INFO | train task=Ses05F epoch=6 batch=1700/2378 step=3400 loss=0.4692 ce=0.2267 mse=0.4850 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1426639556884766, "reserved_gb": 1.943359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "39", "gpu_mem_used_mb": "2296", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "68.09"}
2026-08-09 07:55:10 | INFO | train task=Ses05F epoch=6 batch=1800/2378 step=3425 loss=0.2500 ce=0.2388 mse=0.0225 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1426787376403809, "reserved_gb": 2.375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "2738", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "63.10"}
2026-08-09 07:55:32 | INFO | train task=Ses05F epoch=6 batch=1900/2378 step=3450 loss=0.8422 ce=0.5212 mse=0.6421 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1435809135437012, "reserved_gb": 1.92578125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "42", "gpu_mem_used_mb": "2278", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "81.37"}
2026-08-09 07:55:53 | INFO | train task=Ses05F epoch=6 batch=2000/2378 step=3475 loss=1.2847 ce=1.1293 mse=0.3109 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1430864334106445, "reserved_gb": 1.978515625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "30", "gpu_mem_used_mb": "2332", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "94.58"}
2026-08-09 07:56:16 | INFO | train task=Ses05F epoch=6 batch=2100/2378 step=3500 loss=0.8377 ce=0.4401 mse=0.7953 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1425323486328125, "reserved_gb": 1.93359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "2286", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "66.75"}
2026-08-09 07:56:41 | INFO | train task=Ses05F epoch=6 batch=2200/2378 step=3525 loss=0.2705 ce=0.2639 mse=0.0131 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1427040100097656, "reserved_gb": 1.9453125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "24", "gpu_mem_used_mb": "2298", "gpu_mem_total_mb": "12288", "gpu_temp_c": "44", "gpu_power_w": "53.67"}
2026-08-09 07:57:04 | INFO | train task=Ses05F epoch=6 batch=2300/2378 step=3550 loss=0.6500 ce=0.5730 mse=0.1540 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1442346572875977, "reserved_gb": 1.927734375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "35", "gpu_mem_used_mb": "2280", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "69.39"}

predict:   0%|          | 0/303 [00:00<?, ?it/s]

2026-08-09 07:57:43 | INFO | Epoch 06 task=Ses05F train_loss=0.8629 val_macro_f1=0.5054 val_mae=0.5365 epoch_seconds=532.7

epoch 7:   0%|          | 0/2378 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 07:57:52 | INFO | train task=Ses05F epoch=7 batch=20/2378 step=3575 loss=0.8158 ce=0.6390 mse=0.3536 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1437406539916992, "reserved_gb": 12.068359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "90", "gpu_mem_used_mb": "11998", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "59.93"}
2026-08-09 07:58:13 | INFO | train task=Ses05F epoch=7 batch=120/2378 step=3600 loss=0.4389 ce=0.4066 mse=0.0645 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1427698135375977, "reserved_gb": 1.943359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "23", "gpu_mem_used_mb": "2294", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "87.11"}
2026-08-09 07:58:37 | INFO | train task=Ses05F epoch=7 batch=220/2378 step=3625 loss=0.1828 ce=0.1676 mse=0.0304 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1431245803833008, "reserved_gb": 2.453125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "42", "gpu_mem_used_mb": "2818", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "66.60"}
2026-08-09 07:58:59 | INFO | train task=Ses05F epoch=7 batch=320/2378 step=3650 loss=0.2603 ce=0.1889 mse=0.1428 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1423053741455078, "reserved_gb": 2.1328125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "26", "gpu_mem_used_mb": "2490", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "64.91"}
2026-08-09 07:59:19 | INFO | train task=Ses05F epoch=7 batch=420/2378 step=3675 loss=0.9935 ce=0.9416 mse=0.1039 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1433520317077637, "reserved_gb": 1.923828125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "56", "gpu_mem_used_mb": "2276", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "62.75"}
2026-08-09 07:59:38 | INFO | train task=Ses05F epoch=7 batch=520/2378 step=3700 loss=1.5109 ce=1.4731 mse=0.0755 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.143599033355713, "reserved_gb": 2.140625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "16", "gpu_mem_used_mb": "2498", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "71.78"}
2026-08-09 08:00:01 | INFO | train task=Ses05F epoch=7 batch=620/2378 step=3725 loss=0.6516 ce=0.6212 mse=0.0609 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1425304412841797, "reserved_gb": 2.138671875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "44", "gpu_mem_used_mb": "2496", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "64.82"}
2026-08-09 08:00:21 | INFO | train task=Ses05F epoch=7 batch=720/2378 step=3750 loss=0.4877 ce=0.4326 mse=0.1103 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.142850399017334, "reserved_gb": 1.9453125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "24", "gpu_mem_used_mb": "2298", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "68.07"}
2026-08-09 08:00:40 | INFO | train task=Ses05F epoch=7 batch=820/2378 step=3775 loss=0.4610 ce=0.3634 mse=0.1951 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1428470611572266, "reserved_gb": 1.9453125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "26", "gpu_mem_used_mb": "2298", "gpu_mem_total_mb": "12288", "gpu_temp_c": "44", "gpu_power_w": "59.69"}
2026-08-09 08:01:00 | INFO | train task=Ses05F epoch=7 batch=920/2378 step=3800 loss=0.2534 ce=0.0315 mse=0.4439 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1430907249450684, "reserved_gb": 2.1640625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "39", "gpu_mem_used_mb": "2522", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "69.57"}
2026-08-09 08:01:24 | INFO | train task=Ses05F epoch=7 batch=1020/2378 step=3825 loss=0.3032 ce=0.0841 mse=0.4383 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.142470359802246, "reserved_gb": 2.369140625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "25", "gpu_mem_used_mb": "2752", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "70.90"}
2026-08-09 08:01:45 | INFO | train task=Ses05F epoch=7 batch=1120/2378 step=3850 loss=4.5720 ce=4.3905 mse=0.3631 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.142441749572754, "reserved_gb": 1.9296875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "84", "gpu_mem_used_mb": "2302", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "77.44"}
2026-08-09 08:02:06 | INFO | train task=Ses05F epoch=7 batch=1220/2378 step=3875 loss=0.1587 ce=0.0830 mse=0.1514 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1432442665100098, "reserved_gb": 1.9375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "26", "gpu_mem_used_mb": "2310", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "68.09"}
2026-08-09 08:02:26 | INFO | train task=Ses05F epoch=7 batch=1320/2378 step=3900 loss=2.0850 ce=1.8693 mse=0.4314 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1429166793823242, "reserved_gb": 1.9453125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "2318", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "70.89"}
2026-08-09 08:02:50 | INFO | train task=Ses05F epoch=7 batch=1420/2378 step=3925 loss=1.7889 ce=1.6739 mse=0.2299 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.143150806427002, "reserved_gb": 1.9296875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "32", "gpu_mem_used_mb": "2302", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "88.02"}
2026-08-09 08:03:10 | INFO | train task=Ses05F epoch=7 batch=1520/2378 step=3950 loss=0.9121 ce=0.8918 mse=0.0406 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1425247192382812, "reserved_gb": 2.205078125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "2584", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "62.32"}
2026-08-09 08:03:31 | INFO | train task=Ses05F epoch=7 batch=1620/2378 step=3975 loss=0.5753 ce=0.2512 mse=0.6482 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.142446517944336, "reserved_gb": 1.931640625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "2304", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "63.82"}
2026-08-09 08:03:50 | INFO | train task=Ses05F epoch=7 batch=1720/2378 step=4000 loss=1.3839 ce=1.3133 mse=0.1414 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1428794860839844, "reserved_gb": 1.923828125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "2296", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "66.76"}
2026-08-09 08:04:14 | INFO | train task=Ses05F epoch=7 batch=1820/2378 step=4025 loss=1.7697 ce=1.6274 mse=0.2846 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.143449306488037, "reserved_gb": 2.171875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "19", "gpu_mem_used_mb": "2550", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "68.21"}
2026-08-09 08:04:34 | INFO | train task=Ses05F epoch=7 batch=1920/2378 step=4050 loss=1.2858 ce=1.1807 mse=0.2102 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1423182487487793, "reserved_gb": 2.150390625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "41", "gpu_mem_used_mb": "2528", "gpu_mem_total_mb": "12288", "gpu_temp_c": "43", "gpu_power_w": "40.81"}
2026-08-09 08:04:55 | INFO | train task=Ses05F epoch=7 batch=2020/2378 step=4075 loss=0.4971 ce=0.2057 mse=0.5826 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1427607536315918, "reserved_gb": 1.9453125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "33", "gpu_mem_used_mb": "2318", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "60.85"}
2026-08-09 08:05:17 | INFO | train task=Ses05F epoch=7 batch=2120/2378 step=4100 loss=0.0630 ce=0.0298 mse=0.0664 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.145066738128662, "reserved_gb": 1.923828125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "38", "gpu_mem_used_mb": "2296", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "80.89"}
2026-08-09 08:05:41 | INFO | train task=Ses05F epoch=7 batch=2220/2378 step=4125 loss=0.8674 ce=0.2177 mse=1.2994 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1426153182983398, "reserved_gb": 1.9453125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "2318", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "72.89"}
2026-08-09 08:06:03 | INFO | train task=Ses05F epoch=7 batch=2320/2378 step=4150 loss=0.0619 ce=0.0480 mse=0.0277 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.143331527709961, "reserved_gb": 2.2265625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "18", "gpu_mem_used_mb": "2606", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "81.58"}

predict:   0%|          | 0/303 [00:00<?, ?it/s]

2026-08-09 08:06:37 | INFO | Epoch 07 task=Ses05F train_loss=0.7585 val_macro_f1=0.5077 val_mae=0.5427 epoch_seconds=531.4

predict:   0%|          | 0/261 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)

predict:   0%|          | 0/383 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
2026-08-09 08:08:03 | INFO | Task de641ed1d0ddc4dc_main_fold -> complete
2026-08-09 08:08:05 | INFO | Manuscript outputs refreshed: 21 tables, 4 figures
2026-08-09 08:08:05 | INFO | Task 5cc793bc30552668_main_fold -> running
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\transformers\configuration_utils.py:335: UserWarning: Passing `gradient_checkpointing` to a config initialization is deprecated and will be removed in v5 Transformers. Using `model.gradient_checkpointing_enable()` instead, or if you are using the `Trainer` API, pass `gradient_checkpointing=True` in your `TrainingArguments`.
  warnings.warn(
2026-08-09 08:08:07 | INFO | Task C:\Users\HaseebWajid\Downloads\runs\dersx_paper_aligned\campaign_01\main\seed_13\Ses05M parameters={'total': 163009451, 'trainable': 69034283, 'frozen': 93975168} scope={'corpus': 'IEMOCAP', 'protocol': 'strict_LOSO', 'heldout_speaker': 'Ses05M', 'seed': 13, 'stage': 'main', 'profile': 'rtx3060_24h'}

epoch 1:   0%|          | 0/2378 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 08:08:30 | INFO | train task=Ses05M epoch=1 batch=100/2378 step=25 loss=2.6365 ce=2.4379 mse=0.3972 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2687535285949707, "reserved_gb": 2.8515625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "23", "gpu_mem_used_mb": "3246", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "60.17"}
2026-08-09 08:08:51 | INFO | train task=Ses05M epoch=1 batch=200/2378 step=50 loss=2.5487 ce=2.2450 mse=0.6075 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2684507369995117, "reserved_gb": 2.837890625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "31", "gpu_mem_used_mb": "3232", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "60.70"}
2026-08-09 08:09:12 | INFO | train task=Ses05M epoch=1 batch=300/2378 step=75 loss=2.7798 ce=1.9619 mse=1.6358 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2688589096069336, "reserved_gb": 2.84765625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "44", "gpu_mem_used_mb": "3242", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "64.05"}
2026-08-09 08:09:34 | INFO | train task=Ses05M epoch=1 batch=400/2378 step=100 loss=2.0582 ce=1.8691 mse=0.3780 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2694149017333984, "reserved_gb": 2.84375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "32", "gpu_mem_used_mb": "3238", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "62.00"}
2026-08-09 08:09:59 | INFO | train task=Ses05M epoch=1 batch=500/2378 step=125 loss=2.1640 ce=1.6938 mse=0.9404 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2688212394714355, "reserved_gb": 2.986328125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "3384", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "71.07"}
2026-08-09 08:10:23 | INFO | train task=Ses05M epoch=1 batch=600/2378 step=150 loss=1.7745 ce=1.4468 mse=0.6555 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2686233520507812, "reserved_gb": 2.88671875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "48", "gpu_mem_used_mb": "3282", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "72.23"}
2026-08-09 08:10:44 | INFO | train task=Ses05M epoch=1 batch=700/2378 step=175 loss=2.0435 ce=1.9751 mse=0.1369 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2688040733337402, "reserved_gb": 2.859375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "24", "gpu_mem_used_mb": "3254", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "78.94"}
2026-08-09 08:11:05 | INFO | train task=Ses05M epoch=1 batch=800/2378 step=200 loss=1.8935 ce=1.8552 mse=0.0765 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2685842514038086, "reserved_gb": 2.853515625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "40", "gpu_mem_used_mb": "3248", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "64.58"}
2026-08-09 08:11:31 | INFO | train task=Ses05M epoch=1 batch=900/2378 step=225 loss=2.1283 ce=1.2344 mse=1.7878 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2691802978515625, "reserved_gb": 2.86328125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "52", "gpu_mem_used_mb": "3258", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "74.76"}
2026-08-09 08:11:54 | INFO | train task=Ses05M epoch=1 batch=1000/2378 step=250 loss=1.9482 ce=1.4238 mse=1.0488 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.14546537399292, "reserved_gb": 1.86328125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "18", "gpu_mem_used_mb": "2234", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "66.76"}
2026-08-09 08:12:17 | INFO | train task=Ses05M epoch=1 batch=1100/2378 step=275 loss=1.4155 ce=1.1729 mse=0.4852 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1476144790649414, "reserved_gb": 2.033203125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "30", "gpu_mem_used_mb": "2408", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "72.88"}
2026-08-09 08:12:41 | INFO | train task=Ses05M epoch=1 batch=1200/2378 step=300 loss=1.8863 ce=1.8832 mse=0.0062 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1458721160888672, "reserved_gb": 1.896484375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "29", "gpu_mem_used_mb": "2268", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "80.12"}
2026-08-09 08:13:06 | INFO | train task=Ses05M epoch=1 batch=1300/2378 step=325 loss=1.8316 ce=1.7067 mse=0.2498 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1503963470458984, "reserved_gb": 1.853515625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "54", "gpu_mem_used_mb": "2224", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "50.76"}
2026-08-09 08:13:29 | INFO | train task=Ses05M epoch=1 batch=1400/2378 step=350 loss=1.9263 ce=1.8666 mse=0.1194 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.145998477935791, "reserved_gb": 1.95703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "2330", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "67.06"}
2026-08-09 08:13:52 | INFO | train task=Ses05M epoch=1 batch=1500/2378 step=375 loss=2.5221 ce=2.1457 mse=0.7530 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1456847190856934, "reserved_gb": 1.91015625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "2282", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "53.15"}
2026-08-09 08:14:15 | INFO | train task=Ses05M epoch=1 batch=1600/2378 step=400 loss=1.2480 ce=1.1369 mse=0.2222 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.145193099975586, "reserved_gb": 1.8515625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "18", "gpu_mem_used_mb": "2222", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "73.28"}
2026-08-09 08:14:43 | INFO | train task=Ses05M epoch=1 batch=1700/2378 step=425 loss=1.4529 ce=1.1608 mse=0.5843 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1456003189086914, "reserved_gb": 1.8671875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "36", "gpu_mem_used_mb": "2238", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "81.75"}
2026-08-09 08:15:07 | INFO | train task=Ses05M epoch=1 batch=1800/2378 step=450 loss=0.7749 ce=0.2645 mse=1.0208 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1528534889221191, "reserved_gb": 1.849609375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "72", "gpu_mem_used_mb": "2220", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "86.16"}
2026-08-09 08:15:30 | INFO | train task=Ses05M epoch=1 batch=1900/2378 step=475 loss=1.4502 ce=1.4329 mse=0.0346 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1455512046813965, "reserved_gb": 1.90625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "29", "gpu_mem_used_mb": "2278", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "67.54"}
2026-08-09 08:15:55 | INFO | train task=Ses05M epoch=1 batch=2000/2378 step=500 loss=2.5787 ce=2.4567 mse=0.2440 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1450700759887695, "reserved_gb": 1.84765625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "30", "gpu_mem_used_mb": "2218", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "61.68"}
2026-08-09 08:16:23 | INFO | train task=Ses05M epoch=1 batch=2100/2378 step=525 loss=1.7514 ce=1.4885 mse=0.5258 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1454319953918457, "reserved_gb": 1.8671875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "2238", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "70.52"}
2026-08-09 08:16:47 | INFO | train task=Ses05M epoch=1 batch=2200/2378 step=550 loss=2.0284 ce=2.0259 mse=0.0051 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1457791328430176, "reserved_gb": 1.84765625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "34", "gpu_mem_used_mb": "2218", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "71.96"}
2026-08-09 08:17:11 | INFO | train task=Ses05M epoch=1 batch=2300/2378 step=575 loss=2.8097 ce=2.5193 mse=0.5808 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1506328582763672, "reserved_gb": 1.84765625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "2218", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "74.13"}

predict:   0%|          | 0/303 [00:00<?, ?it/s]

2026-08-09 08:18:09 | INFO | Epoch 01 task=Ses05M train_loss=2.0505 val_macro_f1=0.4835 val_mae=0.5539 epoch_seconds=600.8

epoch 2:   0%|          | 0/2378 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 08:18:17 | INFO | train task=Ses05M epoch=2 batch=20/2378 step=600 loss=1.1751 ce=1.0411 mse=0.2680 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.146733283996582, "reserved_gb": 2.376953125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "30", "gpu_mem_used_mb": "2760", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "67.43"}
2026-08-09 08:18:41 | INFO | train task=Ses05M epoch=2 batch=120/2378 step=625 loss=1.4001 ce=1.3989 mse=0.0024 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1451225280761719, "reserved_gb": 1.853515625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "15", "gpu_mem_used_mb": "2224", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "58.22"}
2026-08-09 08:19:01 | INFO | train task=Ses05M epoch=2 batch=220/2378 step=650 loss=0.6436 ce=0.5980 mse=0.0912 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1466331481933594, "reserved_gb": 2.28125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "35", "gpu_mem_used_mb": "2662", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "70.65"}
2026-08-09 08:19:21 | INFO | train task=Ses05M epoch=2 batch=320/2378 step=675 loss=1.8668 ce=1.7142 mse=0.3052 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1457433700561523, "reserved_gb": 2.005859375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "24", "gpu_mem_used_mb": "2380", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "61.09"}
2026-08-09 08:19:41 | INFO | train task=Ses05M epoch=2 batch=420/2378 step=700 loss=1.0001 ce=0.8214 mse=0.3574 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1454129219055176, "reserved_gb": 2.068359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "26", "gpu_mem_used_mb": "2444", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "66.97"}
2026-08-09 08:20:04 | INFO | train task=Ses05M epoch=2 batch=520/2378 step=725 loss=1.4027 ce=1.1134 mse=0.5787 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1454505920410156, "reserved_gb": 1.861328125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "2232", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "66.21"}
2026-08-09 08:20:25 | INFO | train task=Ses05M epoch=2 batch=620/2378 step=750 loss=2.8050 ce=2.7925 mse=0.0251 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1453852653503418, "reserved_gb": 2.326171875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "23", "gpu_mem_used_mb": "2708", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "68.81"}
2026-08-09 08:20:45 | INFO | train task=Ses05M epoch=2 batch=720/2378 step=775 loss=1.4693 ce=1.2879 mse=0.3629 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1480154991149902, "reserved_gb": 1.84765625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "76", "gpu_mem_used_mb": "2218", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "60.42"}
2026-08-09 08:21:07 | INFO | train task=Ses05M epoch=2 batch=820/2378 step=800 loss=0.3475 ce=0.3309 mse=0.0333 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1453862190246582, "reserved_gb": 1.857421875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "40", "gpu_mem_used_mb": "2228", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "74.61"}
2026-08-09 08:21:29 | INFO | train task=Ses05M epoch=2 batch=920/2378 step=825 loss=2.2667 ce=2.2349 mse=0.0635 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1451330184936523, "reserved_gb": 2.173828125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "15", "gpu_mem_used_mb": "2552", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "70.12"}
2026-08-09 08:21:50 | INFO | train task=Ses05M epoch=2 batch=1020/2378 step=850 loss=1.1783 ce=1.1659 mse=0.0247 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.147202968597412, "reserved_gb": 2.3671875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "53", "gpu_mem_used_mb": "2750", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "78.00"}
2026-08-09 08:22:11 | INFO | train task=Ses05M epoch=2 batch=1120/2378 step=875 loss=0.7643 ce=0.5283 mse=0.4721 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.145556926727295, "reserved_gb": 2.158203125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "24", "gpu_mem_used_mb": "2536", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "66.07"}
2026-08-09 08:22:31 | INFO | train task=Ses05M epoch=2 batch=1220/2378 step=900 loss=2.0038 ce=1.9628 mse=0.0820 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1471567153930664, "reserved_gb": 1.84765625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "60", "gpu_mem_used_mb": "2218", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "48.56"}
2026-08-09 08:22:55 | INFO | train task=Ses05M epoch=2 batch=1320/2378 step=925 loss=0.1904 ce=0.1591 mse=0.0626 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1461758613586426, "reserved_gb": 1.908203125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "26", "gpu_mem_used_mb": "2280", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "61.09"}
2026-08-09 08:23:15 | INFO | train task=Ses05M epoch=2 batch=1420/2378 step=950 loss=1.2664 ce=1.2463 mse=0.0400 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.145127773284912, "reserved_gb": 1.849609375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "77", "gpu_mem_used_mb": "2220", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "70.96"}
2026-08-09 08:23:37 | INFO | train task=Ses05M epoch=2 batch=1520/2378 step=975 loss=1.1377 ce=0.9324 mse=0.4105 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1452159881591797, "reserved_gb": 2.068359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "33", "gpu_mem_used_mb": "2444", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "71.86"}
2026-08-09 08:23:58 | INFO | train task=Ses05M epoch=2 batch=1620/2378 step=1000 loss=2.1470 ce=2.1017 mse=0.0906 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.145277976989746, "reserved_gb": 1.8515625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "24", "gpu_mem_used_mb": "2222", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "88.46"}
2026-08-09 08:24:25 | INFO | train task=Ses05M epoch=2 batch=1720/2378 step=1025 loss=0.3562 ce=0.3450 mse=0.0224 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1450986862182617, "reserved_gb": 1.8515625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "32", "gpu_mem_used_mb": "2222", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "92.11"}
2026-08-09 08:24:47 | INFO | train task=Ses05M epoch=2 batch=1820/2378 step=1050 loss=2.8118 ce=2.5278 mse=0.5680 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1454358100891113, "reserved_gb": 1.859375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "2230", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "89.65"}
2026-08-09 08:25:08 | INFO | train task=Ses05M epoch=2 batch=1920/2378 step=1075 loss=2.1568 ce=1.8494 mse=0.6149 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1453351974487305, "reserved_gb": 2.20703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "2586", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "70.86"}
2026-08-09 08:25:31 | INFO | train task=Ses05M epoch=2 batch=2020/2378 step=1100 loss=1.8797 ce=1.4926 mse=0.7742 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1457099914550781, "reserved_gb": 1.84765625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "25", "gpu_mem_used_mb": "2218", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "91.31"}
2026-08-09 08:25:54 | INFO | train task=Ses05M epoch=2 batch=2120/2378 step=1125 loss=1.9042 ce=1.6078 mse=0.5927 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1452789306640625, "reserved_gb": 1.91796875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "15", "gpu_mem_used_mb": "2290", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "60.53"}
2026-08-09 08:26:16 | INFO | train task=Ses05M epoch=2 batch=2220/2378 step=1150 loss=2.0308 ce=1.2247 mse=1.6122 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1456794738769531, "reserved_gb": 1.84765625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "23", "gpu_mem_used_mb": "2218", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "68.04"}
2026-08-09 08:26:41 | INFO | train task=Ses05M epoch=2 batch=2320/2378 step=1175 loss=1.1998 ce=0.8904 mse=0.6189 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1457791328430176, "reserved_gb": 1.923828125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "58", "gpu_mem_used_mb": "2296", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "79.96"}

predict:   0%|          | 0/303 [00:00<?, ?it/s]

2026-08-09 08:27:16 | INFO | Epoch 02 task=Ses05M train_loss=1.4827 val_macro_f1=0.4713 val_mae=0.5737 epoch_seconds=543.4

epoch 3:   0%|          | 0/2378 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 08:27:28 | INFO | train task=Ses05M epoch=3 batch=40/2378 step=1200 loss=1.2174 ce=1.0510 mse=0.3327 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.147111415863037, "reserved_gb": 2.298828125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "32", "gpu_mem_used_mb": "2622", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "50.44"}
2026-08-09 08:27:52 | INFO | train task=Ses05M epoch=3 batch=140/2378 step=1225 loss=1.1924 ce=0.6821 mse=1.0205 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.145545482635498, "reserved_gb": 2.49609375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "28", "gpu_mem_used_mb": "2824", "gpu_mem_total_mb": "12288", "gpu_temp_c": "53", "gpu_power_w": "71.20"}
2026-08-09 08:28:13 | INFO | train task=Ses05M epoch=3 batch=240/2378 step=1250 loss=0.5755 ce=0.2637 mse=0.6236 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1455044746398926, "reserved_gb": 1.86328125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "14", "gpu_mem_used_mb": "2211", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "64.29"}
2026-08-09 08:28:33 | INFO | train task=Ses05M epoch=3 batch=340/2378 step=1275 loss=1.3103 ce=1.3000 mse=0.0207 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.147834300994873, "reserved_gb": 2.228515625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "62", "gpu_mem_used_mb": "2585", "gpu_mem_total_mb": "12288", "gpu_temp_c": "56", "gpu_power_w": "80.52"}
2026-08-09 08:28:53 | INFO | train task=Ses05M epoch=3 batch=440/2378 step=1300 loss=1.1749 ce=0.6354 mse=1.0791 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1466007232666016, "reserved_gb": 1.939453125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "2289", "gpu_mem_total_mb": "12288", "gpu_temp_c": "55", "gpu_power_w": "70.13"}
2026-08-09 08:29:16 | INFO | train task=Ses05M epoch=3 batch=540/2378 step=1325 loss=0.4937 ce=0.3931 mse=0.2012 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1453285217285156, "reserved_gb": 1.853515625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "2203", "gpu_mem_total_mb": "12288", "gpu_temp_c": "57", "gpu_power_w": "69.43"}
2026-08-09 08:29:37 | INFO | train task=Ses05M epoch=3 batch=640/2378 step=1350 loss=0.3629 ce=0.1840 mse=0.3579 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1454873085021973, "reserved_gb": 2.439453125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "48", "gpu_mem_used_mb": "2803", "gpu_mem_total_mb": "12288", "gpu_temp_c": "54", "gpu_power_w": "80.01"}
2026-08-09 08:29:57 | INFO | train task=Ses05M epoch=3 batch=740/2378 step=1375 loss=1.0378 ce=0.7605 mse=0.5546 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.146533489227295, "reserved_gb": 1.943359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "51", "gpu_mem_used_mb": "2295", "gpu_mem_total_mb": "12288", "gpu_temp_c": "55", "gpu_power_w": "90.33"}
2026-08-09 08:30:18 | INFO | train task=Ses05M epoch=3 batch=840/2378 step=1400 loss=0.2401 ce=0.1946 mse=0.0909 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1460390090942383, "reserved_gb": 1.912109375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "2263", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "71.10"}
2026-08-09 08:30:42 | INFO | train task=Ses05M epoch=3 batch=940/2378 step=1425 loss=1.2611 ce=1.0899 mse=0.3424 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1507253646850586, "reserved_gb": 2.6171875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "57", "gpu_mem_used_mb": "2985", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "70.17"}
2026-08-09 08:31:03 | INFO | train task=Ses05M epoch=3 batch=1040/2378 step=1450 loss=1.4878 ce=1.4807 mse=0.0142 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1453828811645508, "reserved_gb": 1.869140625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "48", "gpu_mem_used_mb": "2219", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "71.86"}
2026-08-09 08:31:24 | INFO | train task=Ses05M epoch=3 batch=1140/2378 step=1475 loss=1.4494 ce=1.2593 mse=0.3802 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1454663276672363, "reserved_gb": 1.9375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "28", "gpu_mem_used_mb": "2290", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "73.18"}
2026-08-09 08:31:45 | INFO | train task=Ses05M epoch=3 batch=1240/2378 step=1500 loss=0.8087 ce=0.6661 mse=0.2853 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1452751159667969, "reserved_gb": 2.10546875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "31", "gpu_mem_used_mb": "2462", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "70.78"}
2026-08-09 08:32:08 | INFO | train task=Ses05M epoch=3 batch=1340/2378 step=1525 loss=0.5280 ce=0.5180 mse=0.0202 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1479568481445312, "reserved_gb": 2.138671875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "28", "gpu_mem_used_mb": "2496", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "79.75"}
2026-08-09 08:32:28 | INFO | train task=Ses05M epoch=3 batch=1440/2378 step=1550 loss=2.0308 ce=1.9079 mse=0.2459 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1463027000427246, "reserved_gb": 1.921875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "19", "gpu_mem_used_mb": "2274", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "69.42"}
2026-08-09 08:32:50 | INFO | train task=Ses05M epoch=3 batch=1540/2378 step=1575 loss=3.5036 ce=3.4173 mse=0.1727 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1460628509521484, "reserved_gb": 1.91015625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "27", "gpu_mem_used_mb": "2262", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "66.86"}
2026-08-09 08:33:12 | INFO | train task=Ses05M epoch=3 batch=1640/2378 step=1600 loss=1.9742 ce=0.9517 mse=2.0450 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.14544677734375, "reserved_gb": 1.859375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "50", "gpu_mem_used_mb": "2210", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "52.94"}
2026-08-09 08:33:37 | INFO | train task=Ses05M epoch=3 batch=1740/2378 step=1625 loss=0.8168 ce=0.1816 mse=1.2704 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1456599235534668, "reserved_gb": 1.9375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "2290", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "65.23"}
2026-08-09 08:33:58 | INFO | train task=Ses05M epoch=3 batch=1840/2378 step=1650 loss=0.9112 ce=0.7030 mse=0.4163 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1454148292541504, "reserved_gb": 1.85546875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "2206", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "86.09"}
2026-08-09 08:34:20 | INFO | train task=Ses05M epoch=3 batch=1940/2378 step=1675 loss=0.3398 ce=0.2170 mse=0.2456 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1453986167907715, "reserved_gb": 1.857421875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "29", "gpu_mem_used_mb": "2208", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "76.92"}
2026-08-09 08:34:42 | INFO | train task=Ses05M epoch=3 batch=2040/2378 step=1700 loss=1.0541 ce=0.9762 mse=0.1559 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1452908515930176, "reserved_gb": 1.97265625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "2326", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "67.97"}
2026-08-09 08:35:08 | INFO | train task=Ses05M epoch=3 batch=2140/2378 step=1725 loss=0.1412 ce=0.0637 mse=0.1552 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.146347999572754, "reserved_gb": 1.849609375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "2200", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "58.55"}
2026-08-09 08:35:31 | INFO | train task=Ses05M epoch=3 batch=2240/2378 step=1750 loss=1.3620 ce=0.6701 mse=1.3839 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1459221839904785, "reserved_gb": 1.912109375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "30", "gpu_mem_used_mb": "2264", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "87.98"}
2026-08-09 08:35:54 | INFO | train task=Ses05M epoch=3 batch=2340/2378 step=1775 loss=1.5876 ce=1.2792 mse=0.6168 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1525769233703613, "reserved_gb": 1.85546875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "87", "gpu_mem_used_mb": "2206", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "91.27"}

predict:   0%|          | 0/303 [00:00<?, ?it/s]

2026-08-09 08:36:23 | INFO | Epoch 03 task=Ses05M train_loss=1.2559 val_macro_f1=0.4862 val_mae=0.5540 epoch_seconds=544.1

epoch 4:   0%|          | 0/2378 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 08:36:44 | INFO | train task=Ses05M epoch=4 batch=60/2378 step=1800 loss=0.3555 ce=0.1305 mse=0.4502 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1471614837646484, "reserved_gb": 1.84765625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "55", "gpu_mem_used_mb": "2157", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "72.24"}
2026-08-09 08:37:09 | INFO | train task=Ses05M epoch=4 batch=160/2378 step=1825 loss=1.1161 ce=0.7690 mse=0.6943 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.145155906677246, "reserved_gb": 1.857421875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "8", "gpu_mem_used_mb": "2208", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "68.92"}
2026-08-09 08:37:30 | INFO | train task=Ses05M epoch=4 batch=260/2378 step=1850 loss=2.4644 ce=2.3636 mse=0.2016 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1462903022766113, "reserved_gb": 2.01171875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "11", "gpu_mem_used_mb": "2366", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "68.89"}
2026-08-09 08:37:51 | INFO | train task=Ses05M epoch=4 batch=360/2378 step=1875 loss=0.7968 ce=0.3972 mse=0.7991 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.145765781402588, "reserved_gb": 1.84765625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "40", "gpu_mem_used_mb": "2198", "gpu_mem_total_mb": "12288", "gpu_temp_c": "56", "gpu_power_w": "74.81"}
2026-08-09 08:38:11 | INFO | train task=Ses05M epoch=4 batch=460/2378 step=1900 loss=0.4335 ce=0.3374 mse=0.1922 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1456212997436523, "reserved_gb": 2.125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "28", "gpu_mem_used_mb": "2482", "gpu_mem_total_mb": "12288", "gpu_temp_c": "58", "gpu_power_w": "60.24"}
2026-08-09 08:38:35 | INFO | train task=Ses05M epoch=4 batch=560/2378 step=1925 loss=0.3629 ce=0.0456 mse=0.6346 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1467576026916504, "reserved_gb": 2.3984375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "19", "gpu_mem_used_mb": "2762", "gpu_mem_total_mb": "12288", "gpu_temp_c": "59", "gpu_power_w": "66.19"}
2026-08-09 08:38:54 | INFO | train task=Ses05M epoch=4 batch=660/2378 step=1950 loss=0.6202 ce=0.3964 mse=0.4476 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1455883979797363, "reserved_gb": 1.86328125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "2214", "gpu_mem_total_mb": "12288", "gpu_temp_c": "53", "gpu_power_w": "72.48"}
2026-08-09 08:39:14 | INFO | train task=Ses05M epoch=4 batch=760/2378 step=1975 loss=0.9436 ce=0.6841 mse=0.5191 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1472430229187012, "reserved_gb": 1.84765625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "58", "gpu_mem_used_mb": "2198", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "63.37"}
2026-08-09 08:39:34 | INFO | train task=Ses05M epoch=4 batch=860/2378 step=2000 loss=1.5481 ce=1.3553 mse=0.3854 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1506328582763672, "reserved_gb": 1.8515625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "78", "gpu_mem_used_mb": "2202", "gpu_mem_total_mb": "12288", "gpu_temp_c": "54", "gpu_power_w": "73.50"}
2026-08-09 08:39:58 | INFO | train task=Ses05M epoch=4 batch=960/2378 step=2025 loss=2.6908 ce=2.5535 mse=0.2747 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1466798782348633, "reserved_gb": 2.12890625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "38", "gpu_mem_used_mb": "2486", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "70.79"}
2026-08-09 08:40:19 | INFO | train task=Ses05M epoch=4 batch=1060/2378 step=2050 loss=1.1305 ce=1.0445 mse=0.1719 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.146237850189209, "reserved_gb": 1.966796875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "23", "gpu_mem_used_mb": "2320", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "63.49"}
2026-08-09 08:40:39 | INFO | train task=Ses05M epoch=4 batch=1160/2378 step=2075 loss=1.6325 ce=1.0425 mse=1.1801 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1454758644104004, "reserved_gb": 2.09375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "24", "gpu_mem_used_mb": "2450", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "53.63"}
2026-08-09 08:41:00 | INFO | train task=Ses05M epoch=4 batch=1260/2378 step=2100 loss=2.1554 ce=2.1274 mse=0.0559 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1470885276794434, "reserved_gb": 2.138671875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "42", "gpu_mem_used_mb": "2496", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "76.70"}
2026-08-09 08:41:23 | INFO | train task=Ses05M epoch=4 batch=1360/2378 step=2125 loss=0.6266 ce=0.4624 mse=0.3284 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1453781127929688, "reserved_gb": 2.228515625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "10", "gpu_mem_used_mb": "2588", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "64.52"}
2026-08-09 08:41:43 | INFO | train task=Ses05M epoch=4 batch=1460/2378 step=2150 loss=0.6584 ce=0.6354 mse=0.0459 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.14607572555542, "reserved_gb": 2.193359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "32", "gpu_mem_used_mb": "2552", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "68.29"}
2026-08-09 08:42:06 | INFO | train task=Ses05M epoch=4 batch=1560/2378 step=2175 loss=1.9165 ce=1.7927 mse=0.2476 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1452255249023438, "reserved_gb": 1.85546875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "26", "gpu_mem_used_mb": "2206", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "85.03"}
2026-08-09 08:42:27 | INFO | train task=Ses05M epoch=4 batch=1660/2378 step=2200 loss=2.8147 ce=2.4636 mse=0.7021 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.145533561706543, "reserved_gb": 2.197265625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "52", "gpu_mem_used_mb": "2556", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "53.35"}
2026-08-09 08:42:51 | INFO | train task=Ses05M epoch=4 batch=1760/2378 step=2225 loss=1.3883 ce=0.5815 mse=1.6137 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.14556884765625, "reserved_gb": 1.9140625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "30", "gpu_mem_used_mb": "2266", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "72.61"}
2026-08-09 08:43:13 | INFO | train task=Ses05M epoch=4 batch=1860/2378 step=2250 loss=0.9912 ce=0.8648 mse=0.2528 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1452531814575195, "reserved_gb": 1.87109375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "2222", "gpu_mem_total_mb": "12288", "gpu_temp_c": "43", "gpu_power_w": "43.72"}
2026-08-09 08:43:34 | INFO | train task=Ses05M epoch=4 batch=1960/2378 step=2275 loss=2.6632 ce=2.2301 mse=0.8661 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1451053619384766, "reserved_gb": 2.1640625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "41", "gpu_mem_used_mb": "2522", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "67.93"}
2026-08-09 08:43:56 | INFO | train task=Ses05M epoch=4 batch=2060/2378 step=2300 loss=0.2933 ce=0.0475 mse=0.4916 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1455473899841309, "reserved_gb": 1.916015625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "19", "gpu_mem_used_mb": "2268", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "82.25"}
2026-08-09 08:44:21 | INFO | train task=Ses05M epoch=4 batch=2160/2378 step=2325 loss=0.8423 ce=0.3793 mse=0.9260 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.145254135131836, "reserved_gb": 1.86328125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "24", "gpu_mem_used_mb": "2214", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "73.86"}
2026-08-09 08:44:45 | INFO | train task=Ses05M epoch=4 batch=2260/2378 step=2350 loss=0.4485 ce=0.4104 mse=0.0763 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1479082107543945, "reserved_gb": 1.8515625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "40", "gpu_mem_used_mb": "2202", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "77.81"}
2026-08-09 08:45:08 | INFO | train task=Ses05M epoch=4 batch=2360/2378 step=2375 loss=0.5946 ce=0.3842 mse=0.4208 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1458439826965332, "reserved_gb": 1.84765625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "2198", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "79.30"}

predict:   0%|          | 0/303 [00:00<?, ?it/s]

2026-08-09 08:45:36 | INFO | Epoch 04 task=Ses05M train_loss=1.0857 val_macro_f1=0.4997 val_mae=0.5824 epoch_seconds=546.9

epoch 5:   0%|          | 0/2378 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 08:46:00 | INFO | train task=Ses05M epoch=5 batch=80/2378 step=2400 loss=1.2988 ce=1.0924 mse=0.4127 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1455717086791992, "reserved_gb": 2.052734375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "27", "gpu_mem_used_mb": "2388", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "66.74"}
2026-08-09 08:46:23 | INFO | train task=Ses05M epoch=5 batch=180/2378 step=2425 loss=1.0135 ce=0.9411 mse=0.1448 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1506328582763672, "reserved_gb": 2.490234375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "69", "gpu_mem_used_mb": "2844", "gpu_mem_total_mb": "12288", "gpu_temp_c": "53", "gpu_power_w": "70.46"}
2026-08-09 08:46:44 | INFO | train task=Ses05M epoch=5 batch=280/2378 step=2450 loss=0.1996 ce=0.1833 mse=0.0326 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1459951400756836, "reserved_gb": 1.84765625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "39", "gpu_mem_used_mb": "2195", "gpu_mem_total_mb": "12288", "gpu_temp_c": "55", "gpu_power_w": "83.05"}
2026-08-09 08:47:04 | INFO | train task=Ses05M epoch=5 batch=380/2378 step=2475 loss=0.2477 ce=0.1608 mse=0.1738 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1455268859863281, "reserved_gb": 1.86328125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "2211", "gpu_mem_total_mb": "12288", "gpu_temp_c": "54", "gpu_power_w": "69.03"}
2026-08-09 08:47:23 | INFO | train task=Ses05M epoch=5 batch=480/2378 step=2500 loss=1.0022 ce=0.5648 mse=0.8748 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1466412544250488, "reserved_gb": 2.041015625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "26", "gpu_mem_used_mb": "2395", "gpu_mem_total_mb": "12288", "gpu_temp_c": "53", "gpu_power_w": "39.42"}
2026-08-09 08:47:47 | INFO | train task=Ses05M epoch=5 batch=580/2378 step=2525 loss=0.4080 ce=0.3014 mse=0.2131 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.145406723022461, "reserved_gb": 1.91015625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "2261", "gpu_mem_total_mb": "12288", "gpu_temp_c": "57", "gpu_power_w": "93.52"}
2026-08-09 08:48:06 | INFO | train task=Ses05M epoch=5 batch=680/2378 step=2550 loss=3.6922 ce=2.1906 mse=3.0033 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1452240943908691, "reserved_gb": 2.025390625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "54", "gpu_mem_used_mb": "2379", "gpu_mem_total_mb": "12288", "gpu_temp_c": "57", "gpu_power_w": "85.53"}
2026-08-09 08:48:27 | INFO | train task=Ses05M epoch=5 batch=780/2378 step=2575 loss=0.4310 ce=0.2962 mse=0.2696 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1459131240844727, "reserved_gb": 2.642578125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "26", "gpu_mem_used_mb": "3011", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "75.86"}
2026-08-09 08:48:47 | INFO | train task=Ses05M epoch=5 batch=880/2378 step=2600 loss=1.0046 ce=0.9367 mse=0.1357 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1461806297302246, "reserved_gb": 1.84765625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "31", "gpu_mem_used_mb": "2197", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "70.82"}
2026-08-09 08:49:10 | INFO | train task=Ses05M epoch=5 batch=980/2378 step=2625 loss=0.5089 ce=0.4893 mse=0.0393 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.14640474319458, "reserved_gb": 1.84765625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "29", "gpu_mem_used_mb": "2197", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "64.27"}
2026-08-09 08:49:31 | INFO | train task=Ses05M epoch=5 batch=1080/2378 step=2650 loss=0.2184 ce=0.1510 mse=0.1349 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1464786529541016, "reserved_gb": 2.005859375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "40", "gpu_mem_used_mb": "2359", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "71.68"}
2026-08-09 08:49:53 | INFO | train task=Ses05M epoch=5 batch=1180/2378 step=2675 loss=0.3407 ce=0.1048 mse=0.4717 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.146550178527832, "reserved_gb": 1.927734375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "26", "gpu_mem_used_mb": "2279", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "68.78"}
2026-08-09 08:50:13 | INFO | train task=Ses05M epoch=5 batch=1280/2378 step=2700 loss=1.6205 ce=0.8254 mse=1.5901 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1454143524169922, "reserved_gb": 2.126953125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "29", "gpu_mem_used_mb": "2483", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "62.71"}
2026-08-09 08:50:38 | INFO | train task=Ses05M epoch=5 batch=1380/2378 step=2725 loss=0.8489 ce=0.6357 mse=0.4264 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1468596458435059, "reserved_gb": 1.953125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "24", "gpu_mem_used_mb": "2305", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "67.86"}
2026-08-09 08:51:01 | INFO | train task=Ses05M epoch=5 batch=1480/2378 step=2750 loss=1.8707 ce=1.8493 mse=0.0429 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1454687118530273, "reserved_gb": 1.86328125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "2213", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "62.54"}
2026-08-09 08:51:22 | INFO | train task=Ses05M epoch=5 batch=1580/2378 step=2775 loss=2.5847 ce=2.5602 mse=0.0490 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.147824764251709, "reserved_gb": 1.849609375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "65", "gpu_mem_used_mb": "2199", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "76.23"}
2026-08-09 08:51:43 | INFO | train task=Ses05M epoch=5 batch=1680/2378 step=2800 loss=0.4100 ce=0.3188 mse=0.1825 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.14530611038208, "reserved_gb": 1.86328125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "2213", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "63.87"}
2026-08-09 08:52:07 | INFO | train task=Ses05M epoch=5 batch=1780/2378 step=2825 loss=2.6391 ce=2.5844 mse=0.1095 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1459159851074219, "reserved_gb": 1.8984375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "50", "gpu_mem_used_mb": "2249", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "69.40"}
2026-08-09 08:52:28 | INFO | train task=Ses05M epoch=5 batch=1880/2378 step=2850 loss=0.5577 ce=0.3102 mse=0.4950 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1457791328430176, "reserved_gb": 2.126953125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "2483", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "73.28"}
2026-08-09 08:52:49 | INFO | train task=Ses05M epoch=5 batch=1980/2378 step=2875 loss=1.7192 ce=1.4585 mse=0.5214 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1452393531799316, "reserved_gb": 1.8515625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "2201", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "64.21"}
2026-08-09 08:53:13 | INFO | train task=Ses05M epoch=5 batch=2080/2378 step=2900 loss=0.2131 ce=0.0589 mse=0.3085 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1506328582763672, "reserved_gb": 2.203125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "29", "gpu_mem_used_mb": "2561", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "81.56"}
2026-08-09 08:53:40 | INFO | train task=Ses05M epoch=5 batch=2180/2378 step=2925 loss=0.3530 ce=0.2619 mse=0.1822 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1488676071166992, "reserved_gb": 2.095703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "41", "gpu_mem_used_mb": "2451", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "75.33"}
2026-08-09 08:54:01 | INFO | train task=Ses05M epoch=5 batch=2280/2378 step=2950 loss=0.9673 ce=0.7228 mse=0.4891 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.145646095275879, "reserved_gb": 1.869140625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "30", "gpu_mem_used_mb": "2219", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "67.01"}
2026-08-09 08:54:23 | INFO | train task=Ses05M epoch=5 batch=2378/2378 step=2975 loss=0.4537 ce=0.1217 mse=0.6641 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1450657844543457, "reserved_gb": 1.84765625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "44", "gpu_mem_used_mb": "2197", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "76.04"}

predict:   0%|          | 0/303 [00:00<?, ?it/s]

2026-08-09 08:54:44 | INFO | Epoch 05 task=Ses05M train_loss=0.9609 val_macro_f1=0.5174 val_mae=0.5417 epoch_seconds=542.6

epoch 6:   0%|          | 0/2378 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 08:55:10 | INFO | train task=Ses05M epoch=6 batch=100/2378 step=3000 loss=0.3998 ce=0.3777 mse=0.0441 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1462302207946777, "reserved_gb": 2.177734375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "41", "gpu_mem_used_mb": "2500", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "65.60"}
2026-08-09 08:55:34 | INFO | train task=Ses05M epoch=6 batch=200/2378 step=3025 loss=0.1084 ce=0.0933 mse=0.0303 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1470365524291992, "reserved_gb": 2.07421875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "30", "gpu_mem_used_mb": "2429", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "71.64"}
2026-08-09 08:55:55 | INFO | train task=Ses05M epoch=6 batch=300/2378 step=3050 loss=0.5383 ce=0.4377 mse=0.2011 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1488676071166992, "reserved_gb": 2.166015625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "40", "gpu_mem_used_mb": "2523", "gpu_mem_total_mb": "12288", "gpu_temp_c": "53", "gpu_power_w": "70.45"}
2026-08-09 08:56:14 | INFO | train task=Ses05M epoch=6 batch=400/2378 step=3075 loss=3.0035 ce=2.9438 mse=0.1193 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1450700759887695, "reserved_gb": 2.40234375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "19", "gpu_mem_used_mb": "2765", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "71.36"}
2026-08-09 08:56:33 | INFO | train task=Ses05M epoch=6 batch=500/2378 step=3100 loss=0.6745 ce=0.6187 mse=0.1116 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.145726203918457, "reserved_gb": 1.84765625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "2197", "gpu_mem_total_mb": "12288", "gpu_temp_c": "56", "gpu_power_w": "91.05"}
2026-08-09 08:56:57 | INFO | train task=Ses05M epoch=6 batch=600/2378 step=3125 loss=2.4448 ce=2.2923 mse=0.3050 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1452751159667969, "reserved_gb": 2.33984375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "41", "gpu_mem_used_mb": "2701", "gpu_mem_total_mb": "12288", "gpu_temp_c": "57", "gpu_power_w": "75.61"}
2026-08-09 08:57:17 | INFO | train task=Ses05M epoch=6 batch=700/2378 step=3150 loss=0.2678 ce=0.1923 mse=0.1510 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.146247386932373, "reserved_gb": 2.197265625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "37", "gpu_mem_used_mb": "2555", "gpu_mem_total_mb": "12288", "gpu_temp_c": "57", "gpu_power_w": "77.47"}
2026-08-09 08:57:37 | INFO | train task=Ses05M epoch=6 batch=800/2378 step=3175 loss=0.3087 ce=0.2920 mse=0.0334 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1462492942810059, "reserved_gb": 2.076171875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "34", "gpu_mem_used_mb": "2431", "gpu_mem_total_mb": "12288", "gpu_temp_c": "54", "gpu_power_w": "68.59"}
2026-08-09 08:57:57 | INFO | train task=Ses05M epoch=6 batch=900/2378 step=3200 loss=0.7609 ce=0.2257 mse=1.0704 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1456518173217773, "reserved_gb": 2.091796875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "36", "gpu_mem_used_mb": "2447", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "76.43"}
2026-08-09 08:58:21 | INFO | train task=Ses05M epoch=6 batch=1000/2378 step=3225 loss=2.2896 ce=2.2665 mse=0.0462 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1450858116149902, "reserved_gb": 1.90234375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "25", "gpu_mem_used_mb": "2253", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "59.64"}
2026-08-09 08:58:42 | INFO | train task=Ses05M epoch=6 batch=1100/2378 step=3250 loss=0.2872 ce=0.1223 mse=0.3298 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1464262008666992, "reserved_gb": 2.068359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "2423", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "62.71"}
2026-08-09 08:59:04 | INFO | train task=Ses05M epoch=6 batch=1200/2378 step=3275 loss=1.9734 ce=1.5687 mse=0.8092 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1456279754638672, "reserved_gb": 1.869140625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "36", "gpu_mem_used_mb": "2220", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "69.15"}
2026-08-09 08:59:23 | INFO | train task=Ses05M epoch=6 batch=1300/2378 step=3300 loss=0.7342 ce=0.7019 mse=0.0646 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1454930305480957, "reserved_gb": 1.861328125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "35", "gpu_mem_used_mb": "2212", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "77.97"}
2026-08-09 08:59:49 | INFO | train task=Ses05M epoch=6 batch=1400/2378 step=3325 loss=0.2109 ce=0.1864 mse=0.0489 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1450672149658203, "reserved_gb": 1.84765625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "100", "gpu_mem_used_mb": "2198", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "70.07"}
2026-08-09 09:00:09 | INFO | train task=Ses05M epoch=6 batch=1500/2378 step=3350 loss=1.2843 ce=0.9975 mse=0.5735 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.145956039428711, "reserved_gb": 1.900390625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "26", "gpu_mem_used_mb": "2252", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "62.69"}
2026-08-09 09:00:29 | INFO | train task=Ses05M epoch=6 batch=1600/2378 step=3375 loss=1.6539 ce=1.5962 mse=0.1155 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1457386016845703, "reserved_gb": 1.84765625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "2198", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "66.64"}
2026-08-09 09:00:49 | INFO | train task=Ses05M epoch=6 batch=1700/2378 step=3400 loss=0.5104 ce=0.1360 mse=0.7489 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1454954147338867, "reserved_gb": 1.904296875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "38", "gpu_mem_used_mb": "2256", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "75.05"}
2026-08-09 09:01:14 | INFO | train task=Ses05M epoch=6 batch=1800/2378 step=3425 loss=0.3791 ce=0.3520 mse=0.0540 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.145510196685791, "reserved_gb": 2.447265625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "14", "gpu_mem_used_mb": "2832", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "67.59"}
2026-08-09 09:01:36 | INFO | train task=Ses05M epoch=6 batch=1900/2378 step=3450 loss=0.6867 ce=0.4045 mse=0.5644 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1464123725891113, "reserved_gb": 1.84765625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "43", "gpu_mem_used_mb": "2218", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "80.64"}
2026-08-09 09:01:58 | INFO | train task=Ses05M epoch=6 batch=2000/2378 step=3475 loss=0.9514 ce=0.6103 mse=0.6822 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1459178924560547, "reserved_gb": 1.94921875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "23", "gpu_mem_used_mb": "2322", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "91.39"}
2026-08-09 09:02:21 | INFO | train task=Ses05M epoch=6 batch=2100/2378 step=3500 loss=0.7730 ce=0.2187 mse=1.1087 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1453638076782227, "reserved_gb": 1.853515625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "24", "gpu_mem_used_mb": "2224", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "67.06"}
2026-08-09 09:02:47 | INFO | train task=Ses05M epoch=6 batch=2200/2378 step=3525 loss=0.4426 ce=0.4299 mse=0.0254 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1455354690551758, "reserved_gb": 1.8671875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "19", "gpu_mem_used_mb": "2238", "gpu_mem_total_mb": "12288", "gpu_temp_c": "44", "gpu_power_w": "51.88"}
2026-08-09 09:03:11 | INFO | train task=Ses05M epoch=6 batch=2300/2378 step=3550 loss=0.2725 ce=0.2045 mse=0.1360 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1470661163330078, "reserved_gb": 1.84765625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "51", "gpu_mem_used_mb": "2218", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "70.31"}

predict:   0%|          | 0/303 [00:00<?, ?it/s]

2026-08-09 09:03:50 | INFO | Epoch 06 task=Ses05M train_loss=0.8569 val_macro_f1=0.5251 val_mae=0.5329 epoch_seconds=540.8

epoch 7:   0%|          | 0/2378 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 09:04:03 | INFO | train task=Ses05M epoch=7 batch=20/2378 step=3575 loss=0.1622 ce=0.1114 mse=0.1015 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1465721130371094, "reserved_gb": 12.3828125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "80", "gpu_mem_used_mb": "12104", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "57.66"}
2026-08-09 09:04:24 | INFO | train task=Ses05M epoch=7 batch=120/2378 step=3600 loss=0.6850 ce=0.6577 mse=0.0546 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1456012725830078, "reserved_gb": 1.8671875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "14", "gpu_mem_used_mb": "2184", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "75.04"}
2026-08-09 09:04:48 | INFO | train task=Ses05M epoch=7 batch=220/2378 step=3625 loss=0.2996 ce=0.2971 mse=0.0050 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.145956039428711, "reserved_gb": 2.37109375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "26", "gpu_mem_used_mb": "2700", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "67.75"}
2026-08-09 09:05:10 | INFO | train task=Ses05M epoch=7 batch=320/2378 step=3650 loss=0.1912 ce=0.1468 mse=0.0887 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.145136833190918, "reserved_gb": 2.125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "33", "gpu_mem_used_mb": "2448", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "66.95"}
2026-08-09 09:05:31 | INFO | train task=Ses05M epoch=7 batch=420/2378 step=3675 loss=1.2370 ce=1.1955 mse=0.0830 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1461834907531738, "reserved_gb": 1.84765625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "25", "gpu_mem_used_mb": "2201", "gpu_mem_total_mb": "12288", "gpu_temp_c": "56", "gpu_power_w": "67.07"}
2026-08-09 09:05:50 | INFO | train task=Ses05M epoch=7 batch=520/2378 step=3700 loss=1.9027 ce=1.8270 mse=0.1514 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.146430492401123, "reserved_gb": 2.0625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "50", "gpu_mem_used_mb": "2421", "gpu_mem_total_mb": "12288", "gpu_temp_c": "57", "gpu_power_w": "78.73"}
2026-08-09 09:06:13 | INFO | train task=Ses05M epoch=7 batch=620/2378 step=3725 loss=1.0826 ce=1.0594 mse=0.0465 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1453619003295898, "reserved_gb": 2.12890625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "36", "gpu_mem_used_mb": "2489", "gpu_mem_total_mb": "12288", "gpu_temp_c": "58", "gpu_power_w": "66.93"}
2026-08-09 09:06:33 | INFO | train task=Ses05M epoch=7 batch=720/2378 step=3750 loss=0.5651 ce=0.5100 mse=0.1103 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1456818580627441, "reserved_gb": 1.869140625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "19", "gpu_mem_used_mb": "2223", "gpu_mem_total_mb": "12288", "gpu_temp_c": "55", "gpu_power_w": "68.21"}
2026-08-09 09:06:53 | INFO | train task=Ses05M epoch=7 batch=820/2378 step=3775 loss=1.1923 ce=1.0901 mse=0.2044 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1456785202026367, "reserved_gb": 1.8671875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "2221", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "63.28"}
2026-08-09 09:07:13 | INFO | train task=Ses05M epoch=7 batch=920/2378 step=3800 loss=0.3371 ce=0.0329 mse=0.6084 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1459221839904785, "reserved_gb": 2.138671875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "38", "gpu_mem_used_mb": "2499", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "71.18"}
2026-08-09 09:07:36 | INFO | train task=Ses05M epoch=7 batch=1020/2378 step=3825 loss=0.4906 ce=0.3442 mse=0.2928 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1453018188476562, "reserved_gb": 2.287109375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "2651", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "73.10"}
2026-08-09 09:07:57 | INFO | train task=Ses05M epoch=7 batch=1120/2378 step=3850 loss=2.5788 ce=2.2946 mse=0.5684 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.145273208618164, "reserved_gb": 1.849609375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "79", "gpu_mem_used_mb": "2203", "gpu_mem_total_mb": "12288", "gpu_temp_c": "54", "gpu_power_w": "83.01"}
2026-08-09 09:08:18 | INFO | train task=Ses05M epoch=7 batch=1220/2378 step=3875 loss=0.2604 ce=0.1265 mse=0.2678 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.14607572555542, "reserved_gb": 2.0234375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "2381", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "68.35"}
2026-08-09 09:08:38 | INFO | train task=Ses05M epoch=7 batch=1320/2378 step=3900 loss=1.9181 ce=1.8284 mse=0.1794 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1457481384277344, "reserved_gb": 1.91796875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "24", "gpu_mem_used_mb": "2273", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "65.44"}
2026-08-09 09:09:03 | INFO | train task=Ses05M epoch=7 batch=1420/2378 step=3925 loss=2.4145 ce=2.2958 mse=0.2375 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.145982265472412, "reserved_gb": 1.90625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "10", "gpu_mem_used_mb": "2261", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "88.47"}
2026-08-09 09:09:23 | INFO | train task=Ses05M epoch=7 batch=1520/2378 step=3950 loss=1.2359 ce=1.2116 mse=0.0487 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1453561782836914, "reserved_gb": 2.12890625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "2490", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "62.08"}
2026-08-09 09:09:44 | INFO | train task=Ses05M epoch=7 batch=1620/2378 step=3975 loss=0.6098 ce=0.4195 mse=0.3806 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.145277976989746, "reserved_gb": 1.8515625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "19", "gpu_mem_used_mb": "2206", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "59.12"}
2026-08-09 09:10:05 | INFO | train task=Ses05M epoch=7 batch=1720/2378 step=4000 loss=2.0582 ce=2.0355 mse=0.0455 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1457109451293945, "reserved_gb": 1.84765625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "39", "gpu_mem_used_mb": "2202", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "67.69"}
2026-08-09 09:10:29 | INFO | train task=Ses05M epoch=7 batch=1820/2378 step=4025 loss=1.7392 ce=1.5633 mse=0.3518 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1462807655334473, "reserved_gb": 2.09765625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "47", "gpu_mem_used_mb": "2458", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "64.18"}
2026-08-09 09:10:49 | INFO | train task=Ses05M epoch=7 batch=1920/2378 step=4050 loss=0.7500 ce=0.7021 mse=0.0958 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1451497077941895, "reserved_gb": 2.123046875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "26", "gpu_mem_used_mb": "2484", "gpu_mem_total_mb": "12288", "gpu_temp_c": "43", "gpu_power_w": "41.70"}
2026-08-09 09:11:10 | INFO | train task=Ses05M epoch=7 batch=2020/2378 step=4075 loss=0.4871 ce=0.1258 mse=0.7226 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.145592212677002, "reserved_gb": 1.869140625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "2224", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "61.51"}
2026-08-09 09:11:33 | INFO | train task=Ses05M epoch=7 batch=2120/2378 step=4100 loss=0.0712 ce=0.0335 mse=0.0754 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.148054599761963, "reserved_gb": 1.84765625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "76", "gpu_mem_used_mb": "2202", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "81.40"}
2026-08-09 09:11:57 | INFO | train task=Ses05M epoch=7 batch=2220/2378 step=4125 loss=1.0377 ce=0.3048 mse=1.4658 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.14544677734375, "reserved_gb": 1.86328125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "24", "gpu_mem_used_mb": "2218", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "71.54"}
2026-08-09 09:12:20 | INFO | train task=Ses05M epoch=7 batch=2320/2378 step=4150 loss=0.0679 ce=0.0338 mse=0.0683 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.146162986755371, "reserved_gb": 2.1484375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "43", "gpu_mem_used_mb": "2510", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "82.19"}

predict:   0%|          | 0/303 [00:00<?, ?it/s]

2026-08-09 09:12:54 | INFO | Epoch 07 task=Ses05M train_loss=0.7658 val_macro_f1=0.5104 val_mae=0.5486 epoch_seconds=538.8

epoch 8:   0%|          | 0/2378 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 09:13:05 | INFO | train task=Ses05M epoch=8 batch=40/2378 step=4175 loss=1.3063 ce=1.2697 mse=0.0732 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1462492942810059, "reserved_gb": 2.083984375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "32", "gpu_mem_used_mb": "2444", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "63.99"}
2026-08-09 09:13:25 | INFO | train task=Ses05M epoch=8 batch=140/2378 step=4200 loss=0.2474 ce=0.0436 mse=0.4076 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1506328582763672, "reserved_gb": 1.853515625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "29", "gpu_mem_used_mb": "2208", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "70.82"}
2026-08-09 09:13:50 | INFO | train task=Ses05M epoch=8 batch=240/2378 step=4225 loss=0.6552 ce=0.5425 mse=0.2254 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1458959579467773, "reserved_gb": 1.84765625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "32", "gpu_mem_used_mb": "2202", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "74.98"}
2026-08-09 09:14:10 | INFO | train task=Ses05M epoch=8 batch=340/2378 step=4250 loss=0.2059 ce=0.0944 mse=0.2231 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.145841121673584, "reserved_gb": 2.03125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "23", "gpu_mem_used_mb": "2390", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "67.49"}
2026-08-09 09:14:30 | INFO | train task=Ses05M epoch=8 batch=440/2378 step=4275 loss=5.1565 ce=4.3251 mse=1.6629 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1451373100280762, "reserved_gb": 1.97265625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "2330", "gpu_mem_total_mb": "12288", "gpu_temp_c": "44", "gpu_power_w": "47.06"}
2026-08-09 09:14:50 | INFO | train task=Ses05M epoch=8 batch=540/2378 step=4300 loss=0.6512 ce=0.5236 mse=0.2552 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1454205513000488, "reserved_gb": 1.859375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "57", "gpu_mem_used_mb": "2214", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "69.76"}
2026-08-09 09:15:14 | INFO | train task=Ses05M epoch=8 batch=640/2378 step=4325 loss=1.3436 ce=1.2457 mse=0.1956 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.145604133605957, "reserved_gb": 1.8671875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "13", "gpu_mem_used_mb": "2222", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "67.70"}
2026-08-09 09:15:33 | INFO | train task=Ses05M epoch=8 batch=740/2378 step=4350 loss=0.7725 ce=0.7593 mse=0.0264 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.145348072052002, "reserved_gb": 1.8671875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "27", "gpu_mem_used_mb": "2222", "gpu_mem_total_mb": "12288", "gpu_temp_c": "43", "gpu_power_w": "55.82"}
2026-08-09 09:15:53 | INFO | train task=Ses05M epoch=8 batch=840/2378 step=4375 loss=0.2125 ce=0.1163 mse=0.1924 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.146836757659912, "reserved_gb": 1.9453125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "43", "gpu_mem_used_mb": "2302", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "66.08"}
2026-08-09 09:16:14 | INFO | train task=Ses05M epoch=8 batch=940/2378 step=4400 loss=0.4332 ce=0.0148 mse=0.8369 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.147141933441162, "reserved_gb": 1.84765625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "65", "gpu_mem_used_mb": "2202", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "70.20"}
2026-08-09 09:16:38 | INFO | train task=Ses05M epoch=8 batch=1040/2378 step=4425 loss=0.7978 ce=0.1085 mse=1.3787 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1455326080322266, "reserved_gb": 1.919921875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "32", "gpu_mem_used_mb": "2276", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "79.13"}
2026-08-09 09:16:58 | INFO | train task=Ses05M epoch=8 batch=1140/2378 step=4450 loss=0.3439 ce=0.2785 mse=0.1308 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1465134620666504, "reserved_gb": 2.04296875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "44", "gpu_mem_used_mb": "2402", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "63.80"}
2026-08-09 09:17:20 | INFO | train task=Ses05M epoch=8 batch=1240/2378 step=4475 loss=0.4079 ce=0.3275 mse=0.1608 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1458101272583008, "reserved_gb": 2.03515625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "44", "gpu_mem_used_mb": "2394", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "86.38"}
2026-08-09 09:17:43 | INFO | train task=Ses05M epoch=8 batch=1340/2378 step=4500 loss=0.3230 ce=0.3206 mse=0.0049 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1460890769958496, "reserved_gb": 1.96484375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "51", "gpu_mem_used_mb": "2322", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "77.58"}
2026-08-09 09:18:07 | INFO | train task=Ses05M epoch=8 batch=1440/2378 step=4525 loss=0.3599 ce=0.2901 mse=0.1395 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1469240188598633, "reserved_gb": 2.046875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "30", "gpu_mem_used_mb": "2406", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "72.98"}
2026-08-09 09:18:28 | INFO | train task=Ses05M epoch=8 batch=1540/2378 step=4550 loss=0.3421 ce=0.2715 mse=0.1411 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1454286575317383, "reserved_gb": 1.865234375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "25", "gpu_mem_used_mb": "2220", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "71.33"}
2026-08-09 09:18:51 | INFO | train task=Ses05M epoch=8 batch=1640/2378 step=4575 loss=0.2187 ce=0.1910 mse=0.0553 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.145573616027832, "reserved_gb": 1.8671875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "50", "gpu_mem_used_mb": "2222", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "100.59"}
2026-08-09 09:19:12 | INFO | train task=Ses05M epoch=8 batch=1740/2378 step=4600 loss=0.1681 ce=0.0359 mse=0.2644 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.147911548614502, "reserved_gb": 1.849609375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "43", "gpu_mem_used_mb": "2204", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "74.09"}
2026-08-09 09:19:36 | INFO | train task=Ses05M epoch=8 batch=1840/2378 step=4625 loss=0.2412 ce=0.0557 mse=0.3711 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1456117630004883, "reserved_gb": 2.33203125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "44", "gpu_mem_used_mb": "2698", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "65.76"}
2026-08-09 09:19:59 | INFO | train task=Ses05M epoch=8 batch=1940/2378 step=4650 loss=2.8604 ce=2.2344 mse=1.2521 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1452598571777344, "reserved_gb": 1.908203125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "24", "gpu_mem_used_mb": "2264", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "64.88"}
2026-08-09 09:20:21 | INFO | train task=Ses05M epoch=8 batch=2040/2378 step=4675 loss=0.1401 ce=0.1167 mse=0.0469 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1453471183776855, "reserved_gb": 1.8515625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "2206", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "64.20"}
2026-08-09 09:20:43 | INFO | train task=Ses05M epoch=8 batch=2140/2378 step=4700 loss=0.8683 ce=0.6902 mse=0.3563 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1451435089111328, "reserved_gb": 1.84765625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "24", "gpu_mem_used_mb": "2202", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "79.89"}
2026-08-09 09:21:09 | INFO | train task=Ses05M epoch=8 batch=2240/2378 step=4725 loss=2.1760 ce=1.9694 mse=0.4132 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1462340354919434, "reserved_gb": 1.970703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "23", "gpu_mem_used_mb": "2328", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "72.31"}
2026-08-09 09:21:33 | INFO | train task=Ses05M epoch=8 batch=2340/2378 step=4750 loss=0.1113 ce=0.0202 mse=0.1822 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.145582675933838, "reserved_gb": 1.869140625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "37", "gpu_mem_used_mb": "2224", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "73.03"}

predict:   0%|          | 0/303 [00:00<?, ?it/s]

2026-08-09 09:22:04 | INFO | Epoch 08 task=Ses05M train_loss=0.6894 val_macro_f1=0.5075 val_mae=0.5680 epoch_seconds=546.4

predict:   0%|          | 0/261 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)

predict:   0%|          | 0/442 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
2026-08-09 09:23:49 | INFO | Task 5cc793bc30552668_main_fold -> complete
2026-08-09 09:23:51 | INFO | Manuscript outputs refreshed: 21 tables, 4 figures
2026-08-09 09:23:51 | INFO | Task 5819fd4ddc4d955f_main_fold -> running
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\transformers\configuration_utils.py:335: UserWarning: Passing `gradient_checkpointing` to a config initialization is deprecated and will be removed in v5 Transformers. Using `model.gradient_checkpointing_enable()` instead, or if you are using the `Trainer` API, pass `gradient_checkpointing=True` in your `TrainingArguments`.
  warnings.warn(
2026-08-09 09:23:53 | INFO | Task C:\Users\HaseebWajid\Downloads\runs\dersx_paper_aligned\campaign_01\main\seed_29\Ses01F parameters={'total': 163009451, 'trainable': 69034283, 'frozen': 93975168} scope={'corpus': 'IEMOCAP', 'protocol': 'strict_LOSO', 'heldout_speaker': 'Ses01F', 'seed': 29, 'stage': 'main', 'profile': 'rtx3060_24h'}

epoch 1:   0%|          | 0/2395 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 09:24:17 | INFO | train task=Ses01F epoch=1 batch=100/2395 step=25 loss=3.2245 ce=2.2541 mse=1.9407 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.269162178039551, "reserved_gb": 2.94140625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "23", "gpu_mem_used_mb": "3320", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "91.17"}
2026-08-09 09:24:39 | INFO | train task=Ses01F epoch=1 batch=200/2395 step=50 loss=2.8086 ce=2.1533 mse=1.3106 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2747650146484375, "reserved_gb": 2.90234375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "89", "gpu_mem_used_mb": "3280", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "86.88"}
2026-08-09 09:25:00 | INFO | train task=Ses01F epoch=1 batch=300/2395 step=75 loss=3.2503 ce=2.3914 mse=1.7180 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2696280479431152, "reserved_gb": 2.91796875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "19", "gpu_mem_used_mb": "3296", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "63.10"}
2026-08-09 09:25:23 | INFO | train task=Ses01F epoch=1 batch=400/2395 step=100 loss=3.6271 ce=2.0364 mse=3.1813 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2800774574279785, "reserved_gb": 2.9921875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "98", "gpu_mem_used_mb": "3372", "gpu_mem_total_mb": "12288", "gpu_temp_c": "53", "gpu_power_w": "98.39"}
2026-08-09 09:25:52 | INFO | train task=Ses01F epoch=1 batch=500/2395 step=125 loss=2.0249 ce=1.8232 mse=0.4034 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2710952758789062, "reserved_gb": 2.87109375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "37", "gpu_mem_used_mb": "3248", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "92.47"}
2026-08-09 09:26:13 | INFO | train task=Ses01F epoch=1 batch=600/2395 step=150 loss=2.7531 ce=1.9785 mse=1.5492 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.270388126373291, "reserved_gb": 2.921875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "39", "gpu_mem_used_mb": "3300", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "70.28"}
2026-08-09 09:26:36 | INFO | train task=Ses01F epoch=1 batch=700/2395 step=175 loss=2.3104 ce=2.0643 mse=0.4921 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2699317932128906, "reserved_gb": 2.982421875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "65", "gpu_mem_used_mb": "3362", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "98.71"}
2026-08-09 09:26:59 | INFO | train task=Ses01F epoch=1 batch=800/2395 step=200 loss=2.0627 ce=1.7437 mse=0.6382 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.269397258758545, "reserved_gb": 2.828125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "33", "gpu_mem_used_mb": "3204", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "75.48"}
2026-08-09 09:27:32 | INFO | train task=Ses01F epoch=1 batch=900/2395 step=225 loss=2.5465 ce=2.3697 mse=0.3535 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2693562507629395, "reserved_gb": 2.845703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "28", "gpu_mem_used_mb": "3222", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "59.99"}
2026-08-09 09:27:52 | INFO | train task=Ses01F epoch=1 batch=1000/2395 step=250 loss=1.7766 ce=1.6475 mse=0.2584 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2696433067321777, "reserved_gb": 2.84765625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "3224", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "69.62"}
2026-08-09 09:28:14 | INFO | train task=Ses01F epoch=1 batch=1100/2395 step=275 loss=1.4116 ce=1.0967 mse=0.6299 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2696356773376465, "reserved_gb": 2.849609375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "3226", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "60.12"}
2026-08-09 09:28:37 | INFO | train task=Ses01F epoch=1 batch=1200/2395 step=300 loss=1.3411 ce=1.0516 mse=0.5792 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2696328163146973, "reserved_gb": 2.970703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "25", "gpu_mem_used_mb": "3350", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "83.64"}
2026-08-09 09:29:04 | INFO | train task=Ses01F epoch=1 batch=1300/2395 step=325 loss=1.5220 ce=1.5153 mse=0.0135 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2701950073242188, "reserved_gb": 3.04296875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "55", "gpu_mem_used_mb": "3424", "gpu_mem_total_mb": "12288", "gpu_temp_c": "53", "gpu_power_w": "107.44"}
2026-08-09 09:29:26 | INFO | train task=Ses01F epoch=1 batch=1400/2395 step=350 loss=1.7637 ce=1.3882 mse=0.7511 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.269690990447998, "reserved_gb": 2.859375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "32", "gpu_mem_used_mb": "3236", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "65.59"}
2026-08-09 09:29:49 | INFO | train task=Ses01F epoch=1 batch=1500/2395 step=375 loss=1.7842 ce=1.7240 mse=0.1205 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.269620418548584, "reserved_gb": 2.849609375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "36", "gpu_mem_used_mb": "3226", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "68.52"}
2026-08-09 09:30:14 | INFO | train task=Ses01F epoch=1 batch=1600/2395 step=400 loss=1.3091 ce=1.1662 mse=0.2857 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.269627094268799, "reserved_gb": 2.833984375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "18", "gpu_mem_used_mb": "3210", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "78.55"}
2026-08-09 09:30:41 | INFO | train task=Ses01F epoch=1 batch=1700/2395 step=425 loss=3.2242 ce=2.4441 mse=1.5602 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2693943977355957, "reserved_gb": 2.9140625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "53", "gpu_mem_used_mb": "3292", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "72.25"}
2026-08-09 09:31:04 | INFO | train task=Ses01F epoch=1 batch=1800/2395 step=450 loss=1.7205 ce=1.6122 mse=0.2166 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2694387435913086, "reserved_gb": 2.828125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "18", "gpu_mem_used_mb": "3204", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "61.69"}
2026-08-09 09:31:27 | INFO | train task=Ses01F epoch=1 batch=1900/2395 step=475 loss=1.1012 ce=0.8896 mse=0.4230 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.271146297454834, "reserved_gb": 2.90625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "44", "gpu_mem_used_mb": "3284", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "74.17"}
2026-08-09 09:31:51 | INFO | train task=Ses01F epoch=1 batch=2000/2395 step=500 loss=2.0006 ce=1.6265 mse=0.7482 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2698869705200195, "reserved_gb": 2.904296875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "3282", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "76.79"}
2026-08-09 09:32:18 | INFO | train task=Ses01F epoch=1 batch=2100/2395 step=525 loss=1.8009 ce=1.7538 mse=0.0942 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2700881958007812, "reserved_gb": 2.955078125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "47", "gpu_mem_used_mb": "3334", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "85.03"}
2026-08-09 09:32:40 | INFO | train task=Ses01F epoch=1 batch=2200/2395 step=550 loss=0.6396 ce=0.3902 mse=0.4987 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2698564529418945, "reserved_gb": 2.857421875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "3234", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "65.30"}
2026-08-09 09:33:03 | INFO | train task=Ses01F epoch=1 batch=2300/2395 step=575 loss=1.1720 ce=1.0947 mse=0.1547 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2694435119628906, "reserved_gb": 2.931640625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "41", "gpu_mem_used_mb": "3310", "gpu_mem_total_mb": "12288", "gpu_temp_c": "44", "gpu_power_w": "47.69"}

predict:   0%|          | 0/313 [00:00<?, ?it/s]

2026-08-09 09:34:07 | INFO | Epoch 01 task=Ses01F train_loss=2.0966 val_macro_f1=0.3888 val_mae=0.5116 epoch_seconds=613.1

epoch 2:   0%|          | 0/2395 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 09:34:14 | INFO | train task=Ses01F epoch=2 batch=4/2395 step=600 loss=1.4637 ce=0.7744 mse=1.3785 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2703652381896973, "reserved_gb": 2.841796875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "18", "gpu_mem_used_mb": "3218", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "37.06"}
2026-08-09 09:34:38 | INFO | train task=Ses01F epoch=2 batch=104/2395 step=625 loss=1.7290 ce=1.3042 mse=0.8496 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2695817947387695, "reserved_gb": 3.0234375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "28", "gpu_mem_used_mb": "3404", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "69.31"}
2026-08-09 09:34:58 | INFO | train task=Ses01F epoch=2 batch=204/2395 step=650 loss=0.9331 ce=0.7862 mse=0.2939 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.269343376159668, "reserved_gb": 3.615234375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "49", "gpu_mem_used_mb": "4010", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "80.39"}
2026-08-09 09:35:19 | INFO | train task=Ses01F epoch=2 batch=304/2395 step=675 loss=1.8477 ce=1.5440 mse=0.6074 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.269561290740967, "reserved_gb": 3.142578125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "32", "gpu_mem_used_mb": "3526", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "66.50"}
2026-08-09 09:35:39 | INFO | train task=Ses01F epoch=2 batch=404/2395 step=700 loss=2.4721 ce=2.1786 mse=0.5869 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2702622413635254, "reserved_gb": 2.8984375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "3276", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "60.06"}
2026-08-09 09:36:01 | INFO | train task=Ses01F epoch=2 batch=504/2395 step=725 loss=1.1373 ce=1.1350 mse=0.0046 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2695722579956055, "reserved_gb": 2.96484375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "3344", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "69.74"}
2026-08-09 09:36:22 | INFO | train task=Ses01F epoch=2 batch=604/2395 step=750 loss=1.5241 ce=0.6370 mse=1.7743 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2700753211975098, "reserved_gb": 2.916015625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "31", "gpu_mem_used_mb": "3294", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "64.19"}
2026-08-09 09:36:41 | INFO | train task=Ses01F epoch=2 batch=704/2395 step=775 loss=1.0015 ce=0.8284 mse=0.3463 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2705078125, "reserved_gb": 3.056640625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "27", "gpu_mem_used_mb": "3438", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "77.43"}
2026-08-09 09:37:03 | INFO | train task=Ses01F epoch=2 batch=804/2395 step=800 loss=1.5240 ce=1.2173 mse=0.6134 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2747650146484375, "reserved_gb": 2.89453125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "44", "gpu_mem_used_mb": "3272", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "85.69"}
2026-08-09 09:37:26 | INFO | train task=Ses01F epoch=2 batch=904/2395 step=825 loss=0.5176 ce=0.4343 mse=0.1666 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.269416332244873, "reserved_gb": 3.205078125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "36", "gpu_mem_used_mb": "3590", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "69.27"}
2026-08-09 09:37:45 | INFO | train task=Ses01F epoch=2 batch=1004/2395 step=850 loss=2.2526 ce=2.2463 mse=0.0125 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.270144462585449, "reserved_gb": 3.12890625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "53", "gpu_mem_used_mb": "3512", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "70.88"}
2026-08-09 09:38:05 | INFO | train task=Ses01F epoch=2 batch=1104/2395 step=875 loss=1.6990 ce=1.4589 mse=0.4803 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.270268440246582, "reserved_gb": 3.533203125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "26", "gpu_mem_used_mb": "3926", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "74.14"}
2026-08-09 09:38:25 | INFO | train task=Ses01F epoch=2 batch=1204/2395 step=900 loss=1.0285 ce=0.7150 mse=0.6270 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2703146934509277, "reserved_gb": 3.263671875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "25", "gpu_mem_used_mb": "3650", "gpu_mem_total_mb": "12288", "gpu_temp_c": "43", "gpu_power_w": "60.92"}
2026-08-09 09:38:48 | INFO | train task=Ses01F epoch=2 batch=1304/2395 step=925 loss=1.7140 ce=1.2871 mse=0.8538 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.272274971008301, "reserved_gb": 3.203125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "30", "gpu_mem_used_mb": "3588", "gpu_mem_total_mb": "12288", "gpu_temp_c": "44", "gpu_power_w": "52.91"}
2026-08-09 09:39:08 | INFO | train task=Ses01F epoch=2 batch=1404/2395 step=950 loss=1.7340 ce=1.5759 mse=0.3162 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.270542621612549, "reserved_gb": 2.8359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "35", "gpu_mem_used_mb": "3212", "gpu_mem_total_mb": "12288", "gpu_temp_c": "43", "gpu_power_w": "46.85"}
2026-08-09 09:39:27 | INFO | train task=Ses01F epoch=2 batch=1504/2395 step=975 loss=1.7537 ce=1.3863 mse=0.7347 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2693538665771484, "reserved_gb": 2.822265625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "29", "gpu_mem_used_mb": "3198", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "72.04"}
2026-08-09 09:39:49 | INFO | train task=Ses01F epoch=2 batch=1604/2395 step=1000 loss=1.7663 ce=1.2920 mse=0.9486 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.269625186920166, "reserved_gb": 2.9375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "16", "gpu_mem_used_mb": "3316", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "66.89"}
2026-08-09 09:40:12 | INFO | train task=Ses01F epoch=2 batch=1704/2395 step=1025 loss=1.0830 ce=0.8909 mse=0.3841 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2692575454711914, "reserved_gb": 3.185546875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "32", "gpu_mem_used_mb": "3570", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "66.10"}
2026-08-09 09:40:31 | INFO | train task=Ses01F epoch=2 batch=1804/2395 step=1050 loss=1.8187 ce=1.4091 mse=0.8192 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2699317932128906, "reserved_gb": 3.09375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "25", "gpu_mem_used_mb": "3476", "gpu_mem_total_mb": "12288", "gpu_temp_c": "44", "gpu_power_w": "61.56"}
2026-08-09 09:40:53 | INFO | train task=Ses01F epoch=2 batch=1904/2395 step=1075 loss=0.5297 ce=0.4560 mse=0.1475 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.270113468170166, "reserved_gb": 2.837890625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "25", "gpu_mem_used_mb": "3214", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "67.39"}
2026-08-09 09:41:15 | INFO | train task=Ses01F epoch=2 batch=2004/2395 step=1100 loss=1.6156 ce=1.2368 mse=0.7575 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2695112228393555, "reserved_gb": 2.8828125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "16", "gpu_mem_used_mb": "3260", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "67.28"}
2026-08-09 09:41:39 | INFO | train task=Ses01F epoch=2 batch=2104/2395 step=1125 loss=2.6890 ce=2.2959 mse=0.7862 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.270352840423584, "reserved_gb": 2.826171875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "61", "gpu_mem_used_mb": "3202", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "70.47"}
2026-08-09 09:42:00 | INFO | train task=Ses01F epoch=2 batch=2204/2395 step=1150 loss=0.4238 ce=0.2950 mse=0.2577 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2699546813964844, "reserved_gb": 2.83984375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "37", "gpu_mem_used_mb": "3216", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "64.72"}
2026-08-09 09:42:22 | INFO | train task=Ses01F epoch=2 batch=2304/2395 step=1175 loss=1.7470 ce=1.2800 mse=0.9340 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2692809104919434, "reserved_gb": 3.091796875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "35", "gpu_mem_used_mb": "3474", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "66.25"}

predict:   0%|          | 0/313 [00:00<?, ?it/s]

2026-08-09 09:43:02 | INFO | Epoch 02 task=Ses01F train_loss=1.5193 val_macro_f1=0.3941 val_mae=0.5315 epoch_seconds=529.2

epoch 3:   0%|          | 0/2395 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 09:43:08 | INFO | train task=Ses01F epoch=3 batch=8/2395 step=1200 loss=1.2924 ce=1.2219 mse=0.1411 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.269338607788086, "reserved_gb": 5.005859375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "13", "gpu_mem_used_mb": "5434", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "64.56"}
2026-08-09 09:43:31 | INFO | train task=Ses01F epoch=3 batch=108/2395 step=1225 loss=0.3840 ce=0.3507 mse=0.0666 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.270486354827881, "reserved_gb": 3.037109375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "39", "gpu_mem_used_mb": "3418", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "79.00"}
2026-08-09 09:43:51 | INFO | train task=Ses01F epoch=3 batch=208/2395 step=1250 loss=1.1783 ce=0.8801 mse=0.5964 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.271329402923584, "reserved_gb": 2.857421875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "25", "gpu_mem_used_mb": "3234", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "57.98"}
2026-08-09 09:44:09 | INFO | train task=Ses01F epoch=3 batch=308/2395 step=1275 loss=2.8124 ce=2.6174 mse=0.3901 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2693605422973633, "reserved_gb": 2.86328125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "34", "gpu_mem_used_mb": "3240", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "75.51"}
2026-08-09 09:44:28 | INFO | train task=Ses01F epoch=3 batch=408/2395 step=1300 loss=2.3613 ce=2.2805 mse=0.1616 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2694625854492188, "reserved_gb": 3.744140625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "4142", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "53.88"}
2026-08-09 09:44:49 | INFO | train task=Ses01F epoch=3 batch=508/2395 step=1325 loss=0.3687 ce=0.3156 mse=0.1062 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1437788009643555, "reserved_gb": 2.0390625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "2396", "gpu_mem_total_mb": "12288", "gpu_temp_c": "55", "gpu_power_w": "67.00"}
2026-08-09 09:45:09 | INFO | train task=Ses01F epoch=3 batch=608/2395 step=1350 loss=1.0842 ce=1.0813 mse=0.0059 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1437358856201172, "reserved_gb": 2.033203125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "16", "gpu_mem_used_mb": "2390", "gpu_mem_total_mb": "12288", "gpu_temp_c": "56", "gpu_power_w": "79.60"}
2026-08-09 09:45:28 | INFO | train task=Ses01F epoch=3 batch=708/2395 step=1375 loss=1.3223 ce=1.2988 mse=0.0470 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.143113136291504, "reserved_gb": 2.03515625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "33", "gpu_mem_used_mb": "2392", "gpu_mem_total_mb": "12288", "gpu_temp_c": "55", "gpu_power_w": "62.03"}
2026-08-09 09:45:49 | INFO | train task=Ses01F epoch=3 batch=808/2395 step=1400 loss=1.4838 ce=1.3864 mse=0.1947 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1429963111877441, "reserved_gb": 2.04296875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "15", "gpu_mem_used_mb": "2400", "gpu_mem_total_mb": "12288", "gpu_temp_c": "53", "gpu_power_w": "70.26"}
2026-08-09 09:46:11 | INFO | train task=Ses01F epoch=3 batch=908/2395 step=1425 loss=2.7941 ce=2.7885 mse=0.0112 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1432976722717285, "reserved_gb": 2.0390625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "27", "gpu_mem_used_mb": "2396", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "69.76"}
2026-08-09 09:46:29 | INFO | train task=Ses01F epoch=3 batch=1008/2395 step=1450 loss=0.7130 ce=0.4096 mse=0.6069 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.14326810836792, "reserved_gb": 2.236328125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "19", "gpu_mem_used_mb": "2598", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "52.53"}
2026-08-09 09:46:49 | INFO | train task=Ses01F epoch=3 batch=1108/2395 step=1475 loss=1.1090 ce=0.8796 mse=0.4588 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1471481323242188, "reserved_gb": 2.302734375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "46", "gpu_mem_used_mb": "2666", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "61.43"}
2026-08-09 09:47:08 | INFO | train task=Ses01F epoch=3 batch=1208/2395 step=1500 loss=0.4534 ce=0.2139 mse=0.4791 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1443262100219727, "reserved_gb": 2.18359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "30", "gpu_mem_used_mb": "2544", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "73.00"}
2026-08-09 09:47:31 | INFO | train task=Ses01F epoch=3 batch=1308/2395 step=1525 loss=1.9213 ce=1.6971 mse=0.4484 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1535816192626953, "reserved_gb": 2.931640625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "3310", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "62.60"}
2026-08-09 09:47:50 | INFO | train task=Ses01F epoch=3 batch=1408/2395 step=1550 loss=1.5051 ce=1.3543 mse=0.3017 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.14439058303833, "reserved_gb": 2.322265625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "29", "gpu_mem_used_mb": "2686", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "68.32"}
2026-08-09 09:48:12 | INFO | train task=Ses01F epoch=3 batch=1508/2395 step=1575 loss=1.0681 ce=0.9263 mse=0.2838 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1437606811523438, "reserved_gb": 2.19140625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "38", "gpu_mem_used_mb": "2552", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "73.99"}
2026-08-09 09:48:32 | INFO | train task=Ses01F epoch=3 batch=1608/2395 step=1600 loss=2.3837 ce=1.6649 mse=1.4375 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1443347930908203, "reserved_gb": 2.103515625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "24", "gpu_mem_used_mb": "2462", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "65.93"}
2026-08-09 09:48:56 | INFO | train task=Ses01F epoch=3 batch=1708/2395 step=1625 loss=1.6907 ce=1.3057 mse=0.7700 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1431422233581543, "reserved_gb": 2.111328125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "29", "gpu_mem_used_mb": "2470", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "82.99"}
2026-08-09 09:49:16 | INFO | train task=Ses01F epoch=3 batch=1808/2395 step=1650 loss=1.4598 ce=0.9975 mse=0.9247 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1431312561035156, "reserved_gb": 2.048828125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "14", "gpu_mem_used_mb": "2406", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "67.95"}
2026-08-09 09:49:36 | INFO | train task=Ses01F epoch=3 batch=1908/2395 step=1675 loss=1.0370 ce=1.0217 mse=0.0306 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1432466506958008, "reserved_gb": 2.298828125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "2662", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "68.29"}
2026-08-09 09:49:55 | INFO | train task=Ses01F epoch=3 batch=2008/2395 step=1700 loss=0.8297 ce=0.6724 mse=0.3145 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1433634757995605, "reserved_gb": 2.271484375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "2634", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "63.39"}
2026-08-09 09:50:18 | INFO | train task=Ses01F epoch=3 batch=2108/2395 step=1725 loss=1.1065 ce=0.6925 mse=0.8280 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1444640159606934, "reserved_gb": 2.1171875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "23", "gpu_mem_used_mb": "2476", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "74.57"}
2026-08-09 09:50:38 | INFO | train task=Ses01F epoch=3 batch=2208/2395 step=1750 loss=1.4261 ce=1.1949 mse=0.4625 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1433238983154297, "reserved_gb": 2.041015625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "24", "gpu_mem_used_mb": "2398", "gpu_mem_total_mb": "12288", "gpu_temp_c": "43", "gpu_power_w": "59.01"}
2026-08-09 09:51:00 | INFO | train task=Ses01F epoch=3 batch=2308/2395 step=1775 loss=0.9448 ce=0.3971 mse=1.0954 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1477060317993164, "reserved_gb": 2.03515625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "73", "gpu_mem_used_mb": "2392", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "67.19"}

predict:   0%|          | 0/313 [00:00<?, ?it/s]

2026-08-09 09:51:41 | INFO | Epoch 03 task=Ses01F train_loss=1.2843 val_macro_f1=0.3476 val_mae=0.5745 epoch_seconds=514.4

epoch 4:   0%|          | 0/2395 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 09:51:46 | INFO | train task=Ses01F epoch=4 batch=12/2395 step=1800 loss=1.7862 ce=1.1164 mse=1.3397 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.143397331237793, "reserved_gb": 2.3515625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "2716", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "68.73"}
2026-08-09 09:52:09 | INFO | train task=Ses01F epoch=4 batch=112/2395 step=1825 loss=0.9332 ce=0.6873 mse=0.4919 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1439380645751953, "reserved_gb": 2.033203125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "35", "gpu_mem_used_mb": "2390", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "76.08"}
2026-08-09 09:52:29 | INFO | train task=Ses01F epoch=4 batch=212/2395 step=1850 loss=3.6466 ce=2.7679 mse=1.7575 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1437668800354004, "reserved_gb": 2.349609375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "33", "gpu_mem_used_mb": "2714", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "68.53"}
2026-08-09 09:52:48 | INFO | train task=Ses01F epoch=4 batch=312/2395 step=1875 loss=0.8583 ce=0.7294 mse=0.2578 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1440973281860352, "reserved_gb": 2.033203125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "67", "gpu_mem_used_mb": "2390", "gpu_mem_total_mb": "12288", "gpu_temp_c": "53", "gpu_power_w": "70.34"}
2026-08-09 09:53:08 | INFO | train task=Ses01F epoch=4 batch=412/2395 step=1900 loss=1.5127 ce=0.7408 mse=1.5439 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1434669494628906, "reserved_gb": 2.171875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "2532", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "49.83"}
2026-08-09 09:53:29 | INFO | train task=Ses01F epoch=4 batch=512/2395 step=1925 loss=2.7011 ce=1.9348 mse=1.5325 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1431279182434082, "reserved_gb": 2.67578125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "18", "gpu_mem_used_mb": "3048", "gpu_mem_total_mb": "12288", "gpu_temp_c": "55", "gpu_power_w": "69.02"}
2026-08-09 09:53:48 | INFO | train task=Ses01F epoch=4 batch=612/2395 step=1950 loss=2.2168 ce=1.9165 mse=0.6006 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1434898376464844, "reserved_gb": 2.04296875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "18", "gpu_mem_used_mb": "2400", "gpu_mem_total_mb": "12288", "gpu_temp_c": "57", "gpu_power_w": "73.43"}
2026-08-09 09:54:08 | INFO | train task=Ses01F epoch=4 batch=712/2395 step=1975 loss=0.4960 ce=0.3150 mse=0.3621 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1438226699829102, "reserved_gb": 2.314453125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "30", "gpu_mem_used_mb": "2678", "gpu_mem_total_mb": "12288", "gpu_temp_c": "53", "gpu_power_w": "55.15"}
2026-08-09 09:54:28 | INFO | train task=Ses01F epoch=4 batch=812/2395 step=2000 loss=0.2739 ce=0.0923 mse=0.3633 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1601572036743164, "reserved_gb": 3.404296875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "57", "gpu_mem_used_mb": "3794", "gpu_mem_total_mb": "12288", "gpu_temp_c": "57", "gpu_power_w": "75.79"}
2026-08-09 09:54:51 | INFO | train task=Ses01F epoch=4 batch=912/2395 step=2025 loss=0.3436 ce=0.3249 mse=0.0373 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1452770233154297, "reserved_gb": 2.275390625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "25", "gpu_mem_used_mb": "2638", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "64.37"}
2026-08-09 09:55:10 | INFO | train task=Ses01F epoch=4 batch=1012/2395 step=2050 loss=4.6596 ce=4.3356 mse=0.6481 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1435785293579102, "reserved_gb": 2.048828125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "25", "gpu_mem_used_mb": "2406", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "81.25"}
2026-08-09 09:55:29 | INFO | train task=Ses01F epoch=4 batch=1112/2395 step=2075 loss=1.5408 ce=1.1577 mse=0.7662 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1440849304199219, "reserved_gb": 2.595703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "25", "gpu_mem_used_mb": "2966", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "49.42"}
2026-08-09 09:55:49 | INFO | train task=Ses01F epoch=4 batch=1212/2395 step=2100 loss=0.2598 ce=0.1628 mse=0.1940 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1502690315246582, "reserved_gb": 2.568359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "37", "gpu_mem_used_mb": "2938", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "70.68"}
2026-08-09 09:56:11 | INFO | train task=Ses01F epoch=4 batch=1312/2395 step=2125 loss=0.1928 ce=0.1792 mse=0.0273 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1443896293640137, "reserved_gb": 2.185546875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "27", "gpu_mem_used_mb": "2546", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "62.77"}
2026-08-09 09:56:32 | INFO | train task=Ses01F epoch=4 batch=1412/2395 step=2150 loss=0.7055 ce=0.6746 mse=0.0618 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1434717178344727, "reserved_gb": 2.111328125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "2470", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "70.52"}
2026-08-09 09:56:52 | INFO | train task=Ses01F epoch=4 batch=1512/2395 step=2175 loss=0.5911 ce=0.5861 mse=0.0100 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.144683837890625, "reserved_gb": 2.125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "31", "gpu_mem_used_mb": "2484", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "53.46"}
2026-08-09 09:57:13 | INFO | train task=Ses01F epoch=4 batch=1612/2395 step=2200 loss=1.9489 ce=1.7827 mse=0.3325 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1434168815612793, "reserved_gb": 2.04296875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "2400", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "71.30"}
2026-08-09 09:57:36 | INFO | train task=Ses01F epoch=4 batch=1712/2395 step=2225 loss=0.5024 ce=0.4515 mse=0.1017 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1442484855651855, "reserved_gb": 2.033203125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "11", "gpu_mem_used_mb": "2390", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "66.85"}
2026-08-09 09:57:58 | INFO | train task=Ses01F epoch=4 batch=1812/2395 step=2250 loss=2.6635 ce=2.5101 mse=0.3068 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.144120693206787, "reserved_gb": 2.12109375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "42", "gpu_mem_used_mb": "2480", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "73.68"}
2026-08-09 09:58:18 | INFO | train task=Ses01F epoch=4 batch=1912/2395 step=2275 loss=0.6981 ce=0.5929 mse=0.2104 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1433520317077637, "reserved_gb": 2.0390625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "45", "gpu_mem_used_mb": "2396", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "62.06"}
2026-08-09 09:58:39 | INFO | train task=Ses01F epoch=4 batch=2012/2395 step=2300 loss=0.7437 ce=0.6961 mse=0.0952 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1433439254760742, "reserved_gb": 2.04296875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "38", "gpu_mem_used_mb": "2400", "gpu_mem_total_mb": "12288", "gpu_temp_c": "44", "gpu_power_w": "41.19"}
2026-08-09 09:59:03 | INFO | train task=Ses01F epoch=4 batch=2112/2395 step=2325 loss=1.6147 ce=1.5464 mse=0.1366 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.143937110900879, "reserved_gb": 2.033203125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "2390", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "69.78"}
2026-08-09 09:59:26 | INFO | train task=Ses01F epoch=4 batch=2212/2395 step=2350 loss=1.8700 ce=1.6994 mse=0.3411 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1432147026062012, "reserved_gb": 2.033203125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "39", "gpu_mem_used_mb": "2390", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "100.49"}
2026-08-09 09:59:46 | INFO | train task=Ses01F epoch=4 batch=2312/2395 step=2375 loss=0.3653 ce=0.1847 mse=0.3613 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1432576179504395, "reserved_gb": 2.044921875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "23", "gpu_mem_used_mb": "2402", "gpu_mem_total_mb": "12288", "gpu_temp_c": "44", "gpu_power_w": "49.48"}

predict:   0%|          | 0/313 [00:00<?, ?it/s]

2026-08-09 10:00:25 | INFO | Epoch 04 task=Ses01F train_loss=1.1093 val_macro_f1=0.3963 val_mae=0.5062 epoch_seconds=521.0

epoch 5:   0%|          | 0/2395 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 10:00:33 | INFO | train task=Ses01F epoch=5 batch=16/2395 step=2400 loss=1.1620 ce=0.9951 mse=0.3336 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1434626579284668, "reserved_gb": 2.287109375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "47", "gpu_mem_used_mb": "2652", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "84.09"}
2026-08-09 10:00:57 | INFO | train task=Ses01F epoch=5 batch=116/2395 step=2425 loss=0.1040 ce=0.0987 mse=0.0107 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.143531322479248, "reserved_gb": 2.7265625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "37", "gpu_mem_used_mb": "3102", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "66.30"}
2026-08-09 10:01:17 | INFO | train task=Ses01F epoch=5 batch=216/2395 step=2450 loss=0.5422 ce=0.3594 mse=0.3656 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1431312561035156, "reserved_gb": 2.03515625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "19", "gpu_mem_used_mb": "2414", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "65.86"}
2026-08-09 10:01:36 | INFO | train task=Ses01F epoch=5 batch=316/2395 step=2475 loss=0.5462 ce=0.3082 mse=0.4759 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1451411247253418, "reserved_gb": 2.359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "2746", "gpu_mem_total_mb": "12288", "gpu_temp_c": "53", "gpu_power_w": "82.16"}
2026-08-09 10:01:55 | INFO | train task=Ses01F epoch=5 batch=416/2395 step=2500 loss=0.6042 ce=0.2466 mse=0.7152 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.143458366394043, "reserved_gb": 2.40234375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "37", "gpu_mem_used_mb": "2790", "gpu_mem_total_mb": "12288", "gpu_temp_c": "55", "gpu_power_w": "70.70"}
2026-08-09 10:02:18 | INFO | train task=Ses01F epoch=5 batch=516/2395 step=2525 loss=0.7154 ce=0.5923 mse=0.2462 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1459369659423828, "reserved_gb": 2.27734375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "40", "gpu_mem_used_mb": "2662", "gpu_mem_total_mb": "12288", "gpu_temp_c": "55", "gpu_power_w": "48.15"}
2026-08-09 10:02:38 | INFO | train task=Ses01F epoch=5 batch=616/2395 step=2550 loss=0.9039 ce=0.8251 mse=0.1576 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1477060317993164, "reserved_gb": 2.298828125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "44", "gpu_mem_used_mb": "2684", "gpu_mem_total_mb": "12288", "gpu_temp_c": "58", "gpu_power_w": "66.19"}
2026-08-09 10:02:56 | INFO | train task=Ses01F epoch=5 batch=716/2395 step=2575 loss=0.4713 ce=0.3192 mse=0.3043 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.143484115600586, "reserved_gb": 2.048828125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "26", "gpu_mem_used_mb": "2428", "gpu_mem_total_mb": "12288", "gpu_temp_c": "54", "gpu_power_w": "75.78"}
2026-08-09 10:03:16 | INFO | train task=Ses01F epoch=5 batch=816/2395 step=2600 loss=0.9352 ce=0.7357 mse=0.3990 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1431188583374023, "reserved_gb": 2.51953125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "50", "gpu_mem_used_mb": "2910", "gpu_mem_total_mb": "12288", "gpu_temp_c": "54", "gpu_power_w": "71.47"}
2026-08-09 10:03:38 | INFO | train task=Ses01F epoch=5 batch=916/2395 step=2625 loss=0.1789 ce=0.1601 mse=0.0377 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1466188430786133, "reserved_gb": 2.51953125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "43", "gpu_mem_used_mb": "2910", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "54.33"}
2026-08-09 10:03:57 | INFO | train task=Ses01F epoch=5 batch=1016/2395 step=2650 loss=1.5350 ce=1.2903 mse=0.4893 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1445412635803223, "reserved_gb": 2.515625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "39", "gpu_mem_used_mb": "2906", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "62.25"}
2026-08-09 10:04:18 | INFO | train task=Ses01F epoch=5 batch=1116/2395 step=2675 loss=1.0970 ce=1.0851 mse=0.0239 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.144620418548584, "reserved_gb": 2.111328125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "34", "gpu_mem_used_mb": "2492", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "79.65"}
2026-08-09 10:04:38 | INFO | train task=Ses01F epoch=5 batch=1216/2395 step=2700 loss=0.2159 ce=0.0692 mse=0.2934 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1433229446411133, "reserved_gb": 2.0390625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "27", "gpu_mem_used_mb": "2418", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "47.05"}
2026-08-09 10:05:00 | INFO | train task=Ses01F epoch=5 batch=1316/2395 step=2725 loss=2.7128 ce=2.6561 mse=0.1135 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1493768692016602, "reserved_gb": 2.03515625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "64", "gpu_mem_used_mb": "2414", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "86.10"}
2026-08-09 10:05:21 | INFO | train task=Ses01F epoch=5 batch=1416/2395 step=2750 loss=0.7881 ce=0.4579 mse=0.6603 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1484384536743164, "reserved_gb": 2.033203125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "51", "gpu_mem_used_mb": "2412", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "78.56"}
2026-08-09 10:05:41 | INFO | train task=Ses01F epoch=5 batch=1516/2395 step=2775 loss=0.7924 ce=0.7596 mse=0.0656 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.145033359527588, "reserved_gb": 2.228515625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "16", "gpu_mem_used_mb": "2612", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "72.91"}
2026-08-09 10:06:01 | INFO | train task=Ses01F epoch=5 batch=1616/2395 step=2800 loss=0.2817 ce=0.2689 mse=0.0255 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1451678276062012, "reserved_gb": 2.298828125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "2684", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "71.01"}
2026-08-09 10:06:25 | INFO | train task=Ses01F epoch=5 batch=1716/2395 step=2825 loss=1.0934 ce=0.4188 mse=1.3492 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1433343887329102, "reserved_gb": 2.041015625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "44", "gpu_mem_used_mb": "2420", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "67.54"}
2026-08-09 10:06:45 | INFO | train task=Ses01F epoch=5 batch=1816/2395 step=2850 loss=1.3635 ce=1.2725 mse=0.1821 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1433768272399902, "reserved_gb": 2.041015625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "25", "gpu_mem_used_mb": "2420", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "66.63"}
2026-08-09 10:07:05 | INFO | train task=Ses01F epoch=5 batch=1916/2395 step=2875 loss=2.5792 ce=1.1596 mse=2.8391 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.143115520477295, "reserved_gb": 2.033203125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "16", "gpu_mem_used_mb": "2412", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "66.61"}
2026-08-09 10:07:27 | INFO | train task=Ses01F epoch=5 batch=2016/2395 step=2900 loss=1.3512 ce=1.1662 mse=0.3700 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1444449424743652, "reserved_gb": 2.11328125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "15", "gpu_mem_used_mb": "2494", "gpu_mem_total_mb": "12288", "gpu_temp_c": "44", "gpu_power_w": "50.29"}
2026-08-09 10:07:49 | INFO | train task=Ses01F epoch=5 batch=2116/2395 step=2925 loss=0.9521 ce=0.8215 mse=0.2612 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1442580223083496, "reserved_gb": 2.23046875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "23", "gpu_mem_used_mb": "2614", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "66.73"}
2026-08-09 10:08:11 | INFO | train task=Ses01F epoch=5 batch=2216/2395 step=2950 loss=3.6122 ce=3.5166 mse=0.1911 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1460223197937012, "reserved_gb": 2.51171875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "27", "gpu_mem_used_mb": "2902", "gpu_mem_total_mb": "12288", "gpu_temp_c": "43", "gpu_power_w": "50.55"}
2026-08-09 10:08:32 | INFO | train task=Ses01F epoch=5 batch=2316/2395 step=2975 loss=0.8192 ce=0.8170 mse=0.0044 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1470422744750977, "reserved_gb": 2.298828125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "63", "gpu_mem_used_mb": "2684", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "82.18"}

predict:   0%|          | 0/313 [00:00<?, ?it/s]

2026-08-09 10:09:11 | INFO | Epoch 05 task=Ses01F train_loss=0.9852 val_macro_f1=0.3895 val_mae=0.5767 epoch_seconds=521.1

epoch 6:   0%|          | 0/2395 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 10:09:18 | INFO | train task=Ses01F epoch=6 batch=20/2395 step=3000 loss=0.9138 ce=0.8106 mse=0.2063 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.145129680633545, "reserved_gb": 2.259765625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "55", "gpu_mem_used_mb": "2644", "gpu_mem_total_mb": "12288", "gpu_temp_c": "44", "gpu_power_w": "59.72"}
2026-08-09 10:09:41 | INFO | train task=Ses01F epoch=6 batch=120/2395 step=3025 loss=1.8093 ce=1.4901 mse=0.6384 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1442036628723145, "reserved_gb": 2.033203125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "70", "gpu_mem_used_mb": "2412", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "44.94"}
2026-08-09 10:09:59 | INFO | train task=Ses01F epoch=6 batch=220/2395 step=3050 loss=0.4761 ce=0.3322 mse=0.2878 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1480417251586914, "reserved_gb": 2.431640625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "2820", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "67.68"}
2026-08-09 10:10:17 | INFO | train task=Ses01F epoch=6 batch=320/2395 step=3075 loss=3.0810 ce=2.5015 mse=1.1590 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1433796882629395, "reserved_gb": 2.291015625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "18", "gpu_mem_used_mb": "2676", "gpu_mem_total_mb": "12288", "gpu_temp_c": "43", "gpu_power_w": "53.27"}
2026-08-09 10:10:35 | INFO | train task=Ses01F epoch=6 batch=420/2395 step=3100 loss=0.6124 ce=0.2765 mse=0.6718 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1433334350585938, "reserved_gb": 2.259765625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "28", "gpu_mem_used_mb": "2644", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "70.86"}
2026-08-09 10:10:58 | INFO | train task=Ses01F epoch=6 batch=520/2395 step=3125 loss=0.4277 ce=0.2977 mse=0.2600 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1435389518737793, "reserved_gb": 2.046875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "2426", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "63.83"}
2026-08-09 10:11:17 | INFO | train task=Ses01F epoch=6 batch=620/2395 step=3150 loss=1.5024 ce=1.4227 mse=0.1595 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1439309120178223, "reserved_gb": 2.033203125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "18", "gpu_mem_used_mb": "2412", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "67.99"}
2026-08-09 10:11:36 | INFO | train task=Ses01F epoch=6 batch=720/2395 step=3175 loss=1.1321 ce=1.0290 mse=0.2062 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1433463096618652, "reserved_gb": 2.044921875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "2424", "gpu_mem_total_mb": "12288", "gpu_temp_c": "43", "gpu_power_w": "62.43"}
2026-08-09 10:11:56 | INFO | train task=Ses01F epoch=6 batch=820/2395 step=3200 loss=0.7079 ce=0.1688 mse=1.0783 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1470880508422852, "reserved_gb": 2.3125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "2698", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "64.58"}
2026-08-09 10:12:18 | INFO | train task=Ses01F epoch=6 batch=920/2395 step=3225 loss=0.4325 ce=0.2755 mse=0.3141 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1443538665771484, "reserved_gb": 2.373046875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "29", "gpu_mem_used_mb": "2760", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "58.78"}
2026-08-09 10:12:37 | INFO | train task=Ses01F epoch=6 batch=1020/2395 step=3250 loss=1.6568 ce=1.4839 mse=0.3460 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1450543403625488, "reserved_gb": 2.033203125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "75", "gpu_mem_used_mb": "2412", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "81.39"}
2026-08-09 10:12:58 | INFO | train task=Ses01F epoch=6 batch=1120/2395 step=3275 loss=1.4286 ce=1.2006 mse=0.4560 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1447124481201172, "reserved_gb": 2.125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "30", "gpu_mem_used_mb": "2506", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "71.68"}
2026-08-09 10:13:16 | INFO | train task=Ses01F epoch=6 batch=1220/2395 step=3300 loss=0.2949 ce=0.2658 mse=0.0583 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1439876556396484, "reserved_gb": 2.515625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "29", "gpu_mem_used_mb": "2906", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "70.07"}
2026-08-09 10:13:38 | INFO | train task=Ses01F epoch=6 batch=1320/2395 step=3325 loss=0.7051 ce=0.4762 mse=0.4577 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1434764862060547, "reserved_gb": 2.048828125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "16", "gpu_mem_used_mb": "2428", "gpu_mem_total_mb": "12288", "gpu_temp_c": "44", "gpu_power_w": "67.49"}
2026-08-09 10:13:58 | INFO | train task=Ses01F epoch=6 batch=1420/2395 step=3350 loss=0.6290 ce=0.3342 mse=0.5896 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1436614990234375, "reserved_gb": 2.033203125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "31", "gpu_mem_used_mb": "2412", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "51.59"}
2026-08-09 10:14:18 | INFO | train task=Ses01F epoch=6 batch=1520/2395 step=3375 loss=0.7275 ce=0.7003 mse=0.0544 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.143507480621338, "reserved_gb": 2.044921875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "35", "gpu_mem_used_mb": "2424", "gpu_mem_total_mb": "12288", "gpu_temp_c": "44", "gpu_power_w": "62.18"}
2026-08-09 10:14:38 | INFO | train task=Ses01F epoch=6 batch=1620/2395 step=3400 loss=0.1136 ce=0.0743 mse=0.0786 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1448616981506348, "reserved_gb": 2.119140625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "52", "gpu_mem_used_mb": "2500", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "61.64"}
2026-08-09 10:15:01 | INFO | train task=Ses01F epoch=6 batch=1720/2395 step=3425 loss=0.2806 ce=0.2321 mse=0.0971 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1474132537841797, "reserved_gb": 2.462890625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "34", "gpu_mem_used_mb": "2852", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "68.66"}
2026-08-09 10:15:23 | INFO | train task=Ses01F epoch=6 batch=1820/2395 step=3450 loss=0.3966 ce=0.1326 mse=0.5280 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1459269523620605, "reserved_gb": 2.26171875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "61", "gpu_mem_used_mb": "2646", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "74.75"}
2026-08-09 10:15:44 | INFO | train task=Ses01F epoch=6 batch=1920/2395 step=3475 loss=0.0644 ce=0.0237 mse=0.0814 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.143280029296875, "reserved_gb": 2.044921875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "2424", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "64.26"}
2026-08-09 10:16:04 | INFO | train task=Ses01F epoch=6 batch=2020/2395 step=3500 loss=0.1527 ce=0.0405 mse=0.2245 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.14373779296875, "reserved_gb": 2.041015625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "35", "gpu_mem_used_mb": "2420", "gpu_mem_total_mb": "12288", "gpu_temp_c": "44", "gpu_power_w": "54.42"}
2026-08-09 10:16:28 | INFO | train task=Ses01F epoch=6 batch=2120/2395 step=3525 loss=0.7531 ce=0.3999 mse=0.7065 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1451072692871094, "reserved_gb": 2.31640625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "37", "gpu_mem_used_mb": "2702", "gpu_mem_total_mb": "12288", "gpu_temp_c": "43", "gpu_power_w": "45.23"}
2026-08-09 10:16:50 | INFO | train task=Ses01F epoch=6 batch=2220/2395 step=3550 loss=0.7014 ce=0.6995 mse=0.0038 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1437606811523438, "reserved_gb": 2.03515625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "25", "gpu_mem_used_mb": "2414", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "53.25"}
2026-08-09 10:17:11 | INFO | train task=Ses01F epoch=6 batch=2320/2395 step=3575 loss=0.3639 ce=0.0383 mse=0.6512 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1444449424743652, "reserved_gb": 2.10546875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "23", "gpu_mem_used_mb": "2486", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "76.43"}

predict:   0%|          | 0/313 [00:00<?, ?it/s]

2026-08-09 10:17:47 | INFO | Epoch 06 task=Ses01F train_loss=0.8677 val_macro_f1=0.4106 val_mae=0.5290 epoch_seconds=512.9

epoch 7:   0%|          | 0/2395 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 10:17:56 | INFO | train task=Ses01F epoch=7 batch=24/2395 step=3600 loss=0.1711 ce=0.0712 mse=0.1996 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.144700050354004, "reserved_gb": 2.115234375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "32", "gpu_mem_used_mb": "2496", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "71.41"}
2026-08-09 10:18:18 | INFO | train task=Ses01F epoch=7 batch=124/2395 step=3625 loss=2.4629 ce=2.3034 mse=0.3190 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.144333839416504, "reserved_gb": 2.294921875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "55", "gpu_mem_used_mb": "2680", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "76.57"}
2026-08-09 10:18:39 | INFO | train task=Ses01F epoch=7 batch=224/2395 step=3650 loss=1.0230 ce=0.1325 mse=1.7810 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1435370445251465, "reserved_gb": 2.40625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "37", "gpu_mem_used_mb": "2824", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "70.96"}
2026-08-09 10:18:58 | INFO | train task=Ses01F epoch=7 batch=324/2395 step=3675 loss=0.7807 ce=0.6574 mse=0.2467 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1441168785095215, "reserved_gb": 2.3359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "2752", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "69.69"}
2026-08-09 10:19:17 | INFO | train task=Ses01F epoch=7 batch=424/2395 step=3700 loss=0.9478 ce=0.6927 mse=0.5101 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.142989158630371, "reserved_gb": 2.41015625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "30", "gpu_mem_used_mb": "2828", "gpu_mem_total_mb": "12288", "gpu_temp_c": "55", "gpu_power_w": "80.71"}
2026-08-09 10:19:39 | INFO | train task=Ses01F epoch=7 batch=524/2395 step=3725 loss=0.4616 ce=0.3154 mse=0.2924 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1431927680969238, "reserved_gb": 2.404296875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "29", "gpu_mem_used_mb": "2822", "gpu_mem_total_mb": "12288", "gpu_temp_c": "55", "gpu_power_w": "71.47"}
2026-08-09 10:19:57 | INFO | train task=Ses01F epoch=7 batch=624/2395 step=3750 loss=0.7276 ce=0.5001 mse=0.4550 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1441245079040527, "reserved_gb": 2.396484375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "28", "gpu_mem_used_mb": "2814", "gpu_mem_total_mb": "12288", "gpu_temp_c": "57", "gpu_power_w": "79.93"}
2026-08-09 10:20:16 | INFO | train task=Ses01F epoch=7 batch=724/2395 step=3775 loss=1.7124 ce=1.2833 mse=0.8581 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1435370445251465, "reserved_gb": 2.04296875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "2452", "gpu_mem_total_mb": "12288", "gpu_temp_c": "57", "gpu_power_w": "57.56"}
2026-08-09 10:20:36 | INFO | train task=Ses01F epoch=7 batch=824/2395 step=3800 loss=0.4121 ce=0.3155 mse=0.1933 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.143296718597412, "reserved_gb": 2.03515625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "36", "gpu_mem_used_mb": "2444", "gpu_mem_total_mb": "12288", "gpu_temp_c": "58", "gpu_power_w": "78.12"}
2026-08-09 10:20:57 | INFO | train task=Ses01F epoch=7 batch=924/2395 step=3825 loss=0.5376 ce=0.4428 mse=0.1895 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1432170867919922, "reserved_gb": 2.328125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "27", "gpu_mem_used_mb": "2744", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "45.82"}
2026-08-09 10:21:17 | INFO | train task=Ses01F epoch=7 batch=1024/2395 step=3850 loss=0.8653 ce=0.8499 mse=0.0309 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.144948959350586, "reserved_gb": 2.314453125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "18", "gpu_mem_used_mb": "2730", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "65.92"}
2026-08-09 10:21:37 | INFO | train task=Ses01F epoch=7 batch=1124/2395 step=3875 loss=0.7370 ce=0.4680 mse=0.5380 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1438541412353516, "reserved_gb": 2.033203125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "19", "gpu_mem_used_mb": "2442", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "73.53"}
2026-08-09 10:21:56 | INFO | train task=Ses01F epoch=7 batch=1224/2395 step=3900 loss=0.0396 ce=0.0075 mse=0.0642 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1446704864501953, "reserved_gb": 2.033203125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "52", "gpu_mem_used_mb": "2442", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "65.46"}
2026-08-09 10:22:19 | INFO | train task=Ses01F epoch=7 batch=1324/2395 step=3925 loss=1.0898 ce=1.0164 mse=0.1469 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1441726684570312, "reserved_gb": 2.626953125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "3050", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "63.82"}
2026-08-09 10:22:39 | INFO | train task=Ses01F epoch=7 batch=1424/2395 step=3950 loss=0.0643 ce=0.0599 mse=0.0086 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1456384658813477, "reserved_gb": 2.240234375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "61", "gpu_mem_used_mb": "2654", "gpu_mem_total_mb": "12288", "gpu_temp_c": "54", "gpu_power_w": "98.06"}
2026-08-09 10:22:59 | INFO | train task=Ses01F epoch=7 batch=1524/2395 step=3975 loss=0.1872 ce=0.0637 mse=0.2472 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1440868377685547, "reserved_gb": 2.03515625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "47", "gpu_mem_used_mb": "2444", "gpu_mem_total_mb": "12288", "gpu_temp_c": "53", "gpu_power_w": "82.91"}
2026-08-09 10:23:20 | INFO | train task=Ses01F epoch=7 batch=1624/2395 step=4000 loss=0.2011 ce=0.0603 mse=0.2815 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1458401679992676, "reserved_gb": 2.140625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "37", "gpu_mem_used_mb": "2552", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "69.94"}
2026-08-09 10:23:43 | INFO | train task=Ses01F epoch=7 batch=1724/2395 step=4025 loss=3.3504 ce=3.2395 mse=0.2218 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1439218521118164, "reserved_gb": 2.033203125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "19", "gpu_mem_used_mb": "2442", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "84.09"}
2026-08-09 10:24:05 | INFO | train task=Ses01F epoch=7 batch=1824/2395 step=4050 loss=0.0868 ce=0.0543 mse=0.0648 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1434812545776367, "reserved_gb": 2.044921875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "74", "gpu_mem_used_mb": "2454", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "72.56"}
2026-08-09 10:24:25 | INFO | train task=Ses01F epoch=7 batch=1924/2395 step=4075 loss=0.2617 ce=0.0393 mse=0.4448 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1484384536743164, "reserved_gb": 2.443359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "35", "gpu_mem_used_mb": "2862", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "66.27"}
2026-08-09 10:24:47 | INFO | train task=Ses01F epoch=7 batch=2024/2395 step=4100 loss=1.0582 ce=0.6191 mse=0.8780 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1430363655090332, "reserved_gb": 2.033203125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "29", "gpu_mem_used_mb": "2442", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "77.19"}
2026-08-09 10:25:10 | INFO | train task=Ses01F epoch=7 batch=2124/2395 step=4125 loss=0.3532 ce=0.2967 mse=0.1129 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1434149742126465, "reserved_gb": 2.5859375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "19", "gpu_mem_used_mb": "3008", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "73.25"}
2026-08-09 10:25:31 | INFO | train task=Ses01F epoch=7 batch=2224/2395 step=4150 loss=0.3128 ce=0.3127 mse=0.0002 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1442804336547852, "reserved_gb": 2.033203125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "16", "gpu_mem_used_mb": "2442", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "63.98"}
2026-08-09 10:25:52 | INFO | train task=Ses01F epoch=7 batch=2324/2395 step=4175 loss=0.8922 ce=0.6070 mse=0.5704 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1434803009033203, "reserved_gb": 2.04296875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "2452", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "62.79"}

predict:   0%|          | 0/313 [00:00<?, ?it/s]

2026-08-09 10:26:27 | INFO | Epoch 07 task=Ses01F train_loss=0.7741 val_macro_f1=0.4267 val_mae=0.5054 epoch_seconds=515.8

epoch 8:   0%|          | 0/2395 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 10:26:38 | INFO | train task=Ses01F epoch=8 batch=28/2395 step=4200 loss=0.1410 ce=0.1189 mse=0.0441 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1466197967529297, "reserved_gb": 2.384765625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "2802", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "68.14"}
2026-08-09 10:27:02 | INFO | train task=Ses01F epoch=8 batch=128/2395 step=4225 loss=1.3934 ce=1.2396 mse=0.3078 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1443414688110352, "reserved_gb": 2.388671875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "37", "gpu_mem_used_mb": "2806", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "70.25"}
2026-08-09 10:27:21 | INFO | train task=Ses01F epoch=8 batch=228/2395 step=4250 loss=0.3567 ce=0.2382 mse=0.2369 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.145268440246582, "reserved_gb": 2.275390625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "29", "gpu_mem_used_mb": "2690", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "63.34"}
2026-08-09 10:27:41 | INFO | train task=Ses01F epoch=8 batch=328/2395 step=4275 loss=0.6571 ce=0.1231 mse=1.0679 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1437668800354004, "reserved_gb": 2.033203125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "34", "gpu_mem_used_mb": "2442", "gpu_mem_total_mb": "12288", "gpu_temp_c": "55", "gpu_power_w": "72.93"}
2026-08-09 10:28:00 | INFO | train task=Ses01F epoch=8 batch=428/2395 step=4300 loss=0.2973 ce=0.2818 mse=0.0310 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.143686294555664, "reserved_gb": 2.431640625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "25", "gpu_mem_used_mb": "2850", "gpu_mem_total_mb": "12288", "gpu_temp_c": "54", "gpu_power_w": "60.18"}
2026-08-09 10:28:23 | INFO | train task=Ses01F epoch=8 batch=528/2395 step=4325 loss=0.0507 ce=0.0272 mse=0.0470 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1434617042541504, "reserved_gb": 2.375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "38", "gpu_mem_used_mb": "2792", "gpu_mem_total_mb": "12288", "gpu_temp_c": "58", "gpu_power_w": "73.00"}
2026-08-09 10:28:43 | INFO | train task=Ses01F epoch=8 batch=628/2395 step=4350 loss=0.1037 ce=0.0581 mse=0.0913 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1438121795654297, "reserved_gb": 2.328125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "2744", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "48.89"}
2026-08-09 10:29:02 | INFO | train task=Ses01F epoch=8 batch=728/2395 step=4375 loss=1.0944 ce=1.0139 mse=0.1609 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1445550918579102, "reserved_gb": 2.109375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "25", "gpu_mem_used_mb": "2520", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "73.45"}
2026-08-09 10:29:22 | INFO | train task=Ses01F epoch=8 batch=828/2395 step=4400 loss=0.6523 ce=0.3290 mse=0.6466 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.143204689025879, "reserved_gb": 2.1484375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "19", "gpu_mem_used_mb": "2560", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "82.54"}
2026-08-09 10:29:45 | INFO | train task=Ses01F epoch=8 batch=928/2395 step=4425 loss=1.7100 ce=1.6501 mse=0.1198 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1429963111877441, "reserved_gb": 2.033203125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "30", "gpu_mem_used_mb": "2442", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "75.55"}
2026-08-09 10:30:06 | INFO | train task=Ses01F epoch=8 batch=1028/2395 step=4450 loss=0.4633 ce=0.4135 mse=0.0997 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1435966491699219, "reserved_gb": 2.216796875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "34", "gpu_mem_used_mb": "2630", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "62.44"}
2026-08-09 10:30:24 | INFO | train task=Ses01F epoch=8 batch=1128/2395 step=4475 loss=0.9969 ce=0.8728 mse=0.2482 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1436529159545898, "reserved_gb": 2.123046875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "2534", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "65.93"}
2026-08-09 10:30:45 | INFO | train task=Ses01F epoch=8 batch=1228/2395 step=4500 loss=0.7329 ce=0.5536 mse=0.3587 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1431312561035156, "reserved_gb": 2.115234375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "37", "gpu_mem_used_mb": "2526", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "68.10"}
2026-08-09 10:31:09 | INFO | train task=Ses01F epoch=8 batch=1328/2395 step=4525 loss=0.9060 ce=0.8923 mse=0.0274 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1457910537719727, "reserved_gb": 2.271484375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "41", "gpu_mem_used_mb": "2686", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "61.82"}
2026-08-09 10:31:29 | INFO | train task=Ses01F epoch=8 batch=1428/2395 step=4550 loss=1.2156 ce=1.0266 mse=0.3780 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.142989158630371, "reserved_gb": 2.111328125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "23", "gpu_mem_used_mb": "2522", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "71.91"}
2026-08-09 10:31:49 | INFO | train task=Ses01F epoch=8 batch=1528/2395 step=4575 loss=0.2211 ce=0.1981 mse=0.0459 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.143298625946045, "reserved_gb": 2.03515625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "26", "gpu_mem_used_mb": "2444", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "67.77"}
2026-08-09 10:32:10 | INFO | train task=Ses01F epoch=8 batch=1628/2395 step=4600 loss=0.1787 ce=0.0169 mse=0.3237 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1484384536743164, "reserved_gb": 2.033203125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "43", "gpu_mem_used_mb": "2442", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "82.91"}
2026-08-09 10:32:36 | INFO | train task=Ses01F epoch=8 batch=1728/2395 step=4625 loss=0.7322 ce=0.6492 mse=0.1661 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.146097183227539, "reserved_gb": 2.376953125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "2936", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "66.40"}
2026-08-09 10:32:58 | INFO | train task=Ses01F epoch=8 batch=1828/2395 step=4650 loss=0.1088 ce=0.0196 mse=0.1784 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.144040584564209, "reserved_gb": 2.4140625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "23", "gpu_mem_used_mb": "2978", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "69.31"}
2026-08-09 10:33:18 | INFO | train task=Ses01F epoch=8 batch=1928/2395 step=4675 loss=0.7371 ce=0.5636 mse=0.3471 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1434745788574219, "reserved_gb": 2.048828125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "2604", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "64.24"}
2026-08-09 10:33:38 | INFO | train task=Ses01F epoch=8 batch=2028/2395 step=4700 loss=0.0395 ce=0.0121 mse=0.0549 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.149683952331543, "reserved_gb": 2.5703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "23", "gpu_mem_used_mb": "3138", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "64.41"}
2026-08-09 10:34:04 | INFO | train task=Ses01F epoch=8 batch=2128/2395 step=4725 loss=0.2693 ce=0.1629 mse=0.2128 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1441245079040527, "reserved_gb": 2.3359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "24", "gpu_mem_used_mb": "2898", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "68.78"}
2026-08-09 10:34:24 | INFO | train task=Ses01F epoch=8 batch=2228/2395 step=4750 loss=0.3870 ce=0.1045 mse=0.5651 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1436948776245117, "reserved_gb": 2.12109375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "28", "gpu_mem_used_mb": "2678", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "60.74"}
2026-08-09 10:34:45 | INFO | train task=Ses01F epoch=8 batch=2328/2395 step=4775 loss=0.9933 ce=0.4353 mse=1.1159 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1429758071899414, "reserved_gb": 2.103515625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "32", "gpu_mem_used_mb": "2660", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "64.58"}

predict:   0%|          | 0/313 [00:00<?, ?it/s]

2026-08-09 10:35:22 | INFO | Epoch 08 task=Ses01F train_loss=0.6962 val_macro_f1=0.4003 val_mae=0.5558 epoch_seconds=530.2

epoch 9:   0%|          | 0/2395 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 10:35:32 | INFO | train task=Ses01F epoch=9 batch=32/2395 step=4800 loss=1.0509 ce=0.5083 mse=1.0852 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.143460750579834, "reserved_gb": 2.12109375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "18", "gpu_mem_used_mb": "2678", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "60.04"}
2026-08-09 10:35:55 | INFO | train task=Ses01F epoch=9 batch=132/2395 step=4825 loss=0.3999 ce=0.2188 mse=0.3621 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1461081504821777, "reserved_gb": 2.037109375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "23", "gpu_mem_used_mb": "2592", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "68.42"}
2026-08-09 10:36:14 | INFO | train task=Ses01F epoch=9 batch=232/2395 step=4850 loss=0.7514 ce=0.0710 mse=1.3608 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1434378623962402, "reserved_gb": 2.04296875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "82", "gpu_mem_used_mb": "2598", "gpu_mem_total_mb": "12288", "gpu_temp_c": "54", "gpu_power_w": "68.28"}
2026-08-09 10:36:33 | INFO | train task=Ses01F epoch=9 batch=332/2395 step=4875 loss=0.9185 ce=0.6522 mse=0.5326 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1429996490478516, "reserved_gb": 2.30859375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "39", "gpu_mem_used_mb": "2870", "gpu_mem_total_mb": "12288", "gpu_temp_c": "54", "gpu_power_w": "68.96"}
2026-08-09 10:36:52 | INFO | train task=Ses01F epoch=9 batch=432/2395 step=4900 loss=1.3226 ce=1.2242 mse=0.1968 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1432466506958008, "reserved_gb": 2.037109375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "2592", "gpu_mem_total_mb": "12288", "gpu_temp_c": "54", "gpu_power_w": "71.79"}
2026-08-09 10:37:15 | INFO | train task=Ses01F epoch=9 batch=532/2395 step=4925 loss=1.4448 ce=1.3563 mse=0.1772 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1434803009033203, "reserved_gb": 2.046875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "2602", "gpu_mem_total_mb": "12288", "gpu_temp_c": "56", "gpu_power_w": "74.87"}
2026-08-09 10:37:35 | INFO | train task=Ses01F epoch=9 batch=632/2395 step=4950 loss=0.8095 ce=0.5157 mse=0.5876 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.143357276916504, "reserved_gb": 2.89453125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "3470", "gpu_mem_total_mb": "12288", "gpu_temp_c": "55", "gpu_power_w": "94.45"}
2026-08-09 10:37:54 | INFO | train task=Ses01F epoch=9 batch=732/2395 step=4975 loss=0.0796 ce=0.0347 mse=0.0900 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.143397331237793, "reserved_gb": 2.203125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "43", "gpu_mem_used_mb": "2766", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "52.93"}
2026-08-09 10:38:15 | INFO | train task=Ses01F epoch=9 batch=832/2395 step=5000 loss=0.8165 ce=0.2990 mse=1.0350 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1430068016052246, "reserved_gb": 2.033203125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "24", "gpu_mem_used_mb": "2592", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "81.08"}
2026-08-09 10:38:40 | INFO | train task=Ses01F epoch=9 batch=932/2395 step=5025 loss=2.2636 ce=1.8553 mse=0.8166 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1431045532226562, "reserved_gb": 2.044921875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "12", "gpu_mem_used_mb": "2604", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "61.33"}
2026-08-09 10:38:59 | INFO | train task=Ses01F epoch=9 batch=1032/2395 step=5050 loss=0.0959 ce=0.0303 mse=0.1312 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1446785926818848, "reserved_gb": 2.12109375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "31", "gpu_mem_used_mb": "2682", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "68.59"}
2026-08-09 10:39:18 | INFO | train task=Ses01F epoch=9 batch=1132/2395 step=5075 loss=0.2213 ce=0.1954 mse=0.0519 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1431903839111328, "reserved_gb": 2.033203125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "2592", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "70.79"}
2026-08-09 10:39:37 | INFO | train task=Ses01F epoch=9 batch=1232/2395 step=5100 loss=0.5187 ce=0.2122 mse=0.6130 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.144315242767334, "reserved_gb": 2.533203125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "29", "gpu_mem_used_mb": "3104", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "65.03"}
2026-08-09 10:39:59 | INFO | train task=Ses01F epoch=9 batch=1332/2395 step=5125 loss=0.3603 ce=0.1903 mse=0.3400 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1432323455810547, "reserved_gb": 2.119140625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "36", "gpu_mem_used_mb": "2680", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "67.21"}
2026-08-09 10:40:19 | INFO | train task=Ses01F epoch=9 batch=1432/2395 step=5150 loss=0.6130 ce=0.4880 mse=0.2500 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1451497077941895, "reserved_gb": 2.240234375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "46", "gpu_mem_used_mb": "2804", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "79.54"}
2026-08-09 10:40:38 | INFO | train task=Ses01F epoch=9 batch=1532/2395 step=5175 loss=1.5548 ce=1.5518 mse=0.0060 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1432762145996094, "reserved_gb": 2.0390625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "19", "gpu_mem_used_mb": "2598", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "68.41"}
2026-08-09 10:40:58 | INFO | train task=Ses01F epoch=9 batch=1632/2395 step=5200 loss=0.2531 ce=0.2065 mse=0.0931 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1441168785095215, "reserved_gb": 2.033203125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "14", "gpu_mem_used_mb": "2592", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "65.79"}
2026-08-09 10:41:21 | INFO | train task=Ses01F epoch=9 batch=1732/2395 step=5225 loss=0.6058 ce=0.4392 mse=0.3332 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.143106460571289, "reserved_gb": 2.2578125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "39", "gpu_mem_used_mb": "2822", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "69.07"}
2026-08-09 10:41:42 | INFO | train task=Ses01F epoch=9 batch=1832/2395 step=5250 loss=0.1967 ce=0.0798 mse=0.2340 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.144239902496338, "reserved_gb": 2.111328125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "16", "gpu_mem_used_mb": "2672", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "59.55"}
2026-08-09 10:42:02 | INFO | train task=Ses01F epoch=9 batch=1932/2395 step=5275 loss=0.6773 ce=0.6499 mse=0.0549 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1434626579284668, "reserved_gb": 2.12109375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "2682", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "75.23"}
2026-08-09 10:42:23 | INFO | train task=Ses01F epoch=9 batch=2032/2395 step=5300 loss=0.1697 ce=0.0507 mse=0.2381 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.144117832183838, "reserved_gb": 2.337890625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "23", "gpu_mem_used_mb": "2904", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "68.96"}
2026-08-09 10:42:47 | INFO | train task=Ses01F epoch=9 batch=2132/2395 step=5325 loss=0.9450 ce=0.8686 mse=0.1527 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1434264183044434, "reserved_gb": 2.04296875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "65", "gpu_mem_used_mb": "2602", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "81.77"}
2026-08-09 10:43:10 | INFO | train task=Ses01F epoch=9 batch=2232/2395 step=5350 loss=0.0988 ce=0.0372 mse=0.1231 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.143531322479248, "reserved_gb": 2.326171875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "24", "gpu_mem_used_mb": "2892", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "71.19"}
2026-08-09 10:43:32 | INFO | train task=Ses01F epoch=9 batch=2332/2395 step=5375 loss=0.0374 ce=0.0325 mse=0.0099 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1435332298278809, "reserved_gb": 2.125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "27", "gpu_mem_used_mb": "2686", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "65.68"}

predict:   0%|          | 0/313 [00:00<?, ?it/s]

2026-08-09 10:44:08 | INFO | Epoch 09 task=Ses01F train_loss=0.6312 val_macro_f1=0.3982 val_mae=0.5323 epoch_seconds=522.8

predict:   0%|          | 0/357 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)

predict:   0%|          | 0/328 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
2026-08-09 10:45:44 | INFO | Task 5819fd4ddc4d955f_main_fold -> complete
2026-08-09 10:45:46 | INFO | Manuscript outputs refreshed: 21 tables, 4 figures
2026-08-09 10:45:46 | INFO | Task 207a89e0d36f7233_main_fold -> running
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\transformers\configuration_utils.py:335: UserWarning: Passing `gradient_checkpointing` to a config initialization is deprecated and will be removed in v5 Transformers. Using `model.gradient_checkpointing_enable()` instead, or if you are using the `Trainer` API, pass `gradient_checkpointing=True` in your `TrainingArguments`.
  warnings.warn(
2026-08-09 10:45:49 | INFO | Task C:\Users\HaseebWajid\Downloads\runs\dersx_paper_aligned\campaign_01\main\seed_29\Ses03M parameters={'total': 163009451, 'trainable': 69034283, 'frozen': 93975168} scope={'corpus': 'IEMOCAP', 'protocol': 'strict_LOSO', 'heldout_speaker': 'Ses03M', 'seed': 29, 'stage': 'main', 'profile': 'rtx3060_24h'}

epoch 1:   0%|          | 0/2396 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 10:46:12 | INFO | train task=Ses03M epoch=1 batch=100/2396 step=25 loss=2.4390 ce=2.2036 mse=0.4709 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1436529159545898, "reserved_gb": 1.84765625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "30", "gpu_mem_used_mb": "2414", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "89.75"}
2026-08-09 10:46:35 | INFO | train task=Ses03M epoch=1 batch=200/2396 step=50 loss=2.4075 ce=2.2171 mse=0.3808 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.141383171081543, "reserved_gb": 1.80859375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "19", "gpu_mem_used_mb": "2380", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "79.34"}
2026-08-09 10:46:57 | INFO | train task=Ses03M epoch=1 batch=300/2396 step=75 loss=2.4101 ce=2.1775 mse=0.4652 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.141240119934082, "reserved_gb": 1.9921875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "26", "gpu_mem_used_mb": "2580", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "69.94"}
2026-08-09 10:47:19 | INFO | train task=Ses03M epoch=1 batch=400/2396 step=100 loss=1.7133 ce=1.6841 mse=0.0585 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1420602798461914, "reserved_gb": 1.890625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "23", "gpu_mem_used_mb": "2476", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "92.87"}
2026-08-09 10:47:43 | INFO | train task=Ses03M epoch=1 batch=500/2396 step=125 loss=3.7669 ce=2.3827 mse=2.7684 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1413450241088867, "reserved_gb": 1.703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "25", "gpu_mem_used_mb": "2284", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "75.14"}
2026-08-09 10:48:04 | INFO | train task=Ses03M epoch=1 batch=600/2396 step=150 loss=3.3879 ce=3.3493 mse=0.0771 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1412272453308105, "reserved_gb": 1.875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "2477", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "61.90"}
2026-08-09 10:48:28 | INFO | train task=Ses03M epoch=1 batch=700/2396 step=175 loss=2.2435 ce=1.8130 mse=0.8611 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1416959762573242, "reserved_gb": 1.708984375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "25", "gpu_mem_used_mb": "2321", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "63.35"}
2026-08-09 10:48:50 | INFO | train task=Ses03M epoch=1 batch=800/2396 step=200 loss=1.7586 ce=1.6055 mse=0.3061 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1424860954284668, "reserved_gb": 1.921875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "16", "gpu_mem_used_mb": "2533", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "62.73"}
2026-08-09 10:49:17 | INFO | train task=Ses03M epoch=1 batch=900/2396 step=225 loss=2.1924 ce=2.0410 mse=0.3028 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1463594436645508, "reserved_gb": 1.755859375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "44", "gpu_mem_used_mb": "2363", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "79.63"}
2026-08-09 10:49:39 | INFO | train task=Ses03M epoch=1 batch=1000/2396 step=250 loss=1.9991 ce=1.9634 mse=0.0714 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1411285400390625, "reserved_gb": 1.818359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "35", "gpu_mem_used_mb": "2427", "gpu_mem_total_mb": "12288", "gpu_temp_c": "44", "gpu_power_w": "60.31"}
2026-08-09 10:50:01 | INFO | train task=Ses03M epoch=1 batch=1100/2396 step=275 loss=2.5059 ce=1.6731 mse=1.6656 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1422605514526367, "reserved_gb": 1.703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "31", "gpu_mem_used_mb": "2309", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "65.03"}
2026-08-09 10:50:23 | INFO | train task=Ses03M epoch=1 batch=1200/2396 step=300 loss=2.7818 ce=2.2080 mse=1.1476 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.144108772277832, "reserved_gb": 1.96484375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "2577", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "73.46"}
2026-08-09 10:50:49 | INFO | train task=Ses03M epoch=1 batch=1300/2396 step=325 loss=2.3631 ce=2.2866 mse=0.1529 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1418657302856445, "reserved_gb": 1.76171875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "29", "gpu_mem_used_mb": "2369", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "67.42"}
2026-08-09 10:51:12 | INFO | train task=Ses03M epoch=1 batch=1400/2396 step=350 loss=0.8214 ce=0.5399 mse=0.5631 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1503300666809082, "reserved_gb": 2.353515625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "26", "gpu_mem_used_mb": "2975", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "68.61"}
2026-08-09 10:51:33 | INFO | train task=Ses03M epoch=1 batch=1500/2396 step=375 loss=1.0382 ce=0.8479 mse=0.3806 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1461915969848633, "reserved_gb": 1.759765625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "74", "gpu_mem_used_mb": "2367", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "84.61"}
2026-08-09 10:51:58 | INFO | train task=Ses03M epoch=1 batch=1600/2396 step=400 loss=2.1052 ce=1.9014 mse=0.4075 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1465425491333008, "reserved_gb": 1.76171875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "98", "gpu_mem_used_mb": "2369", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "89.75"}
2026-08-09 10:52:24 | INFO | train task=Ses03M epoch=1 batch=1700/2396 step=425 loss=1.7292 ce=1.6064 mse=0.2455 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1411738395690918, "reserved_gb": 1.82421875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "27", "gpu_mem_used_mb": "2433", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "60.76"}
2026-08-09 10:52:46 | INFO | train task=Ses03M epoch=1 batch=1800/2396 step=450 loss=2.1761 ce=1.5639 mse=1.2245 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1410408020019531, "reserved_gb": 1.736328125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "29", "gpu_mem_used_mb": "2343", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "69.62"}
2026-08-09 10:53:10 | INFO | train task=Ses03M epoch=1 batch=1900/2396 step=475 loss=2.2024 ce=2.1770 mse=0.0508 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.141364574432373, "reserved_gb": 1.703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "30", "gpu_mem_used_mb": "2309", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "65.77"}
2026-08-09 10:53:32 | INFO | train task=Ses03M epoch=1 batch=2000/2396 step=500 loss=0.6075 ce=0.4252 mse=0.3645 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.142488956451416, "reserved_gb": 1.873046875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "29", "gpu_mem_used_mb": "2483", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "70.66"}
2026-08-09 10:53:57 | INFO | train task=Ses03M epoch=1 batch=2100/2396 step=525 loss=0.8783 ce=0.7997 mse=0.1573 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1422510147094727, "reserved_gb": 1.7265625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "23", "gpu_mem_used_mb": "2333", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "66.07"}
2026-08-09 10:54:21 | INFO | train task=Ses03M epoch=1 batch=2200/2396 step=550 loss=1.1015 ce=0.9695 mse=0.2641 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1419930458068848, "reserved_gb": 1.712890625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "64", "gpu_mem_used_mb": "2319", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "78.47"}
2026-08-09 10:54:44 | INFO | train task=Ses03M epoch=1 batch=2300/2396 step=575 loss=2.5241 ce=2.3349 mse=0.3785 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1416277885437012, "reserved_gb": 1.912109375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "2523", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "63.73"}

predict:   0%|          | 0/301 [00:00<?, ?it/s]

2026-08-09 10:55:43 | INFO | Epoch 01 task=Ses03M train_loss=2.0239 val_macro_f1=0.3523 val_mae=0.6186 epoch_seconds=593.7

epoch 2:   0%|          | 0/2396 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 10:55:49 | INFO | train task=Ses03M epoch=2 batch=4/2396 step=600 loss=1.2777 ce=0.7952 mse=0.9650 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1416501998901367, "reserved_gb": 1.73828125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "24", "gpu_mem_used_mb": "2345", "gpu_mem_total_mb": "12288", "gpu_temp_c": "44", "gpu_power_w": "35.99"}
2026-08-09 10:56:13 | INFO | train task=Ses03M epoch=2 batch=104/2396 step=625 loss=3.3206 ce=3.1934 mse=0.2544 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.142049789428711, "reserved_gb": 1.939453125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "14", "gpu_mem_used_mb": "2551", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "66.43"}
2026-08-09 10:56:33 | INFO | train task=Ses03M epoch=2 batch=204/2396 step=650 loss=0.6364 ce=0.2262 mse=0.8205 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1413874626159668, "reserved_gb": 2.890625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "16", "gpu_mem_used_mb": "3525", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "66.50"}
2026-08-09 10:56:52 | INFO | train task=Ses03M epoch=2 batch=304/2396 step=675 loss=0.8028 ce=0.8023 mse=0.0010 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1414375305175781, "reserved_gb": 2.078125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "18", "gpu_mem_used_mb": "2693", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "62.69"}
2026-08-09 10:57:12 | INFO | train task=Ses03M epoch=2 batch=404/2396 step=700 loss=1.2898 ce=1.1358 mse=0.3079 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.141265869140625, "reserved_gb": 2.099609375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "34", "gpu_mem_used_mb": "2715", "gpu_mem_total_mb": "12288", "gpu_temp_c": "44", "gpu_power_w": "66.19"}
2026-08-09 10:57:35 | INFO | train task=Ses03M epoch=2 batch=504/2396 step=725 loss=1.2703 ce=0.8991 mse=0.7425 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1420116424560547, "reserved_gb": 2.158203125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "19", "gpu_mem_used_mb": "2775", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "70.48"}
2026-08-09 10:57:53 | INFO | train task=Ses03M epoch=2 batch=604/2396 step=750 loss=2.7790 ce=2.3678 mse=0.8225 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1413512229919434, "reserved_gb": 2.21875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "27", "gpu_mem_used_mb": "2837", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "62.80"}
2026-08-09 10:58:13 | INFO | train task=Ses03M epoch=2 batch=704/2396 step=775 loss=1.1320 ce=0.6450 mse=0.9740 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.141230583190918, "reserved_gb": 1.869140625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "2479", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "62.02"}
2026-08-09 10:58:33 | INFO | train task=Ses03M epoch=2 batch=804/2396 step=800 loss=2.4190 ce=2.1703 mse=0.4973 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1412067413330078, "reserved_gb": 2.626953125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "92", "gpu_mem_used_mb": "3255", "gpu_mem_total_mb": "12288", "gpu_temp_c": "54", "gpu_power_w": "71.07"}
2026-08-09 10:58:55 | INFO | train task=Ses03M epoch=2 batch=904/2396 step=825 loss=0.8527 ce=0.7151 mse=0.2754 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1465425491333008, "reserved_gb": 2.345703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "30", "gpu_mem_used_mb": "2967", "gpu_mem_total_mb": "12288", "gpu_temp_c": "54", "gpu_power_w": "66.57"}
2026-08-09 10:59:15 | INFO | train task=Ses03M epoch=2 batch=1004/2396 step=850 loss=1.5608 ce=1.2738 mse=0.5741 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1414880752563477, "reserved_gb": 1.712890625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "2318", "gpu_mem_total_mb": "12288", "gpu_temp_c": "54", "gpu_power_w": "65.54"}
2026-08-09 10:59:35 | INFO | train task=Ses03M epoch=2 batch=1104/2396 step=875 loss=0.3975 ce=0.2930 mse=0.2090 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1465425491333008, "reserved_gb": 2.044921875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "26", "gpu_mem_used_mb": "2661", "gpu_mem_total_mb": "12288", "gpu_temp_c": "55", "gpu_power_w": "60.89"}
2026-08-09 10:59:53 | INFO | train task=Ses03M epoch=2 batch=1204/2396 step=900 loss=1.1987 ce=1.1583 mse=0.0808 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.141223430633545, "reserved_gb": 1.701171875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "2309", "gpu_mem_total_mb": "12288", "gpu_temp_c": "56", "gpu_power_w": "67.59"}
2026-08-09 11:00:16 | INFO | train task=Ses03M epoch=2 batch=1304/2396 step=925 loss=1.6802 ce=1.6583 mse=0.0439 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1412601470947266, "reserved_gb": 1.74609375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "75", "gpu_mem_used_mb": "2355", "gpu_mem_total_mb": "12288", "gpu_temp_c": "57", "gpu_power_w": "53.52"}
2026-08-09 11:00:35 | INFO | train task=Ses03M epoch=2 batch=1404/2396 step=950 loss=0.5502 ce=0.4461 mse=0.2082 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.141387939453125, "reserved_gb": 1.8671875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "14", "gpu_mem_used_mb": "2479", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "52.03"}
2026-08-09 11:00:57 | INFO | train task=Ses03M epoch=2 batch=1504/2396 step=975 loss=2.2918 ce=2.1574 mse=0.2687 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.141169548034668, "reserved_gb": 2.423828125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "55", "gpu_mem_used_mb": "3049", "gpu_mem_total_mb": "12288", "gpu_temp_c": "55", "gpu_power_w": "78.80"}
2026-08-09 11:01:17 | INFO | train task=Ses03M epoch=2 batch=1604/2396 step=1000 loss=1.8391 ce=1.5699 mse=0.5384 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1413683891296387, "reserved_gb": 1.869140625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "2481", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "42.91"}
2026-08-09 11:01:40 | INFO | train task=Ses03M epoch=2 batch=1704/2396 step=1025 loss=4.2918 ce=4.1536 mse=0.2765 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.142138957977295, "reserved_gb": 2.00390625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "42", "gpu_mem_used_mb": "2619", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "60.24"}
2026-08-09 11:01:59 | INFO | train task=Ses03M epoch=2 batch=1804/2396 step=1050 loss=1.6634 ce=1.4937 mse=0.3395 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1411142349243164, "reserved_gb": 2.359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "41", "gpu_mem_used_mb": "2983", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "80.92"}
2026-08-09 11:02:19 | INFO | train task=Ses03M epoch=2 batch=1904/2396 step=1075 loss=2.0632 ce=1.9624 mse=0.2014 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1409540176391602, "reserved_gb": 1.75390625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "23", "gpu_mem_used_mb": "2363", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "68.30"}
2026-08-09 11:02:40 | INFO | train task=Ses03M epoch=2 batch=2004/2396 step=1100 loss=0.5488 ce=0.4366 mse=0.2243 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1412005424499512, "reserved_gb": 1.73046875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "18", "gpu_mem_used_mb": "2339", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "81.18"}
2026-08-09 11:03:03 | INFO | train task=Ses03M epoch=2 batch=2104/2396 step=1125 loss=0.2327 ce=0.2236 mse=0.0182 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1446542739868164, "reserved_gb": 2.033203125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "33", "gpu_mem_used_mb": "2649", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "63.43"}
2026-08-09 11:03:23 | INFO | train task=Ses03M epoch=2 batch=2204/2396 step=1150 loss=2.9732 ce=2.9587 mse=0.0292 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1412792205810547, "reserved_gb": 1.82421875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "29", "gpu_mem_used_mb": "2435", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "72.95"}
2026-08-09 11:03:43 | INFO | train task=Ses03M epoch=2 batch=2304/2396 step=1175 loss=0.6214 ce=0.5088 mse=0.2252 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1415696144104004, "reserved_gb": 2.052734375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "26", "gpu_mem_used_mb": "2669", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "60.30"}

predict:   0%|          | 0/301 [00:00<?, ?it/s]

2026-08-09 11:04:26 | INFO | Epoch 02 task=Ses03M train_loss=1.4900 val_macro_f1=0.4443 val_mae=0.5518 epoch_seconds=518.5

epoch 3:   0%|          | 0/2396 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 11:04:33 | INFO | train task=Ses03M epoch=3 batch=8/2396 step=1200 loss=1.3361 ce=0.7977 mse=1.0768 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.141097068786621, "reserved_gb": 12.71875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "12015", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "74.03"}
2026-08-09 11:04:56 | INFO | train task=Ses03M epoch=3 batch=108/2396 step=1225 loss=0.4353 ce=0.4017 mse=0.0672 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1422104835510254, "reserved_gb": 2.35546875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "31", "gpu_mem_used_mb": "2915", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "72.29"}
2026-08-09 11:05:15 | INFO | train task=Ses03M epoch=3 batch=208/2396 step=1250 loss=1.1477 ce=1.0710 mse=0.1534 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1426539421081543, "reserved_gb": 1.8359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "39", "gpu_mem_used_mb": "2383", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "60.18"}
2026-08-09 11:05:33 | INFO | train task=Ses03M epoch=3 batch=308/2396 step=1275 loss=2.7766 ce=1.9123 mse=1.7285 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.141092300415039, "reserved_gb": 2.10546875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "46", "gpu_mem_used_mb": "2675", "gpu_mem_total_mb": "12288", "gpu_temp_c": "55", "gpu_power_w": "78.66"}
2026-08-09 11:05:52 | INFO | train task=Ses03M epoch=3 batch=408/2396 step=1300 loss=0.4837 ce=0.2650 mse=0.4374 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1412606239318848, "reserved_gb": 1.72265625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "28", "gpu_mem_used_mb": "2283", "gpu_mem_total_mb": "12288", "gpu_temp_c": "53", "gpu_power_w": "62.63"}
2026-08-09 11:06:13 | INFO | train task=Ses03M epoch=3 batch=508/2396 step=1325 loss=2.0479 ce=1.9310 mse=0.2338 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1417632102966309, "reserved_gb": 2.546875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "34", "gpu_mem_used_mb": "3127", "gpu_mem_total_mb": "12288", "gpu_temp_c": "53", "gpu_power_w": "60.34"}
2026-08-09 11:06:32 | INFO | train task=Ses03M epoch=3 batch=608/2396 step=1350 loss=1.8170 ce=1.1466 mse=1.3407 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.141660213470459, "reserved_gb": 1.744140625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "2305", "gpu_mem_total_mb": "12288", "gpu_temp_c": "57", "gpu_power_w": "85.99"}
2026-08-09 11:06:51 | INFO | train task=Ses03M epoch=3 batch=708/2396 step=1375 loss=1.2904 ce=1.0416 mse=0.4976 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1410493850708008, "reserved_gb": 2.13671875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "31", "gpu_mem_used_mb": "2707", "gpu_mem_total_mb": "12288", "gpu_temp_c": "53", "gpu_power_w": "61.44"}
2026-08-09 11:07:09 | INFO | train task=Ses03M epoch=3 batch=808/2396 step=1400 loss=0.9906 ce=0.8661 mse=0.2491 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.140953540802002, "reserved_gb": 1.90625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "2471", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "69.64"}
2026-08-09 11:07:33 | INFO | train task=Ses03M epoch=3 batch=908/2396 step=1425 loss=1.2260 ce=1.0453 mse=0.3613 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1412272453308105, "reserved_gb": 1.88671875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "32", "gpu_mem_used_mb": "2451", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "80.54"}
2026-08-09 11:07:51 | INFO | train task=Ses03M epoch=3 batch=1008/2396 step=1450 loss=0.8704 ce=0.7061 mse=0.3287 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1411995887756348, "reserved_gb": 2.177734375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "34", "gpu_mem_used_mb": "2749", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "60.83"}
2026-08-09 11:08:10 | INFO | train task=Ses03M epoch=3 batch=1108/2396 step=1475 loss=0.9303 ce=0.8887 mse=0.0833 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1465415954589844, "reserved_gb": 2.19921875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "27", "gpu_mem_used_mb": "2771", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "54.68"}
2026-08-09 11:08:29 | INFO | train task=Ses03M epoch=3 batch=1208/2396 step=1500 loss=0.5584 ce=0.4633 mse=0.1902 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1427392959594727, "reserved_gb": 1.80078125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "2363", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "58.52"}
2026-08-09 11:08:50 | INFO | train task=Ses03M epoch=3 batch=1308/2396 step=1525 loss=1.4671 ce=1.4260 mse=0.0822 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.141901969909668, "reserved_gb": 1.9375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "28", "gpu_mem_used_mb": "2503", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "70.09"}
2026-08-09 11:09:10 | INFO | train task=Ses03M epoch=3 batch=1408/2396 step=1550 loss=0.4655 ce=0.4415 mse=0.0480 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.141439437866211, "reserved_gb": 2.013671875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "37", "gpu_mem_used_mb": "2581", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "71.35"}
2026-08-09 11:09:29 | INFO | train task=Ses03M epoch=3 batch=1508/2396 step=1575 loss=1.0880 ce=1.0854 mse=0.0050 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.142064094543457, "reserved_gb": 1.92578125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "28", "gpu_mem_used_mb": "2491", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "69.55"}
2026-08-09 11:09:48 | INFO | train task=Ses03M epoch=3 batch=1608/2396 step=1600 loss=0.8498 ce=0.6477 mse=0.4042 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1412148475646973, "reserved_gb": 1.71875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "28", "gpu_mem_used_mb": "2279", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "59.16"}
2026-08-09 11:10:10 | INFO | train task=Ses03M epoch=3 batch=1708/2396 step=1625 loss=1.3061 ce=0.6002 mse=1.4117 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.142549991607666, "reserved_gb": 1.9140625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "28", "gpu_mem_used_mb": "2479", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "68.87"}
2026-08-09 11:10:30 | INFO | train task=Ses03M epoch=3 batch=1808/2396 step=1650 loss=0.3713 ce=0.2505 mse=0.2415 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1415019035339355, "reserved_gb": 2.34765625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "2923", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "61.41"}
2026-08-09 11:10:50 | INFO | train task=Ses03M epoch=3 batch=1908/2396 step=1675 loss=0.7582 ce=0.2590 mse=0.9984 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1465425491333008, "reserved_gb": 2.064453125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "35", "gpu_mem_used_mb": "2633", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "63.97"}
2026-08-09 11:11:09 | INFO | train task=Ses03M epoch=3 batch=2008/2396 step=1700 loss=0.9258 ce=0.6873 mse=0.4771 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1414270401000977, "reserved_gb": 1.947265625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "34", "gpu_mem_used_mb": "2513", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "53.28"}
2026-08-09 11:11:32 | INFO | train task=Ses03M epoch=3 batch=2108/2396 step=1725 loss=3.1495 ce=2.7305 mse=0.8381 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1412086486816406, "reserved_gb": 2.220703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "18", "gpu_mem_used_mb": "2793", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "64.74"}
2026-08-09 11:11:50 | INFO | train task=Ses03M epoch=3 batch=2208/2396 step=1750 loss=0.4741 ce=0.2254 mse=0.4973 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1412625312805176, "reserved_gb": 1.7109375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "2271", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "52.44"}
2026-08-09 11:12:10 | INFO | train task=Ses03M epoch=3 batch=2308/2396 step=1775 loss=1.3887 ce=1.2132 mse=0.3511 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1411848068237305, "reserved_gb": 2.07421875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "11", "gpu_mem_used_mb": "2642", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "68.60"}

predict:   0%|          | 0/301 [00:00<?, ?it/s]

2026-08-09 11:12:47 | INFO | Epoch 03 task=Ses03M train_loss=1.2493 val_macro_f1=0.4263 val_mae=0.5682 epoch_seconds=495.6

epoch 4:   0%|          | 0/2396 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 11:12:52 | INFO | train task=Ses03M epoch=4 batch=12/2396 step=1800 loss=1.4615 ce=1.2098 mse=0.5034 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1413207054138184, "reserved_gb": 2.0859375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "40", "gpu_mem_used_mb": "2654", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "59.04"}
2026-08-09 11:13:15 | INFO | train task=Ses03M epoch=4 batch=112/2396 step=1825 loss=1.0060 ce=1.0052 mse=0.0017 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.141852855682373, "reserved_gb": 2.228515625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "26", "gpu_mem_used_mb": "2800", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "69.73"}
2026-08-09 11:13:33 | INFO | train task=Ses03M epoch=4 batch=212/2396 step=1850 loss=0.7964 ce=0.6753 mse=0.2422 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1464776992797852, "reserved_gb": 2.623046875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "18", "gpu_mem_used_mb": "3204", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "48.14"}
2026-08-09 11:13:51 | INFO | train task=Ses03M epoch=4 batch=312/2396 step=1875 loss=1.0976 ce=0.8486 mse=0.4980 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1465425491333008, "reserved_gb": 2.419921875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "54", "gpu_mem_used_mb": "2996", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "68.54"}
2026-08-09 11:14:09 | INFO | train task=Ses03M epoch=4 batch=412/2396 step=1900 loss=2.2797 ce=2.1123 mse=0.3349 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1413931846618652, "reserved_gb": 2.5546875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "16", "gpu_mem_used_mb": "3134", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "60.54"}
2026-08-09 11:14:32 | INFO | train task=Ses03M epoch=4 batch=512/2396 step=1925 loss=0.3258 ce=0.3057 mse=0.0402 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1410584449768066, "reserved_gb": 2.193359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "2764", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "73.15"}
2026-08-09 11:14:53 | INFO | train task=Ses03M epoch=4 batch=612/2396 step=1950 loss=0.2966 ce=0.2407 mse=0.1119 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.141416072845459, "reserved_gb": 1.98046875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "2546", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "65.13"}
2026-08-09 11:15:12 | INFO | train task=Ses03M epoch=4 batch=712/2396 step=1975 loss=0.4830 ce=0.2608 mse=0.4444 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1417508125305176, "reserved_gb": 2.51953125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "15", "gpu_mem_used_mb": "3097", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "62.22"}
2026-08-09 11:15:31 | INFO | train task=Ses03M epoch=4 batch=812/2396 step=2000 loss=1.0941 ce=1.0410 mse=0.1062 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1424860954284668, "reserved_gb": 1.86328125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "37", "gpu_mem_used_mb": "2425", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "48.01"}
2026-08-09 11:15:53 | INFO | train task=Ses03M epoch=4 batch=912/2396 step=2025 loss=0.5584 ce=0.5543 mse=0.0082 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1416702270507812, "reserved_gb": 1.8203125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "18", "gpu_mem_used_mb": "2381", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "66.68"}
2026-08-09 11:16:12 | INFO | train task=Ses03M epoch=4 batch=1012/2396 step=2050 loss=0.2638 ce=0.0840 mse=0.3598 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1414971351623535, "reserved_gb": 1.712890625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "45", "gpu_mem_used_mb": "2271", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "71.34"}
2026-08-09 11:16:31 | INFO | train task=Ses03M epoch=4 batch=1112/2396 step=2075 loss=0.4652 ce=0.3193 mse=0.2918 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1419148445129395, "reserved_gb": 2.34765625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "36", "gpu_mem_used_mb": "2921", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "72.67"}
2026-08-09 11:16:49 | INFO | train task=Ses03M epoch=4 batch=1212/2396 step=2100 loss=0.3438 ce=0.2049 mse=0.2778 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1415634155273438, "reserved_gb": 1.734375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "27", "gpu_mem_used_mb": "2293", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "84.63"}
2026-08-09 11:17:11 | INFO | train task=Ses03M epoch=4 batch=1312/2396 step=2125 loss=0.4108 ce=0.3317 mse=0.1582 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1415019035339355, "reserved_gb": 1.748046875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "12", "gpu_mem_used_mb": "2307", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "68.86"}
2026-08-09 11:17:30 | INFO | train task=Ses03M epoch=4 batch=1412/2396 step=2150 loss=0.4945 ce=0.1564 mse=0.6762 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1423125267028809, "reserved_gb": 2.17578125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "2744", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "63.15"}
2026-08-09 11:17:50 | INFO | train task=Ses03M epoch=4 batch=1512/2396 step=2175 loss=1.3303 ce=0.9209 mse=0.8188 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1413602828979492, "reserved_gb": 1.9609375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "2524", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "50.33"}
2026-08-09 11:18:08 | INFO | train task=Ses03M epoch=4 batch=1612/2396 step=2200 loss=0.8510 ce=0.8319 mse=0.0382 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1411175727844238, "reserved_gb": 1.826171875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "34", "gpu_mem_used_mb": "2386", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "63.64"}
2026-08-09 11:18:32 | INFO | train task=Ses03M epoch=4 batch=1712/2396 step=2225 loss=0.3049 ce=0.2343 mse=0.1412 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1465425491333008, "reserved_gb": 2.232421875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "31", "gpu_mem_used_mb": "2802", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "72.58"}
2026-08-09 11:18:51 | INFO | train task=Ses03M epoch=4 batch=1812/2396 step=2250 loss=0.9420 ce=0.9092 mse=0.0655 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1415696144104004, "reserved_gb": 1.884765625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "30", "gpu_mem_used_mb": "2446", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "68.31"}
2026-08-09 11:19:11 | INFO | train task=Ses03M epoch=4 batch=1912/2396 step=2275 loss=1.3092 ce=1.0258 mse=0.5667 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.141324520111084, "reserved_gb": 2.984375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "3572", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "63.98"}
2026-08-09 11:19:31 | INFO | train task=Ses03M epoch=4 batch=2012/2396 step=2300 loss=0.8652 ce=0.8311 mse=0.0683 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1424646377563477, "reserved_gb": 2.0546875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "32", "gpu_mem_used_mb": "2619", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "62.18"}
2026-08-09 11:19:54 | INFO | train task=Ses03M epoch=4 batch=2112/2396 step=2325 loss=1.0168 ce=0.9893 mse=0.0550 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1414103507995605, "reserved_gb": 1.966796875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "15", "gpu_mem_used_mb": "2529", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "62.69"}
2026-08-09 11:20:14 | INFO | train task=Ses03M epoch=4 batch=2212/2396 step=2350 loss=0.4968 ce=0.3277 mse=0.3383 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1409921646118164, "reserved_gb": 1.740234375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "36", "gpu_mem_used_mb": "2297", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "84.84"}
2026-08-09 11:20:34 | INFO | train task=Ses03M epoch=4 batch=2312/2396 step=2375 loss=2.5877 ce=2.2538 mse=0.6678 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.141852855682373, "reserved_gb": 1.763671875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "14", "gpu_mem_used_mb": "2321", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "64.76"}

predict:   0%|          | 0/301 [00:00<?, ?it/s]

2026-08-09 11:21:14 | INFO | Epoch 04 task=Ses03M train_loss=1.0736 val_macro_f1=0.4167 val_mae=0.5657 epoch_seconds=504.6

predict:   0%|          | 0/287 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)

predict:   0%|          | 0/413 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
2026-08-09 11:23:06 | INFO | Task 207a89e0d36f7233_main_fold -> complete
2026-08-09 11:23:08 | INFO | Manuscript outputs refreshed: 21 tables, 4 figures
2026-08-09 11:23:08 | INFO | Task 182d0b3b72ef6788_main_fold -> running
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\transformers\configuration_utils.py:335: UserWarning: Passing `gradient_checkpointing` to a config initialization is deprecated and will be removed in v5 Transformers. Using `model.gradient_checkpointing_enable()` instead, or if you are using the `Trainer` API, pass `gradient_checkpointing=True` in your `TrainingArguments`.
  warnings.warn(
2026-08-09 11:23:10 | INFO | Task C:\Users\HaseebWajid\Downloads\runs\dersx_paper_aligned\campaign_01\main\seed_29\Ses05M parameters={'total': 163009451, 'trainable': 69034283, 'frozen': 93975168} scope={'corpus': 'IEMOCAP', 'protocol': 'strict_LOSO', 'heldout_speaker': 'Ses05M', 'seed': 29, 'stage': 'main', 'profile': 'rtx3060_24h'}

epoch 1:   0%|          | 0/2365 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 11:23:33 | INFO | train task=Ses05M epoch=1 batch=100/2365 step=25 loss=2.6652 ce=2.0596 mse=1.2113 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1559829711914062, "reserved_gb": 1.89453125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "2435", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "65.07"}
2026-08-09 11:23:54 | INFO | train task=Ses05M epoch=1 batch=200/2365 step=50 loss=2.9680 ce=2.4460 mse=1.0442 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.156385898590088, "reserved_gb": 1.728515625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "45", "gpu_mem_used_mb": "2265", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "74.59"}
2026-08-09 11:24:17 | INFO | train task=Ses05M epoch=1 batch=300/2365 step=75 loss=3.2369 ce=1.9998 mse=2.4741 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1610875129699707, "reserved_gb": 2.060546875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "50", "gpu_mem_used_mb": "2605", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "80.28"}
2026-08-09 11:24:39 | INFO | train task=Ses05M epoch=1 batch=400/2365 step=100 loss=2.8735 ce=1.9085 mse=1.9299 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.155881404876709, "reserved_gb": 1.759765625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "16", "gpu_mem_used_mb": "2296", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "82.74"}
2026-08-09 11:25:02 | INFO | train task=Ses05M epoch=1 batch=500/2365 step=125 loss=3.0979 ce=2.0933 mse=2.0093 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.156287670135498, "reserved_gb": 1.728515625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "25", "gpu_mem_used_mb": "2264", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "70.47"}
2026-08-09 11:25:27 | INFO | train task=Ses05M epoch=1 batch=600/2365 step=150 loss=2.1051 ce=2.0749 mse=0.0605 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.156334400177002, "reserved_gb": 1.751953125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "2288", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "80.99"}
2026-08-09 11:25:49 | INFO | train task=Ses05M epoch=1 batch=700/2365 step=175 loss=2.4480 ce=2.1582 mse=0.5797 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.15730619430542, "reserved_gb": 1.8359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "30", "gpu_mem_used_mb": "2374", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "76.84"}
2026-08-09 11:26:11 | INFO | train task=Ses05M epoch=1 batch=800/2365 step=200 loss=2.5941 ce=1.8775 mse=1.4331 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1565194129943848, "reserved_gb": 1.708984375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "29", "gpu_mem_used_mb": "2244", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "75.30"}
2026-08-09 11:26:37 | INFO | train task=Ses05M epoch=1 batch=900/2365 step=225 loss=1.6863 ce=1.5757 mse=0.2213 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1562995910644531, "reserved_gb": 1.75, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "2286", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "85.52"}
2026-08-09 11:27:01 | INFO | train task=Ses05M epoch=1 batch=1000/2365 step=250 loss=1.8312 ce=1.7282 mse=0.2061 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1564393043518066, "reserved_gb": 1.75390625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "23", "gpu_mem_used_mb": "2289", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "73.61"}
2026-08-09 11:27:25 | INFO | train task=Ses05M epoch=1 batch=1100/2365 step=275 loss=1.8698 ce=1.6144 mse=0.5107 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.160250186920166, "reserved_gb": 1.888671875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "2427", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "76.64"}
2026-08-09 11:27:46 | INFO | train task=Ses05M epoch=1 batch=1200/2365 step=300 loss=1.5532 ce=1.4688 mse=0.1688 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1569108963012695, "reserved_gb": 1.791015625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "23", "gpu_mem_used_mb": "2327", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "67.65"}
2026-08-09 11:28:13 | INFO | train task=Ses05M epoch=1 batch=1300/2365 step=325 loss=2.2106 ce=1.4245 mse=1.5721 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1565699577331543, "reserved_gb": 1.814453125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "25", "gpu_mem_used_mb": "2351", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "83.12"}
2026-08-09 11:28:35 | INFO | train task=Ses05M epoch=1 batch=1400/2365 step=350 loss=1.7293 ce=1.4993 mse=0.4600 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1566991806030273, "reserved_gb": 1.748046875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "28", "gpu_mem_used_mb": "2283", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "79.12"}
2026-08-09 11:29:00 | INFO | train task=Ses05M epoch=1 batch=1500/2365 step=375 loss=3.2740 ce=1.9677 mse=2.6126 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.156458854675293, "reserved_gb": 1.798828125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "26", "gpu_mem_used_mb": "2334", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "76.20"}
2026-08-09 11:29:23 | INFO | train task=Ses05M epoch=1 batch=1600/2365 step=400 loss=1.3680 ce=1.1144 mse=0.5071 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.155881404876709, "reserved_gb": 1.625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "2156", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "78.36"}
2026-08-09 11:29:48 | INFO | train task=Ses05M epoch=1 batch=1700/2365 step=425 loss=1.6157 ce=0.8632 mse=1.5049 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1563901901245117, "reserved_gb": 1.70703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "24", "gpu_mem_used_mb": "2240", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "51.41"}
2026-08-09 11:30:12 | INFO | train task=Ses05M epoch=1 batch=1800/2365 step=450 loss=1.5181 ce=1.3515 mse=0.3332 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1564826965332031, "reserved_gb": 1.705078125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "59", "gpu_mem_used_mb": "2238", "gpu_mem_total_mb": "12288", "gpu_temp_c": "54", "gpu_power_w": "84.64"}
2026-08-09 11:30:36 | INFO | train task=Ses05M epoch=1 batch=1900/2365 step=475 loss=0.9794 ce=0.9615 mse=0.0359 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1572604179382324, "reserved_gb": 1.775390625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "31", "gpu_mem_used_mb": "2310", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "73.68"}
2026-08-09 11:30:59 | INFO | train task=Ses05M epoch=1 batch=2000/2365 step=500 loss=1.5436 ce=1.3931 mse=0.3010 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1612753868103027, "reserved_gb": 1.779296875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "55", "gpu_mem_used_mb": "2313", "gpu_mem_total_mb": "12288", "gpu_temp_c": "54", "gpu_power_w": "92.82"}
2026-08-09 11:31:25 | INFO | train task=Ses05M epoch=1 batch=2100/2365 step=525 loss=0.8346 ce=0.7894 mse=0.0903 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1575074195861816, "reserved_gb": 1.837890625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "60", "gpu_mem_used_mb": "2373", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "75.35"}
2026-08-09 11:31:49 | INFO | train task=Ses05M epoch=1 batch=2200/2365 step=550 loss=1.2347 ce=1.1451 mse=0.1791 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1574492454528809, "reserved_gb": 1.62109375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "35", "gpu_mem_used_mb": "2151", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "81.20"}
2026-08-09 11:32:13 | INFO | train task=Ses05M epoch=1 batch=2300/2365 step=575 loss=0.7880 ce=0.7010 mse=0.1741 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1562151908874512, "reserved_gb": 1.701171875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "25", "gpu_mem_used_mb": "2233", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "77.98"}

predict:   0%|          | 0/311 [00:00<?, ?it/s]

2026-08-09 11:33:09 | INFO | Epoch 01 task=Ses05M train_loss=2.0418 val_macro_f1=0.3724 val_mae=0.5717 epoch_seconds=598.3

epoch 2:   0%|          | 0/2365 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 11:33:20 | INFO | train task=Ses05M epoch=2 batch=32/2365 step=600 loss=2.5600 ce=2.3370 mse=0.4459 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1583404541015625, "reserved_gb": 1.75, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "54", "gpu_mem_used_mb": "2282", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "73.80"}
2026-08-09 11:33:43 | INFO | train task=Ses05M epoch=2 batch=132/2365 step=625 loss=1.3052 ce=1.1714 mse=0.2677 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.157383918762207, "reserved_gb": 1.79296875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "18", "gpu_mem_used_mb": "2326", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "68.07"}
2026-08-09 11:34:03 | INFO | train task=Ses05M epoch=2 batch=232/2365 step=650 loss=0.8836 ce=0.8748 mse=0.0177 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1562933921813965, "reserved_gb": 1.708984375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "2240", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "55.16"}
2026-08-09 11:34:23 | INFO | train task=Ses05M epoch=2 batch=332/2365 step=675 loss=1.4481 ce=1.4041 mse=0.0880 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1561460494995117, "reserved_gb": 1.69921875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "25", "gpu_mem_used_mb": "2230", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "52.57"}
2026-08-09 11:34:42 | INFO | train task=Ses05M epoch=2 batch=432/2365 step=700 loss=1.3483 ce=1.0524 mse=0.5918 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1559205055236816, "reserved_gb": 2.083984375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "73", "gpu_mem_used_mb": "2624", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "55.43"}
2026-08-09 11:35:06 | INFO | train task=Ses05M epoch=2 batch=532/2365 step=725 loss=1.0796 ce=0.9262 mse=0.3067 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1558332443237305, "reserved_gb": 1.77734375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "68", "gpu_mem_used_mb": "2310", "gpu_mem_total_mb": "12288", "gpu_temp_c": "53", "gpu_power_w": "90.13"}
2026-08-09 11:35:24 | INFO | train task=Ses05M epoch=2 batch=632/2365 step=750 loss=0.6901 ce=0.6252 mse=0.1297 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1568026542663574, "reserved_gb": 1.828125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "27", "gpu_mem_used_mb": "2361", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "43.71"}
2026-08-09 11:35:45 | INFO | train task=Ses05M epoch=2 batch=732/2365 step=775 loss=2.5231 ce=2.1006 mse=0.8450 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.156090259552002, "reserved_gb": 1.79296875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "2325", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "52.73"}
2026-08-09 11:36:05 | INFO | train task=Ses05M epoch=2 batch=832/2365 step=800 loss=1.4353 ce=1.3312 mse=0.2082 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1567749977111816, "reserved_gb": 1.625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "2153", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "63.24"}
2026-08-09 11:36:29 | INFO | train task=Ses05M epoch=2 batch=932/2365 step=825 loss=1.1148 ce=0.6092 mse=1.0111 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1558818817138672, "reserved_gb": 1.798828125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "12", "gpu_mem_used_mb": "2331", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "66.26"}
2026-08-09 11:36:51 | INFO | train task=Ses05M epoch=2 batch=1032/2365 step=850 loss=1.0979 ce=1.0236 mse=0.1486 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1564784049987793, "reserved_gb": 1.763671875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "10", "gpu_mem_used_mb": "2295", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "64.68"}
2026-08-09 11:37:11 | INFO | train task=Ses05M epoch=2 batch=1132/2365 step=875 loss=0.9715 ce=0.8466 mse=0.2499 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1561107635498047, "reserved_gb": 1.818359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "55", "gpu_mem_used_mb": "2351", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "63.97"}
2026-08-09 11:37:31 | INFO | train task=Ses05M epoch=2 batch=1232/2365 step=900 loss=0.8312 ce=0.7455 mse=0.1716 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1576342582702637, "reserved_gb": 2.587890625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "35", "gpu_mem_used_mb": "3138", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "74.43"}
2026-08-09 11:37:55 | INFO | train task=Ses05M epoch=2 batch=1332/2365 step=925 loss=1.3894 ce=1.2532 mse=0.2724 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1571202278137207, "reserved_gb": 1.783203125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "32", "gpu_mem_used_mb": "2314", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "60.52"}
2026-08-09 11:38:15 | INFO | train task=Ses05M epoch=2 batch=1432/2365 step=950 loss=1.2544 ce=0.9522 mse=0.6043 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.156343936920166, "reserved_gb": 1.888671875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "30", "gpu_mem_used_mb": "2422", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "82.81"}
2026-08-09 11:38:36 | INFO | train task=Ses05M epoch=2 batch=1532/2365 step=975 loss=0.4737 ce=0.4522 mse=0.0429 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1559290885925293, "reserved_gb": 1.98046875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "16", "gpu_mem_used_mb": "2516", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "74.38"}
2026-08-09 11:38:57 | INFO | train task=Ses05M epoch=2 batch=1632/2365 step=1000 loss=0.6088 ce=0.5467 mse=0.1243 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.156247615814209, "reserved_gb": 1.85546875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "24", "gpu_mem_used_mb": "2388", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "60.53"}
2026-08-09 11:39:21 | INFO | train task=Ses05M epoch=2 batch=1732/2365 step=1025 loss=1.2472 ce=1.2183 mse=0.0578 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1559138298034668, "reserved_gb": 1.794921875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "24", "gpu_mem_used_mb": "2325", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "64.76"}
2026-08-09 11:39:42 | INFO | train task=Ses05M epoch=2 batch=1832/2365 step=1050 loss=1.0369 ce=0.6282 mse=0.8175 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1589274406433105, "reserved_gb": 1.90234375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "25", "gpu_mem_used_mb": "2435", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "72.83"}
2026-08-09 11:40:04 | INFO | train task=Ses05M epoch=2 batch=1932/2365 step=1075 loss=2.0560 ce=1.9863 mse=0.1394 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.156301498413086, "reserved_gb": 1.728515625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "43", "gpu_mem_used_mb": "2257", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "63.87"}
2026-08-09 11:40:26 | INFO | train task=Ses05M epoch=2 batch=2032/2365 step=1100 loss=2.1107 ce=1.2793 mse=1.6629 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1557135581970215, "reserved_gb": 1.623046875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "16", "gpu_mem_used_mb": "2149", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "75.06"}
2026-08-09 11:40:50 | INFO | train task=Ses05M epoch=2 batch=2132/2365 step=1125 loss=1.3239 ce=1.2459 mse=0.1559 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.157407283782959, "reserved_gb": 1.626953125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "9", "gpu_mem_used_mb": "2153", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "65.46"}
2026-08-09 11:41:12 | INFO | train task=Ses05M epoch=2 batch=2232/2365 step=1150 loss=0.8000 ce=0.7559 mse=0.0883 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1570935249328613, "reserved_gb": 1.7265625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "29", "gpu_mem_used_mb": "2255", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "88.07"}
2026-08-09 11:41:35 | INFO | train task=Ses05M epoch=2 batch=2332/2365 step=1175 loss=1.7681 ce=1.7544 mse=0.0274 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1561994552612305, "reserved_gb": 1.638671875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "25", "gpu_mem_used_mb": "2164", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "72.90"}

predict:   0%|          | 0/311 [00:00<?, ?it/s]

2026-08-09 11:42:02 | INFO | Epoch 02 task=Ses05M train_loss=1.4821 val_macro_f1=0.3725 val_mae=0.5976 epoch_seconds=528.0

epoch 3:   0%|          | 0/2365 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 11:42:19 | INFO | train task=Ses05M epoch=3 batch=64/2365 step=1200 loss=0.9502 ce=0.8997 mse=0.1010 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1571755409240723, "reserved_gb": 1.78125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "62", "gpu_mem_used_mb": "2310", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "69.15"}
2026-08-09 11:42:42 | INFO | train task=Ses05M epoch=3 batch=164/2365 step=1225 loss=1.2864 ce=1.2279 mse=0.1171 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1558828353881836, "reserved_gb": 1.751953125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "37", "gpu_mem_used_mb": "2280", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "64.09"}
2026-08-09 11:43:02 | INFO | train task=Ses05M epoch=3 batch=264/2365 step=1250 loss=0.8590 ce=0.2585 mse=1.2010 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1563963890075684, "reserved_gb": 1.74609375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "31", "gpu_mem_used_mb": "2274", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "50.38"}
2026-08-09 11:43:22 | INFO | train task=Ses05M epoch=3 batch=364/2365 step=1275 loss=1.2317 ce=1.2302 mse=0.0029 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1559386253356934, "reserved_gb": 1.7265625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "27", "gpu_mem_used_mb": "2254", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "61.76"}
2026-08-09 11:43:41 | INFO | train task=Ses05M epoch=3 batch=464/2365 step=1300 loss=0.6346 ce=0.3249 mse=0.6193 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.158259391784668, "reserved_gb": 2.27734375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "43", "gpu_mem_used_mb": "2817", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "72.14"}
2026-08-09 11:44:05 | INFO | train task=Ses05M epoch=3 batch=564/2365 step=1325 loss=0.8476 ce=0.8359 mse=0.0234 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1572747230529785, "reserved_gb": 1.94140625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "25", "gpu_mem_used_mb": "2473", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "41.49"}
2026-08-09 11:44:25 | INFO | train task=Ses05M epoch=3 batch=664/2365 step=1350 loss=0.6577 ce=0.5361 mse=0.2432 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1563324928283691, "reserved_gb": 1.697265625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "33", "gpu_mem_used_mb": "2223", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "56.82"}
2026-08-09 11:44:44 | INFO | train task=Ses05M epoch=3 batch=764/2365 step=1375 loss=1.2400 ce=1.0358 mse=0.4085 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1560006141662598, "reserved_gb": 2.150390625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "14", "gpu_mem_used_mb": "2687", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "69.92"}
2026-08-09 11:45:03 | INFO | train task=Ses05M epoch=3 batch=864/2365 step=1400 loss=1.9310 ce=1.6627 mse=0.5367 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1562724113464355, "reserved_gb": 1.771484375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "31", "gpu_mem_used_mb": "2299", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "49.67"}
2026-08-09 11:45:25 | INFO | train task=Ses05M epoch=3 batch=964/2365 step=1425 loss=2.1192 ce=2.0488 mse=0.1406 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1564817428588867, "reserved_gb": 1.775390625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "18", "gpu_mem_used_mb": "2303", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "70.85"}
2026-08-09 11:45:46 | INFO | train task=Ses05M epoch=3 batch=1064/2365 step=1450 loss=2.1291 ce=2.0263 mse=0.2057 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1560025215148926, "reserved_gb": 1.71484375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "40", "gpu_mem_used_mb": "2240", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "77.16"}
2026-08-09 11:46:07 | INFO | train task=Ses05M epoch=3 batch=1164/2365 step=1475 loss=1.6444 ce=1.6343 mse=0.0202 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1563715934753418, "reserved_gb": 1.900390625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "2430", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "74.81"}
2026-08-09 11:46:28 | INFO | train task=Ses05M epoch=3 batch=1264/2365 step=1500 loss=0.4217 ce=0.3976 mse=0.0481 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.138784408569336, "reserved_gb": 2.212890625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "32", "gpu_mem_used_mb": "2750", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "43.93"}
2026-08-09 11:46:52 | INFO | train task=Ses05M epoch=3 batch=1364/2365 step=1525 loss=2.2227 ce=1.5904 mse=1.2646 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1393380165100098, "reserved_gb": 1.701171875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "29", "gpu_mem_used_mb": "2226", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "71.42"}
2026-08-09 11:47:13 | INFO | train task=Ses05M epoch=3 batch=1464/2365 step=1550 loss=0.8094 ce=0.6673 mse=0.2843 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1386075019836426, "reserved_gb": 1.9375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "44", "gpu_mem_used_mb": "2468", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "74.13"}
2026-08-09 11:47:34 | INFO | train task=Ses05M epoch=3 batch=1564/2365 step=1575 loss=1.0831 ce=0.9648 mse=0.2365 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1383190155029297, "reserved_gb": 1.634765625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "29", "gpu_mem_used_mb": "2158", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "76.97"}
2026-08-09 11:47:54 | INFO | train task=Ses05M epoch=3 batch=1664/2365 step=1600 loss=1.2169 ce=0.9821 mse=0.4696 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1423768997192383, "reserved_gb": 2.158203125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "35", "gpu_mem_used_mb": "2693", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "60.25"}
2026-08-09 11:48:18 | INFO | train task=Ses05M epoch=3 batch=1764/2365 step=1625 loss=0.7900 ce=0.5528 mse=0.4744 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1384119987487793, "reserved_gb": 1.626953125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "30", "gpu_mem_used_mb": "2149", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "72.35"}
2026-08-09 11:48:40 | INFO | train task=Ses05M epoch=3 batch=1864/2365 step=1650 loss=3.3366 ce=3.2169 mse=0.2394 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.141122817993164, "reserved_gb": 1.71484375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "32", "gpu_mem_used_mb": "2239", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "74.26"}
2026-08-09 11:49:03 | INFO | train task=Ses05M epoch=3 batch=1964/2365 step=1675 loss=0.9543 ce=0.9052 mse=0.0982 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1383838653564453, "reserved_gb": 1.640625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "13", "gpu_mem_used_mb": "2163", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "68.29"}
2026-08-09 11:49:25 | INFO | train task=Ses05M epoch=3 batch=2064/2365 step=1700 loss=0.4571 ce=0.1952 mse=0.5238 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1400585174560547, "reserved_gb": 2.1328125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "39", "gpu_mem_used_mb": "2667", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "70.05"}
2026-08-09 11:49:50 | INFO | train task=Ses05M epoch=3 batch=2164/2365 step=1725 loss=0.3804 ce=0.1774 mse=0.4061 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1413602828979492, "reserved_gb": 1.86328125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "28", "gpu_mem_used_mb": "2390", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "72.94"}
2026-08-09 11:50:12 | INFO | train task=Ses05M epoch=3 batch=2264/2365 step=1750 loss=0.6465 ce=0.6459 mse=0.0013 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1391716003417969, "reserved_gb": 1.70703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "25", "gpu_mem_used_mb": "2230", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "86.30"}
2026-08-09 11:50:35 | INFO | train task=Ses05M epoch=3 batch=2364/2365 step=1775 loss=0.5125 ce=0.4692 mse=0.0865 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.142425537109375, "reserved_gb": 1.728515625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "57", "gpu_mem_used_mb": "2252", "gpu_mem_total_mb": "12288", "gpu_temp_c": "53", "gpu_power_w": "83.81"}

predict:   0%|          | 0/311 [00:00<?, ?it/s]

2026-08-09 11:50:54 | INFO | Epoch 03 task=Ses05M train_loss=1.2542 val_macro_f1=0.3897 val_mae=0.5721 epoch_seconds=528.2

epoch 4:   0%|          | 0/2365 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 11:51:18 | INFO | train task=Ses05M epoch=4 batch=96/2365 step=1800 loss=1.4445 ce=1.2292 mse=0.4306 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1390447616577148, "reserved_gb": 1.8046875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "24", "gpu_mem_used_mb": "2330", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "72.62"}
2026-08-09 11:51:41 | INFO | train task=Ses05M epoch=4 batch=196/2365 step=1825 loss=0.7301 ce=0.6474 mse=0.1653 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1384334564208984, "reserved_gb": 1.76953125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "26", "gpu_mem_used_mb": "2294", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "64.68"}
2026-08-09 11:52:02 | INFO | train task=Ses05M epoch=4 batch=296/2365 step=1850 loss=0.8581 ce=0.6479 mse=0.4204 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1395397186279297, "reserved_gb": 1.875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "50", "gpu_mem_used_mb": "2401", "gpu_mem_total_mb": "12288", "gpu_temp_c": "54", "gpu_power_w": "96.70"}
2026-08-09 11:52:22 | INFO | train task=Ses05M epoch=4 batch=396/2365 step=1875 loss=0.6024 ce=0.5367 mse=0.1314 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1399197578430176, "reserved_gb": 2.158203125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "28", "gpu_mem_used_mb": "2691", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "73.15"}
2026-08-09 11:52:43 | INFO | train task=Ses05M epoch=4 batch=496/2365 step=1900 loss=0.3412 ce=0.1028 mse=0.4767 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1426019668579102, "reserved_gb": 1.9921875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "39", "gpu_mem_used_mb": "2521", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "60.66"}
2026-08-09 11:53:06 | INFO | train task=Ses05M epoch=4 batch=596/2365 step=1925 loss=0.2918 ce=0.2275 mse=0.1285 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.139383316040039, "reserved_gb": 1.84765625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "42", "gpu_mem_used_mb": "2373", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "86.77"}
2026-08-09 11:53:26 | INFO | train task=Ses05M epoch=4 batch=696/2365 step=1950 loss=0.6059 ce=0.5282 mse=0.1554 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1393070220947266, "reserved_gb": 1.91015625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "26", "gpu_mem_used_mb": "2437", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "64.18"}
2026-08-09 11:53:46 | INFO | train task=Ses05M epoch=4 batch=796/2365 step=1975 loss=0.6360 ce=0.4283 mse=0.4153 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1385016441345215, "reserved_gb": 1.82421875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "34", "gpu_mem_used_mb": "2349", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "63.41"}
2026-08-09 11:54:07 | INFO | train task=Ses05M epoch=4 batch=896/2365 step=2000 loss=1.5320 ce=1.5015 mse=0.0611 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1385436058044434, "reserved_gb": 1.806640625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "40", "gpu_mem_used_mb": "2330", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "66.31"}
2026-08-09 11:54:30 | INFO | train task=Ses05M epoch=4 batch=996/2365 step=2025 loss=2.0261 ce=1.9193 mse=0.2135 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.138382911682129, "reserved_gb": 1.7734375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "26", "gpu_mem_used_mb": "2296", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "62.94"}
2026-08-09 11:54:50 | INFO | train task=Ses05M epoch=4 batch=1096/2365 step=2050 loss=1.1686 ce=1.1157 mse=0.1057 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1391630172729492, "reserved_gb": 1.75, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "34", "gpu_mem_used_mb": "2272", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "55.56"}
2026-08-09 11:55:11 | INFO | train task=Ses05M epoch=4 batch=1196/2365 step=2075 loss=1.1709 ce=1.0412 mse=0.2595 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1382555961608887, "reserved_gb": 1.75, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "29", "gpu_mem_used_mb": "2272", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "66.54"}
2026-08-09 11:55:32 | INFO | train task=Ses05M epoch=4 batch=1296/2365 step=2100 loss=0.4779 ce=0.2452 mse=0.4653 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.138188362121582, "reserved_gb": 2.15625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "19", "gpu_mem_used_mb": "2688", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "67.62"}
2026-08-09 11:55:56 | INFO | train task=Ses05M epoch=4 batch=1396/2365 step=2125 loss=2.0904 ce=2.0770 mse=0.0267 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.139052391052246, "reserved_gb": 1.697265625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "24", "gpu_mem_used_mb": "2218", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "42.76"}
2026-08-09 11:56:16 | INFO | train task=Ses05M epoch=4 batch=1496/2365 step=2150 loss=0.8313 ce=0.7437 mse=0.1754 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1386113166809082, "reserved_gb": 1.814453125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "15", "gpu_mem_used_mb": "2337", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "53.48"}
2026-08-09 11:56:38 | INFO | train task=Ses05M epoch=4 batch=1596/2365 step=2175 loss=1.4010 ce=1.1696 mse=0.4629 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1383519172668457, "reserved_gb": 1.689453125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "18", "gpu_mem_used_mb": "2209", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "54.89"}
2026-08-09 11:57:01 | INFO | train task=Ses05M epoch=4 batch=1696/2365 step=2200 loss=2.0684 ce=2.0308 mse=0.0751 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1398749351501465, "reserved_gb": 1.625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "25", "gpu_mem_used_mb": "2143", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "53.88"}
2026-08-09 11:57:27 | INFO | train task=Ses05M epoch=4 batch=1796/2365 step=2225 loss=0.1864 ce=0.0899 mse=0.1930 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1399030685424805, "reserved_gb": 1.880859375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "69", "gpu_mem_used_mb": "2405", "gpu_mem_total_mb": "12288", "gpu_temp_c": "53", "gpu_power_w": "72.94"}
2026-08-09 11:57:50 | INFO | train task=Ses05M epoch=4 batch=1896/2365 step=2250 loss=2.3924 ce=1.6982 mse=1.3884 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1384716033935547, "reserved_gb": 1.72265625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "37", "gpu_mem_used_mb": "2243", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "87.96"}
2026-08-09 11:58:11 | INFO | train task=Ses05M epoch=4 batch=1996/2365 step=2275 loss=0.3833 ce=0.3659 mse=0.0347 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1383275985717773, "reserved_gb": 1.69921875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "24", "gpu_mem_used_mb": "2219", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "67.10"}
2026-08-09 11:58:36 | INFO | train task=Ses05M epoch=4 batch=2096/2365 step=2300 loss=0.9621 ce=0.7237 mse=0.4768 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1388301849365234, "reserved_gb": 2.076171875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "28", "gpu_mem_used_mb": "2604", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "68.52"}
2026-08-09 11:59:02 | INFO | train task=Ses05M epoch=4 batch=2196/2365 step=2325 loss=2.3264 ce=2.1465 mse=0.3598 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1384410858154297, "reserved_gb": 1.685546875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "2204", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "81.73"}
2026-08-09 11:59:25 | INFO | train task=Ses05M epoch=4 batch=2296/2365 step=2350 loss=1.1532 ce=0.5837 mse=1.1390 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1385416984558105, "reserved_gb": 1.63671875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "38", "gpu_mem_used_mb": "2154", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "78.32"}

predict:   0%|          | 0/311 [00:00<?, ?it/s]

2026-08-09 12:00:02 | INFO | Epoch 04 task=Ses05M train_loss=1.0809 val_macro_f1=0.3678 val_mae=0.5685 epoch_seconds=543.3

epoch 5:   0%|          | 0/2365 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 12:00:11 | INFO | train task=Ses05M epoch=5 batch=28/2365 step=2375 loss=0.6776 ce=0.5674 mse=0.2203 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.138495922088623, "reserved_gb": 1.8125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "27", "gpu_mem_used_mb": "2334", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "72.72"}
2026-08-09 12:00:31 | INFO | train task=Ses05M epoch=5 batch=128/2365 step=2400 loss=1.3212 ce=1.2934 mse=0.0556 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1386642456054688, "reserved_gb": 1.951171875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "50", "gpu_mem_used_mb": "2476", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "52.23"}
2026-08-09 12:00:54 | INFO | train task=Ses05M epoch=5 batch=228/2365 step=2425 loss=1.0620 ce=0.8892 mse=0.3456 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1389718055725098, "reserved_gb": 1.74609375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "2266", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "43.17"}
2026-08-09 12:01:13 | INFO | train task=Ses05M epoch=5 batch=328/2365 step=2450 loss=2.0031 ce=1.8022 mse=0.4017 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1385574340820312, "reserved_gb": 1.78515625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "26", "gpu_mem_used_mb": "2306", "gpu_mem_total_mb": "12288", "gpu_temp_c": "45", "gpu_power_w": "41.01"}
2026-08-09 12:01:32 | INFO | train task=Ses05M epoch=5 batch=428/2365 step=2475 loss=1.0528 ce=0.9923 mse=0.1211 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1398367881774902, "reserved_gb": 1.837890625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "26", "gpu_mem_used_mb": "2360", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "62.38"}
2026-08-09 12:01:53 | INFO | train task=Ses05M epoch=5 batch=528/2365 step=2500 loss=0.3238 ce=0.0247 mse=0.5982 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.147918701171875, "reserved_gb": 2.53125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "10", "gpu_mem_used_mb": "3070", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "82.50"}
2026-08-09 12:02:17 | INFO | train task=Ses05M epoch=5 batch=628/2365 step=2525 loss=0.4839 ce=0.4622 mse=0.0435 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1383776664733887, "reserved_gb": 1.77734375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "25", "gpu_mem_used_mb": "2298", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "60.77"}
2026-08-09 12:02:37 | INFO | train task=Ses05M epoch=5 batch=728/2365 step=2550 loss=0.4316 ce=0.3207 mse=0.2217 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1384382247924805, "reserved_gb": 1.76171875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "2282", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "56.44"}
2026-08-09 12:02:58 | INFO | train task=Ses05M epoch=5 batch=828/2365 step=2575 loss=0.7347 ce=0.3513 mse=0.7669 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1392340660095215, "reserved_gb": 1.998046875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "18", "gpu_mem_used_mb": "2524", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "64.39"}
2026-08-09 12:03:18 | INFO | train task=Ses05M epoch=5 batch=928/2365 step=2600 loss=0.8622 ce=0.8557 mse=0.0129 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.138984203338623, "reserved_gb": 1.669921875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "25", "gpu_mem_used_mb": "2188", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "71.60"}
2026-08-09 12:03:41 | INFO | train task=Ses05M epoch=5 batch=1028/2365 step=2625 loss=0.2395 ce=0.0498 mse=0.3794 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1403732299804688, "reserved_gb": 1.974609375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "9", "gpu_mem_used_mb": "2500", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "66.24"}
2026-08-09 12:04:02 | INFO | train task=Ses05M epoch=5 batch=1128/2365 step=2650 loss=0.4052 ce=0.2489 mse=0.3126 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.138455867767334, "reserved_gb": 1.720703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "41", "gpu_mem_used_mb": "2240", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "54.49"}
2026-08-09 12:04:22 | INFO | train task=Ses05M epoch=5 batch=1228/2365 step=2675 loss=0.0956 ce=0.0591 mse=0.0730 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1391944885253906, "reserved_gb": 1.8359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "29", "gpu_mem_used_mb": "2358", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "80.13"}
2026-08-09 12:04:42 | INFO | train task=Ses05M epoch=5 batch=1328/2365 step=2700 loss=0.5301 ce=0.3681 mse=0.3239 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1384129524230957, "reserved_gb": 1.8203125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "23", "gpu_mem_used_mb": "2342", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "61.96"}
2026-08-09 12:05:06 | INFO | train task=Ses05M epoch=5 batch=1428/2365 step=2725 loss=0.6906 ce=0.5041 mse=0.3731 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1384382247924805, "reserved_gb": 1.759765625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "16", "gpu_mem_used_mb": "2280", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "66.30"}
2026-08-09 12:05:28 | INFO | train task=Ses05M epoch=5 batch=1528/2365 step=2750 loss=0.1709 ce=0.1344 mse=0.0730 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1389093399047852, "reserved_gb": 1.83984375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "46", "gpu_mem_used_mb": "2362", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "76.92"}
2026-08-09 12:05:48 | INFO | train task=Ses05M epoch=5 batch=1628/2365 step=2775 loss=1.1551 ce=1.1289 mse=0.0523 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1393370628356934, "reserved_gb": 1.689453125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "24", "gpu_mem_used_mb": "2208", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "48.62"}
2026-08-09 12:06:11 | INFO | train task=Ses05M epoch=5 batch=1728/2365 step=2800 loss=1.3490 ce=0.9104 mse=0.8773 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1386513710021973, "reserved_gb": 1.79296875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "34", "gpu_mem_used_mb": "2314", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "76.75"}
2026-08-09 12:06:34 | INFO | train task=Ses05M epoch=5 batch=1828/2365 step=2825 loss=0.9853 ce=0.7623 mse=0.4461 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1431818008422852, "reserved_gb": 1.751953125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "40", "gpu_mem_used_mb": "2272", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "74.41"}
2026-08-09 12:06:56 | INFO | train task=Ses05M epoch=5 batch=1928/2365 step=2850 loss=1.4733 ce=1.3812 mse=0.1841 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1383371353149414, "reserved_gb": 2.0859375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "31", "gpu_mem_used_mb": "2614", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "74.67"}
2026-08-09 12:07:19 | INFO | train task=Ses05M epoch=5 batch=2028/2365 step=2875 loss=0.4466 ce=0.4277 mse=0.0378 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1389188766479492, "reserved_gb": 1.767578125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "2288", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "87.80"}
2026-08-09 12:07:43 | INFO | train task=Ses05M epoch=5 batch=2128/2365 step=2900 loss=0.3560 ce=0.2686 mse=0.1748 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1386661529541016, "reserved_gb": 1.638671875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "2156", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "75.92"}
2026-08-09 12:08:08 | INFO | train task=Ses05M epoch=5 batch=2228/2365 step=2925 loss=0.8949 ce=0.4354 mse=0.9190 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1386141777038574, "reserved_gb": 1.638671875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "23", "gpu_mem_used_mb": "2156", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "70.05"}
2026-08-09 12:08:30 | INFO | train task=Ses05M epoch=5 batch=2328/2365 step=2950 loss=0.9221 ce=0.8372 mse=0.1698 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.138357162475586, "reserved_gb": 1.78515625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "49", "gpu_mem_used_mb": "2306", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "80.68"}

predict:   0%|          | 0/311 [00:00<?, ?it/s]

2026-08-09 12:08:58 | INFO | Epoch 05 task=Ses05M train_loss=0.9600 val_macro_f1=0.4066 val_mae=0.5650 epoch_seconds=532.7

epoch 6:   0%|          | 0/2365 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 12:09:16 | INFO | train task=Ses05M epoch=6 batch=60/2365 step=2975 loss=0.0992 ce=0.0430 mse=0.1124 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1398096084594727, "reserved_gb": 1.80078125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "16", "gpu_mem_used_mb": "2322", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "82.31"}
2026-08-09 12:09:34 | INFO | train task=Ses05M epoch=6 batch=160/2365 step=3000 loss=0.3592 ce=0.3173 mse=0.0838 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.138291358947754, "reserved_gb": 1.828125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "31", "gpu_mem_used_mb": "2350", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "67.76"}
2026-08-09 12:10:00 | INFO | train task=Ses05M epoch=6 batch=260/2365 step=3025 loss=0.5285 ce=0.4805 mse=0.0958 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1389031410217285, "reserved_gb": 1.798828125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "2320", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "74.72"}
2026-08-09 12:10:20 | INFO | train task=Ses05M epoch=6 batch=360/2365 step=3050 loss=0.0883 ce=0.0733 mse=0.0299 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.140061378479004, "reserved_gb": 1.78125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "37", "gpu_mem_used_mb": "2302", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "72.21"}
2026-08-09 12:10:39 | INFO | train task=Ses05M epoch=6 batch=460/2365 step=3075 loss=0.7597 ce=0.7012 mse=0.1170 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1401333808898926, "reserved_gb": 2.078125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "23", "gpu_mem_used_mb": "2606", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "55.53"}
2026-08-09 12:10:59 | INFO | train task=Ses05M epoch=6 batch=560/2365 step=3100 loss=0.4553 ce=0.2669 mse=0.3768 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.138808250427246, "reserved_gb": 1.615234375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "63", "gpu_mem_used_mb": "2132", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "65.64"}
2026-08-09 12:11:21 | INFO | train task=Ses05M epoch=6 batch=660/2365 step=3125 loss=0.5179 ce=0.3269 mse=0.3820 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1387720108032227, "reserved_gb": 1.919921875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "33", "gpu_mem_used_mb": "2444", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "67.69"}
2026-08-09 12:11:41 | INFO | train task=Ses05M epoch=6 batch=760/2365 step=3150 loss=1.9154 ce=1.8353 mse=0.1603 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1428823471069336, "reserved_gb": 2.08203125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "2610", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "66.57"}
2026-08-09 12:12:01 | INFO | train task=Ses05M epoch=6 batch=860/2365 step=3175 loss=1.8197 ce=1.4592 mse=0.7211 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1397504806518555, "reserved_gb": 1.826171875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "27", "gpu_mem_used_mb": "2348", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "65.96"}
2026-08-09 12:12:21 | INFO | train task=Ses05M epoch=6 batch=960/2365 step=3200 loss=0.5467 ce=0.3179 mse=0.4576 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.139765739440918, "reserved_gb": 1.8203125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "25", "gpu_mem_used_mb": "2342", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "67.16"}
2026-08-09 12:12:44 | INFO | train task=Ses05M epoch=6 batch=1060/2365 step=3225 loss=1.3599 ce=0.0285 mse=2.6628 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1389904022216797, "reserved_gb": 2.513671875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "16", "gpu_mem_used_mb": "3052", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "66.19"}
2026-08-09 12:13:05 | INFO | train task=Ses05M epoch=6 batch=1160/2365 step=3250 loss=0.2968 ce=0.2876 mse=0.0183 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1386594772338867, "reserved_gb": 1.814453125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "2390", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "61.62"}
2026-08-09 12:13:25 | INFO | train task=Ses05M epoch=6 batch=1260/2365 step=3275 loss=0.7896 ce=0.7788 mse=0.0217 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1400294303894043, "reserved_gb": 1.845703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "40", "gpu_mem_used_mb": "2422", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "86.78"}
2026-08-09 12:13:45 | INFO | train task=Ses05M epoch=6 batch=1360/2365 step=3300 loss=0.3485 ce=0.2234 mse=0.2503 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1399097442626953, "reserved_gb": 1.767578125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "49", "gpu_mem_used_mb": "2342", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "66.95"}
2026-08-09 12:14:09 | INFO | train task=Ses05M epoch=6 batch=1460/2365 step=3325 loss=1.1391 ce=0.6794 mse=0.9195 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1385993957519531, "reserved_gb": 1.83203125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "23", "gpu_mem_used_mb": "2408", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "68.37"}
2026-08-09 12:14:29 | INFO | train task=Ses05M epoch=6 batch=1560/2365 step=3350 loss=0.4399 ce=0.1718 mse=0.5362 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1384716033935547, "reserved_gb": 1.724609375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "2298", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "82.24"}
2026-08-09 12:14:51 | INFO | train task=Ses05M epoch=6 batch=1660/2365 step=3375 loss=0.5395 ce=0.5101 mse=0.0587 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1387181282043457, "reserved_gb": 1.814453125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "2390", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "89.76"}
2026-08-09 12:15:13 | INFO | train task=Ses05M epoch=6 batch=1760/2365 step=3400 loss=0.2630 ce=0.2224 mse=0.0811 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1387219429016113, "reserved_gb": 1.806640625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "76", "gpu_mem_used_mb": "2382", "gpu_mem_total_mb": "12288", "gpu_temp_c": "54", "gpu_power_w": "93.36"}
2026-08-09 12:15:37 | INFO | train task=Ses05M epoch=6 batch=1860/2365 step=3425 loss=1.1702 ce=1.0013 mse=0.3379 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1385273933410645, "reserved_gb": 1.63671875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "73", "gpu_mem_used_mb": "2208", "gpu_mem_total_mb": "12288", "gpu_temp_c": "53", "gpu_power_w": "71.59"}
2026-08-09 12:15:57 | INFO | train task=Ses05M epoch=6 batch=1960/2365 step=3450 loss=0.3393 ce=0.1268 mse=0.4250 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1399493217468262, "reserved_gb": 1.84375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "50", "gpu_mem_used_mb": "2420", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "60.41"}
2026-08-09 12:16:21 | INFO | train task=Ses05M epoch=6 batch=2060/2365 step=3475 loss=1.5438 ce=0.9761 mse=1.1355 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1386384963989258, "reserved_gb": 1.638671875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "2210", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "72.13"}
2026-08-09 12:16:43 | INFO | train task=Ses05M epoch=6 batch=2160/2365 step=3500 loss=0.4963 ce=0.3957 mse=0.2013 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1401715278625488, "reserved_gb": 1.84375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "30", "gpu_mem_used_mb": "2420", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "81.60"}
2026-08-09 12:17:09 | INFO | train task=Ses05M epoch=6 batch=2260/2365 step=3525 loss=0.7185 ce=0.5099 mse=0.4172 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1382732391357422, "reserved_gb": 1.744140625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "62", "gpu_mem_used_mb": "2318", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "85.10"}
2026-08-09 12:17:31 | INFO | train task=Ses05M epoch=6 batch=2360/2365 step=3550 loss=0.9734 ce=0.8170 mse=0.3127 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1395277976989746, "reserved_gb": 1.740234375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "29", "gpu_mem_used_mb": "2314", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "77.15"}

predict:   0%|          | 0/311 [00:00<?, ?it/s]

2026-08-09 12:17:52 | INFO | Epoch 06 task=Ses05M train_loss=0.8551 val_macro_f1=0.3858 val_mae=0.6039 epoch_seconds=528.8

epoch 7:   0%|          | 0/2365 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 12:18:14 | INFO | train task=Ses05M epoch=7 batch=92/2365 step=3575 loss=0.8803 ce=0.7896 mse=0.1813 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1387782096862793, "reserved_gb": 1.8046875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "18", "gpu_mem_used_mb": "2380", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "51.76"}
2026-08-09 12:18:33 | INFO | train task=Ses05M epoch=7 batch=192/2365 step=3600 loss=0.7030 ce=0.5503 mse=0.3054 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1397504806518555, "reserved_gb": 1.880859375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "28", "gpu_mem_used_mb": "2458", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "81.19"}
2026-08-09 12:18:58 | INFO | train task=Ses05M epoch=7 batch=292/2365 step=3625 loss=0.0615 ce=0.0510 mse=0.0210 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.139383316040039, "reserved_gb": 1.849609375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "27", "gpu_mem_used_mb": "2426", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "66.28"}
2026-08-09 12:19:18 | INFO | train task=Ses05M epoch=7 batch=392/2365 step=3650 loss=2.0853 ce=2.0060 mse=0.1587 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1392607688903809, "reserved_gb": 1.7734375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "24", "gpu_mem_used_mb": "2348", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "76.68"}
2026-08-09 12:19:38 | INFO | train task=Ses05M epoch=7 batch=492/2365 step=3675 loss=0.1594 ce=0.1185 mse=0.0817 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1383943557739258, "reserved_gb": 1.703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "26", "gpu_mem_used_mb": "2276", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "53.77"}
2026-08-09 12:19:58 | INFO | train task=Ses05M epoch=7 batch=592/2365 step=3700 loss=0.2812 ce=0.0903 mse=0.3819 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1394357681274414, "reserved_gb": 1.677734375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "34", "gpu_mem_used_mb": "2250", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "49.88"}
2026-08-09 12:20:21 | INFO | train task=Ses05M epoch=7 batch=692/2365 step=3725 loss=0.7691 ce=0.4972 mse=0.5438 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.14013671875, "reserved_gb": 1.8671875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "30", "gpu_mem_used_mb": "2443", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "73.58"}
2026-08-09 12:20:43 | INFO | train task=Ses05M epoch=7 batch=792/2365 step=3750 loss=0.9176 ce=0.7622 mse=0.3109 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1389260292053223, "reserved_gb": 1.72265625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "19", "gpu_mem_used_mb": "2295", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "62.42"}
2026-08-09 12:21:02 | INFO | train task=Ses05M epoch=7 batch=892/2365 step=3775 loss=0.5833 ce=0.4548 mse=0.2569 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1431818008422852, "reserved_gb": 2.11328125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "58", "gpu_mem_used_mb": "2695", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "72.09"}
2026-08-09 12:21:23 | INFO | train task=Ses05M epoch=7 batch=992/2365 step=3800 loss=0.3703 ce=0.0727 mse=0.5952 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.139340877532959, "reserved_gb": 1.853515625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "13", "gpu_mem_used_mb": "2429", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "70.70"}
2026-08-09 12:21:46 | INFO | train task=Ses05M epoch=7 batch=1092/2365 step=3825 loss=0.3781 ce=0.2789 mse=0.1985 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1382951736450195, "reserved_gb": 1.865234375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "2441", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "54.94"}
2026-08-09 12:22:07 | INFO | train task=Ses05M epoch=7 batch=1192/2365 step=3850 loss=0.2224 ce=0.0808 mse=0.2831 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1400585174560547, "reserved_gb": 2.1171875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "2699", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "79.24"}
2026-08-09 12:22:28 | INFO | train task=Ses05M epoch=7 batch=1292/2365 step=3875 loss=0.2697 ce=0.1646 mse=0.2101 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.138279914855957, "reserved_gb": 1.625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "2194", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "75.38"}
2026-08-09 12:22:50 | INFO | train task=Ses05M epoch=7 batch=1392/2365 step=3900 loss=1.0590 ce=0.6913 mse=0.7352 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.13922119140625, "reserved_gb": 1.748046875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "28", "gpu_mem_used_mb": "2320", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "69.74"}
2026-08-09 12:23:13 | INFO | train task=Ses05M epoch=7 batch=1492/2365 step=3925 loss=0.2338 ce=0.1464 mse=0.1747 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1390643119812012, "reserved_gb": 1.685546875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "23", "gpu_mem_used_mb": "2256", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "90.68"}
2026-08-09 12:23:35 | INFO | train task=Ses05M epoch=7 batch=1592/2365 step=3950 loss=0.6437 ce=0.5793 mse=0.1288 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1393694877624512, "reserved_gb": 1.708984375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "80", "gpu_mem_used_mb": "2280", "gpu_mem_total_mb": "12288", "gpu_temp_c": "55", "gpu_power_w": "88.77"}
2026-08-09 12:23:58 | INFO | train task=Ses05M epoch=7 batch=1692/2365 step=3975 loss=0.3042 ce=0.2908 mse=0.0268 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1399612426757812, "reserved_gb": 1.794921875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "16", "gpu_mem_used_mb": "2368", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "70.47"}
2026-08-09 12:24:18 | INFO | train task=Ses05M epoch=7 batch=1792/2365 step=4000 loss=0.1225 ce=0.1220 mse=0.0009 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1382217407226562, "reserved_gb": 1.810546875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "25", "gpu_mem_used_mb": "2384", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "69.54"}
2026-08-09 12:24:42 | INFO | train task=Ses05M epoch=7 batch=1892/2365 step=4025 loss=1.5292 ce=0.6555 mse=1.7475 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1383171081542969, "reserved_gb": 1.765625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "18", "gpu_mem_used_mb": "2337", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "84.09"}
2026-08-09 12:25:05 | INFO | train task=Ses05M epoch=7 batch=1992/2365 step=4050 loss=0.9920 ce=0.8654 mse=0.2532 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1389403343200684, "reserved_gb": 1.74609375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "18", "gpu_mem_used_mb": "2317", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "66.43"}
2026-08-09 12:25:27 | INFO | train task=Ses05M epoch=7 batch=2092/2365 step=4075 loss=0.0969 ce=0.0668 mse=0.0601 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.138878345489502, "reserved_gb": 1.88671875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "2461", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "74.20"}
2026-08-09 12:25:50 | INFO | train task=Ses05M epoch=7 batch=2192/2365 step=4100 loss=1.9386 ce=1.9292 mse=0.0188 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.139183521270752, "reserved_gb": 1.775390625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "34", "gpu_mem_used_mb": "2347", "gpu_mem_total_mb": "12288", "gpu_temp_c": "53", "gpu_power_w": "86.99"}
2026-08-09 12:26:15 | INFO | train task=Ses05M epoch=7 batch=2292/2365 step=4125 loss=1.2912 ce=1.2287 mse=0.1251 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.139462947845459, "reserved_gb": 1.822265625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "26", "gpu_mem_used_mb": "2395", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "82.86"}

predict:   0%|          | 0/311 [00:00<?, ?it/s]

2026-08-09 12:26:52 | INFO | Epoch 07 task=Ses05M train_loss=0.7599 val_macro_f1=0.3869 val_mae=0.5814 epoch_seconds=536.9

predict:   0%|          | 0/266 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)

predict:   0%|          | 0/442 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
2026-08-09 12:28:34 | INFO | Task 182d0b3b72ef6788_main_fold -> complete
2026-08-09 12:28:35 | INFO | Manuscript outputs refreshed: 21 tables, 4 figures
2026-08-09 12:28:35 | INFO | Task def600f0152ffe25_main_fold -> running
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\transformers\configuration_utils.py:335: UserWarning: Passing `gradient_checkpointing` to a config initialization is deprecated and will be removed in v5 Transformers. Using `model.gradient_checkpointing_enable()` instead, or if you are using the `Trainer` API, pass `gradient_checkpointing=True` in your `TrainingArguments`.
  warnings.warn(
2026-08-09 12:28:38 | INFO | Task C:\Users\HaseebWajid\Downloads\runs\dersx_paper_aligned\campaign_01\main\seed_47\Ses01F parameters={'total': 163009451, 'trainable': 69034283, 'frozen': 93975168} scope={'corpus': 'IEMOCAP', 'protocol': 'strict_LOSO', 'heldout_speaker': 'Ses01F', 'seed': 47, 'stage': 'main', 'profile': 'rtx3060_24h'}

epoch 1:   0%|          | 0/2413 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 12:29:03 | INFO | train task=Ses01F epoch=1 batch=100/2413 step=25 loss=3.4872 ce=2.1940 mse=2.5864 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2589001655578613, "reserved_gb": 2.98046875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "28", "gpu_mem_used_mb": "3552", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "73.71"}
2026-08-09 12:29:26 | INFO | train task=Ses01F epoch=1 batch=200/2413 step=50 loss=2.3686 ce=2.1592 mse=0.4188 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2588729858398438, "reserved_gb": 2.830078125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "25", "gpu_mem_used_mb": "3398", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "76.49"}
2026-08-09 12:29:49 | INFO | train task=Ses01F epoch=1 batch=300/2413 step=75 loss=2.2915 ce=2.1349 mse=0.3133 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2587790489196777, "reserved_gb": 2.869140625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "48", "gpu_mem_used_mb": "3437", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "61.44"}
2026-08-09 12:30:13 | INFO | train task=Ses01F epoch=1 batch=400/2413 step=100 loss=2.2168 ce=2.0503 mse=0.3331 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.258850574493408, "reserved_gb": 2.833984375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "37", "gpu_mem_used_mb": "3401", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "74.27"}
2026-08-09 12:30:39 | INFO | train task=Ses01F epoch=1 batch=500/2413 step=125 loss=2.7995 ce=1.9065 mse=1.7859 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.258962631225586, "reserved_gb": 2.83984375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "46", "gpu_mem_used_mb": "3407", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "59.12"}
2026-08-09 12:31:00 | INFO | train task=Ses01F epoch=1 batch=600/2413 step=150 loss=2.1613 ce=1.7555 mse=0.8115 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2637815475463867, "reserved_gb": 2.900390625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "79", "gpu_mem_used_mb": "3469", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "61.94"}
2026-08-09 12:31:24 | INFO | train task=Ses01F epoch=1 batch=700/2413 step=175 loss=1.6318 ce=1.5698 mse=0.1240 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.259549617767334, "reserved_gb": 2.783203125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "34", "gpu_mem_used_mb": "3349", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "75.68"}
2026-08-09 12:31:47 | INFO | train task=Ses01F epoch=1 batch=800/2413 step=200 loss=1.7755 ce=1.7129 mse=0.1253 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2641239166259766, "reserved_gb": 2.935546875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "72", "gpu_mem_used_mb": "3505", "gpu_mem_total_mb": "12288", "gpu_temp_c": "53", "gpu_power_w": "80.36"}
2026-08-09 12:32:16 | INFO | train task=Ses01F epoch=1 batch=900/2413 step=225 loss=1.6536 ce=1.5577 mse=0.1917 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2617311477661133, "reserved_gb": 2.888671875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "57", "gpu_mem_used_mb": "3456", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "53.78"}
2026-08-09 12:32:39 | INFO | train task=Ses01F epoch=1 batch=1000/2413 step=250 loss=1.8247 ce=1.7340 mse=0.1814 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2594871520996094, "reserved_gb": 2.787109375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "44", "gpu_mem_used_mb": "3352", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "74.21"}
2026-08-09 12:33:04 | INFO | train task=Ses01F epoch=1 batch=1100/2413 step=275 loss=2.2379 ce=1.5977 mse=1.2804 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.258726119995117, "reserved_gb": 2.884765625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "26", "gpu_mem_used_mb": "3452", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "72.20"}
2026-08-09 12:33:26 | INFO | train task=Ses01F epoch=1 batch=1200/2413 step=300 loss=1.3572 ce=1.3105 mse=0.0933 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.259563446044922, "reserved_gb": 2.90234375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "3470", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "64.32"}
2026-08-09 12:33:53 | INFO | train task=Ses01F epoch=1 batch=1300/2413 step=325 loss=1.7161 ce=1.6204 mse=0.1913 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2602715492248535, "reserved_gb": 2.84765625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "25", "gpu_mem_used_mb": "3414", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "91.33"}
2026-08-09 12:34:16 | INFO | train task=Ses01F epoch=1 batch=1400/2413 step=350 loss=1.2668 ce=1.2030 mse=0.1277 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2587246894836426, "reserved_gb": 2.91796875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "71", "gpu_mem_used_mb": "3485", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "67.82"}
2026-08-09 12:34:41 | INFO | train task=Ses01F epoch=1 batch=1500/2413 step=375 loss=1.3719 ce=1.2484 mse=0.2470 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.259754180908203, "reserved_gb": 2.84375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "32", "gpu_mem_used_mb": "3409", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "72.35"}
2026-08-09 12:35:05 | INFO | train task=Ses01F epoch=1 batch=1600/2413 step=400 loss=2.3728 ce=1.6606 mse=1.4244 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.259270191192627, "reserved_gb": 2.8984375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "51", "gpu_mem_used_mb": "3465", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "81.52"}
2026-08-09 12:35:31 | INFO | train task=Ses01F epoch=1 batch=1700/2413 step=425 loss=1.7863 ce=1.5145 mse=0.5436 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2594833374023438, "reserved_gb": 2.84765625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "28", "gpu_mem_used_mb": "3413", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "47.79"}
2026-08-09 12:35:54 | INFO | train task=Ses01F epoch=1 batch=1800/2413 step=450 loss=1.4506 ce=1.3379 mse=0.2254 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2593417167663574, "reserved_gb": 2.91796875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "24", "gpu_mem_used_mb": "3485", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "59.03"}
2026-08-09 12:36:17 | INFO | train task=Ses01F epoch=1 batch=1900/2413 step=475 loss=4.5428 ce=3.9657 mse=1.1541 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.258909225463867, "reserved_gb": 3.046875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "3616", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "69.52"}
2026-08-09 12:36:40 | INFO | train task=Ses01F epoch=1 batch=2000/2413 step=500 loss=0.9514 ce=0.5077 mse=0.8874 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2587876319885254, "reserved_gb": 3.1015625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "67", "gpu_mem_used_mb": "3672", "gpu_mem_total_mb": "12288", "gpu_temp_c": "56", "gpu_power_w": "128.99"}
2026-08-09 12:37:07 | INFO | train task=Ses01F epoch=1 batch=2100/2413 step=525 loss=1.4467 ce=1.3918 mse=0.1099 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2591094970703125, "reserved_gb": 2.845703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "18", "gpu_mem_used_mb": "3410", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "63.01"}
2026-08-09 12:37:30 | INFO | train task=Ses01F epoch=1 batch=2200/2413 step=550 loss=0.8651 ce=0.8242 mse=0.0817 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2593297958374023, "reserved_gb": 2.89453125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "28", "gpu_mem_used_mb": "3460", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "74.46"}
2026-08-09 12:37:53 | INFO | train task=Ses01F epoch=1 batch=2300/2413 step=575 loss=1.6276 ce=1.2614 mse=0.7324 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.259457588195801, "reserved_gb": 2.919921875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "19", "gpu_mem_used_mb": "3486", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "88.67"}
2026-08-09 12:38:16 | INFO | train task=Ses01F epoch=1 batch=2400/2413 step=600 loss=1.9349 ce=1.8332 mse=0.2033 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.25948429107666, "reserved_gb": 2.896484375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "18", "gpu_mem_used_mb": "3461", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "62.36"}

predict:   0%|          | 0/304 [00:00<?, ?it/s]

2026-08-09 12:39:03 | INFO | Epoch 01 task=Ses01F train_loss=2.0670 val_macro_f1=0.4590 val_mae=0.5047 epoch_seconds=624.2

epoch 2:   0%|          | 0/2413 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 12:39:25 | INFO | train task=Ses01F epoch=2 batch=84/2413 step=625 loss=1.8641 ce=1.6148 mse=0.4985 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2590417861938477, "reserved_gb": 2.8359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "13", "gpu_mem_used_mb": "3399", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "65.50"}
2026-08-09 12:39:46 | INFO | train task=Ses01F epoch=2 batch=184/2413 step=650 loss=1.2730 ce=0.7231 mse=1.0997 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2600841522216797, "reserved_gb": 3.076171875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "25", "gpu_mem_used_mb": "3645", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "74.71"}
2026-08-09 12:40:05 | INFO | train task=Ses01F epoch=2 batch=284/2413 step=675 loss=1.0910 ce=0.9682 mse=0.2456 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.261970043182373, "reserved_gb": 3.177734375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "40", "gpu_mem_used_mb": "3749", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "70.23"}
2026-08-09 12:40:24 | INFO | train task=Ses01F epoch=2 batch=384/2413 step=700 loss=1.5725 ce=1.1352 mse=0.8746 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2590584754943848, "reserved_gb": 3.474609375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "19", "gpu_mem_used_mb": "4052", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "62.25"}
2026-08-09 12:40:48 | INFO | train task=Ses01F epoch=2 batch=484/2413 step=725 loss=2.5276 ce=2.3121 mse=0.4310 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.261524200439453, "reserved_gb": 3.49609375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "23", "gpu_mem_used_mb": "4074", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "70.70"}
2026-08-09 12:41:08 | INFO | train task=Ses01F epoch=2 batch=584/2413 step=750 loss=2.1308 ce=1.9414 mse=0.3787 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2595839500427246, "reserved_gb": 3.306640625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "3880", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "69.77"}
2026-08-09 12:41:30 | INFO | train task=Ses01F epoch=2 batch=684/2413 step=775 loss=0.9873 ce=0.8788 mse=0.2169 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.260160446166992, "reserved_gb": 2.853515625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "69", "gpu_mem_used_mb": "3416", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "66.31"}
2026-08-09 12:41:51 | INFO | train task=Ses01F epoch=2 batch=784/2413 step=800 loss=1.3591 ce=1.2251 mse=0.2680 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.260450839996338, "reserved_gb": 2.837890625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "16", "gpu_mem_used_mb": "3400", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "61.44"}
2026-08-09 12:42:15 | INFO | train task=Ses01F epoch=2 batch=884/2413 step=825 loss=1.4954 ce=1.0890 mse=0.8129 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2596092224121094, "reserved_gb": 2.828125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "39", "gpu_mem_used_mb": "3390", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "73.89"}
2026-08-09 12:42:36 | INFO | train task=Ses01F epoch=2 batch=984/2413 step=850 loss=1.8878 ce=1.8845 mse=0.0064 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2616496086120605, "reserved_gb": 2.873046875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "29", "gpu_mem_used_mb": "3435", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "74.00"}
2026-08-09 12:42:59 | INFO | train task=Ses01F epoch=2 batch=1084/2413 step=875 loss=0.7308 ce=0.4069 mse=0.6477 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.259451389312744, "reserved_gb": 2.884765625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "30", "gpu_mem_used_mb": "3447", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "77.18"}
2026-08-09 12:43:19 | INFO | train task=Ses01F epoch=2 batch=1184/2413 step=900 loss=1.5011 ce=1.4883 mse=0.0256 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.258906841278076, "reserved_gb": 2.8359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "55", "gpu_mem_used_mb": "3397", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "68.96"}
2026-08-09 12:43:44 | INFO | train task=Ses01F epoch=2 batch=1284/2413 step=925 loss=1.8620 ce=1.1125 mse=1.4990 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.259666919708252, "reserved_gb": 3.20703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "24", "gpu_mem_used_mb": "3777", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "66.95"}
2026-08-09 12:44:04 | INFO | train task=Ses01F epoch=2 batch=1384/2413 step=950 loss=1.0124 ce=1.0037 mse=0.0174 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.259291648864746, "reserved_gb": 2.84375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "31", "gpu_mem_used_mb": "3405", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "69.91"}
2026-08-09 12:44:26 | INFO | train task=Ses01F epoch=2 batch=1484/2413 step=975 loss=0.3890 ce=0.2650 mse=0.2480 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.259377956390381, "reserved_gb": 3.17578125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "3745", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "76.46"}
2026-08-09 12:44:47 | INFO | train task=Ses01F epoch=2 batch=1584/2413 step=1000 loss=2.4656 ce=2.4346 mse=0.0621 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2589664459228516, "reserved_gb": 2.89453125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "25", "gpu_mem_used_mb": "3456", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "61.90"}
2026-08-09 12:45:09 | INFO | train task=Ses01F epoch=2 batch=1684/2413 step=1025 loss=1.6295 ce=1.4525 mse=0.3541 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.259064197540283, "reserved_gb": 2.921875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "33", "gpu_mem_used_mb": "3484", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "69.09"}
2026-08-09 12:45:30 | INFO | train task=Ses01F epoch=2 batch=1784/2413 step=1050 loss=0.6916 ce=0.5720 mse=0.2391 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2594823837280273, "reserved_gb": 2.892578125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "19", "gpu_mem_used_mb": "3454", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "68.21"}
2026-08-09 12:45:52 | INFO | train task=Ses01F epoch=2 batch=1884/2413 step=1075 loss=2.8336 ce=2.7769 mse=0.1134 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2591934204101562, "reserved_gb": 3.560546875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "33", "gpu_mem_used_mb": "4138", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "72.34"}
2026-08-09 12:46:16 | INFO | train task=Ses01F epoch=2 batch=1984/2413 step=1100 loss=2.1201 ce=1.5947 mse=1.0507 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2617974281311035, "reserved_gb": 2.880859375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "86", "gpu_mem_used_mb": "3442", "gpu_mem_total_mb": "12288", "gpu_temp_c": "53", "gpu_power_w": "87.74"}
2026-08-09 12:46:40 | INFO | train task=Ses01F epoch=2 batch=2084/2413 step=1125 loss=0.7817 ce=0.7240 mse=0.1153 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2591867446899414, "reserved_gb": 3.44140625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "4015", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "91.07"}
2026-08-09 12:47:03 | INFO | train task=Ses01F epoch=2 batch=2184/2413 step=1150 loss=1.4367 ce=1.4268 mse=0.0199 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.261477470397949, "reserved_gb": 2.876953125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "19", "gpu_mem_used_mb": "3437", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "77.08"}
2026-08-09 12:47:25 | INFO | train task=Ses01F epoch=2 batch=2284/2413 step=1175 loss=0.7265 ce=0.3100 mse=0.8330 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2590274810791016, "reserved_gb": 2.8359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "26", "gpu_mem_used_mb": "3395", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "75.69"}
2026-08-09 12:47:49 | INFO | train task=Ses01F epoch=2 batch=2384/2413 step=1200 loss=1.5918 ce=1.2938 mse=0.5959 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.258930206298828, "reserved_gb": 2.802734375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "27", "gpu_mem_used_mb": "3361", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "68.36"}

predict:   0%|          | 0/304 [00:00<?, ?it/s]

2026-08-09 12:48:31 | INFO | Epoch 02 task=Ses01F train_loss=1.4902 val_macro_f1=0.4988 val_mae=0.4989 epoch_seconds=563.7

epoch 3:   0%|          | 0/2413 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 12:48:52 | INFO | train task=Ses01F epoch=3 batch=68/2413 step=1225 loss=0.5903 ce=0.2368 mse=0.7070 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.259556770324707, "reserved_gb": 4.11328125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "38", "gpu_mem_used_mb": "4533", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "69.14"}
2026-08-09 12:49:12 | INFO | train task=Ses01F epoch=3 batch=168/2413 step=1250 loss=0.7096 ce=0.6730 mse=0.0732 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.260195255279541, "reserved_gb": 2.853515625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "48", "gpu_mem_used_mb": "3243", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "64.45"}
2026-08-09 12:49:32 | INFO | train task=Ses01F epoch=3 batch=268/2413 step=1275 loss=0.6271 ce=0.3280 mse=0.5981 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2594094276428223, "reserved_gb": 2.90234375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "18", "gpu_mem_used_mb": "3331", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "66.81"}
2026-08-09 12:49:53 | INFO | train task=Ses01F epoch=3 batch=368/2413 step=1300 loss=1.4031 ce=1.2666 mse=0.2730 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.259131908416748, "reserved_gb": 3.017578125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "36", "gpu_mem_used_mb": "3449", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "71.18"}
2026-08-09 12:50:16 | INFO | train task=Ses01F epoch=3 batch=468/2413 step=1325 loss=1.2083 ce=0.9990 mse=0.4186 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.258840560913086, "reserved_gb": 3.01171875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "14", "gpu_mem_used_mb": "3448", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "68.19"}
2026-08-09 12:50:36 | INFO | train task=Ses01F epoch=3 batch=568/2413 step=1350 loss=1.2163 ce=0.9725 mse=0.4875 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.259471893310547, "reserved_gb": 2.89453125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "36", "gpu_mem_used_mb": "3328", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "65.99"}
2026-08-09 12:50:55 | INFO | train task=Ses01F epoch=3 batch=668/2413 step=1375 loss=0.5529 ce=0.3955 mse=0.3148 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2591185569763184, "reserved_gb": 2.919921875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "29", "gpu_mem_used_mb": "3354", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "70.61"}
2026-08-09 12:51:16 | INFO | train task=Ses01F epoch=3 batch=768/2413 step=1400 loss=1.9221 ce=1.6666 mse=0.5110 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.258920669555664, "reserved_gb": 2.826171875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "28", "gpu_mem_used_mb": "3258", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "57.15"}
2026-08-09 12:51:39 | INFO | train task=Ses01F epoch=3 batch=868/2413 step=1425 loss=0.6288 ce=0.5514 mse=0.1548 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2599339485168457, "reserved_gb": 3.095703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "19", "gpu_mem_used_mb": "3534", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "66.05"}
2026-08-09 12:52:00 | INFO | train task=Ses01F epoch=3 batch=968/2413 step=1450 loss=0.9755 ce=0.4805 mse=0.9900 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.259481430053711, "reserved_gb": 2.974609375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "3410", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "70.45"}
2026-08-09 12:52:22 | INFO | train task=Ses01F epoch=3 batch=1068/2413 step=1475 loss=0.5345 ce=0.5260 mse=0.0170 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.261793613433838, "reserved_gb": 3.271484375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "28", "gpu_mem_used_mb": "3714", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "89.44"}
2026-08-09 12:52:44 | INFO | train task=Ses01F epoch=3 batch=1168/2413 step=1500 loss=2.0670 ce=1.8428 mse=0.4484 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2588891983032227, "reserved_gb": 2.833984375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "3266", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "66.56"}
2026-08-09 12:53:09 | INFO | train task=Ses01F epoch=3 batch=1268/2413 step=1525 loss=1.2968 ce=1.0256 mse=0.5423 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1400222778320312, "reserved_gb": 1.923828125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "26", "gpu_mem_used_mb": "2334", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "70.62"}
2026-08-09 12:53:29 | INFO | train task=Ses01F epoch=3 batch=1368/2413 step=1550 loss=2.7642 ce=2.1432 mse=1.2420 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.139594554901123, "reserved_gb": 2.85546875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "24", "gpu_mem_used_mb": "3288", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "74.61"}
2026-08-09 12:53:51 | INFO | train task=Ses01F epoch=3 batch=1468/2413 step=1575 loss=1.3786 ce=1.3684 mse=0.0205 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.141204833984375, "reserved_gb": 2.0078125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "36", "gpu_mem_used_mb": "2420", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "85.39"}
2026-08-09 12:54:10 | INFO | train task=Ses01F epoch=3 batch=1568/2413 step=1600 loss=0.6742 ce=0.6100 mse=0.1284 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1401000022888184, "reserved_gb": 2.013671875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "36", "gpu_mem_used_mb": "2426", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "67.77"}
2026-08-09 12:54:33 | INFO | train task=Ses01F epoch=3 batch=1668/2413 step=1625 loss=0.7589 ce=0.5971 mse=0.3235 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1398615837097168, "reserved_gb": 1.923828125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "2334", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "64.69"}
2026-08-09 12:54:54 | INFO | train task=Ses01F epoch=3 batch=1768/2413 step=1650 loss=0.7868 ce=0.7707 mse=0.0322 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.140209674835205, "reserved_gb": 1.99609375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "2408", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "62.47"}
2026-08-09 12:55:16 | INFO | train task=Ses01F epoch=3 batch=1868/2413 step=1675 loss=0.8011 ce=0.5159 mse=0.5705 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1398625373840332, "reserved_gb": 2.017578125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "27", "gpu_mem_used_mb": "2430", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "71.86"}
2026-08-09 12:55:37 | INFO | train task=Ses01F epoch=3 batch=1968/2413 step=1700 loss=0.8563 ce=0.7227 mse=0.2671 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.140584945678711, "reserved_gb": 2.0625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "27", "gpu_mem_used_mb": "2476", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "55.09"}
2026-08-09 12:56:03 | INFO | train task=Ses01F epoch=3 batch=2068/2413 step=1725 loss=1.2927 ce=1.2188 mse=0.1479 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1427130699157715, "reserved_gb": 1.912109375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "37", "gpu_mem_used_mb": "2322", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "60.24"}
2026-08-09 12:56:25 | INFO | train task=Ses01F epoch=3 batch=2168/2413 step=1750 loss=0.9470 ce=0.4887 mse=0.9166 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1403255462646484, "reserved_gb": 2.037109375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "34", "gpu_mem_used_mb": "2450", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "77.61"}
2026-08-09 12:56:46 | INFO | train task=Ses01F epoch=3 batch=2268/2413 step=1775 loss=0.5729 ce=0.5674 mse=0.0111 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1411523818969727, "reserved_gb": 2.001953125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "12", "gpu_mem_used_mb": "2414", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "68.64"}
2026-08-09 12:57:08 | INFO | train task=Ses01F epoch=3 batch=2368/2413 step=1800 loss=1.7510 ce=0.8183 mse=1.8653 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1411237716674805, "reserved_gb": 1.9921875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "14", "gpu_mem_used_mb": "2404", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "72.91"}

predict:   0%|          | 0/304 [00:00<?, ?it/s]

2026-08-09 12:57:40 | INFO | Epoch 03 task=Ses01F train_loss=1.2425 val_macro_f1=0.5506 val_mae=0.5226 epoch_seconds=544.4

epoch 4:   0%|          | 0/2413 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 12:57:57 | INFO | train task=Ses01F epoch=4 batch=52/2413 step=1825 loss=4.9324 ce=4.5809 mse=0.7029 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1402778625488281, "reserved_gb": 2.240234375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "36", "gpu_mem_used_mb": "2658", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "74.14"}
2026-08-09 12:58:17 | INFO | train task=Ses01F epoch=4 batch=152/2413 step=1850 loss=0.9517 ce=0.8726 mse=0.1582 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1399517059326172, "reserved_gb": 2.04296875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "24", "gpu_mem_used_mb": "2522", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "74.46"}
2026-08-09 12:58:37 | INFO | train task=Ses01F epoch=4 batch=252/2413 step=1875 loss=1.8400 ce=1.5207 mse=0.6385 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1396970748901367, "reserved_gb": 1.912109375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "76", "gpu_mem_used_mb": "2388", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "67.38"}
2026-08-09 12:58:57 | INFO | train task=Ses01F epoch=4 batch=352/2413 step=1900 loss=0.8037 ce=0.1678 mse=1.2718 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1397690773010254, "reserved_gb": 2.171875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "29", "gpu_mem_used_mb": "2654", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "72.53"}
2026-08-09 12:59:19 | INFO | train task=Ses01F epoch=4 batch=452/2413 step=1925 loss=0.5989 ce=0.5871 mse=0.0236 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1396141052246094, "reserved_gb": 2.029296875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "19", "gpu_mem_used_mb": "2512", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "53.74"}
2026-08-09 12:59:39 | INFO | train task=Ses01F epoch=4 batch=552/2413 step=1950 loss=0.4330 ce=0.3334 mse=0.1992 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1409473419189453, "reserved_gb": 2.00390625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "44", "gpu_mem_used_mb": "2486", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "65.07"}
2026-08-09 12:59:57 | INFO | train task=Ses01F epoch=4 batch=652/2413 step=1975 loss=0.9322 ce=0.5397 mse=0.7851 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1423468589782715, "reserved_gb": 2.0234375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "2506", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "55.12"}
2026-08-09 13:00:16 | INFO | train task=Ses01F epoch=4 batch=752/2413 step=2000 loss=0.8657 ce=0.5768 mse=0.5778 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1398444175720215, "reserved_gb": 1.923828125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "23", "gpu_mem_used_mb": "2404", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "59.10"}
2026-08-09 13:00:38 | INFO | train task=Ses01F epoch=4 batch=852/2413 step=2025 loss=0.7685 ce=0.6391 mse=0.2588 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1402759552001953, "reserved_gb": 1.998046875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "18", "gpu_mem_used_mb": "2480", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "69.81"}
2026-08-09 13:00:58 | INFO | train task=Ses01F epoch=4 batch=952/2413 step=2050 loss=0.4872 ce=0.4846 mse=0.0052 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1399478912353516, "reserved_gb": 2.02734375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "23", "gpu_mem_used_mb": "2510", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "73.57"}
2026-08-09 13:01:17 | INFO | train task=Ses01F epoch=4 batch=1052/2413 step=2075 loss=1.8769 ce=1.7816 mse=0.1906 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.139739990234375, "reserved_gb": 2.02734375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "36", "gpu_mem_used_mb": "2510", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "64.06"}
2026-08-09 13:01:39 | INFO | train task=Ses01F epoch=4 batch=1152/2413 step=2100 loss=2.3691 ce=2.2099 mse=0.3184 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1399059295654297, "reserved_gb": 1.923828125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "39", "gpu_mem_used_mb": "2404", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "80.65"}
2026-08-09 13:02:03 | INFO | train task=Ses01F epoch=4 batch=1252/2413 step=2125 loss=0.2731 ce=0.1343 mse=0.2776 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1404223442077637, "reserved_gb": 1.919921875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "26", "gpu_mem_used_mb": "2400", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "63.90"}
2026-08-09 13:02:26 | INFO | train task=Ses01F epoch=4 batch=1352/2413 step=2150 loss=0.6722 ce=0.5537 mse=0.2370 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1410107612609863, "reserved_gb": 1.908203125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "28", "gpu_mem_used_mb": "2387", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "53.89"}
2026-08-09 13:02:47 | INFO | train task=Ses01F epoch=4 batch=1452/2413 step=2175 loss=1.0488 ce=0.9456 mse=0.2065 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1424751281738281, "reserved_gb": 1.912109375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "65", "gpu_mem_used_mb": "2391", "gpu_mem_total_mb": "12288", "gpu_temp_c": "53", "gpu_power_w": "75.83"}
2026-08-09 13:03:08 | INFO | train task=Ses01F epoch=4 batch=1552/2413 step=2200 loss=0.5953 ce=0.4270 mse=0.3367 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.139695167541504, "reserved_gb": 2.0546875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "28", "gpu_mem_used_mb": "2537", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "67.81"}
2026-08-09 13:03:33 | INFO | train task=Ses01F epoch=4 batch=1652/2413 step=2225 loss=1.2166 ce=0.9951 mse=0.4431 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1398677825927734, "reserved_gb": 1.919921875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "2399", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "80.49"}
2026-08-09 13:03:54 | INFO | train task=Ses01F epoch=4 batch=1752/2413 step=2250 loss=0.7661 ce=0.4045 mse=0.7231 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1397466659545898, "reserved_gb": 1.9921875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "29", "gpu_mem_used_mb": "2474", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "83.35"}
2026-08-09 13:04:15 | INFO | train task=Ses01F epoch=4 batch=1852/2413 step=2275 loss=0.4462 ce=0.2748 mse=0.3427 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1415295600891113, "reserved_gb": 2.091796875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "47", "gpu_mem_used_mb": "2576", "gpu_mem_total_mb": "12288", "gpu_temp_c": "53", "gpu_power_w": "78.74"}
2026-08-09 13:04:36 | INFO | train task=Ses01F epoch=4 batch=1952/2413 step=2300 loss=0.2409 ce=0.0986 mse=0.2846 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.140486717224121, "reserved_gb": 2.00390625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "32", "gpu_mem_used_mb": "2486", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "62.92"}
2026-08-09 13:04:59 | INFO | train task=Ses01F epoch=4 batch=2052/2413 step=2325 loss=1.7292 ce=1.4971 mse=0.4642 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.139660358428955, "reserved_gb": 1.91015625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "18", "gpu_mem_used_mb": "2393", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "68.66"}
2026-08-09 13:05:21 | INFO | train task=Ses01F epoch=4 batch=2152/2413 step=2350 loss=1.7344 ce=1.6899 mse=0.0891 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1394743919372559, "reserved_gb": 1.923828125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "18", "gpu_mem_used_mb": "2407", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "67.84"}
2026-08-09 13:05:44 | INFO | train task=Ses01F epoch=4 batch=2252/2413 step=2375 loss=0.7572 ce=0.5988 mse=0.3167 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1401786804199219, "reserved_gb": 1.916015625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "16", "gpu_mem_used_mb": "2399", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "89.53"}
2026-08-09 13:06:05 | INFO | train task=Ses01F epoch=4 batch=2352/2413 step=2400 loss=2.5995 ce=2.4477 mse=0.3035 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.139702320098877, "reserved_gb": 1.923828125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "23", "gpu_mem_used_mb": "2407", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "72.29"}

predict:   0%|          | 0/304 [00:00<?, ?it/s]

2026-08-09 13:06:40 | INFO | Epoch 04 task=Ses01F train_loss=1.0614 val_macro_f1=0.5586 val_mae=0.5278 epoch_seconds=534.7

epoch 5:   0%|          | 0/2413 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 13:06:52 | INFO | train task=Ses01F epoch=5 batch=36/2413 step=2425 loss=0.8681 ce=0.8590 mse=0.0181 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1410369873046875, "reserved_gb": 1.91796875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "47", "gpu_mem_used_mb": "2380", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "73.65"}
2026-08-09 13:07:12 | INFO | train task=Ses01F epoch=5 batch=136/2413 step=2450 loss=0.6874 ce=0.5513 mse=0.2721 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1423969268798828, "reserved_gb": 2.037109375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "25", "gpu_mem_used_mb": "2502", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "63.67"}
2026-08-09 13:07:31 | INFO | train task=Ses01F epoch=5 batch=236/2413 step=2475 loss=0.2339 ce=0.1521 mse=0.1636 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1402406692504883, "reserved_gb": 2.001953125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "23", "gpu_mem_used_mb": "2466", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "67.92"}
2026-08-09 13:07:49 | INFO | train task=Ses01F epoch=5 batch=336/2413 step=2500 loss=0.3024 ce=0.2858 mse=0.0331 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1403913497924805, "reserved_gb": 2.013671875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "30", "gpu_mem_used_mb": "2478", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "54.33"}
2026-08-09 13:08:10 | INFO | train task=Ses01F epoch=5 batch=436/2413 step=2525 loss=0.1999 ce=0.1206 mse=0.1585 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1405987739562988, "reserved_gb": 1.904296875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "23", "gpu_mem_used_mb": "2366", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "72.48"}
2026-08-09 13:08:28 | INFO | train task=Ses01F epoch=5 batch=536/2413 step=2550 loss=2.8888 ce=2.4272 mse=0.9231 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1397409439086914, "reserved_gb": 2.05078125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "23", "gpu_mem_used_mb": "2516", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "64.63"}
2026-08-09 13:08:47 | INFO | train task=Ses01F epoch=5 batch=636/2413 step=2575 loss=0.7188 ce=0.5582 mse=0.3212 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1401686668395996, "reserved_gb": 2.017578125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "18", "gpu_mem_used_mb": "2482", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "56.88"}
2026-08-09 13:09:07 | INFO | train task=Ses01F epoch=5 batch=736/2413 step=2600 loss=0.9590 ce=0.6736 mse=0.5709 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.141146183013916, "reserved_gb": 2.03515625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "38", "gpu_mem_used_mb": "2499", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "62.54"}
2026-08-09 13:09:29 | INFO | train task=Ses01F epoch=5 batch=836/2413 step=2625 loss=0.4342 ce=0.4032 mse=0.0619 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1401443481445312, "reserved_gb": 2.03125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "32", "gpu_mem_used_mb": "2495", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "96.79"}
2026-08-09 13:09:50 | INFO | train task=Ses01F epoch=5 batch=936/2413 step=2650 loss=0.3196 ce=0.0708 mse=0.4975 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1408276557922363, "reserved_gb": 2.01953125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "2483", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "77.35"}
2026-08-09 13:10:10 | INFO | train task=Ses01F epoch=5 batch=1036/2413 step=2675 loss=2.3707 ce=1.9831 mse=0.7751 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.140261173248291, "reserved_gb": 2.03125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "2549", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "65.90"}
2026-08-09 13:10:31 | INFO | train task=Ses01F epoch=5 batch=1136/2413 step=2700 loss=0.4109 ce=0.1472 mse=0.5274 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1458969116210938, "reserved_gb": 2.888671875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "67", "gpu_mem_used_mb": "3427", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "82.25"}
2026-08-09 13:10:54 | INFO | train task=Ses01F epoch=5 batch=1236/2413 step=2725 loss=0.7181 ce=0.4104 mse=0.6155 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.139838695526123, "reserved_gb": 1.923828125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "2439", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "64.24"}
2026-08-09 13:11:15 | INFO | train task=Ses01F epoch=5 batch=1336/2413 step=2750 loss=0.3791 ce=0.3702 mse=0.0178 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1400046348571777, "reserved_gb": 2.060546875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "51", "gpu_mem_used_mb": "2579", "gpu_mem_total_mb": "12288", "gpu_temp_c": "54", "gpu_power_w": "84.03"}
2026-08-09 13:11:36 | INFO | train task=Ses01F epoch=5 batch=1436/2413 step=2775 loss=0.4157 ce=0.3004 mse=0.2306 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1408967971801758, "reserved_gb": 1.908203125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "31", "gpu_mem_used_mb": "2423", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "70.00"}
2026-08-09 13:11:55 | INFO | train task=Ses01F epoch=5 batch=1536/2413 step=2800 loss=0.4863 ce=0.3808 mse=0.2110 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1399245262145996, "reserved_gb": 1.923828125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "25", "gpu_mem_used_mb": "2439", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "73.03"}
2026-08-09 13:12:19 | INFO | train task=Ses01F epoch=5 batch=1636/2413 step=2825 loss=0.5723 ce=0.4677 mse=0.2093 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1411876678466797, "reserved_gb": 2.01953125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "12", "gpu_mem_used_mb": "2536", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "59.47"}
2026-08-09 13:12:39 | INFO | train task=Ses01F epoch=5 batch=1736/2413 step=2850 loss=0.4125 ce=0.3803 mse=0.0643 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1395654678344727, "reserved_gb": 1.90625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "2420", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "64.09"}
2026-08-09 13:13:00 | INFO | train task=Ses01F epoch=5 batch=1836/2413 step=2875 loss=1.9149 ce=1.8511 mse=0.1276 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1416254043579102, "reserved_gb": 1.912109375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "42", "gpu_mem_used_mb": "2426", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "85.59"}
2026-08-09 13:13:22 | INFO | train task=Ses01F epoch=5 batch=1936/2413 step=2900 loss=0.2902 ce=0.2081 mse=0.1643 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1400251388549805, "reserved_gb": 1.923828125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "2438", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "84.71"}
2026-08-09 13:13:46 | INFO | train task=Ses01F epoch=5 batch=2036/2413 step=2925 loss=0.6502 ce=0.6456 mse=0.0091 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1405320167541504, "reserved_gb": 1.904296875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "49", "gpu_mem_used_mb": "2418", "gpu_mem_total_mb": "12288", "gpu_temp_c": "54", "gpu_power_w": "72.32"}
2026-08-09 13:14:08 | INFO | train task=Ses01F epoch=5 batch=2136/2413 step=2950 loss=1.0482 ce=0.9197 mse=0.2571 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1399245262145996, "reserved_gb": 2.03515625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "16", "gpu_mem_used_mb": "2552", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "64.08"}
2026-08-09 13:14:28 | INFO | train task=Ses01F epoch=5 batch=2236/2413 step=2975 loss=0.7493 ce=0.7158 mse=0.0671 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1401729583740234, "reserved_gb": 1.90234375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "16", "gpu_mem_used_mb": "2416", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "81.59"}
2026-08-09 13:14:49 | INFO | train task=Ses01F epoch=5 batch=2336/2413 step=3000 loss=0.4081 ce=0.3084 mse=0.1993 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1396894454956055, "reserved_gb": 1.912109375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "19", "gpu_mem_used_mb": "2426", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "68.99"}

predict:   0%|          | 0/304 [00:00<?, ?it/s]

2026-08-09 13:15:28 | INFO | Epoch 05 task=Ses01F train_loss=0.9318 val_macro_f1=0.5417 val_mae=0.4976 epoch_seconds=522.8

epoch 6:   0%|          | 0/2413 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 13:15:35 | INFO | train task=Ses01F epoch=6 batch=20/2413 step=3025 loss=0.8477 ce=0.3682 mse=0.9590 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1416854858398438, "reserved_gb": 2.0078125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "37", "gpu_mem_used_mb": "2523", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "54.14"}
2026-08-09 13:15:54 | INFO | train task=Ses01F epoch=6 batch=120/2413 step=3050 loss=0.5480 ce=0.4142 mse=0.2675 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1395368576049805, "reserved_gb": 2.056640625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "16", "gpu_mem_used_mb": "2573", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "62.80"}
2026-08-09 13:16:13 | INFO | train task=Ses01F epoch=6 batch=220/2413 step=3075 loss=0.4885 ce=0.3554 mse=0.2663 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1398024559020996, "reserved_gb": 2.046875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "2563", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "65.09"}
2026-08-09 13:16:31 | INFO | train task=Ses01F epoch=6 batch=320/2413 step=3100 loss=0.2330 ce=0.1510 mse=0.1640 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1396574974060059, "reserved_gb": 2.00390625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "32", "gpu_mem_used_mb": "2519", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "59.46"}
2026-08-09 13:16:54 | INFO | train task=Ses01F epoch=6 batch=420/2413 step=3125 loss=0.5553 ce=0.2169 mse=0.6768 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1396360397338867, "reserved_gb": 2.048828125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "47", "gpu_mem_used_mb": "2565", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "67.85"}
2026-08-09 13:17:13 | INFO | train task=Ses01F epoch=6 batch=520/2413 step=3150 loss=0.2804 ce=0.2405 mse=0.0798 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.139838695526123, "reserved_gb": 2.037109375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "2553", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "69.87"}
2026-08-09 13:17:33 | INFO | train task=Ses01F epoch=6 batch=620/2413 step=3175 loss=0.1454 ce=0.0632 mse=0.1644 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1414527893066406, "reserved_gb": 2.02734375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "29", "gpu_mem_used_mb": "2542", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "75.03"}
2026-08-09 13:17:52 | INFO | train task=Ses01F epoch=6 batch=720/2413 step=3200 loss=1.5195 ce=1.2212 mse=0.5966 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.140425205230713, "reserved_gb": 2.041015625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "25", "gpu_mem_used_mb": "2556", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "72.29"}
2026-08-09 13:18:15 | INFO | train task=Ses01F epoch=6 batch=820/2413 step=3225 loss=1.1315 ce=1.0157 mse=0.2316 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1398882865905762, "reserved_gb": 1.921875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "2434", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "70.17"}
2026-08-09 13:18:34 | INFO | train task=Ses01F epoch=6 batch=920/2413 step=3250 loss=2.0059 ce=1.9785 mse=0.0549 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.139653205871582, "reserved_gb": 1.91015625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "16", "gpu_mem_used_mb": "2422", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "72.20"}
2026-08-09 13:18:55 | INFO | train task=Ses01F epoch=6 batch=1020/2413 step=3275 loss=0.6945 ce=0.4683 mse=0.4524 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1397809982299805, "reserved_gb": 1.912109375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "2424", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "76.36"}
2026-08-09 13:19:14 | INFO | train task=Ses01F epoch=6 batch=1120/2413 step=3300 loss=0.1648 ce=0.1426 mse=0.0444 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1400341987609863, "reserved_gb": 2.0546875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "44", "gpu_mem_used_mb": "2570", "gpu_mem_total_mb": "12288", "gpu_temp_c": "53", "gpu_power_w": "80.49"}
2026-08-09 13:19:37 | INFO | train task=Ses01F epoch=6 batch=1220/2413 step=3325 loss=0.2352 ce=0.0362 mse=0.3980 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1425871849060059, "reserved_gb": 2.046875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "24", "gpu_mem_used_mb": "2561", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "54.00"}
2026-08-09 13:19:57 | INFO | train task=Ses01F epoch=6 batch=1320/2413 step=3350 loss=0.2595 ce=0.0144 mse=0.4903 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1405463218688965, "reserved_gb": 1.91015625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "58", "gpu_mem_used_mb": "2421", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "90.68"}
2026-08-09 13:20:16 | INFO | train task=Ses01F epoch=6 batch=1420/2413 step=3375 loss=1.5182 ce=1.3983 mse=0.2398 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1394920349121094, "reserved_gb": 1.90234375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "16", "gpu_mem_used_mb": "2413", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "64.76"}
2026-08-09 13:20:37 | INFO | train task=Ses01F epoch=6 batch=1520/2413 step=3400 loss=0.6228 ce=0.3948 mse=0.4561 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1411480903625488, "reserved_gb": 1.91015625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "66", "gpu_mem_used_mb": "2421", "gpu_mem_total_mb": "12288", "gpu_temp_c": "53", "gpu_power_w": "71.29"}
2026-08-09 13:21:00 | INFO | train task=Ses01F epoch=6 batch=1620/2413 step=3425 loss=0.9343 ce=0.8406 mse=0.1872 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1404809951782227, "reserved_gb": 2.02734375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "36", "gpu_mem_used_mb": "2541", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "67.66"}
2026-08-09 13:21:20 | INFO | train task=Ses01F epoch=6 batch=1720/2413 step=3450 loss=0.8870 ce=0.5312 mse=0.7116 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1403217315673828, "reserved_gb": 1.923828125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "41", "gpu_mem_used_mb": "2435", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "73.42"}
2026-08-09 13:21:40 | INFO | train task=Ses01F epoch=6 batch=1820/2413 step=3475 loss=0.2766 ce=0.2633 mse=0.0266 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1408967971801758, "reserved_gb": 1.90625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "31", "gpu_mem_used_mb": "2416", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "80.35"}
2026-08-09 13:22:01 | INFO | train task=Ses01F epoch=6 batch=1920/2413 step=3500 loss=0.8478 ce=0.5033 mse=0.6891 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1400761604309082, "reserved_gb": 1.923828125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "18", "gpu_mem_used_mb": "2434", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "75.88"}
2026-08-09 13:22:27 | INFO | train task=Ses01F epoch=6 batch=2020/2413 step=3525 loss=0.4051 ce=0.2986 mse=0.2131 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1401805877685547, "reserved_gb": 2.025390625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "2538", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "88.79"}
2026-08-09 13:22:49 | INFO | train task=Ses01F epoch=6 batch=2120/2413 step=3550 loss=0.6992 ce=0.4268 mse=0.5446 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.142641544342041, "reserved_gb": 2.03125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "41", "gpu_mem_used_mb": "2544", "gpu_mem_total_mb": "12288", "gpu_temp_c": "53", "gpu_power_w": "80.30"}
2026-08-09 13:23:10 | INFO | train task=Ses01F epoch=6 batch=2220/2413 step=3575 loss=0.1300 ce=0.0458 mse=0.1684 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.142293930053711, "reserved_gb": 2.013671875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "23", "gpu_mem_used_mb": "2525", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "81.27"}
2026-08-09 13:23:32 | INFO | train task=Ses01F epoch=6 batch=2320/2413 step=3600 loss=0.8520 ce=0.5862 mse=0.5317 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.145613670349121, "reserved_gb": 2.38671875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "31", "gpu_mem_used_mb": "2907", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "82.71"}

predict:   0%|          | 0/304 [00:00<?, ?it/s]

2026-08-09 13:24:13 | INFO | Epoch 06 task=Ses01F train_loss=0.8283 val_macro_f1=0.5186 val_mae=0.4894 epoch_seconds=522.2

predict:   0%|          | 0/348 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)

predict:   0%|          | 0/328 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
2026-08-09 13:25:36 | INFO | Task def600f0152ffe25_main_fold -> complete
2026-08-09 13:25:38 | INFO | Manuscript outputs refreshed: 21 tables, 4 figures
2026-08-09 13:25:38 | INFO | Task d28ec9b324867906_main_fold -> running
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\transformers\configuration_utils.py:335: UserWarning: Passing `gradient_checkpointing` to a config initialization is deprecated and will be removed in v5 Transformers. Using `model.gradient_checkpointing_enable()` instead, or if you are using the `Trainer` API, pass `gradient_checkpointing=True` in your `TrainingArguments`.
  warnings.warn(
2026-08-09 13:25:41 | INFO | Task C:\Users\HaseebWajid\Downloads\runs\dersx_paper_aligned\campaign_01\main\seed_47\Ses03M parameters={'total': 163009451, 'trainable': 69034283, 'frozen': 93975168} scope={'corpus': 'IEMOCAP', 'protocol': 'strict_LOSO', 'heldout_speaker': 'Ses03M', 'seed': 47, 'stage': 'main', 'profile': 'rtx3060_24h'}

epoch 1:   0%|          | 0/2369 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 13:26:07 | INFO | train task=Ses03M epoch=1 batch=100/2369 step=25 loss=3.7051 ce=2.3514 mse=2.7075 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1402912139892578, "reserved_gb": 1.80859375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "27", "gpu_mem_used_mb": "2317", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "72.55"}
2026-08-09 13:26:29 | INFO | train task=Ses03M epoch=1 batch=200/2369 step=50 loss=2.6447 ce=2.1125 mse=1.0644 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.139754295349121, "reserved_gb": 1.705078125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "26", "gpu_mem_used_mb": "2211", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "63.24"}
2026-08-09 13:26:51 | INFO | train task=Ses03M epoch=1 batch=300/2369 step=75 loss=2.9856 ce=2.2734 mse=1.4243 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1398005485534668, "reserved_gb": 1.814453125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "36", "gpu_mem_used_mb": "2323", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "72.22"}
2026-08-09 13:27:12 | INFO | train task=Ses03M epoch=1 batch=400/2369 step=100 loss=2.4281 ce=2.3908 mse=0.0747 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1405863761901855, "reserved_gb": 1.837890625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "18", "gpu_mem_used_mb": "2347", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "51.53"}
2026-08-09 13:27:38 | INFO | train task=Ses03M epoch=1 batch=500/2369 step=125 loss=2.1696 ce=1.9751 mse=0.3890 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1394877433776855, "reserved_gb": 1.75, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "14", "gpu_mem_used_mb": "2257", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "62.27"}
2026-08-09 13:28:02 | INFO | train task=Ses03M epoch=1 batch=600/2369 step=150 loss=2.0413 ce=2.0007 mse=0.0813 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1393718719482422, "reserved_gb": 1.75, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "67", "gpu_mem_used_mb": "2280", "gpu_mem_total_mb": "12288", "gpu_temp_c": "55", "gpu_power_w": "79.92"}
2026-08-09 13:28:25 | INFO | train task=Ses03M epoch=1 batch=700/2369 step=175 loss=2.0623 ce=1.3018 mse=1.5210 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1449556350708008, "reserved_gb": 2.15234375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "31", "gpu_mem_used_mb": "2667", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "68.49"}
2026-08-09 13:28:47 | INFO | train task=Ses03M epoch=1 batch=800/2369 step=200 loss=1.4832 ce=1.2780 mse=0.4104 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1428861618041992, "reserved_gb": 1.7421875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "32", "gpu_mem_used_mb": "2266", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "76.21"}
2026-08-09 13:29:14 | INFO | train task=Ses03M epoch=1 batch=900/2369 step=225 loss=2.3313 ce=2.0565 mse=0.5496 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1414284706115723, "reserved_gb": 1.947265625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "2476", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "77.88"}
2026-08-09 13:29:38 | INFO | train task=Ses03M epoch=1 batch=1000/2369 step=250 loss=2.5093 ce=1.8576 mse=1.3034 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.139592170715332, "reserved_gb": 1.837890625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "35", "gpu_mem_used_mb": "2364", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "70.01"}
2026-08-09 13:29:59 | INFO | train task=Ses03M epoch=1 batch=1100/2369 step=275 loss=1.6848 ce=1.5430 mse=0.2836 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1399688720703125, "reserved_gb": 1.73828125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "41", "gpu_mem_used_mb": "2265", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "71.60"}
2026-08-09 13:30:22 | INFO | train task=Ses03M epoch=1 batch=1200/2369 step=300 loss=2.3183 ce=2.1378 mse=0.3610 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1403141021728516, "reserved_gb": 1.72265625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "29", "gpu_mem_used_mb": "2249", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "68.83"}
2026-08-09 13:30:48 | INFO | train task=Ses03M epoch=1 batch=1300/2369 step=325 loss=1.7435 ce=1.6557 mse=0.1756 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1449556350708008, "reserved_gb": 1.958984375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "25", "gpu_mem_used_mb": "2491", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "71.90"}
2026-08-09 13:31:11 | INFO | train task=Ses03M epoch=1 batch=1400/2369 step=350 loss=0.7844 ce=0.7486 mse=0.0716 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.139981746673584, "reserved_gb": 1.72265625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "35", "gpu_mem_used_mb": "2249", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "99.84"}
2026-08-09 13:31:33 | INFO | train task=Ses03M epoch=1 batch=1500/2369 step=375 loss=2.6343 ce=2.3191 mse=0.6305 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1402406692504883, "reserved_gb": 1.744140625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "24", "gpu_mem_used_mb": "2271", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "63.85"}
2026-08-09 13:31:56 | INFO | train task=Ses03M epoch=1 batch=1600/2369 step=400 loss=1.8627 ce=1.7630 mse=0.1995 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1396055221557617, "reserved_gb": 2.068359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "64", "gpu_mem_used_mb": "2603", "gpu_mem_total_mb": "12288", "gpu_temp_c": "53", "gpu_power_w": "90.22"}
2026-08-09 13:32:22 | INFO | train task=Ses03M epoch=1 batch=1700/2369 step=425 loss=1.7081 ce=1.2888 mse=0.8386 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.139634609222412, "reserved_gb": 1.69921875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "18", "gpu_mem_used_mb": "2225", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "78.62"}
2026-08-09 13:32:42 | INFO | train task=Ses03M epoch=1 batch=1800/2369 step=450 loss=1.8048 ce=1.6691 mse=0.2714 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1398820877075195, "reserved_gb": 1.70703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "43", "gpu_mem_used_mb": "2233", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "43.35"}
2026-08-09 13:33:04 | INFO | train task=Ses03M epoch=1 batch=1900/2369 step=475 loss=0.8224 ce=0.8007 mse=0.0433 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.139653205871582, "reserved_gb": 1.77734375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "51", "gpu_mem_used_mb": "2305", "gpu_mem_total_mb": "12288", "gpu_temp_c": "54", "gpu_power_w": "88.40"}
2026-08-09 13:33:25 | INFO | train task=Ses03M epoch=1 batch=2000/2369 step=500 loss=1.6840 ce=1.5839 mse=0.2001 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1393685340881348, "reserved_gb": 1.99609375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "24", "gpu_mem_used_mb": "2529", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "73.36"}
2026-08-09 13:33:50 | INFO | train task=Ses03M epoch=1 batch=2100/2369 step=525 loss=2.2509 ce=1.8036 mse=0.8946 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1407747268676758, "reserved_gb": 1.705078125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "2235", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "81.70"}
2026-08-09 13:34:13 | INFO | train task=Ses03M epoch=1 batch=2200/2369 step=550 loss=0.9095 ce=0.8529 mse=0.1131 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1411895751953125, "reserved_gb": 2.37890625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "35", "gpu_mem_used_mb": "2925", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "76.46"}
2026-08-09 13:34:36 | INFO | train task=Ses03M epoch=1 batch=2300/2369 step=575 loss=1.2252 ce=1.1948 mse=0.0609 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1449556350708008, "reserved_gb": 2.1953125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "42", "gpu_mem_used_mb": "2737", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "86.13"}

predict:   0%|          | 0/295 [00:00<?, ?it/s]

2026-08-09 13:35:28 | INFO | Epoch 01 task=Ses03M train_loss=2.0872 val_macro_f1=0.3705 val_mae=0.5848 epoch_seconds=586.5

epoch 2:   0%|          | 0/2369 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 13:35:38 | INFO | train task=Ses03M epoch=2 batch=28/2369 step=600 loss=1.6423 ce=0.9665 mse=1.3516 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.139786720275879, "reserved_gb": 3.017578125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "46", "gpu_mem_used_mb": "3579", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "62.83"}
2026-08-09 13:36:02 | INFO | train task=Ses03M epoch=2 batch=128/2369 step=625 loss=1.5975 ce=1.5647 mse=0.0656 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1394786834716797, "reserved_gb": 1.77734375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "28", "gpu_mem_used_mb": "2309", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "67.53"}
2026-08-09 13:36:21 | INFO | train task=Ses03M epoch=2 batch=228/2369 step=650 loss=1.5307 ce=1.4819 mse=0.0977 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1399765014648438, "reserved_gb": 1.759765625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "28", "gpu_mem_used_mb": "2291", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "73.66"}
2026-08-09 13:36:39 | INFO | train task=Ses03M epoch=2 batch=328/2369 step=675 loss=1.4838 ce=1.2329 mse=0.5017 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1401824951171875, "reserved_gb": 2.017578125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "31", "gpu_mem_used_mb": "2555", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "72.82"}
2026-08-09 13:37:00 | INFO | train task=Ses03M epoch=2 batch=428/2369 step=700 loss=1.9423 ce=1.7855 mse=0.3137 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1396145820617676, "reserved_gb": 2.33984375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "2884", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "66.33"}
2026-08-09 13:37:22 | INFO | train task=Ses03M epoch=2 batch=528/2369 step=725 loss=1.6719 ce=1.2302 mse=0.8835 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1396198272705078, "reserved_gb": 1.8046875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "2336", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "94.10"}
2026-08-09 13:37:43 | INFO | train task=Ses03M epoch=2 batch=628/2369 step=750 loss=0.7905 ce=0.6657 mse=0.2496 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1395072937011719, "reserved_gb": 1.68359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "12", "gpu_mem_used_mb": "2212", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "55.78"}
2026-08-09 13:38:04 | INFO | train task=Ses03M epoch=2 batch=728/2369 step=775 loss=1.4660 ce=1.4039 mse=0.1241 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.139510154724121, "reserved_gb": 1.755859375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "27", "gpu_mem_used_mb": "2286", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "66.41"}
2026-08-09 13:38:24 | INFO | train task=Ses03M epoch=2 batch=828/2369 step=800 loss=2.0482 ce=1.5297 mse=1.0370 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.139413833618164, "reserved_gb": 1.98828125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "48", "gpu_mem_used_mb": "2524", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "65.67"}
2026-08-09 13:38:45 | INFO | train task=Ses03M epoch=2 batch=928/2369 step=825 loss=0.2889 ce=0.2529 mse=0.0720 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1456575393676758, "reserved_gb": 2.275390625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "41", "gpu_mem_used_mb": "2818", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "67.61"}
2026-08-09 13:39:05 | INFO | train task=Ses03M epoch=2 batch=1028/2369 step=850 loss=1.4486 ce=1.3322 mse=0.2327 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1428499221801758, "reserved_gb": 1.732421875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "29", "gpu_mem_used_mb": "2262", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "76.10"}
2026-08-09 13:39:25 | INFO | train task=Ses03M epoch=2 batch=1128/2369 step=875 loss=0.5571 ce=0.5001 mse=0.1140 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.139693260192871, "reserved_gb": 1.75, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "33", "gpu_mem_used_mb": "2280", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "35.30"}
2026-08-09 13:39:45 | INFO | train task=Ses03M epoch=2 batch=1228/2369 step=900 loss=1.5379 ce=0.5564 mse=1.9629 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1396145820617676, "reserved_gb": 1.859375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "26", "gpu_mem_used_mb": "2392", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "96.29"}
2026-08-09 13:40:09 | INFO | train task=Ses03M epoch=2 batch=1328/2369 step=925 loss=0.4268 ce=0.4087 mse=0.0361 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1416573524475098, "reserved_gb": 1.93359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "2467", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "80.23"}
2026-08-09 13:40:28 | INFO | train task=Ses03M epoch=2 batch=1428/2369 step=950 loss=1.0521 ce=0.9004 mse=0.3034 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1404376029968262, "reserved_gb": 1.76953125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "2299", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "54.62"}
2026-08-09 13:40:47 | INFO | train task=Ses03M epoch=2 batch=1528/2369 step=975 loss=1.8842 ce=1.5205 mse=0.7273 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.139643669128418, "reserved_gb": 2.029296875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "19", "gpu_mem_used_mb": "2565", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "63.56"}
2026-08-09 13:41:08 | INFO | train task=Ses03M epoch=2 batch=1628/2369 step=1000 loss=0.5970 ce=0.2428 mse=0.7084 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1486597061157227, "reserved_gb": 1.837890625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "98", "gpu_mem_used_mb": "2369", "gpu_mem_total_mb": "12288", "gpu_temp_c": "56", "gpu_power_w": "96.41"}
2026-08-09 13:41:30 | INFO | train task=Ses03M epoch=2 batch=1728/2369 step=1025 loss=1.4263 ce=1.3294 mse=0.1939 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1413278579711914, "reserved_gb": 1.728515625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "54", "gpu_mem_used_mb": "2257", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "74.91"}
2026-08-09 13:41:51 | INFO | train task=Ses03M epoch=2 batch=1828/2369 step=1050 loss=1.0974 ce=1.0877 mse=0.0194 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1404967308044434, "reserved_gb": 1.70703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "2235", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "69.28"}
2026-08-09 13:42:13 | INFO | train task=Ses03M epoch=2 batch=1928/2369 step=1075 loss=1.4348 ce=1.3787 mse=0.1122 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1399827003479004, "reserved_gb": 2.46484375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "34", "gpu_mem_used_mb": "3010", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "64.23"}
2026-08-09 13:42:33 | INFO | train task=Ses03M epoch=2 batch=2028/2369 step=1100 loss=0.4962 ce=0.3896 mse=0.2131 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1398215293884277, "reserved_gb": 1.947265625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "40", "gpu_mem_used_mb": "2480", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "68.13"}
2026-08-09 13:42:55 | INFO | train task=Ses03M epoch=2 batch=2128/2369 step=1125 loss=1.1863 ce=0.6939 mse=0.9847 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1402912139892578, "reserved_gb": 1.708984375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "23", "gpu_mem_used_mb": "2236", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "71.45"}
2026-08-09 13:43:16 | INFO | train task=Ses03M epoch=2 batch=2228/2369 step=1150 loss=0.6242 ce=0.4885 mse=0.2713 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1396675109863281, "reserved_gb": 1.78125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "16", "gpu_mem_used_mb": "2310", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "64.28"}
2026-08-09 13:43:37 | INFO | train task=Ses03M epoch=2 batch=2328/2369 step=1175 loss=1.1848 ce=0.9991 mse=0.3713 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.140608310699463, "reserved_gb": 1.703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "26", "gpu_mem_used_mb": "2230", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "56.53"}

predict:   0%|          | 0/295 [00:00<?, ?it/s]

2026-08-09 13:44:08 | INFO | Epoch 02 task=Ses03M train_loss=1.5037 val_macro_f1=0.3924 val_mae=0.5643 epoch_seconds=515.6

epoch 3:   0%|          | 0/2369 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 13:44:24 | INFO | train task=Ses03M epoch=3 batch=56/2369 step=1200 loss=0.8380 ce=0.6947 mse=0.2868 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1449556350708008, "reserved_gb": 1.763671875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "72", "gpu_mem_used_mb": "2291", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "51.53"}
2026-08-09 13:44:46 | INFO | train task=Ses03M epoch=3 batch=156/2369 step=1225 loss=0.9235 ce=0.8166 mse=0.2138 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1401853561401367, "reserved_gb": 1.70703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "19", "gpu_mem_used_mb": "2233", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "75.64"}
2026-08-09 13:45:05 | INFO | train task=Ses03M epoch=3 batch=256/2369 step=1250 loss=1.7381 ce=1.6670 mse=0.1422 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1394610404968262, "reserved_gb": 2.046875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "16", "gpu_mem_used_mb": "2581", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "64.64"}
2026-08-09 13:45:24 | INFO | train task=Ses03M epoch=3 batch=356/2369 step=1275 loss=1.7181 ce=1.4246 mse=0.5870 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1408076286315918, "reserved_gb": 1.849609375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "51", "gpu_mem_used_mb": "2379", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "46.66"}
2026-08-09 13:45:43 | INFO | train task=Ses03M epoch=3 batch=456/2369 step=1300 loss=1.8441 ce=1.8390 mse=0.0101 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1394400596618652, "reserved_gb": 1.75390625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "10", "gpu_mem_used_mb": "2281", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "63.59"}
2026-08-09 13:46:06 | INFO | train task=Ses03M epoch=3 batch=556/2369 step=1325 loss=0.6747 ce=0.5250 mse=0.2994 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1439237594604492, "reserved_gb": 2.18359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "40", "gpu_mem_used_mb": "2721", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "64.85"}
2026-08-09 13:46:26 | INFO | train task=Ses03M epoch=3 batch=656/2369 step=1350 loss=0.8866 ce=0.7159 mse=0.3415 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.140782356262207, "reserved_gb": 1.81640625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "36", "gpu_mem_used_mb": "2344", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "57.79"}
2026-08-09 13:46:44 | INFO | train task=Ses03M epoch=3 batch=756/2369 step=1375 loss=1.1325 ce=1.0636 mse=0.1378 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.144730567932129, "reserved_gb": 2.037109375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "18", "gpu_mem_used_mb": "2570", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "81.09"}
2026-08-09 13:47:04 | INFO | train task=Ses03M epoch=3 batch=856/2369 step=1400 loss=2.6243 ce=2.3260 mse=0.5965 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.139758586883545, "reserved_gb": 1.8046875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "2332", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "86.21"}
2026-08-09 13:47:26 | INFO | train task=Ses03M epoch=3 batch=956/2369 step=1425 loss=1.0953 ce=0.9648 mse=0.2611 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1449556350708008, "reserved_gb": 2.810546875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "49", "gpu_mem_used_mb": "3362", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "87.13"}
2026-08-09 13:47:46 | INFO | train task=Ses03M epoch=3 batch=1056/2369 step=1450 loss=1.1388 ce=0.6641 mse=0.9492 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1415247917175293, "reserved_gb": 1.95703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "26", "gpu_mem_used_mb": "2488", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "74.08"}
2026-08-09 13:48:05 | INFO | train task=Ses03M epoch=3 batch=1156/2369 step=1475 loss=0.5407 ce=0.5217 mse=0.0380 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1401658058166504, "reserved_gb": 2.255859375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "37", "gpu_mem_used_mb": "2794", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "47.70"}
2026-08-09 13:48:24 | INFO | train task=Ses03M epoch=3 batch=1256/2369 step=1500 loss=1.3618 ce=1.3500 mse=0.0237 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1401658058166504, "reserved_gb": 1.869140625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "31", "gpu_mem_used_mb": "2398", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "64.64"}
2026-08-09 13:48:48 | INFO | train task=Ses03M epoch=3 batch=1356/2369 step=1525 loss=0.5733 ce=0.2220 mse=0.7026 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1432642936706543, "reserved_gb": 2.205078125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "37", "gpu_mem_used_mb": "2741", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "80.37"}
2026-08-09 13:49:07 | INFO | train task=Ses03M epoch=3 batch=1456/2369 step=1550 loss=0.9219 ce=0.6650 mse=0.5139 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1401762962341309, "reserved_gb": 1.779296875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "10", "gpu_mem_used_mb": "2305", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "59.51"}
2026-08-09 13:49:28 | INFO | train task=Ses03M epoch=3 batch=1556/2369 step=1575 loss=0.1953 ce=0.1758 mse=0.0390 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.145857334136963, "reserved_gb": 2.236328125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "51", "gpu_mem_used_mb": "2773", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "72.12"}
2026-08-09 13:49:48 | INFO | train task=Ses03M epoch=3 batch=1656/2369 step=1600 loss=1.7007 ce=1.6828 mse=0.0357 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1402831077575684, "reserved_gb": 1.755859375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "2281", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "65.96"}
2026-08-09 13:50:11 | INFO | train task=Ses03M epoch=3 batch=1756/2369 step=1625 loss=3.4891 ce=3.1837 mse=0.6108 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.139514446258545, "reserved_gb": 2.05859375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "33", "gpu_mem_used_mb": "2591", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "68.72"}
2026-08-09 13:50:29 | INFO | train task=Ses03M epoch=3 batch=1856/2369 step=1650 loss=1.0795 ce=0.9483 mse=0.2624 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1394033432006836, "reserved_gb": 2.5234375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "26", "gpu_mem_used_mb": "3067", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "52.09"}
2026-08-09 13:50:49 | INFO | train task=Ses03M epoch=3 batch=1956/2369 step=1675 loss=0.8994 ce=0.8931 mse=0.0126 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1449556350708008, "reserved_gb": 2.6640625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "33", "gpu_mem_used_mb": "3210", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "73.00"}
2026-08-09 13:51:10 | INFO | train task=Ses03M epoch=3 batch=2056/2369 step=1700 loss=0.2251 ce=0.1663 mse=0.1176 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1400671005249023, "reserved_gb": 2.09375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "24", "gpu_mem_used_mb": "2626", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "65.65"}
2026-08-09 13:51:33 | INFO | train task=Ses03M epoch=3 batch=2156/2369 step=1725 loss=0.3386 ce=0.0724 mse=0.5324 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1411166191101074, "reserved_gb": 1.94140625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "52", "gpu_mem_used_mb": "2470", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "59.10"}
2026-08-09 13:51:52 | INFO | train task=Ses03M epoch=3 batch=2256/2369 step=1750 loss=0.8427 ce=0.7572 mse=0.1709 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.141115665435791, "reserved_gb": 1.953125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "2482", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "68.95"}
2026-08-09 13:52:15 | INFO | train task=Ses03M epoch=3 batch=2356/2369 step=1775 loss=0.4586 ce=0.2829 mse=0.3515 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1411094665527344, "reserved_gb": 1.884765625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "42", "gpu_mem_used_mb": "2412", "gpu_mem_total_mb": "12288", "gpu_temp_c": "53", "gpu_power_w": "93.09"}

predict:   0%|          | 0/295 [00:00<?, ?it/s]

2026-08-09 13:52:36 | INFO | Epoch 03 task=Ses03M train_loss=1.2414 val_macro_f1=0.3874 val_mae=0.5768 epoch_seconds=503.7

epoch 4:   0%|          | 0/2369 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 13:52:55 | INFO | train task=Ses03M epoch=4 batch=84/2369 step=1800 loss=0.8225 ce=0.3116 mse=1.0217 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1395487785339355, "reserved_gb": 1.74609375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "14", "gpu_mem_used_mb": "2269", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "62.48"}
2026-08-09 13:53:16 | INFO | train task=Ses03M epoch=4 batch=184/2369 step=1825 loss=3.5991 ce=3.5892 mse=0.0198 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1452984809875488, "reserved_gb": 2.544921875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "3087", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "55.50"}
2026-08-09 13:53:35 | INFO | train task=Ses03M epoch=4 batch=284/2369 step=1850 loss=0.3157 ce=0.2968 mse=0.0377 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1449556350708008, "reserved_gb": 2.419921875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "27", "gpu_mem_used_mb": "2959", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "49.34"}
2026-08-09 13:53:54 | INFO | train task=Ses03M epoch=4 batch=384/2369 step=1875 loss=1.3950 ce=1.3225 mse=0.1451 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.141951084136963, "reserved_gb": 1.939453125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "40", "gpu_mem_used_mb": "2467", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "68.94"}
2026-08-09 13:54:14 | INFO | train task=Ses03M epoch=4 batch=484/2369 step=1900 loss=3.5511 ce=3.0337 mse=1.0349 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1439180374145508, "reserved_gb": 2.052734375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "67", "gpu_mem_used_mb": "2583", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "78.35"}
2026-08-09 13:54:36 | INFO | train task=Ses03M epoch=4 batch=584/2369 step=1925 loss=1.9083 ce=1.7384 mse=0.3398 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1397318840026855, "reserved_gb": 2.1796875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "11", "gpu_mem_used_mb": "2713", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "70.79"}
2026-08-09 13:54:56 | INFO | train task=Ses03M epoch=4 batch=684/2369 step=1950 loss=0.8178 ce=0.5725 mse=0.4905 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1407470703125, "reserved_gb": 1.794921875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "59", "gpu_mem_used_mb": "2318", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "68.11"}
2026-08-09 13:55:14 | INFO | train task=Ses03M epoch=4 batch=784/2369 step=1975 loss=1.9857 ce=1.5501 mse=0.8713 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1395254135131836, "reserved_gb": 2.279296875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "2814", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "74.07"}
2026-08-09 13:55:35 | INFO | train task=Ses03M epoch=4 batch=884/2369 step=2000 loss=0.5929 ce=0.2521 mse=0.6814 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1449556350708008, "reserved_gb": 1.76953125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "45", "gpu_mem_used_mb": "2292", "gpu_mem_total_mb": "12288", "gpu_temp_c": "53", "gpu_power_w": "83.90"}
2026-08-09 13:55:59 | INFO | train task=Ses03M epoch=4 batch=984/2369 step=2025 loss=0.6189 ce=0.4139 mse=0.4100 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1397147178649902, "reserved_gb": 1.82421875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "2348", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "69.57"}
2026-08-09 13:56:19 | INFO | train task=Ses03M epoch=4 batch=1084/2369 step=2050 loss=1.4378 ce=1.3473 mse=0.1810 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1415247917175293, "reserved_gb": 1.916015625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "14", "gpu_mem_used_mb": "2442", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "74.42"}
2026-08-09 13:56:40 | INFO | train task=Ses03M epoch=4 batch=1184/2369 step=2075 loss=2.1286 ce=1.9813 mse=0.2945 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.145246982574463, "reserved_gb": 1.796875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "93", "gpu_mem_used_mb": "2320", "gpu_mem_total_mb": "12288", "gpu_temp_c": "55", "gpu_power_w": "90.31"}
2026-08-09 13:56:59 | INFO | train task=Ses03M epoch=4 batch=1284/2369 step=2100 loss=2.1538 ce=1.9331 mse=0.4415 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1399812698364258, "reserved_gb": 1.880859375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "2406", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "68.64"}
2026-08-09 13:57:22 | INFO | train task=Ses03M epoch=4 batch=1384/2369 step=2125 loss=1.4008 ce=1.3896 mse=0.0224 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.140246868133545, "reserved_gb": 1.79296875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "45", "gpu_mem_used_mb": "2316", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "65.83"}
2026-08-09 13:57:42 | INFO | train task=Ses03M epoch=4 batch=1484/2369 step=2150 loss=0.5784 ce=0.2392 mse=0.6785 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1416563987731934, "reserved_gb": 2.166015625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "47", "gpu_mem_used_mb": "2698", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "58.05"}
2026-08-09 13:58:02 | INFO | train task=Ses03M epoch=4 batch=1584/2369 step=2175 loss=0.4146 ce=0.3886 mse=0.0521 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1394414901733398, "reserved_gb": 2.267578125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "15", "gpu_mem_used_mb": "2801", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "74.97"}
2026-08-09 13:58:22 | INFO | train task=Ses03M epoch=4 batch=1684/2369 step=2200 loss=0.2519 ce=0.2421 mse=0.0195 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1394400596618652, "reserved_gb": 1.935546875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "29", "gpu_mem_used_mb": "2461", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "81.54"}
2026-08-09 13:58:44 | INFO | train task=Ses03M epoch=4 batch=1784/2369 step=2225 loss=1.0092 ce=0.8628 mse=0.2927 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1400957107543945, "reserved_gb": 2.140625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "33", "gpu_mem_used_mb": "2671", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "73.81"}
2026-08-09 13:59:03 | INFO | train task=Ses03M epoch=4 batch=1884/2369 step=2250 loss=0.5880 ce=0.5394 mse=0.0972 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1399450302124023, "reserved_gb": 2.2734375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "24", "gpu_mem_used_mb": "2807", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "65.82"}
2026-08-09 13:59:23 | INFO | train task=Ses03M epoch=4 batch=1984/2369 step=2275 loss=0.6293 ce=0.5552 mse=0.1482 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1394166946411133, "reserved_gb": 2.068359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "14", "gpu_mem_used_mb": "2597", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "63.28"}
2026-08-09 13:59:43 | INFO | train task=Ses03M epoch=4 batch=2084/2369 step=2300 loss=3.0044 ce=2.9959 mse=0.0169 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1396923065185547, "reserved_gb": 1.701171875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "16", "gpu_mem_used_mb": "2221", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "63.72"}
2026-08-09 14:00:05 | INFO | train task=Ses03M epoch=4 batch=2184/2369 step=2325 loss=0.6761 ce=0.3477 mse=0.6568 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1396923065185547, "reserved_gb": 1.896484375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "45", "gpu_mem_used_mb": "2420", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "68.88"}
2026-08-09 14:00:24 | INFO | train task=Ses03M epoch=4 batch=2284/2369 step=2350 loss=0.4354 ce=0.2571 mse=0.3566 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1419477462768555, "reserved_gb": 2.06640625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "44", "gpu_mem_used_mb": "2594", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "66.39"}

predict:   0%|          | 0/295 [00:00<?, ?it/s]

2026-08-09 14:00:59 | INFO | Epoch 04 task=Ses03M train_loss=1.0804 val_macro_f1=0.3850 val_mae=0.5523 epoch_seconds=500.1

predict:   0%|          | 0/321 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)

predict:   0%|          | 0/413 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
2026-08-09 14:02:45 | INFO | Task d28ec9b324867906_main_fold -> complete
2026-08-09 14:02:47 | INFO | Manuscript outputs refreshed: 21 tables, 4 figures
2026-08-09 14:02:47 | INFO | Task 8be8e78c11f179a4_main_fold -> running
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\transformers\configuration_utils.py:335: UserWarning: Passing `gradient_checkpointing` to a config initialization is deprecated and will be removed in v5 Transformers. Using `model.gradient_checkpointing_enable()` instead, or if you are using the `Trainer` API, pass `gradient_checkpointing=True` in your `TrainingArguments`.
  warnings.warn(
2026-08-09 14:02:49 | INFO | Task C:\Users\HaseebWajid\Downloads\runs\dersx_paper_aligned\campaign_01\main\seed_47\Ses05M parameters={'total': 163009451, 'trainable': 69034283, 'frozen': 93975168} scope={'corpus': 'IEMOCAP', 'protocol': 'strict_LOSO', 'heldout_speaker': 'Ses05M', 'seed': 47, 'stage': 'main', 'profile': 'rtx3060_24h'}

epoch 1:   0%|          | 0/2330 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 14:03:12 | INFO | train task=Ses05M epoch=1 batch=100/2330 step=25 loss=3.4285 ce=2.2218 mse=2.4134 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2585153579711914, "reserved_gb": 2.888671875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "28", "gpu_mem_used_mb": "3435", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "79.50"}
2026-08-09 14:03:34 | INFO | train task=Ses05M epoch=1 batch=200/2330 step=50 loss=2.9164 ce=2.2309 mse=1.3710 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.259674072265625, "reserved_gb": 3.00390625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "56", "gpu_mem_used_mb": "3553", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "86.98"}
2026-08-09 14:03:57 | INFO | train task=Ses05M epoch=1 batch=300/2330 step=75 loss=2.5266 ce=2.0153 mse=1.0225 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2588305473327637, "reserved_gb": 2.8828125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "37", "gpu_mem_used_mb": "3429", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "72.48"}
2026-08-09 14:04:22 | INFO | train task=Ses05M epoch=1 batch=400/2330 step=100 loss=1.9153 ce=1.8308 mse=0.1689 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2586584091186523, "reserved_gb": 2.90625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "3452", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "86.39"}
2026-08-09 14:04:48 | INFO | train task=Ses05M epoch=1 batch=500/2330 step=125 loss=2.2387 ce=1.8337 mse=0.8100 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.259955406188965, "reserved_gb": 3.10546875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "31", "gpu_mem_used_mb": "3656", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "94.48"}
2026-08-09 14:05:10 | INFO | train task=Ses05M epoch=1 batch=600/2330 step=150 loss=2.8761 ce=2.0575 mse=1.6373 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.258512020111084, "reserved_gb": 2.94140625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "27", "gpu_mem_used_mb": "3488", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "67.28"}
2026-08-09 14:05:33 | INFO | train task=Ses05M epoch=1 batch=700/2330 step=175 loss=1.4706 ce=1.2930 mse=0.3552 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2592997550964355, "reserved_gb": 2.935546875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "44", "gpu_mem_used_mb": "3482", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "63.33"}
2026-08-09 14:05:57 | INFO | train task=Ses05M epoch=1 batch=800/2330 step=200 loss=1.6124 ce=1.2988 mse=0.6272 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2599124908447266, "reserved_gb": 2.888671875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "50", "gpu_mem_used_mb": "3434", "gpu_mem_total_mb": "12288", "gpu_temp_c": "53", "gpu_power_w": "78.89"}
2026-08-09 14:06:24 | INFO | train task=Ses05M epoch=1 batch=900/2330 step=225 loss=1.5649 ce=1.5107 mse=0.1083 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.258674144744873, "reserved_gb": 3.05859375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "31", "gpu_mem_used_mb": "3607", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "72.69"}
2026-08-09 14:06:49 | INFO | train task=Ses05M epoch=1 batch=1000/2330 step=250 loss=1.8195 ce=1.6180 mse=0.4031 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.263880729675293, "reserved_gb": 2.921875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "97", "gpu_mem_used_mb": "3467", "gpu_mem_total_mb": "12288", "gpu_temp_c": "55", "gpu_power_w": "72.69"}
2026-08-09 14:07:13 | INFO | train task=Ses05M epoch=1 batch=1100/2330 step=275 loss=2.2231 ce=1.9503 mse=0.5456 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.259084701538086, "reserved_gb": 2.912109375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "33", "gpu_mem_used_mb": "3457", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "69.58"}
2026-08-09 14:07:38 | INFO | train task=Ses05M epoch=1 batch=1200/2330 step=300 loss=1.5671 ce=1.5139 mse=0.1064 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2586493492126465, "reserved_gb": 2.880859375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "61", "gpu_mem_used_mb": "3425", "gpu_mem_total_mb": "12288", "gpu_temp_c": "53", "gpu_power_w": "76.71"}
2026-08-09 14:08:06 | INFO | train task=Ses05M epoch=1 batch=1300/2330 step=325 loss=2.3621 ce=2.3232 mse=0.0776 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2590227127075195, "reserved_gb": 3.306640625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "3861", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "72.78"}
2026-08-09 14:08:30 | INFO | train task=Ses05M epoch=1 batch=1400/2330 step=350 loss=1.6694 ce=1.2638 mse=0.8113 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2586593627929688, "reserved_gb": 2.880859375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "24", "gpu_mem_used_mb": "3424", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "68.96"}
2026-08-09 14:08:55 | INFO | train task=Ses05M epoch=1 batch=1500/2330 step=375 loss=1.2539 ce=1.1670 mse=0.1738 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2584939002990723, "reserved_gb": 2.869140625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "27", "gpu_mem_used_mb": "3412", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "79.69"}
2026-08-09 14:09:21 | INFO | train task=Ses05M epoch=1 batch=1600/2330 step=400 loss=0.8071 ce=0.5105 mse=0.5932 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2589597702026367, "reserved_gb": 2.888671875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "3432", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "70.58"}
2026-08-09 14:09:47 | INFO | train task=Ses05M epoch=1 batch=1700/2330 step=425 loss=1.0661 ce=0.8334 mse=0.4654 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2586803436279297, "reserved_gb": 2.9140625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "39", "gpu_mem_used_mb": "3458", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "77.32"}
2026-08-09 14:10:11 | INFO | train task=Ses05M epoch=1 batch=1800/2330 step=450 loss=2.5704 ce=2.3396 mse=0.4616 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.259119987487793, "reserved_gb": 2.806640625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "47", "gpu_mem_used_mb": "3348", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "71.23"}
2026-08-09 14:10:34 | INFO | train task=Ses05M epoch=1 batch=1900/2330 step=475 loss=3.1123 ce=2.9228 mse=0.3790 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.259671211242676, "reserved_gb": 3.03125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "25", "gpu_mem_used_mb": "3577", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "68.45"}
2026-08-09 14:11:02 | INFO | train task=Ses05M epoch=1 batch=2000/2330 step=500 loss=1.3698 ce=1.2050 mse=0.3296 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.263880729675293, "reserved_gb": 2.951171875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "54", "gpu_mem_used_mb": "3495", "gpu_mem_total_mb": "12288", "gpu_temp_c": "55", "gpu_power_w": "73.26"}
2026-08-09 14:11:30 | INFO | train task=Ses05M epoch=1 batch=2100/2330 step=525 loss=2.4084 ce=2.1874 mse=0.4421 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2584738731384277, "reserved_gb": 2.947265625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "89", "gpu_mem_used_mb": "3491", "gpu_mem_total_mb": "12288", "gpu_temp_c": "56", "gpu_power_w": "87.15"}
2026-08-09 14:11:56 | INFO | train task=Ses05M epoch=1 batch=2200/2330 step=550 loss=1.1808 ce=0.8166 mse=0.7285 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.259735584259033, "reserved_gb": 3.015625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "28", "gpu_mem_used_mb": "3561", "gpu_mem_total_mb": "12288", "gpu_temp_c": "53", "gpu_power_w": "84.51"}
2026-08-09 14:12:21 | INFO | train task=Ses05M epoch=1 batch=2300/2330 step=575 loss=1.6034 ce=0.8916 mse=1.4235 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2584877014160156, "reserved_gb": 2.884765625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "39", "gpu_mem_used_mb": "3427", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "56.26"}

predict:   0%|          | 0/312 [00:00<?, ?it/s]

2026-08-09 14:13:07 | INFO | Epoch 01 task=Ses05M train_loss=2.0817 val_macro_f1=0.5251 val_mae=0.5517 epoch_seconds=617.2

epoch 2:   0%|          | 0/2330 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 14:13:27 | INFO | train task=Ses05M epoch=2 batch=68/2330 step=600 loss=2.4943 ce=2.0146 mse=0.9594 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.259917736053467, "reserved_gb": 3.3515625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "48", "gpu_mem_used_mb": "3904", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "81.10"}
2026-08-09 14:13:51 | INFO | train task=Ses05M epoch=2 batch=168/2330 step=625 loss=0.8127 ce=0.7043 mse=0.2168 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.259824275970459, "reserved_gb": 3.365234375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "30", "gpu_mem_used_mb": "3918", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "66.57"}
2026-08-09 14:14:11 | INFO | train task=Ses05M epoch=2 batch=268/2330 step=650 loss=2.5718 ce=2.4048 mse=0.3341 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.261535167694092, "reserved_gb": 2.912109375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "40", "gpu_mem_used_mb": "3454", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "76.15"}
2026-08-09 14:14:32 | INFO | train task=Ses05M epoch=2 batch=368/2330 step=675 loss=3.3236 ce=3.3066 mse=0.0340 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2589120864868164, "reserved_gb": 2.97265625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "3516", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "66.82"}
2026-08-09 14:14:52 | INFO | train task=Ses05M epoch=2 batch=468/2330 step=700 loss=2.6172 ce=1.7190 mse=1.7965 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2621288299560547, "reserved_gb": 3.171875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "18", "gpu_mem_used_mb": "3719", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "61.91"}
2026-08-09 14:15:15 | INFO | train task=Ses05M epoch=2 batch=568/2330 step=725 loss=2.6999 ce=2.0001 mse=1.3996 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.259305477142334, "reserved_gb": 2.865234375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "52", "gpu_mem_used_mb": "3405", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "67.77"}
2026-08-09 14:15:35 | INFO | train task=Ses05M epoch=2 batch=668/2330 step=750 loss=1.4977 ce=1.3641 mse=0.2672 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2591004371643066, "reserved_gb": 3.1484375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "24", "gpu_mem_used_mb": "3695", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "59.23"}
2026-08-09 14:15:56 | INFO | train task=Ses05M epoch=2 batch=768/2330 step=775 loss=0.5650 ce=0.4404 mse=0.2492 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.266411304473877, "reserved_gb": 4.693359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "16", "gpu_mem_used_mb": "5277", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "64.18"}
2026-08-09 14:16:16 | INFO | train task=Ses05M epoch=2 batch=868/2330 step=800 loss=2.1815 ce=1.7592 mse=0.8445 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2615199089050293, "reserved_gb": 3.580078125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "23", "gpu_mem_used_mb": "4137", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "67.47"}
2026-08-09 14:16:40 | INFO | train task=Ses05M epoch=2 batch=968/2330 step=825 loss=1.0178 ce=0.3688 mse=1.2978 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2587194442749023, "reserved_gb": 2.92578125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "3467", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "76.12"}
2026-08-09 14:17:00 | INFO | train task=Ses05M epoch=2 batch=1068/2330 step=850 loss=2.0191 ce=1.4795 mse=1.0792 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2586007118225098, "reserved_gb": 2.9765625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "29", "gpu_mem_used_mb": "3519", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "54.94"}
2026-08-09 14:17:21 | INFO | train task=Ses05M epoch=2 batch=1168/2330 step=875 loss=0.5326 ce=0.4843 mse=0.0965 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.258723735809326, "reserved_gb": 3.107421875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "11", "gpu_mem_used_mb": "3653", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "75.53"}
2026-08-09 14:17:42 | INFO | train task=Ses05M epoch=2 batch=1268/2330 step=900 loss=0.4389 ce=0.4387 mse=0.0003 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.260845184326172, "reserved_gb": 2.90234375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "31", "gpu_mem_used_mb": "3443", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "76.01"}
2026-08-09 14:18:07 | INFO | train task=Ses05M epoch=2 batch=1368/2330 step=925 loss=0.8666 ce=0.7588 mse=0.2156 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2584939002990723, "reserved_gb": 2.884765625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "26", "gpu_mem_used_mb": "3425", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "70.29"}
2026-08-09 14:18:28 | INFO | train task=Ses05M epoch=2 batch=1468/2330 step=950 loss=0.5681 ce=0.4708 mse=0.1946 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.259246349334717, "reserved_gb": 2.8984375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "39", "gpu_mem_used_mb": "3439", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "82.01"}
2026-08-09 14:18:49 | INFO | train task=Ses05M epoch=2 batch=1568/2330 step=975 loss=1.9512 ce=1.8421 mse=0.2182 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.258901596069336, "reserved_gb": 3.064453125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "86", "gpu_mem_used_mb": "3609", "gpu_mem_total_mb": "12288", "gpu_temp_c": "53", "gpu_power_w": "106.57"}
2026-08-09 14:19:13 | INFO | train task=Ses05M epoch=2 batch=1668/2330 step=1000 loss=0.5846 ce=0.5033 mse=0.1627 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2595314979553223, "reserved_gb": 2.94140625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "3483", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "69.39"}
2026-08-09 14:19:38 | INFO | train task=Ses05M epoch=2 batch=1768/2330 step=1025 loss=1.3362 ce=1.0942 mse=0.4839 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2589478492736816, "reserved_gb": 2.869140625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "23", "gpu_mem_used_mb": "3409", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "64.25"}
2026-08-09 14:20:00 | INFO | train task=Ses05M epoch=2 batch=1868/2330 step=1050 loss=0.6564 ce=0.5419 mse=0.2291 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.259039878845215, "reserved_gb": 3.435546875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "70", "gpu_mem_used_mb": "3989", "gpu_mem_total_mb": "12288", "gpu_temp_c": "54", "gpu_power_w": "90.73"}
2026-08-09 14:20:24 | INFO | train task=Ses05M epoch=2 batch=1968/2330 step=1075 loss=1.0494 ce=0.1944 mse=1.7102 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2584972381591797, "reserved_gb": 2.91796875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "18", "gpu_mem_used_mb": "3459", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "68.54"}
2026-08-09 14:20:47 | INFO | train task=Ses05M epoch=2 batch=2068/2330 step=1100 loss=0.4644 ce=0.4212 mse=0.0864 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.259678363800049, "reserved_gb": 3.10546875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "26", "gpu_mem_used_mb": "3651", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "58.63"}
2026-08-09 14:21:13 | INFO | train task=Ses05M epoch=2 batch=2168/2330 step=1125 loss=2.2592 ce=2.0120 mse=0.4943 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.258538246154785, "reserved_gb": 2.921875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "3462", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "73.32"}
2026-08-09 14:21:37 | INFO | train task=Ses05M epoch=2 batch=2268/2330 step=1150 loss=1.4534 ce=1.2437 mse=0.4193 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.25897216796875, "reserved_gb": 2.8671875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "3429", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "70.81"}

predict:   0%|          | 0/312 [00:00<?, ?it/s]

2026-08-09 14:22:13 | INFO | Epoch 02 task=Ses05M train_loss=1.5180 val_macro_f1=0.4907 val_mae=0.5180 epoch_seconds=541.2

epoch 3:   0%|          | 0/2330 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 14:22:24 | INFO | train task=Ses05M epoch=3 batch=36/2330 step=1175 loss=1.1973 ce=0.8529 mse=0.6889 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2583765983581543, "reserved_gb": 2.9375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "33", "gpu_mem_used_mb": "3501", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "70.19"}
2026-08-09 14:22:44 | INFO | train task=Ses05M epoch=3 batch=136/2330 step=1200 loss=0.8123 ce=0.5689 mse=0.4868 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.258645534515381, "reserved_gb": 2.9375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "31", "gpu_mem_used_mb": "3501", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "57.83"}
2026-08-09 14:23:07 | INFO | train task=Ses05M epoch=3 batch=236/2330 step=1225 loss=0.4601 ce=0.3478 mse=0.2246 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2594752311706543, "reserved_gb": 3.287109375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "23", "gpu_mem_used_mb": "3859", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "67.25"}
2026-08-09 14:23:27 | INFO | train task=Ses05M epoch=3 batch=336/2330 step=1250 loss=0.3871 ce=0.3620 mse=0.0502 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2590537071228027, "reserved_gb": 2.92578125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "25", "gpu_mem_used_mb": "3489", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "76.55"}
2026-08-09 14:23:48 | INFO | train task=Ses05M epoch=3 batch=436/2330 step=1275 loss=0.6734 ce=0.4564 mse=0.4340 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.25958251953125, "reserved_gb": 2.998046875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "34", "gpu_mem_used_mb": "3563", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "60.08"}
2026-08-09 14:24:10 | INFO | train task=Ses05M epoch=3 batch=536/2330 step=1300 loss=0.9324 ce=0.8359 mse=0.1931 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.258537769317627, "reserved_gb": 3.140625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "35", "gpu_mem_used_mb": "3709", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "66.42"}
2026-08-09 14:24:34 | INFO | train task=Ses05M epoch=3 batch=636/2330 step=1325 loss=1.6366 ce=1.0501 mse=1.1730 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.259228229522705, "reserved_gb": 3.0703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "68", "gpu_mem_used_mb": "3637", "gpu_mem_total_mb": "12288", "gpu_temp_c": "53", "gpu_power_w": "83.50"}
2026-08-09 14:24:56 | INFO | train task=Ses05M epoch=3 batch=736/2330 step=1350 loss=1.3502 ce=1.1296 mse=0.4412 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2596030235290527, "reserved_gb": 3.099609375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "90", "gpu_mem_used_mb": "3667", "gpu_mem_total_mb": "12288", "gpu_temp_c": "53", "gpu_power_w": "84.74"}
2026-08-09 14:25:17 | INFO | train task=Ses05M epoch=3 batch=836/2330 step=1375 loss=3.8402 ce=3.6426 mse=0.3951 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.259064197540283, "reserved_gb": 2.94921875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "3513", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "72.66"}
2026-08-09 14:25:39 | INFO | train task=Ses05M epoch=3 batch=936/2330 step=1400 loss=2.5503 ce=2.3989 mse=0.3029 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2589144706726074, "reserved_gb": 2.88671875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "3449", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "66.75"}
2026-08-09 14:26:03 | INFO | train task=Ses05M epoch=3 batch=1036/2330 step=1425 loss=4.2600 ce=4.1375 mse=0.2449 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2586379051208496, "reserved_gb": 2.931640625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "3495", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "67.77"}
2026-08-09 14:26:26 | INFO | train task=Ses05M epoch=3 batch=1136/2330 step=1450 loss=0.5475 ce=0.5231 mse=0.0488 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2590270042419434, "reserved_gb": 3.376953125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "26", "gpu_mem_used_mb": "3951", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "59.91"}
2026-08-09 14:26:48 | INFO | train task=Ses05M epoch=3 batch=1236/2330 step=1475 loss=0.6544 ce=0.4418 mse=0.4251 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.258535861968994, "reserved_gb": 2.873046875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "25", "gpu_mem_used_mb": "3435", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "63.37"}
2026-08-09 14:27:09 | INFO | train task=Ses05M epoch=3 batch=1336/2330 step=1500 loss=1.4126 ce=1.3460 mse=0.1332 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2596731185913086, "reserved_gb": 3.07421875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "36", "gpu_mem_used_mb": "3641", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "60.70"}
2026-08-09 14:27:33 | INFO | train task=Ses05M epoch=3 batch=1436/2330 step=1525 loss=2.0188 ce=1.2092 mse=1.6192 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2585949897766113, "reserved_gb": 2.8828125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "12", "gpu_mem_used_mb": "3445", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "68.42"}
2026-08-09 14:27:56 | INFO | train task=Ses05M epoch=3 batch=1536/2330 step=1550 loss=2.1655 ce=2.0308 mse=0.2694 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2588462829589844, "reserved_gb": 2.904296875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "51", "gpu_mem_used_mb": "3467", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "80.22"}
2026-08-09 14:28:18 | INFO | train task=Ses05M epoch=3 batch=1636/2330 step=1575 loss=2.1105 ce=1.8206 mse=0.5798 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2587499618530273, "reserved_gb": 2.875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "19", "gpu_mem_used_mb": "3437", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "77.22"}
2026-08-09 14:28:40 | INFO | train task=Ses05M epoch=3 batch=1736/2330 step=1600 loss=0.2783 ce=0.2287 mse=0.0991 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.258495807647705, "reserved_gb": 2.87109375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "32", "gpu_mem_used_mb": "3433", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "67.25"}
2026-08-09 14:29:08 | INFO | train task=Ses05M epoch=3 batch=1836/2330 step=1625 loss=0.4652 ce=0.4176 mse=0.0953 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.259343147277832, "reserved_gb": 3.103515625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "3671", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "60.77"}
2026-08-09 14:29:31 | INFO | train task=Ses05M epoch=3 batch=1936/2330 step=1650 loss=1.5234 ce=1.3079 mse=0.4312 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.263880729675293, "reserved_gb": 2.935546875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "61", "gpu_mem_used_mb": "3499", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "56.80"}
2026-08-09 14:29:55 | INFO | train task=Ses05M epoch=3 batch=2036/2330 step=1675 loss=0.3475 ce=0.2966 mse=0.1018 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.25970458984375, "reserved_gb": 2.880859375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "49", "gpu_mem_used_mb": "3443", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "66.38"}
2026-08-09 14:30:19 | INFO | train task=Ses05M epoch=3 batch=2136/2330 step=1700 loss=0.7132 ce=0.6607 mse=0.1051 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2587833404541016, "reserved_gb": 2.880859375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "3443", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "89.27"}
2026-08-09 14:30:46 | INFO | train task=Ses05M epoch=3 batch=2236/2330 step=1725 loss=1.8477 ce=1.7873 mse=0.1209 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.263880729675293, "reserved_gb": 2.9296875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "65", "gpu_mem_used_mb": "3493", "gpu_mem_total_mb": "12288", "gpu_temp_c": "53", "gpu_power_w": "96.34"}

predict:   0%|          | 0/312 [00:00<?, ?it/s]

2026-08-09 14:31:31 | INFO | Epoch 03 task=Ses05M train_loss=1.2502 val_macro_f1=0.5255 val_mae=0.4957 epoch_seconds=554.7

epoch 4:   0%|          | 0/2330 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 14:31:37 | INFO | train task=Ses05M epoch=4 batch=4/2330 step=1750 loss=0.2954 ce=0.1531 mse=0.2845 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1391148567199707, "reserved_gb": 1.83203125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "26", "gpu_mem_used_mb": "2369", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "52.52"}
2026-08-09 14:31:59 | INFO | train task=Ses05M epoch=4 batch=104/2330 step=1775 loss=0.8565 ce=0.5410 mse=0.6309 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1380953788757324, "reserved_gb": 1.83984375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "33", "gpu_mem_used_mb": "2377", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "54.82"}
2026-08-09 14:32:18 | INFO | train task=Ses05M epoch=4 batch=204/2330 step=1800 loss=0.9527 ce=0.8200 mse=0.2656 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1407670974731445, "reserved_gb": 1.970703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "2511", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "60.07"}
2026-08-09 14:32:41 | INFO | train task=Ses05M epoch=4 batch=304/2330 step=1825 loss=0.7159 ce=0.2966 mse=0.8386 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1385269165039062, "reserved_gb": 1.828125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "49", "gpu_mem_used_mb": "2365", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "52.92"}
2026-08-09 14:33:02 | INFO | train task=Ses05M epoch=4 batch=404/2330 step=1850 loss=2.0616 ce=1.7906 mse=0.5420 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.13997220993042, "reserved_gb": 2.025390625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "35", "gpu_mem_used_mb": "2567", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "63.27"}
2026-08-09 14:33:21 | INFO | train task=Ses05M epoch=4 batch=504/2330 step=1875 loss=0.7518 ce=0.2800 mse=0.9436 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1380605697631836, "reserved_gb": 1.748046875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "2283", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "62.53"}
2026-08-09 14:33:41 | INFO | train task=Ses05M epoch=4 batch=604/2330 step=1900 loss=0.0932 ce=0.0863 mse=0.0137 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.143376350402832, "reserved_gb": 2.466796875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "46", "gpu_mem_used_mb": "3019", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "54.19"}
2026-08-09 14:34:04 | INFO | train task=Ses05M epoch=4 batch=704/2330 step=1925 loss=0.7252 ce=0.6215 mse=0.2075 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1379404067993164, "reserved_gb": 1.880859375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "29", "gpu_mem_used_mb": "2419", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "68.56"}
2026-08-09 14:34:24 | INFO | train task=Ses05M epoch=4 batch=804/2330 step=1950 loss=0.5159 ce=0.2560 mse=0.5198 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1393847465515137, "reserved_gb": 1.705078125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "41", "gpu_mem_used_mb": "2239", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "69.91"}
2026-08-09 14:34:44 | INFO | train task=Ses05M epoch=4 batch=904/2330 step=1975 loss=0.3828 ce=0.2892 mse=0.1873 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1397557258605957, "reserved_gb": 1.908203125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "31", "gpu_mem_used_mb": "2447", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "78.33"}
2026-08-09 14:35:06 | INFO | train task=Ses05M epoch=4 batch=1004/2330 step=2000 loss=0.6628 ce=0.3289 mse=0.6677 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1384544372558594, "reserved_gb": 1.74609375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "30", "gpu_mem_used_mb": "2281", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "110.22"}
2026-08-09 14:35:31 | INFO | train task=Ses05M epoch=4 batch=1104/2330 step=2025 loss=1.5476 ce=1.1169 mse=0.8614 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1389036178588867, "reserved_gb": 1.955078125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "43", "gpu_mem_used_mb": "2495", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "70.17"}
2026-08-09 14:35:51 | INFO | train task=Ses05M epoch=4 batch=1204/2330 step=2050 loss=0.7100 ce=0.1203 mse=1.1795 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1388969421386719, "reserved_gb": 1.8125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "14", "gpu_mem_used_mb": "2349", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "89.09"}
2026-08-09 14:36:13 | INFO | train task=Ses05M epoch=4 batch=1304/2330 step=2075 loss=1.7586 ce=1.6479 mse=0.2213 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1383695602416992, "reserved_gb": 1.8125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "18", "gpu_mem_used_mb": "2349", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "88.55"}
2026-08-09 14:36:34 | INFO | train task=Ses05M epoch=4 batch=1404/2330 step=2100 loss=0.3027 ce=0.2748 mse=0.0558 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1409382820129395, "reserved_gb": 2.083984375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "24", "gpu_mem_used_mb": "2627", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "78.24"}
2026-08-09 14:36:59 | INFO | train task=Ses05M epoch=4 batch=1504/2330 step=2125 loss=1.3383 ce=1.0626 mse=0.5514 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1381306648254395, "reserved_gb": 1.697265625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "2231", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "68.91"}
2026-08-09 14:37:20 | INFO | train task=Ses05M epoch=4 batch=1604/2330 step=2150 loss=0.9942 ce=0.9045 mse=0.1794 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1394081115722656, "reserved_gb": 1.705078125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "16", "gpu_mem_used_mb": "2239", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "84.09"}
2026-08-09 14:37:42 | INFO | train task=Ses05M epoch=4 batch=1704/2330 step=2175 loss=1.3132 ce=1.2168 mse=0.1928 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.140078067779541, "reserved_gb": 1.91015625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "18", "gpu_mem_used_mb": "2449", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "87.98"}
2026-08-09 14:38:05 | INFO | train task=Ses05M epoch=4 batch=1804/2330 step=2200 loss=1.1561 ce=1.1421 mse=0.0280 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.138094425201416, "reserved_gb": 1.9609375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "19", "gpu_mem_used_mb": "2501", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "67.12"}
2026-08-09 14:38:30 | INFO | train task=Ses05M epoch=4 batch=1904/2330 step=2225 loss=1.9706 ce=1.9017 mse=0.1377 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1378731727600098, "reserved_gb": 1.73828125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "47", "gpu_mem_used_mb": "2273", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "82.08"}
2026-08-09 14:38:54 | INFO | train task=Ses05M epoch=4 batch=2004/2330 step=2250 loss=0.2898 ce=0.1487 mse=0.2823 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.138561725616455, "reserved_gb": 1.775390625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "75", "gpu_mem_used_mb": "2311", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "82.22"}
2026-08-09 14:39:16 | INFO | train task=Ses05M epoch=4 batch=2104/2330 step=2275 loss=0.3297 ce=0.2406 mse=0.1781 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1391191482543945, "reserved_gb": 1.833984375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "27", "gpu_mem_used_mb": "2371", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "71.32"}
2026-08-09 14:39:39 | INFO | train task=Ses05M epoch=4 batch=2204/2330 step=2300 loss=1.7519 ce=1.2225 mse=1.0588 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1378870010375977, "reserved_gb": 1.943359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "33", "gpu_mem_used_mb": "2483", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "75.80"}
2026-08-09 14:40:07 | INFO | train task=Ses05M epoch=4 batch=2304/2330 step=2325 loss=0.8713 ce=0.3678 mse=1.0070 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.138260841369629, "reserved_gb": 1.724609375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "2259", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "82.05"}

predict:   0%|          | 0/312 [00:00<?, ?it/s]

2026-08-09 14:40:33 | INFO | Epoch 04 task=Ses05M train_loss=1.0851 val_macro_f1=0.5364 val_mae=0.5143 epoch_seconds=537.9

epoch 5:   0%|          | 0/2330 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 14:40:51 | INFO | train task=Ses05M epoch=5 batch=72/2330 step=2350 loss=2.0832 ce=1.5796 mse=1.0072 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1387548446655273, "reserved_gb": 1.943359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "25", "gpu_mem_used_mb": "2483", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "66.07"}
2026-08-09 14:41:12 | INFO | train task=Ses05M epoch=5 batch=172/2330 step=2375 loss=1.1422 ce=0.6848 mse=0.9148 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.138634204864502, "reserved_gb": 2.041015625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "24", "gpu_mem_used_mb": "2583", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "59.58"}
2026-08-09 14:41:32 | INFO | train task=Ses05M epoch=5 batch=272/2330 step=2400 loss=0.7016 ce=0.6997 mse=0.0038 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.138167381286621, "reserved_gb": 1.845703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "29", "gpu_mem_used_mb": "2383", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "58.26"}
2026-08-09 14:41:56 | INFO | train task=Ses05M epoch=5 batch=372/2330 step=2425 loss=0.9555 ce=0.8834 mse=0.1442 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1386594772338867, "reserved_gb": 1.796875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "57", "gpu_mem_used_mb": "2333", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "84.51"}
2026-08-09 14:42:17 | INFO | train task=Ses05M epoch=5 batch=472/2330 step=2450 loss=1.8621 ce=1.2838 mse=1.1566 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1384878158569336, "reserved_gb": 1.87109375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "35", "gpu_mem_used_mb": "2409", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "70.16"}
2026-08-09 14:42:37 | INFO | train task=Ses05M epoch=5 batch=572/2330 step=2475 loss=0.7975 ce=0.6013 mse=0.3926 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1384334564208984, "reserved_gb": 1.744140625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "60", "gpu_mem_used_mb": "2279", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "74.82"}
2026-08-09 14:42:57 | INFO | train task=Ses05M epoch=5 batch=672/2330 step=2500 loss=0.6047 ce=0.5203 mse=0.1689 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.138631820678711, "reserved_gb": 1.703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "48", "gpu_mem_used_mb": "2237", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "43.61"}
2026-08-09 14:43:20 | INFO | train task=Ses05M epoch=5 batch=772/2330 step=2525 loss=0.1846 ce=0.1793 mse=0.0106 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.140425682067871, "reserved_gb": 1.931640625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "28", "gpu_mem_used_mb": "2471", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "70.28"}
2026-08-09 14:43:40 | INFO | train task=Ses05M epoch=5 batch=872/2330 step=2550 loss=0.6912 ce=0.4253 mse=0.5317 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1382341384887695, "reserved_gb": 1.724609375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "23", "gpu_mem_used_mb": "2259", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "70.08"}
2026-08-09 14:44:01 | INFO | train task=Ses05M epoch=5 batch=972/2330 step=2575 loss=0.1016 ce=0.0559 mse=0.0913 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1395072937011719, "reserved_gb": 1.859375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "18", "gpu_mem_used_mb": "2397", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "68.83"}
2026-08-09 14:44:23 | INFO | train task=Ses05M epoch=5 batch=1072/2330 step=2600 loss=0.6013 ce=0.2414 mse=0.7197 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1382384300231934, "reserved_gb": 1.912109375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "47", "gpu_mem_used_mb": "2451", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "94.76"}
2026-08-09 14:44:46 | INFO | train task=Ses05M epoch=5 batch=1172/2330 step=2625 loss=1.9702 ce=1.8568 mse=0.2269 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1378846168518066, "reserved_gb": 1.73046875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "14", "gpu_mem_used_mb": "2265", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "76.41"}
2026-08-09 14:45:08 | INFO | train task=Ses05M epoch=5 batch=1272/2330 step=2650 loss=0.4689 ce=0.4096 mse=0.1185 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1382732391357422, "reserved_gb": 1.72265625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "2257", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "66.81"}
2026-08-09 14:45:30 | INFO | train task=Ses05M epoch=5 batch=1372/2330 step=2675 loss=0.7457 ce=0.6603 mse=0.1708 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1390118598937988, "reserved_gb": 1.705078125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "64", "gpu_mem_used_mb": "2239", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "74.45"}
2026-08-09 14:45:51 | INFO | train task=Ses05M epoch=5 batch=1472/2330 step=2700 loss=3.6530 ce=3.5639 mse=0.1782 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1390204429626465, "reserved_gb": 1.703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "19", "gpu_mem_used_mb": "2237", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "72.07"}
2026-08-09 14:46:15 | INFO | train task=Ses05M epoch=5 batch=1572/2330 step=2725 loss=1.5895 ce=1.4131 mse=0.3528 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.137850284576416, "reserved_gb": 1.798828125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "30", "gpu_mem_used_mb": "2335", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "82.46"}
2026-08-09 14:46:39 | INFO | train task=Ses05M epoch=5 batch=1672/2330 step=2750 loss=1.5130 ce=1.2136 mse=0.5988 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1379685401916504, "reserved_gb": 1.685546875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "37", "gpu_mem_used_mb": "2219", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "85.44"}
2026-08-09 14:47:00 | INFO | train task=Ses05M epoch=5 batch=1772/2330 step=2775 loss=1.5915 ce=1.3433 mse=0.4965 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.13836669921875, "reserved_gb": 1.703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "2237", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "56.20"}
2026-08-09 14:47:22 | INFO | train task=Ses05M epoch=5 batch=1872/2330 step=2800 loss=0.2636 ce=0.1234 mse=0.2802 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1399378776550293, "reserved_gb": 1.744140625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "32", "gpu_mem_used_mb": "2279", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "63.02"}
2026-08-09 14:47:45 | INFO | train task=Ses05M epoch=5 batch=1972/2330 step=2825 loss=0.3716 ce=0.1584 mse=0.4263 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1387057304382324, "reserved_gb": 1.767578125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "26", "gpu_mem_used_mb": "2303", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "69.64"}
2026-08-09 14:48:07 | INFO | train task=Ses05M epoch=5 batch=2072/2330 step=2850 loss=0.3780 ce=0.1046 mse=0.5468 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.139721393585205, "reserved_gb": 1.888671875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "28", "gpu_mem_used_mb": "2427", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "71.29"}
2026-08-09 14:48:29 | INFO | train task=Ses05M epoch=5 batch=2172/2330 step=2875 loss=0.6127 ce=0.3658 mse=0.4936 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.139112949371338, "reserved_gb": 1.857421875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "16", "gpu_mem_used_mb": "2395", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "72.50"}
2026-08-09 14:48:54 | INFO | train task=Ses05M epoch=5 batch=2272/2330 step=2900 loss=0.4509 ce=0.2270 mse=0.4478 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.140803337097168, "reserved_gb": 1.91015625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "18", "gpu_mem_used_mb": "2449", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "85.78"}

predict:   0%|          | 0/312 [00:00<?, ?it/s]

2026-08-09 14:49:28 | INFO | Epoch 05 task=Ses05M train_loss=0.9534 val_macro_f1=0.5333 val_mae=0.5077 epoch_seconds=530.4

epoch 6:   0%|          | 0/2330 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
2026-08-09 14:49:39 | INFO | train task=Ses05M epoch=6 batch=40/2330 step=2925 loss=0.7600 ce=0.4747 mse=0.5708 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1383495330810547, "reserved_gb": 1.791015625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "2327", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "66.63"}
2026-08-09 14:49:58 | INFO | train task=Ses05M epoch=6 batch=140/2330 step=2950 loss=1.2191 ce=1.2189 mse=0.0004 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.143376350402832, "reserved_gb": 2.19921875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "36", "gpu_mem_used_mb": "2745", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "78.29"}
2026-08-09 14:50:18 | INFO | train task=Ses05M epoch=6 batch=240/2330 step=2975 loss=0.2012 ce=0.1363 mse=0.1298 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1381850242614746, "reserved_gb": 1.69921875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "16", "gpu_mem_used_mb": "2233", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "61.19"}
2026-08-09 14:50:39 | INFO | train task=Ses05M epoch=6 batch=340/2330 step=3000 loss=0.5972 ce=0.3585 mse=0.4774 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1384334564208984, "reserved_gb": 1.794921875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "24", "gpu_mem_used_mb": "2331", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "67.63"}
2026-08-09 14:51:00 | INFO | train task=Ses05M epoch=6 batch=440/2330 step=3025 loss=2.1231 ce=1.9675 mse=0.3113 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1380963325500488, "reserved_gb": 1.859375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "25", "gpu_mem_used_mb": "2397", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "69.82"}
2026-08-09 14:51:22 | INFO | train task=Ses05M epoch=6 batch=540/2330 step=3050 loss=0.5862 ce=0.5057 mse=0.1610 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1383023262023926, "reserved_gb": 1.900390625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "26", "gpu_mem_used_mb": "2439", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "82.68"}
2026-08-09 14:51:43 | INFO | train task=Ses05M epoch=6 batch=640/2330 step=3075 loss=0.8038 ce=0.1535 mse=1.3007 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.139472484588623, "reserved_gb": 1.939453125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "35", "gpu_mem_used_mb": "2479", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "64.26"}
2026-08-09 14:52:04 | INFO | train task=Ses05M epoch=6 batch=740/2330 step=3100 loss=0.8493 ce=0.1885 mse=1.3216 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1393442153930664, "reserved_gb": 1.779296875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "36", "gpu_mem_used_mb": "2315", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "72.44"}
2026-08-09 14:52:26 | INFO | train task=Ses05M epoch=6 batch=840/2330 step=3125 loss=0.6095 ce=0.4744 mse=0.2702 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1388030052185059, "reserved_gb": 1.701171875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "41", "gpu_mem_used_mb": "2235", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "76.72"}
2026-08-09 14:52:48 | INFO | train task=Ses05M epoch=6 batch=940/2330 step=3150 loss=0.3897 ce=0.3312 mse=0.1169 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.138071060180664, "reserved_gb": 1.705078125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "2239", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "51.42"}
2026-08-09 14:53:08 | INFO | train task=Ses05M epoch=6 batch=1040/2330 step=3175 loss=0.4493 ce=0.1962 mse=0.5062 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1383376121520996, "reserved_gb": 1.80078125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "32", "gpu_mem_used_mb": "2337", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "58.12"}
2026-08-09 14:53:28 | INFO | train task=Ses05M epoch=6 batch=1140/2330 step=3200 loss=1.8009 ce=1.0048 mse=1.5924 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1385278701782227, "reserved_gb": 1.77734375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "42", "gpu_mem_used_mb": "2313", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "73.71"}
2026-08-09 14:53:52 | INFO | train task=Ses05M epoch=6 batch=1240/2330 step=3225 loss=0.5888 ce=0.3821 mse=0.4134 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1380553245544434, "reserved_gb": 1.755859375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "48", "gpu_mem_used_mb": "2291", "gpu_mem_total_mb": "12288", "gpu_temp_c": "53", "gpu_power_w": "79.35"}
2026-08-09 14:54:13 | INFO | train task=Ses05M epoch=6 batch=1340/2330 step=3250 loss=0.7900 ce=0.2917 mse=0.9967 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1380295753479004, "reserved_gb": 1.724609375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "37", "gpu_mem_used_mb": "2259", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "41.31"}
2026-08-09 14:54:34 | INFO | train task=Ses05M epoch=6 batch=1440/2330 step=3275 loss=2.7690 ce=2.3518 mse=0.8345 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.137948989868164, "reserved_gb": 1.8359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "2373", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "71.76"}
2026-08-09 14:54:54 | INFO | train task=Ses05M epoch=6 batch=1540/2330 step=3300 loss=0.2154 ce=0.1754 mse=0.0800 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1395931243896484, "reserved_gb": 2.12109375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "54", "gpu_mem_used_mb": "2665", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "52.23"}
2026-08-09 14:55:19 | INFO | train task=Ses05M epoch=6 batch=1640/2330 step=3325 loss=0.2744 ce=0.0919 mse=0.3651 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1383023262023926, "reserved_gb": 1.890625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "16", "gpu_mem_used_mb": "2429", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "66.08"}
2026-08-09 14:55:40 | INFO | train task=Ses05M epoch=6 batch=1740/2330 step=3350 loss=0.9102 ce=0.4456 mse=0.9292 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1378345489501953, "reserved_gb": 2.208984375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "16", "gpu_mem_used_mb": "2755", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "67.11"}
2026-08-09 14:56:03 | INFO | train task=Ses05M epoch=6 batch=1840/2330 step=3375 loss=0.5930 ce=0.5742 mse=0.0375 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1394052505493164, "reserved_gb": 1.892578125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "2431", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "65.24"}
2026-08-09 14:56:28 | INFO | train task=Ses05M epoch=6 batch=1940/2330 step=3400 loss=0.3974 ce=0.0622 mse=0.6704 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1476020812988281, "reserved_gb": 2.57421875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "38", "gpu_mem_used_mb": "3129", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "100.09"}
2026-08-09 14:56:52 | INFO | train task=Ses05M epoch=6 batch=2040/2330 step=3425 loss=0.4107 ce=0.3518 mse=0.1179 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1407933235168457, "reserved_gb": 1.923828125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "19", "gpu_mem_used_mb": "2463", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "65.82"}
2026-08-09 14:57:16 | INFO | train task=Ses05M epoch=6 batch=2140/2330 step=3450 loss=0.3162 ce=0.1178 mse=0.3968 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1380014419555664, "reserved_gb": 1.689453125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "12", "gpu_mem_used_mb": "2223", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "78.94"}
2026-08-09 14:57:40 | INFO | train task=Ses05M epoch=6 batch=2240/2330 step=3475 loss=0.4541 ce=0.1844 mse=0.5393 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1385316848754883, "reserved_gb": 1.748046875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "30", "gpu_mem_used_mb": "2283", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "71.80"}

predict:   0%|          | 0/312 [00:00<?, ?it/s]

2026-08-09 14:58:20 | INFO | Epoch 06 task=Ses05M train_loss=0.8436 val_macro_f1=0.5311 val_mae=0.5128 epoch_seconds=529.0

predict:   0%|          | 0/300 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)

predict:   0%|          | 0/442 [00:00<?, ?it/s]

C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.pin_memory() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:48.)
  return data.pin_memory(device)
C:\Users\HaseebWajid\AppData\Local\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\pin_memory.py:57: DeprecationWarning: The argument 'device' of Tensor.is_pinned() is deprecated. Please do not pass this argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Memory.cpp:33.)
  return data.pin_memory(device)
2026-08-09 15:00:12 | INFO | Task 8be8e78c11f179a4_main_fold -> complete
2026-08-09 15:00:13 | INFO | Manuscript outputs refreshed: 21 tables, 4 figures
2026-08-09 15:00:15 | INFO | Manuscript outputs refreshed: 21 tables, 4 figures

,kind,fold,seed,status,error,direction
0,main_fold,Ses01F,13,complete_cached,NaN,NaN
1,degradation,Ses01F,13,complete_cached,NaN,NaN
2,fusion_ablation,Ses01F,13,complete_cached,NaN,NaN
3,modality_degradation,Ses01F,13,complete_cached,NaN,NaN
4,regression_ablation,Ses01F,13,complete,NaN,NaN
5,encoder_ablation,Ses01F,13,failed,ValueError('Input contains NaN.'),NaN
6,context,Ses01F,13,complete,NaN,NaN
7,cross,NaN,13,blocked_missing_msp,NaN,iemocap_to_msp
8,cross,NaN,13,blocked_missing_msp,NaN,msp_to_iemocap
9,main_fold,Ses01M,13,complete,NaN,NaN
10,main_fold,Ses02F,13,complete,NaN,NaN
11,main_fold,Ses02M,13,complete,NaN,NaN
12,main_fold,Ses03F,13,complete,NaN,NaN
13,main_fold,Ses03M,13,complete,NaN,NaN
14,main_fold,Ses04F,13,complete,NaN,NaN
15,main_fold,Ses04M,13,complete,NaN,NaN
16,main_fold,Ses05F,13,complete,NaN,NaN
17,main_fold,Ses05M,13,complete,NaN,NaN
18,main_fold,Ses01F,29,complete,NaN,NaN
19,main_fold,Ses03M,29,complete,NaN,NaN
20,main_fold,Ses05M,29,complete,NaN,NaN
21,main_fold,Ses01F,47,complete,NaN,NaN
22,main_fold,Ses03M,47,complete,NaN,NaN
23,main_fold,Ses05M,47,complete,NaN,NaN

2026-08-09 15:00:16 | INFO | Manuscript outputs refreshed: 21 tables, 4 figures

{'tables': ['C:\\Users\\HaseebWajid\\Downloads\\runs\\dersx_paper_aligned\\campaign_01\\paper_tables\\table_01_corpus_roles.csv',
  'C:\\Users\\HaseebWajid\\Downloads\\runs\\dersx_paper_aligned\\campaign_01\\paper_tables\\table_02_dataset_statistics.csv',
  'C:\\Users\\HaseebWajid\\Downloads\\runs\\dersx_paper_aligned\\campaign_01\\paper_tables\\table_03_class_distribution.csv',
  'C:\\Users\\HaseebWajid\\Downloads\\runs\\dersx_paper_aligned\\campaign_01\\paper_tables\\table_05_foldwise_loso.csv',
  'C:\\Users\\HaseebWajid\\Downloads\\runs\\dersx_paper_aligned\\campaign_01\\paper_tables\\table_04_fold_average_summary.csv',
  'C:\\Users\\HaseebWajid\\Downloads\\runs\\dersx_paper_aligned\\campaign_01\\paper_tables\\table_06_seedwise_summary.csv',
  'C:\\Users\\HaseebWajid\\Downloads\\runs\\dersx_paper_aligned\\campaign_01\\paper_tables\\table_04_pooled_main_summary.csv',
  'C:\\Users\\HaseebWajid\\Downloads\\runs\\dersx_paper_aligned\\campaign_01\\paper_tables\\table_07_regression_utterance_dialog.csv',
  'C:\\Users\\HaseebWajid\\Downloads\\runs\\dersx_paper_aligned\\campaign_01\\paper_tables\\table_08_binned_distress.csv',
  'C:\\Users\\HaseebWajid\\Downloads\\runs\\dersx_paper_aligned\\campaign_01\\paper_tables\\table_11_pooled_emotion_classwise.csv',
  'C:\\Users\\HaseebWajid\\Downloads\\runs\\dersx_paper_aligned\\campaign_01\\paper_tables\\table_10_temperature_calibration.csv',
  'C:\\Users\\HaseebWajid\\Downloads\\runs\\dersx_paper_aligned\\campaign_01\\paper_tables\\table_09_modality_comparison.csv',
  'C:\\Users\\HaseebWajid\\Downloads\\runs\\dersx_paper_aligned\\campaign_01\\paper_tables\\table_12_fusion_ablation.csv',
  'C:\\Users\\HaseebWajid\\Downloads\\runs\\dersx_paper_aligned\\campaign_01\\paper_tables\\table_13_regression_head_ablation.csv',
  'C:\\Users\\HaseebWajid\\Downloads\\runs\\dersx_paper_aligned\\campaign_01\\paper_tables\\table_14_encoder_ablation.csv',
  'C:\\Users\\HaseebWajid\\Downloads\\runs\\dersx_paper_aligned\\campaign_01\\paper_tables\\table_15_context_ablation.csv',
  'C:\\Users\\HaseebWajid\\Downloads\\runs\\dersx_paper_aligned\\campaign_01\\paper_tables\\table_16_literature_context.csv',
  'C:\\Users\\HaseebWajid\\Downloads\\runs\\dersx_paper_aligned\\campaign_01\\paper_tables\\table_19_acoustic_channel_degradation.csv',
  'C:\\Users\\HaseebWajid\\Downloads\\runs\\dersx_paper_aligned\\campaign_01\\paper_tables\\table_20_transcript_wer_degradation.csv',
  'C:\\Users\\HaseebWajid\\Downloads\\runs\\dersx_paper_aligned\\campaign_01\\paper_tables\\table_21_combined_degradation.csv',
  'C:\\Users\\HaseebWajid\\Downloads\\runs\\dersx_paper_aligned\\campaign_01\\paper_tables\\table_22_modality_under_degradation.csv'],
 'figures': ['C:\\Users\\HaseebWajid\\Downloads\\runs\\dersx_paper_aligned\\campaign_01\\paper_figures\\figure_01_modality_fusion.png',
  'C:\\Users\\HaseebWajid\\Downloads\\runs\\dersx_paper_aligned\\campaign_01\\paper_figures\\figure_03_degradation_curve.png',
  'C:\\Users\\HaseebWajid\\Downloads\\runs\\dersx_paper_aligned\\campaign_01\\paper_figures\\figure_04_attention_shift.png',
  'C:\\Users\\HaseebWajid\\Downloads\\runs\\dersx_paper_aligned\\campaign_01\\paper_figures\\figure_05_modality_degradation.png']}

## 22. Show live logs and generated outputs

The log tail is real output from this campaign. It is not a fabricated example. Experimental scores appear only after the corresponding prediction files exist.

In [26]:
def show_log_tail(n:int=80) -> None:
    if LOG_PATH.exists():
        lines=LOG_PATH.read_text(encoding="utf-8",errors="ignore").splitlines()
        print("\n".join(lines[-n:]))

def list_generated_results() -> pd.DataFrame:
    rows=[]
    for p in RUN_DIR.rglob("*"):
        if p.is_file() and p.suffix.lower() in {".json",".csv",".md",".log",".pt",".pkl",".png",".ipynb"}:
            rows.append({"path":str(p.relative_to(RUN_DIR)),"size_mb":p.stat().st_size/2**20,"modified":time.strftime("%Y-%m-%d %H:%M:%S",time.localtime(p.stat().st_mtime))})
    return pd.DataFrame(rows).sort_values("path") if rows else pd.DataFrame(columns=["path","size_mb","modified"])

show_log_tail()
display(list_generated_results())
print("Report:", generate_progress_report())
print("Remaining campaign hours:", budget.remaining_seconds/3600)

print("Generated manuscript outputs:", safe_generate_manuscript_outputs(IEMOCAP_DF, MSP_DF))

2026-08-09 14:30:19 | INFO | train task=Ses05M epoch=3 batch=2136/2330 step=1700 loss=0.7132 ce=0.6607 mse=0.1051 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.2587833404541016, "reserved_gb": 2.880859375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "3443", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "89.27"}
2026-08-09 14:30:46 | INFO | train task=Ses05M epoch=3 batch=2236/2330 step=1725 loss=1.8477 ce=1.7873 mse=0.1209 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 2.263880729675293, "reserved_gb": 2.9296875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "65", "gpu_mem_used_mb": "3493", "gpu_mem_total_mb": "12288", "gpu_temp_c": "53", "gpu_power_w": "96.34"}
2026-08-09 14:31:31 | INFO | Epoch 03 task=Ses05M train_loss=1.2502 val_macro_f1=0.5255 val_mae=0.4957 epoch_seconds=554.7
2026-08-09 14:31:37 | INFO | train task=Ses05M epoch=4 batch=4/2330 step=1750 loss=0.2954 ce=0.1531 mse=0.2845 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1391148567199707, "reserved_gb": 1.83203125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "26", "gpu_mem_used_mb": "2369", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "52.52"}
2026-08-09 14:31:59 | INFO | train task=Ses05M epoch=4 batch=104/2330 step=1775 loss=0.8565 ce=0.5410 mse=0.6309 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1380953788757324, "reserved_gb": 1.83984375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "33", "gpu_mem_used_mb": "2377", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "54.82"}
2026-08-09 14:32:18 | INFO | train task=Ses05M epoch=4 batch=204/2330 step=1800 loss=0.9527 ce=0.8200 mse=0.2656 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1407670974731445, "reserved_gb": 1.970703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "2511", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "60.07"}
2026-08-09 14:32:41 | INFO | train task=Ses05M epoch=4 batch=304/2330 step=1825 loss=0.7159 ce=0.2966 mse=0.8386 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1385269165039062, "reserved_gb": 1.828125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "49", "gpu_mem_used_mb": "2365", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "52.92"}
2026-08-09 14:33:02 | INFO | train task=Ses05M epoch=4 batch=404/2330 step=1850 loss=2.0616 ce=1.7906 mse=0.5420 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.13997220993042, "reserved_gb": 2.025390625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "35", "gpu_mem_used_mb": "2567", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "63.27"}
2026-08-09 14:33:21 | INFO | train task=Ses05M epoch=4 batch=504/2330 step=1875 loss=0.7518 ce=0.2800 mse=0.9436 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1380605697631836, "reserved_gb": 1.748046875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "21", "gpu_mem_used_mb": "2283", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "62.53"}
2026-08-09 14:33:41 | INFO | train task=Ses05M epoch=4 batch=604/2330 step=1900 loss=0.0932 ce=0.0863 mse=0.0137 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.143376350402832, "reserved_gb": 2.466796875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "46", "gpu_mem_used_mb": "3019", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "54.19"}
2026-08-09 14:34:04 | INFO | train task=Ses05M epoch=4 batch=704/2330 step=1925 loss=0.7252 ce=0.6215 mse=0.2075 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1379404067993164, "reserved_gb": 1.880859375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "29", "gpu_mem_used_mb": "2419", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "68.56"}
2026-08-09 14:34:24 | INFO | train task=Ses05M epoch=4 batch=804/2330 step=1950 loss=0.5159 ce=0.2560 mse=0.5198 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1393847465515137, "reserved_gb": 1.705078125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "41", "gpu_mem_used_mb": "2239", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "69.91"}
2026-08-09 14:34:44 | INFO | train task=Ses05M epoch=4 batch=904/2330 step=1975 loss=0.3828 ce=0.2892 mse=0.1873 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1397557258605957, "reserved_gb": 1.908203125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "31", "gpu_mem_used_mb": "2447", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "78.33"}
2026-08-09 14:35:06 | INFO | train task=Ses05M epoch=4 batch=1004/2330 step=2000 loss=0.6628 ce=0.3289 mse=0.6677 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1384544372558594, "reserved_gb": 1.74609375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "30", "gpu_mem_used_mb": "2281", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "110.22"}
2026-08-09 14:35:31 | INFO | train task=Ses05M epoch=4 batch=1104/2330 step=2025 loss=1.5476 ce=1.1169 mse=0.8614 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1389036178588867, "reserved_gb": 1.955078125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "43", "gpu_mem_used_mb": "2495", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "70.17"}
2026-08-09 14:35:51 | INFO | train task=Ses05M epoch=4 batch=1204/2330 step=2050 loss=0.7100 ce=0.1203 mse=1.1795 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1388969421386719, "reserved_gb": 1.8125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "14", "gpu_mem_used_mb": "2349", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "89.09"}
2026-08-09 14:36:13 | INFO | train task=Ses05M epoch=4 batch=1304/2330 step=2075 loss=1.7586 ce=1.6479 mse=0.2213 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1383695602416992, "reserved_gb": 1.8125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "18", "gpu_mem_used_mb": "2349", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "88.55"}
2026-08-09 14:36:34 | INFO | train task=Ses05M epoch=4 batch=1404/2330 step=2100 loss=0.3027 ce=0.2748 mse=0.0558 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1409382820129395, "reserved_gb": 2.083984375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "24", "gpu_mem_used_mb": "2627", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "78.24"}
2026-08-09 14:36:59 | INFO | train task=Ses05M epoch=4 batch=1504/2330 step=2125 loss=1.3383 ce=1.0626 mse=0.5514 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1381306648254395, "reserved_gb": 1.697265625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "2231", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "68.91"}
2026-08-09 14:37:20 | INFO | train task=Ses05M epoch=4 batch=1604/2330 step=2150 loss=0.9942 ce=0.9045 mse=0.1794 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1394081115722656, "reserved_gb": 1.705078125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "16", "gpu_mem_used_mb": "2239", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "84.09"}
2026-08-09 14:37:42 | INFO | train task=Ses05M epoch=4 batch=1704/2330 step=2175 loss=1.3132 ce=1.2168 mse=0.1928 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.140078067779541, "reserved_gb": 1.91015625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "18", "gpu_mem_used_mb": "2449", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "87.98"}
2026-08-09 14:38:05 | INFO | train task=Ses05M epoch=4 batch=1804/2330 step=2200 loss=1.1561 ce=1.1421 mse=0.0280 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.138094425201416, "reserved_gb": 1.9609375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "19", "gpu_mem_used_mb": "2501", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "67.12"}
2026-08-09 14:38:30 | INFO | train task=Ses05M epoch=4 batch=1904/2330 step=2225 loss=1.9706 ce=1.9017 mse=0.1377 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1378731727600098, "reserved_gb": 1.73828125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "47", "gpu_mem_used_mb": "2273", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "82.08"}
2026-08-09 14:38:54 | INFO | train task=Ses05M epoch=4 batch=2004/2330 step=2250 loss=0.2898 ce=0.1487 mse=0.2823 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.138561725616455, "reserved_gb": 1.775390625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "75", "gpu_mem_used_mb": "2311", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "82.22"}
2026-08-09 14:39:16 | INFO | train task=Ses05M epoch=4 batch=2104/2330 step=2275 loss=0.3297 ce=0.2406 mse=0.1781 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1391191482543945, "reserved_gb": 1.833984375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "27", "gpu_mem_used_mb": "2371", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "71.32"}
2026-08-09 14:39:39 | INFO | train task=Ses05M epoch=4 batch=2204/2330 step=2300 loss=1.7519 ce=1.2225 mse=1.0588 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1378870010375977, "reserved_gb": 1.943359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "33", "gpu_mem_used_mb": "2483", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "75.80"}
2026-08-09 14:40:07 | INFO | train task=Ses05M epoch=4 batch=2304/2330 step=2325 loss=0.8713 ce=0.3678 mse=1.0070 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.138260841369629, "reserved_gb": 1.724609375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "2259", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "82.05"}
2026-08-09 14:40:33 | INFO | Epoch 04 task=Ses05M train_loss=1.0851 val_macro_f1=0.5364 val_mae=0.5143 epoch_seconds=537.9
2026-08-09 14:40:51 | INFO | train task=Ses05M epoch=5 batch=72/2330 step=2350 loss=2.0832 ce=1.5796 mse=1.0072 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1387548446655273, "reserved_gb": 1.943359375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "25", "gpu_mem_used_mb": "2483", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "66.07"}
2026-08-09 14:41:12 | INFO | train task=Ses05M epoch=5 batch=172/2330 step=2375 loss=1.1422 ce=0.6848 mse=0.9148 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.138634204864502, "reserved_gb": 2.041015625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "24", "gpu_mem_used_mb": "2583", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "59.58"}
2026-08-09 14:41:32 | INFO | train task=Ses05M epoch=5 batch=272/2330 step=2400 loss=0.7016 ce=0.6997 mse=0.0038 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.138167381286621, "reserved_gb": 1.845703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "29", "gpu_mem_used_mb": "2383", "gpu_mem_total_mb": "12288", "gpu_temp_c": "47", "gpu_power_w": "58.26"}
2026-08-09 14:41:56 | INFO | train task=Ses05M epoch=5 batch=372/2330 step=2425 loss=0.9555 ce=0.8834 mse=0.1442 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1386594772338867, "reserved_gb": 1.796875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "57", "gpu_mem_used_mb": "2333", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "84.51"}
2026-08-09 14:42:17 | INFO | train task=Ses05M epoch=5 batch=472/2330 step=2450 loss=1.8621 ce=1.2838 mse=1.1566 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1384878158569336, "reserved_gb": 1.87109375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "35", "gpu_mem_used_mb": "2409", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "70.16"}
2026-08-09 14:42:37 | INFO | train task=Ses05M epoch=5 batch=572/2330 step=2475 loss=0.7975 ce=0.6013 mse=0.3926 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1384334564208984, "reserved_gb": 1.744140625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "60", "gpu_mem_used_mb": "2279", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "74.82"}
2026-08-09 14:42:57 | INFO | train task=Ses05M epoch=5 batch=672/2330 step=2500 loss=0.6047 ce=0.5203 mse=0.1689 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.138631820678711, "reserved_gb": 1.703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "48", "gpu_mem_used_mb": "2237", "gpu_mem_total_mb": "12288", "gpu_temp_c": "46", "gpu_power_w": "43.61"}
2026-08-09 14:43:20 | INFO | train task=Ses05M epoch=5 batch=772/2330 step=2525 loss=0.1846 ce=0.1793 mse=0.0106 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.140425682067871, "reserved_gb": 1.931640625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "28", "gpu_mem_used_mb": "2471", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "70.28"}
2026-08-09 14:43:40 | INFO | train task=Ses05M epoch=5 batch=872/2330 step=2550 loss=0.6912 ce=0.4253 mse=0.5317 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1382341384887695, "reserved_gb": 1.724609375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "23", "gpu_mem_used_mb": "2259", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "70.08"}
2026-08-09 14:44:01 | INFO | train task=Ses05M epoch=5 batch=972/2330 step=2575 loss=0.1016 ce=0.0559 mse=0.0913 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1395072937011719, "reserved_gb": 1.859375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "18", "gpu_mem_used_mb": "2397", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "68.83"}
2026-08-09 14:44:23 | INFO | train task=Ses05M epoch=5 batch=1072/2330 step=2600 loss=0.6013 ce=0.2414 mse=0.7197 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1382384300231934, "reserved_gb": 1.912109375, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "47", "gpu_mem_used_mb": "2451", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "94.76"}
2026-08-09 14:44:46 | INFO | train task=Ses05M epoch=5 batch=1172/2330 step=2625 loss=1.9702 ce=1.8568 mse=0.2269 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1378846168518066, "reserved_gb": 1.73046875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "14", "gpu_mem_used_mb": "2265", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "76.41"}
2026-08-09 14:45:08 | INFO | train task=Ses05M epoch=5 batch=1272/2330 step=2650 loss=0.4689 ce=0.4096 mse=0.1185 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1382732391357422, "reserved_gb": 1.72265625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "20", "gpu_mem_used_mb": "2257", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "66.81"}
2026-08-09 14:45:30 | INFO | train task=Ses05M epoch=5 batch=1372/2330 step=2675 loss=0.7457 ce=0.6603 mse=0.1708 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1390118598937988, "reserved_gb": 1.705078125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "64", "gpu_mem_used_mb": "2239", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "74.45"}
2026-08-09 14:45:51 | INFO | train task=Ses05M epoch=5 batch=1472/2330 step=2700 loss=3.6530 ce=3.5639 mse=0.1782 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1390204429626465, "reserved_gb": 1.703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "19", "gpu_mem_used_mb": "2237", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "72.07"}
2026-08-09 14:46:15 | INFO | train task=Ses05M epoch=5 batch=1572/2330 step=2725 loss=1.5895 ce=1.4131 mse=0.3528 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.137850284576416, "reserved_gb": 1.798828125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "30", "gpu_mem_used_mb": "2335", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "82.46"}
2026-08-09 14:46:39 | INFO | train task=Ses05M epoch=5 batch=1672/2330 step=2750 loss=1.5130 ce=1.2136 mse=0.5988 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1379685401916504, "reserved_gb": 1.685546875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "37", "gpu_mem_used_mb": "2219", "gpu_mem_total_mb": "12288", "gpu_temp_c": "51", "gpu_power_w": "85.44"}
2026-08-09 14:47:00 | INFO | train task=Ses05M epoch=5 batch=1772/2330 step=2775 loss=1.5915 ce=1.3433 mse=0.4965 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.13836669921875, "reserved_gb": 1.703125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "22", "gpu_mem_used_mb": "2237", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "56.20"}
2026-08-09 14:47:22 | INFO | train task=Ses05M epoch=5 batch=1872/2330 step=2800 loss=0.2636 ce=0.1234 mse=0.2802 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1399378776550293, "reserved_gb": 1.744140625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "32", "gpu_mem_used_mb": "2279", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "63.02"}
2026-08-09 14:47:45 | INFO | train task=Ses05M epoch=5 batch=1972/2330 step=2825 loss=0.3716 ce=0.1584 mse=0.4263 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1387057304382324, "reserved_gb": 1.767578125, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "26", "gpu_mem_used_mb": "2303", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "69.64"}
2026-08-09 14:48:07 | INFO | train task=Ses05M epoch=5 batch=2072/2330 step=2850 loss=0.3780 ce=0.1046 mse=0.5468 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.139721393585205, "reserved_gb": 1.888671875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "28", "gpu_mem_used_mb": "2427", "gpu_mem_total_mb": "12288", "gpu_temp_c": "52", "gpu_power_w": "71.29"}
2026-08-09 14:48:29 | INFO | train task=Ses05M epoch=5 batch=2172/2330 step=2875 loss=0.6127 ce=0.3658 mse=0.4936 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.139112949371338, "reserved_gb": 1.857421875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "16", "gpu_mem_used_mb": "2395", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "72.50"}
2026-08-09 14:48:54 | INFO | train task=Ses05M epoch=5 batch=2272/2330 step=2900 loss=0.4509 ce=0.2270 mse=0.4478 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.140803337097168, "reserved_gb": 1.91015625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "18", "gpu_mem_used_mb": "2449", "gpu_mem_total_mb": "12288", "gpu_temp_c": "50", "gpu_power_w": "85.78"}
2026-08-09 14:49:28 | INFO | Epoch 05 task=Ses05M train_loss=0.9534 val_macro_f1=0.5333 val_mae=0.5077 epoch_seconds=530.4
2026-08-09 14:49:39 | INFO | train task=Ses05M epoch=6 batch=40/2330 step=2925 loss=0.7600 ce=0.4747 mse=0.5708 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.1383495330810547, "reserved_gb": 1.791015625, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "17", "gpu_mem_used_mb": "2327", "gpu_mem_total_mb": "12288", "gpu_temp_c": "48", "gpu_power_w": "66.63"}
2026-08-09 14:49:58 | INFO | train task=Ses05M epoch=6 batch=140/2330 step=2950 loss=1.2191 ce=1.2189 mse=0.0004 gpu={"device": "NVIDIA GeForce RTX 3060", "allocated_gb": 1.143376350402832, "reserved_gb": 2.19921875, "max_allocated_gb": 10.124285221099854, "gpu_util_pct": "36", "gpu_mem_used_mb": "2745", "gpu_mem_total_mb": "12288", "gpu_temp_c": "49", "gpu_power_w": "78.29"}

,path,size_mb,modified
5,REPORT.md,0.019258,2026-08-09 15:00:13
9,ablations\context\seed_13\Ses01F\done.json,0.000472,2026-08-09 01:09:44
10,ablations\encoder\logmel_cnn\seed_13\Ses01F\ca...,0.023380,2026-08-08 23:58:31
11,ablations\encoder\logmel_cnn\seed_13\Ses01F\la...,14.527598,2026-08-09 00:56:05
12,ablations\encoder\logmel_cnn\seed_13\Ses01F\te...,0.028856,2026-08-08 23:58:31
...,...,...,...
398,paper_tables\table_21_combined_degradation.csv,0.005996,2026-08-09 15:00:15
399,paper_tables\table_22_modality_under_degradati...,0.012449,2026-08-09 15:00:15
6,run.log,1.195782,2026-08-09 15:00:16
7,self_tests.json,0.000149,2026-08-08 22:33:13
8,task_status.json,0.008118,2026-08-09 15:00:12

Report: C:\Users\HaseebWajid\Downloads\runs\dersx_paper_aligned\campaign_01\REPORT.md
Remaining campaign hours: 0.7625108331441879

2026-08-09 15:00:19 | INFO | Manuscript outputs refreshed: 21 tables, 4 figures

Generated manuscript outputs: {'tables': ['C:\\Users\\HaseebWajid\\Downloads\\runs\\dersx_paper_aligned\\campaign_01\\paper_tables\\table_01_corpus_roles.csv', 'C:\\Users\\HaseebWajid\\Downloads\\runs\\dersx_paper_aligned\\campaign_01\\paper_tables\\table_02_dataset_statistics.csv', 'C:\\Users\\HaseebWajid\\Downloads\\runs\\dersx_paper_aligned\\campaign_01\\paper_tables\\table_03_class_distribution.csv', 'C:\\Users\\HaseebWajid\\Downloads\\runs\\dersx_paper_aligned\\campaign_01\\paper_tables\\table_05_foldwise_loso.csv', 'C:\\Users\\HaseebWajid\\Downloads\\runs\\dersx_paper_aligned\\campaign_01\\paper_tables\\table_04_fold_average_summary.csv', 'C:\\Users\\HaseebWajid\\Downloads\\runs\\dersx_paper_aligned\\campaign_01\\paper_tables\\table_06_seedwise_summary.csv', 'C:\\Users\\HaseebWajid\\Downloads\\runs\\dersx_paper_aligned\\campaign_01\\paper_tables\\table_04_pooled_main_summary.csv', 'C:\\Users\\HaseebWajid\\Downloads\\runs\\dersx_paper_aligned\\campaign_01\\paper_tables\\table_07_regression_utterance_dialog.csv', 'C:\\Users\\HaseebWajid\\Downloads\\runs\\dersx_paper_aligned\\campaign_01\\paper_tables\\table_08_binned_distress.csv', 'C:\\Users\\HaseebWajid\\Downloads\\runs\\dersx_paper_aligned\\campaign_01\\paper_tables\\table_11_pooled_emotion_classwise.csv', 'C:\\Users\\HaseebWajid\\Downloads\\runs\\dersx_paper_aligned\\campaign_01\\paper_tables\\table_10_temperature_calibration.csv', 'C:\\Users\\HaseebWajid\\Downloads\\runs\\dersx_paper_aligned\\campaign_01\\paper_tables\\table_09_modality_comparison.csv', 'C:\\Users\\HaseebWajid\\Downloads\\runs\\dersx_paper_aligned\\campaign_01\\paper_tables\\table_12_fusion_ablation.csv', 'C:\\Users\\HaseebWajid\\Downloads\\runs\\dersx_paper_aligned\\campaign_01\\paper_tables\\table_13_regression_head_ablation.csv', 'C:\\Users\\HaseebWajid\\Downloads\\runs\\dersx_paper_aligned\\campaign_01\\paper_tables\\table_14_encoder_ablation.csv', 'C:\\Users\\HaseebWajid\\Downloads\\runs\\dersx_paper_aligned\\campaign_01\\paper_tables\\table_15_context_ablation.csv', 'C:\\Users\\HaseebWajid\\Downloads\\runs\\dersx_paper_aligned\\campaign_01\\paper_tables\\table_16_literature_context.csv', 'C:\\Users\\HaseebWajid\\Downloads\\runs\\dersx_paper_aligned\\campaign_01\\paper_tables\\table_19_acoustic_channel_degradation.csv', 'C:\\Users\\HaseebWajid\\Downloads\\runs\\dersx_paper_aligned\\campaign_01\\paper_tables\\table_20_transcript_wer_degradation.csv', 'C:\\Users\\HaseebWajid\\Downloads\\runs\\dersx_paper_aligned\\campaign_01\\paper_tables\\table_21_combined_degradation.csv', 'C:\\Users\\HaseebWajid\\Downloads\\runs\\dersx_paper_aligned\\campaign_01\\paper_tables\\table_22_modality_under_degradation.csv'], 'figures': ['C:\\Users\\HaseebWajid\\Downloads\\runs\\dersx_paper_aligned\\campaign_01\\paper_figures\\figure_01_modality_fusion.png', 'C:\\Users\\HaseebWajid\\Downloads\\runs\\dersx_paper_aligned\\campaign_01\\paper_figures\\figure_03_degradation_curve.png', 'C:\\Users\\HaseebWajid\\Downloads\\runs\\dersx_paper_aligned\\campaign_01\\paper_figures\\figure_04_attention_shift.png', 'C:\\Users\\HaseebWajid\\Downloads\\runs\\dersx_paper_aligned\\campaign_01\\paper_figures\\figure_05_modality_degradation.png']}